### ISSUE TITLE
code smells

### ISSUE THREAD

**Issue by chandrin** [OpenRefine/OpenRefine#1002]
Hello everyone !

I tried to detect some code smells in the project, just out of curiosity and i thought that some of the results i had may be useful to the community.
 I used the JDeodorant eclipse plugin to detect structures in the code that may indicate weaknesses in the design of the project.

First of all i detected some classes that use methods or fields of other classes excessively (feature envy).

One such notable example is method computeJoin in com.google.refine.InterProjectModel which JDeodorant suggests to be moved in com.google.refine.InterProjectModel.ProjectJoin

![envy_1](https://cloud.githubusercontent.com/assets/9272941/7564839/3b4400e0-f7f3-11e4-92b2-5d7629b05b16.png)

Another example is method internalVisit in com.google.refine.commands.row.GetRowsCommand.RowWritingVisitor which JDeodorant suggests to be moved in com.google.refine.model.Record

![envy_2](https://cloud.githubusercontent.com/assets/9272941/7564928/16f9525c-f7f4-11e4-91cc-002b4be4ddee.png)

The same goes for method internalVisit in com.google.refine.templating.Template.RowWritingVisitor
which JDeodorant suggests to be moved in com.google.refine.model.record

![envy_3](https://cloud.githubusercontent.com/assets/9272941/7565014/ffd70ed8-f7f4-11e4-8c39-0521f4b3cf21.png)

A last example of feature envy is method getBigIndex in com.google.refine.commands.column.GetColumnsInfoCommand with the target class being com.google.refine.model.Column

![envy_4](https://cloud.githubusercontent.com/assets/9272941/7565077/861255e8-f7f5-11e4-856a-0561732fee7a.png)

JDeodorant also detected some "God Classes" that do too much.
An example is class com.google.refine.browsing.util.TimeBinIndex and here is a suggestion to extract another class out of this one.

![goid_class_1b](https://cloud.githubusercontent.com/assets/9272941/7565191/8d575fa0-f7f6-11e4-89d2-d26f7a5fa455.png)

A similar "god class" is  com.google.refine.browsing.util.NumericBinIndex from which the following class could be extracted 

![god](https://cloud.githubusercontent.com/assets/9272941/7565237/241d949a-f7f7-11e4-9558-cfe2a815ab38.png)
and
![god](https://cloud.githubusercontent.com/assets/9272941/7565272/77604ecc-f7f7-11e4-8323-c028737e4ace.png)
JDeodorant also found other code smells, but i thought they were insignificant and just posted some of them.
Of course these are not bugs or anything like that and it might be better for the code to stay the way it is, but i just thought i should share these suggestions with you.

I hope these results prove to be useful for you, even by a little.

**Comment by thadguidry** [comment]
@wetneb Hmm, We might want to refactor in a few of these mentioned.  I'll leave it up to you as we progress this year in 2019 and depending on our time and budgets, of course.

**Comment by wetneb** [comment]
Some of these suggestions might make sense but it's hard to discuss them based on screenshots of the tool. It would be easier to discuss this in a pull request: feel free to pick the most natural refactorings suggested by the tool and submit them as a PR. Closing this otherwise.
