### ISSUE TITLE
Problems running on Windows 7 from a network share

### ISSUE THREAD

**Issue by jezcope** [OpenRefine/OpenRefine#1004]
When trying to run OpenRefine for the first time on Windows 7, I couldn't get it working.  All I could get was an `org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'macros.vm'` error, followed by a 404 error trying to access it from my browser ([full errors in this gist](https://gist.github.com/jezcope/3bf5525f32c51702f5ab)).

It seems like it doesn't like running from a network share (even if you've mapped it to a drive letter). I've found two workarounds for this.  The simplest, if you can, is to just extract OpenRefine onto a local hard drive (e.g. `C:`) and run it from there.

The alternative, if you can't access a local drive or prefer to keep everything on the network, is as follows:
1. If you haven't already, map the network share to a drive letter (my corporate IT environment uses `H:` for my home share, for example);
2. Open a command line by clicking the Start button, typing `cmd` into the search box and either hitting <enter> or clicking on the `cmd.exe` menu item that appears;
3. In the command line, navigate to wherever you have OR installed; this will involve:
   1. Selecting the drive you mapped before: type `H:` (or whichever letter you use) and hit `Enter`;
   2. Changing to the right directory: in my case, typing `cd "Data wrangling\openrefine-2.6-beta.1"` and hitting <enter> does the trick (the double quotes are required if the path has any spaces);
4. Start OR by typing `openrefine` and hitting <enter>;
5. Use OR through your browser as normal, and when you've finished, kill it by returning to the command line window (that should still be open) and pressing `Ctrl-C`.

This may well be something that's fixable in the distribution though.

**Comment by karawoo** [comment]
I've run into this problem as well on Windows 8. It would be great if OpenRefine could run from a network share. Due to a set of highly annoying factors I don't have privileges to move OpenRefine to the local hard drive, and I am teaching students who are not familiar with command line interfaces and would be scared off by having to run OpenRefine from the command prompt.

**Comment by simon1tan** [comment]
You don't have to run anything from the command line. Mapping a drive letter or starting OpenRefine can all be done in the GUI.

**Comment by jezcope** [comment]
It looks like this has never been resolved — I've just helped out a colleague who ran into the same problem. I don't even know why the UNC path doesn't work because I thought all the file access primitives in Windows worked with either that or a Local File System path.

WRT to @simon1tan's suggestion, sadly if you start OpenRefine by double-clicking `openrefine.bat`, Windows reports the UNC path instead of the (mapped) LFS path to the process as the working directory, which is why the error happens in the first place.

**Comment by thadguidry** [comment]
@jezcope you might try creating a shortcut and setting the "Start in" path as the network path.  Sorry, but we can't help more with this issue.  Try to ask Windows guru's on Stackoverflow, I'm sure they could help with a workaround somehow.
