### ISSUE TITLE
Google AuthSub permanently shut down

### ISSUE THREAD

**Issue by mrScott** [OpenRefine/OpenRefine#1008]
Google has changed the sign-in for third-party apps (https://support.google.com/a/answer/6217830?p=authsub&rd=1).  As a result I am unable to use spreadsheets stored on Google Drive.  I am not a developer.  I am a user.

I just downloaded OpenRefine v2.5.  Is there a newer release that allows for Google Drive sign-in?  If not will there be?  If not, what is the work-around?

**Comment by mtelesha** [comment]
mrScot your work around is that you can have Google Drive sync with your computer into a driver folder.  https://support.google.com/drive/answer/2375083?hl=en

**Comment by tfmorris** [comment]
There is no OpenRefine 2.5.  There was a Google Refine 2.5 and we have a release candidate for OpenRefine 2.6 rc1.  The problem you describe is fixed, I think in RC1, but if not, definitely in 2.6 RC2.
