### ISSUE TITLE
Cosmetic: Boolean return values from Jython are treated as integers

### ISSUE THREAD

**Issue by esiegerman** [OpenRefine/OpenRefine#1013]
If a Jython facet function returns Python _True_ or _False_, the facet offers choices _1_ or _0_ respectively.  That works, but isn't as nice as GREL boolean expressions, which the facet displays as _true_ and _false_.  (Being only one character long, it isn't as easy to click on, either...)

**Comment by jackyq2015** [comment]
I suggest to cast in explicitly like this:
return str(value=="2acdf11b911faba3183630de42a22a70";

To tweak the expression engine to change the default behavior of the Jython could lead to problem if you use it in other ways.
