### ISSUE TITLE
Jython variables

### ISSUE THREAD

**Issue by esiegerman** [OpenRefine/OpenRefine#1014]
`cells["foo"]["value"]` is rather more annoying to type than `cells.foo.value` (four times as many punctuation characters!).

Can the latter be made to work in Jython, as it does in GREL?

**Comment by jackyq2015** [comment]
Please check this:
http://stackoverflow.com/questions/16279212/how-to-use-dot-notation-for-dict-in-python

I believe that even upgrading the version of Jython to 2.7 won't have this feature.

**Comment by esiegerman** [comment]
I think I agree with [this answer](http://stackoverflow.com/a/16279450) in that thread -- as far as long-lived code is concerned.  But the little scripts one writes in OpenRefine are throwaway -- run once and forget (modulo the history feature of course :-) )

For those, the focus should be different: ease of typing (and reading in a small space, i.e. the facet's window) seems to me more important than long-term maintainability.

Besides, GREL makes "." notation available in this context, so whatever the theoretical arguments against that, OpenRefine is already ignoring them.  It would just be nice if it ignored them consistently :-)

**Comment by tfmorris** [comment]
Unlike GREL, the language syntax is defined by Python, so this isn't an option.
