### ISSUE TITLE
HTML export : Unicode Asian language fonts need <meta charset="utf-8" />

### ISSUE THREAD

**Issue by answerquest** [OpenRefine/OpenRefine#1015]
HTML export : Data in Unicode Asian language (like Devnagri.. हिंदी ) needs a ``<meta charset="utf-8" />`` in the ``<head>`` section, without which the html created by ``HTML Table`` Export shows the content like this:
```
¤¸à¥à¤µà¤¾à¤°à¤—à¥‡à¤Ÿ
```
The content is being saved properly in the HTML file (checked in text editor).. just this charset specifier needs to be there in the header.
Using ``Version 2.5 [r2407]``

**Comment by tfmorris** [comment]
We probably need to check to make sure that we're not using the default system encoding here and that we either always export in UTF-8 or allow the user to specify the encoding.  We should include a meta tag with the matching character set, no matter what character set is used.

**Comment by jackyq2015** [comment]
Exporting in UTF-8  covers (almost) all the characters, punctuations, and symbols in the world. 
http://www.w3schools.com/tags/ref_charactersets.asp

I will make the change to implement this if there is no objection.

**Comment by answerquest** [comment]
Yay! So, curious: is this fixed in the latest version to download?

**Comment by magdmartin** [comment]
I will be part of the next release.
For now you will have to build Refine from the repository.

**Comment by tfmorris** [comment]
I'll be building another release candidate shortly.
