### ISSUE TITLE
Close modal dialogs on ESC key

### ISSUE THREAD

**Issue by Opennat** [OpenRefine/OpenRefine#1018]
We need a possibility to close any modal window by pressing "Escape". Like we have this behaviour now on cells' "Edit", and "Rename this column" windows.

**Comment by magdmartin** [comment]
+1

**Comment by tfmorris** [comment]
Any ones in particular?

**Comment by magdmartin** [comment]
I'll suggest we have this as a default behaviour for any windows prompting over the data grid including the following interface:
* cluster 
* all GREL related windows (fetch url, transform, add column, custom facet)
* transpose
* template export
* custom export
* other that I can't think right now.

**Comment by Opennat** [comment]
Yes, thanks for clarifying, @magdmartin
As now, you should use mouse or tabbing many times to press "Close" button to just close dialog.

**Comment by lisa761** [comment]
Hi, can I be assigned to this issue?

**Comment by ostephens** [comment]
@lisa761 done!

**Comment by lisa761** [comment]
Thanks! I should start working on it now
