### ISSUE TITLE
"Add column..." dialog should have input focus in "New column name" field

### ISSUE THREAD

**Issue by Opennat** [OpenRefine/OpenRefine#1019]
As anyway you must enter name of column to create it, but now you need to Shift-Tab/Tab many times or move mouse in opposite directions each time.

**Comment by wetneb** [comment]
It was decided by @katrinleinweber in #2139 to focus the expression input instead.

**Comment by katrinleinweber** [comment]
Without having seen this issue, though ;-)

**Comment by wetneb** [comment]
I would say both options have their pros and cons… But if we have a change of mind it does not have to be set in stone!
