### ISSUE TITLE
Window that opens by "XXX choices" in text facet needs a button to close

### ISSUE THREAD

**Issue by Opennat** [OpenRefine/OpenRefine#1020]
Now you should hit pixel in left bottom.

**Comment by Opennat** [comment]
Excuse me, it's already fixed in dev branch (not in 2.6-beta, available for download).

**Comment by tfmorris** [comment]
It's also fixed in RC1 available on the downloads page https://github.com/OpenRefine/OpenRefine/releases/tag/v2.6-rc1
