### ISSUE TITLE
Move Column Right doesn't work

### ISSUE THREAD

**Issue by Opennat** [OpenRefine/OpenRefine#1021]
Sometimes (I can't now provide steps to reproduce this bug) OpenRefine does not react on "Edit column - Move column[...]" on some columns, but any other columns (to the left and/or right of this column) can freely be moved any way. At this moment "Move column right" itself work on ~15-20% of all attempts. I know about possibility to move/reorder them from "All" - "Edit columns"...

**Comment by magdmartin** [comment]
Just to confirm, did you try to move right the last column or move left the first column. On the top of my head this might generate an error.

**Comment by Opennat** [comment]
I've tried to move columns on each side in some project, and no errors/exceptions or any visual changes have been seen.

btw, in 2.6-rc1 "Edit columnt -> Move column right" does not work at all for me (any column name/position in some projects tried, any type of cells, Chrome/Firefox under Win9/Debian locally/remote combinations). No errors (or any actions) in Open Refine log, no actions/errors/exceptions in browser (only one for a long time for Refine: "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.").

**Comment by magdmartin** [comment]
I confirm that move column right doesn't work on 2.6-rc1 (firefox, ubuntu) - no error generated.

**Comment by magdmartin** [comment]
Move column right doesn't work in OpenRefine2.6-beta (chrome and firefox, ubuntu)

**Comment by magdmartin** [comment]
As temporary work around you can use:  All >  Edit columns > Re-order / remove columns ...
