### ISSUE TITLE
Make opening browser on startup optional

### ISSUE THREAD

**Issue by Opennat** [OpenRefine/OpenRefine#1022]
Default option not always (almost never for me) needed, as it only can open Refine in default browser (it could differ from browser to work with Refine).

**Comment by jackyq2015** [comment]
That's good point. I also feel annoying when we run the Refine under hosted
Linux server. It won't cause issue, but I agree the configuration way to
disable this

**Comment by tfmorris** [comment]
This will need to be added to the command line as well as the .ini file.

@jackyq2015 What is the issue when running on a remote Linux server?  Doesn't it just fail to do anything?

**Comment by Opennat** [comment]
To disable browser autostart, add

`JAVA_OPTIONS=-Drefine.headless=true`

to refine.ini

Thanks for hint: https://github.com/tabulapdf/tabula/issues/534

**Comment by wetneb** [comment]
As pointed out above, the `refine.headless=true` option does the trick.
