### ISSUE TITLE
OpenRefine should respect columns order on import data from JSON

### ISSUE THREAD

**Issue by Opennat** [OpenRefine/OpenRefine#1023]
Or ask for their order, or, more important - give a choice to use some templates for it (like templates on export). We work in Refine on a couple of stabile projects, that have same columns (i.e. keys in JSON), and each time on creating project we should rearrange columns in usual order, as Refine opens JSON keys in chaotically order.

**Comment by tfmorris** [comment]
The only place JSON has ordering is in arrays.  Iterating through JSON keys will always have an implementation specific order which depends on the hash used.

Could you describe a little bit more about your use case and why you need the columns in a specific order during processing?  Do you know that you can easily reorder them on export by simply dragging column names around? (If export order is your end goal)

**Comment by wetneb** [comment]
I agree, order for JSON keys is unspecified so the user should not expect them in any particular order. Closing.
