### ISSUE TITLE
Ability to run OpenRefine not in root of (sub)domain

### ISSUE THREAD

**Issue by Opennat** [OpenRefine/OpenRefine#1024]
Refine works well behind http proxy on personal (sub)domain like http://refine.domain.com, but you can't run it on URI like http://sub.domain.com/refine, because of hardcoded absolute paths. It is especially needed, when you limited by subdomain choice due to SSL certificate issued on exact subdomain and can't provide root of it to Refine.

**Comment by magdmartin** [comment]
If few people (including RefinePro) run OpenRefine as an hosted service, it has been designed as a local application. I am open to see how many people are interested to take Refine as an hybrid local / hosted solution.

**Comment by tfmorris** [comment]
We fixed most (all? at the time) of the absolute path references a while ago.  If new hardcoded path references have crept in, please provide a list of them (it should be a short list) -- or better yet, a pull request with the necessary fixes.

I don't understand what, if anything, running on a non-PLD has to do with this.  I don't know of any place where host name/address matters.  Can you clarify?

**Comment by thadguidry** [comment]
Closing as **no response from OP**
