### ISSUE TITLE
Dialog on hovering over reconciliation candidates

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#103]
_Original author: iainsproat (June 30, 2010 17:49:33)_

When reconciling entities, a number of candidates are shown but only their topic names.  To determine if they are actually the correct topic you have to open each link in turn.  This can be quite tedious.

As an enhancement to the UI, I'd like to propose that a tooltip-style dialog be displayed on hovering over each candidate.  This would display the description, picture, types etc. from Freebase.

Bonus points for expanding it to support other reconciliation services.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=103_
##

**Comment by wetneb** [comment]
This has been implemented, and the feature is available to standard reconciliation services with the preview endpoint. It is being used (for instance) by OpenCorporates and Wikidata.
