### ISSUE TITLE
Project rename dialog on "Open Project" page doesn't refresh on 2nd rename

### ISSUE THREAD

**Issue by Opennat** [OpenRefine/OpenRefine#1032]
When you renaming project, you press "rename", type new name, press OK, and project name changes, but if you press "rename" again - you'll see old name, and any alternating of it does not reflects on the page until refresh.
Renaming project when project opened works as expected.

**Comment by elroykanye** [comment]
@wetneb , I tried recreating this issue but it was not the same. I think it has been fixed already.

**Comment by wetneb** [comment]
I agree, it seems fixed indeed! Thanks for investigating :)
