### ISSUE TITLE
Request: Autofit panels sizing

### ISSUE THREAD

**Issue by simon1tan** [OpenRefine/OpenRefine#1041]
It would be nice if the panels can be automatically sized(height) upon creation. When I do a facet that results in True/False, the panel is created with a default height which takes up some screen real estate. Then I have to manually resize so I can see more panels. There may be cases where creating the a new panel may be too big, for which we could set a height limit. For the panels that open with a few items, we should autofit them.

**Comment by wetneb** [comment]
Duplicate of #5513.
