### ISSUE TITLE
Error initializing module freebase by script function init()

### ISSUE THREAD

**Issue by dbl001** [OpenRefine/OpenRefine#1043]
Hi,

I got this error launching OpenRefine on OS X 10.10.3.

17:18:36.888 [         butterfly.module] Error initializing module freebase by script function init() (2070ms)
org.mozilla.javascript.EcmaError: TypeError: Cannot call property register in object [JavaPackage com.google.refine.freebase.oauth.FreebaseProvider]. It is not a function, it is "object". (file:/Users/davidlaxer/OpenRefine/main/webapp/../../extensions/freebase/module/MOD-INF/controller.js#35)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3654)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3632)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3660)
	at org.mozilla.javascript.ScriptRuntime.typeError3(ScriptRuntime.java:3686)
	at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:3746)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2247)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2214)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:117)
	at org.mozilla.javascript.gen.c6._c1(file:/Users/davidlaxer/OpenRefine/main/webapp/../../extensions/freebase/module/MOD-INF/controller.js:35)
	at org.mozilla.javascript.gen.c6.call(file:/Users/davidlaxer/OpenRefine/main/webapp/../../extensions/freebase/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
	at org.mozilla.javascript.gen.c6.call(file:/Users/davidlaxer/OpenRefine/main/webapp/../../extensions/freebase/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:294)
	at com.google.refine.RefineServer.init(Refine.java:208)
	at com.google.refine.Refine.init(Refine.java:114)
	at com.google.refine.Refine.main(Refine.java:108)
17:18:41.289 [                   refine] POST /command/core/load-language (4401ms)
17:18:41.398 [                   refine] POST /command/core/load-language (109ms)
17:18:41.605 [                   refine] POST /command/core/get-importing-configuration (207ms)
17:18:41.621 [                   refine] GET /command/core/get-all-project-metadata (16ms)
17:18:41.680 [                   refine] GET /command/core/get-languages (59ms)
17:18:41.705 [                   refine] GET /command/core/get-version (25ms)

I see these links:

https://groups.google.com/forum/#!msg/openrefine-dev/-Ylxd4bF8qw/fQwLDTaeupMJ

https://travis-ci.org/OpenRefine/OpenRefine/jobs/64949299

Any suggestions?

**Comment by jackyq2015** [comment]
You can remove the extensions/freebase folder, also remove the line in the controller.js
      "scripts/reconciliation/freebase-query-panel.js",

Freebase supposed to be removed completely as my understanding and it is a pending issue in next release(2.6). Will confirm with Tom regarding this.

**Comment by ScientificProgressGoesBoing** [comment]
Tried did advice but program did not work anymore. Would be grateful for another quick fix because the error message keeps popping up and changing tabs which is annoying. Thank you for your work! I appreciate the development effort put into this program!

**Comment by jackyq2015** [comment]
What error did you see when you say it is not working? Can you also provide
the version of the openrefine and how you run it

**Comment by dbl001** [comment]
The advised update worked for me.  I’m running OS  10.10.4 Yosemite.

David-Laxers-MacBook-Pro:OpenRefine davidlaxer$ ./refine 
Starting OpenRefine at 'http://127.0.0.1:3333/'

20:19:17.312 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
20:19:17.313 [            refine_server] refine.memory size: 1400M JVM Max heap: 1304952832 (1ms)
20:19:17.333 [            refine_server] Initializing context: '/' from '/Users/davidlaxer/OpenRefine/main/webapp' (20ms)
20:19:17.428 [            refine_server] Starting autoreloading scanner...  (95ms)
20:19:18.311 [                   refine] Starting OpenRefine 2.6 [TRUNK]... (883ms)
20:19:25.589 [                   refine] POST /command/core/load-language (7278ms)
20:19:25.736 [                   refine] POST /command/core/load-language (147ms)
20:19:25.827 [                   refine] POST /command/core/get-importing-configuration (91ms)
20:19:25.858 [                   refine] GET /command/core/get-all-project-metadata (31ms)
20:19:25.904 [                   refine] GET /command/core/get-languages (46ms)
20:19:25.933 [                   refine] GET /command/core/get-version (29ms)
09:20:00.030 [                   refine] POST /command/core/load-language (46834097ms)
09:20:00.062 [                   refine] GET /command/core/get-preference (32ms)
09:20:00.068 [                   refine] GET /command/core/get-preference (6ms)
09:20:00.073 [                   refine] POST /command/core/load-language (5ms)
09:20:00.099 [                   refine] GET /command/core/get-project-metadata (26ms)
09:20:00.264 [                  project] Loaded project 2231895062070 from disk in 0 sec(s) (165ms)
09:20:00.299 [                   refine] GET /command/core/get-models (35ms)
09:20:00.392 [                   refine] GET /command/core/get-history (93ms)
09:20:00.435 [                   refine] POST /command/core/get-rows (43ms)
09:20:00.580 [                   refine] GET /command/core/get-history (145ms)
09:20:07.455 [                   refine] GET /command/core/get-history (6875ms)
09:20:07.470 [                   refine] POST /command/core/get-rows (15ms)
09:20:07.617 [                   refine] POST /command/core/compute-facets (147ms)
09:22:39.258 [                   refine] GET /command/core/get-starred-expressions (151641ms)
09:22:39.259 [                   refine] GET /command/core/get-expression-history (1ms)
09:22:39.261 [                   refine] GET /command/core/get-expression-language-info (2ms)
09:22:39.289 [                   refine] POST /command/core/preview-expression (28ms)
09:23:10.473 [                   refine] POST /command/core/preview-expression (31184ms)
09:23:11.007 [                   refine] POST /command/core/preview-expression (534ms)
09:23:12.846 [                   refine] POST /command/core/preview-expression (1839ms)
09:23:15.015 [                   refine] POST /command/core/log-expression (2169ms)
09:23:15.019 [                   refine] POST /command/core/text-transform (4ms)
09:23:15.091 [                   refine] GET /command/core/get-history (72ms)
09:23:15.136 [                   refine] POST /command/core/get-rows (45ms)
09:23:15.256 [                   refine] POST /command/core/compute-facets (120ms)
09:23:15.263 [                   refine] POST /command/core/preview-expression (7ms)
09:23:29.057 [                   refine] GET /command/core/get-history (13794ms)
09:23:29.076 [                   refine] POST /command/core/get-rows (19ms)
09:23:29.203 [                   refine] POST /command/core/compute-facets (127ms)
09:24:19.157 [           ProjectManager] Saving some modified projects ... (49954ms)
09:24:19.202 [        project_utilities] Saved project '2231895062070' (45ms)

**Comment by jackyq2015** [comment]
PR created.

The code was deployed under:
http://208.75.74.214:3333/

Please help to verify if it works properly and also check the reconsideration part. If need to install some extension, let me know.
