### ISSUE TITLE
Integer Devision doesn't work?

### ISSUE THREAD

**Issue by D1no** [OpenRefine/OpenRefine#1044]
OpenRefineRC1 After a long time I needed to use Refine again to do some data preparation.

It seems, the math does not work so that a devision of integers (1 / 2) will not be evaluated to a decimal - instead to 0. If one of the numbers were decimals, than devision works. 
![image](https://cloud.githubusercontent.com/assets/2397125/8966244/9cd4de30-3630-11e5-9dac-253fa2ac8e80.png)
### not working
![image](https://cloud.githubusercontent.com/assets/2397125/8966257/b04e3dbc-3630-11e5-9806-38c6a55762fc.png)
![image](https://cloud.githubusercontent.com/assets/2397125/8966371/5b2bcbbe-3631-11e5-8985-5db662acea0d.png)

Its not just the preview, the output is effected too. Please let me know if I do anything wrong here...

**Comment by D1no** [comment]
*odd add-on:*
If you include in your calculation a meaningless decimal-based devision, than it keeps evaluation to decimals. I guess I am going to add ``(0.5/1*2) * `` for a while now...
![image](https://cloud.githubusercontent.com/assets/2397125/8966804/a600674c-3633-11e5-86f5-2054884db1ec.png)

**Comment by tfmorris** [comment]
Welcome back to Refine.  If you've got questions, the openrefine mailing list is a good place to get them answered. https://groups.google.com/forum/#!forum/openrefine

Integer division works the same way it always has.  1 / 2 is equivalent to floor(1/2) ie it returns only whole number results.  If either operand is a floating point number, they both get promoted to floating point and a floating point result is returned.

You can use 1 / 2.0 or 1.0 / 2 or 1.0 * x / y (if you're working with variables of unknown contents) to achieve the results you desire.

**Comment by D1no** [comment]
Apologies. I did a prior google search before; checked the [GREL math operations](https://github.com/OpenRefine/OpenRefine/wiki/GREL-Functions) and did not find any notable behaviour for devisions, float and automatic typing.

Maybe this could be added, as it is certainly an unexpected ux - as it seems to [https://code.google.com/p/google-refine/issues/detail?id=350](have popped up before)

**Comment by thadguidry** [comment]
Added Tom's note to wiki:
https://github.com/OpenRefine/OpenRefine/wiki/GREL-Math-Functions

Thad
+ThadGuidry <https://www.google.com/+ThadGuidry>

**Comment by tfmorris** [comment]
Thanks Thad!
