### ISSUE TITLE
Add original source of the data to metadata.json in project download

### ISSUE THREAD

**Issue by nickynicolson** [OpenRefine/OpenRefine#1045]
Could details of the original source of the data be persisted and output in the the metadata.json file created when the project is downloaded as a complete Open Refine project?

**Comment by jackyq2015** [comment]
Is this a duplipcate of issue #512?
Store file source in each row not working for JSON from URL #512

If so, please close it.

**Comment by nickynicolson** [comment]
#512 describes storing file source as a column in the data (and a problem whereby this is not populated for JSON from URL). I'd like the file source(s) to be stored as project metadata (not data columns) and output when the project is saved in Open Refine project format, in the `metadata.json` file.

**Comment by jackyq2015** [comment]
I see. That make sense.

**Comment by tfmorris** [comment]
Good suggestion and one that we've certainly thought about, but I can't seem to find an existing issue for it, so thanks for adding it.

In addition to the original URL/filename, we should also add:
- a free form description field that the user can populate with notes if they want
- the import option settings which were used

The second is a poor man's workaround to not having the import operation included in our operation history.  Ideally, the project creation operation, along with all its settings and parameters would be just another operation like all the others.

p.s. speaking of workarounds, I just paste the URL at the end of the project name and use that to keep track of where data came from.  Not elegant, but it works with the current system.

**Comment by tfmorris** [comment]
This was addressed as part of #1221 which was included with OpenRefine 2.8 in November 2017, although the filename/source URL is buried in a blob of JSON which makes it pretty hard to spot. It probably deserves its own line in the "About" display up toward the top, but we can create a separate issue for that.
