### ISSUE TITLE
Incomplete install documentation

### ISSUE THREAD

**Issue by niconoe** [OpenRefine/OpenRefine#1053]
Hi,

I think I found something lacking from the install documentation (at still I have this question, and can't find the answer): the documentation says how to use the Mac OS X package, and also for linux how to pass parameters at launch, such as:

    $ ./refine -i 0.0.0.0

There's no mention of how to change the IP the server listen to on Mac OS X... Any hints?

**Comment by niconoe** [comment]
To complete this ticket, it seems the solution proposed at https://groups.google.com/forum/#!topicsearchin/openrefine/listen/openrefine/km25PNwn-_Q (adding a key to Info.plist) just works fine for me.

Maybe we should just explain that in the documentation?

**Comment by magdmartin** [comment]
@niconoe thank you for your update. Anyone with a github account can edit the documentation. Do you mind updating the installation page with your finding: https://github.com/OpenRefine/OpenRefine/wiki/Installation-Instructions

Thank you very much.

**Comment by niconoe** [comment]
Done, thanks!

**Comment by magdmartin** [comment]
Thank you for your contribution.
