### ISSUE TITLE
"Browse this Cluster" URL incorrectly escaped

### ISSUE THREAD

**Issue by joewiz** [OpenRefine/OpenRefine#1059]
In the "Cluster & Edit" window, the "Browse this Cluster" link opens a window with zero rows if any of the candidates the cluster contain characters like curly/typographic quotation marks, e.g., “. (I'm guessing this has to do with character escaping.)

(I'm using 2.6RC1 with current versions of Mac OS X and Google Chrome.)

**Comment by joewiz** [comment]
The issue isn't limited to curly/smart quotes. I'm getting it with other characters too.  Here are some example clusters and the character that triggers the problem:

`á`
- Montagne Sánchez, Ernesto
- Sanchez, Ernesto Montagne

`ç`
- Mitterrand, Francois
- Mitterrand, François

**Comment by wolxXx** [comment]
same here...
