### ISSUE TITLE
Edits made via "Edit this cell" occasionally fail to apply

### ISSUE THREAD

**Issue by joewiz** [OpenRefine/OpenRefine#1062]
In some circumstances that I'm not able to consistently reproduce, changes made a cell via "Edit this cell" and "Apply" are not applied. 

I will update this issue if I am able to supply reproducible test, but I'm submitting this in the hope that others can contribute tests/observations if they've seen this too.

(I'm using 2.6RC1 with current versions of Mac OS X and Google Chrome.)

**Comment by Blakko** [comment]
It happened to me a couple of times, but it was just related to the interface not being updated. Next time try to refresh the page to see if it's the case :)

**Comment by Opennat** [comment]
In addition to what have been said above, sometimes your edit is really applied to the cells, and sometimes not (you could check this in another browser tab with current project). In both cases you will see yellow "popup": "Edit ..... on row X, column Y Undo".

This bug occurs (I believe) in 100% cases, when you have 2 or more filters/facets active.
I'll check this later and make screencast.

**Comment by joewiz** [comment]
@Opennat Thanks for what you suggested. I agree that this often happened when I had 2 or more filters/facets active. (And sorry I didn't spot your reply sooner.) Were you able to find a reproducible case? It's been a while since I was working intensively with OR, but if you had anything more to add, esp. with 2.6RC2, that would be worth keeping the issue open for.

**Comment by tfmorris** [comment]
We've fixed the case where this was being triggered by text filter facets in #2846 (as demonstrated by @zengchu2's excellent analysis in #2492). Unfortunately, although I wrote the patch back in May 2016, it got lost in the shuffle and just got committed recently.

I'm going to close this, but if anyone finds any other reproducible cases where this happens, please open separate bug reports for them.
