### ISSUE TITLE
Wrong result with .reverse array function

### ISSUE THREAD

**Issue by pprasqui** [OpenRefine/OpenRefine#1067]
I want to compare a field with a list of starting strings and get the one with most matching characters. In order to extract the resulting value from the testing array, I reverse sort it. But the result isn't logical: on the first line, reverse sort works well. On the following ones, I sometimes get "" before "alex", which doesn't make sense.
![capture d ecran 2015-09-18 a 11 34 41](https://cloud.githubusercontent.com/assets/7451210/9961880/43375eb6-5df9-11e5-95df-1f831465d944.png)

Using Version 2.6-rc1 [TRUNK] on a MacOS 10.10.5

**Comment by simon1tan** [comment]
I can't tell if this a bug or faulty logic in the code. You are just replacing values with "" or the name and reversing the array. Nowhere is there a sort.

**Comment by pprasqui** [comment]
My bad... Because of the example in the reverse function description "For example, reverse([ 0, 1, 2, 3]) returns the array [ 3, 2, 1, 0 ]", I somehow inferred that reverse was an inverted sort.
