### ISSUE TITLE
"Extract Operation History" checkbox not show

### ISSUE THREAD

**Issue by jackyq2015** [OpenRefine/OpenRefine#1072]
From the operation history panel, when click the "Extract" button, the checkbox for each operation at left side does not show.

It's related to the merge in last week. Need to find out which one introduced this bug.

**Comment by magdmartin** [comment]
I just test it with Chrome on a chromebook on the test deployment and I don't see the issue. Works fine for me.

**Comment by thadguidry** [comment]
Jacky,

ant clean
ant build

Shift F5 on browser to force clear cache
?

**Comment by jackyq2015** [comment]
@thadguidry Tried, the same.

But it works if I deploy to Linux machine. weird.

**Comment by jackyq2015** [comment]
My bad. It was cached somewhere.
