### ISSUE TITLE
Can I trim a list?

### ISSUE THREAD

**Issue by dbolser-ebi** [OpenRefine/OpenRefine#1077]
trim(split(...)) doesn't seem to work.

**Comment by thadguidry** [comment]
Dan,

You will need to first get the part of the array that you want to trim.
Remember that split() outputs an Array, not a whole string.  It outputs a
first and second part.  Our GREL String functions are documented a bit
here: https://github.com/OpenRefine/OpenRefine/wiki/GREL-String-Functions

You probably want to do something like:

value.split(";")[0].trim()

or

value.split(";")[1].trim()

to trim the first or second part

Thad
+ThadGuidry <https://www.google.com/+ThadGuidry>

**Comment by dbolser-ebi** [comment]
Thanks Thad,

The issue I'm having is that the list can be 1 to n terms, and I want to trim them all... Actually the solution in this case is to split on ' ,' rather than ','.

I'm guessing it isn't possible to run a function over a list in GREL?

Cheers,

**Comment by thadguidry** [comment]
Yes we have GREL Control functions.  Controls are bit different than
functions.  And you can read more how they differ here:

https://github.com/OpenRefine/OpenRefine/wiki/GREL-Controls

 forEach()
 forNonBlank()
 etc....

Take a look more at all of our Reference material :
https://github.com/OpenRefine/OpenRefine/wiki/Documentation-For-Users#reference

then dive into more docs and Recipes for a fuller picture  (Scroll down
this page before you click on any link, just to get a high level view of
all the kinds of documentation we have)

https://github.com/OpenRefine/OpenRefine/wiki/Documentation-For-Users
.


Thad
+ThadGuidry <https://www.google.com/+ThadGuidry>

**Comment by thadguidry** [comment]
Looks like we do have a few recipes that showcase what you sort of need to
do.
I like making folks think and work through problems, rather than directly
showing them the answers. :)  - I do the same for my kids :) :)

https://github.com/OpenRefine/OpenRefine/wiki/Recipes#split--map--join

If you still need help after that, just reach back out to us on the mailing
list.


Thad
+ThadGuidry <https://www.google.com/+ThadGuidry>

**Comment by dbolser-ebi** [comment]
Thanks thad,

Looking here:
https://github.com/OpenRefine/OpenRefine/wiki/GREL-Controls#filterexpression-a-variable-v-expression-test

this solution was pretty obvious:
forEach(split(value, ','), v, trim(v))

Personally, I rather just try the answer than work it out for myself ;-)


Thanks for help,
Dan.

**Comment by thadguidry** [comment]
Dan,

But then you would not have learned those 10 shiny new things you now know
you can do in GREL besides your immediate problem.  And you have gained
confidence in yourself = PRICELESS

Thad
+ThadGuidry <https://www.google.com/+ThadGuidry>

**Comment by dbolser-ebi** [comment]
​Meh ;-P

**Comment by tfmorris** [comment]
@dbolser-ebi Glad you got your question answered, but please using the mailing list / Google Group for future questions so that we can reserve the issue tracker for actual problem reports.
