### ISSUE TITLE
Doesn't run on OS X10.11.1 Beta (15B30a)

### ISSUE THREAD

**Issue by FigaCZ** [OpenRefine/OpenRefine#1080]
This version doesn't open on this version OS X.

**Comment by magdmartin** [comment]
Thank you for reporting this. At which point the program failed? Do you see any error message? 

Thank you for the additional information.

**Comment by FigaCZ** [comment]
Unfortunatelly, it doesn't show any error message. It crash after few seconds. I can say that RC1 runs great on this OS X build.

**Comment by jackyq2015** [comment]
can't find 15B30a. Is it sha? I tried the updated version  8b4a1d on Mac it start fine.

**Comment by tfmorris** [comment]
@FigaCZ Can you please clarify what version of OpenRefine you are attempting to run and which OS X 10.11.1 Beta you are running (there have been four so far).

My first inclination, if OpenRefine runs on released versions of OS X, is to report this as an OS X bug to Apple.
