### ISSUE TITLE
Migrate autoupdate mechanism off code.google.com

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#1082]
The data for the autoupdate mechanism used by Refine currently lives at http://google-refine.googlecode.com/svn/support/releases.js and we need to move it to a new location.  If we can trigger the 2.5 -> 2.6 update from there, that would be ideal, but there may be too many assumptions built in about SVN revision numbers, file locations, etc.

If autoupdate can't be made to work, we'll have to rely on a one-time manual update for users and cut over to a new autoupdate location.

**Comment by wetneb** [comment]
We decided to just notify about the new version without auto-updating the local copy: #1258
