### ISSUE TITLE
OpenRefine reconciliation service not working - mutliple vs single queries

### ISSUE THREAD

**Issue by lmsanch** [OpenRefine/OpenRefine#1101]
I have been using OpenRefine 2.6 Beta 1 w/o problems since its release, and later, with the reconciliation service at:

http://reconcile.freebaseapps.com/reconcile

However, in the past fee days, I have not been able to use it all. If I go to the URL:

http://reconcile.freebaseapps.com/

and type the multiple query:

{
  "query": "Ford",
  "type": "/people/person",
  "properties": [
    {
      "pid": "/people/person/place_of_birth",
      "v": "Detroit"
    }
  ]
}
I obtain:

{
  "result": [
    {
      "id": "/m/0j8pb6y",
      "name": "Ford",
      "type": [
        {
          "id": "/people/person",
          "name": "Person"
        },
        {
          "id": "/common/topic",
          "name": "Topic"
        },
        {
          "id": "/geography/mountaineer",
          "name": "Mountaineer"
        }
      ],
      "notable": [],
      "score": 1.1546246,
      "match": false
    },
    {
      "id": "/m/01vd3gv",
      "name": "Ford",
      "type": [
        {
          "id": "/common/topic",
          "name": "Topic"
        },
        {
          "id": "/music/artist",
          "name": "Musical Artist"
        }
      ],
      "notable": [],
      "score": 1.0330245999999998,
      "match": false
    },
    {
      "id": "/m/0cmdhzt",
      "name": "James Meredith",
      "type": [
        {
          "id": "/common/topic",
          "name": "Topic"
        },
        {
          "id": "/people/person",
          "name": "Person"
        },
        {
          "id": "/military/military_person",
          "name": "Military Person"
        },
        {
          "id": "/people/deceased_person",
          "name": "Deceased Person"
        }
      ],
      "notable": [],
      "score": 0.0681692,
      "match": false
    }
  ],
  "duration": 369
}
But if I try a simple query:

{
  "query": "Ford"
}
I get:

Status: error Error:undefined

Any insights into what's happening with the reconciliation service? Is there any other service I could use to replace freebaseapps.com?

**Comment by lmsanch** [comment]
I tried this this in "Queries Parameter" insted of "Query Parameter" at http://reconcile.freebaseapps.com/, and it works. Still having problems with reconciling with OpenRefine.

{
  "q0": {
    "query": "Ford"
  }

}

**Comment by thadguidry** [comment]
That reconcile service is no longer supported.  It is deprecated.

See https://developers.google.com/freebase/v1/reconciliation-overview?hl=en

**Comment by lmsanch** [comment]
Tad, I am confused: Is the reconcile within OpenRefine working? I am referring to the reconciliation service I use in Open Refine http://reconcile.freebaseapps.com/reconcile. Thanks

**Comment by thadguidry** [comment]
this service:  http://reconcile.freebaseapps.com/

Is in a state of "no longer being actively being maintained".  The original maintainer was Andi Vajda who can be reached at email vajda@google.com

You can ask him directly.  That service is not run by the OpenRefine team, but was run by Andi when he was with Freebase/Google and it is his app and indexing service that you are having problems this.  Freebase/Google have already said that there are no guarantees of any service availability in the future after the deprecation time, which was last summer in June 2015.

OpenRefine does provide a Reconciliation interface for any kind of reconciling service...and there are a few of those services still around on the internet... see a list here: https://github.com/OpenRefine/OpenRefine/wiki/Reconcilable-Data-Sources
