### ISSUE TITLE
2.6-rc.2 starting stopps in half-way in Windows 10 (64)

### ISSUE THREAD

**Issue by PeterJPower** [OpenRefine/OpenRefine#1102]
Launching 2.6.-rc.2 beta version stopps after reading get-importing-conficuration. Ui becomes ready but nothing functioning.

22:34:46.684 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
22:34:46.705 [            refine_server] Initializing context: '/' from 'D:\xx\xx\OpenRefine_2.6_rc2\openrefine-2.6-rc.2\webapp' (21ms)
22:34:47.354 [                   refine] Starting OpenRefine 2.6-rc.2 [TRUNK]... (649ms)
22:34:49.851 [                   refine] POST /command/core/get-importing-configuration (2497ms)

**Comment by PeterJPower** [comment]
It must be a MS Edge browser's incompatibility fault, I noticed now with Google Chrome everything of OpenRefine is functioning ok .

**Comment by magdmartin** [comment]
@PeterJPower OpenRefine works in Chrome and Firefox only.
