### ISSUE TITLE
On various Mac OSX versions, OpenRefine does not launch console, in-browser window

### ISSUE THREAD

**Issue by c0gs** [OpenRefine/OpenRefine#1104]
Hello, I am in the middle of teaching OpenRefine in-class and have had issues getting my students to run OpenRefine in a Mac environment.

What happens:
- Students install OpenRefine 2.6, drag to application folder, double-click to launch
- OpenRefine appears to be running on the dock, but the console doesn't pop up; neither does the in-browser window.

Can anyone suggest anything?

Thanks,

David

**Comment by lmsanch** [comment]
Try typing your localhost IP to bypass the automatic launching.

**Comment by c0gs** [comment]
I'll give it a shot, thanks!

**Comment by c0gs** [comment]
This worked, thanks!
