### ISSUE TITLE
Open Refine reconciliation service not working?

### ISSUE THREAD

**Issue by lmsanch** [OpenRefine/OpenRefine#1108]
I have test data with the names of 10 actors, that I would like to expand with some additional data.

![screen shot 2016-01-16 at 3 06 23 pm](https://cloud.githubusercontent.com/assets/3156487/12374221/bd58bcd6-bc62-11e5-9a73-83e5636eb195.png)

This used to work fine using this reconciliation service: http://reconcile.freebaseapps.com/reconcile. However, now it is stuck there. Is there any problem with the service?

![screen shot 2016-01-16 at 3 07 36 pm](https://cloud.githubusercontent.com/assets/3156487/12374237/0bdc1c0e-bc63-11e5-9b69-b82ba5a13baf.png)

![screen shot 2016-01-16 at 3 04 55 pm](https://cloud.githubusercontent.com/assets/3156487/12374239/22edf872-bc63-11e5-9cea-aadd485b99a1.png)

**Comment by thadguidry** [comment]
The service (not provided by OpenRefine, but Google/Freebase) is now
deprecated.

Read comments on this closed issue:
https://github.com/OpenRefine/OpenRefine/issues/1101


Thad
+ThadGuidry <https://www.google.com/+ThadGuidry>
