### ISSUE TITLE
Change default value in "Add column based on this column" dialog

### ISSUE THREAD

**Issue by Opennat** [OpenRefine/OpenRefine#1109]
Default value in "Expression" field in "Add column based on this column..." dialog should be set to `null` by default.

In previous versions of Refine (I think, below 2.6-rc.1) you could delete default `value` to just get new blank column, but in 2.6-rc.2 you must replace default `value` to `null` manually.

**Comment by wetneb** [comment]
Hmm, I think having `value` as a default is also sensible, because users normally want to enter expressions that depend on the value. Creating empty rows sounds a bit less common in a data cleaning workflow (I expect you would use them to enter data manually in them?)

**Comment by thadguidry** [comment]
We won't change the current behavior of defaulting to `value` since its a normal practice in other data tools.  Other OpenRefine extensions can certainly override this behavior if need be, or have a preference toggle.
