### ISSUE TITLE
Auto-switching tabs in Transform dialog

### ISSUE THREAD

**Issue by Opennat** [OpenRefine/OpenRefine#1110]
In 2.6-beta.1 click on `Reuse` link on `History` or `Starred` tab in `Transform` window pastes saved expression into `Expression` field, and automatically switches tab to `Preview`. In current 2.6-rc.2 click on `Reuse` link does not switches tab to `Preview`.

It was changed in 2.6-rc.1 (not working there too). Was it done intentionally?

**Comment by wetneb** [comment]
Not sure if this is still current?

**Comment by thadguidry** [comment]
Fixed long ago.  Tested against 3.3-beta just now and does not auto-switch to Preview tab.
