### ISSUE TITLE
Separator in "Join multi-valued cells"

### ISSUE THREAD

**Issue by Opennat** [OpenRefine/OpenRefine#1113]
Edit cells -> Join multi-valued cells have `,` (comma & whitespace) separator as default value. If you change it to `,` (just comma) you will anyway get result with comma & whitespace. In history you could see just comma: "separator": ",")

**Comment by ultraklon** [comment]
I've just tested this with a file with the following content
```
a,b
c,d
,e
f,g
,h
,i
```
and it looks like it works, when you leave the default ", " or you manually introduce that, you get
```
c|d, e
f|g, h, i
```
when the value "," is used, you get
```
c|d,e
f|g,h,i
```
BUT, when I tested it with ",&nbsp;&nbsp;&nbsp;&nbsp;" (comma and four spaces), I got the same results as with ", ". IDK if this is expected or not
With ",&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@" (comma, five spaces and @), you get
```
d|@e
g|@h, @i
```
so this is looks like collapsing multiple spaces into one

**Comment by ostephens** [comment]
So I've been having a look at this - it looks to me like the issue is with display rather than with the join. In the display, the spaces are collapsed (standard behaviour for html/web browsers), but if you actually access the value in the field, the spaces are present. See screenshot recreating scenario above with cell shown next to edit box for the cell - both contain the same information, but display differently.

<img width="720" alt="screen shot 2017-10-24 at 18 15 39" src="https://user-images.githubusercontent.com/576174/31957747-a205d65c-b8e7-11e7-99b3-af7b1279a63d.png">

**Comment by ostephens** [comment]
Which leads me to ask - is there any reason we don't style cells with css `white-space: pre-wrap` ? This would be a simple and I think useful change

**Comment by ettorerizza** [comment]
Arf, you're right @ostephens. This is particularly misleading, since these extra spaces are also invisible in the transformation window.

![screenshot-localhost-3333-2017-10-24-19-36-25-495](https://user-images.githubusercontent.com/6286410/31958687-d5a92972-b8f2-11e7-9348-e03729d77515.jpeg)

**Comment by thadguidry** [comment]
@ettorerizza @ostephens Yeap... Hence the new issue I created so we can deal with that in a different and new and improved way, like other code editors, notepads, etc. deal with this...  #1286 and we can show those non-breaking spaces (nbsp) as well as regular spaces and carriage returns, etc ... basically anything less than char(32) ... the unprintable range.   The idea in #1286 is to showcase unprintable chars in all of OpenRefine's various dialogs, facets, edit areas to dealing with those kinds of hidden characters... easier.

**Comment by thadguidry** [comment]
@ostephens can you do an ad-hoc restyle, using browser dev tools and perhaps take a screenshot to show me how that might look like ?

**Comment by ostephens** [comment]
@thadguidry I'm ok with not changing this, but I don't understand what you mean that css pre-wrap changes the data value for the user?

And looking forward to news!

**Comment by ostephens** [comment]
@thadguidry just going back to the issue of using css pre-wrap - can you clarify why you think this changes the data value for the user? Surely this is just for display, and would make the display of the data more accurate (as at the moment whitespace is collapsed, which means we are displaying the data differently to how it really is)

**Comment by thadguidry** [comment]
@ostephens Hi Owen, so sorry, earlier I actually was testing pre-wrap in another grid technology, not OpenRefine's that resulted in my jumping to conclusions.

This is only a display issue and I can confirm in newest Firefox that ```white-space: pre-wrap``` works effectively

```
div.data-table-cell-content {
  line-height: 1.2;
  color: #222;
  position: relative;
  white-space: pre-wrap;
}
```
