### ISSUE TITLE
Different syntax for regexp in Text filter and Transform

### ISSUE THREAD

**Issue by Opennat** [OpenRefine/OpenRefine#1117]
Say, I'm looking for all rows, that ends with 3 and 4 symbols, delimits by / and enclosed in round brackets. In Text filter regexp `\(.{3}/.{4}\)$` works, but in Transform expression (GREL used) I must use backslash as an escape character for / to get it work - `\(.{3}\/.{4}\)$`.

I'm pretty sure, as I used copy/pasting, that previous version (GoogleRefine 2.5 probably) have identical syntax for Text filter and Transform (GREL), but can't remember now: first variant or second. So, I would like to know, what syntax using in Text filter and what differences have it against GREL at the moment?

**Comment by magdmartin** [comment]
Please use our mailing list for [support question](https://groups.google.com/forum/?fromgroups#!forum/openrefine)
