### ISSUE TITLE
Open project not working on Firefox

### ISSUE THREAD

**Issue by kafran** [OpenRefine/OpenRefine#1120]
"Open Project" doesn't shows the created project when running on Firefox. Firefox version: 43.0.4; OS: Elementaryos 0.3.2 (Ubuntu 14.04 LTS); Openrefine: 2.6-rc2. I'm temporarily using Chromium until this get fixed. 

**Firefox Screenshot**
![openrefine_firefox](https://cloud.githubusercontent.com/assets/1889828/12511983/2fa68922-c0f4-11e5-8fd3-e62463c37c4c.png)

**Chromium Screenshot**
![openrefine_chrome](https://cloud.githubusercontent.com/assets/1889828/12512045/9a2de678-c0f4-11e5-8f7e-23e1758265ab.png)

**Comment by magdmartin** [comment]
Thank you for reporting this. Did you try with previous version of OpenRefine 2.6 like the rc1 or beta release? 
I've been using OpenRefine on ubuntu with Firefox without issue personally.

**Comment by kafran** [comment]
@magdmartin no, I haven’t tried it with previous version. Its my first time using Open Refine. On Firefox console I get this (which doesn't appear on Chromium):

![firefox1](https://cloud.githubusercontent.com/assets/1889828/12596892/12e1c7d2-c461-11e5-959a-2c489cca4333.png)

![firefox2](https://cloud.githubusercontent.com/assets/1889828/12596895/1a118ab0-c461-11e5-8bdb-ff236363d8cf.png)

**Comment by tfmorris** [comment]
So Chromium works and Firefox doesn't with the same Refine installation and no other changes?  That's very weird.

What version of Java do you have?  Can you cut & paste the text of the traceback?  The screen capture is nice visually, but it's much easier to work with the text in debugging tools.

If you're comfortable using the browser debugging tools, comparing the network traffic for the two browsers to see if they're the same would be interesting.  Also see if there are any warnings/errors on the Chromium debugging console.

The reason Firefox is unhappy is that it's expecting JSON and we're sending HTML, which we shouldn't be doing, but I suspect there's a lot more to it than that.

**Comment by kafran** [comment]
Problem solved. When I compared the network traffic I saw a lot of things cached on Firefox. I erase then the browser cache and the existing projects showed up in "Open Project's" tab.

Sorry for the trouble guys. And thanks for the help.

@tfmorris

**Comment by radinamatic** [comment]
`openrefine-2.6-rc.2` not working in Firefox 45 on Ubuntu 15.10. Tried running in safe mode with all the add-ons disabled & erasing cache to no avail:

![openrefine - mozilla firefox_428](https://cloud.githubusercontent.com/assets/1457929/14360553/3ee55d84-fcf7-11e5-8165-b9728c9a3e1f.png)

Chromium:
![export csv - openrefine - chromium_429](https://cloud.githubusercontent.com/assets/1457929/14360567/5286af00-fcf7-11e5-800b-34d0f15bdac8.png)

```
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.15.10.2)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```
