### ISSUE TITLE
Text filter failed for one record

### ISSUE THREAD

**Issue by BuhtigithuB** [OpenRefine/OpenRefine#1121]
Hello,

A simple text filter over a True/False text column contains a False row. I am filtering "Mariage" column with "True" filter...

![open_refine_2-6-rc-2_text_filter_bug](https://cloud.githubusercontent.com/assets/1660615/12560300/f0eff832-c367-11e5-883a-7e11437fa597.png)

Open Refine version 2.6 rc 2

**Comment by BuhtigithuB** [comment]
I add an index column and the issue goes away very strange... The same number of rows are matching though... And I tried export the filtered rows priviously to index the project and there were 29 rows... I circle only on False, but there were 2 as you can see...

**Comment by magdmartin** [comment]
Filtering in record mode will show the full record. In your case, since the first row of your record contains the value true OpenRefine display all the rows including other values. 

If you are not sure about an OpenRefine functionality, please use the mailing list for support question.

**Comment by BuhtigithuB** [comment]
Ok, I guess I should read about the difference between rows and records mode, I just start using and learn. Thanks to notice me.
