### ISSUE TITLE
epoch is missing, well not really - but any reference to it is missing

### ISSUE THREAD

**Issue by ajoslin103** [OpenRefine/OpenRefine#1122]
The Help section of the Expression dialog has a reference to the SimpleDateFormat docs, and would be benefited by the addition of a link to the GREL docs -- I'd suggest putting it under the DatePart function, or perhaps just putting a section of reference links at the top of the Functions section of that help text

thanks!

**Comment by NikitaEmberi** [comment]
Hey I am new to open source contribution. Can I work on this issue?

**Comment by wetneb** [comment]
Sure!

**Comment by Binita-tech** [comment]
I have read the issue description but I am not sure on which files I have to make changes, Please guide @wetneb , I want to work on this issue.

**Comment by wetneb** [comment]
Hi @Binita-tech, thanks for volunteering! Before figuring out which files to edit, have you reproduced the issue locally? Are you able to see the place in the UI that you would try to change?

**Comment by Binita-tech** [comment]
I am setting up environment locally with the help of this documentation https://docs.openrefine.org/technical-reference/build-test-run
Do I have to install OpenRefine to reproduce the issue locally?

**Comment by elroykanye** [comment]
> I am setting up environment locally with the help of this documentation https://docs.openrefine.org/technical-reference/build-test-run Do I have to install OpenRefine to reproduce the issue locally?

Okay @Binita-tech. From what I understand, you may have to run install it. Running the shell or batch script is going to do the trick for you. Just make sure you have JDK1.8+ and Maven installed on your system and available on your path because the scripts call commands from their binaries. Do you need any help with adjusting your path?

**Comment by Binita-tech** [comment]
@elroykanye, I have JDK1.8+ and Maven installed and I have set path also.

>  Running the shell or batch script is going to do the trick for you.

Can you elaborate above sentence more and how can I run?

**Comment by elroykanye** [comment]
Okay, there is shell script (refine) and a batch script (refine.bat). The shell script is for Linux/Mac while the batch is for Windows.
- Depending on the system you are using (Windows or Mac/Linux), you have to run the corresponding script. Do this first.
- If you did the first step and noticed any error about not being able to find JDK or Maven in path, then let me know so I can you help install and set up.

For the first time running the tool, all required is to have maven and Jdk. The script provided does offer a lot of help in configuring and setting up the workspace so you don't have much work to do 😊

**Comment by elroykanye** [comment]
Since you have already set the path, just run the script.
- ./refine (Linux or Mac)
- refine.bat (Windows)

**Comment by thadguidry** [comment]
@Binita-tech our docs provide all of this wonderful information:
Technical docs:  https://docs.openrefine.org/technical-reference/build-test-run
User docs:  https://docs.openrefine.org/manual/installing

**Comment by Binita-tech** [comment]
@thadguidry, I have gone through this documentation, but I am facing difficulty in running refine.bat in the command line. 
After running refine.bat, only logo of OpenRefine is showing in browser and refine.bat command gets paused while running. I have Java 11.0.9 version.

**Comment by thadguidry** [comment]
@Binita-tech usually that means that JAVA_HOME was not set properly to use Java 11+.  You might verify that environment variable is reported as set in the same terminal session you use to launch OpenRefine.

**Comment by Binita-tech** [comment]
![image](https://user-images.githubusercontent.com/78761614/160297356-211d47b2-5ddf-4759-9755-522a413aa467.png)
![image](https://user-images.githubusercontent.com/78761614/160297563-2715a4ca-d796-4e75-9e34-188151bbb8f4.png)
![image](https://user-images.githubusercontent.com/78761614/160297619-f0c26eb7-d6a8-4dfa-a487-caef78c1614f.png)


Please check if it is done rightly or not @thadguidry

**Comment by wetneb** [comment]
Have you installed `npm` as well? It is required now as well. The documentation has been updated but we should also backport the documentation change to previous versions, probably…

**Comment by thadguidry** [comment]
@Binita-tech Yes that looks correct.

**Comment by Binita-tech** [comment]
![image](https://user-images.githubusercontent.com/78761614/160309151-6c1c5cd0-9db5-43e4-8bd6-594d541cb822.png)

@wetneb I have already installed npm in my computer, what should I do next?

**Comment by elroykanye** [comment]
> Have you installed `npm` as well? It is required now as well. The documentation has been updated but we should also backport the documentation change to previous versions, probably…

Hello @wetneb , `npm` is actually available as indicated from the image above.
I think the problem was the version of npm @Binita-tech used. After updating, it should fix things up. 
@Binita-tech please confirm if this works for you...

**Comment by Binita-tech** [comment]
@elroykanye yes, this works for me. Thank you!!
@wetneb, I tried reproducing the issue and what I understood is that I have to put this link -https://docs.openrefine.org/manual/grelfunctions#date-functions under dataPart(below image) function, please correct me if I am wrong.
![image](https://user-images.githubusercontent.com/78761614/160440404-0657e3f8-4088-4de1-9c30-afac1cea25ba.png)

**Comment by antoine2711** [comment]
> @wetneb, I tried reproducing the issue and what I understood is that I have to put this link -https://docs.openrefine.org/manual/grelfunctions#date-functions under dataPart(below image) function, please correct me if I am wrong.

Yes, you are right. This is correct.

Regards, Antoine

**Comment by Binita-tech** [comment]
I am not able to get into which file I have to make changes as there are so many files.
Please guide me to get those files.

**Comment by wetneb** [comment]
@Binita-tech to locate the files you should edit, have you had a look at the method proposed [in the technical reference](https://docs.openrefine.org/technical-reference/contributing#your-first-code-pull-request), in particular at [this technique](https://github.com/OpenRefine/OpenRefine/issues/3137#issuecomment-691649962)?
