### ISSUE TITLE
Error: Form too large

### ISSUE THREAD

**Issue by AliND** [OpenRefine/OpenRefine#1123]
Hi,
Any help is appreciated.

I am having this error: "Error: Form too large"

I tried many methods related to this error as mentioned in previous posts. At last, I followed the instructions/modifications posted earlier and which are connected to posts #908 & #971  (refine.max_form_content_size).

I am running windows with 48GB of rams and 2 Hexacore processors, and unfortunately even after applying the modifications, I am not able to get it to work.

I am not sure I am applying everything correctly. These are the steps:
1- Add "REFINE_MAX_FORM_CONTENT_SIZE=5242880" to refine.ini
2- Add the following below to refine.bat under :gotMemory
  "+if not "%REFINE_MAX_FORM_CONTENT_SIZE%" == "" goto gotMaxFormContentSize
 +set REFINE_MAX_FORM_CONTENT_SIZE=1048576
 +:gotMaxFormContentSize
 +set OPTS=%OPTS% -   Drefine.max_form_content_size=%REFINE_MAX_FORM_CONTENT_SIZE%
 +"
3- Run openrefine.exe (diamond icon).

I understand that running openrefine.exe can override the new commands, but I have no idea how to run refine.bat and if I double-click it, a command window shows for milliseconds and then disappear.

Could you please advise on what is wrong with what I am doing?
Thanks a lot,
Ali

**Comment by tfmorris** [comment]
Sorry to hear you're having difficulty.  Can you provide more context on what you are doing and what the environment is?

What version of OpenRefine? What version of Windows? What browser and version? Is this something you're trying to do interactively? If so, what menus, choices, etc are you selecting? If not, can you post the JSON for the script that you're pasting into OpenRefine's history window.

p.s. Anything you add to `refine.bat` has no effect if you don't actually run `refine.bat`

**Comment by AliND** [comment]
Hi Tom,
Thanks a lot for your reply.

I am using OpenRefine 2.6 Beta1, Windows 7 x64, Chrome v48.

The error occurs when I try to cluster & edit a column (method: key collusion). Once I try to merge the data, this message pops up "Error: Form too large 4467189>1048576".

Apparently, it has to do with the 1MB limit which I am trying to change. I was happy to know that this parameter can be changed but I am not successful in doing that. 

Since refine.ini & refine.bat have to be altered, I need to run refine.bat, otherwise it has no effects as you stated.

I tried running refine.bat by double-clicking and it didn't work (command window shows for milliseconds and then disappears). If I try to run it from the command window, I get: The system cannot find the file refine.ini...etc. There is a link with instructions on how to set JAVA_HOME to point at JDK installation, but the site is down!

Could you please advise if the following is sufficient for overriding the 1MB form limit?

> Alter refine.ini & refine.bat as explained in my initial post, and then run refine.bat and not the executable openrefine.exe file.


If I am correct on that point, then all what I need to do is to learn how to run refine.bat.

Thanks again @tfmorris, Appreciate it.
Ali

**Comment by AliND** [comment]
UPDATE:

Hi again,

I have installed JDK and set the JAVA_HOME variable. Now, I am able to run OpenRefine through refine.bat.

I've replaced refine.bat & refine.ini with the update of @amsardesai ( #908 & #971) and changed the value of "REFINE_MAX_FORM_CONTENT_SIZE" to 10485760 in refine.ini. Unfortunately, I am still getting the same error.

Is't that I have to apply the modification mentioned in #876 first so that the new limit is applied? If this is the case, I am unable to find the file refine.java. In case that is the only additional step for the new parameters to become effective, could you please advise on how to do it?

Thanks & Regards,
Ali

**Comment by thadguidry** [comment]
@AliND If you still need assistance on this issue, then feel free to post to our mailing list.
