### ISSUE TITLE
Quotation marks option doesn't work

### ISSUE THREAD

**Issue by pprasqui** [OpenRefine/OpenRefine#1125]
![capture d ecran 232](https://cloud.githubusercontent.com/assets/7451210/13247525/cba2512c-d9f8-11e5-89c7-6cff35b786d8.png)
Although I've selected the option "Quotation marks are used to enclose cells containing column separators", some quotation marks are still appearing in the cells, thus destroying the right fields allocation. Anyone knows why? 
See input file in https://dl.dropboxusercontent.com/u/10767095/IFS_01-05-2016%2008-53-12-06-000.csv

**Comment by magdmartin** [comment]
Which version of OpenRefine are you using and what is your OS?
I can reproduce the issue with RC2 and linux. 
This may be related to #1034

**Comment by pprasqui** [comment]
2.6 beta 1 on Win 10

**Comment by thatbudakguy** [comment]
**OSX 10.11.6 / OpenRefine 2.6-rc.2**

Also have this issue. The project looks fine in preview and correctly detects that the option is needed, but ignores it when I create the project.

**Comment by thatbudakguy** [comment]
Just reproduced on **Ubuntu 16.04 / OpenRefine 2.7-rc.2** as well.

**Comment by thatbudakguy** [comment]
workaround for me was to upload the `.csv` I was trying to import to Google Drive/convert to Google Sheets, which parsed the file correctly. Then I could use the "import from Google" option in OpenRefine on the newly created sheet and the data came in correctly.

**Comment by wetneb** [comment]
@thatbudakguy Your DropBox link has expired, any chances we could have a new copy? Ideally, a minimal non-working example would be very useful. The following example works fine for me:
```
foo,bar
"hello, world",4
"this, works"
pretty,well
```

**Comment by ettorerizza** [comment]
This may not have anything to do with this, but it often happens that Open Refine fails to parse a bad CSV properly. I had to first open it with Libre Office, save it, then import it in OR. I will try to find an example.

**Comment by ettorerizza** [comment]
Here is this sort of CSV : Libre Office or even old specialized softwares can parse it, but OR 2.7 is struggling.
[Pages_that_link_to_Q5_Wikidata.zip](https://github.com/OpenRefine/OpenRefine/files/1177350/Pages_that_link_to_Q5_Wikidata.zip)

**Comment by thadguidry** [comment]
@ettorerizza what about using Line-based ?  That's sorta OK ?  Just trying to know where in our code the issue really lies.

**Comment by ettorerizza** [comment]
@thadguidry : you're right, it was a bad example: my csv does not contain any column of text with commas, so everything works well with your solution. This is not very bad, but let's say it can annoy people who export strange CSV from old databases.

**Comment by ostephens** [comment]
Hard to analyse without the original file (no longer available on the dropbox link given). However, could potentially be an encoding issue - I can recreate the perceived issue if I try to import (e.g.) a UTF-16 encoded file with UTF-8

Screenshots attached showing how works if encoding set to UTF-16 but not if UTF-8
<img width="1157" alt="screen shot 2017-10-10 at 16 27 33" src="https://user-images.githubusercontent.com/576174/31395177-0eabceb2-add8-11e7-95b2-e7b24f57fc49.png">
<img width="1163" alt="screen shot 2017-10-10 at 16 27 20" src="https://user-images.githubusercontent.com/576174/31395178-0ec38b2e-add8-11e7-83fe-bcad9d9432f8.png">

If this was the issue in this case, then I think the system is behaving as expected - until encoding is correct the data will not import correctly

**Comment by wetneb** [comment]
@ostephens thanks for investigating! let's just close as non-reproducible then.
