### ISSUE TITLE
Extract text from parsed html?

### ISSUE THREAD

**Issue by ciscoheat** [OpenRefine/OpenRefine#1127]
GREL Jsoup is great, but I cannot seem to extract only the text from the html, even though it seems possible in the reference. Like this for example:

`value.parseHtml().text()` or even `value.parseHtml().select('body').text()`

I get the error that function `text` cannot be found.

**Comment by ettorerizza** [comment]
Hi,

Have-you tried htmText() instead of text() ?

2016-04-07 16:25 GMT+02:00 Andreas <notifications@github.com>:

**Comment by ettorerizza** [comment]
htmlText(), sorry.

https://github.com/OpenRefine/OpenRefine/wiki/GREL-Other-Functions

2016-04-07 17:39 GMT+02:00 Ettore RIZZA <ettorerizza@gmail.com>:

**Comment by thadguidry** [comment]
The reference for the functions is here on our wiki:
https://github.com/OpenRefine/OpenRefine/wiki/GREL-Other-Functions#jsoup-html-parsing-functions
use htmlText()
`value.parseHtml().select('body').htmlText()`

**Comment by ciscoheat** [comment]
Perfect, thank you! :)

**Comment by tfmorris** [comment]
Additionally, the select() function returns an array even if there's only a single element, so you'll need an array index.

`value.parseHtml().select('body')[0].htmlText()`
