### ISSUE TITLE
Import json - cannot process Chinese text properly

### ISSUE THREAD

**Issue by joyceho951** [OpenRefine/OpenRefine#1130]
Import .json file with some of the values being in Chinese. 
The records beneath the first record with Chinese values were not imported.

**Comment by tfmorris** [comment]
Do you have an example file that you can provide which demonstrates the problem? That would make it easier to debug.

**Comment by joyceho951** [comment]
Since the issue report system does not support uploading .json, I change the file extension to .txt for upload.
I can only import 9 records (13 rows) of this file. It stopped import at the one with Chinese characters in parameter values using Google Refine v2.5

[20160423_210000_shop.txt](https://github.com/OpenRefine/OpenRefine/files/229279/20160423_210000_shop.txt)

**Comment by sputnik62** [comment]
Anyone working on this?

**Comment by jamessspanggg** [comment]
This issue no longer occurs in the current version. Chinese characters are able to be imported.

**Comment by wetneb** [comment]
Thanks for checking! Let's close this then.
