### ISSUE TITLE
Why n*m*(m-1)/2 not n*m*log(m) for clustering

### ISSUE THREAD

**Issue by kirilligum** [OpenRefine/OpenRefine#1133]
I saw that you implemented VPtree and probably tried it. why did you decide to go with canopy clustering after all? vptree scales better

**Comment by thadguidry** [comment]
Can you describe where in the tree search that the scaling is defined as "better"?  Would like to understand more.  My understanding is that you still have to do k distance calculations and each element has log n levels.
>The time cost to search a Vantage-Point tree to find a single nearest neighbor is O(log n). There are log n levels, each involving k distance calculations, where k is the number of vantage points (elements) at that position in the tree. - https://en.wikipedia.org/wiki/Vantage-point_tree

**Comment by tfmorris** [comment]
The context for this obscure question is apparently this commented out line: https://github.com/OpenRefine/OpenRefine/blob/ddd9bf9aa80a43c68bf6d8fb4dc9d0b8bb29dcd5/main/src/com/google/refine/clustering/knn/kNNClusterer.java#L236-L238

from the original implementation over a decade ago. It certainly would be easy enough to offer the user a choice if we could characterize their performance profiles in a way that would make sense to a user (and VP Trees outperform the Pass-Join algorithm).

**Comment by thadguidry** [comment]
@kirilligum @tfmorris I reached out to Stefano about this and he replied back with this when I asked him about VPTree and if he had issues with it at the time :

> I have zero recollection of why... O() notation is tricky because it hides constants so it's possible that even if one algo is better from a computational complexity perspective, it's actually slower in practice because of implementation or size of the data used.
>
>Honestly, the only way to know is to try the two and measure the difference.
>
>Sorry if that's not really that helpful :)
