### ISSUE TITLE
Add support for JSON Lines / NDJSON / Streaming JSON

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#1135]
APIs which want to support incremental access and parsing sometimes use this format instead of the traditional JSON format which has a single JSON object or array at the top level. It consists of a series of JSON objects or arrays on single lines, each separate by a newline. Because JSON parsing ignores leading trailing whitespace, this also support CRLF delimiters.

It goes by various names with minor differences in the spec:
- Newline Delimited JSON - http://ndjson.org/
- JSON Lines - http://jsonlines.org/
- jsonl

**Comment by zacharynanfelt** [comment]
@tfmorris, as the most (thumbs up) voted issue for this project that is currently open, I thought I would look into it.  
I just tried verifying this with the [Easy Nested Example.txt](https://github.com/OpenRefine/OpenRefine/files/2901877/Easy.Nested.Example.txt) from http://jsonlines.org/examples/ and selecting "Parse data as: JSON Files" which provided the attached result.  

Can we close this issue?

![screen shot 2019-02-25 at 10 09 35 am](https://user-images.githubusercontent.com/517872/53358623-af3a2380-38e5-11e9-93f8-355e41fe6e88.png)

**Comment by wetneb** [comment]
@zacharynanfelt good catch! It seems to work indeed. We have plenty of other good first issues if you want to get started with contributing to OpenRefine though! Happy to help you find something to your taste if you need.

**Comment by tfmorris** [comment]
@zacharynanfelt Welcome to the community! Thanks for validating that this works now.
