### ISSUE TITLE
Issues on OS X El Capitan

### ISSUE THREAD

**Issue by standage** [OpenRefine/OpenRefine#1140]
I'm trying unsuccessfully to install OpenRefine on OS 10.11.5.

- When I launch the latest version (2.6-rc2) it quits before it finishes initializing, without any sort of warning/error message.
- For the previous version (GoogleRefine 2.5), my first couple of attempts to launch were hampered by various problems. First the operating system had me install a legacy version of Java. Then I got the "move to trash" message. I was able to fix this by changing the security settings as described elsewhere, but then I just got the same behavior as before: GoogleRefine quits before it even finishes launching.

Is this a known issue?

**Comment by standage** [comment]
Well, 2.6-rc2 seems to run fine after restarting the computer. Sorry this might be hard to reproduce, given that I was trying with 2 different versions, with vs without legacy Java, etc. The only clue I can provide is that my last few attempts to launch 2.5 before restarting my computer, an error dialog popped up very briefly (i.e. <2 seconds) referencing some kind of binding exception and stating that the address was already in use.

**Comment by WalnerPessoa** [comment]
try to downgrade java

**Comment by WalnerPessoa** [comment]
I uninstalled the newest version of java and install old version of java, so I installed google refine Version 2.5 [r2407].

**Comment by magdmartin** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/openrefine) for support type question.
