### ISSUE TITLE
how to install openrefine in window 10

### ISSUE THREAD

**Issue by Hyeongsu** [OpenRefine/OpenRefine#1144]
I can't install openrefien in my computer.
I use OS windows 10. 
I downloaded openrefine-win-2.6-rc.2.zip through https://github.com/OpenRefine/OpenRefine/releases
But, when I was installing openrefine, I received message like that. 
![image](https://cloud.githubusercontent.com/assets/20904775/17478977/8ac67512-5daa-11e6-9fc5-2a19b73f57b0.png) How to install openrefine.....? please teach me. 

my email address is everydaypeace4u@hanmail.net

**Comment by magdmartin** [comment]
For support related question please use the [mailing list](https://groups.google.com/forum/#!forum/openrefine)
