### ISSUE TITLE
Column names issue when importing json file

### ISSUE THREAD

**Issue by juanmas07** [OpenRefine/OpenRefine#1147]
In Version 2.6-rc.2 [TRUNK] I'm getting someting like this in all the column names:

_ - _ - year

although the json is well formed:

[{"id":"1021","line_name":"W07004","breeder":"Barrow","origin":"CBS","year":"2010","status":...

**Comment by Opennat** [comment]
Same https://github.com/OpenRefine/OpenRefine/issues/1017

**Comment by wetneb** [comment]
Closing as a duplicate of #1017.
