### ISSUE TITLE
Importing json file options bug

### ISSUE THREAD

**Issue by juanmas07** [OpenRefine/OpenRefine#1148]
When importing from json in form Parse data as:
clicking in field: **Field Trim leading & trailing whitespace from strings**
changes the checkbox for field: **Parse cell text into numbers, dates, ...**

for="guess-407969" should be for="trim-812080"

**Comment by wetneb** [comment]
@juanmas07 I don't understand your last line - where do you see `for="guess-407969"` and why should it be different?

**Comment by wetneb** [comment]
No response, closing as not reproducible.
