### ISSUE TITLE
Unexpected program error 

### ISSUE THREAD

**Issue by ignacio-chiazzo** [OpenRefine/OpenRefine#1149]
I am using the 2.6 rc2, and the application process is killed after being used for a time (for each 30 minutes approximatelly).

SO : El Capitan 10.11.5
Java 8

**Comment by wetneb** [comment]
@ignacio-chiazzo can you provide more detail - what operation are you doing, what data are you working on? can you share the logs?

**Comment by ignacio-chiazzo** [comment]
Couldn't reproduce it. I will open the issue if I see it again.
