### ISSUE TITLE
Add a "move column before/after" in column contextual menu

### ISSUE THREAD

**Issue by ronanguilloux** [OpenRefine/OpenRefine#1150]

**Comment by ericjarvies** [comment]
Perhaps adding a contextual menu shortcut link, e.g.-

Move column to beginning
Move column to end
Move column left
Move column right
**Re-order columns**

wherein **"Re-order columns"** opens what can otherwise be found (_opened_) here;

**All -> Edit Columns -> re-order / remove columns...**

**Comment by elroykanye** [comment]
@wetneb  , I checked this out and realised it has already been implemented.

**Comment by wetneb** [comment]
Happy to close this as well, thank you!
