### ISSUE TITLE
poor website layout for open refine download page

### ISSUE THREAD

**Issue by daviddou82** [OpenRefine/OpenRefine#1151]
I would like some refinement to be made in the main download page.
http://openrefine.org/download.html

I would like the stable version be placed at the top of the download page.  All other beta versions should be moved to the bottom.  

A new user might accidentally download the beta versions.

**Comment by javian** [comment]
You can submit a PR to https://github.com/OpenRefine/openrefine.github.com to change it.

**Comment by magdmartin** [comment]
The 2.6-beta version contain a lot of improvement compared to the 2.5 version (see [release note](https://github.com/OpenRefine/OpenRefine/releases/tag/2.6-beta.1)) and the RC1 and RC2 have minor improvement and new language packages. This is more a release naming issue than anything else and I recommend using the RC2 version to new users.
