### ISSUE TITLE
Project not found when running from supervisor

### ISSUE THREAD

**Issue by juanmas07** [OpenRefine/OpenRefine#1152]
I've created a project in refine, I've ran the program (/home/juan/openrefine-2.6-rc.2/) with the command:

`./refine -i 0.0.0.0
`

Now, I'm using the next supervisor script to run it, but the project does not show up (unless I cd to the openrefine directory, and run it from there)

```
[program:refine]
directory=/home/juan/openrefine-2.6-rc.2/
command=/home/juan/openrefine-2.6-rc.2/refine -i 0.0.0.0
autostart=true
autorestart=true
```

So I cannot use supervisor to see the current projects. Of course I can export / import but that's not the idea

**Comment by jackyq2015** [comment]
There is a user option for supervisord.

user=juan

The supervisord can not locate the project location since it's running
under another user.

**Comment by wetneb** [comment]
Looks like the user is happy with the proposed workaround.
