### ISSUE TITLE
split in multiple cells leaves the remaining cells as blank

### ISSUE THREAD

**Issue by ignacio-chiazzo** [OpenRefine/OpenRefine#1153]
I have a simple table like this :

         id | name
         -------------------
         1 | Jack, Jeff, Win
         -------------------
         2 | Jonhy, chin
I want to split the cell name by "," and want to preserve the id, so after the split, the table
 should look like this :

         id | name
         -------------------
         1 | Jack
         -------------------
         1 | Jeff
         -------------------
         1 | Win
         -------------------
         2 | Jonhy
         -------------------
         2 | chin 

HOWEVER, if I click on _edit cell > split multiple-values_  the cell will be separated but the id will be blank (in the case that the cell was separated). Below I gave an example that shows you how it looks like after clicking on it

           id | name
         -------------------
            1 | Jack
         -------------------
         null | Jeff
         -------------------
         null | Win
         -------------------
            2 | Jonhy
         -------------------
         null | chin 

http://stackoverflow.com/questions/39317899/open-refine-split-in-multiple-cells

**Comment by ignacio-chiazzo** [comment]
Filling down the cells solved the issue

**Comment by tfmorris** [comment]
Glad you figured it out!

**Comment by ignacio-chiazzo** [comment]
@tfmorris Is there a way to fill dow all the columns with one click? Instead of clicking in each columns and filling down?
