### ISSUE TITLE
create project button no effect

### ISSUE THREAD

**Issue by debpaul** [OpenRefine/OpenRefine#1156]
Hi. New problem for me today. Tried to Create Project (xls file, or csv file), and nothing happens. Any ideas? Windows 10 Pro, 64-bit OS, Surface Pro 4, using Firefox 49.0.1, JAVA version 8 Update 101. Java starts, and I can open already existing projects. But, I cannot create a new one. 370 GB free space. Tried updating Java, now services don't start and so Refine not working at all. Please help.

**Comment by joewiz** [comment]
Any luck with Chrome? I've seen other users report problems with Firefox here.

**Comment by wetneb** [comment]
@debpaul Thanks for the bug report. What file did you use to create a project? What happens exactly when you try to create the project? Do you get an error message?

**Comment by wetneb** [comment]
Closing as non-reproducible.
