### ISSUE TITLE
Advanced button disabled in RDF extension 0.9 

### ISSUE THREAD

**Issue by rjakshayjain13** [OpenRefine/OpenRefine#1159]
While using RDF extension 0.9, when I edit RDF skeleton and add prefixes, the advanced button for adding a new prefix appears disabled. How do I enable this button to add a prefix of local ontology file?

**Comment by wetneb** [comment]
@rjakshayjain13 You should rather report this issue at https://github.com/fadmaa/grefine-rdf-extension , this is the repository for the core functionality of OpenRefine.
