### ISSUE TITLE
Java 9 problems

### ISSUE THREAD

**Issue by hotnuts21** [OpenRefine/OpenRefine#1162]
Hi Guys,

When trying to start the OpenRefine on Ubuntu, I kept getting the 'error' cannot find the java environment ...make sure $JAVA_HOME is pointing to a proper Java installation.

Well it was, it was pointing to /usr/lib/jvm/java-9-openjdk-amd64/ but I kept getting the error. 

In the end I changed my refine.ini and pointed it to /usr/lib/jvm/java-8-openjdk-amd64/ and it worked fine.

Both are valid java installs so not sure why Java 9 is throwing an error, but thought I would flag it up.

Paul

**Comment by thadguidry** [comment]
We have not compiled against Java 9 yet, or tested against it yet.  Only Java 8 so far...but sure, we'll eventually release an updated OpenRefine that supports Java 9 and perhaps utilize a few new features and slightly improve performance in a few areas of OpenRefine.

If you feel that Java 9 support is worthwhile, and potentially encourage our developers here to get Java 9 supported sooner... feel free to place a bounty of whatever $$$ against this issue you have opened at https://www.bountysource.com/teams/openrefine/issues

**Comment by augusto-herrmann** [comment]
For anyone also experiencing the problem, I can confirm that the following workaround for using Java 8 currently works:

```
sudo apt install openjdk-8-jre
export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
./refine
```

**Comment by jackyq2015** [comment]
The output format out java -version for Java 9 is different from 6,7,8. That's where the problem comes from. Need to change the startup script to address this.
