### ISSUE TITLE
Column numbers

### ISSUE THREAD

**Issue by griii2** [OpenRefine/OpenRefine#1163]
I am working with a document with many columns (up to 100) and it would be tremendously helpful to see column numbers in the top row.

Also many thanks to everyone here for this amazing product.

**Comment by thadguidry** [comment]
You can get that by changing your importer options for the header row.
By not selecting for a header row (0) then you will get OpenRefine default column naming convention:

Column 1 , Column 2 , Column 3 ...

@griii2 Does that help your use case ?

**Comment by griii2** [comment]
That's amazing, thanks!
