### ISSUE TITLE
"Search for match" ignores the reconciliation service you've used and only searches Freebase

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#117]
_Original author: rob.02...@gmail.com (August 19, 2010 09:24:23)_

With the development build:
1. Choose a column, select Reconcile -&gt; Start reconciling
2. Choose to reconcile against a non-Freebase reconciliation service
3. For a cell that has multiple matches, click the &quot;search for match&quot; link

My expectation is that this &quot;search for match&quot; would search the reconciliation service I'd chosen, and show me matching results.

Instead &quot;search for match&quot; only searches Freebase.

I'm using the latest project source code as at Aug 19 2010.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=117_
##

**Comment by thadguidry** [comment]
@wetneb Do you know if this functionality is working against Wikidata or any standard reconcile service, since Freebase is now deprecated and you removed some legacy Freebase stuff from our code ?

**Comment by wetneb** [comment]
@thadguidry I don't see why this bug would still be present, because clearly for Wikidata the search works and does not fall back on Freebase… And there is nothing specific about Wikidata in the code (except that the service is configured by default). I think we can close this.

**Comment by thadguidry** [comment]
@wetneb awesome.  Thanks for your input. Closing it.
