### ISSUE TITLE
JSON Commands Written for 2.6 Produce Different Results in 2.7rc1

### ISSUE THREAD

**Issue by scottythered** [OpenRefine/OpenRefine#1173]
Version used: Google Refine 2.6 v. 2.7cr1
Operating Systems: Windows 10
Browser: Chrome

I'm working with a large set of cleaning/normalization commands for tabular data. The commands were written/extracted from commands in Google Refine 2.6; however, when the same data and commands are executed in 2.7cr1, I am seeing unexpected NULL and other data for lines that should be blank (see screenshots attached). Example data and commands are also attached.

![refin-2-6](https://cloud.githubusercontent.com/assets/11927373/23140334/9b4cb4d0-f776-11e6-8510-4e086693c967.png)

![refin-2-7](https://cloud.githubusercontent.com/assets/11927373/23140333/9b4c98d8-f776-11e6-84f0-838c889f7087.png)

[example.txt](https://github.com/OpenRefine/OpenRefine/files/788425/example.txt)

[Cleaning-commands.txt](https://github.com/OpenRefine/OpenRefine/files/788427/Cleaning-commands.txt)

**Comment by thadguidry** [comment]
Good Catch Scotty !

I'll take a look later tonight and let you know what I find out.

Thanks for this report,

-Thad
+ThadGuidry <https://www.google.com/+ThadGuidry>

**Comment by thadguidry** [comment]
Looks like your operation history is not exactly aligned with the dataset... or you missed an operation (or more) somehow...

In the below section...I get a ERROR for column not found for "264$c 2" removal.
The column-split operation before it however, makes a "264$c 1" column.

```
  {
    "op": "core/column-split",
    "description": "Split column 264$c by separator",
    "engineConfig": {
      "mode": "record-based",
      "facets": []
    },
    "columnName": "264$c",
    "guessCellType": false,
    "removeOriginalColumn": true,
    "mode": "separator",
    "separator": "||",
    "regex": false,
    "maxColumns": 2
  },
  {
    "op": "core/column-removal",
    "description": "Remove column 264$c 2",
    "columnName": "264$c 2"
  },
```

**Comment by scottythered** [comment]
HI Thad, thanks for looking into this. The commands are set up so that they can run if a column is generated, or the command can die if a column wasn't generated by a previous command. The issue I'm raising is why in 2.7 the commands generate the NULL values in the "959$a" column and the value in the "link" column -- they should both be set to blank, as what happens in the 2.6 version, right?

**Comment by thadguidry** [comment]
OK understood.  Errors are to be expected then with your JSON operations....OK.

So, Looks like real issue with ```null``` is with the simple operation at step 66 that uses
```
value.toString()
```
on column ```959$a```
Another thing I'm wondering is if your intent might have been to do a blankdown on that column instead ?  There are 2 record rows under ```10706``` ... in the 700 column for the Added Entry-Personal Name in Marc 21 format I notice :)

**Comment by thadguidry** [comment]
@scottythered found it.  We weren't passing a valid test case in the past that would throw an error.  Tom Morris fixed this and now doing ```value.toString()``` will actually give you the ```null``` as a real String literal of ```"null"```

Details here: https://github.com/OpenRefine/OpenRefine/pull/915
The code change itself is here: https://github.com/OpenRefine/OpenRefine/commit/4eb6eb6eda50f4cbf81c937219c02227d9c4fb29
Test is here: https://github.com/OpenRefine/OpenRefine/blob/master/main/tests/server/src/com/google/refine/tests/expr/functions/strings/ToFromConversionTests.java#L117
