### ISSUE TITLE
[macOS] 2.7 rc1 isn't codesigned

### ISSUE THREAD

**Issue by cwhits** [OpenRefine/OpenRefine#1174]
2.7 rc1 isn't codesigned, 2.6 rc1 was.

```
$ codesign --display -r- --deep -v /Volumes/OpenRefine\ 2.7-rc.1/OpenRefine.app
/Volumes/OpenRefine 2.7-rc.1/OpenRefine.app: code object is not signed at all
```

```
$ codesign --display -r- --deep -v /Volumes/OpenRefine\ 2.6-rc1/OpenRefine.app
Executable=/Volumes/OpenRefine 2.6-rc1/OpenRefine.app/Contents/MacOS/JavaAppLauncher
Identifier=com.google.refine.Refine
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20100 size=233 flags=0x0(none) hashes=5+3 location=embedded
Signature size=1277
Signed Time=Apr 29, 2015, 10:36:03 PM
Info.plist entries=16
TeamIdentifier=not set
Sealed Resources version=2 rules=12 files=491
Nested=PlugIns/jdk1.8.0_45.jdk
designated => identifier "com.google.refine.Refine" and certificate leaf = H"3324785d3f758d78f729a7424a75447b15364f98"
```

**Comment by thadguidry** [comment]
@jackyq2015 Can you take a look into this ?  Did you build with the right parameters ? See https://github.com/OpenRefine/OpenRefine/blob/master/refine#L540

**Comment by jackyq2015** [comment]
There was some package issue on my Mac. Just fixed it and built a signed one. The old one was replaced from the 2.7.rc.1 release.

**Comment by cwhits** [comment]
Was a different cert used to sign the .app this time? The cert leaf has changed since 2.6.

Could you look into using a shared codesigning cert if different people are building and signing the app or getting an Apple Dev ID?

Thanks!
