### ISSUE TITLE
Line breaks in tab-delimited text file (TSV)

### ISSUE THREAD

**Issue by adehner** [OpenRefine/OpenRefine#1176]
When importing a TSV file, line breaks within a tab-separated value are treated as the end of a record. This results in incorrect parsing of the TSV file. Selecting "Quotation marks are used to enclose cells containing column separators" does not solve the problem.

Example TSV file:
https://drive.google.com/file/d/0BzGHHDat663scjVMRG0wd29QUHc/view?usp=sharing

Is this a bug? 
And is there a workaround?

**Comment by thadguidry** [comment]
@adehner If you look at your TSV file in Notepad... what is the Character or Control Char that tells you and me that the line has ended ?  Things like this are usually a data problem in the original file when it was created.

If you have mixed CR/LF and LF without always enclosing quotes for all your data fields, then OpenRefine will not be able to figure out when a line ends or begins either.

Try to export from your original data source and select to "always enclose columns/fields with quotes" or similar.  Then try importing into OpenRefine.

However, if your stuck with this really bad format of a file...then your only recourse is to try to use the Line-based importer in OpenRefine... but even that might be wrong, if your original data is so bad that even you can't see some kind of pattern of when a line starts or ends in Notepad.  If you can see a true pattern that signifies when a line should end, then you can use external scripting tools (Python, SED, etc) to try to clean it up, wrap with enclosing quotes, and then output a TSV or CSV file with meaningful lines.

Let us know.

**Comment by adehner** [comment]
Thank you. Unfortunately the system outputs this wonky data, without config options to improve the format. Sometimes bad OCR results in characters that split records unpredictably. We will probably need to use scripting between system export and OpenRefine import.

**Comment by Tech-Horizon** [comment]
when importing to excel the wizard does not ask for row separator. it treats both CRLF and LF as row seperator . if it defaults to only CRLF  then it could work.
