### ISSUE TITLE
Homebrew installation returns "No available Cask for openrefine-dev"

### ISSUE THREAD

**Issue by Archaeo-Programmer** [OpenRefine/OpenRefine#1182]
I have installed many things through homebrew on my computer, which is a MacBook Pro running macOS Sierra Version 10.12.3. However, when I enter the code `brew cask install openrefine-dev`, it returns the following errors:

Error: No available Cask for openrefine-dev
Error: nothing to install

I have not been able to replicate this with other programs. Thanks.

**Comment by thadguidry** [comment]
@joewiz Can you assist @Archaeo-Programmer with this issue ?

**Comment by joewiz** [comment]
@Archaeo-Programmer Could you try this command?

    brew tap caskroom/versions

Then do the install again:

    brew cask install openrefine-dev

Please let me know if you have any success.

**Comment by Archaeo-Programmer** [comment]
Yes, that did the trick. Everything installed just fine. Thanks!

**Comment by joewiz** [comment]
@Archaeo-Programmer Thanks for the report! I've updated the homebrew-based installation instructions with this additional step. I think I had already performed that step on my own system to access other version-specific casks, so I neglected to include it in the steps that first-time users would need to run. Thanks again!

**Comment by Archaeo-Programmer** [comment]
Great, thanks so much for the reply, and updating the instructions with additional step. I was unaware that this was a necessary step for some casks. Thanks!

**Comment by joewiz** [comment]
Yes, Caskroom only puts an app's current stable release in the primary caskroom tap. Pre-releases, betas, and version-specific builds go into the versions tap. OpenRefine this fits into the latter, and as soon as a final release is issued we will submit a PR for a new `openrefine` cask in the core caskroom tap.
