### ISSUE TITLE
GREL OR boolean is not allowing more than two conditions

### ISSUE THREAD

**Issue by BobHarper1** [OpenRefine/OpenRefine#1183]
The [Wiki](https://github.com/OpenRefine/OpenRefine/wiki/GREL-Boolean-Functions) states:

> ### or(boolean b1, boolean b2, ...)
> 
> Logically OR two or more booleans to yield a boolean. For example, `or(1 < 3, 1 > 7)` returns `true` because at least one of the conditions (the first one) is true.

However, in my GREL expression where I want to use more than two (regular expression) booleans
`if(or(isNotNull(cells['column1'].value.match(/A/)),isNotNull(cells['column1'].value.match(/B/)),isNotNull(cells['column1'].value.match(/C/))),"This matches","This does not match")`

I get 

> Error: or expects two booleans

Granted that there's probably a better way to write my expression - I would have expected that `or()` would accept more than two conditions.

If I were to reduce that to only two conditions, vis:

`if(or(isNotNull(cells['column1'].value.match(/A/)),isNotNull(cells['column1'].value.match(/B/))),"This matches","This does not match")`

it does work as expected.

Either the boolean operator is not working as it should, or the documentation is wrong... or my reading of it is wrong.

**Comment by BobHarper1** [comment]
Is this relevant line of code?
[com.google.refine.expr.functions.booleans.Or.java](https://github.com/OpenRefine/OpenRefine/blob/d5fb07384242d07241b0ce103c47d930046f1135/main/src/com/google/refine/expr/functions/booleans/Or.java#L49)

Not a java guy, but should it be `if (args.length >= 2 ...`??

**Comment by jackyq2015** [comment]
Though or only accept 2 arguments, but you can use multiple boolean operator to achieve what you need. something like this:
`or(or(isNotNull(cells['column1'].value.match(/A/)),isNotNull(cells['column1'].value.match(/B/))),isNotNull(cells['column1'].value.match(/C/)))`

**Comment by BobHarper1** [comment]
Ok, so the documentation needs to change then.

**Comment by jackyq2015** [comment]
Wiki mentioned above fixed.
