### ISSUE TITLE
Can cluster reapply as a operation

### ISSUE THREAD

**Issue by sheva605** [OpenRefine/OpenRefine#1184]
If I use facet cluster to merge based on fingerprint and ngram-fingerprint in a sample file with other steps. I cannot apply the whole JSON operation to a similar file, because the cluster step is mass edit. Is there a way to walk around it, because I don't care what to merge, I just want to merge everyone based on those two methods.

**Comment by thadguidry** [comment]
@sheva605 sorry but this doesn't make a lot of sense to me.  If you want to exclude parts of the Undo/Redo history when you do Extract...just uncheck the operation box.  Can you explain further what you mean by merge everyone based on those two methods ? which methods ?

**Comment by sheva605** [comment]
@thadguidry
Every time I use cluster feature in the text facet, basically there are two methods. For the key collision, there are four functions. If I select all and merge them together, this process will be shown up as a mass edit as a part of the Undo/Redo history which means if I copy the whole history and paste into a same format but a different data file, those mass edit steps wouldn't be processed. I want to use the whole Undo/Redo history as a script to fully automate my daily task which is to merge data based on the keying function without human intervention.

**Comment by thadguidry** [comment]
@sheva605 Currently we don't support merging data by applying String Similarity functions directly.  Instead our Clustering functions create "mass edit" operations with From / To as shown in the below example export, and what your describing as not wanting OpenRefine to peform.  We could add the feature that your wanting, but this would need to be a feature request and we might never get to it, or you could post a bounty $$$ to get someone to hack on it for you.

For your wants and needs, there are other String Similarity tools like Python scripts and libraries, [here's one](http://chairnerd.seatgeek.com/fuzzywuzzy-fuzzy-string-matching-in-python/) , even Office 365 has a feature or plugin for merging similar strings.  Do some web searches, post on forums, and you'll find lots of other tools and ways to accomplish this without using OpenRefine. Best of luck to you.

```json
[
  {
    "op": "core/mass-edit",
    "description": "Mass edit cells in column Column 1",
    "engineConfig": {
      "mode": "row-based",
      "facets": []
    },
    "columnName": "Column 1",
    "expression": "value",
    "edits": [
      {
        "fromBlank": false,
        "fromError": false,
        "from": [
          "Michael",
          "Micheal"
        ],
        "to": "Michael"
      },
      {
        "fromBlank": false,
        "fromError": false,
        "from": [
          "George",
          "Gorge"
        ],
        "to": "George"
      }
    ]
  }
]
```
