### ISSUE TITLE
Error While uploading excel

### ISSUE THREAD

**Issue by MayerSonawane** [OpenRefine/OpenRefine#1186]
Hi,

this is the first time I am using OpenRefine.
While uploading the excel file, I am getting following error- 

![image](https://cloud.githubusercontent.com/assets/24365269/24806821/1210dd86-1b84-11e7-9c49-4b887834a273.png)

 I changed the location of excel and tried, still facing same issue.

Could you please help me for this.

**Comment by jackyq2015** [comment]
Can you describe how you do the upload and the full path of the file?

**Comment by MayerSonawane** [comment]
Ohhh Got it.. I can upload excel only by Google chrome. 

Thanks, Jacky
