### ISSUE TITLE
Add column by fetching URLs: adding authentication headers

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1187]
Some web services use HTTP headers to authenticate clients (for instance, the Twitter API). OpenRefine should allow users to define a list of headers to be attached to each request.

**Comment by thadguidry** [comment]
@wetneb You gonna hack on this ? :)  Perhaps some of the extensions might have some reusable code ?

**Comment by thadguidry** [comment]
@wetneb I tried :)  Thanks for helping out where you can, nonetheless.

**Comment by wetneb** [comment]
This issue is a duplicate of #218, sorry.
