### ISSUE TITLE
JAVA_HOME misdirect - bin/java/bin/java

### ISSUE THREAD

**Issue by davidhaynz** [OpenRefine/OpenRefine#1188]
Just installed latest version on Ubuntu 16.10 but on start-up it kept throwing the error: "Could not find the 'java' executable at '$JAVA' (etc) 
I noticed that the java path ended in .../bin/java/bin/java
So I edited line startup bash script at line 863 to JAVA="$JAVA_HOME"  (i.e. removing /bin/java) and it worked fine after that.
Note my JAVA_HOME path was correctly set in /etc/environment

**Comment by jackyq2015** [comment]
what's your JAVA_HOME? seems a wrong JAVA_HOME setting.
