### ISSUE TITLE
can openrefine import  text  data?

### ISSUE THREAD

**Issue by xiaoxiaohouzi** [OpenRefine/OpenRefine#1190]
in the example , the openrefine may be can import the   excel , json etc, this is  
strucuture data , like the  database data.  can openrefine import text data  and dispose text data?

**Comment by thadguidry** [comment]
This is a question.  Not an issue.  Please ask questions on our mailing list.

(Yes OpenRefine can read in CSV files or just Lines of text using Line-based importer)

Please ask further questions on our helpful mailing list and do not open issues on Github which are used for opening bug reports or feature requests. Thanks.
