### ISSUE TITLE
Phonetic Fingerprint

### ISSUE THREAD

**Issue by ignacio-chiazzo** [OpenRefine/OpenRefine#1192]
I didn't find whether the algorithm "Phonetic Fingerprint" supports other languages that english or german.

If not, is there an idea to implement it in the future?

Thanks for sharing this awesome tool and trying to keep it updated 👍

**Comment by thadguidry** [comment]
We use these that support English and German.
(we could add others or you or someone else could with a bit of Java and a pull request)

org.apache.commons.codec.language.Metaphone;
org.apache.commons.codec.language.DoubleMetaphone;
org.apache.commons.codec.language.ColognePhonetic;
org.apache.commons.codec.language.Soundex;

and Metaphone3 ... there are some good code comments from developer Lawrence Philips in here about how Metaphone3 works with English and its keying system https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/clustering/binning/Metaphone3.java

German language is support uses. 
https://commons.apache.org/proper/commons-codec/apidocs/index.html?org/apache/commons/codec/language/ColognePhonetic.html
