### ISSUE TITLE
Feature Request: Chrome Extension/Android App

### ISSUE THREAD

**Issue by jwillmer** [OpenRefine/OpenRefine#1196]
With the Chromebooks, Android PC's and the world moving applications to the WWW it would be nice to be able to have a version of OpenRefine that runs on Chrome/Android.
I don't know how easy it is to (auto?) transform the Java code to JavaScript for a Chrome extension but I guess for an Android app the biggest workload might be the GUI.

Please feel free to use this issue to discuss about the possibilities as well as if it might make sense. I obviously had the idea as I was working on my Chromebook.

**Comment by jackyq2015** [comment]
I haven't used chromebooks or Android PC. I would image that OR can run
under Android PC as a java application. For Chromebooks, maybe need much
more work to embed the server side code into the Chrome.

As long as there's fair amount of user base it make sense.

**Comment by jwillmer** [comment]
There is a [web server](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en) for Chrome so at least it is possible to host it inside the browser.

**Comment by thadguidry** [comment]
This would need to be a fork of OpenRefine that someone else can certainly maintain.  As it is now, our developer resources are already constrained enough for existing feature requests and user bases on Linux, PC, and Mac.  

Personally, I think getting OpenRefine to run on alternate platforms would be a lofty but educational goal for someone to hack on, if not limiting.

**Comment by uogbuji** [comment]
Just noting for anyone who stumbles on this that you can run OpenRefine no problem on modern Chromebooks with Crostini (Linux) support.

**Comment by thadguidry** [comment]
@uogbuji write up a blog post on how to do that and mention here!

**Comment by hywu0110** [comment]
I just found this and wanted to say this link (see below) helped me!
https://gist.github.com/organisciak/3e12e5138e44a2fed75240f4a4985b4f
