### ISSUE TITLE
HTML/CSV export corrupts UTF-8 characters outside of Basic Multilingual Pane (BMP) ie code point >10000

### ISSUE THREAD

**Issue by Yuutakasan** [OpenRefine/OpenRefine#1197]
OpenRefine 2.7 rc2

After reading UTF 8 file and executing export as UTF 8 file, garbled characters occurred.

displayed characters
![image](https://cloud.githubusercontent.com/assets/1161494/26835736/e9cb538c-4b13-11e7-9760-4e55f39140fb.png)
有限会社なべ茶屋あさ𡌛

Exported garbled characters
![image](https://cloud.githubusercontent.com/assets/1161494/26835844/1ed2dca8-4b14-11e7-94b1-4f835aee0b9a.png)
有限会社なべ茶屋あさ����

other garbled export charactor sample
𣘺𣳾

**Comment by thadguidry** [comment]
@Yuutakasan hmm, that's weird.  What is interesting is that it is showing 4 bytes (4 question marks) to hold just 1 character.  I see that the code for that last character is actually 6 bytes however (which is the maximum that UTF-8 can hold per character.  

𡌛  =  \x0A\xF0\xA1\x8C\x9B\x0A

Further interesting is that when I copy your last character, I actually get...

ጛ = \xE1\x8C\x9B

instead of

𡌛 = \xF0\xA1\x8C\x9B

@jackyq2015 Can you debug this ?

**Comment by Yuutakasan** [comment]
I will attach a sample file for reference.

import file
[import.txt](https://github.com/OpenRefine/OpenRefine/files/1055560/import.txt)
export file
[export.txt](https://github.com/OpenRefine/OpenRefine/files/1055563/export.txt)

**Comment by thadguidry** [comment]
@Yuutakasan When I export your import.txt file... I get
![capture](https://user-images.githubusercontent.com/986438/26838140-e1afe696-4aa4-11e7-900a-0cf0ca930d25.PNG)

有限会社なべ茶屋あさ𡌛

You are probably not using a viewer like Notepad++ or similar that can show that last character as being \xED\xA1\x84\xED\xBC\x9B  ?

**Comment by Yuutakasan** [comment]
I currently use EmEditor, I will try using Notpad ++.
EmEditor
https://www.emeditor.com/

**Comment by Yuutakasan** [comment]
I was able to reproduce the same phenomenon.
![image](https://user-images.githubusercontent.com/1161494/26838356-cf2aabfc-4b1a-11e7-8982-ef7a8d111911.png)

**Comment by Yuutakasan** [comment]
thank you. @thadguidry. 
I tried testing with multiple character codes.
It seems that a character with a code point of 10000 or more will be garbled.

import txt
[import-test-sample.txt](https://github.com/OpenRefine/OpenRefine/files/1055742/import-test-sample.txt)
export txt
[export-test-sample-txt.txt](https://github.com/OpenRefine/OpenRefine/files/1055746/export-test-sample-txt.txt)

**Comment by thadguidry** [comment]
@Yuutakasan Thanks, we'll have to let @jackyq2015 look into this specifically.  My hunch is that we might not actually be storing it correctly in cell and so this https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/exporters/CsvExporter.java#L108 might be giving back the wrong data in the first place.  Otherwise its an issue in csvwriter itself here https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/exporters/CsvExporter.java#L114

**Comment by jackyq2015** [comment]
can you  try to add -Dfile.encoding=UTF-8 to java command options to enforce the encoding?

**Comment by Yuutakasan** [comment]
OK.I will try it!

**Comment by Yuutakasan** [comment]
@jackyq2015 
Can I test by adding "-Dfile.encoding = UTF-8" setting to the openrefine.l4j.ini file?

**Comment by thadguidry** [comment]
@Yuutakasan Yes, but you can also test it by adding it to the refine.ini file and starting refine.bat or refine.sh if your on Linux.  Just uncomment the JAVA_OPTIONS= line

**Comment by Yuutakasan** [comment]
Since there is no pervert, I was worried whether the setting really worked.
it is executed once, I will share the result later.

**Comment by jackyq2015** [comment]
@Yuutakasan  Given your description, your file is not properly decoded as utf8. that's why I asked you to enforce it. Please note that system cannot 100% accurate to detect the encoding of random stream. There is some library like icu4j can help to improve the accuracy.  Actually there is a [PR](https://github.com/OpenRefine/OpenRefine/pull/1094/files)(not merged yet) to introduce it. If you want to wet your hand, you can create your own branch and merge the PR to your own branch and have a try.

**Comment by Yuutakasan** [comment]
@jackyq2015 @thadguidry 
Sorry for being late. I tried the settings I got the other day.

1. I downloaded openrefine - 2.8.
2. It changed to the following setting.
[openrefine.l4j.zip](https://github.com/OpenRefine/OpenRefine/files/1492661/openrefine.l4j.zip)
3. I imported garbled data before.
[import-test-sample.zip](https://github.com/OpenRefine/OpenRefine/files/1492677/import-test-sample.zip)
![image](https://user-images.githubusercontent.com/1161494/33092476-9560866a-cf3d-11e7-8557-f4fd49e6c696.png)

It is displayed normally
①
![image](https://user-images.githubusercontent.com/1161494/33092358-4a10f2da-cf3d-11e7-818d-9eab6ee118b7.png)
②
![image](https://user-images.githubusercontent.com/1161494/33092410-6caed668-cf3d-11e7-9abf-9f2d175e2510.png)

4.The exported file is garbled.
[export-test-sample-txt.zip](https://github.com/OpenRefine/OpenRefine/files/1492682/export-test-sample-txt.zip)
![image](https://user-images.githubusercontent.com/1161494/33092559-d795f88a-cf3d-11e7-9513-797b2a7579d3.png)

**Comment by Yuutakasan** [comment]
other export pattern
Excel
[import-test-sample-xlsx.zip](https://github.com/OpenRefine/OpenRefine/files/1492711/import-test-sample-xlsx.zip)
![image](https://user-images.githubusercontent.com/1161494/33092860-c0fc904c-cf3e-11e7-9771-d11c60388d81.png)

HTML
![image](https://user-images.githubusercontent.com/1161494/33092994-1a3e4006-cf3f-11e7-9b3a-8237c7ddbbe8.png)
[import-test-sample-html.zip](https://github.com/OpenRefine/OpenRefine/files/1492715/import-test-sample-html.zip)

**Comment by jackyq2015** [comment]
can you please add the encoding switch I provided above and try again?

**Comment by Yuutakasan** [comment]
@jackyq2015 
The above processing is executed with the following settings.

＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
openrefine.l4j.ini
# Launch4j runtime config

# initial memory heap size
-Xms256M

# max memory memory heap size
-Xmx1024M

# Use system defined HTTP proxies
-Djava.net.useSystemProxies=true

#-XX:+UseLargePages
#-Dsomevar="%SOMEVAR%"

**-Dfile.encoding="UTF-8"**

**Comment by tfmorris** [comment]
Hopefully this has been fixed, but we should confirm for the 3.4 release.

**Comment by tfmorris** [comment]
From my limited testing, it looks like XLSX export is OK (at least for Numbers on my Mac), CSV is totally corrupted, and HTML broken for the higher code points as shown above.

**Comment by tfmorris** [comment]
@Yuutakasan Sorry for the long delay. The fix for this should make it into 3.4.

**Comment by Yuutakasan** [comment]
thank you. I'll test.

**Comment by Yuutakasan** [comment]
@tfmorris 
I've tested it and it still seems to cause garbled text.
Could you please open this issue?
OpenRefine 3.4 beta

1.import-test-sample.txt import ( No more problems than before. )
[import-test-sample.txt](https://github.com/OpenRefine/OpenRefine/files/4801165/import-test-sample.txt)
![image](https://user-images.githubusercontent.com/1161494/85071899-2d18f100-b1f3-11ea-90ff-d5856253bf4f.png)
2. Configure Parsing Options ( No more problems than before. )
![image](https://user-images.githubusercontent.com/1161494/85071965-40c45780-b1f3-11ea-9c29-b1486602abaa.png)
3.create project ( No more problems than before. )
![image](https://user-images.githubusercontent.com/1161494/85072132-8719b680-b1f3-11ea-8383-262d1a80329c.png)
4.export( Garbled characters in some formats. )
I used to test for HTML and CSV, but I also tested for other formats.
[export openrefine 3.4.zip](https://github.com/OpenRefine/OpenRefine/files/4801217/export.openrefine.3.4.zip)

①export tsv (Garbled characters)
![image](https://user-images.githubusercontent.com/1161494/85073169-458a0b00-b1f5-11ea-8c97-ba4b94781591.png)

②export csv (Garbled characters)
![image](https://user-images.githubusercontent.com/1161494/85073226-60f51600-b1f5-11ea-813e-4ad721afa4be.png)

③export html (Garbled characters)
View in a text editor
![image](https://user-images.githubusercontent.com/1161494/85073336-8eda5a80-b1f5-11ea-9dcb-42396425334a.png)
View in a chrome
![image](https://user-images.githubusercontent.com/1161494/85073387-a4e81b00-b1f5-11ea-991b-385adc2c9791.png)

④export excel (NOT Garbled characters)
![image](https://user-images.githubusercontent.com/1161494/85073495-d8c34080-b1f5-11ea-8d71-d93580d820e8.png)

⑤export excel2007+ (NOT Garbled characters)
![image](https://user-images.githubusercontent.com/1161494/85073646-1e800900-b1f6-11ea-8b97-eb193bd6f5a3.png)

⑥export ODF SpreadSheet (NOT Garbled characters)
![image](https://user-images.githubusercontent.com/1161494/85073609-10ca8380-b1f6-11ea-8c63-6a2207eb667b.png)

⑦export SQL (NOT Garbled characters)
![image](https://user-images.githubusercontent.com/1161494/85073801-630ba480-b1f6-11ea-982f-18a56182a80e.png)

⑧export SpreadSheet (NOT Garbled characters)
![image](https://user-images.githubusercontent.com/1161494/85073978-bed62d80-b1f6-11ea-8b12-8b354c5bb5e3.png)
https://docs.google.com/spreadsheets/d/12zaOy_Mh9d-85Cv7pVXYV_TTc9gJJALR8gbXi-aAvuQ/edit?usp=sharing

**Comment by wetneb** [comment]
@Yuutakasan this has not been fixed in 3.4 beta - that version was released before this fix. For a version that we expect not to have the issue, try this one:
https://github.com/OpenRefine/OpenRefine-nightly-releases/releases/tag/3.4-beta-148-gf88c0e3

**Comment by Yuutakasan** [comment]
@wetneb Thanx. I'll re-test.

**Comment by Yuutakasan** [comment]
@wetneb @tfmorris
I have found that the garbling has been resolved. Thank you very much.

[export openrefine 3.4-beta-148-gf88c0e3.zip](https://github.com/OpenRefine/OpenRefine/files/4801409/export.openrefine.3.4-beta-148-gf88c0e3.zip)


export tsv
![image](https://user-images.githubusercontent.com/1161494/85076012-64d76700-b1fa-11ea-8f15-0a7fc299ff2b.png)

export csv
![image](https://user-images.githubusercontent.com/1161494/85076062-73be1980-b1fa-11ea-9a76-fa7baac73b65.png)

export html
![image](https://user-images.githubusercontent.com/1161494/85076095-81739f00-b1fa-11ea-931d-6c0260433e72.png)

export excel
![image](https://user-images.githubusercontent.com/1161494/85076155-94866f00-b1fa-11ea-92fe-99fee2633d47.png)

export excel2007+
![image](https://user-images.githubusercontent.com/1161494/85076275-c697d100-b1fa-11ea-9769-0c51af864d7f.png)

export odf
![image](https://user-images.githubusercontent.com/1161494/85076331-ddd6be80-b1fa-11ea-913a-5352c8160a5a.png)

export spreadsheet
https://docs.google.com/spreadsheets/d/1TFTVPR-H-CDrGDC7yw252qc3QoBmOJVS9Uztu9VD7Eo/edit?usp=sharing

**Comment by tfmorris** [comment]
Excellent. Thank you very much for testing @Yuutakasan
