### ISSUE TITLE
MySQL Support Would be Amazing

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#12]
_Original author: mjlissner (May 10, 2010 17:39:53)_

<b>What steps will reproduce the problem?</b>
1. Try to connect to a MySQL database

As a DB administrator, all of my data is locked up in a MySQL database. I
COULD export it to CSV, then import it into Gridworks, then do some
cleanup, then export it to CSV, then import it to MySQL again, overwriting
the old data, but that seems very complicated.

Since this works in the browser anyway, it would be amazing if it could be
connected to MySQL databases, and if data manipulation could happen from there.

This would unlock a TON of new data, though I'm unsure how the program
would scale to the quantities of information that would be pulled in.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=12_
##

**Comment by thadguidry** [comment]
#1277 Is being worked on to support this issue !
