### ISSUE TITLE
Suggestion: Adopt the codes from Google's "Facets" and "Dive"

### ISSUE THREAD

**Issue by dfpoon** [OpenRefine/OpenRefine#1207]
Google's newly released "Facets" and "Dive" look promising. It would be great if OpenRefine could adopt some of the codes and improve the facets visualization in OpenRefine.

Google's project page: https://pair-code.github.io/facets/

**Comment by thadguidry** [comment]
The visualizations provided by the open source Facets project is built upon Polymer components and Typescript.

I do not see our team re-architecting our existing facets that our users are accustomed to now.
But there is no reason why someone else could not produce a new extension that could provide the Facets project or something like it for enhanced visualizations within OpenRefine or outside of it, even in a new browser tab or with a different server, or even fork OpenRefine and produce better facet visualization based on some libraries or newer web components.

Thanks for the suggestion.  I do hope someone works on some part of the above that I mentioned.  But our team won't for the foreseeable future.

**Comment by thadguidry** [comment]
OpenRefine's mission is to provide users a nice interface for cleaning messy data and light analysis towards the goal of cleaning messy data.  We didn't design it for Statistical Analysis, but there are some Extensions that provide a bit of this.  You might be better off looking at real Stat tools or Machine Learning tools.
