### ISSUE TITLE
appbundler no longer available

### ISSUE THREAD

**Issue by nehaljwani** [OpenRefine/OpenRefine#1209]
mac_dist fails, because appbundler-1.0.jar is no longer available at http://java.net/projects/appbundler/downloads/download/appbundler-1.0.jar

**Comment by tfmorris** [comment]
There's what looks like a copy of the original project here: https://github.com/joshmarinacci/AppBundler
and a fork which has some improvements and actually looks like is maintained here: https://bitbucket.org/infinitekind/appbundler/

**Comment by nehaljwani** [comment]
I also found:

http://repository.pentaho.org/content/groups/omni/com/oracle/appbundler/1.0/appbundler-1.0.jar
http://repo.boundlessgeo.com/main/com/oracle/appbundler/1.0ea/appbundler-1.0ea.jar

Although, both of them gave some error (Maybe I was using them wrong. I only edited refine and build.xml)

**Comment by jackyq2015** [comment]
fixed
