### ISSUE TITLE
Create project from SPARQL query

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1212]
As suggested by @Daniel-Mietchen at https://github.com/wetneb/openrefine-wikidata/issues/7 it would be great to be able to create a project using a SPARQL query (for instance against Wikidata).

Ideally, cells corresponding to entities would be automatically reconciled against the right identifier and schema space (this seems hard to do in a generic way for any SPARQL endpoint but it is quite easy for Wikidata).

OpenRefine would embed a query editor (ideally, with most of the features of the Wikidata Query Service, although again that seems hard to do in a generic way). Perhaps the way to go is just to provide two import methods, one for generic SPARQL and one for Wikidata SPARQL. This would make sense as Wikidata is already the default reconciliation service.

--------------------------
_This is a [proposed Outreachy project in 2022](https://github.com/OpenRefine/OpenRefine/wiki/GSoC-Outreachy-2022%C2%A0Ideas). If you are **not** planning to apply for an internship via Outreachy/GSoC, we kindly ask that you do not work on this task yet, in order to leave the floor to potential interns._

**Comment by thadguidry** [comment]
1. Support any SPARQL endpoint, but maybe we actually want to just put effort into Wikidata.
2. Mapping of Prefixes.

**Comment by thadguidry** [comment]
**STUDENTS** - Here is a recent SPARQL query Documentation discussion on our Users mailing list where I have provided 1 student who asked some helpful links for those interested in working on this issue:  https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/openrefine/lz7ac9ONro0/wFvg8WNoCAAJ

Feel free to discuss further in this issue, on our [Dev mailing list](https://groups.google.com/forum/#!forum/openrefine-dev), or on our [Gitter chat](https://gitter.im/OpenRefine/OpenRefine)

**Comment by aakankasha028** [comment]
Hi @wetneb @ostephens @thadguidry , I would like to contribute to this project as a part of Google Summer of Code 2020. I have previous experience of working in web frontend and backend, and find it interesting. Although I am a bit late but I'll pick it up as soon as possible. Please guide me for the same.

**Comment by wetneb** [comment]
@aakankasha028 sure, why don't you follow the steps here to get your first pull request on another issue first?
https://github.com/OpenRefine/OpenRefine/wiki/Your-first-pull-request

**Comment by SakuraX99** [comment]
Hello,@wetneb @ostephens @thadguidry , I also want to contribute to this project through Google Summer of Code 2020. I'm a university students major in Software Engineering in ShangHai, China. I have teamwork experience in Web programed based on Vue and Spring, I have basic fronted skills but more familiar with the backend. I know it's quite close to the deadline, but I really want to catch this chance to improve my ability in web backend. Please guide me for the same.Here is my e-mail: ztianyi936@gmail.com, thank you.

**Comment by wetneb** [comment]
@SakuraX99 same reply as above, please go through https://github.com/OpenRefine/OpenRefine/wiki/Your-first-pull-request

**Comment by thadguidry** [comment]
See also mailing list discussion: https://groups.google.com/d/msgid/openrefine-dev/f65fb2fa-f992-4144-9e2c-9cfa6b6e177an%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by wetneb** [comment]
I have proposed this as a potential Outreachy project (and maybe GSoC if we participate to that as well). This means I think it should be a good topic for a 3 months internship. This is therefore not suitable as a first issue: have a look at [our list of good first issues](https://github.com/OpenRefine/OpenRefine/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) instead

**Comment by khadijm** [comment]
i think, i can work on this project with your help .

**Comment by antoine2711** [comment]
> i think, i can work on this project with your help .

Unfortunatly @khadijm, this issue can NOT be taken, as it is one of the 3 projects of the Outreachy 2022 program (see the 
![image](https://user-images.githubusercontent.com/12217525/162544593-f3b9dd82-f87c-4f96-ac2d-b42b1bad5886.png) label). Since only 2 interns will be chosen, and that there is 3 project, there is a slite possibility that this issue might not be taken in May, if none of the interns choose this issue.

Regards, Antoine

**Comment by khadijm** [comment]
i am an  Outreachy aspirant. i don't know if can write a proposal on it.

**Comment by antoine2711** [comment]
> i am an Outreachy aspirant. i don't know if can write a proposal on it. @antoine2711

There is currently 3 issues that are RESERVED, and will be for the 2 choosen interns for the Outreachy 2022 program. This one is one of them.

At the start of May, those 2 interns will start to work on these 3 specifics issues, so nobody can't take them until then. All the others issues of are available to you, though. For your first issue, I would recommend to start with a « [good first issue](https://github.com/OpenRefine/OpenRefine/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) or « [good second issue](https://github.com/OpenRefine/OpenRefine/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+second+issue%22) ».

Regards, Antoine

**Comment by antoine2711** [comment]
@WaltonG : you asked me in a email how to incoporate <iframe> tags. Here's an example:
![image](https://user-images.githubusercontent.com/12217525/172977483-539fdb3d-2f59-42cf-b1f4-dcdc9e0ba9cd.png)

This is the HTML code, that only works if the WD Query GUI is running…

`<iframe src="http://127.0.0.1:8080/examples/editor.html" height="308px" width="1292px"></iframe>`

Regards, Antoine

**Comment by wetneb** [comment]
This has been implemented as an extension: https://github.com/OpenRefine/SparqlExtension
@antoine2711 told me he still intended to polish up some rough edges there, but perhaps it is already worth trying out for adventurous beta testers?
In any case, I would close this - let's open issues about this importer in https://github.com/OpenRefine/SparqlExtension/issues instead.
