### ISSUE TITLE
Schema alignment for Wikidata

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1213]
A schema alignment for Wikidata would enable OpenRefine users to prepare their datasets for inclusion in Wikidata. It should be implemented in a Wikidata extension (inside this repository or not).

* [x] create an OverlayModel that matches Wikibase's model (with native support for qualifiers, references and ranks)
* [x] add a dialog, operation and change to let the user edit this OverlayModel
* [x] enable export to QuickStatements format
- [x] add direct editing capabilities without going through QuickStatements
- [x] add warnings (no references, unreconciled cells…)
<s>- [ ] add delete statements</s>
<s>- [ ] enable configuration of statement mapping (for instance, adding or ignoring qualifier statement)</s>

The last points will be done later as it requires significant work in the underlying library (Wikidata-Toolkit).

**Comment by magdmartin** [comment]
It will be nice to have an extension that allows users to define a schema they want to match against (Wikidata, GoKB or anything else). 

The GOKB project already did some neat work for schema alignment. See https://www.youtube.com/watch?v=0wAY94hc7Gw  @ostephens may be able to give more background on it.

**Comment by wetneb** [comment]
@magdmartin it seems quite hard to make something that will work for everything directly… I suppose DERI's RDF export tool is the closest approximation to that. But that would not work very well for Wikidata.

The problem is that all these databases have different data models (not just schemas). Typically the notions of qualifier, references and ranks are quite specific to Wikibase.

**Comment by magdmartin** [comment]
That make sense. I was referring more to a general validation engine for flat file (csv, XLS ...). We can make that through a different issue.

**Comment by wetneb** [comment]
- [ ] add direct editing capabilities without going through QuickStatements
- [ ] add warnings (no references, unreconciled cells…)
