### ISSUE TITLE
Document Transposition functions

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1215]
As per #1214 there is currently a lack of documentation around how the transposition functions work. Add to the wiki a description of how each of the transposition functions work and examples of data scenarios where they can be useful

**Comment by thadguidry** [comment]
I elect.... Owen to work on this :)

**Comment by ettorerizza** [comment]
@ostephens If I'm not mistaken, "columnize by key-value" works in the same way as the spread/cast functions in R, while "transpose cells across columns into rows" is the equivalent of gather/melt. The [documentation ](https://www.jstatsoft.org/article/view/v021i12) and [tutorials](http://garrettgman.github.io/tidying/) of these two functions can therefore serve as a source of inspiration, I believe.

**Comment by wetneb** [comment]
A wikidatan is interested in something that looks like transposition functions, but I could not point them to any documentation for that, so I gave the link to this issue:
https://www.wikidata.org/wiki/User:John_Cummings/Useful_spreadsheet_processes_for_Wikidata#Select_every_Nth_line

**Comment by wetneb** [comment]
I am working on this today, with the intention to provide an example of operation documentation, which can hopefully be used as a gold standard to document other operations.

**Comment by wetneb** [comment]
Here is an attempt for key/value columnize:
* [Rendered version](http://pintoch.ulminfo.fr/e7c523cfa5a/operations/key_value_columnize.html)
* [Source](https://github.com/OpenRefine/OpenRefine/blob/3d6960200374783fc841cbfc1f8fe1bb72f1fedf/docs/src/operations/key_value_columnize.md)

**Comment by wetneb** [comment]
This is done for the key-value columnize operation - it remains to be done for other transpose operations.

https://docs.openrefine.org/operations/key_value_columnize.html

**Comment by wetneb** [comment]
This was resolved by @allanaaa: https://docs.openrefine.org/manual/transposing
