### ISSUE TITLE
Fetching URLs that yield un-styled XML ...

### ISSUE THREAD

**Issue by ericjarvies** [OpenRefine/OpenRefine#1218]
When fetching URLs that _only_ yield **XML**, OpenRefine does not write the XML into the fetched [_column_] cells.

In a web browser, the XML is displayed/formatted like so;

<img width="380" alt="xml_without_styling_as_seen_in_web_browser" src="https://user-images.githubusercontent.com/977450/28765788-61d6ec64-7581-11e7-92be-fe0b0f302d92.png">

Using OpenRefine, how does one fetch un-styled XML like explained/shown above?

Thank you,

Eric

**Comment by ettorerizza** [comment]
@ericjarvies Can you provide an example ?

**Comment by ericjarvies** [comment]
I've run into this problem a few times in the past, but do not have the URLs committed to memory (or saved to file).  The current URL is a credential-based website, so I must first log into the website, and then the URL/query looks something like this;

https://someWebsite.com/user/@ericjarvies;pid=111-222-333;fileReference=;selectedDistrictCode=ALL;selectedDistrictName=;includeCancelledTitles=N?t=1485910928995

The returned result is entirely in XML like so;

`<TitleSummaries>
<errors/>
<itemsPerPage>20</itemsPerPage>
<titleSearchResultByPidorShortLegal>
<errors/>
<pid>FOO</pid>
<shortLegal>S/4502///24//7 *</shortLegal>
<titleSummary>
<errors/>
<concatShortLegal>
0000000000000004502 00000000000024 00007 011542641001
</concatShortLegal>
<firstOwner>FOO</firstOwner>
<fullLegalDescription>LOT 7 BLOCK 24 DISTRICT LOT 526 PLAN 4502</fullLegalDescription>
<index>1</index>
<landTitleDistrict>VA</landTitleDistrict>
<pid>FOO</pid>
<shortLegal>S/4502///24//7 *</shortLegal>
<status>REGISTERED</status>
<strataPlanCommonProperty>false</strataPlanCommonProperty>
<titleNumber>BB300420</titleNumber>
</titleSummary>
</titleSearchResultByPidorShortLegal>
<titleSearchResultByPidorShortLegal>
<errors/>
<pid>FOO</pid>
<shortLegal>S/4502///24//8 *</shortLegal>
<titleSummary>
<errors/>
<concatShortLegal>
0000000000000004502 00000000000024 00008 011542675001
</concatShortLegal>
<firstOwner>FOO</firstOwner>
<fullLegalDescription>LOT 8 BLOCK 24 DISTRICT LOT 526 PLAN 4502</fullLegalDescription>
<index>1</index>
<landTitleDistrict>VA</landTitleDistrict>
<pid>FOO</pid>
<shortLegal>S/4502///24//8 *</shortLegal>
<status>REGISTERED</status>
<strataPlanCommonProperty>false</strataPlanCommonProperty>
<titleNumber>CA5139349</titleNumber>
</titleSummary>
</titleSearchResultByPidorShortLegal>
</TitleSummaries>`

The web browser simply displays the XML -even though it does not have any styling/is not part of an html (or whatever) type of document.  But OpenRefine simply ignores the fetched/returned results/XML

Eric

**Comment by ettorerizza** [comment]
This must be a very specific problem, which is why a real URL would be welcome. In general, Open Refine has no problem with URLs that return a pure XML response. I suspect an encoding problem in your URLs. Web browsers are very nice, when the URL contains forbidden characters, they transform them and display an answer anyway. But not Open Refine. You need to use `value.escape('url')` when your value contains blank spaces and other forbidden characters.

**Comment by wetneb** [comment]
Closing as non-reproducible.
