### ISSUE TITLE
Travis: oraclejdk7 is not available anymore

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1223]
Some Travis builds fail when they are executed on Ubuntu Trusty, because oraclejdk7 is not available there anymore:
https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879
We have two options:
- either set "dist: precise" to force using Precise (this image will stop being updated at some point)
- or we just drop oraclejdk7 support.

**Comment by thadguidry** [comment]
@wetneb The forward plan was to drop oraclejdk7 and go to 8.  Help there is appreciated.

**Comment by thadguidry** [comment]
@wetneb I think we'll need to edit our travis.yml file then.... see https://github.com/travis-ci/travis-ci/issues/5897

basically add

`"addons": {
    "apt": {
      "packages": [
        "oracle-java8-installer"
      ]
    }
  },
`
like this guy did https://travis-ci.org/gsmet/hibernate-validator/jobs/181629047/config

**Comment by wetneb** [comment]
@thadguidry hmm, you can try, but I don't think it is going to work. The issue you linked to is quite old and I think it is a different problem.

**Comment by thadguidry** [comment]
@wetneb The issue could be fixed with that addon package, but doesn't matter now, and oraclejdk7 is end of life and why it was removed in Ubuntu trusty.  Looks like your good now against oraclejdk8 and openjdk7 as evidenced here https://travis-ci.org/OpenRefine/OpenRefine/builds/260572450
