### ISSUE TITLE
Travis: generate code coverage statistics

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1224]
We could use coveralls to report test coverage. It has a good Github integration.

**Comment by thadguidry** [comment]
I'd prefer we use Codecov...or Codacy ... both free for open source projects
https://github.com/marketplace/codecov
https://github.com/marketplace/codacy

Codacy has a nicer view even for pull requests.

**Comment by wetneb** [comment]
@thadguidry yeah any of these would do - the hard part is generating the coverage data in Travis. It looks like we have to migrate to Maven first (#1054 should help).

**Comment by thadguidry** [comment]
@wetneb Just use Gradle instead.  I've done the work already.  You can add anything else you need into the build.gradle file on our work in progress branch.  Then pull over what we need into master branch from it.
https://github.com/OpenRefine/OpenRefine/tree/java8-refactor

**Comment by wetneb** [comment]
@thadguidry awesome!

**Comment by thadguidry** [comment]
@wetneb yeah, so we are already "gradleized" in the java8-refactor branch...  I'm a Gradle expert as well, btw, but still don't know enough shit :)  ping me on dev list if you need assist or want to schedule a hangout.

**Comment by wetneb** [comment]
This is solved!

**Comment by thadguidry** [comment]
@wetneb sweet ! and looks like we now have the 2 new badge icons that are clickable on the main Github project page https://github.com/OpenRefine/OpenRefine
build **passing** Codacy **B** coverage **20%** Bountysource **$150 in 1 bounty**
