### ISSUE TITLE
Streamline the process of submitting sample files in bug reports

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1225]
I have spent some time triaging the backlog of issues.

Very often we need sample files to investigate, and it seems that we do not have a clean solution to let users share these sample files. This is very sad, because it creates bug reports like #940, #725 or #713 - if I wanted to fix any of these bugs, I would need to chase the user to get the dataset, and as the issue was filed a few years ago it would probably be quite hard. So the reporting effort is wasted.

GitHub attachments are apparently limited to some formats, so it seems they cannot be used for that. Sending datasets by email is not appropriate either: you don't want to send a large file on the mailing list, and you don't want to send your dataset to just one contributor (because they come and go).

Is there a hosting site that we can rely on for that?

**Comment by magdmartin** [comment]
I think we can leave it to the person who creates the issue to share the file with the platform of his/her choice. 
It can be good to add a line in the CONTRIBUTING.md Guidelines for Reporting a Bug to invite the reporter to add a file.

**Comment by wetneb** [comment]
Perhaps GitHub attachments are good enough for this, people can always bundle any file as a `.zip`…
