### ISSUE TITLE
Localization support: use Weblate?

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1229]
It seems that some people are keen to contribute to OpenRefine's localization. It is a bit sad to see PRs like #924, where a lot of work was done but wasn't eventually delivered to the users because the translation is not complete.

I have come across [Weblate](https://weblate.org/), a nice web interface to help translators localize the interface. It would both decrease the technical requirements to start translating, and make it more of a collaborative process. It is tightly integrated with git, which means translations can be pushed to the git repository by Weblate, or proposed as pull requests.

It seems that it is possible to get free hosted accounts for open source projects. If the community is interested, I can ask them for one and do the initial set up.

**Comment by thadguidry** [comment]
@wetneb Dude, don't even ask... just get that done !  It would super awesome.  Yes anything that can help folks translate OpenRefine to more languages easily = A GOOD THING.

**Comment by wetneb** [comment]
This is done, translations can be edited here:
https://hosted.weblate.org/projects/openrefine/translations/
I've started a German translation, if people want to get involved…

**Comment by wetneb** [comment]
By the way if we do not like weblate's automatic pushes we can always ask it to do pull requests instead - let me know if it is better.

**Comment by thadguidry** [comment]
@wetneb the pushes are fine.  I like seeing those fixed fast...not worried about abuse.
