### ISSUE TITLE
BountySource integration is broken

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1240]
Issues do not get updated with the link to BountySource. It should look like this issue: https://github.com/dissemin/dissemin/issues/441.
I think this could be solved by disabling and re-enabling the integration. @thadguidry, thoughts?

**Comment by thadguidry** [comment]
@wetneb OK, I'll try to re-enable it.  I tried before in the past and didn't seem to help, but who knows.

**Comment by jackyq2015** [comment]
close it. not deal with BS for now.
