### ISSUE TITLE
Unable to delete projects + disappearing icons?

### ISSUE THREAD

**Issue by angryfrenchguy** [OpenRefine/OpenRefine#1242]
The Opne refine main screen is not giving me the option to *delete* projects anymore. Also, most logos and images have disappeared.

I have tried uninstalling and reinstalling OR. Twice. 

I have Hazel, which should have removed configuration files. I also cleared my safari cache, for good measure. 

The only significant that that happened before was that I installed and uninstalled the VIB-Bits plugin.

With my browser in developper mode, I get two errors : 

    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (http://google-refine.googlecode.com/svn/support/releases.js, line 0)

    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (http://127.0.0.1:3333/underscore-min.map, line 0)

<img width="1440" alt="capture d ecran 2017-09-02 a 10 35 02" src="https://user-images.githubusercontent.com/17603054/29996402-aaa39014-8fcb-11e7-81af-07c1bc473406.png">

<img width="627" alt="capture d ecran 2017-09-02 a 10 34 03" src="https://user-images.githubusercontent.com/17603054/29996403-ae3ae1dc-8fcb-11e7-9bb9-bdc128fd59aa.png">

Any insight?

**Comment by wetneb** [comment]
I would inspect the places where images are supposed to appear (like, the OpenRefine logo in the top left corner) with the developer tools of your browser. If you can also access the server's logs, that would be helpful, I think.
