### ISSUE TITLE
Can't specify a record path in OpenRefine

### ISSUE THREAD

**Issue by tmmcub** [OpenRefine/OpenRefine#1245]
Hi,

I just installed and had been using OpenRefine on a Win7 64-bit with 8GB of RAM, working with reasonable sized (220MB) json files and Firefox, with no problem.  I then tried to create a project on a much larger, 390MB json file, which hit a memory limit and basically froze.

Now, when I click "Create Project" I'm now receiving a message, after importing a json file, to "Please Specify a record path first".  When I click the button to specify a record path, nothing happens.  I then tried with Chrome, but had the same result.  I then installed on another Win7 64-bit with 4GB of Ram and used Firefox to import a file of 50+ records (json file 250K) and am receiving the same response.

Hope someone can help!
Tim

**Comment by thadguidry** [comment]
@tmmcub You might be causing OpenRefine to run out of memory.  Try allocating more memory to OpenRefine when you work with large record files.  Follow this guide and then let us know if it fixes the issue for you https://github.com/OpenRefine/OpenRefine/wiki/FAQ#out-of-memory-errors---feels-slow---could-not-reserve-enough-space-for-object-heap

**Comment by tmmcub** [comment]
Hi Thad,

Thanks tons for all the suggestions!  I pretty much had to do all the above in order to get the json file loaded, but that's fine by me.  Allocating more memory was the key.

Really appreciate your help!  I learned a lot today.

Have a great week!

**Comment by thadguidry** [comment]
@tmmcub sure thing.  glad to help.

**Comment by ettorerizza** [comment]
Memory problems are so common when you organize Open Refine training. I wonder if it would not be a good idea to display a pop up when OR runs out of resources. The other solution would obviously be to set the -Xmx automatically according to the computer possibilities and the presence or not of Java 64 bits, but I imagine it would be more work.

**Comment by thadguidry** [comment]
@ettorerizza The free memory detection is being worked on in #1295

**Comment by debpaul** [comment]
> To specify a record path for a JSON file, you just click with your mouse in the preview to highlight the JSON object that you wish to work with. It will pull out all those same objects from the JSON array and load them into record rows so you can work with the data.

Thanks @thadguidry ^^^ that was just the hint I needed today.
