### ISSUE TITLE
Range facet to/from is incorrect for Reconciling "Best candidate's score"

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#1247]
From Pull #1246

When adding a "Best candidate's score" facet to a column with equal reconciliation scores, I get the following facet JSON:

 {
          "to": 1,
          "expression": "cell.recon.best.score",
          "selectError": false,
          "selectNumeric": true,
          "selectBlank": true,
          "name": "occupation: best candidate's score",
          "columnName": "occupation",
          "selectNonNumeric": true,
          "from": 100,
          "type": "range"
        }
I think the problem is rather in the UI: the facet selection UI looks buggy in that case. (In the JSON above, the "to": 1 is wrong).

Anyway, I think it would be quite dangerous to change the semantics of the range facets: this can potentially break a lot of user scripts. We just need to make sure that OpenRefine generates the right facet (with min=score and max=score+1) by default.

**Comment by wetneb** [comment]
Closed by #1263.
