### ISSUE TITLE
[epic]  Automatic reference generation for Wikidata export based on project metadata

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1249]
If we had proper support for project metadata (#1221) we could generate automatically references for Wikidata statements added from OpenRefine.

That would be pretty awesome.

**Comment by thadguidry** [comment]
@wetneb I need a visual on this to understand it better.  Just scribble on some paper and snap it with your phone and upload is fine. :)

**Comment by wetneb** [comment]
@thadguidry it's going to be clearer once the wikidata extension is merged.

**Comment by thadguidry** [comment]
@wetneb AH, ok

**Comment by wetneb** [comment]
This is not going to be feasible given the sort of metadata we have in projects and the sort of reference that is expected in Wikidata. One better way to ease adding references in Wikidata schemas would be to provide a way to copy/paste them as suggested by Owen.
