### ISSUE TITLE
Facet/Filter Unable to Organize with Two Variables

### ISSUE THREAD

**Issue by AndrewRCalderon** [OpenRefine/OpenRefine#1250]
I have a text and numeric data set. I want to organize the entire data set along two variables: Zip Code and Compliance. I'm only interested in compliance among 5 of the zip codes. When I used Facet, I was able to isolate the target zip codes. The, when I wanted to organize those target zip codes by Compliance, the facet affected the entire data set. Not sure how to just get co-variant results. Please help!

**Comment by wetneb** [comment]
@AndrewRCalderon  Please use the mailing list to ask for help - we only use this issue system to track bug reports or feature requests. Thanks!
https://groups.google.com/forum/#!forum/openrefine
