### ISSUE TITLE
URL sitemap error message

### ISSUE THREAD

**Issue by ViktorHolas** [OpenRefine/OpenRefine#1252]
Hi,

I've placed a URL sitemap of my website and getting this error message. How can I fix it? Any idea?

![screenshot_1](https://user-images.githubusercontent.com/32128288/30639294-92ca5bf8-9dfe-11e7-8bb8-f07d0745cb4e.jpg)

Thanks in advance.

**Comment by wetneb** [comment]
@ViktorHolas is that an error you get when trying to create a project from the URL of your sitemap? Could you share that URL to us?

**Comment by ViktorHolas** [comment]
@wetneb yes, the URL is http://dumazahrada.eu/sitemap_index.xml

**Comment by wetneb** [comment]
@ViktorHolas Which version of OpenRefine and which operating system are you using? It works fine for me.

**Comment by ViktorHolas** [comment]
@wetneb Im using version 2.7 on Windows, but now I tried it on my OSX and works fine.

**Comment by wetneb** [comment]
Great! Then most likely the problem is independent from OpenRefine itself.

**Comment by ettorerizza** [comment]
No problem on my Windows 10 installation (Open Refine 2.7)

![screenshot-127 0 0 1-3333-2017-09-21-11-48-03-677](https://user-images.githubusercontent.com/6286410/30689944-e462e952-9ec2-11e7-837a-d67d7bf1f2f9.jpeg)
