### ISSUE TITLE
Notify user if a more recent release is available

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1258]
As per https://groups.google.com/forum/#!topic/openrefine-dev/AoLLeS7j8UE

@thadguidry said:

> What is much more important is within OpenRefine letting users know about a new update.  One way we talked about would be to just provide an update notifier link "Get newest OpenRefine 2.7.1 here" or somesuch near our logo in OpenRefine that provides a link to the releases page on our Github.  To implement perhaps that could be just a bit of javascript to check our https://github.com/OpenRefine/OpenRefine/releases/latest Github page and compare to the version running and make the update link visible ?

**Comment by ostephens** [comment]
I've been having a look at this, and there is some old code in /main/webapp/modules/core/scripts/index.js that does something very similar, but checking Google Code site. If it finds a more recent release it puts a notification at the top of the page.

I've been playing around with modifying it so uses https://api.github.com/repos/openrefine/openrefine/releases/latest to check the latest version and that's straightforward.

I'm assuming we use the 'tag_name' from the Github JSON to get the latest version number - is that a safe assumption (that the tag_name will reflect the version number)?

In terms of comparing versions, should I assume semver for versioning?

**Comment by wetneb** [comment]
According to GitHub

>  It’s common practice to prefix your version names with the letter v. Some good tag names might be v1.0 or v2.3.4.

So I would recommend we follow this practice… (this lets us define tags which are not releases).

**Comment by ostephens** [comment]
OK - that sounds reasonable.
(n.b. you can have tags that aren't releases anyway - a tag isn't a release by default. The Github /releases/latest api call only returns full releases - not draft releases or prereleases).

**Comment by ostephens** [comment]
I've made an attempt at fixing this. It assumes Semantic Version numbering format of form X.Y.Z where X, Y, and Z are non-negative integer. It ignores any trailing letters e.g. 2.7.1-rc.1 will be interpreted as equivalent to 2.7.1

Comments on PR welcome if this could be approached in a better/more robust way

**Comment by thadguidry** [comment]
@wetneb FYI, Most of the open source world has aligned to GAVC convention borrowed from Maven.

Group:Artifact,:Version:Classifier.
org.openrefine:OpenRefine:2.7.1:SNAPSHOT

and filenames look like
openrefine-2.7.1-SNAPSHOT.zip
openrefine-2.7.1-rc1.zip

Typically, tag names are just the VC parts ... version and classifier

2.7.1-SNAPSHOT
2.7.1-rc1
