### ISSUE TITLE
Generate cvs from a son file (problem)

### ISSUE THREAD

**Issue by Gucci1986** [OpenRefine/OpenRefine#1261]
Hello, 
I'm new with OpenRefine and I encountered a problem. 
I upload my JSON files and it work well but my JSON is somehow "cut" per comparison of the original file. I have more than 200 entry in the original file, and it generate only 16 rows in the csv sheet I want to work with. Do you ever had this problem? Is it a problem of syntax in the original file? 
Thank you very much.

**Comment by jackyq2015** [comment]
can you provide a sample of the JSON file?

**Comment by Gucci1986** [comment]
Sure, here : 
{
  "data": [
    {
      "created_time": "2017-05-31T15:53:45+0000",
      "from": {
        "name": "JJ Nina",
        "id": "10203499588585347"
      },
      "message": "Orélie Orélie ... mdrrr j en peux plus 😂😂",
      "id": "1551460621555337_1551461834888549"
    },
    {
      "created_time": "2017-05-31T15:55:03+0000",
      "from": {
        "name": "Emilie Duthoy",
        "id": "10203735457525161"
      },
      "message": "\" tu veux voir mon clitoris de 15cm ?\"",
      "id": "1551460621555337_1551462631555136"
    },
    {
      "created_time": "2017-05-31T15:56:50+0000",
      "from": {
        "name": "Mi Stick",
        "id": "133169370361082"
      },
      "message": "Trol Lex ça te rappelle qqn ? 😂😂",
      "id": "1551460621555337_1551464234888309"
    },
    {
      "created_time": "2017-05-31T15:53:46+0000",
      "from": {
        "name": "Seb Seb",
        "id": "123755004648034"
      },
      "message": "Mdr",
      "id": "1551460621555337_1551461858221880"
    },

**Comment by wetneb** [comment]
@Gucci1986 I have added closing `]` and `}` to turn your text into valid JSON.

**Comment by wetneb** [comment]
@Gucci1986 importing the JSON payload above in OpenRefine and exporting it to CSV gives the following result:
```
_ - id,_ - message,_ - created_time,_ - from - id,_ - from - name
1551460621555337_1551461834888549,Orélie Orélie ... mdrrr j en peux plus  😂😂,2017-05-31T15:53:45+0000,10203499588585347,JJ Nina
1551460621555337_1551462631555136,""" tu veux voir mon clitoris de 15cm ?""",2017-05-31T15:55:03+0000,10203735457525161,Emilie Duthoy
1551460621555337_1551464234888309,Trol Lex ça te rappelle qqn ?  😂😂,2017-05-31T15:56:50+0000,133169370361082,Mi Stick
1551460621555337_1551461858221880,Mdr,2017-05-31T15:53:46+0000,123755004648034,Seb Seb
```
which is exactly what I would expect.

Please provide an example input where your bug can be observed! (Make sure you can see the bug you are describing given the data you send us.)

**Comment by ettorerizza** [comment]
Open Refine probably does not accept this story of "clitoris de 15 cm" in the Json.

**Comment by Gucci1986** [comment]
@wetneb Here's the screenshot of the lasts utterances of 1) the json file and 2) the Openrefine result
<img width="716" alt="jsonfile" src="https://user-images.githubusercontent.com/32593142/31405807-8faf4e68-adff-11e7-90ba-3afcf4a7bb97.png">
<img width="738" alt="resultcsv" src="https://user-images.githubusercontent.com/32593142/31405828-9277b50e-adff-11e7-9714-a8e88fc79c58.png">

As you may see, the file is cut from the original. I know I don't explain very well, as I said, i'm very new in this.

@ettorerizza You think? I'm working on hate speeches, it will be a shame if cursed words are censored by Openrefine :/

Thank you for your responses.

**Comment by Gucci1986** [comment]
Ok, I'll find another way to do what I want. It seems very complicated and I don't have the competences to expose my problem. i don't want to bother you ahaha.
Thank you very much, I'll close the topic.

**Comment by ettorerizza** [comment]
@Gucci1986 No, it was just a bad joke ^^ Pleased that you have solved the problem by another way, but it would still be interesting to understand what happened. This is maybe a bug. A screenshot isn't very useful, we need a file that can be imported into OR to reproduce the problem. If there is no privacy concern, you could add the complete json file as an attachement.

**Comment by Gucci1986** [comment]
@ettorerizza I can't send the whole file because there is confidentiality problem, I can send you a sample but not the whole file I'm sorry. This is why I said it will be complicated. 
I think the file has been truncated during the process in Open Refined, I used another device to organize my file into a proper spreadsheet and it worked, so I think maybe OpenRefine is not what I needed in the first place.
Thank you very much for your response
