### ISSUE TITLE
Reconciliation: change "topic" to "item" in the UI?

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1267]
OpenRefine's reconciliation features were primarily designed to reconcile against Freebase. The entries in Freebase were called "topics", so this terminology was also adopted in OpenRefine.

Today, Freebase has been replaced by Wikidata, which uses "item" instead. I propose that we update the user interface to use this term instead, as the notion of "topic" is rarely used in this context outside of Freebase. We could also consider other generic terms, such as "record" (but that collides with OpenRefine's notion of record) or "entry".

The translations would need to be accordingly, but Weblate handles that correctly (translations made before a change in English labels will be flagged).

**Comment by thadguidry** [comment]
I'm fine with "item" or "thing".... "topic" is broader than either one of those, but that's how Freebase was...you could have either an "item" or a "subject" or "category" and both were equal footing, all represented as a general "topic".  This doesn't align with SKOS or Schema.org's Thing or WIkidata's Item.  So agree to change this to a narrower term which makes it easier for alignment with any Ontology system or Vocabulary.
