### ISSUE TITLE
Reconciliation: two ways to assign new topics to cells

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1272]
In the Reconcile / Actions menu, there are two seemingly identical operations:
![new_topic](https://user-images.githubusercontent.com/309908/31779583-5ec90a62-b4eb-11e7-8eac-b16b466b6888.png)

I believe one was intended to set the same new topic for all cells, whereas the other added a different new topic for each cell. If that is the case, the UI should reflect that. If not, we should only keep one.

**Comment by thadguidry** [comment]
@wetneb uh... yeah...THAT was not there before... lololol
