### ISSUE TITLE
Openrefine start server take too much time on Openstack Instance

### ISSUE THREAD

**Issue by ValentinChCloud** [OpenRefine/OpenRefine#1274]
Hello, I have some issues to start Openrefine.
## Operefine version
OpenRefine 2.7 

## Configuration:
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"

on a cloud base on Opentask

## Curent Results
When I start Openrefine one step takes too much time.
```
root@galaxy-e-v1:~/OpenRefine# ./refine -v trave
Starting OpenRefine at 'http://127.0.0.1:3333/'

13:42:27.776 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
13:42:27.777 [            refine_server] refine.memory size: 1400M JVM Max heap: 1407188992 (1ms)
13:42:27.786 [            refine_server] Initializing context: '/' from '/root/OpenRefine/main/webapp' (9ms)
13:42:27.823 [            refine_server] Starting autoreloading scanner...  (37ms)
13:43:52.751 [                   refine] Starting OpenRefine 2.7 [TRUNK]... (84928ms)
13:43:52.756 [       FileProjectManager] Failed to load workspace from any attempted alternatives. (5ms)
```
As you can see with the step
>13:43:52.751 [                   refine] Starting OpenRefine 2.7 [TRUNK]... (84928ms

where 84928ms = 1.4 minutes, many other attempts same results (even 3 minutes)

So I try to identify what's wrong, by adding some lines in `server/src/com/google/refine/Refine.java`

```
root@galaxy-e-v1:~/OpenRefine# ./refine -v trace
Starting OpenRefine at 'http://127.0.0.1:3333/'

13:53:04.249 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
13:53:04.251 [            refine_server] refine.memory size: 1400M JVM Max heap: 1407188992 (2ms)
13:53:04.260 [            refine_server] Initializing context: '/' from '/root/OpenRefine/main/webapp' (9ms)
13:53:04.335 [            refine_server] Starting autoreloading scanner...  (75ms)
13:53:04.338 [            refine_server] After Scanner scanner (3ms)
13:53:04.338 [            refine_server] After scanner.setScanInterval (0ms)
13:53:04.338 [            refine_server] After scanner.setScanDirs(scanList); (0ms)
13:53:04.338 [            refine_server] After scanner.setReportExistingFilesOnStartup(false); (0ms)
13:53:04.339 [            refine_server] After big bloc (1ms)
13:53:04.373 [            refine_server] After scanner.start()); (34ms)
13:53:04.373 [            refine_server] After scanForUpdate (0ms)
13:54:47.832 [            refine_server] After this.start()) (103459ms)
13:54:47.849 [                   refine] Starting OpenRefine 2.7 [TRUNK]... (17ms)
13:54:47.855 [       FileProjectManager] Failed to load workspace from any attempted alternatives. (6ms)
13:54:50.708 [                   refine] Sorry, some error prevented us from launching the browser for you.
```
As you can see the line https://github.com/OpenRefine/OpenRefine/blob/master/server/src/com/google/refine/Refine.java#L202
seems to be the problem.

## Expected Results
Start Openrefine don't take too much time

If you could help me to debug this, if you know what could be take so mush time on an environment as a cloud build with Openstack

**Comment by jackyq2015** [comment]
Since you are using Openstack, I think it is related to the IO. can you use iostat to check while you starting it?

**Comment by ValentinChCloud** [comment]
Something like that ?
```
root@galaxy-e-v1:~/OpenRefine# iostat  ./refine
Linux 4.4.0-87-generic (galaxy-e-v1)    10/20/2017      _x86_64_        (8 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.91    0.00    0.07    0.01    0.00   99.02

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn


```

**Comment by jackyq2015** [comment]
that's weird. but from the log it shows the process "scanForUpdates" takes much of the time. You are using root to launch it. I am not sure where does it get launched. You may on a mounted storage. can you use a regular user to download a new copy and try again? The idea is to try to make it running locally, not from remote storage.

**Comment by ValentinChCloud** [comment]
>can you use a regular user to download a new copy and try again? The idea is to try to make it running locally, not from remote storage.

I used to have Open refine on my VM with virtual box and it works well

**Comment by ValentinChCloud** [comment]
>that's weird. but from the log it shows the process "scanForUpdates" takes much of the time

I don't follow you it only takes few ms no?

**Comment by jackyq2015** [comment]
Right! that must relate to your cloud environment. which provider are you using?  Run this and paste the result:
`mount | grep $(df -P ~/.local/share/openrefine | tail -1 | awk {'print $1'})`

**Comment by ValentinChCloud** [comment]
```
root@galaxy-e-v1:~# mount | grep $(df -P ~/.local/share/openrefine | tail -1 | awk {'print $1'})
/dev/vda1 on / type ext4 (rw,relatime,data=ordered)
/dev/vda1 on /var/lib/docker/overlay type ext4 (rw,relatime,data=ordered)
```

**Comment by jackyq2015** [comment]
looks fine for me. I assume you did not tune those parameters yourself for the file system. The last thing that I can think of is the number of your projects. maybe it's too many? OR will try to load all the project meta data when starting up. that could take long if you have too many project and on a slow disk IO.

Do you have other applications run on Genouest in similar way? I never heard of this provider.

**Comment by ValentinChCloud** [comment]
It makes me think,, this happens after the 2~3 the launch of openrefine. But if I don't use  it for few days and come back,, same things happen.

**Comment by jackyq2015** [comment]
Can you delete the ~/.locale/share/openrefine folder and try again? Back up it if necessary

**Comment by ValentinChCloud** [comment]
Done, nothing changes :/

**Comment by ValentinChCloud** [comment]
There is ./refine test server if it could helps : 
https://github.com/ValentinChCloud/Logs/blob/master/out_server_test.txt

**Comment by jackyq2015** [comment]
can't see any obvious issue which can cause the slowness. You said that the first time after you removed the folder it's work though? what kind of project did you create after that and what else did you do?

**Comment by ValentinChCloud** [comment]
>You said that the first time after you removed the folder it's work though?

No I said, remove the folder didn't change anything.I said this issue happen when, I create a new VM, I download Openrefine from github, I build and run refine, and after many launches it gets slower.
I don't use refine at all, I just want first to launch many server on different ip and port ( finnaly to use Openrefine as container)

**Comment by thadguidry** [comment]
@jackyq2015 @ValentinChCloud  
I should probably put this into our Wiki somewhere but... here's additional info for both of you to be aware of.  Something that I deal with often in the enterprise with Java apps running in containers.

A few things to be aware of when dealing with memory usage with Java Apps running in Containers…

1. The kernel can sometimes kill the Java process if JVM memory usage grows over the cgroups limit defined for a Docker container.  Deep details are here: https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt

2. The default GC algorithm uses 1/4th of all memory from the host OS, if Xmx option is not defined explicitly.
http://blog.jelastic.com/2017/04/13/java-ram-usage-in-containers-top-5-tips-not-to-lose-your-memory/

In case you run into performance memory issues with Java Apps running in Containers,
you have the above as a general guide.

**Comment by ValentinChCloud** [comment]
Very interesting, I guess I have to use openjdk-9 to work with containers right? I tried but as mentioned  #1162 didn't work ^^

**Comment by jackyq2015** [comment]
jdk 8 is good to work with container. jdk9 is not supported yet.

**Comment by ValentinChCloud** [comment]
Of course, I don't have any problems locally, so back to openstack issue :/.

**Comment by jackyq2015** [comment]
close for now. if you think it's an issue of the OR itself. please reopen it.
