### ISSUE TITLE
JDBC?

### ISSUE THREAD

**Issue by aadrian** [OpenRefine/OpenRefine#1277]
Hi,

How to get data using JDBC (so as an input source)?
I couldn't find any working example :( .

Thank you.

**Comment by wetneb** [comment]
hi @aadrian, I don't think OpenRefine supports JDBC natively. You can try exporting your dataset from JDBC to a format that OpenRefine supports.

**Comment by aadrian** [comment]
@wetneb thank you for the information.

> I don't think OpenRefine supports JDBC natively. 

This looks quite unusual to me, since the server is based on Java, and Java's main advantage, purpose and selling point with businesses is mostly JDBC .

> You can try exporting your dataset from JDBC to a format that OpenRefine supports.

Hmm, using those formats would also mean to loose information (metadata, constraints,  relationships etc), so it would pretty defy the whole purpose of "refining" the data  :( .

**Comment by thadguidry** [comment]
It's in our future plans to support database connectivity options. This
will happen next year. Stay tuned.

**Comment by thadguidry** [comment]
There are also additional advanced parameters that are also useful to have.
We can add an Advanced Tab later on however.  For now I like just going with a simple enumerated list or dropdown for the DB Type

A Validation Query field is also useful. Pentaho, NiFi and others have that.
And perhaps a maximum wait time just in case.
and others.

Also a JDBC Property Name / Value array is also useful.  Pentaho's UI for that is just another dialog 2 columns: Property Name | Value 
and the user fills in and they are added to the JDBC connection as parameters.
https://help.pentaho.com/Documentation/5.1/0P0/0U0/010/000
https://nifi.apache.org/docs/nifi-docs/components/org.apache.nifi/nifi-dbcp-service-nar/1.4.0/org.apache.nifi.dbcp.DBCPConnectionPool/index.html

**Comment by tcbuzor** [comment]
I think the JDBC functionality should support the following:
a) Multiple database types, selectable from a drop down.
b) Start with most common database types: MySQL, MariaDB, PostgreSQL
c) Support the plugin of new database types. It should be as easy as dropping a jar containing the JDBC driver and Database implementation in  a folder and the JDBC extension should load all jars in the folder.
d) Support a well defined API for common database operations. e.g: connect, list etc..

**Comment by tcbuzor** [comment]
aadrian, can you try out the new OR JDBC extension?
[](https://github.com/tcbuzor/openrefine-db-extension.git)
The extension supports MySQL, PostgresSQL and MariaDB.

**Comment by wetneb** [comment]
Closing as the feature was implemented.

**Comment by kidehen** [comment]
@thadguidry,

What's the status of JDBC support?

**Comment by thadguidry** [comment]
@kidehen Its implemented now as "database" extension, available in OpenRefine 3.0

**Comment by kidehen** [comment]
@thadguidry ,

Great! I will give it a whirl. 

Kingsley

**Comment by kidehen** [comment]
@thadguidry,

I've looked at the DBMS connection, which I assume is JDBC-based, but it only offers PostgreSQL, MySQL, and MariaDB as options. How do I make generic JDBC connection? 

Kingsley

**Comment by thadguidry** [comment]
@kidehen We're open source.  So hack on [the inner of the "database" extension](https://github.com/OpenRefine/OpenRefine/tree/master/extensions/database)

@tcbuzor @jackyq2015  Can you assist Kingsley on what he needs to do , other than [providing the ConnectionManager and DatabaseService classes](https://github.com/OpenRefine/OpenRefine/tree/master/extensions/database/src/com/google/refine/extension/database/pgsql) ?
