### ISSUE TITLE
add find() function similar to match()  but can do re.findall() in python

### ISSUE THREAD

**Issue by ettorerizza** [OpenRefine/OpenRefine#1296]
I do not like `match()` and I'm sure I'm not the only one. As much as `replace()` is a pleasure to use, so much `match()` gives me a headache. In 90% of the cases, someone who uses this function wants to find some substrings in a string using a regular expression. But why is it absolutely necessary that this function imposes to match first the whole cell? In any regular expression tester, like regex101.com, you just have to match the pattern that interests you. Same thing in Python/Jython.

Let's take an example with this dataset:

```
name
Jean De Dinant
Jeanne de Paris
```

If I want to extract all the words that begin with the capital letter D, the Python regex will be very simple:

![screenshot-127 0 0 1-3333-2017-11-01-18-17-55-322](https://user-images.githubusercontent.com/6286410/32287656-d048d19a-bf31-11e7-9cb6-d1f344057438.jpeg)

But with `value.match()`, you have to spend five minutes wondering why this formula does not produce the expected result.

![screenshot-127 0 0 1-3333-2017-11-01-18-47-34-165](https://user-images.githubusercontent.com/6286410/32288800-57c1327c-bf35-11e7-82c1-c4d6f2d68d7d.jpeg)

Nor this one : 

![screenshot-127 0 0 1-3333-2017-11-01-18-48-38-322](https://user-images.githubusercontent.com/6286410/32288807-5ecc9106-bf35-11e7-8f34-3f365f434c81.jpeg)

@thadguidry  wrote somewhere that GREL must be a _walk in the park_. This is certainly the case for `value.replace()`, but `value.match() ` looks more like a walk in the mud on a rainy day. Would not it be a good idea to rewrite this function to make it an equivalent of `value.replace()`, a kind of `value.find()` that would include `contains()` by accepting both a string and a regex?

On the string "HELLO World!", it will send back:

```
value.find("World")

["world"]

value.find(/[A-Z]{2,}/)

["HELLO"]

value.find(/\w+/)

["HELLO", "World"]

value.find(/(hello|world/i)[0]

["HELLO"]
```

**Comment by jackyq2015** [comment]
but what's the fundamental difference do you expect from the future find() and current match()?

**Comment by ettorerizza** [comment]
@jackyq2015 Simply that it works in a natural way. On the string "Hello World", how would you, with `match()`, extract all words that start with a capital letter? Or maybe I don't understand it correctly.

**Comment by ostephens** [comment]
It feels like what is needed here is just a ‘regex’ function that takes a regex and returns an array of any capture groups

I would say the two things that frustrate me about ‘match’ are:

1) the need to match the entire string
2) the inability to do a /g flag to do a global reg ex

**Comment by jackyq2015** [comment]
@ettorerizza you should have be able to do group and get the result. something like this:
value.match(/(([A-Z](.+?))) /)

But seems it doesn't work. I would say it's a bug.

**Comment by ettorerizza** [comment]
@jackyq2015 It's not a bug, it's unfortunately a feature. [The documentation is clear on this.](https://github.com/OpenRefine/OpenRefine/wiki/GREL-String-Functions#matchstring-s-regexp-p) 

On the string "`hello 123456 goodbye`", you can't simply extract the number with `value.match (/(\d{6})/)`.  You must match the whole string and indicate between parentheses the part you want to extract, that is to say: `value.match (/.*(\d{6}).*/)`.

**Comment by jackyq2015** [comment]
GREL match just wrapped the java java.util.regex.Matcher. But java.util.regex.Matcher is able to do the same thing your python script does. If we stick with the document, current behaviour follow the spec well. 
Maybe we can add another function findall to do the same thing. thought?

**Comment by ettorerizza** [comment]
@jackyq2015 Exactly. Looks like the [find() method ](http://tutorials.jenkov.com/java-regex/matcher.html) already exists and it would be easy to create a `match()` variant named `find()`.

> matches()
> The matches() method in the Matcher class matches the regular expression against the whole text passed to the Pattern.matcher() method, when the Matcher was created. Here is a Matcher.matches() example:
> 
> String patternString = ".*http://.*";
> Pattern pattern = Pattern.compile(patternString);
> 
> boolean matches = matcher.matches();
> **If the regular expression matches the whole text**, then the matches() method returns true. If not, the matches() method returns false.
> 
> **You cannot use the matches() method to search for multiple occurrences of a regular expression** in a text. **For that, you need to use the find(), start() and end() methods.**

**Comment by ettorerizza** [comment]
[Related question on StackOverflow.](https://stackoverflow.com/questions/47500019/regex-possible-to-match-repeated-patterns-in-openrefine)
