### ISSUE TITLE
Transform not executing

### ISSUE THREAD

**Issue by schignel** [OpenRefine/OpenRefine#1298]
GREL functions that have no syntax errors do not execute. Nothing happens when the "OK" button is pressed. Video is attached for reference.

Open Refine 2.7
Firefox 57.0b13 (64-bit) 

![image](https://user-images.githubusercontent.com/19474876/32301277-3738c860-bf55-11e7-99ae-fe94a746acb3.png)
 
[capture.zip](https://github.com/OpenRefine/OpenRefine/files/1435929/capture.zip)

**Comment by jackyq2015** [comment]
just tied with the head version without issue. Did you see any exception from the console. or can you try chrome instead?

**Comment by schignel** [comment]
Thanks@jackyq2015! Switching to Chrome fixed the problem. 

So something to with Firefox? I have a number of add-ons enabled. I have listed them below in case this is useful for bug fixing (listed below):

![image](https://user-images.githubusercontent.com/19474876/32302914-358cc5b8-bf5d-11e7-8902-5ea5aa84cd4d.png)

**Comment by jackyq2015** [comment]
I just tried on firefox and works well also. It's hard to say which plugin cause issue. I haven't heard most of them. You can open the developer tool by press ctrl-shift-I to watch if there is any exception on the javascript console to help troubleshooting. close for now

**Comment by ettorerizza** [comment]
@jackyq2015  @schignel Ok, I see, the problem comes from [Poper Blocker extension](https://addons.mozilla.org/en-US/firefox/addon/poper-blocker-pop-up-blocker/).
