### ISSUE TITLE
Display the git version when startup

### ISSUE THREAD

**Issue by jackyq2015** [OpenRefine/OpenRefine#1305]
Right now, we have the following message on the console when startup:
00:19:26.615 [                   refine] Starting OpenRefine 2.7 [TRUNK]... (22ms)

Instead of TRUNK, need a git version to precisely identify a version.

**Comment by jackyq2015** [comment]
Push this task. it should be done with part of the build system migration(gradle or maven)

**Comment by thadguidry** [comment]
@wetneb Can you add/squeeze this into 3.1 ?

**Comment by wetneb** [comment]
Sure, good idea!
