### ISSUE TITLE
RDF extension display in browser distorted

### ISSUE THREAD

**Issue by ygherman** [OpenRefine/OpenRefine#1316]
Hi, 
I'm having a display issue with the rdf extension, in the skeleton editing window.
The display in chrome and firefox (these are the browsers I've checked) of the skeleton editing windows is distorted that I cannot edit and configure all the fields I need.

Attached is the view of the display I'm getting:

![image](https://user-images.githubusercontent.com/2689048/32618786-52e0676c-c581-11e7-9531-651804facdf0.png)

thx.

**Comment by wetneb** [comment]
@ygherman hi, we are aware of this issue but the RDF extension is not maintained by this team. I think this extension is looking for a maintainer actually.

**Comment by fpompermaier** [comment]
We could tale care of it...could it be possibile to move it under an
official repo?

**Comment by ettorerizza** [comment]
https://github.com/fadmaa/grefine-rdf-extension

The author is @fmaali

**Comment by fpompermaier** [comment]
How can we ask for its ownership ?

**Comment by wetneb** [comment]
@fpompermaier just fork it and you'll be the owner :)

**Comment by ettorerizza** [comment]
The Github repo does not mention a type of license. I don't know who owns the intellectual property. This extension was developed within the DERI research center, which no longer exists, I believe, or has been merged. The best is to ask the author.

**Comment by thadguidry** [comment]
All software produced in DERI is BSD licensed.  Even if @fmaali doesn't recall :)  He and Richard mentioned it once in a talk http://refine.deri.ie/

**Comment by fpompermaier** [comment]
@wetneb I was referring to an official ownership...the right term is repository transfer: https://help.github.com/articles/about-repository-transfers/

**Comment by wetneb** [comment]
@fpompermaier my point is that you don't need to transfer the repository at all! If you start maintaining your own fork of it, you'll be de facto the owner of the "official" repo. That's the good thing about FOSS! :)

**Comment by magdmartin** [comment]
@fpompermaier Please lets us know what is the new project URL so we can promote and redirect users.

**Comment by fpompermaier** [comment]
We made a fork at https://github.com/okkam-it/grefine-rdf-extension but we
need some time to align our code (that use a mavenized version of Refine)
and to check if it works with Refine 2.7 and the code on the master branch.
We'll let you know once ready

**Comment by ettorerizza** [comment]
@fpompermaier For your information, [here is another fork](https://github.com/stkenny/grefine-rdf-extension/tree/9fd2005aa2b5570f54db32dc00287acffeb9b2a0) that I have not tested, but quite recent. However, it uses a modified version of Open Refine with Jetty9, if I understand correctly, and I don't remember why.

**Comment by stkenny** [comment]
@ettorerizza I had to modify Open Refine to remove the dependency on xerces-j. It was the only way I could find to resolve classpath problems with the extension. I'll look at bringing the forks up to date to see if the extension works with the latest.
