### ISSUE TITLE
new translation from weblate break the master

### ISSUE THREAD

**Issue by jackyq2015** [OpenRefine/OpenRefine#1325]
There is a empty translation file from weblate which cause issue on master:
https://github.com/OpenRefine/OpenRefine/commit/62be866a9f6346f0f62bcf60a150ebc6ed51de9f

need to find out why and how to prevent in future.

**Comment by wetneb** [comment]
Yes this is annoying, this has already happened in the past and I have just deleted the translation. I will work on a cleaner solution so that OpenRefine just ignores these translations.

**Comment by jackyq2015** [comment]
Not sure if this can be done from the weblate side. Another option is to merge to a dedicated branch and manually merge to master after review.

**Comment by nijel** [comment]
Weblate can also generate JSON file with empty translations for new language, would that work better for you?

If this is desired, just set "Base file for new translations" under [File settings for your translation](https://hosted.weblate.org/settings/openrefine/translations/#files) to translation to use a a template (translations will be removed when using it).

**Comment by wetneb** [comment]
@nijel thanks a lot for chiming in, it's good to know! In our case I don't think it would work as the language name would be empty, so we could end up with blank labels in our drop-down list of languages to choose from.
