### ISSUE TITLE
transformer dialog  is displayed all along the screen

### ISSUE THREAD

**Issue by jackyq2015** [OpenRefine/OpenRefine#1332]
As mentioned in https://github.com/OpenRefine/OpenRefine/issues/1221#issuecomment-344499767, the dialog should keep the consistence with others.

**Comment by thadguidry** [comment]
Thanks for the temp fix on this Jacky.  Hoping we can get much better dialog handling in later milestones.  We'll close this now.

**Comment by tfmorris** [comment]
The highest priority for consistency is between the three transform expression dialogs, which are different after this change, and, only then, with other similar dialogs.

We also don't have support for resizable dialogs (as mentioned in #421), so they can't be sized by percentages.
