### ISSUE TITLE
RowCount Project Metadata only updated on Project File save

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1335]
The RowCount in the Project metadata is only updated when the project is saved to file. This only happens after the autosave interval (default 5 minutes) or on quitting OpenRefine.

This means that changes (e.g. removal of rows from a project) are not reflected in the project metadata display until the save has happened.

**Comment by thadguidry** [comment]
@ostephens With #1342 this is now fixed, and the Row Count metadata column is updated immediately whenever our datagrid view is updated through /core/get-rows command https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/commands/row/GetRowsCommand.java
