### ISSUE TITLE
Retrieving releases.js from http://google-refine.googlecode.com/svn/support/releases.js produces a 404

### ISSUE THREAD

**Issue by marioa** [OpenRefine/OpenRefine#1337]
Downloaded and installed open refine 2.7 on a mac with high sierra. Uploading files on chrome was giving me some anomalous behaviour. Looked at the chrome development tool and it notified me that trying to retrieve releases.js from http://google-refine.googlecode.com/svn/support/releases.js produces a 404. On the mac found this was produced by ./Resource/webapp/modules/core/scripts/index.js at (line numbers):

```
120           var script = $('<script></script>')
121           .attr("src", "http://google-refine.googlecode.com/svn/support/releases.js")
122           .attr("type", "text/javascript");
123           document.body.appendChild(script[0]);
```

Sounds like a relatively fix. If the javascript is being used find a new distribution point, if it is not then it can be removed.

**Comment by ostephens** [comment]
Thanks @marioa - there is a fix for this ready for the 2.7.2 release  - see https://github.com/OpenRefine/OpenRefine/commit/e482878596cbda7d6e7e99cb1f02d57aa8f4d549#diff-6d8a16be362b3c276c8837f74ac81415
