### ISSUE TITLE
Improve Datagrid performance

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#1347]
In general, we want to improve the datagrid performance, perhaps with newer, more performant javascript libraries, etc.

See document [Planned in Phase 2 enhancements](https://docs.google.com/document/d/1lK3LT9Llwxqv4NFSQO33UX-P3vD1MzYefv6YCtf6HHk/edit?usp=sharing)

**Comment by wetneb** [comment]
Let's close this as a duplicate of #583.
