### ISSUE TITLE
Allow to delete all projects

### ISSUE THREAD

**Issue by xseris** [OpenRefine/OpenRefine#1353]
maybe an option that allows to delete all projects can be useful:
![](https://i.imgur.com/WnEnsWR.png)

**Comment by ettorerizza** [comment]
Most dangerous option ever ! Especially since it can be done easily by opening the workspace directory, CTRL + A, DEL. 

@xseris Your tag system is pretty cool. Could you share the recipe? :)

**Comment by jackyq2015** [comment]
should just go to work space and delete all files easier? but delete all is really dangerous option to provide

**Comment by xseris** [comment]
@ettorerizza I know that could be dangerous, but in my personal implemetation is a "tag-based remove all". The upper bar contains all defined project tags, and clicking on one of them returns and shows a filtered list of projects that contain that specific tag. Then can be all removed in block (Of course with a warning message).  Answering your question: Yes, I can share this tag-system implementation, but i need some time to isolate the feature's code from other junk personal implemented stuff.

**Comment by ettorerizza** [comment]
In this case, it's different. The option seems quite justifiable.

**Comment by xseris** [comment]
@ettorerizza I have isolate the tag system code, the following is a fast screencast of the feature...

![](https://i.imgur.com/wSVMexx.gif)

I created a PR ( #1357 ) if you want to test it more deeply

**Comment by ettorerizza** [comment]
@xseris Many thanks, I'll try this !

**Comment by jackyq2015** [comment]
PR was merged
