### ISSUE TITLE
isX functions should support value.isX() syntax

### ISSUE THREAD

**Issue by msaby** [OpenRefine/OpenRefine#1358]
isBlank, isNonBlank, isNull, isNotNull, isNumeric, isError functions are not supporting value.function() syntax but only the function(value) syntax.
Is there a reason for that? Could it be fixed?

**Comment by jackyq2015** [comment]
isX is not a function. All the isX() implements "Control" interface. A control can decide which part of the code to execute and can affect the environment bindings.  Functions, on the other hand, can't do either.

**Comment by ettorerizza** [comment]
Right ! This is obvious for if() or forEach(), but isBlank() and co looks much more like functions. I'll add a clarification in the documentation.

**Comment by jackyq2015** [comment]
@ettorerizza thanks for the documentation.
