### ISSUE TITLE
Checkstyle

### ISSUE THREAD

**Issue by fpompermaier** [OpenRefine/OpenRefine#1359]
Hi to all,
what about introducing some checkstyle for Refine...?

**Comment by jackyq2015** [comment]
@fpompermaier Any recommendation on your mind?

**Comment by fpompermaier** [comment]
The simplest thing is to use google checkstyle:
http://checkstyle.sourceforge.net/google_style.html

**Comment by wetneb** [comment]
@fpompermaier does this actually perform any fixes? Codacy already provide style warnings:
https://www.codacy.com/app/OpenRefine/OpenRefine/dashboard

**Comment by fpompermaier** [comment]
I just didn't know Refine was using a checkstyle. Is there any wiki about how to enable it on Eclipse and IntelliJ?

**Comment by wetneb** [comment]
@fpompermaier I'm not sure if Codacy has any Eclipse or IntelliJ integrations - your best bet is probably to look at the underlying tools that they use to generate the warnings and configure them locally.

**Comment by thadguidry** [comment]
@fpompermaier Most folks just use PMD and its what Codacy uses behind the scenes for Code Style checking  https://marketplace.eclipse.org/content/eclipse-pmd

Feel free to submit pull requests on all 365 issues it currently finds here :) 
https://www.codacy.com/app/OpenRefine/OpenRefine/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQ2F0ZWdvcnkiLCJ2YWx1ZXMiOlsiQ29kZSBTdHlsZSJdfSx7ImlkIjoiTGV2ZWwiLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IlBhdHRlcm4iLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W251bGxdfV0=
