### ISSUE TITLE
XML import merges records together

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#137]
_Original author: iainsproat (September 22, 2010 10:02:42)_

Imported a small Xml file but the project, attached, can not be displayed in the browser.  The browser complains of unresponsive script on various lines of project-bundle.js (lines 52, 29, 40 &amp; 109 have been indicated at various stages).

The unresponsive script seems to be happening after the GET response for /scripts/views/data-table/column-header.html

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=137_
##

**Comment by tfmorris** [comment]
_From tfmorris on October 14, 2011 18:49:13:_
I think I've figured out what the problem is here.  The column groups for this XML fragment are getting computed incorrectly:

```xml
   <sponsors>
      <lead_sponsor>
        <agency>National Center for Research Resources (NCRR)</agency>
        <agency_class>NIH</agency_class>
      </lead_sponsor>
      <collaborator>
        <agency>HRSA/Maternal and Child Health Bureau</agency>
        <agency_class>U.S. Fed</agency_class>
      </collaborator>
    </sponsors>
```

Refine is currently computing three column groups from this: lead_sponsor (2 columns), collaborator (2 columns), and sponsor (all 4 columns).  This last group is triggering unnecessary row dependencies when there is no collaborator element.

I'm tempted to say that column groups which consist of nothing but other groups, without any individual ungrouped columns of their own should be eliminated, but it's a fairly critical piece of code, so I want to look at it a little more closely.

p.s. I suspect the reason for the sluggish browser performance is that it was trying to deal with the entire file at once since the monster second record effectively disabled the paging.

**Comment by tfmorris** [comment]
_From tfmorris on October 27, 2011 00:04:03:_
Reversing course, I now think that perhaps we should be computing row->record dependencies directly since we have that information from the parse.  We know what the path to the top level element is and, by definition, all rows that we create during the parse of its children are part of the same record.

Visually the column groups look like this:

```
Col #         2222333344445555
Sponsor group SSSSSSSSSSSSSSSS
Lead/Collab   CCCCccccLLLLllll
```

The three groups are group S, group Cc, and group Ll.Note that the columns have been reordered with the Collaborator columns before the Lead columns.  Group S is the problematic one.  Since the Collaborator sponsors are optional, that means that the "key" column #  2 can be blank for a top level record, causing it to get merged with the previous record (the algorithm searches back for a row with a non-blank "key" cell if any of the cells in the column group are non-blank).

Group S is a real column group (consisting solely of other column groups), but since we don't appear to use column groups for anything, I'm not sure what value it has.

I think there are two options here:
1. Eliminate column groups which consist solely of other column groups from the dependency analysis
2. Compute row dependencies using a different method than column groups (eg use the tree structure directly from the parse).

Opinions?

**Comment by eswright** [comment]
Is this what might be causing my json import not to give all records an index?

**Comment by wetneb** [comment]
@eswright I suspect it might. I have run into the same problem today actually.

**Comment by eswright** [comment]
Any suggestions on how to rebuild a record index?   All my data is parsed but just a bunch of records are merged into one.

**Comment by thadguidry** [comment]
@eswright Hi Eric, yeah, we have a bug in our column counting strategy, as @tfmorris hinted at above, and its never been found yet because of our lack of time, sorry about that.  But for now, you could just MANUALLY parse the data by selecting the upper most outer record set element visually with the Json Importer...then you'll get some rows...and then manually parse those with Add new column using GREL parseJson() function as our Wiki has a few recipes and examples.  That will probably get you by for now with nice record rows.  Hopefully we can find time to work on this issue more by the end of the year.  Having more example data that causes the issue would be EXTREMELY HELPFUL !  If you can upload your JSON file somewhere and email me the link, then I can analyze more for you.

**Comment by wetneb** [comment]
@thadguidry Here is an example dataset:
https://figshare.com/articles/GRID_release_2017-07-12/5203408
(the file where I observed the problem is "grid.json")

**Comment by thadguidry** [comment]
@eswright Thanks Eric.  We got the linked file you sent privately to us.  Yeah, I see a problem, where not all the objects in the large array get created in OpenRefine 2.7 release.  I've sent this to @jackyq2015 as well.  Stay tuned over the next few weeks while we work on a the issue and a fix.

@wetneb Thanks Antonin, that file will help us also !

**Comment by thadguidry** [comment]
@jackyq2015 I'd say this need to be our highest priority issue at the moment, it looks like we're throwing away records of data during import. Not good.

**Comment by jackyq2015** [comment]
Those file provided are huge. I can see the column count issue and it's hard to debug. can somebody provide a minimum data set on which can reproduce this problem? or this issue only happens when have large data set like this?

**Comment by wetneb** [comment]
@jackyq2015 Here is a much smaller file where the same problem appears: the source file contains eight records, OpenRefine merges some of them and obtains only four.
http://pintoch.ulminfo.fr/49a768ad87/grid_small.json

**Comment by jackyq2015** [comment]
@wetneb Tried this file. it generated a project with 63 columns and 63 rows in row mode. But I did not see the missing rows. The problem I see is that the column and data are messed up. I think for that big file where appeared to import partially may due to the "record mode"?  

I need to find out what exactly the issue before I can fix it.

**Comment by wetneb** [comment]
Hi @jackyq2015. In rows mode all is fine indeed, but when you switch to records mode you will see that some records are merged together.
![2017-08-02-072715_1920x1080_scrot](https://user-images.githubusercontent.com/309908/28860542-f6ce797a-7754-11e7-898a-2628e1c78428.png)

**Comment by jackyq2015** [comment]
I think the problem is under records mode OR miscalculate the row dependency under some situation. It causes some root node were flagged as a child node. From the UI aspect, they are merged together. Not found the solution yet. will work out it.

**Comment by jackyq2015** [comment]
I fixed it. can somebody help to test it from https://github.com/jackyq2015/OpenRefine? If it works as expected, I will create a PR for this. cheers!

**Comment by wetneb** [comment]
@jackyq2015 that's fantastic! It works indeed for my example.
It'd be great to have a test for that (I can help if needed).
