### ISSUE TITLE
Weblate unable to push new translations

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1374]
Now that the master branch is protected, Weblate fails to push new translations. One possible solution would be to change the weblate user to administrator, but that's not really ideal… Any better ideas?

Also, it's currently failing to merge translation files. I will look into solving that.

**Comment by magdmartin** [comment]
Can weblet push to a dedicated branch?

On Dec 5, 2017 6:48 AM, "Antonin Delpeuch" <notifications@github.com> wrote:

Now that the master branch is protected, Weblate fails to push new
translations. One possible solution would be to change the weblate user to
administrator, but that's not really ideal… Any better ideas?

Also, it's currently failing to merge translation files. I will look into
solving that.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenRefine/OpenRefine/issues/1374>, or mute the thread

**Comment by wetneb** [comment]
@magdmartin I did not find any such option in the configuration panels.

**Comment by thadguidry** [comment]
I think I fixed it.  I checked the option under Protected Branch to "Restrict who can push to this branch" and then added Weblate user.

**Comment by jackyq2015** [comment]
they really should provide this push to branch feature. it is quite useful

**Comment by thadguidry** [comment]
@jackyq2015 what do you mean ? They already provide that, we are just restricting direct pushes to Master branch and requiring pull request reviews before merging.

**Comment by jackyq2015** [comment]
got it. I thought they do not have that.

**Comment by wetneb** [comment]
@thadguidry no, I just tried triggering a push from Weblate and it's still rejected:
```
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: At least one approved review is required by reviewers with write access.        
To github.com:OpenRefine/OpenRefine.git
 ! [remote rejected]   master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:OpenRefine/OpenRefine.git' (1)
```

**Comment by thadguidry** [comment]
@wetneb Ah, approved review required.  let me see...

**Comment by thadguidry** [comment]
@wetneb Weird, it says that it should be allowed to push. See ?  Click the EDIT button at bottom next to Master branch on here:  https://github.com/OpenRefine/OpenRefine/settings/branches/master

**Comment by wetneb** [comment]
It only works if we uncheck "Require pull request reviews before merging".

**Comment by jackyq2015** [comment]
we can separate out the translation as a submodule by creating a repo under openrefine and lift the restriction just for translate. For user there is no difference.

**Comment by wetneb** [comment]
@jackyq2015 hmm, that's a nice idea, but I see a few issues:
* it does make things a bit harder for users as a simple "git clone" will not fetch everything as it currently does
* currently we are only translating files in one folder but we might want to include translations of extensions later (for instance, the wikidata extension)
Maybe we can ping @nijel for his kind input on this issue?

**Comment by nijel** [comment]
Weblate can also create pull requests with the changes, maybe that would be better fit for your project?

I thought there is way to configure GitHub to dismiss checks for certain users for protected branch, but I've never used this feature myself, so I really can't help here.

**Comment by wetneb** [comment]
@nijel the docs say that this feature (github pull requests) isn't available on hosted.weblate.org (and indeed I cannot find it in the configuration screens).

**Comment by nijel** [comment]
Apparently the docs was wrong (I've just fixed that). It just has to be configured manually.

**Comment by nijel** [comment]
Here is first PR: https://github.com/OpenRefine/OpenRefine/pull/1375

**Comment by wetneb** [comment]
@nijel thank you so much!
