### ISSUE TITLE
Reconcile->"Match All Filtered Cells to..." option

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1376]
The "Match All Filtered Cells to..." action (under the Reconcile/Actions section of the column drop down menu) is designed to look up a value on Freebase and allow the user to match all cells (in the current filtered view) to that Freebase topic.

Since Freebase no longer exists, this option no longer works as expected.

On the basis we shouldn't have options that don't work, I suggest that we:

* Remove this option for now
* Consider implementing a new, similar, option, but one which (a) uses the Suggest API and (b) allows the user to choose from any Reconciliation target implementing the Suggest API which the install of OR has in its list of registered reconciliation services

Comments? @thadguidry @ettorerizza @wetneb

**Comment by ettorerizza** [comment]
@ostephens Are we talking about the same thing? The "match each cell to its best candidate" feature  works with any reconciliation service, not just Freebase. I see it as a very practical way to batch reconcile cells  when, for example, a facet has been used to filter candidates with a high score. This is at least how I use it, but perhaps it had another goal in the beginning?

**Comment by ostephens** [comment]
@ettorerizza no - this is a different option - apologies I got the labelled slight wrong originally - I've amended this issue.

Here it is in the menu:

<img width="749" alt="screen shot 2017-12-08 at 15 17 31" src="https://user-images.githubusercontent.com/576174/33771989-069e9476-dc2b-11e7-8f1b-48b84a3f075b.png">

**Comment by ettorerizza** [comment]
Yes, this feature has certainly become useless. Having never used it in the past, I don't know if it was useful nor if it should be adapted.

**Comment by wetneb** [comment]
@ostephens absolutely! It would be very useful to migrate this as you suggested.
