### ISSUE TITLE
Jython: not all variables are available

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1377]
Not sure if this is intended, but I find it annoying that the fields of some variables available in GREL do not seem to be available in Python. For instance, the famous `cell.recon.match.id` GREL expression works fine, but `return cell.recon.match.id` does not work in Jython. Wouldn't it be better to make this more uniform?

**Comment by ettorerizza** [comment]
@wetneb It can be accessed, but as a value in a dictionary ( return cell['recon']['match']['id'] ). the dot notation does not work in Python.

![screenshot-127 0 0 1-3333-2017-12-12-09-30-44-368](https://user-images.githubusercontent.com/6286410/33874586-974133a2-df1f-11e7-9758-c0bb5735f432.png)

**Comment by wetneb** [comment]
@ettorerizza ah, thanks a lot! Do you think it make sense to also allow the dot notation too?

**Comment by ettorerizza** [comment]
Of course, it would be much more convenient ! To get the list of values in a record, the formula is `row['record']['cell']['column name']['value']`

This is very boring to write without autocompletion ...
