### ISSUE TITLE
Renaming a column should update the facets

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1379]
When renaming a column, the facets that rely on it should be updated to refer to the new column name. That might be a bit hard to do in general as facets can contain arbitrary expressions…

**Comment by thadguidry** [comment]
@wetneb Hmm, shouldn't be hard.  PostCoreProcess supports updateOptions and we seem to already store and keep the expression of the bound Facet even after a Column rename, we just don't seem to update dynamically a particular Facet id.

```
<a href="javascript:{}" class="facet-choice-link" bind="changeButton" title="Current Expression: grel:value +12">change</a>
<span bind="titleSpan">Source</span>
```

**Comment by wetneb** [comment]
@thadguidry my point is that facets can contain arbitrary GREL, Python, Clojure expressions… so you need to dive down in these expressions, find out where columns are used, rename them, and generate a new expression. That's because we have access not just to the `value` variable, but also to the whole `cells` object.

**Comment by thadguidry** [comment]
@wetneb Ah, yes, and that.

**Comment by wetneb** [comment]
Closing as a duplicate of #133.
