### ISSUE TITLE
Flyout service amputates ids with a hash character "#"

### ISSUE THREAD

**Issue by ddu1** [OpenRefine/OpenRefine#1381]
In the [suggest API](https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation-Service-API#suggest-apis), it seems like the flyout service returns a partial id string if the id has a "#" character. For example, if the id is `somedomain#sometopic` and the flyout endpoint is `/api/flyout`, openrefine will try to make a request to 

`.../api/flyout?id=somedomain`

instead of

`.../api/flyout?id=somedomain#sometopic`

This can be reproduced in OpenRefine2.8 on Mac OS 10.13

Any idea?

**Comment by wetneb** [comment]
that seems to indicate that OpenRefine is not properly url-encoding this parameter. I suspect it should not be too hard to solve.

Out of curiosity, are you encountering this problem in an existing reconciliation service, or are you building a new one?

**Comment by ddu1** [comment]
I encountered this problem in a customized reconciliation service.
