### ISSUE TITLE
use the local time instead of GMT+0 for "modified time"

### ISSUE THREAD

**Issue by jackyq2015** [OpenRefine/OpenRefine#1383]
For project related class, upgrade the current java.util.Date and Calendar of JDK7 to use java.time.LocalDateTime of JDK8. Will deal with others later to narrow down the scope of change.

**Comment by tfmorris** [comment]
This is completely wrong! `java.time.LocalDateTime` doesn't represent an instant in time because it has no timezone information. This never should have been merged.

**Comment by thadguidry** [comment]
@tfmorris See all the fun you missed out on Tom while being away? :-)  Seriously though, thanks very much for coming back and helping us fix some of the wrongs.
