### ISSUE TITLE
testUrlCaching UT failed in windows

### ISSUE THREAD

**Issue by jackyq2015** [OpenRefine/OpenRefine#1389]
[testng] FAILED: testUrlCaching
   [testng] java.lang.AssertionError: expected [false] but found [true]
   [testng] 	at org.testng.Assert.fail(Assert.java:94)
   [testng] 	at org.testng.Assert.failNotEquals(Assert.java:513)
   [testng] 	at org.testng.Assert.assertFalse(Assert.java:63)
   [testng] 	at org.testng.Assert.assertFalse(Assert.java:73)
   [testng] 	at com.google.refine.tests.model.UrlFetchingTests.testUrlCaching(UrlFetchingTests.java:156)
   [testng] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [testng] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   [testng] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [testng] 	at java.lang.reflect.Method.invoke(Method.java:498)
   [testng] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
   [testng] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
   [testng] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
   [testng] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
   [testng] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
   [testng] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
   [testng] 	at org.testng.TestRunner.privateRun(TestRunner.java:782)
   [testng] 	at org.testng.TestRunner.run(TestRunner.java:632)
   [testng] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
   [testng] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
   [testng] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
   [testng] 	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
   [testng] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
   [testng] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
   [testng] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
   [testng] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
   [testng] 	at org.testng.TestNG.run(TestNG.java:1064)
   [testng] 	at org.testng.TestNG.privateMain(TestNG.java:1385)
   [testng] 	at org.testng.TestNG.main(TestNG.java:1354)
   [testng] 
   [testng] 
   [testng] ===============================================
   [testng]     tests
   [testng]     Tests run: 298, Failures: 1, Skips: 0
   [testng] ===============================================

**Comment by wetneb** [comment]
yes, this happens when the network is too slow. Your fix looks great, thanks!

**Comment by jackyq2015** [comment]
actually the problem still there. there is some other reason.

**Comment by jackyq2015** [comment]
submitted the PR. it is a network issue. Appveyor has some network policy to control the access the external network.
