### ISSUE TITLE
move the tag system data from the Project Metadata to Data Package metadata

### ISSUE THREAD

**Issue by jackyq2015** [OpenRefine/OpenRefine#1404]
Data Package metadata has the same idea but different name(keywords). Better to move the tag system to hook with Data Package metadata

Please voice if you have any objection or concern.

**Comment by thadguidry** [comment]
@jackyq2015 no concerns on the mapping between the 2 ideas.  Yes, even Schema.org uses "keywords" to represent the idea of "tags" or "tagwords".

**Comment by wetneb** [comment]
I believe this issue will disappear as we have decided to store all the project-level metadata in the existing ProjectMetadata object (so, no DataPackageMetadata object).
