### ISSUE TITLE
is there has a short key support in the openrefine?

### ISSUE THREAD

**Issue by zhouyao1994** [OpenRefine/OpenRefine#1408]

**Comment by wetneb** [comment]
@zhouyao1994 Please ask your questions on the mailing list, Stack Exchange or Twitter. Do you mean keyboard shortcuts? It would help if your question was a bit more explicit.

**Comment by zhouyao1994** [comment]
@wetneb  oh thank you very much to remind me . i just find that there is no support for the keyboard shortcuts support~
