### ISSUE TITLE
Add translatable for core-buttons "browse"

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#1409]
In the [import-from-computer-form.html](https://github.com/OpenRefine/OpenRefine/blob/bdf1c3eda7ba55cc037565a5635201f9bcdf4a17/main/webapp/modules/core/scripts/index/default-importing-sources/import-from-computer-form.html#L3) and [sources.js](https://github.com/OpenRefine/OpenRefine/blob/d5fb07384242d07241b0ce103c47d930046f1135/main/webapp/modules/core/scripts/index/default-importing-sources/sources.js#L50)
we have a **Browse...** button and associated "no files selected" text
that remain non-translatable and should be assigned id's to make translatable in https://github.com/OpenRefine/OpenRefine/tree/master/main/webapp/modules/core/langs

**Comment by AlexandruAmarandei** [comment]
Hello, I think I've solved the main issue. It still need the proper string id's in https://github.com/OpenRefine/OpenRefine/tree/master/main/webapp/modules/core/langs. Until then I've just used Select Files to Import. Should I also apply this to the import project html?

**Comment by dbutlerdb** [comment]
Is this one solved?

**Comment by ostephens** [comment]
I don't think anyone has got back to @AlexandruAmarandei so I don't think is resolved yet

**Comment by magdmartin** [comment]
ping @OpenRefine/core regarding @AlexandruAmarandei  question.

**Comment by AlexandruAmarandei** [comment]
@dbutlerdb  @ostephens @magdmartin , I wrote a solution but didn't have time to implement the rest of the code for the other browse buttons. Exams started so I'll see when I have time to finish it. Feel free to add to my solution.

**Comment by thadguidry** [comment]
@AlexandruAmarandei we'd love to see this finished!

**Comment by kovacskarolina** [comment]
Hi, I'd like to continue this issue. Can I work on it?

**Comment by thadguidry** [comment]
@kovacskarolina Yes, thanks!

**Comment by kovacskarolina** [comment]
@thadguidry This method provided here is not working for me.  (https://github.com/OpenRefine/OpenRefine/wiki/Translate-OpenRefine)
Can't recognize new strings that I add at the .json files and also throws the error: ,,$.i18n._ is not a function".

**Comment by thadguidry** [comment]
It seems that Forms[1] and in particular elements on forms like `<input type="file">` and other types[2] are handled by localization within browsers themselves.
1. https://www.w3.org/International/wiki/Locale-based_forms
2. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#Localization

Given this new found information, we can probably close this issue now.
