### ISSUE TITLE
fetching URL in OR 2.8 sometimes get data from other column of the project

### ISSUE THREAD

**Issue by msaby** [OpenRefine/OpenRefine#1411]
I'm not sure if it is the same bug as the one described for previous versions:
In OR 2.8 on Mac, I am trying to fetch the json data behind this URL : https://geo.api.gouv.fr/communes?lon=1.083333&lat=49.433333

With caching off, OR gives me in the resulting column ("wo_cache_clear") the content of an other column of my project! (value = "Populated", which is present in 2 of my columns). I have never encountered this bug before !

If I choose to show the errors,  I have this message, related to a certificate error. I am surprised, because I thought I had fixed this issue before...
"sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"

![image](https://user-images.githubusercontent.com/932804/34467353-4b9f6a88-eeef-11e7-946a-99f64a16c24e.png)

**Comment by wetneb** [comment]
Wow, that is a strange bug. It would be great if you could post an excerpt of your file and a JSON operation history which lets us reproduce the issue.

Out of curiosity, why did you disable caching? Is there still any issue with this feature?

**Comment by msaby** [comment]
I disabled caching because I remember there were a bug in 2.7. I thought it was linked, but no...
Unfortunately I don't have anymore the history, and I can't reproduce the bug easily, because I updated the JDK of my system, in order to fix the SSL issue.

**Comment by wetneb** [comment]
Closing as not reproducible.
