### ISSUE TITLE
id of deleted project will be kept in workspace.json

### ISSUE THREAD

**Issue by zazi** [OpenRefine/OpenRefine#1418]
I have a project that makes use of another project (as mapping table). After the processing (i.e. application of the mapping rules (JSON history) + exporting the result), I'm deleting both projects. Only the id of the main project will be kept in workspace.json. The auxiliary project (with the mapping table) disappears as expected. When I restart OpenRefine, it tries to recover the project whose id still has been left in the workspace.json. When I try to reimport both projects and do the processing afterwards, then the mapping table won't be applied. So I guess it has something to do with the incomplete removal (and the unsuccessful recovery after OpenRefine restart) of the main project.
My current workaround is that I'll give the main project each time a new name at import.
  
tested with OpenRefine 2.7 and 2.8

**Comment by jackyq2015** [comment]
are you sure the project were removed? The project only will try to recovery if the project folder is there.

**Comment by zazi** [comment]
The project has been created after applying the mappings (JSON history) to the main project. After removal of the main project the project folder disappeared and the only things that has been left was the id of the main project in the workspace.json. Hence, the existence of this id causes (from my understanding) the creation of the (empty) project folder (after OpenRefine restart).

**Comment by tfmorris** [comment]
Refine deletes the project directory and immediately saves the workspace:

https://github.com/OpenRefine/OpenRefine/blob/6e66cb5144e1a621cfe1843a86b06f6bad9dcedd/main/src/com/google/refine/io/FileProjectManager.java#L325-L336

so it's difficult to see how this could happen unless it's unable to delete the project data directory for some reason (external tool with a file open it?).

@zazi Are you using the OpenRefine web interface? Can you provide the steps to reproduce this?

**Comment by WaltonG** [comment]
Steps to reproduce have been stated in [a comment](https://github.com/OpenRefine/OpenRefine/issues/3719#issuecomment-851678423) of a related issue #3719
