### ISSUE TITLE
Annoying switches between "Create project" and "Open project"

### ISSUE THREAD

**Issue by ettorerizza** [OpenRefine/OpenRefine#1437]
Open Refine opens on the "Create project" view, but switches automatically after one second to the "Open Project" window. It's pretty annoying and causes many unintentional project openings.

![screencast](https://user-images.githubusercontent.com/6286410/35211119-6466a25e-ff55-11e7-8d31-48fd271d5830.gif)

**Comment by thadguidry** [comment]
Does it happen in Firefox ?  Can you try to disable ALL Chrome extensions and try again ?

**Comment by ettorerizza** [comment]
@thadguidry Well done. It seems that it is related to the ADBlock+ extension  for Chrome. Thanks !
