### ISSUE TITLE
Concatenation of columns that contain null values (+ Google group statistics)

### ISSUE THREAD

**Issue by ettorerizza** [OpenRefine/OpenRefine#1439]
I created a [spreadsheet](https://docs.google.com/spreadsheets/d/18ojit-6LYyfJn5qHD_6igDk2lWSpNXWSbyrybjzO9b0/edit?usp=sharing) containing the list of topics on the Google group sorted by number of views. 

With 3884 views (the mean is 47 and the median 14), the question ["how to concatenate values of 2 or more columns into a new one?"](https://groups.google.com/forum/#!topic/openrefine/O6QF_KKaMw0) seems by far the most popular. Perhaps it should be taken into account when it comes time to create new functions or menu features.

**Comment by thadguidry** [comment]
@ettorerizza Does the new `coalesce()` function we provide now #1496 help here on this issue?

**Comment by wetneb** [comment]
I would say this is solved by #2110.
