### ISSUE TITLE
Custom Tabular Exporter no longer saves the state of Options for each Column

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#1446]
If you select column1 and change some options for it, then click on another column2 and change some options on it, then go back to column1, the Options dialog state is not saved.  Notice we actually have text above the Options section that states "Options for Column1" , "Options for Column2".

I don't know when this broke, but it was hinged around Reconciling I thought, but honestly cannot remember...so ?  @wetneb any idea ?

**Comment by wetneb** [comment]
@thadguidry I tried to reproduce this but everything seems to work correctly for me - the state of the options dialog is saved and restored when I go back to the column. Not sure how to debug that :-/

**Comment by thadguidry** [comment]
@wetneb hmm, for sanity's sake....can you try with OpenRefine 2.7 release as well on your end ?
