### ISSUE TITLE
Update OpenRefine logo

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1453]
- [ ] We should add the new logo to the UI
- [ ] And also to our README.md
- [ ] And finally our Website

**Comment by thadguidry** [comment]
And we need to work on the website refresh, well, at least attempt to "freshen it up" :)  This would be an awesome portfolio opportunity for some teenager somewhere in the world :)

**Comment by joanneong** [comment]
Although I am technically no longer a teen, I am interested in giving this issue a shot :P However, just to clarify, what do you mean by "the new logo"? I can only see this:

![image](https://user-images.githubusercontent.com/24493463/35820346-4c466402-0ae0-11e8-9833-d071930f6510.png)

which does not say "Google Refine" so I thought that it has already been updated. Has another logo been created for OpenRefine to replace this?

**Comment by thadguidry** [comment]
@joanneong Yes we have new logos designed for us by Google.  I'll email the package to you Joanne, check your email.

**Comment by magdmartin** [comment]
@thadguidry @joanneong I [created a new issue](https://github.com/OpenRefine/openrefine.github.com/issues/24) to refresh the website styling

**Comment by joanneong** [comment]
Can I get some directions on how to update the website? I can't seem to find the relevant files in the Git repository so I am not too sure how to proceed...

**Comment by magdmartin** [comment]
@joanneong this is a separate repo, see https://github.com/OpenRefine/openrefine.github.com

**Comment by tfmorris** [comment]
There's not much by way of explanation here and I can't find any related issues. What triggered the logo refresh? Simplification (ie less specularity)? Something else? Did Google just say "hey, we've got these new logos for you?"

**Comment by thadguidry** [comment]
@tfmorris Hi Tom.  Yes Google helped with a bit of rebranding, as part of a larger effort to help us where they could in addition to the sponsorship for that year 2018.  Additionally, we fully own and maintain the copyright on the artwork.  Martin or I can share some of the private emails with you if your want fine details. Let me know.

**Comment by tfmorris** [comment]
I can't imagine why the reason would be private. The previous new logo was the result of the re-branding effort #630. I think we should be transparent with the community unless there's a compelling reason to hide things, but whatever...

Can we at least get the source file(s) for the new logo committed to replace the .ai/.psd files that we had for the previous logos?

**Comment by thadguidry** [comment]
@tfmorris It's a whole zip file package of artwork, btw.  Hmm... did we push that into our repo?  That zip file?

**Comment by thadguidry** [comment]
@tfmorris I found the whole zip package.  and the email chain during the design process with the designer, Denis Radenkovic.  Here you go:  
[_OR_FINAL_LOGOS.zip](https://github.com/OpenRefine/OpenRefine/files/4730503/_OR_FINAL_LOGOS.zip)
