### ISSUE TITLE
localization/Filipino translation

### ISSUE THREAD

**Issue by jcpuzs1** [OpenRefine/OpenRefine#1464]
I want to contribute Filipino translation.

**Comment by magdmartin** [comment]
@jcpuzs1 thanks for offering your help. We use Weblate to manage translation. You can start a Filipino project [from here](https://hosted.weblate.org/projects/openrefine/translations/ ) - see `start new translation` at the bottom.

You can register to Weblate using your Github account

**Comment by jcpuzs1** [comment]
Sir thank you. What I wanted to do is that I want to translate and request a pull request from you sir and present it to utopian.io

**Comment by wetneb** [comment]
@jcpuzs1 sure, you can do that! and we would be very grateful.
You can either do the pull request yourself, or you can use Weblate as pointed out above by Martin. I recommend the latter, as it is much easier. If you use your github account to sign up for weblate, you will get exactly the same result (a commit attributed to your account in a PR on this repo).

Let us know if anything is unclear.

**Comment by jcpuzs1** [comment]
@wetneb thank you sir now I get it. Great help.

**Comment by jcpuzs1** [comment]
Sir good eve, sorry to bother you but I don't know how to pull request again. I want to pull request the 100% of my English to Filipino translation. I promised to finished it and here it goes. But my problem is I cant do pull request. Do u have guides of which I can follow ? Thank you sir

**Comment by magdmartin** [comment]
@jcpuzs1 Weblate submits automatically the Pull Request. Your work is available in #1479

**Comment by jcpuzs1** [comment]
Wow, thank you sir God bless.

**Comment by jcpuzs1** [comment]
Sir Good day, Since I finished translation in English. Can I also translate it to my dialect? which iis Cebuano?

**Comment by wetneb** [comment]
@jcpuzs1 sure - please only use weblate, do not file a PR yourself.
