### ISSUE TITLE
Research Apache Beam and Google Dataflow.

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#1468]
To support working with Bigger Data in OpenRefine we can collect ideas, questions, concerns on implementing batch processing in the cloud, we can can collect our research into a design document shared with the world here:

https://docs.google.com/document/d/1WT8nCYdNUU14y39IJJlB9fqnxhO0XZnjgHZljEdw-60/edit?usp=sharing 

We can then add Tasks with issues against each here:
- [ ] Some task with some issue #0000
- [ ] Another task with some issue #0000

**Comment by wetneb** [comment]
Let's close this as a duplicate of #1433 where the discussion is happening, I'll add the link to the design document there.
