### ISSUE TITLE
Requesting for translation to Filipino

### ISSUE THREAD

**Issue by Cyyy1998** [OpenRefine/OpenRefine#1470]
Good day sir,

I want to transtate it to my native language which is tagalog/Filipino

**Comment by magdmartin** [comment]
@Cyyy1998 please see the discussion with @jcpuzs1 in #1464  for the Filipino translation. 
Happy to see you participate.

**Comment by Cyyy1998** [comment]
Or can I translate it to Cebuano dialect ?
