### ISSUE TITLE
Translation into Spanish language

### ISSUE THREAD

**Issue by michaelizer** [OpenRefine/OpenRefine#1471]
Greetings, I would like to contribute to the project by translating it into Spanish. Spanish is my native language so don't panic, but a lot of Spanish speakers are still limited by the language so this is primarily to help them. At Utopian we love contributing to open source projects.

Thanks in advance and for your time. Keep up the great work.

**Comment by thadguidry** [comment]
@michaelizer We already have OpenRefine translated in Spanish, but you can review and possibly provide better translations or missing ones by visiting our [Translate OpenRefine wiki page](https://github.com/OpenRefine/OpenRefine/wiki/Translate-OpenRefine)
