### ISSUE TITLE
Add function Concatenate with...

### ISSUE THREAD

**Issue by magdmartin** [OpenRefine/OpenRefine#1473]
Add function `Concatenate with...` in each column drop-down menu. The new menu will display a modal windows listing all available column to concatenate with

Request from [mailing list](https://groups.google.com/d/msg/openrefine-dev/2vBmQNEBHW8/GIyVef6JAQAJ)

**Comment by ettorerizza** [comment]
Related to #1439 and #239

**Comment by wetneb** [comment]
Closed by #2110.
