### ISSUE TITLE
Translation to Spanish (question)

### ISSUE THREAD

**Issue by vacilagodzila** [OpenRefine/OpenRefine#1474]
Hi there, I was surfing through Github and ended up on your repo. Just wondering if I could contribute with spanish translations, if they're needed I'd be glad to help. Thank you!

**Comment by magdmartin** [comment]
We already have a Spanish translation in progress via Weblate. You can check it [on Weblate](https://hosted.weblate.org/languages/es/openrefine/) or in [OpenRefine repo](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/langs/translation-es.json). 
Looking forward your pull request.
