### ISSUE TITLE
Add Base-64 encoding/decoding to GREL

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#148]
_Original author: stefa...@google.com (September 30, 2010 15:41:25)_

Would be nice to be able to perform base64 encoding/decoding directly in GREL

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=148_

**Comment by tfmorris** [comment]
Rather than implementing this as it's own function, it might be a good idea to introduce a pair of `encode()` / `decode()` functions which take an algorithm as an argument. e.g. `"foo".encode("base64")`

**Comment by thadguidry** [comment]
@tfmorris Totally agree.  I can envision how that proposed pair of `encode()` / `decode()` functions would be similar in syntax with how we did the `escape()` / `unescape` functions.
