### ISSUE TITLE
Localization/Translation

### ISSUE THREAD

**Issue by vinzruzell** [OpenRefine/OpenRefine#1485]
REQUESTING to contribute FILIPINO/TAGALOG translation and CEBUANO translation.

**Comment by ostephens** [comment]
Hi @vinzruzell - you can contribute to existing translations and create new translations through a service called Weblate. Got to https://hosted.weblate.org/engage/openrefine/ and follow the instructions.

There is already a Filipino translation which you could review, or you can start a new translation for Cebuano etc

Thanks very much

**Comment by vinzruzell** [comment]
HI. I have already completed the file. I would like to ask  if there is another that needs translation for filipino and tagalog?
