### ISSUE TITLE
Implement "Facet by null" Command and add to Customised Facets menu

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1486]
From #820 

A "Facet by null" function would create a facet with the values 'true' (the cell value is null) and 'false' (the cell value is not null). It would work similarly to the existing 'Facet by Blank' option, but would only include cells containing a value of 'null', not those containing empty strings

**Comment by joanneong** [comment]
I will work on this this weekend and get a PR up by next week :)

**Comment by ostephens** [comment]
Thanks @joanneong - would you be able to look at doing #1487 at the same time? They should be pretty similar

**Comment by ostephens** [comment]
Hi @joanneong did you make any progress with this?

**Comment by joanneong** [comment]
My apologies for the long period of inactivity, @ostephens - had examinations over this period. I will get a PR up and running by this Sunday.

**Comment by ostephens** [comment]
No problem at all @joanneong - we are always very grateful for any time people can spare to contribute! (I've done barely anything over the last month but just got a few hours last night and was reviewing stuff, that was the only reason I asked)

**Comment by ostephens** [comment]
With #1500 you can see I tried to put in translations where I could. I don't entirely trust Google translate for the OpenRefine interface because there are so many ambiguities (e.g. 'row', 'cell', 'blank' all have multiple meanings in English) - so I used a combination of existing translations and Google translate.

Ideally we could just implement the English and rely on the i8n library falling back on English where no specific translation is supplied. Unfortunately the current  i8n library we use doesn't support fall back options, so not having translations in place can lead to problems (#1350 #1455) but the solution to this is to replace the i8n library (see #1285)
