### ISSUE TITLE
Does anyone need findAll() at all?

### ISSUE THREAD

**Issue by isaomatsunami** [OpenRefine/OpenRefine#1490]
As discussed at #1296, does anyone want findAll(regx)?
I can do it with Python. I do. But Isn't findAll a missing piece in GREL?

ex1) value.findAll(\[\d]+\)[3]
ex2) value.findAll(\[\d]+\).join("/")   // after this, apply "split multi-valued cell"

Isn't this a natural, usual way that beginners would expect.

**Comment by ettorerizza** [comment]
What's wrong with the brand new [`find() `function](https://github.com/OpenRefine/OpenRefine/wiki/GREL-String-Functions#new--findstring-s-regexp-p) implemented in the development version ?
