### ISSUE TITLE
project files

### ISSUE THREAD

**Issue by adambako** [OpenRefine/OpenRefine#1538]
OpenRefine 2.8 (1)
osx 10.13.3
rome Version 65.0.3325.162

hi.

i just need help but i cant find the place where to ask..
im using openrefine on osx. but i was need to reinstall my mac. so what i did was copy the whole hdd to backup.. i forgot to export openrefine projects.
now im on clean installation but im not able to find where the projects files are stored.. 
i found this paths: https://github.com/OpenRefine/OpenRefine/wiki/Installing-Extensions
but there is NO /openrefine or google/refine folders in my backup...
also i checked this paths in my actual installation folders and also, there are no folders for openrefine..
i got also shows hidden files..

so. where i can find the projects files on mac?
thx

**Comment by ettorerizza** [comment]
@adambako I think the folder should be in Users > YourUserName > Library > Application support > OpenRefine

**Comment by adambako** [comment]
thanks a lot for your fast answer.. 
files are there :) 👍
