### ISSUE TITLE
Partition operation does not consider Zero-Length assertion situation

### ISSUE THREAD

**Issue by quan17** [OpenRefine/OpenRefine#1550]
Version 2.8
MacOS, Safari

Create one column with data: abc, abb, abce, abe, abed
Transform on one column with GREL,  `partition(value,/(?<=e)/)`, 

**Current Results:**

<img width="446" alt="screen shot 2018-03-23 at 4 45 00 pm" src="https://user-images.githubusercontent.com/10971020/37852598-9ea49b0e-2eb9-11e8-9c0c-8845039cdca1.png">

 **Expected Results:**

The first row( the regex not match any context) should return null instead of "" (empty String),
otherwise, it can not tell the difference with the row 3,4,5, which have regex match.

This issue also make the smartSplit operation has wrong result:
<img width="577" alt="screen shot 2018-03-23 at 4 48 48 pm" src="https://user-images.githubusercontent.com/10971020/37852731-169a5432-2eba-11e8-82f4-c297f4d4d5d8.png">

please look the row 5, expected results should be [ abe, d ]

Thank you.

**Comment by ettorerizza** [comment]
Hi @quan17 . I understand what you mean, but it would be very dangerous to change the `partition ` behavior (if only for reasons of backward compatibility). In a case like yours - still very specific - it might be better to make a GREL formula that triggers an error if the pattern is missing from the string. For example :

`if(length(value.find(/(?<=e)/)[0]) + 1 > 0, value.partition(/(?<=e)/), null)`

You can then play with the options to decide what to do in case of an error.

![screenshot-127 0 0 1-3333-2018 03 23-23-59-21](https://user-images.githubusercontent.com/6286410/37856957-b0641390-2ef7-11e8-9d49-1cc579e627c2.png)

Note: The `find ` function I used only exists in the development version, it will be officially implemented in Open Refine 2.9.

**Comment by quan17** [comment]
@ettorerizza Thank you. 
From the API page, I guess the new `find` operation can help but I never test it. Since I am also afraid to update the Open Refine to 2.9 version, since we are developing based on 2.6 version. Is that possible to only get the new `find` function rather than upgrading the whole package? If I directly change the `partition` function return value form "" to `null`, based on your experience, will there more issues come out?
I totally understand the reason you don't want to change `partition` here, however I believe another parameters can help us in this case.
The case I have is to distinguish the regex part has been matched or not, so `split` may not give me the result as expected.

**Comment by ostephens** [comment]
@quan17 the 'find' function is quite discrete so you could add it into OpenRefine 2.6 if you wanted. See this PR for the files that were added/changed to add the new 'find' function https://github.com/OpenRefine/OpenRefine/pull/1432/files

**Comment by quan17** [comment]
@ettorerizza Thank you.

**Comment by thadguidry** [comment]
@quan17 `partition()` is not about regex matching, nor is it intended for Zero-length assertions, but instead can use a pattern to partition against.  Your assuming to much with the `partition()` function.  If there's a no match, then nothing is returned (in this case an empty), and that's what we want.

IF you need to see the differences between rows 3,4,5 ... then use our correct function... `match()`.
