### ISSUE TITLE
Adding Prefix Issue

### ISSUE THREAD

**Issue by Gautamshahi** [OpenRefine/OpenRefine#1572]
I am getting the below error, even with 2.8 version.

![image](https://user-images.githubusercontent.com/3966230/39047187-92560550-44b6-11e8-954a-9581a7e4ecdf.png)

**Comment by wetneb** [comment]
Hi @Gautamshahi, this issue is specific to the RDF extension, which is not maintained by our team. As far as I am aware nobody maintains it at the moment.

**Comment by Gautamshahi** [comment]
Thank you.
