### ISSUE TITLE
Translation via Weblate

### ISSUE THREAD

**Issue by joniarroba** [OpenRefine/OpenRefine#1575]
Currently using OpenRefine 2.8

The translation of Openrefine into Portuguese is done at weblate. My question the translation will be available within the default package? Many students in Brazil would benefit from it, meanwhile I am searching for workarounds. 

#### Current Results:

Portuguese language does not show up.

#### Expected Results:

Portuguese language available to select.

**Comment by wetneb** [comment]
Hi @joniarroba, thanks for this report. The Portuguese translation will be available in the next version of OpenRefine, which should arrive soon-ish. It will look like this:
![image](https://user-images.githubusercontent.com/309908/39092531-2b0e2732-4610-11e8-9ebd-bb1dc1733ff5.png)

**Comment by joniarroba** [comment]
Thanks for your prompt response! Looking forward to see it! For now we added manually the JSON file.
