### ISSUE TITLE
Reconciliation Issue

### ISSUE THREAD

**Issue by Gautamshahi** [OpenRefine/OpenRefine#1587]
Hi,

I am trying to reconcile with Geoname , DBPedia etc. I think there is an issue with the SPARQL Endpoint. I tried with both OpenRefine 2.5 or 2.8.

Can you suggest the possible options to reconcile?

Regards.

**Comment by wetneb** [comment]
Hi @Gautamshahi, reconciling via SPARQL endpoints is a feature that is added by the RDF extension, which is not maintained by our team.
