### ISSUE TITLE
Unable to follow FAQ tutorial to allocate more memory for Mac

### ISSUE THREAD

**Issue by griii2** [OpenRefine/OpenRefine#1589]
When reporting a bug please provide the following information to help reproduce the bug:

#### Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
OpenRefine2.8

#### Operating Systems and version:
macOS 10.12.3

#### Browser + version used - Please note that OpenRefine doesn't support Internet Explorer but works OK in most cases:
Chrome

#### Steps followed to create the issue:
Follow the FAQ to allocate more memory for Machttps://github.com/OpenRefine/OpenRefine/wiki/FAQ%3A-Allocate-More-Memory

#### If you are allowed and are OK with making your data public, it would be awesome if you can include the data causing the issue or a URL pointing to where the data is (if your concerned about keeping your data private, ping us on our mailing list):
<img width="650" alt="screen shot 2018-04-30 at 17 16 09" src="https://user-images.githubusercontent.com/2312983/39435280-3f7d94b4-4c9b-11e8-91b9-84da60f13ada.png">

#### Current Results:
there is not "java" section, no "VMOptions", no "${java.options}". See the screenshot obove.

#### Expected Results:
from the FAQ:
expand the "java" section at the bottom
double click on the "VMOptions" content (the right end side)
change "${java.options}" with "-Xms256M -Xmx1024M"

**Comment by thadguidry** [comment]
Thanks for this David!  Do you care to update our Wiki FAQ ?  I'll give you write access to fix this up and then let us know in this issue and we'll close it out.

**Comment by thadguidry** [comment]
@griii2 Actually, you should already have EDIT rights for our Wiki.  Look for the Edit button in the top right corner of any Wiki page.

**Comment by griii2** [comment]
Hi Thad, there is a misunderstanding, I have no idea how to allocate more memory - I was unable to follow the FAQ and I don't know what to do.

**Comment by ettorerizza** [comment]
The tutorial is probably a bit outdated. Simply change “-Xmx1024M” into something else, eg “-Xmx2048M” or “-Xmx8G”.

**Comment by thadguidry** [comment]
@griii2 if you have further problems just let us know on our mailing list.
