### ISSUE TITLE
Cancel button doesn't work in reconciliation process

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#159]
_Original author: raymond....@gmail.com (October 17, 2010 13:46:43)_

In version 1586 (on Chrome 6.0.472.63 in OS X 10.6.4), after I reconcile a column and try to rematch a single item, the Cancel button doesn't work forcing me to either match against one of the items on the menu or to create a new topic.  You can create a simple example such as the attached spreadsheet in which I reconciled against composers. The last item (WWagner) won't match automatically because I put in a spelling mistake; you will be able to see how hitting Cancel will not work.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=159_
##

**Comment by wetneb** [comment]
Closing as non-reproducible, this works fine in the current version as far as I can tell.
