### ISSUE TITLE
Issue with Reconcilation

### ISSUE THREAD

**Issue by Gautamshahi** [OpenRefine/OpenRefine#1590]
Hi,
I am trying to reconcile my data but I am getting the issue with the SPARQL Endpoint, then I tried with the RDF Dump file then also I am getting the Issue, for a continuous long time its showing working.

Can you please suggest the other option?

If not, please suggest some other tool/way reconcile the data.

Regards,

**Comment by wetneb** [comment]
Hi @Gautamshahi, reconciliation via SPARQL endpoints is a feature of the RDF extension, not OpenRefine itself. This extension is not maintained by our team. The most up to date fork is https://github.com/stkenny/grefine-rdf-extension, you can try this version and submit your issues there.
