### ISSUE TITLE
Concatenating 'null' to a string with '+' results in null

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1595]
When reporting a bug please provide the following information to help reproduce the bug:

#### Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
OpenRefine 2.8

#### Steps followed to create the issue:
In an expression editor type the grel:
`"string" + null`

#### Current Results:
Output is

`null`
#### Expected Results:
All other types (dates, numbers, booleans) are converted to strings in the case of use with the '+' sign:
```
"string" + 1 -> string1 (or string1.0)
"string" + true -> stringtrue
"string" + [date 2018-01-01T00:00:00Z] -> stringMon Jan 01 00:00:00 EST 2018
```

In each case this is equivalent to converting the type to a string using the 'toString()' function.  That is:
`"string" + 1 -> "string" + toString(1) -> string1`

on this basis the correct result for `"string" + null` is the same as `"string" + toString(null)` which is `stringnull` i.e. the null converts to the string "null"

**Comment by ostephens** [comment]
This behaviour is controlled in /main/src/com/google/refine/grel/ast/OperatorCallExpr.java in the evaluate method

**Comment by ostephens** [comment]
Updated to correct the expected behaviour as I had previously mis-represented the outcome of `toString(null)`

**Comment by ostephens** [comment]
Note that @thadguidry describes this behaviour as correct in #820

**Comment by thadguidry** [comment]
@ostephens Thad describes it as The Most Preferred Behavior By The Majority Our Users :)

**Comment by ostephens** [comment]
OK - closing this then as it is preferred behaviour

**Comment by tfmorris** [comment]
I find it hard to believe that the majority of users think that the described behavior is "most preferred." 

The most logical results, to my mind, are:

1. `"string" + null == "string"`
2. `"string" + null` => error

What advantage do "The Majority of Our Users" find to `"string" + null == null`?

**Comment by thadguidry** [comment]
@tfmorris Tom, sorry, I should have been more clear.
Context is king, so let's agree there are 2 contexts here being discussed previously that we didn't perhaps make more clear:
- `+` as an arithmetic Addition operator
- `+` as a unary operator (allowed currently in our code for concatenation of a few Types)

I am restating the following to be more clear, in regards to using the unary operator for String concatenation needs:
- It's useful for users to have a "smart default" for frictionless String appending or concatenation of column values that might contain `null`.
- It's useful for **some** more technical users to have that "smart default" be allowed to modify more easily within a GREL statement where any `null` found in an argument can be replaced by their choosing.  I don't currently think we have this available to users, but happy to know if it can be done currently in version 3.4.

**Comment by ostephens** [comment]
>It's useful for users to have a "smart default" for frictionless String appending or concatenation of column values that might contain null.

My reasoning when I raised this issue initially is that this "smart default" should be that
"string" + `null`
and
"string" + `null`.toString()

would give the same result. I still believe this would be the best outcome, and still believe that the best "smart default" behaviour is to convert `null` to an empty string in both scenarios. I haven't gathered a body of evidence for this so it's based on my own experience and questions I've seen on the mailing list over time.

>It's useful for some more technical users to have that "smart default" be allowed to modify more easily within a GREL statement where any null found in an argument can be replaced by their choosing.
I feel that we support this through various methods that more technical users can happily use including `coalesce()` and `if` in combination with `isNull`

Thad - to be extra clear, what do you believe should be the outcome of 

"string" + `null`

**Comment by thadguidry** [comment]
@ostephens The "smart default" should be:
"string" + `null` == "string"
David and I had this conversation years ago.
I just always felt we also needed extra `null` handling controls separate from "" empty string, but it didn't get added into GREL at the time.  Which we offer more granular control now, thanks to all of you.
