### ISSUE TITLE
Directly use column as reconciliation results

### ISSUE THREAD

**Issue by lucaswerkmeister** [OpenRefine/OpenRefine#1596]
I have not been able to find a way to directly use a column as reconciliation results. In the case of Wikidata, reconciling a column of item IDs works (I assume it’s just due to the fact that `wbsearchentities` supports searching for the item ID), but it takes an unnecessarily long time.

This would be very useful for a kind of workflow where I don’t want to work with the dataset in OpenRefine all the time as one monolithic project, but rather prefer to use plain old text files and associated Unix tools (`cut`, `join`, `awk`, …) as much as possible, and exchange parts of the data with OpenRefine as needed – see https://github.com/lucaswerkmeister/bundestag/ for example (most of the details are in the commit messages).

**Comment by thadguidry** [comment]
@lucaswerkmeister are you trying to figure out how to import your data into an OpenRefine project and limit by a certain number of rows ? or limit by only a few columns ?

One trick to do systematic subsetting of the data set is to create a
custom text facet on any column with this expression

     mod(row.index, 10)

Then select one facet choice at a time.

It is hard to figure out exactly what it is your having difficulty with.  Reconciling produces a result...that is called a match.  You can create new additional columns with anything from a Recon.  [See our Variables doc about the recon object](https://github.com/OpenRefine/OpenRefine/wiki/Variables#recon) 

Does any of the above help you ?

**Comment by lucaswerkmeister** [comment]
Sorry, that doesn’t really help me, there’s some big misunderstanding between us – I’m definitely not interested in limiting anything :)

Say I have a data file like this:
```
Bundestag ID	Wikidata ID	date of birth	place of birth	date of death
11000001	Q109221	20.10.1930	Stuttgart	17.01.2008
11000002	Q214251	09.04.1909	Siegen	02.12.1991
11000003	Q566240	26.05.1913	Parabutsch	18.02.1994
11000004	Q109322	06.11.1933	Berlin	
11000005	Q96630	09.06.1950	Teterow, Kr. Teterow, Bezirk Neubrandenburg	
11000007	Q2171984	10.11.1919	Masburg / Kreis Cochem	25.05.2013
11000008	Q1500263	28.09.1912	Düsseldorf	25.01.1992
11000009	Q2492	05.01.1876	Köln	19.04.1967
11000010	Q916089	22.06.1944	Drangstedt / Krs. Wesermünde	25.10.2004
11000011	Q1287863	31.10.1920	München	28.12.2000
…
```
I want to import it into OpenRefine and use column 2 as Wikidata IDs directly, without going through the lengthy reconciliation process. I suppose this could also be phrased as “set the match for each cell based on an expression”, where in my case the expression would simply be `value`. Does that make more sense?

**Comment by jackyq2015** [comment]
Not sure that can be done directly or not. 
If not,  you might need "edit column"->"add column by fetching URL" if you have have the wikidata Id:
"https://www.wikidata.org/wiki/" + value. Then you need to parse the result using:
https://github.com/OpenRefine/OpenRefine/wiki/StrippingHTML

**Comment by ostephens** [comment]
I think what you'd need to be able to do for this to work is to essentially be able to set the:

- identifierSpace to the correct URL for the service from which the IDs are derived (e.g. https://wikidata.org/wiki/)
- cell.recon.match.id

for each cell containing an identifier. The only way of doing this at the moment is via the Reconciliation process afaik.

I suspect the issues in terms of adding such a function is that allowing you to set this directly avoids the check that the ID in your cell actually does exist on the remote service - which means you'd then have potential errors generated if you tried to push updates or pull down more information.

I'd be interested to have @wetneb's opinion but just converting the cell content to a match without checking the service feels wrong to me. I feel it would be better for us to try to find a way of speeding up the reconciliation process where you already have the IDs - even with the need to check the remote service it feels like it should be quicker to check 'does this ID exist'.

Just my initial thoughts

**Comment by thadguidry** [comment]
@ostephens is correct.  The right way to do it is not skip the reconciling.  And instead just speed up the reconciling.  One way this was done in the past was that with Freebase service (prior to Wikidata), you could tell Freebase that you in fact had MID identifiers already in a column...then Freebase would use a much faster index lookup that OpenRefine could send over 1000 MID lookups in a batch request and return all the matches in about 10 seconds.

**Comment by wetneb** [comment]
The main reason why it is hard to get rid of calls to the service is that we currently need to fetch both the labels and the types for each item. We could in principle have an operation that blindly reconciles the cells without any calls, using the ids as labels and without adding any types, but it would be a sort of poor-man's reconciliation…

As for the speed: the Wikidata service should not do any search API call when you reconcile a column of Qids: it only needs to fetch the labels and types (which it does by getting the full JSON of all items in each batch). So it should be significantly faster than reconciling free text. Any improvements there are welcome though.

**Comment by thadguidry** [comment]
@wetneb Lucas just replied to my question on the wikidata-tech mailing list about fastest query to verify a QID...

"If you have the luxury of access to the replica servers (which is the
case for the reconciliation service, right?), then I doubt any API is
going to beat a raw SQL query:

$ sql wikidata 'SELECT page_title FROM page WHERE page_namespace = 0 AND
page_title IN ("Q12345", "Q123456", "Q1234567")'
+------------+
| page_title |
+------------+
| Q12345     |
| Q123456    |
+------------+

This shows that Q1234567 doesn’t exist. (Someone with more SQL knowledge
could probably turn that into a “yes/no” kind of reply, too.)

Cheers,
Lucas
"

**Comment by wetneb** [comment]
After working with a big dataset I have come to agree with @lucaswerkmeister that it is quite frustrating to have to wait for Qids to be reconciled. I think we should give maximum control to users and provide this operation, with the appropriate caveats that no checks for validity are done. (But anyway, it is also possible for reconciliation results to get out of sync with the reality online, so the rest of our code should not assume that the Qids always remain valid.)
