### ISSUE TITLE
Russian language file contains duplicate keys

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1599]
When reporting a bug please provide the following information to help reproduce the bug:

#### Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
Current build from master 

#### Current Results:
translation-ru.json has 25 duplicate JSON keys:

      "log-length-facet":"Логарифмический фасет по длине текста",
      "copy-val":"скопировать значение исходной колонки",
      "warning-col-name":"Нужно ввести наименование колонки.",
      "add-col-recon-col":"Добавить колонки из сверенной колонки",
      "configure-prop":"настроить",
      "add-col-recon-val":"Добавить колонки из значений сверки",
      "word-facet":"Фасет по словам",
      "duplicates-facet":"Фасет дубликатов",
      "remove-prop":"удалить",
      "cache-responses":"Кешировать ответы",
      "new-col-name":"Наименование новой колонки",
      "unicode-facet":"Фасет по уникоду символов",
      "configure-col":"Настроить эту колонку",
      "add-col-col":"Добавить колонку основываясь на текущей",
      "no-settings":"У этого свойства настройки недоступны.",
      "extend-not-reconciled":"Эта операция доступна только для сверенных колонок.",
      "custom-facets":"Другие фасеты",
      "store-err":"сохранить ошибку",
      "facet-error":"Фасет по ошибкам",
      "on-error":"В случае ошибки",
      "text-filter":"Текстовый фильтр",
      "warning-no-property":"Пожалуйста, сначала выберите свойство.",
      "text-length-facet":"Фасет по длине текста",
      "set-blank":"оставить пустым",
      "numeric-log-facet":"Логарифмический числовой фасет",

#### Expected Results:
Each key should appear in the JSON file once

**Comment by thadguidry** [comment]
Tested as fixed !  Thanks Owen !
