### ISSUE TITLE
GREL Cell Cross - Error: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by mungewell** [OpenRefine/OpenRefine#1603]
When reporting a bug please provide the following information to help reproduce the bug:

#### Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
Version 2.8 [TRUNK]

#### Operating Systems and version:
Windows7

#### Browser + version used - Please note that OpenRefine doesn't support Internet Explorer but works OK in most cases:
Chrome

#### Steps followed to create the issue:
Import XLS data into two different projects attempting to 'make new column based on current' with cross reference to another project
`cell.cross("lango_20180515 xlsx","Lango SN").length()`

Note: data is automatically recognized as a number (shows as green) and appears with the 'x.xxxxExx' notation within a text facet.

#### Current Results:
GREF reports an error:
` Error: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String`

#### Expected Results:
I expect numbers to be compared and cross reference, in the specifc GREL command I would expect an count of how many times the number is located in the other project.

![cell_cross_error](https://user-images.githubusercontent.com/236907/40078655-777b8f4e-5842-11e8-984e-a98ec515baa5.png)

**Comment by jackyq2015** [comment]
why you need cross function instead of just use the column in the same project?

Also, could you please paste the exception from the back end?

**Comment by mungewell** [comment]
I am attempting to validate/cleanup data provided by a 3rd party. The data is from 2 sheets of a XLS which I have imported as separate projects, they have already (poorly) cross referenced it.

Not sure where I might find the 'backend' info, didn't see any log files under:
`C:\Users\swood\AppData\Roaming\OpenRefine`

**Comment by jackyq2015** [comment]
You should be able to see the console for it. it is not in the log.
