### ISSUE TITLE
Support for Java versions > 9

### ISSUE THREAD

**Issue by martinjrobins** [OpenRefine/OpenRefine#1604]
Hi, it doesn't seem like OpenRefine2.8 currently supports Java versions greater than 9, can this be fixed to allow newer Java versions? 

I notice that https://github.com/OpenRefine/OpenRefine/blob/master/refine#L843 only allows versions 6-9, but not greater than this. Adding a 10 onto this list worked OK for me

#### Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):

OpenRefine2.8

#### Operating Systems and version:
Ubuntu 18.04

#### Browser + version used - Please note that OpenRefine doesn't support Internet Explorer but works OK in most cases:

Google Chrome version 66.0.3359.139 

#### Steps followed to create the issue:

```
$ ./refine
```

#### Current Results:

Error: OpenRefine requires Java version 6 or later. If you have multiple versions of Java installed, please set the environment variable JAVA_HOME to the correct version.

#### Expected Results:

OpenRefine to start-up

**Comment by wetneb** [comment]
Indeed this constraints needs updating as we no longer support Java 7 or older. Would you consider making a pull request for that?

**Comment by martinjrobins** [comment]
Can do, created a pull request here #1605
