### ISSUE TITLE
Using 'double tick' on reconciled cell to "create a new item for this cell and all identical cells" results in empty identifierSpace 

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1607]
When reporting a bug please provide the following information to help reproduce the bug:

#### Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
OR 2.7, OR 2.8 and build from current master

#### Operating Systems and version:
MacOS High Sierra

#### Browser + version used - Please note that OpenRefine doesn't support Internet Explorer but works OK in most cases:
Safari 11.1

#### Steps followed to create the issue:
Try to reconcile a column, when a set of candidates have been found for a cell, click the double tick mark next to the option to "Create new topic"

#### Current Results:
The cell.recon.identifierSpace value (which is set by the reconciliation process) becomes unset or empty.
It is then not possible to (e.g.) use that cell to create a new item in Wikidata

See before/after screenshot with a custom text fact showing the cell.recon.identifierSpace

<img width="714" alt="screen shot 2018-05-17 at 13 27 46" src="https://user-images.githubusercontent.com/576174/40177611-086c4012-59d7-11e8-90c7-7c40639d7ef9.png">

<img width="537" alt="screen shot 2018-05-17 at 13 27 52" src="https://user-images.githubusercontent.com/576174/40177630-0dfe4e58-59d7-11e8-9556-07c5ea00d208.png">

#### Expected Results:
The identifierSpace should stay as it is set
This problem only occurs when using the Double Tick to create new items. If the single tick is used, or if double or single ticks are used to match to a proposed item from the reconciliation service the identifierSpace stays set as expected

**Comment by ostephens** [comment]
This problem also occurs when choosing Reconcile->Actions->Create one new item for similar cells

**Comment by ostephens** [comment]
This problem also occurs when using the option to:

"Search for match"
In the pop-up Selecting "Match other cells with same content" 
Clicking 'New item' button

**Comment by ostephens** [comment]
I think this is essentially any time "recon-judge-similar-cells" is called with parameter shareNewTopics: true

**Comment by wetneb** [comment]
Okay so there was probably a problem with my #1568, let me investigate.

**Comment by wetneb** [comment]
@ostephens I cannot reproduce this. Based on your first screenshot above, it looks like you have not used the Wikidata reconciliation service, but another one (maybe VIAF?). So that would explain why you cannot create new Wikidata items based on these reconciled cells.

**Comment by ostephens** [comment]
Hmm - I think I may have tested on a version without your #1568 fix in place - at least I've double checked I'm working from the most up-to-date version of Master and now I'm not seeing the issue.

Sorry
