### ISSUE TITLE
Error when trying to change workspace via -d terminal command

### ISSUE THREAD

**Issue by DFoltzMorrison** [OpenRefine/OpenRefine#1623]
#### Browser: Chromium 66.0.3359.139

I am trying to switch between different workspaces [as listed in the FAQ](https://github.com/OpenRefine/OpenRefine/wiki/FAQ).

I've made a copy of the exact contents of my current workspace into a folder ('/workspace a') on another drive, as well as copies of two other workspaces from different machines into folders ('/workspace b' and '/workspace c').

Using the terminal commands `./refine -d '/path/to/workspace a/'` and 
`./refine -p 3333 -i 0.0.0.0 -m 14000M -d '/path/to/workspace a/'`

results in the following error:

```
Starting OpenRefine at 'http://127.0.0.1:3333/'

Error: Could not find or load main class 00.openrefine

**Comment by jackyq2015** [comment]
you need to remove the space in the path.

**Comment by DFoltzMorrison** [comment]
I can rename the workspace directory to remove the space, but the drive name has a space in it:
 `/media/USER/HDD 00/openrefine_workspaces/`.

Removing the space in the drive name allows openrefine to launch in my browser and displays the following:

```
HTTP ERROR 503

Problem accessing /. Reason:

    java.lang.NullPointerException

Caused by:

javax.servlet.UnavailableException: java.lang.NullPointerException
	at org.mortbay.jetty.servlet.ServletHolder.makeUnavailable(ServletHolder.java:415)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:458)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:296)
	at com.google.refine.RefineServer.init(Refine.java:208)
	at com.google.refine.Refine.init(Refine.java:114)
	at com.google.refine.Refine.main(Refine.java:108)

Powered by Jetty://
```

**Comment by DFoltzMorrison** [comment]
I renamed the workspace directory to remove the space, and had to change the parent drive's label in a partition editor to remove another space.

I can successfully switch between workspaces, but now have the job of fixing a lot of broken file paths.

Perhaps a future version of openrefine can support file paths with spaces wrapped with quotes?

**Comment by jackyq2015** [comment]
@DFoltzMorrison  Glad it works eventually. sorry for the inconvenience. Will add into next milestone.
