### ISSUE TITLE
Quotes not shown when unchecking Quote option on CSV/TSV importer

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#1626]
#### Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
3.0 Beta

#### Operating Systems and version:
Windows 10

#### Browser + version used - Please note that OpenRefine doesn't support Internet Explorer but works OK in most cases:
Firefox Latest

#### Steps followed to create the issue:
1. Import dataset using clipboard
```
thad,test,good,"not so much","ok very good"
nothing,more,to,see,here
```
3. uncheck _Use character " to enclose cells containing column separators._

#### Current Results:
Error in Browser Web Console
```
XML Parsing Error: not well-formed
Location: http://127.0.0.1:3333/command/core/importing-controller?controller=core%2Fdefault-importing-controller&jobID=3&subCommand=update-format-and-options
Line Number 1, Column 1:
```
When I tried to view detail of the error this was thrown in OpenRefine console for some reason:

11:52:52.306 [          org.mortbay.log] /command/core/importing-controller (0ms)
java.lang.IllegalArgumentException: parameter 's' should not be null
        at com.google.refine.util.ParsingUtilities.evaluateJsonStringToObject(ParsingUtilities.java:123)
        at com.google.refine.importing.DefaultImportingController.doUpdateFormatAndOptions(DefaultImportingController.java:180)
        at com.google.refine.importing.DefaultImportingController.doPost(DefaultImportingController.java:93)
        at com.google.refine.commands.importing.ImportingControllerCommand.doGet(ImportingControllerCommand.java:74)
        at com.google.refine.RefineServlet.service(RefineServlet.java:171)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)

#### Expected Results:
Shows quotes around columns 4 and 5 when unchecked, and removes quotes when checked

**Comment by ostephens** [comment]
The "XML Parsing Error: not well formed" looks like it might be FF specific and not related to the specific import/option here. As soon as I try to do an import in FF (tested a couple of different methods) I get errors like:

XML Parsing Error: not well-formed Location: http://127.0.0.1:3333/command/core/get-importing-job-status?jobID=3 Line Number 1, Column 1:

It might be related to this s/o Q&A: https://stackoverflow.com/questions/7642202/xml-parsing-error-not-well-formed-in-firefox-but-good-in-chrome

**Comment by ostephens** [comment]
I can't recreate the console error right now - you say "When I tried to view detail of the error" - did you do something specific to try to view the detail? Just wondering what is happening to trigger that console error

**Comment by jackyq2015** [comment]
Tested on my machine, it is true that quotes do not appear when it is unchecked. But no exception found at back end. Linux 18.0.4, Java 8, Chrome.

**Comment by jackyq2015** [comment]
@thadguidry Maybe we had some false expectation on this switch. Seems it only define the field boundary, not a switch to enable/disable the show of the double quote.

You can try following data set and it will be clear:
```
c1,c2,c3,c4,comma
c1,c2,c3,44444444,"1,000"
c1,c2,c3,44444444,"hello, world"
```
In teams of how to import a double quote, a double double quotes will work:
```
c1,c2,c3,c4,comma
c1,c2,c3,44444444,""1,000 double double""
```

**Comment by thadguidry** [comment]
@jackyq2015 umm, how does a user tell OpenRefine to keep the single quotes and import them into each cell, for them to handle manually later on with GREL, Facets, etc.

I think, especially for CSV/TSV importer, an additional import option is needed, called "keep quotes during import".  The newer versions of OpenCSV library has support for many more options that we are not taking advantage of within CSVParser unfortunately.

I would advise you to look through the BLAME view (left side of this [view](https://github.com/OpenRefine/OpenRefine/blame/master/main/src/com/google/refine/importers/SeparatorBasedImporter.java#L157) of what David, Tom, others have added support for and where.

**Comment by thadguidry** [comment]
@jackyq2015 Sure.  Jackson also provides many options now https://github.com/FasterXML/jackson-dataformats-text/blob/master/csv/src/main/java/com/fasterxml/jackson/dataformat/csv/CsvParser.java#L27

**Comment by xbdeng** [comment]
I think this issue can be closed

**Comment by thadguidry** [comment]
Yes this was an initial relapse of my memory with Line-based importer in actuality and not the CSV/TSV/separator-based importer.  The Line-based importer does allow users to import as lines and keep all forms of quotes within the long string of each row importer since it imports lines and does no parsing other than line endings.  Then how the user wants to parse into individual cells in columns based on quotes or whatever strategy they want would be at their later discretion in the data grid view.

The current functionality of **Use character [ ] to enclose cells containing column separators** works as originally intended and does not need functional changes.  So closing this as not needed.
