### ISSUE TITLE
Importing with Google Data sometimes throws timeout at /command/core/importing-controller

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#1627]
#### Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
3,0 Beta

#### Operating Systems and version:
Windows 10

#### Browser + version used - Please note that OpenRefine doesn't support Internet Explorer but works OK in most cases:
Firefox latest

#### Steps followed to create the issue:
1. Try to import Otto Knoke's private spreadsheet using Google Data importer after signing in. 
2. Spinner occurs and then after 20 seconds an error in console occurs, see Current Results.

#### If you are allowed and are OK with making your data public, it would be awesome if you can include the data causing the issue or a URL pointing to where the data is (if your concerned about keeping your data private, ping us on our mailing list):

(@jackyq2015 email cc'd and added as authorized user to debug and test importing Google Data from Otto's private spreadsheet)

#### Current Results:
```
09:33:59.645 [                   refine] POST /command/core/create-importing-job (10462ms)
09:33:59.649 [                   refine] POST /command/core/importing-controller (4ms)
09:34:19.685 [          org.mortbay.log] /command/core/importing-controller: java.net.SocketTimeoutException: Read timed out (20036ms)
```
#### Expected Results:
Spreadsheet data is imported into Preview datagrid and doesn't stop at 20 sec hard limit, but instead will continue to load data up to the users preference setting in preferences.vt

**Comment by jackyq2015** [comment]
when I tried to open the link Otto sent to me to share. I got error:
```
You need permission
Want in? Ask for access, or switch to an account with permission. Learn more
```
But when I list the files from drive, I can see the shared file. Not sure if it's related. 

Related issues:
https://github.com/google/google-api-java-client/issues/853
https://github.com/google/google-http-java-client/issues/146

**Comment by thadguidry** [comment]
Awesome. Let's Merge it then.
