### ISSUE TITLE
Refine doesn't retain the characters for flat or sharp

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#163]
_Original author: raymond....@gmail.com (October 17, 2010 21:25:08)_

I had flats (♭) and sharps (♯) in the Excel file that I imported into Refine but they were not rendered properly (showing up as ?).  I hit the edit button in Refine for the field and pasted from Excel the flats and sharps and it looked like they &quot;stuck&quot; -- but when I restarted Refine, they were displayed as ? again.

Version 1587.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=163_

**Comment by drangons** [comment]
Hi,
I am the issue for german character. When csv file is imported to refine, the column values are displayed as ? for ö ü characters. I am using 2.5-r2407 . 
for example für is displayed as fÃ¼r
