### ISSUE TITLE
Feature Request: Push updates back into SQL Database

### ISSUE THREAD

**Issue by Bowiemb** [OpenRefine/OpenRefine#1634]
It would be great if you could take a slice of your data from the SQL/postgress database, define your operations, then, apply these changes to the entire table. 

In order for this to work, we would need the ability to push/export updates to the database. This is in contrast to the current data flow of importing, applying operations, and downloading new SQL table dump. 

Thank you for any feedback. 

My best,
Michael

**Comment by wetneb** [comment]
If what you mean is "convert a series of OpenRefine operations into equivalent SQL queries", then this is basically infeasible as far as I can tell.

OpenRefine's operations have not been designed to be easily translated to SQL. Some of them can, but for the majority of them this would be virtually impossible. OpenRefine's data model is just very different from SQL's so there is no hope to build such a seamless integration between the two.

**Comment by Bowiemb** [comment]
Thank you @wetneb. I was afraid so. 

With the new database connection feature, it's foreseeable to potentially query an Hbase in the future. Then, it would be wonderful if we could translate OpenRefine operations into Scala code.

If the backend was disconnected from the front end, this would make this much easier since you could just call the commands directly and parse (and pass) the JSON as parameters.

**Comment by magdmartin** [comment]
@Bowiemb disconnecting the front and back end is [part of our roadmap](https://github.com/OpenRefine/OpenRefine/projects). 

Here are my 2 cents for this proposal. What if we allow the user to generate an `UPDATE` statement following the same principle than the current SQL Exporter for `INSERT INTO`. The worflow will be something like this:
* connect to the database to create the project
* clean up in OpenRefine
* generate an update statement to save back the result in the database with an indication of the key field to use for the update (all the other field will be updated). 

Obviously, this scenario will work only have several limitations including:
* Work with only one table
* Does not support changes to the table schema

**Comment by Bowiemb** [comment]
@magdmartin That's a great idea. This would allow much easier batch processing of large tables.

**Comment by wetneb** [comment]
Closing as this is not something we are going to do directly.
