### ISSUE TITLE
Openrefine 3.0 cannot run when trying to read my 2.8 directory

### ISSUE THREAD

**Issue by yaeln** [OpenRefine/OpenRefine#1636]
Version of OpenRefine ==>  3.0
MacBook Pro, 
Operating Systems and version: macOS High Sierra 10.13.4

java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

Browser: chrome Version 66.0.3359.181 (Official Build) (64-bit)
Running log:

MacBook-Pro-3:MacOS yaeln$ ./JavaAppLauncher 

18:51:18.258 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)

18:51:18.282 [            refine_server] Initializing context: '/' from '/Applications/OpenRefine3.app/Contents/Resource/webapp' (24ms)

18:51:19.158 [                   refine] Starting OpenRefine 3.0-beta [TRUNK]... (876ms)

18:51:19.158 [                   refine] initializing FileProjectManager with dir (0ms)

18:51:19.158 [                   refine] /Users/yaeln/Library/Application Support/OpenRefine (0ms)

18:51:21.055 [       database-extension] Initializing OpenRefine Database... (1897ms)

18:51:21.059 [       database-extension] Database Extension Mount point /extension/database/ [*] (4ms)

18:51:21.059 [       database-extension] Registering Database Extension Commands...... (0ms)

18:51:21.075 [       database-extension] Database Extension Command Registeration done!! (16ms)

18:51:21.075 [       database-extension] Database Operations Registered successfully... (0ms)

18:51:21.075 [       database-extension] Database Functions Registered successfully... (0ms)

Exception in thread "main" java.lang.LinkageError: loader constraint violation: loader (instance of edu/mit/simile/butterfly/ButterflyClassLoader) previously initiated loading for a different type with name "org/slf4j/Logger"

	at java.lang.ClassLoader.defineClass1(Native Method)

	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)

	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)

	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)

	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)

	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)

	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)

	at java.security.AccessController.doPrivileged(Native Method)

	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)

	at edu.mit.simile.butterfly.ButterflyClassLoader.loadClass(ButterflyClassLoader.java:51)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

	at com.google.refine.extension.database.DatabaseModuleImpl.readModuleProperty(DatabaseModuleImpl.java:93)

	at com.google.refine.extension.database.DatabaseModuleImpl.init(DatabaseModuleImpl.java:68)

	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)

	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)

	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)

	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)

	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)

	at com.google.refine.RefineServer.configure(Refine.java:296)

	at com.google.refine.RefineServer.init(Refine.java:208)

	at com.google.refine.Refine.init(Refine.java:114)

	at com.google.refine.Refine.main(Refine.java:108)

Thanks ! Yael

**Comment by jackyq2015** [comment]
Can you try to reinstall the app but when you ask if you want to "keep" or "replace" the old version choose "replace"? I think that will fix the issue.

**Comment by yaeln** [comment]
No, did not help

MacBook-Pro-3:MacOS yaeln$ ls
JavaAppLauncher
MacBook-Pro-3:MacOS yaeln$ ./JavaAppLauncher 
17:06:24.474 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
17:06:24.489 [            refine_server] Initializing context: '/' from '/Applications/OpenRefine.app/Contents/Resource/webapp' (15ms)
17:06:25.099 [                   refine] Starting OpenRefine 3.0-beta [TRUNK]... (610ms)
17:06:25.099 [                   refine] initializing FileProjectManager with dir (0ms)
17:06:25.099 [                   refine] /Users/yaeln/Library/Application Support/OpenRefine (0ms)
17:06:26.605 [       database-extension] Initializing OpenRefine Database... (1506ms)
17:06:26.608 [       database-extension] Database Extension Mount point /extension/database/ [*] (3ms)
17:06:26.608 [       database-extension] Registering Database Extension Commands...... (0ms)
17:06:26.625 [       database-extension] Database Extension Command Registeration done!! (17ms)
17:06:26.625 [       database-extension] Database Operations Registered successfully... (0ms)
17:06:26.625 [       database-extension] Database Functions Registered successfully... (0ms)
Exception in thread "main" java.lang.LinkageError: loader constraint violation: loader (instance of edu/mit/simile/butterfly/ButterflyClassLoader) previously initiated loading for a different type with name "org/slf4j/Logger"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at edu.mit.simile.butterfly.ButterflyClassLoader.loadClass(ButterflyClassLoader.java:51)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.google.refine.extension.database.DatabaseModuleImpl.readModuleProperty(DatabaseModuleImpl.java:93)
	at com.google.refine.extension.database.DatabaseModuleImpl.init(DatabaseModuleImpl.java:68)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:296)
	at com.google.refine.RefineServer.init(Refine.java:208)
	at com.google.refine.Refine.init(Refine.java:114)
	at com.google.refine.Refine.main(Refine.java:108)

**Comment by jackyq2015** [comment]
That's weird. I can reproduce your error if I choose "keep both". but if I choose "replace", it will fix the error.
Then can you manually clean the installation folder by run: 
`mv /Applications/OpenRefine3.app/ /Applications/OpenRefine3.app.bak`

Then do a installation.

**Comment by yaeln** [comment]
Still the same behavior.
The question is how can I import all of my 2.7/ 2.8 projects to the 3.0 (it runs well on an empty directory)?

**Comment by thadguidry** [comment]
@jackyq2015 perhaps have @yaeln zip up his complete OpenRefine workspace folder and email to you privately and you can troubleshoot more since you have a macOS ?  Or is this really something OS specific ?

**Comment by jackyq2015** [comment]
@yaeln The old projects should be automatically imported.Also I noticed that you installed OR under /Applications/OpenRefine3.app/, the default installation folder should /Applications/OpenRefine.app/.

Can you do a ls -ld /Applications/OpenRefine* before and after your installation? or you can upload somewhere as suggested by @thadguidry so I can take a look.

**Comment by yaeln** [comment]
Here is a link to my (quite large) library
https://www.dropbox.com/s/p69fph1qrt0tpv8/OpenRefine.zip?dl=0

attached also my ls -ld before and after  + error of running

**Comment by jackyq2015** [comment]
@yaeln Can you install version 2.8 and see if it's working? Seems it is related to the location of the path which has a space in between. I cannot find any code change might be affecting this. Also my version of MacOS Mavericks works fine and the old projects can be imported automatically.

Also you can try to move your project to: 
```
mkdir /Users/yaeln/.openrefine/
mv /Users/yaeln/Library/Application Support/OpenRefine/* /Users/yaeln/.openrefine/
```
Then edit the refine.ini under installation folder:
`JAVA_OPTIONS=-Drefine.data_dir=/Users/yaeln/.openrefine/`

Let me know the result.

**Comment by yaeln** [comment]
Version 2.8 works fine!
However, I don't know where the installation/refine.ini file is..

Thanks a lot!

**Comment by jackyq2015** [comment]
you can edit file Info.plist under /Applications/OpenRefine.app/Contents by inserting one line:
`<string>-Drefine.data_dir=~/.openrefine</string>`
 under:
`<string>-Drefine.webapp=$APP_ROOT/Contents/Resource/webapp</string>`

**Comment by jackyq2015** [comment]
@yaeln Please ignore it won't work. Seems related to the data itself instead of installation. will do some debug on the projects you shared and get back to you.

**Comment by yaeln** [comment]
Thank you very much

**Comment by jackyq2015** [comment]
I can open the projects you shared using the same version. so it is not a data issue.
Do you still see the exception after install, if so please share the whole log as you did.

Could you please click "open project" then click the "Browse workspace directory" at the bottom and let me know the folder location? you should be able to see all of you projects in its folders and at least a file called workspace.json etc.

**Comment by yaeln** [comment]
Here is the log for current run, quite strange.

I need to start it all over again: I work with openrefine almost on a daily
basis. Would love to use the 3.0 version - what would you suggest?



MacBook-Pro-3:MacOS yaeln$ pwd

/Applications/OpenRefine.app/Contents/MacOS

MacBook-Pro-3:MacOS yaeln$ ./JavaAppLauncher

09:32:04.500 [            refine_server] Starting Server bound to '
127.0.0.1:3333' (0ms)

09:32:04.527 [            refine_server] Initializing context: '/' from
'/Applications/OpenRefine.app/Contents/Resource/webapp' (27ms)

09:32:05.823 [                   refine] Starting OpenRefine 3.0-beta
[TRUNK]... (1296ms)

09:32:05.823 [                   refine] initializing FileProjectManager
with dir (0ms)

09:32:05.823 [                   refine] /Users/yaeln/Library/Application
Support/OpenRefine (0ms)

09:32:05.848 [       FileProjectManager] Failed to load workspace from any
attempted alternatives. (25ms)

09:32:07.768 [       database-extension] Initializing OpenRefine
Database... (1920ms)

09:32:07.809 [       database-extension] Database Extension Mount point
/extension/database/ [*] (41ms)

09:32:07.809 [       database-extension] Registering Database Extension
Commands...... (0ms)

09:32:07.857 [       database-extension] Database Extension Command
Registeration done!! (48ms)

09:32:07.858 [       database-extension] Database Operations Registered
successfully... (1ms)

09:32:07.859 [       database-extension] Database Functions Registered
successfully... (1ms)

09:32:07.886 [       DatabaseModuleImpl] *** Database Extension Module
Initialization Completed!!*** (27ms)

09:32:18.998 [       database-extension] receiving request for
styles/jquery.contextMenu.css (11112ms)

09:32:18.998 [       database-extension] receiving method for GET (0ms)

09:32:19.015 [       database-extension] receiving request for
styles/pure.css (17ms)

09:32:19.015 [       database-extension] receiving method for GET (0ms)

09:32:19.053 [       database-extension] receiving request for
styles/bootstrap.css (38ms)

09:32:19.053 [       database-extension] receiving method for GET (0ms)

09:32:19.276 [       database-extension] receiving request for
styles/database-import.less (223ms)

09:32:19.276 [       database-extension] receiving method for GET (0ms)

09:32:20.465 [                   refine] POST /command/core/load-language
(1189ms)

09:32:20.525 [                   refine] GET /command/core/get-preference
(60ms)

09:32:20.552 [                   refine] POST /command/core/load-language
(27ms)

09:32:20.565 [                   refine] POST /command/core/load-language
(13ms)

09:32:20.862 [                   refine] POST
/command/core/get-importing-configuration (297ms)

09:32:20.899 [                   refine] GET
/command/core/get-all-project-tags (37ms)

09:32:20.940 [                   refine] GET
/command/core/get-all-project-metadata (41ms)

09:32:21.047 [                   refine] GET /command/core/get-languages
(107ms)

09:32:21.124 [                   refine] GET /command/core/get-version
(77ms)

09:32:21.532 [       database-extension] receiving request for
scripts/index/database-import-form.html (408ms)

09:32:21.533 [       database-extension] receiving method for GET (1ms)

09:32:21.551 [                   refine] GET
/command/database/saved-connection (18ms)

^Z

[1]+  Stopped                 ./JavaAppLauncher

MacBook-Pro-3:MacOS yaeln$ bg

[1]+ ./JavaAppLauncher &

MacBook-Pro-3:MacOS yaeln$ cd '/Users/yaeln/Library/Application
Support/OpenRefine'

MacBook-Pro-3:OpenRefine yaeln$ ls

dbextension

MacBook-Pro-3:OpenRefine yaeln$ cd dbextension/

MacBook-Pro-3:dbextension yaeln$ ls

MacBook-Pro-3:dbextension yaeln$

**Comment by ostephens** [comment]
I don’t have a solution currently but I run the Linux version of OpenRefine on my mac. You could try that to see if it works. 

Download the Linux version, unzip the folder, in a terminal change to the directory which contains OpenRefine you’ve just  downloaded and type:

./refine

**Comment by jackyq2015** [comment]
@yaeln Your default workspace is empty. I think for some reason you 2.8 version points to different workspace other than /Users/yaeln/Library/Application Support/OpenRefine. You may be did the change and forgot.

The solution is simple. you can just find the original workspace and copy all to the above folder. If you don't know where the original workspace is, you can just startup the 2.8 the same way you did above and you will find the location in the log by searching the line:
`initializing FileProjectManager with dir`

**Comment by yaeln** [comment]
Jacky, thanks for your answers: the reason the workspace was empty because
I tried again to run openrefine3
but when the directory is not empty still the same problem



MacBook-Pro-3:openrefine-3.0-beta yaeln$ ./refine

You have 229M of free memory.

Your current configuration is set to use 1400M of memory.

OpenRefine can run better when given more memory. Read our FAQ on how to
allocate more memory here:

https://github.com/OpenRefine/OpenRefine/wiki/FAQ:-Allocate-More-Memory

Starting OpenRefine at 'http://127.0.0.1:3333/'


11:58:49.918 [            refine_server] Starting Server bound to '
127.0.0.1:3333' (0ms)

11:58:49.920 [            refine_server] refine.memory size: 1400M JVM Max
heap: 1407188992 (2ms)

11:58:49.941 [            refine_server] Initializing context: '/' from
'/Users/yaeln/Dropbox/OpenRefine3/openrefine-3.0-beta/webapp' (21ms)

11:58:50.880 [                   refine] Starting OpenRefine 3.0-beta
[TRUNK]... (939ms)

11:58:50.881 [                   refine] initializing FileProjectManager
with dir (1ms)

11:58:50.881 [                   refine] /Users/yaeln/Library/Application
Support/OpenRefine (0ms)

11:58:52.570 [       database-extension] Initializing OpenRefine
Database... (1689ms)

11:58:52.574 [       database-extension] Database Extension Mount point
/extension/database/ [*] (4ms)

11:58:52.574 [       database-extension] Registering Database Extension
Commands...... (0ms)

11:58:52.591 [       database-extension] Database Extension Command
Registeration done!! (17ms)

11:58:52.591 [       database-extension] Database Operations Registered
successfully... (0ms)

11:58:52.592 [       database-extension] Database Functions Registered
successfully... (1ms)

Exception in thread "main" java.lang.LinkageError: loader constraint
violation: loader (instance of
edu/mit/simile/butterfly/ButterflyClassLoader) previously initiated loading
for a different type with name "org/slf4j/Logger"

at java.lang.ClassLoader.defineClass1(Native Method)

at java.lang.ClassLoader.defineClass(ClassLoader.java:760)

at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)

at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)

at java.net.URLClassLoader.access$100(URLClassLoader.java:73)

at java.net.URLClassLoader$1.run(URLClassLoader.java:367)

at java.net.URLClassLoader$1.run(URLClassLoader.java:361)

at java.security.AccessController.doPrivileged(Native Method)

at java.net.URLClassLoader.findClass(URLClassLoader.java:360)

at
edu.mit.simile.butterfly.ButterflyClassLoader.loadClass(ButterflyClassLoader.java:51)

at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

at
com.google.refine.extension.database.DatabaseModuleImpl.readModuleProperty(DatabaseModuleImpl.java:93)

at
com.google.refine.extension.database.DatabaseModuleImpl.init(DatabaseModuleImpl.java:68)

at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)

at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)

at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)

at
org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)

at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)

at com.google.refine.RefineServer.configure(Refine.java:296)

at com.google.refine.RefineServer.init(Refine.java:208)

at com.google.refine.Refine.init(Refine.java:114)

at com.google.refine.Refine.main(Refine.java:108)

^CMacBook-Pro-3:openrefine-3.0-beta yaeln$ cd
'/Users/yaeln/Library/Application Support/OpenRefine'

MacBook-Pro-3:OpenRefine yaeln$ cd -

/Users/yaeln/Dropbox/OpenRefine3/openrefine-3.0-beta

MacBook-Pro-3:openrefine-3.0-beta yaeln$ ls
'/Users/yaeln/Library/Application Support/OpenRefine'

1446580682893.project 1666186142080.project 1793693898613.project
1918520131795.project 2020263392516.project 2136998469473.project
2259939700194.project 2402041926607.project

1489218330389.project 1670302201997.project 1799042444002.project
1923689059576.project 2031728960862.project 2139101206950.project
2264253659541.project 2409171240385.project

1489364242205.project 1677344519612.project 1800007913009.project
1924573721718.project 2032311738138.project 2144524865786.project
2272088438167.project 2414008925260.project

1501796329251.project 1687143955008.project 1805021170114.project
1932591736306.project 2041547207055.project 2159414752919.project
2273768868611.project 2414378949082.project

1509132215183.project 1688064656376.project 1818391931890.project
1937502301779.project 2041555231399.project 2175974709736.project
2276183242047.project 2417684623211.project

1530528190323.project 1688773663886.project 1841913137661.project
1942523210146.project 2043587037229.project 2182249138150.project
2282262430452.project 2418843375818.project

1532242424112.project 1702286269219.project 1842698519929.project
1945899236298.project 2050449891603.project 2199657297131.project
2286341239207.project 2421289426309.project

1538911124566.project 1716419152512.project 1850797696343.project
1946853425096.project 2053801477002.project 2200290950472.project
2290251681469.project 2426789312953.project

1549921280123.project 1717878707118.project 1851159164491.project
1952727197627.project 2057187941191.project 2203235113420.project
2302081944383.project 2427499263716.project

1553937602167.project 1719178273314.project 1854933002698.project
1966260829138.project 2064936534813.project 2205995292637.project
2303846768545.project 2431993061547.project

1565172332019.project 1724547469113.project 1858018257345.project
1975702946577.project 2065958278745.project 2208441215130.project
2305460339776.project 2440100340100.project

1567203187209.project 1732489578292.project 1858077236625.project
1976009328081.project 2067034566918.project 2213216606268.project
2318516316786.project 2445864230447.project

1571978127561.project 1733972861179.project 1869203724432.project
1977709691762.project 2067863863631.project 2216638548473.project
2327000760945.project 2455159320072.project

1587825598164.project 1743386847322.project 1878880344349.project
1982646960318.project 2075642828002.project 2222643026646.project
2339788063806.project 2462081905625.project

1588840134378.project 1746472567069.project 1880802807866.project
1986019738472.project 2085520177557.project 2223058456840.project
2347538514479.project 2464898644573.project

1599936691371.project 1751135287300.project 1881060793986.project
1989339977948.project 2089572327315.project 2223467505826.project
2351930441513.project 2468646542835.project

1610771101153.project 1765375004976.project 1884146487283.project
1994193289483.project 2096614283835.project 2235555532353.project
2357055151319.project 2474040628970.project

1614869370298.project 1769290954109.project 1885136041021.project
1995697485713.project 2099572626764.project 2241416007337.project
2372871461418.project 2513584509629.project

1615028782997.project 1773964629200.project 1885362571233.project
1997538651930.project 2111856832805.project 2242409430241.project
2376358755012.project cache

1620294021385.project 1778048960086.project 1889307503617.project
2013137542546.project 2124493779831.project 2243309603691.project
2385830905655.project extensions

1648032973528.project 1780825948647.project 1893484483544.project
2017480276292.project 2127151184698.project 2253906528238.project
2392043806733.project workspace.json

1648050396339.project 1783378714077.project 1903575896504.project
2019052398606.project 2129382286096.project 2254693892092.project
2400494862316.project workspace.old.json

MacBook-Pro-3:openrefine-3.0-beta yaeln$

**Comment by jackyq2015** [comment]
@yaeln I am got confused. From [this ](https://github.com/OpenRefine/OpenRefine/issues/1636#issuecomment-396040135)post, I did not see you had exception java.lang.LinkageError as you did in previous post. You may only have this one issue  and the project loading is the consequence of the failure.

So please do a refresh install by choose "**replace**" when you see the dialog box then start it to see if you still see the LinkageError  exception. If you do, please zip your whole installation package(not the projects package) and share with me. Thanks a lot

**Comment by yaeln** [comment]
Yap, I did it, still error. Installation package - do you mean the
openrefine.app dir? can be downloaded from here
https://www.dropbox.com/s/9qz3p47kqinxu1h/OpenRefine.app.zip?dl=0

Again, this is the log


MacBook-Pro-3:OpenRefine.app yaeln$ cd ..

MacBook-Pro-3:Applications yaeln$ cd OpenRefine.app/

MacBook-Pro-3:OpenRefine.app yaeln$ cd Contents/MacOS/

MacBook-Pro-3:MacOS yaeln$ ./JavaAppLauncher

23:07:21.265 [            refine_server] Starting Server bound to '
127.0.0.1:3333' (0ms)

23:07:21.287 [            refine_server] Initializing context: '/' from
'/Applications/OpenRefine.app/Contents/Resource/webapp' (22ms)

23:07:22.226 [                   refine] Starting OpenRefine 3.0-beta
[TRUNK]... (939ms)

23:07:22.226 [                   refine] initializing FileProjectManager
with dir (0ms)

23:07:22.226 [                   refine] /Users/yaeln/Library/Application
Support/OpenRefine (0ms)

23:07:23.902 [       database-extension] Initializing OpenRefine
Database... (1676ms)

23:07:23.905 [       database-extension] Database Extension Mount point
/extension/database/ [*] (3ms)

23:07:23.905 [       database-extension] Registering Database Extension
Commands...... (0ms)

23:07:23.920 [       database-extension] Database Extension Command
Registeration done!! (15ms)

23:07:23.920 [       database-extension] Database Operations Registered
successfully... (0ms)

23:07:23.920 [       database-extension] Database Functions Registered
successfully... (0ms)

Exception in thread "main" java.lang.LinkageError: loader constraint
violation: loader (instance of
edu/mit/simile/butterfly/ButterflyClassLoader) previously initiated loading
for a different type with name "org/slf4j/Logger"

at java.lang.ClassLoader.defineClass1(Native Method)

at java.lang.ClassLoader.defineClass(ClassLoader.java:760)

at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)

at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)

at java.net.URLClassLoader.access$100(URLClassLoader.java:73)

at java.net.URLClassLoader$1.run(URLClassLoader.java:368)

at java.net.URLClassLoader$1.run(URLClassLoader.java:362)

at java.security.AccessController.doPrivileged(Native Method)

at java.net.URLClassLoader.findClass(URLClassLoader.java:361)

at
edu.mit.simile.butterfly.ButterflyClassLoader.loadClass(ButterflyClassLoader.java:51)

at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

at
com.google.refine.extension.database.DatabaseModuleImpl.readModuleProperty(DatabaseModuleImpl.java:93)

at
com.google.refine.extension.database.DatabaseModuleImpl.init(DatabaseModuleImpl.java:68)

at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)

at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)

at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)

at
org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)

at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)

at com.google.refine.RefineServer.configure(Refine.java:296)

at com.google.refine.RefineServer.init(Refine.java:208)

at com.google.refine.Refine.init(Refine.java:114)

at com.google.refine.Refine.main(Refine.java:108)

**Comment by jackyq2015** [comment]
I downloaded your app zip above and did a clean install and it can run on my Maverick and load the my projects without issue.I know you are using High Sierra
@ostephens @wetneb , do you have some time to download above zip @yaeln provided and have a try on your mac. It is very weird issue.

**Comment by ostephens** [comment]
Downloaded and ran successfully on macOS High Sierra.

@yaeln can you check what version of Java you have installed?
run `java -version` on the command line and paste the results

(I'm clutching at straws a bit here but just trying to think of things that might be difference across setups)

**Comment by yaeln** [comment]
MacBook-Pro-3:MacOS yaeln$ java -version

java version "1.8.0_25"

Java(TM) SE Runtime Environment (build 1.8.0_25-b17)

Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

MacBook-Pro-3:MacOS yaeln$

**Comment by ostephens** [comment]
Mine is slightly more up to date, but I'd be a bit surprised if that is the reason for any different behaviour:

> java version "1.8.0_72"
> Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
> Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)

**Comment by ostephens** [comment]
So from the log do we assume that:
>Exception in thread "main" java.lang.LinkageError: loader constraint violation: loader (instance of edu/mit/simile/butterfly/ButterflyClassLoader) previously initiated loading for a different type with name "org/slf4j/Logger"

Is related to this problem?
I definitely don't see that in mine or when I run that version shared by @yaeln

**Comment by thadguidry** [comment]
Butterfly loads things from the Classpath.  Classpath is figured out through the start script.  Maybe the Classpath is munged for some reason ?

@jackyq2015 has he tried to just run using the Linux start script.... ```./refine``` ?  Because keep seeing JavaAppLauncher being used in his replies.

Debug the entire start flow with
```bash -x ./refine```

and then let's see what it looks like.

**Comment by thadguidry** [comment]
@yaeln Can you move your OpenRefine install outside of a DropBox path ?  I'm wondering if something with a Dropbox client might also be causing some conflict ?  dunno....

/Users/yaeln/Dropbox/OpenRefine3/openrefine-3.0-beta/webapp

**Comment by yaeln** [comment]
I tested - and not - obviously --  I usually run the openrefine from the
/Applications path (this is the linux installation)

My own solution  can be manually 'exporting' all projects from 2.8 and then
'importing' them into the 3.0 one after the other.
..

**Comment by ostephens** [comment]
The lines
```
+ '[' -z '' ']'
++ /usr/libexec/java_home
+ export
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home
+ JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home
+ '[' /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home ']'
```
Indicate your JAVA_HOME isn't set, but the script picks it up anyway from /usr/libexec/java_home so that can't be the problem (I tested unsetting JAVA_HOME on my own install and I got the same output as your script at this stage, but no other problems

**Comment by jackyq2015** [comment]
I also don't have the JAVA_HOME set but it works fine. 
```
$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

Now I have @yaeln 's app and work space. it also works fine. can you installed the updated JRE and have another try? cannot think of other possibility.

**Comment by janruehling** [comment]
I had a similar problem (macOS High Sierra - OpenRefine3 stuck at "Butterfly still initializing" in the browser) and solved it like this:

In your workspace directory (for me ~/Library/Application Support/OpenRefine):

- Rename "extensions" to "_extensions"
- Create a new folder "extensions"
- Copy one extension folder after the other from "_extensions" to "extensions" and restart OpenRefine

The problematic extension for me was "orefine-rdf-extension-0.9"

Good luck

**Comment by yaeln** [comment]
It worked!
Thanks a lot!
I have this extension 'prefine-rdf-extension-0.9' but once I moved them one
after the other it worked!
I am most grateful for you assistance.
OpenRefine is a very meaningful tool for me, I teach it almost like a
missioner in my DH classes, and I will do an effort to advance the Hebrew
translation.

Best regards,
Yael

**Comment by ettorerizza** [comment]
@yaeln [This version of the RDF extension](https://github.com/stkenny/grefine-rdf-extension/releases/tag/v1.0.0-rc2) should work with OR 3.

**Comment by yaeln** [comment]
Thanks.
Thanks for finding a solution to this problem as well
