### ISSUE TITLE
Error while running openrefine.exe

### ISSUE THREAD

**Issue by praveene04** [OpenRefine/OpenRefine#1645]
When reporting a bug please provide the following information to help reproduce the bug:

#### Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
OpenRefine 2.8

#### Operating Systems and version:
Windows 10

#### Browser + version used - Please note that OpenRefine doesn't support Internet Explorer but works OK in most cases:
Firefox

#### Steps followed to create the issue:
Tried running the OpenRefine.exe file and got error message

#### If you are allowed and are OK with making your data public, it would be awesome if you can include the data causing the issue or a URL pointing to where the data is (if your concerned about keeping your data private, ping us on our mailing list):
Error on launch itself

#### Current Results:
11:07:30.288 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
11:07:30.304 [            refine_server] Initializing context: '/' from 'C:\Praveen\Open Refine\openrefine-2.8\webapp' (16ms)
11:07:31.195 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (891ms)
11:07:31.195 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (0ms)
11:07:31.210 [                   refine] Starting OpenRefine 2.8 [TRUNK]... (15ms)
11:07:31.226 [       FileProjectManager] Failed to load workspace from any attempted alternatives. (16ms)

#### Expected Results:
Run without error

**Comment by jackyq2015** [comment]
can you please paste your whole startup log?

Also you can try to move the openrefine-2.8 folder and c:\ and try again. There is a space in your current path which may break.

**Comment by praveene04** [comment]
Hi jackyq2015,

I copy and pasted the openrefine folder directly in C drive and  tried opening openrefine.exe file and received below message.

09:25:30.543 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
09:25:30.559 [            refine_server] Initializing context: '/' from 'C:\openrefine-2.8\webapp' (16ms)
09:25:31.387 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (828ms)
09:25:31.387 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (0ms)
09:25:31.403 [                   refine] Starting OpenRefine 2.8 [TRUNK]... (16ms)

**Comment by thadguidry** [comment]
@praveene04 that is fine....its running as you can see it said "Started OpenRefine 2.8.."
Don't worry about the Failed to use jdatapath... that's just our user data path detection and it resorted to env variables.

Now with that running.. just open your web browser and go to http://127.0.0.1:3333

**Comment by praveene04** [comment]
I am getting this error message 
![error](https://user-images.githubusercontent.com/20364258/41299279-b8619606-6e28-11e8-9df1-9d43ded9ab2a.PNG)

**Comment by praveene04** [comment]
Used "http://localhost:3333" instead of "http://127.0.0.1:3333" which worked.

**Comment by thadguidry** [comment]
@jackyq2015 Hey...hmm, should we default to localhost for Macs ?  Wondering if that makes things easier, or if it was just @praveene04 weird setup ?

**Comment by ostephens** [comment]
@thadguidry this is on Win 10, not a Mac
