### ISSUE TITLE
Reconciliation internationalisation issues

### ISSUE THREAD

**Issue by susannaanas** [OpenRefine/OpenRefine#1654]
When reporting a bug please provide the following information to help reproduce the bug:

#### Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
v 3.0 beta

#### Operating Systems and version:
Mac OS 10.13.5 (17F77)

#### Browser + version used - Please note that OpenRefine doesn't support Internet Explorer but works OK in most cases:
Chrome 67.0.3396.87

#### Steps followed to create the issue:
* I have successfully reconciled items in my data using the Wikidata reconciliation service in Finnish.
* I choose "Search for match" to select from candidates
* Descriptions for items are presented in English, not in the reconciled language. If the description is missing in English, no description is presented.
* The reconciled item ".name" becomes the English label or QID, not the reconciled language label.

#### If you are allowed and are OK with making your data public, it would be awesome if you can include the data causing the issue or a URL pointing to where the data is (if your concerned about keeping your data private, ping us on our mailing list):
-- if needed

#### Current Results:
Extra steps with other tools are required to disambiguate and to make sense of the existing labels in the native language.

#### Expected Results:
Labels and descriptions would be perfectly presented in the reconciliation process.

**Comment by wetneb** [comment]
Thanks! That's an issue for https://github.com/wetneb/openrefine-wikidata. I will look into it.

**Comment by susannaanas** [comment]
Good point, I will create further issues there!

**Comment by wetneb** [comment]
@susannaanas the problem should be fixed now - can you confirm this on your side?

**Comment by wetneb** [comment]
This was fixed in the reconciliation service.
