### ISSUE TITLE
The column selection window of "Transform all" incorrectly labeled "SQL exporter"

### ISSUE THREAD

**Issue by ettorerizza** [OpenRefine/OpenRefine#1657]
When reporting a bug please provide the following information to help reproduce the bug:

#### Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
Version 3 beta

#### Operating Systems and version:
Windows 10

#### Browser + version used - Please note that OpenRefine doesn't support Internet Explorer but works OK in most cases:
All

#### Steps followed to create the issue:
Click on "All", then "Transform", then "OK"

#### If you are allowed and are OK with making your data public, it would be awesome if you can include the data causing the issue or a URL pointing to where the data is (if your concerned about keeping your data private, ping us on our mailing list):
Any dataset

#### Current Results:
![screenshot-127 0 0 1-3333-2018 06 19-12-04-13](https://user-images.githubusercontent.com/6286410/41591108-2252eb56-73b9-11e8-8b03-6e77a6828338.png)

#### Expected Results:
A column selection window labeld "Select the columns to transform", something like that.

**Comment by wetneb** [comment]
What the actual f***?!

**Comment by thadguidry** [comment]
@wetneb LOL, We're preparing the user for the "Enterprise world" where they will have a love/hate relationship later on when the only language available to them will be SQL !

**Comment by thadguidry** [comment]
@tcbuzor Please fix this VERY SOON.

**Comment by ostephens** [comment]
It looks like the problem is that the lang string "custom-tab-exp" has been used for multiple purposes. It should only really be applied to the Custom Tabular Exporter pop-up ```custom-tabular-exporter-dialog.js```

However it has also been applied in:

* expression-column-dialog.js
* sql-exporter-dialog.js

I think these two latter places need two new language strings defining and using
