### ISSUE TITLE
Cannot export a file if the "blank" tab opened after a first export is not closed

### ISSUE THREAD

**Issue by ettorerizza** [OpenRefine/OpenRefine#1664]
When reporting a bug please provide the following information to help reproduce the bug:

#### Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
Version 3 beta

#### Operating Systems and version:
Windows 10

#### Browser + version used - Please note that OpenRefine doesn't support Internet Explorer but works OK in most cases:
Chrome

#### Steps followed to create the issue:
When you export a file, a new blank tab ("about: blank") opens with the download window. As long as this tab remains open, you can't download anything again. This is particularly frustrating when using "Custom tabular export": not only it does not download anything, but you have to restart the settings configuration.

![screencast](https://user-images.githubusercontent.com/6286410/41818017-a543b59a-77a6-11e8-92c1-1f45f3cf50b5.gif)

#### Expected Results:

Automatically close the new blank tab or allow multiple download tabs.

**Comment by thadguidry** [comment]
Actually, I do not see why in 2018, that a new tab has to be opened at all for a download from a webapp.  We should look into handling all that seamlessly and in a better fashion across all 3 browsers.

**Comment by kushthedude** [comment]
@wetneb Can I be assigned to this ?

**Comment by thadguidry** [comment]
@kushthedude Sure, let us know if you have questions.

**Comment by kushthedude** [comment]
@thadguidry The following bug is not present in Safari. Although I have fixed it on chrome too, please take a look at referenced PR.

**Comment by thadguidry** [comment]
@kushthedude On Firefox browser, it still opens a new browser tab in order to download the file.  Let's work more towards not opening a new browser tab at all, in order to download the file.

**Comment by kushthedude** [comment]
@theadguidry The PR opens a new tab and closes it as soon as the user starts download or cancel it. Hence there is no opening of new tab now.

**Comment by thadguidry** [comment]
@kushthedude Have you tested your PR on Firefox?  For me, your PR keeps the tab open for .  Ideally, we don't want a tab to open at all, but if that is too complex for you at this time then I understand.

Also please test our export option "Custom tabular exporter" on both Firefox and Chrome, because both still keep a browser tab open.
