### ISSUE TITLE
Error contacting recon service: timeout : timeout - https://tools.wmflabs.org/openrefine-wikidata/en/api

### ISSUE THREAD

**Issue by visch** [OpenRefine/OpenRefine#1665]
When reporting a bug please provide the following information to help reproduce the bug:

#### Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
Open Refine 3.0 beta

#### Operating Systems and version:
Windows 10 

#### Browser + version used - Please note that OpenRefine doesn't support Internet Explorer but works OK in most cases:

Chrome

#### Steps followed to create the issue:

1. Clone git repo
2. run refine.bat build
3. run refine.bat
4. Import a file or two
5. Wait around, and you'll recieve js alerts with the message "Error contacting recon service: timeout : timeout - https://tools.wmflabs.org/openrefine-wikidata/en/api"

#### If you are allowed and are OK with making your data public, it would be awesome if you can include the data causing the issue or a URL pointing to where the data is (if your concerned about keeping your data private, ping us on our mailing list):

N/A

#### Current Results:
Javascript alert

#### Expected Results:
No javascript alert

**Comment by visch** [comment]
It's obviously tied to https://tools.wmflabs.org/openrefine-wikidata/en/api being down, but OpenRefine probably should fail more gracefully or not have this url baked in? I'm not sure what the right solution is

**Comment by ostephens** [comment]
I'm not sure why we use a javascript alert for this. Would it make more sense to alert within the page where we display other messages (such as the version check, or the reconciliation progress info)?

**Comment by sharun-s** [comment]
I haven't used openrefine in a while, and I just wanted to merge a few misspelled text fields in some data. Everything works fine but when I click "browse a cluster" in the cluster and edit page, it opens the cluster in a new tab. And every new tab I get the pop up. It's quite annoying if I am browsing a bunch of clusters. Is there some configurable way to stop this request being made? I am not doing any recon stuff.Thanks

**Comment by wetneb** [comment]
That's because we try to add the recon service by default in the background - we should indeed not fail like this!
