### ISSUE TITLE
Replace smart quotes transformation

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1676]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
Sometimes data includes a mixture of smart quotes and straight quotes. Sometimes this is not wanted and it can cause confusion and problems when you want to compare data (e.g. via 'cross') or act on all quoted data

**Describe the solution you'd like**
Add on option on the Common transformations menu to "Replace smart quotes"

**Describe alternatives you've considered**
This can be achieved by the `replace` GREL, but this requires multiple replacing and finding all variations of single and double smart open and close quotes

**Additional context**
n/a

**Comment by ostephens** [comment]
This originated on the discussion list - see https://groups.google.com/d/msg/openrefine/gsmP9QOKuhQ/LGPpvuovBAAJ

**Comment by thadguidry** [comment]
Pages and Pages of existing code and libraries to help already with this:  https://github.com/search?q=smart+quotes
