### ISSUE TITLE
Reconcillation Issue

### ISSUE THREAD

**Issue by Gautamshahi** [OpenRefine/OpenRefine#1686]
Why am I not able to reconcile my data with standard SPARQL endpoint? It gives no match. 

Where is the issue? Please suggest some alternatives.

**Comment by thadguidry** [comment]
@Gautamshahi Our documentation for Reconciliation https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation

I've added a special NOTE now to highlight this now:

"NOTE: OpenRefine Reconciliation does NOT work against a SPARQL endpoint at this time (https://github.com/OpenRefine/OpenRefine/issues/1212), but instead only a Reconciliation Service API."

**Comment by Gautamshahi** [comment]
Hi,

Please read the query properly, Everytime I get a same answer.

The SPARQL endpoint is working but reconcilation is not working which is a
part of open refine.

Anyway thanks a lot.
