### ISSUE TITLE
Issue with adding prefix for RDF skeleton

### ISSUE THREAD

**Issue by Gautamshahi** [OpenRefine/OpenRefine#1687]
Hi, 

I am trying to add my ontology to define the RDF-Skelton but not getting an advance option, as shown in Image. I am using 2.8 

![image](https://user-images.githubusercontent.com/3966230/43228052-1ded57ae-907e-11e8-8134-92ec5d122f9a.png)

**Comment by wetneb** [comment]
Hi @Gautamshahi 

As we have already explained to you in issues  #1587, #1590,  #1686 and #1572, this feature is part of the RDF extension, which is not maintained by our team.

**You are reporting these issues to the wrong team.**

You will always get the same answer. Reporting more issues will not change this.

Please **stop** reporting issues in this repository now. You are wasting our time.
