### ISSUE TITLE
Export URL as clickable hyperlink (HTML Table)

### ISSUE THREAD

**Issue by LotharHuber** [OpenRefine/OpenRefine#1696]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
After reconciliation (wikidata) the reconciled values can be exported as clickable hyperlinks using Export > HTML table in OpenRefine

A new colum based on the reconciled values can be created with "https://www.wikidata.org/wiki/"+cell.recon.match.id That creates a new colum with clickable hyperlinks in OpenRefine. If this data will be exported as HTML table those hyperlinks will not exported as clickable hyperlinks.

**Describe the solution you'd like**
All clickabe hyperlinks in the OpenRefine GUI should be exported as clickable hyperlinks using Export > HTML table. 

**Describe alternatives you've considered**
This option could be configured in an option dialog ("Convert URLs to Hyperlinks") but that would need an new option dialog because currently there is no configuration possible.

**Additional context**
![openrefine_gui](https://user-images.githubusercontent.com/41336924/43764476-d342cb12-9a2d-11e8-8d74-daca83b72d61.png)

![openrefine_html-export](https://user-images.githubusercontent.com/41336924/43764494-dab2a3a4-9a2d-11e8-8f5f-26529d30cfd0.png)

**Comment by wetneb** [comment]
Thanks for filing this issue! I agree it would make sense to make these links clickable by default.
