### ISSUE TITLE
Issue with GREL code

### ISSUE THREAD

**Issue by Gautamshahi** [OpenRefine/OpenRefine#1703]
Hi,

I am trying to transform the column by fetching the value from another column, but I am getting a random value, please suggest the possible option.

![image](https://user-images.githubusercontent.com/3966230/43928955-9a6bff3c-9c50-11e8-8502-09c0d89e74f5.png)

**Comment by thadguidry** [comment]
You forgot to ask for the value that you want from the cells object.
```
cells["Serial"].value
```
https://github.com/OpenRefine/OpenRefine/wiki/Variables#cells

**Comment by Gautamshahi** [comment]
Thanks a lot.
