### ISSUE TITLE
No syntax error given for GREL startsWith(value,/\d.*/)

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#171]
_Original author: thadguidry (October 27, 2010 18:41:50)_

It would be nice to have startsWith(string s, sub or regex) supported instead of just startsWith(string s, sub).  Same for endsWith().

Interestingly, startsWith(value,/\d.*/) does not give a syntax error.

<b>What is the expected output? What do you see instead?</b>

Support regex subs or give a syntax error.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=171_

**Comment by ostephens** [comment]
@thadguidry 'contains' now supports regular regex which I think covers all use cases (as you can use ^ and $ in that if you want to test for starts/ends with)

I'm not sure adding regex support to startsWith or endsWith as well is useful or really makes sense. What do you think?

**Comment by thadguidry** [comment]
@ostephens Yeap, your right !  startsWith and endsWith was for simplicity, and they are useful for quick matching without bogging folks down into learning regex.  Let's keep those two simple, agreed.
