### ISSUE TITLE
Nothing is on the Web Page

### ISSUE THREAD

**Issue by wentianq** [OpenRefine/OpenRefine#1717]
**Describe the bug**
When OpenRefine is running, my browser at http://127.0.0.1:3333/. However, nothing is on the web page except an icon

**Screenshots**
![image](https://user-images.githubusercontent.com/42724736/44634755-e8f89480-a96b-11e8-8a7d-b677d3220e81.png)
![image](https://user-images.githubusercontent.com/42724736/44634756-eeee7580-a96b-11e8-9c1e-15411736265a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**OpenRefine (please complete the following information):**
 - Version: OpenRefine 3.0

**Comment by wetneb** [comment]
Hi! Thanks for the report. Can you open the javascript console in your browser and check if there are any errors there?

**Comment by wentianq** [comment]
Thx for your reply. Here is the console. Can you please help me to fix these error?
![image](https://user-images.githubusercontent.com/42724736/44856857-7e31ac80-ac3c-11e8-927e-c56e7b9cba12.png)

**Comment by wetneb** [comment]
Can you click on the `index-bundle.js:63726` link and post another screenshot of what you see?

**Comment by wetneb** [comment]
can you scroll down to line 63726 and see what is there?

**Comment by wetneb** [comment]
@wentianq which version of Chrome are you using and have you tried updating it?

**Comment by wentianq** [comment]
It is version 68.0.3440.106.

**Comment by wetneb** [comment]
Ok then I really don't know - have you added any extension or is it just the default OpenRefine package?

**Comment by wentianq** [comment]
It is the default package.

**Comment by ostephens** [comment]
Do you have any extensions installed in Chrome? If so can you try turning these off and seeing if that helps? Or trying in another browser?

**Comment by wentianq** [comment]
After I forbade the extensions in Chrome, it still didn't work. I also tried IE, but I got the same result.

**Comment by jackyq2015** [comment]
could you please provide:
- the exact version you downloaded
- windows version
- Java version

Another thing you can try is to switch to another user which has no space in between

**Comment by wentianq** [comment]
- Version Downloaded: openrefine-win-3.0-rc.1
- Windows Version: Microsoft Windows 10 Home
- Java Version: 10.0.2

**Comment by jackyq2015** [comment]
@wentianq Most of the OR users are using Java 8. Java 9 is not fully tested and there are some known issues. Java 10 is barely tested. I would suggest you to install the version 8 and set the JAVA_HOME environment variable and have another try.

**Comment by wetneb** [comment]
Ah yes of course, why didn't we think about the Java version! That's clearly the issue.

**Comment by wentianq** [comment]
I reinstalled Java with version 8, but I get the same result for OpenRefine.
![capture](https://user-images.githubusercontent.com/42724736/45185960-f6c6d900-b1f9-11e8-84c4-99fd0f6da202.PNG)

**Comment by jackyq2015** [comment]
Are you sure  Java 8 is picked up? Did you set JAVA_HOME variable?

You can run the refine.bat from the command line and paste the output

**Comment by wentianq** [comment]
I downloaded JRE of Java SE 8u181 from [http://www.oracle.com/technetwork/java/javase/downloads/index.html](url).
![capture1](https://user-images.githubusercontent.com/42724736/45193493-3f8f8980-b21c-11e8-8b85-c44d6f8082d8.PNG)
I also set JAVA_HOME variable like this:
![capture](https://user-images.githubusercontent.com/42724736/45193511-57ffa400-b21c-11e8-9ed4-0f7de2fbc5e8.PNG)
I tried to run refine.bat, but it quit immediately.

**Comment by thadguidry** [comment]
@wentianq For Windows users, I've added 2 more things to check in our FAQ about this https://github.com/OpenRefine/OpenRefine/wiki/FAQ#i-am-having-trouble-connecting-to-openrefine-with-my-browser

**Comment by wentianq** [comment]
I have tried http://localhost:3333, but I still get the following page:
![capture](https://user-images.githubusercontent.com/42724736/45194683-183bbb00-b222-11e8-874c-7ec768ce5d90.PNG)
I read your FAQ about browser and checked all bullet points except the third one since I had no idea about how to use a different IP address and Port. Still, I got the same result.

**Comment by wentianq** [comment]
I think the Port is correct in default. If not, What should I change it into?
![capture](https://user-images.githubusercontent.com/42724736/45195122-32769880-b224-11e8-94de-33baa91ce1b2.PNG)

**Comment by thadguidry** [comment]
@wentianq Anything that works !  Try 8888 or 8181 or 3334
Note you have to remove the # comment character

**Comment by wentianq** [comment]
I tried Firefox on this computer, as well as IE. None of these works.
![capture](https://user-images.githubusercontent.com/42724736/45195775-4bcd1400-b227-11e8-8e7e-c10ea778b4af.PNG)
![capture1](https://user-images.githubusercontent.com/42724736/45195789-57b8d600-b227-11e8-8aa2-f0e4582df8f2.PNG)

**Comment by thadguidry** [comment]
I give up.

**Comment by wentianq** [comment]
It also shows on my computer.
![capture](https://user-images.githubusercontent.com/42724736/45196373-e2023980-b229-11e8-9314-064f49197bbb.PNG)

**Comment by thadguidry** [comment]
I officially give up.  Perhaps others on the team can help discover the solution for you.

**Comment by jackyq2015** [comment]
It is not right to exit quietly when you run refine.bat. are you running it from the command line?

can you run "refine /h" to see what happen?

**Comment by wentianq** [comment]
I just double clicked refine.bat. I don't know how pause it in the end. I tried to add PAUSE at the end of refine.bat, but it didn't work either.
![capture](https://user-images.githubusercontent.com/42724736/45268837-45ba7b80-b451-11e8-9b79-3e6b6cb306a8.PNG)

**Comment by jackyq2015** [comment]
no, you don't have to do pause. it should print the message on your command line console when you run refine.bat. If it does not, then something is wrong

**Comment by wentianq** [comment]
Well... Assuming something is wrong, what should I do? Frankly speaking, I just wanna give up using OpenRefine. Fixing here and there without any fruit is so exhausting to me.

**Comment by jackyq2015** [comment]
Sorry to hear that. It is not easy to troubleshooting your issue since it is hard to reproduce. could you please try two things
- try to rename your current openrefine folder to different one and do a installation
- try to rename you workspace folder to see if it is caused by the data. 

If still cannot resolve, you can upload your copy of your installation somewhere I will take a look for you.

**Comment by wentianq** [comment]
- I installed it again in a different folder and I did not help.
- I don't know how to change the path of the workspace folder to another one.

I don't think the problem comes from the installation package since it is directly download from the OpenRefine website without any change. In addition, the zip file is too large to upload here.

**Comment by jackyq2015** [comment]
You can just rename the folder:
C:\Users\(user id)\AppData\Local\OpenRefine

And start again from the command line:
```
e:\openrefine > refine.bat
```

**Comment by wentianq** [comment]
C:\Users(user id)\AppData\Local\OpenRefine is exactly the path of the workspace at present.

**Comment by pollyhunter** [comment]
i have the same problem. who can solve it ?

**Comment by wetneb** [comment]
@wentianq @pollyhunter have you tried running older versions of OpenRefine, like 2.8 or even 2.7? Does it make any difference?

**Comment by pollyhunter** [comment]
if apache ant is necessary?

**Comment by pollyhunter** [comment]
> @wentianq @pollyhunter have you tried running older versions of OpenRefine, like 2.8 or even 2.7? Does it make any difference?

thank u 
i have tried openrefine 2.8. it succeed!

**Comment by wentianq** [comment]
Thx. OpenRefine 2.8 also works on my computer.

**Comment by wetneb** [comment]
@jackyq2015 I have the feeling that this bug has to do with the Data Package PR. The Javascript error happens in the javascript library used for JSON editing. Not sure why though.

**Comment by thadguidry** [comment]
Which library is that @wetneb ?

**Comment by jackyq2015** [comment]
I suspect that also. For some reason, the js may be combined in different way as usual. Maybe caused by Java version and OS specific. I am sure if I can reproduce it, I can fix it.

@pollyhunter what's the version of your Java and the OS version?

**Comment by wetneb** [comment]
Given that this seems to affect quite a lot of people (three have reported it so far) I am removing the `not-reproducible` tag. The next release will be without the data package PR so hopefully it should solve the issue.

**Comment by AlexGuo1998** [comment]
Hello? Same issue on my Windows PC. 

It seems that they (we) all are using a *Chinese* Windows 10. Could it be some issue related to locale? 

Please check that, thanks!

**Comment by AlexGuo1998** [comment]
BTW, @wetneb 

>           can you scroll down to line 63726 and see what is there?

Line 63726 shows something like this:

![63726](https://user-images.githubusercontent.com/25975864/46013591-59c3d580-c0ff-11e8-83ce-08c66cf8c96b.png)

**Comment by AlexGuo1998** [comment]
Quick fix: Replace `webapp\modules\core\externals\jsoneditor\jsoneditor.js` with this file [jsoneditor.zip](https://github.com/OpenRefine/OpenRefine/files/2415273/jsoneditor.zip) (unzip first).

**Comment by jackyq2015** [comment]
put the fix in master. will release at V3.1. Or you can apply  PR #1745  before the release

**Comment by cnzakimuena** [comment]
I encountered this error following 'Windows kit' OpenRefine 3.4.1 installation (with Java installed on my computer).  Using the 'Windows kit with embedded Java' OpenRefine 3.4.1 installation resolved the issue.

**Comment by alihabib-in** [comment]
@cnzakimuena I am trying the same with Embedded java, but doesnt work for me. Same error !

Could you share me your config files

**Comment by cnzakimuena** [comment]
![screenshot](https://user-images.githubusercontent.com/35876258/118388760-5523f680-b5f4-11eb-9b7f-fe35b766ff04.png)
@alihabib-in do you mean one of these

**Comment by alihabib-in** [comment]
No I meant, this file "refine.ini"

Also, what is the Java Version on your system now ?

**Comment by alihabib-in** [comment]
![image](https://user-images.githubusercontent.com/5759454/118389044-03518f80-b639-11eb-9e44-d4034e185df9.png)

When I run refine, it shows me this.

**Comment by cnzakimuena** [comment]
I have Java version 16 on my system.
The error you show is what I was seeing as well.
[refine.txt](https://github.com/OpenRefine/OpenRefine/files/6494043/refine.txt)

**Comment by ahmadaldhalaan** [comment]
I am having the same issue. I have tried 3.1, 3.2, 3.3, 3.4 and 3.5 and no luck in running it. I get the same blank page with the OR logo.

**Comment by alihabib-in** [comment]
> I am having the same issue. I have tried 3.1, 3.2, 3.3, 3.4 and 3.5 and no luck in running it. I get the same blank page with the OR logo.

@

> I am having the same issue. I have tried 3.1, 3.2, 3.3, 3.4 and 3.5 and no luck in running it. I get the same blank page with the OR logo.

@ahmadaldhalaan Uninstall Java and install the embedded version of Open Refine.. it will work

**Comment by thadguidry** [comment]
@ahmadaldhalaan Can you tell us which version of Java you have installed?

**Comment by ahmadaldhalaan** [comment]
@alihabib-in That definitely worked. But what if I need Java for other applications?

@thadguidry I have Java 16.0.1. I tried OR 2.8 and it works fine with it.

**Comment by thadguidry** [comment]
@ahmadaldhalaan Thanks so much for that info!
@wetneb This should help us look to improve things for OR 3.x knowing that Java 16.0.1 worked fine with OR 2.8

**Comment by ylan1** [comment]
Hello, the collective wisdom of the OR community! 
Until recently (three/four weeks ago?), I was actively using OpenRefine. A week ago, I found that I was unable to run OR 3.4.1. The webpage (http://127.0.0.1:3333/) was loading only the logo as described by @wentianq above. I believe it worked fine with my JDK 16.0.1. previously.  I had other issues with my computer; coincidentally, I think it started with being unable to run OpenRefine, so ended up reinstalling Windows.  Today I tried to reinstall OR 3.4.1. Tried both the default version the version with java. I am using Windows 10 and tested with both Firefox and Chrome. I am wondering if I have set the environment variables wrong. I have also tried with JAVA_HOME set with jdk-11.0.12.  

I am really not sure what is going on. Previously when it was working well, I don't even recall setting the environment variable. It just worked fine. Could you please help? OR has been so useful for my research that I feel devastated that it suddenly stopped working.  Before the problem happened, the only change I made to my computer was installing Jena Fuseki and apache-Jena-4.1.0, and Tableau Desktop. At least, that is what I think. Please help! 

![image](https://user-images.githubusercontent.com/77898472/129512308-4d00ae74-6af8-4cce-81ba-4d8bc509df4b.png)
![EV](https://user-images.githubusercontent.com/77898472/129512672-7c218733-58cd-41a5-93d6-4f6d12b928fb.PNG)

**Comment by thadguidry** [comment]
@ylan1 Try this:
1. Make a new folder for the OpenRefine workspace.  Something like `C:\openrefine_workspace`
2. Follow [our instructions in our Docs](https://docs.openrefine.org/manual/installing#set-where-data-is-stored) to point OpenRefine to use that new workspace folder.
3. Launch OpenRefine and let us know.

**Comment by ylan1** [comment]
@thadguidry
Many thanks for your prompt reply and suggestions. I am still having trouble running the OR. According to [the instruction](https://docs.openrefine.org/manual/installing#set-where-data-is-stored), am I supposed to create a folder C:\openrefine_workspace then edit the openrefine.l4j file like this?  
![refine1](https://user-images.githubusercontent.com/77898472/129637182-465e5c11-1c6e-4a92-828d-ccd0644034dc.PNG)
Anyway, this did not work for me. So now I am trying to run the version 3.4.1 with Java. And I am getting the same blank screen with the logo. 
![cmd](https://user-images.githubusercontent.com/77898472/129637407-ce242b7d-98a7-4b17-8b5a-7cbf19f73bd0.PNG)
The console is displaying the same error that I saw before:
![error](https://user-images.githubusercontent.com/77898472/129637532-0a7d5ab9-5a2b-45a4-926f-9a9e856dafbd.PNG)

I really appreciate any help you can provide.

**Comment by thadguidry** [comment]
@ylan1 OK, so we now have proof in the Windows terminal, last line, that it sees and is using a new workspace folder. Great!

Now the next thing is the error in the browser console which is worrying, because it leads me to think it cannot find some Java classes, but that's likely not the real underlying issue since it clearly load the Java classes for OpenRefine because they are used and produce logging output in the Windows terminal !

1. Can you use safe mode in the browser ([look up on the web](https://www.google.com/search?client=firefox-b-1-d&q=firefox+safe+mode) how to do that for your browser - this will disable temporarily any plugins) and try again?
2. Perhaps try installing OpenRefine into a folder under `C:\Program Files` ?  (You can get permission blocked for certain apps installed directly on C:\ drive in Windows, and so it's usually best to install on another drive or under the regular `Program Files` or `Program Files(X86)` folders.

Finally,
3. what is the output in a Windows terminal for the command such as `C:> java -version`
4. what is the output in a Windows terminal for the command such as `C:> echo %PATH%`

**Comment by ylan1** [comment]
@thadguidry 
Thanks again for your help. Now my OpenRefine is under C:\Program Files. But I still cannot run it, and it is not using a new workspace folder I created; when it was under C:\ it at least had C:\openrefine_workspace (0ms) and generated workspace JSON file. 
![17_8_21](https://user-images.githubusercontent.com/77898472/129801251-a7d89dc4-c6bf-4911-a606-2516244d6873.PNG)
Using Chrome safe mode: 
![safemode](https://user-images.githubusercontent.com/77898472/129801365-7178aac4-b97c-4481-8a84-89c355c6e592.PNG)
Windows terminal output for java and path: 
![java](https://user-images.githubusercontent.com/77898472/129802095-f9b9b9ab-3be4-4538-81a7-8673124fa97d.PNG)
Do you think I should uninstall java and try again since I am using the Windows Kit with embedded Java version? 
Many thanks in advance!

**Comment by thadguidry** [comment]
Since this is a closed issue, Let's move this conversation to a similar bug report #4106 
and then try what I suggested in my last comment within it and let's continue troubleshooting in that same issue with the other user have the exact same problem.
