### ISSUE TITLE
Wikidata schema edit in the Japanese language setting doesn't work properly.

### ISSUE THREAD

**Issue by yayamamo** [OpenRefine/OpenRefine#1738]
**Describe the bug**
When I edit Wikidata schema in the language setting of Japanese, any property cannot be suggested.

**To Reproduce**
1. Go to 'Language Settings'
2. Choose '日本語' and click 'Change Language'
3. Click on 'クリップボード' (= 'Clipboard')
4. Follow the instruction explained at [this tutorial](https://www.wikidata.org/wiki/Wikidata:Tools/OpenRefine/Editing/Tutorials/Inverse_Listeria).
5. When typing in 'patronage' as a property of a statement, you see nothing is suggested.
Even if you type in '利用者数', a Japanese label of the patronage property ([P3872](https://www.wikidata.org/wiki/Property:P3872)), the result doesn't change.

**Current Results**
Nothing suggested.
If I type in 'P3872', OpenRefine suggests 'SPARQL: P3872', which might work properly, but it is not helpful for human.

**Expected behavior**
OpenRefine is expected to suggest properties as in the language setting of English.

**Screenshots**

![2018-09-17_openrefine](https://user-images.githubusercontent.com/995225/45630304-5fa03200-bad3-11e8-9d19-943c60d8ef6b.png)

**Desktop (please complete the following information):**
 - OS [Windows 10]
 - Browser Version: [Chrome 69.0.3497.92]
 - JRE or JDK Version:[JRE 1.8.0_171]

**OpenRefine (please complete the following information):**
 - Version [e.g. OpenRefine 3.0]

**Datasets**
[List of metro systems](https://en.wikipedia.org/wiki/List_of_metro_systems) referred from [this tutorial](https://www.wikidata.org/wiki/Wikidata:Tools/OpenRefine/Editing/Tutorials/Inverse_Listeria)

**Additional context**

**Comment by wetneb** [comment]
@yayamamo thanks! The good news is that this seems to be a bug of the reconciliation service, not OpenRefine itself, so we can fix that even if we just made a release.

**Comment by wetneb** [comment]
In fact it is not a bug in the reconciliation service: the bug was introduced by an anonymous translator who changed the language code for Japanese (currently is `jp`, should be `ja`). So I'll fix this in OpenRefine and introduce a silent mapping in the reconciliation service so that users do not have to upgrade anything.
