### ISSUE TITLE
Feature request: "Anonymise Names" text transformation

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#174]
_Original author: mcnamara.tim@gmail.com (November 01, 2010 21:22:25)_

What feature would you like?
I would like to quickly be able to anonymise text in cells. While this is outside the original scope of Refine, e.g. cleaning &amp; inputting data into Freebase, it would be a valuable transformation for agencies that are attempting to release sensitive info.

Here is a naive approach:
- split the string into n-length characters
- replace each letter with a randomly chosen letter, retaining the case
- join characters together as a string

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=174_
##

**Comment by wetneb** [comment]
I don't think this is in the scope of the project. And it's very old.

**Comment by thadguidry** [comment]
This could be an OpenRefine extension to determine risk of PII leakage and give users options for anonymizing data with various algorithms.  See feature enhancement request #5642
