### ISSUE TITLE
new version does not work in my computer

### ISSUE THREAD

**Issue by skyarchers** [OpenRefine/OpenRefine#1740]
hello every one!
i can use version 2.8 in my computer but cannot use the new version. it is my computer or the new version's problem. i want to use the new version~~

**Comment by wetneb** [comment]
Hi @skyarchers, can you tell us what operating system and java version you have. What exactly do you get when trying to launch the new version?

**Comment by thadguidry** [comment]
@skyarchers Also, if you run the refine.bat (if you are on Windows) you can attach the support.log to this issue (new in 3.0)

**Comment by skyarchers** [comment]
web site http://127.0.0.1:3333/ cannot be opened after run the new version openrefine.exe.
stop at "receiving method for GET"
win 10
java version 8

**Comment by wetneb** [comment]
@skyarchers could you provide a screenshot of the issue?

**Comment by skyarchers** [comment]
At 2018-09-18 23:48:40, "Antonin Delpeuch" <notifications@github.com> wrote:


@skyarchers could you provide a screenshot of the issue?

**Comment by wetneb** [comment]
@skyarchers I assume you attached the screenshot to your email - unfortunately that does not work - you need to go on GitHub and attach it from there.

**Comment by skyarchers** [comment]
![1](https://user-images.githubusercontent.com/43224436/45705285-bc6f1b80-bbab-11e8-9586-24134acadc93.JPG)

**Comment by skyarchers** [comment]
![default](https://user-images.githubusercontent.com/43224436/45705302-d14baf00-bbab-11e8-96ea-615157dc3dfc.JPG)

**Comment by wetneb** [comment]
@skyarchers thanks, it is a known bug (#1717).

**Comment by jackyq2015** [comment]
put the fix in master. will release at V3.1. Or you can apply  PR #1745  before the release
