### ISSUE TITLE
Illegal reflective access from jython/python

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#1741]
We'll need to be aware of an issue with Jython (my test was with Jython 2.5.x standalone jar)
when using Java 9+
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.google.common.base.internal.Finalizer
(file:/E:/openrefine/webapp/extensions/jython/module/MOD-INF/lib/jython-standalone-2.5.4-rc1.jar)
to field java.lang.Thread.inheritableThreadLocals
WARNING: Please consider reporting this to the maintainers of org.python.google.common.base.internal.Finalizer
WARNING: Use --illegal-access=warn to enable warnings
of further illegal reflective access operations
```
I've opened an issue at http://bugs.jython.org/issue2705

where Jeff Allen has responded with the following:
-
Jeff Allen <ja.py@farowl.co.uk> added the comment:

It's the same problem in general as http://bugs.jython.org/issue2656 , arising from Java 9+. We aim to eliminate these from Jython 2.7.2, which I expect we shall release this year. The project has insufficient effort to go back to 2.5.x with fixes, so your route out is via 2.7.x, or stick at Java 8.

A 2.7.0 or 2.7.1 would not be better from this perspective right now, but if you were to use them experimentally it would help prepare your code (and make a step towards a hoped-for 3.x). If non-english text is important to you, as it seems it might, you'll find good and bad here, with str support for UTF-16 gone/broken and increasing conformance to the Python 2.7 model as we go on.

The org.python prefix is the result of repackaging Google code with jarjar as a way to manage dependence on a particular version. However, I feel sure that if you launched with --illegal-access=warn, there would be many others.

keywords: +Java Roadmap
nosy: +jeff.allen
resolution:  -> wont fix
status: open -> pending

**Comment by tfmorris** [comment]
This says the fix is Jython 2.7.2, which we have now, so I'm going to close this.
