### ISSUE TITLE
Feature request: add anonymising numeric transformation

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#175]
_Original author: mcnamara.tim@gmail.com (November 01, 2010 21:26:54)_

I would like to be able to anonymise data sets by adding fuzziness. This would involve a numeric transformation that (largely) retains aggregate function results, but alters each datum slightly.

Rough example of desired result:

 5.0 =&gt; 5.1
 4.0 =&gt; 3.9
 5.0 =&gt; 5.0
 5.0 =&gt; 4.9

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=175_
##

**Comment by wetneb** [comment]
This is too specific and clearly outside the scope of this software, as argued above.
