### ISSUE TITLE
Why openrefine run so slowly?

### ISSUE THREAD

**Issue by skyarchers** [OpenRefine/OpenRefine#1751]
I have a dataset contains 34000 rows. Each time I run oenrefine to deal with It, It will take a long time to open the object, open the facet. it is very time consuming. What's the problem. I think the dataset is not very big.

**Comment by wetneb** [comment]
@skyarchers did you try to increase the available memory? See https://github.com/OpenRefine/OpenRefine/wiki/FAQ%3A-Allocate-More-Memory

**Comment by ostephens** [comment]
Can you given any more information about the dataset? How many columns, overall file size, is it all rows or are you using records mode? All these things could affect speed.

Also - how many unique values are you expecting in the facet?

**Comment by skyarchers** [comment]
The excel file  is 10MB, and has 25 columns, 33971 rows.   I have increase the maximun available memory to 2048M, and the openrefine runs a little faster. Can I set the max available memory to 3072M.

**Comment by thadguidry** [comment]
@skyarchers We have Windows, Mac, and Linux instructions for giving more memory to OpenRefine on our FAQ page https://github.com/OpenRefine/OpenRefine/wiki/FAQ%3A-Allocate-More-Memory

**Comment by skyarchers** [comment]
Thanks！
