### ISSUE TITLE
Error on First Use of a Facet

### ISSUE THREAD

**Issue by scottythered** [OpenRefine/OpenRefine#1756]
version: OpenRefine 3.0
OS: Windows 7E
Browser: Chrome
Java: jre1.8.0_66

![image](https://user-images.githubusercontent.com/11927373/46494276-168cf500-c7d8-11e8-9993-ceb7c27a404b.png)

I'm seeing the terminal post an error with v3.0. It happens whenever I start a new project -- I can edit cells, move columns, etc, but the first time I try to create a facet, I get the above error and the "Working" screen keeps turning over. If I reload the browser page and try the facet again, it works. It seems to affect all facet types, but only the first time one is created.

Checked on Linux version 3.0, and not seeing the same behavior.

**Comment by thadguidry** [comment]
This looks like its an issue in the DERI RDF extension version you are using.
This might be easily fixed if you use the newest version under here ? https://github.com/stkenny/grefine-rdf-extension/releases

Correct @stkenny ?

**Comment by scottythered** [comment]
Ah! I had no idea there was a new version. I was under the impression that the RDF extension had been abandoned?

**Comment by thadguidry** [comment]
You can see the semi-complete list of extensions on our Downloads page and scroll down (notice we have both versions of RDF extension) http://openrefine.org/download.html#list-of-extensions

**Comment by jackyq2015** [comment]
I am wondering if there is a good practice to maintain the interface between the core and plugin in a way that can allow the core part change without breaking plugin. Or Openrefine's plugin mechanism is too rigid to extend.

**Comment by thadguidry** [comment]
@jackyq2015 I don't see why not...that was the whole idea of the command/operations partitioning that David did...I further recall that plugins would be able to use and extend operations... that would be done through the AbstractOperations ?? and the idea was simple in practical terms... core + op  https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/operations/OperationRegistry.java#L74

Question is:  if it is abstracted enough, and can even create/use custom metadata during a plugin's abstracted operations ?

**Comment by ostephens** [comment]
In another piece of s/w I’ve written extensions for the extension was required to state a version compatibility which would be used by the main s/w to decide whether to load the extension or not. 

Would this be an approach we could take with OR?

**Comment by wetneb** [comment]
@ostephens sure, that would make sense, but that would probably require tweaking Butterfly, I think.
Rather than trying to fix this obsolete and unmaintained library I would prefer migrating to something standard like Spring.
