### ISSUE TITLE
Add JSON-LD support

### ISSUE THREAD

**Issue by msaby** [OpenRefine/OpenRefine#1758]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
It could be nice to add a JSON-LD importer, for semantic data stored in that format. In OR v3, you can import JSON-LD data with the JSON importer, but it wont be parsed as semantic data, whereas XML/RDF data is parsed as semantic data, and not imported as ordinary XML.

**Describe the solution you'd like**
With the same "semantic" dataset expressed in different format (RDF/XML, N3, Turtle, JSON-LD...) we should get the same result in Openrefine.
From UX point of view, maybe we could rename the importer menu "Semantic data" with options : "Semantic data (RDF/XML)", "Semantic data (JSON-LD)", etc., to make it clear that it is not ordinary JSON and XML data?

**Describe alternatives you've considered**

**Additional context**

**Comment by ostephens** [comment]
Hi @msaby - thanks for this.

I've done some quick testing, and it looks like adding support for import JSON-LD is trivial.
We could also easily add support for Turtle / *.ttl files

I'm happy to work on adding this support

I don't completely understand what you mean when you sa:

> From UX point of view, maybe we could rename the importer menu "Semantic data" with options : "Semantic data (RDF/XML)", "Semantic data (JSON-LD)", etc., to make it clear that it is not ordinary JSON and XML data?

Do you mean just changing the labels on the import screen in the "Parse data as" section?
<img width="410" alt="screen shot 2018-10-27 at 05 46 06" src="https://user-images.githubusercontent.com/576174/47599720-c0ad0680-d9ab-11e8-8cf3-ac3733d1e08a.png">

I'm not so keen on using the term "Semantic data" here as that seems quite a general label. The approach so far is to use the file format, and my first thought is to keep to that approach. Have I misunderstood what you mean here? Could you give an example?

Thanks

**Comment by msaby** [comment]
Well, the "semantic data" idea is probably a bad one... Implementing JSON-LD import is sufficient

**Comment by ostephens** [comment]
Done! See #1783

**Comment by wetneb** [comment]
@msaby if you get a chance to try OpenRefine from the master branch and check that it works for you, it would be great! We will soon make a new release.
