### ISSUE TITLE
Reconcile (extension or enhancement) between 2 projects

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#176]
_Original author: thadguidry (November 03, 2010 16:51:24)_

It would be useful to perform reconciling between 2 projects themselves.
Currently, cross() function helps, but even better would be to use both ngram() and cross() to look at potential matches, For example, say within an address field, where 2 projects use different site_ids or site_names but have essentially the same address, city, state, zip that is easily discernible as an exact match with human eyes, and the only difference is in each project's unique identifer, site_id, or site_name, person name whatever.

The missing piece, I think is perhaps wiring up a better interface for accomplishing this, via an extension or enhancement.

The interface would allow to display ONLY the fields chosen and needed to apply human judgement to reconcile the 2 projects rows/records and use a cross() ngram() whatever function to find very close potential matches for the user to review.  A new column would be created in both projects that allows to show the 'synced' or 'matched' row indexes from each corresponding project.  Essentially a layman's &quot;matchmaker&quot; interface with only wiring up between comparative columns in the 2 projects that the user wishes to inspect, and also the new column name that the user wants to use to hold his 'syncs' or 'matches'.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=176_

**Comment by wetneb** [comment]
Let's close this in favour of #2003, as it is more visible because more recent, maybe?

**Comment by thadguidry** [comment]
@wetneb Agreed.
