### ISSUE TITLE
Apache subdomain and ProxyPass to 127.0.0.1 url issue

### ISSUE THREAD

**Issue by ralcazar-oeg** [OpenRefine/OpenRefine#1766]
I'm running a open refine instance in a subdomain like http://refine.domain.com/ and it works like a charm. ubuntu server 16.04 with apache and a ProxyPass from the subdomain to http://127.0.0.1:3358

no_proxy="localhost,127.0.0.1"
REFINE_PORT=3358
#REFINE_HOST=127.0.0.1
#REFINE_WEBAPP=main\webapp

It's accessed from our internal network and other external network, so multiple students can access and share it in the same instance.

Permalink points correctly to our subdomain http://refine.domain.com/project?project=213154...etc and is accessed fine

The problem occurs when we reconciliate csv data with dbpedia. It works perfect, but the url changes. Records (borough) points to http://127.0.0.1:3358/extension/rdf-extension/services/dbpedia/view?id=http://dbpedia.org/resource/The_Bronx 

instead of 
http://refine.domain.com/extension/rdf-extension/services/dbpedia/view?id=http://dbpedia.org/resource/The_Bronx (this url forward it to http://dbpedia.org/page/The_Bronx)

I'm not sure if the solution has to be applied in the apache proxy or If I should hardcode the subdomain name in openrefine with a parameter

Any help with this will be appreciated. Thanks.

**Comment by wetneb** [comment]
Thanks for the report! However this seems to be an issue with the RDF extension rather than OpenRefine itself. Could you report it in this repository instead?
https://github.com/stkenny/grefine-rdf-extension

**Comment by ralcazar-oeg** [comment]
Thank you for your answer. 
I think that the solution could be adding a variable in refine.ini file that resolve between 127.0.0.1 and the subdomain, but not sure how to code it, and some attemps that I tried not solve the problem

I'll open this issue in the rdf repo extension. If I find a solution I'll post it here to help others with this issue.

**Comment by tfmorris** [comment]
Closing because it's an RDF extension issue, not ours.
