### ISSUE TITLE
Save and restore Wikidata schemas easily

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1776]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**

It would be convenient to have a library of favourite schemas, just like favourite expressions, that could be reapplied easily to a project.

**Comment by ostephens** [comment]
Related (possibly) it would be really helpful to be able to export/import schemas. On import if columns used in the schema were not present it would need to import the schema without those values mapped.

This would make it easy to share schemas with others making it easier for people to work towards a common data standard (at the moment I'm sharing whole projects with the schema setup, and others then have to copy my examples).

**Comment by wetneb** [comment]
Yeah, what I was advising at the hackathon was just to copy the JSON of the operation that saves the schema (and apply it on another project), but that's a bit convoluted.
