### ISSUE TITLE
String values in Wikidata statements and terms should be trimmed automatically

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1781]
**Describe the bug**
Currently, the Wikidata extension shows warnings when strings have leading or trailing spaces. These warnings should be removed and the strings should be trimmed by default.

**Comment by ostephens** [comment]
Possibly this should trim any non-printing characters rather than just spaces?

**Comment by wetneb** [comment]
@ostephens I'm not sure about non-printable characters, maybe they indicate some underlying encoding problem? I don't know, I haven't encountered the problem very often.

**Comment by ostephens** [comment]
You maybe correct - I've seen issues with invisible characters in Wikidata labels (e.g. I had to do an edit to remove a unicode control character at d https://www.wikidata.org/w/index.php?title=Q42307623&direction=prev&oldid=744504811)  - but the issue wasn't introduced by an OpenRefine edit afaik
