### ISSUE TITLE
Find a way to report failures of item creations for new editors in Wikidata extension

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1782]
**Describe the bug**
It seems that some new item creations are blocked for new editors. Maybe we should just slow down the edit rate to help with that (check needed with Wikidata admins).
We need a way to report creation failures to the user - for now we need to look up the logs but they are not always easily available (for instance when running OR on a mac).

**Comment by wetneb** [comment]
One possibility would be to add a new column containing the editing errors, when they happen.

**Comment by madham32** [comment]
Hi! Can I try working on this issue? :)

**Comment by madham32** [comment]
Could you tell me how to reproduce these errors?

**Comment by wetneb** [comment]
You could create a fresh Wikidata account, without any edits, and then try to [create a new wikidata item from OpenRefine itself](https://www.wikidata.org/wiki/Wikidata:Tools/OpenRefine/Editing/New_items).

If you already have a Wikidata account, make sure you are logged in with your existing account when you sign up for a new account. This will make sure both accounts are linked and the system recognizes them as belonging to the same person (to avoid breaching the policy on multiple accounts).

In general there are many other reasons why Wikidata edits might be rejected - this ticket could be broadened to improve the reporting of these errors in general.
For instance, if you try to create an item whose English label and description are identical to those of another item, this should be rejected as well (I think).

**Comment by wetneb** [comment]
Cc @darecoder1999 who is interested in this issue

**Comment by antoine2711** [comment]
I get this error on the back-end. I would like to see that in the front-end.
```
01:15:49.130 [                   refine] POST /command/wikidata/perform-wikibase-edits (4ms)
01:15:49.131 [..mWikibaseEditsOperation] Performing edits (1ms)
01:15:49.131 [..ting.EditBatchProcessor] Requesting documents (0ms)
01:15:49.515 [..ting.EditBatchProcessor] MediaWiki error while editing [modification-failed]: Item [[Q111909481|Q111909481]] already has label "puppet" associated with language code en, using the same description text. (384ms)
01:15:49.793 [..ting.EditBatchProcessor] MediaWiki error while editing [modification-failed]: Item [[Q111909481|Q111909481]] already has label "puppet" associated with language code en, using the same description text. (278ms)
01:15:50.077 [..ting.EditBatchProcessor] MediaWiki error while editing [modification-failed]: Item [[Q111909481|Q111909481]] already has label "puppet" associated with language code en, using the same description text. (284ms)
01:15:50.312 [..ting.EditBatchProcessor] MediaWiki error while editing [modification-failed]: Item [[Q111909481|Q111909481]] already has label "puppet" associated with language code en, using the same description text. (235ms)
01:15:50.312 [..ting.EditBatchProcessor] Failed to rewrite update on entity http://www.wikidata.org/entity/Q111909132 (reconciled from 3639232596724826008). Missing entity: new item (reconciled from -6554086159627687270). Skipping update. (0ms)
```

Regards, Antoine

**Comment by wetneb** [comment]
@antoine2711 what do you think about #5944?
