### ISSUE TITLE
OpenRefine hangs on 'Initializing context' When Running on OpenStack

### ISSUE THREAD

**Issue by psychemedia** [OpenRefine/OpenRefine#1797]
I'm trying to run OpenRefine inside an OpenStack Linux virtual machine ported from a Virtualbox Linux VM.

Things work fine in the Virtualbox VM but in OpenStack the launch hangs on the initialisation step:

```
21:39:31.445 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
21:39:31.446 [            refine_server] refine.memory size: 1400M JVM Max heap: 1407188992 (1ms)
21:39:31.455 [            refine_server] Initializing context: '/' from '/opt/openrefine-3.0-beta/webapp' (9ms)
```

At this point it hangs...

Config: OpenJDK 1.8.0_171, openrefine-3.0-beta
(I can't update versions in the VM for now...)

Any pointers as to how I can debug this further, or what the issue(s) might be?

I can run other services and see them via http over an internet connection, although I can't see out to the internet from inside the box (eg `ping` etc doesn't work), so I suspect I also have a network issue somewhere.

**Comment by psychemedia** [comment]
I left it >10 mins and it seemed to get going itself... 

So: any ideas why it should take a significantly long time to start running on first run? (It seems to get going okay on later runs.)

**Comment by psychemedia** [comment]
Hmmm... experimenting with a Docker container as part of a docker-compose config and once again OpenRefine just hangs, not getting further than:

```
refine_container | /usr/lib/jvm/java-1.8-openjdk/bin/java -cp server/classes:server/target/lib/*   -Xms1400M -Xmx1400M -Drefine.memory=1400M -Drefine.max_form_content_size=1048576 -Drefine.verbosity=info -Dpython.path=main/webapp/WEB-INF/lib/jython -Dpython.cachedir=/root/.local/share/google/refine/cachedir -Drefine.data_dir=/mnt/refine -Drefine.webapp=main/webapp -Drefine.port=3333 -Drefine.host=0.0.0.0 com.google.refine.Refine
refine_container | Starting OpenRefine at 'http://0.0.0.0:3333/'
refine_container | 
refine_container | 22:12:34.364 [            refine_server] Starting Server bound to '0.0.0.0:3333' (0ms)
refine_container | 22:12:34.368 [            refine_server] refine.memory size: 1400M JVM Max heap: 1419116544 (4ms)
refine_container | 22:12:34.393 [            refine_server] Initializing context: '/' from '/openrefine-3.1/webapp' (25ms)
```

**Comment by psychemedia** [comment]
Okay, I think the issue is that the hanging was a server memory issue.

Anyone know what the minimum spec server that OpenRefine will reliably run on and what the start / config parameters for OR are in such a case?

With the -1400M default and a 2GB machine I got the hanging situation above. 3Gb seems okay.

**Comment by nguaman** [comment]
I have this same issue.
Openrefine 3.2 with 7 GB de ram. 



`guaman@openrefine:~$ ./openrefine-3.2/refine -m 4000M -i 0.0.0.0 -p 80
You have 7473M of free memory.
Your current configuration is set to use 4000M of memory.
OpenRefine can run better when given more memory. Read our FAQ on how to allocate more memory here:
https://github.com/OpenRefine/OpenRefine/wiki/FAQ:-Allocate-More-Memory
Starting OpenRefine at 'http://0.0.0.0:80/'

13:05:53.262 [            refine_server] Starting Server bound to '0.0.0.0:80' (0ms)
13:05:53.315 [            refine_server] refine.memory size: 4000M JVM Max heap: 3728736256 (53ms)
13:05:53.453 [            refine_server] Initializing context: '/' from '/home/guaman/openrefine-3.2/webapp' (138ms)


`

**Comment by freedev** [comment]
I'm having same issue here 128GB/16 cores. Anyone know what's happening?

**Comment by thadguidry** [comment]
@freedev Try removing all OpenRefine extensions temporarily to see if it still hangs?  You can join our https://forum.openrefine.org where we'll be able to help you further.  See you there!

**Comment by thadguidry** [comment]
Closing this issue as not really actionable for our team.  And we have limited resources to try to reproduce exact user environments where this issue seems to stem from.  We'll be more than happy to provide help and support on the forum.
