### ISSUE TITLE
Editing single blank cell and applying to identical cells does not work affect other blank cells

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#180]
_Original author: dfhu...@google.com (November 05, 2010 17:15:12)_

Click edit on a blank cell, enter something, and click Apply to identical cells. That does not affect other blank cells.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=180_

**Comment by ostephens** [comment]
Just an update - I'm working on this and work in progress is at https://github.com/ostephens/OpenRefine/tree/mass-edit-fix

tl/dr fix #1631 is relatively straightforward, but I'm trying to make tests and fix #1632, #180 and #332 at the same time which is proving more complicated and taking more time

**Comment by ostephens** [comment]
Fixed by #1642
