### ISSUE TITLE
incompatible with http2

### ISSUE THREAD

**Issue by davidegiunchidiennea** [OpenRefine/OpenRefine#1817]
**Describe the bug**
If you put a reverse proxy in front of open refine, a reverse that speak **http2** with the outsite word, openrefile will run very slow for every set of GET requests, and sometimes you will get 503 errors.
If i disable http2, to return to http1.1, the problem disappear.

**To Reproduce**
1. install a reverse proxy like nginx, with a configuration like:  
`
server {
        listen  *:443 ssl http2;
        server_name openrefine.locale.lan;
			
        ssl_certificate      /etc/nginx/conf.d/my.cer;
        ssl_certificate_key  /etc/nginx/conf.d/my.key;

        location / {
                proxy_pass         http://127.0.0.1:3333/;
        }
}
`
please note that nginx speaks http2 with the outsite word (browser), but http1.1 with the backend openrefine server (on http://127.0.0.1:3333/).
2. open a browser to https://localhost
3. in the first page you will get some "waiting..", the whole page will be loaded with a delay of ~30-50s.
If you open a Developer Tools, you will se that some files are not loaded immediatly but only after a delay of ~30-50s. Take a look at the attached file.  

**Current Results**
Even the first page is delayed of ~30-50s, sometimes you will get 503 errors.

**Expected behavior**
Normal loading time of max 3s for the first page.

**Workaround**
1. On Firefox go to about:config, and set to false "network.http.spdy.enabled.http2"
2. On nginx or the reverse proxy, disable the http2, by changing the configuration to:
`
server {
        listen  *:443 ssl;
        server_name openrefine.locale.lan;
			
        ssl_certificate      /etc/nginx/conf.d/my.cer;
        ssl_certificate_key  /etc/nginx/conf.d/my.key;

        location / {
                proxy_pass         http://127.0.0.1:3333/;
        }
}
`
(i've removed the *http2*).
With these two workaround, openrefine is fast as normal.

**Screenshots**
![openrefine-broken-ok](https://user-images.githubusercontent.com/13944397/48195337-aed64680-e34f-11e8-8b5c-d3712dff9a73.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 7 or Windows 10, but not limited to
 - Browser Version: Firefox 63.0.1 (64-bit), Chrome 70.0.3538.77 

**OpenRefine (please complete the following information):**
 - Version OpenRefine 3.0
 - Java Version: 8u181 (i'm using the docker image openjdk:8-jdk-slim-stretch)

**Comment by wetneb** [comment]
Thanks for the report! I think this should be solved by migrating to a modern web framework.

**Comment by wetneb** [comment]
In 4.x I have upgraded Butterfly to use Jetty 9 which supports HTTP 2, I am not sure if this will automatically solve this though.

**Comment by tfmorris** [comment]
It's not at all clear to me from the evidence that this is an OpenRefine issue as opposed to an nginx issue. The original report says that nginx is speaking HTTP 1.1 to OpenRefine, so HTTP 2 support shouldn't be a factor.

But, for those who come across this due to the HTTP 2 mention, OpenRefine upgraded to Jetty 9 in March 2021 (0f024d833ee2e4ae3272b940e652bfac40bac76c).

I'm going to close this since it's old and involves external components, but feel free to reopen with additional supporting evidence that demonstrates the problem with a recent version on OpenRefine.
