### ISSUE TITLE
Access to project metadata

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#182]
_Original author: dfhu...@google.com (November 05, 2010 17:43:25)_

It would also be useful to be able to access some of the metadata about the project from within the project itself (in the exporters), to create some provenance traces. E.g., being able to indicate the name of the project, the file that was imported, what options were used when it was imported and so on.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=182_
##

**Comment by wetneb** [comment]
Related to #1221.
