### ISSUE TITLE
After splitting the column into multiple column then data getting mismatch 

### ISSUE THREAD

**Issue by vineetharkut** [OpenRefine/OpenRefine#1821]
**Describe the bug**
I have doubt on the get-rows & get-models api because initially the get-rows and get-models return the same number of count but after splitting the column into multiple column the get-rows and get-models return the different number of count. I mean to say i have dataset where initially number of column is 34 and get-rows return 34 records for each rows that fine but after splitting the column the get-models returning 36 column count which is correct but get-rows is returning 35 records for each rows, so because of that there is mismatch happening the dataset.

**To Reproduce**
1. Load the file 
2. check the get-models api and note the number of column count
3. check the get-rows api and note the number of records count for each rows
4. click on drop down menu select edit column
5. click on splitting column into several column option
6. split any column
7. After splitting now check the get-model api and note the number of column count
8. check the get-rows api and note the number of records count for each rows

**Expected behavior**
I was expecting as the initially get-models api returning the same number of column count and as well as get-rows api returning the same record count for each row which is correct and even after splitting the column also the api should return same number of row & column count, so that there should not be any mismatch in dataset. I dont 'know how open refine team is managing that as i can see there is difference in count.

**Screenshots**
I am sharing a [video link](https://drive.google.com/file/d/1qo1o65Y1ocxMvli5dW7CkOm7gBrOLbsw/view?usp=sharing) for better understand what i want to say.

Please help out on the above scenario. If i am doing any mistake then correct me.

Thanks

**Comment by wetneb** [comment]
Closing as not reproducible.
