### ISSUE TITLE
Why get-models api after splitting the column does not return the column type with some value even click on "Guess cell type" while splitting the column

### ISSUE THREAD

**Issue by vineetharkut** [OpenRefine/OpenRefine#1825]
**Describe the bug**
I have doubt before splitting the column the get models api return various parameter in which one parameter is type to know the data type of the column which is fine but after while splitting the column there is an option Guess the cell type"even checking that option hoping that in get models response after splitting the new column will also return the type parameter with some value (string/number/so on) but it return the type as blank value.

**To Reproduce**
1. Upload the data set 
2. Click on create project
3. After creating the project check the get-models api response particularly the type parameter
4. Split any column remember to checked Guess cell type option and click on ok
5. After splitting check the get-models response particularly the type parameter

**Expected behavior**
As before splitting i am getting the type parameter with some value which predict the data type of the column even after splitting the column (clicking on Guess cell type while splitting) the response should return type with some value but right now it is returning with blank value.  

**Screenshots**
Before splitting the column the type parameter
![type-before-splitting](https://user-images.githubusercontent.com/34603714/48531468-56a8c280-e8c2-11e8-93f3-3ffe25933e73.png)

After splitting (while splitting i have checked Guess cell type) the column the type parameter
![type-after-splitting](https://user-images.githubusercontent.com/34603714/48531242-7db2c480-e8c1-11e8-93c0-8b51eb5ba595.png)

**OpenRefine (please complete the following information):**
 - OpenRefine 3.0 Beta

Even i am adding [video link](https://drive.google.com/file/d/1AjhFp2DkF9i7wrcau1tYfTDqDEAozgMo/view?usp=sharing) for better understanding.

**Comment by tfmorris** [comment]
Apologies for this getting ignored for so long. I'm guessing that you either found your answers or lost interest, but if you still need help let us know.

**Comment by wetneb** [comment]
The `type` parameter in column metadata is unused, it was introduced for Data Package support but without any way to make anything useful out of it.
