### ISSUE TITLE
Reconcile Biodiversity Taxon names not working in 3.0

### ISSUE THREAD

**Issue by DimEvil** [OpenRefine/OpenRefine#1828]
**Describe the bug**
Reconciliation service
"http://iphylo.org/~rpage/phyloinformatics/services/reconciliation_gbif.php" for GBIF (and the others) do still work in V2.7 but not in 3.0
i.e. no return values

**Comment by wetneb** [comment]
@DimEvil can you give an example of cell values for which the reconciliation service works in 2.7? I have tried with taxa from their database but their service returns an invalid response:
```
13:13:13.536 [    refine-standard-recon] Service error for text: Acanthobdella peledina
  Job code: {"query":"Acanthobdella peledina","type":"/biology/organism_classification/scientific_name","type_strict":"should"}
  Response: {} (0ms)
```

So it seems to me that this error does not come from OpenRefine, but from the service itself.

**Comment by DimEvil** [comment]
I double checked with this one from EOL, the GBIF one indeed does not seems to work on both versions.

 http://iphylo.org/~rpage/phyloinformatics/services/reconciliation_eol.php

*Working* EOL reconciliation
![image](https://user-images.githubusercontent.com/3965195/48628431-6bb34d80-e9b7-11e8-9258-67a334a5625b.png) 

*not working* EOL reconciliation
![image](https://user-images.githubusercontent.com/3965195/48628543-c0ef5f00-e9b7-11e8-9df2-c50b1cfe466e.png)

[Checklist_Opiliones.txt](https://github.com/OpenRefine/OpenRefine/files/2589709/Checklist_Opiliones.txt)

**Comment by wetneb** [comment]
@DimEvil thanks for the confirmation - so this is not a bug in OpenRefine. If you have any way to contact the author of the reconciliation service to get this fixed, it would be fantastic!

**Comment by DimEvil** [comment]
I could, but I don't understand that the service is working in 2.7 and not in 3.0.  So the service should be written differently?

**Comment by wetneb** [comment]
@DimEvil no we have not changed anything to the protocol.

From what I can tell, the service is NOT working with OpenRefine at all (neither 2.7 nor 3.0). I tried reconciling the file you provided in OpenRefine 2.7 (trying both GBIF and EOL) and it does not work.

If you had an existing project in 2.7 that was successfully reconciled some time ago it is possible that the service has been broken since.

At the moment the reconciliation service does not comply with the protocol described here:
https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation-Service-API

**Comment by DimEvil** [comment]
I see what happened, EOL just updated their complete site (on Nov 17 th). I was probably the last one ever who could make use of the reconciliation service in the old form.

This one is working in 3.0 (http://iphylo.org/~rpage/phyloinformatics/services/reconciliation_ncbi.php)

![image](https://user-images.githubusercontent.com/3965195/48711223-f344ca80-ec0a-11e8-9402-0f264abc976d.png)

And in 2.7
![image](https://user-images.githubusercontent.com/3965195/48711385-7108d600-ec0b-11e8-86b8-706f73bd5ec5.png)

Thnx for the effort! I agree it's not a bug in OpenRefine
