### ISSUE TITLE
./refine does not trigger a build

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1831]
**Describe the bug**
If the software has not yet been built, running `./refine` no longer automatically builds the software before running

**To Reproduce**
1. At the command line type `./refine`

**Current Results**
```
./refine
You have 5631M of free memory.
Your current configuration is set to use 1400M of memory.
OpenRefine can run better when given more memory. Read our FAQ on how to allocate more memory here:
https://github.com/OpenRefine/OpenRefine/wiki/FAQ:-Allocate-More-Memory
/Library/Java/JavaVirtualMachines/jdk1.8.0_72.jdk/Contents/Home/bin/java -cp server/classes:server/target/lib/*   -Xms1400M -Xmx1400M -Drefine.memory=1400M -Drefine.max_form_content_size=1048576 -Drefine.verbosity=info -Dpython.path=main/webapp/WEB-INF/lib/jython -Dpython.cachedir=/Users/damyantiandowen/.local/share/google/refine/cachedir -Drefine.autoreload=true -Dbutterfly.autoreload=true -Xdock:icon=graphics/icon/openrefine.icns -Drefine.webapp=main/webapp -Drefine.port=3333 -Drefine.host=127.0.0.1 com.google.refine.Refine
Starting OpenRefine at 'http://127.0.0.1:3333/'

Error: Could not find or load main class com.google.refine.Refine
```
**Expected behavior**
Expected software to attempt a build, and if successful, run refine

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.1 (18B75)
 - JRE or JDK Version:
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)

**OpenRefine (please complete the following information):**
 - Version: Latest Master
NB this works on the 3.1 Beta release, so it is a change since that point

**Comment by wetneb** [comment]
That is curious. I don't see why any of the commits since 3.1-beta introduced this - I think this is probably due to a half-built copy of OpenRefine. At the moment we detect whether OR should be built with `ls $REFINE_LIB_DIR | grep openrefine`, that can surely be improved to match your case.

Can you paste the output of `ls server/target/lib` from a copy of OR where `./refine` fails?

**Comment by ostephens** [comment]
Away from computer right now but will check later

**Comment by thadguidry** [comment]
I just tried on fresh Ubuntu install... works fine.
```
thad@DESKTOP-TJUMQT0:~/OpenRefine$ ./refine
You have 16308M of free memory.
Your current configuration is set to use 1400M of memory.
OpenRefine can run better when given more memory. Read our FAQ on how to allocate more memory here:
https://github.com/OpenRefine/OpenRefine/wiki/FAQ:-Allocate-More-Memory
ls: cannot access 'server/target/lib': No such file or directory
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.openrefine:packaging:jar:3.1-SNAPSHOT
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] OpenRefine                                                         [pom]
[INFO] OpenRefine - main                                                  [jar]
[INFO] OpenRefine - server                                                [jar]
[INFO] OpenRefine - extensions                                            [pom]
[INFO] OpenRefine - Jython extension                                      [jar]
[INFO] OpenRefine - Wikidata extension                                    [jar]
[INFO] OpenRefine - Database extension                                    [jar]
[INFO] OpenRefine - Gdata extension                                       [jar]
[INFO] OpenRefine - PC-axis extension                                     [jar]
[INFO] OpenRefine - packaging                                             [jar]
[INFO]
[INFO] ---------------------< org.openrefine:openrefine >----------------------
[INFO] Building OpenRefine 3.1-SNAPSHOT                                  [1/10]
[INFO] --------------------------------[ pom ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/build-helper-maven-plugin/1.8/build-helper-maven-plugin-1.8.pom

[snip][snip]
```

**Comment by thadguidry** [comment]
@ostephens if you are OK with losing work in there... `git reset --hard @{u}`
or you could 1st try not losing work `git reset --soft @{u}`
ref: https://git-scm.com/docs/git-reset#git-reset-emgitresetemltmodegtltcommitgt

**Comment by ostephens** [comment]
Yeah - I don't often push the master to https://github.com/ostephens/OpenRefine (I have done just now), but on my local repo I keep it up to date

When I say "copying the content of the repo": I copy the Git repo to another directory to do test builds to avoid the built files ending up in my branch. If there is a better / different way of doing this part of the workflow then I'd definitely like to learn!

Trying both git reset soft & hard still doesn't fix the problem

**Comment by wetneb** [comment]
@ostephens when I copy the repository to a different location in your computer, I find it useful to use `git clone my_old_location my_new_location` rather than an actual copy such as with `cp -r my_old_location my_new_location`. That ensures that only the files tracked in the repository get copied over. (Not sure if you are already doing that or if it fits your workflow at all of course!)

**Comment by ostephens** [comment]
Ah - I see /server/classes and others all in Git ignore - so I'm guessing that there is something in there...

Yep - removing /server/classes from my end sorts the problem

**Comment by ostephens** [comment]
So currently having any /server/classes directory stops the build even if it is empty. Not sure it is worth changing this behaviour tbh

**Comment by chetan-v** [comment]
I got this error
I do all your procedure but in my repo nothing happend

**Comment by wetneb** [comment]
Try to clean your clone with `./refine clean` maybe?

**Comment by chetan-v** [comment]
> Try to clean your clone with `./refine clean` maybe?

Thanks, but I redownload the repo 
And now it works
