### ISSUE TITLE
Cleanup the multiple SLF4j bindings

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#1832]
**Describe the bug**
SLF4J API is designed to bind with one and only one underlying logging framework at a time. If more than one binding is present on the class path, SLF4J will emit a warning, listing the location of those bindings.

**To Reproduce**
1. Run ./refine

**Current Results**
```
22:40:43.060 [            refine_server] Creating new workspace directory /home/thad/.local/share/openrefine (383ms)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/thad/OpenRefine/server/target/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/thad/OpenRefine/main/webapp/WEB-INF/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
22:40:43.095 [                   refine] Starting OpenRefine 3.1-beta [TRUNK]... (35ms)
```

**Expected behavior**
No multiple SLF4J bindings warning.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Version: Firefox latest
 - JRE or JDK Version: OpenJDK 8

**OpenRefine (please complete the following information):**
 - Version: Trunk (master)

**Additional Context**
https://www.slf4j.org/codes.html#multiple_bindings
Maybe we want to exclude as runtime dependencies in maven ? and only as compile time ?

**Comment by tfmorris** [comment]
Since that's the same JAR being found twice, it doesn't matter which one it picks, so this is purely a cosmetic issue.

**Comment by thadguidry** [comment]
@tfmorris Do we truly need both bindings however on the classpath?  I don't think so?  1 is for `main` (client) and the other is for `server`.  We could point `server` to use the one on `main`?  In multi-project builds in the enterprise, I typically see a `/commons` or `/shared` on the classpath and with Java 9+ I've see typically modules specify which packages are visible to other modules.  

Anyways, I'll leave it to the experts here to decide how to handle, or close this issue, but I'd love to get to a point where the output in the Refine console is useful for users without that "cosmetic" noise.

**Comment by wetneb** [comment]
Somehow my refactoring of the maven modules solved this in my Spark work, so I would not spend energy fixing this in 3.x.

**Comment by thadguidry** [comment]
@wetneb Oh! Great to hear!  Then let's close this.
