### ISSUE TITLE
Fix regular expression option in replace menu

### ISSUE THREAD

**Issue by msaby** [OpenRefine/OpenRefine#1834]
**Describe the bug**
(Fix coming)

The new search & replace menu (issue #1742) does not work well with "regular expression" option : \ character is escaped when it should not.

**To Reproduce**
Ex : with "regular expression" checked, replacing "x\dx" with "" gives replace(/x\\dx/,"") in GREL, instead of replace (/x\dx/,"")

**Current Results**
What results occured or were shown.

**Expected behavior**
A clear and concise description of what you expected to happen or to show.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows 10, Linux, Ubuntu 18.04]
 - Browser Version: [e.g. Chrome 19, Firefox 61, Safari, NOTE: OpenRefine does not support IE but works OK in most cases]
 - JRE or JDK Version:[output of "java -version" e.g. JRE 1.8.0_181]

**OpenRefine (please complete the following information):**
 - Version : OpenRefine 3.1 Beta

**Datasets**

**Additional context**

**Comment by thadguidry** [comment]
To be more clear, this is what is happening...

![replace](https://user-images.githubusercontent.com/986438/48673649-3cacf100-eb09-11e8-891b-7928b09c77f4.PNG)

```
[
  {
    "op": "core/text-transform",
    "description": "Text transform on cells in column Column 1 using expression value.replace(\"x\\\\dx\",\"\")",
    "engineConfig": {
      "facets": [],
      "mode": "row-based"
    },
    "columnName": "Column 1",
    "expression": "value.replace(\"x\\\\dx\",\"\")",
    "onError": "keep-original",
    "repeat": false,
    "repeatCount": 10
  }
]
```

**Comment by msaby** [comment]
Yes ;-)
I made a PR, but it does not seem to link itself with the issue

**Comment by thadguidry** [comment]
You have to put the issue # into the Comments somewhere... not the Title of the PR.  I've just updated your first comment on your PR and now it is linking just fine.
