### ISSUE TITLE
Incorrect text on Transform all columns/select columns screen

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1844]
**Describe the bug**
When selecting columns to apply transformations to from the "All->Transform" dropdown, the text on screen reads "Select and Order Columns to Export" rather than "Select and Order Columns to Transform"

This screen also contains a link labelled "Content" that does not seem to have any function

**To Reproduce**
1. Go to 'All' dropdown menu
2. Click on 'Transform'
3. Click "OK"
4. See incorrect text

**Current Results**
<img width="822" alt="screenshot 2018-11-21 at 15 31 12" src="https://user-images.githubusercontent.com/576174/48851766-bd871980-eda3-11e8-9d83-f2586c2b3503.png">

**Expected behavior**
Text should read ""Select Columns to Transform"
"Content" link should not be displayed (unless a reason for it can be defined and that action implemented)

**Comment by jenyoung** [comment]
Thanks - I thought I was the only one confused by that wording!

**Comment by ostephens** [comment]
Fixed by #1850
