### ISSUE TITLE
Delete entire row

### ISSUE THREAD

**Issue by vineetharkut** [OpenRefine/OpenRefine#1849]
Hi 

Is it possible to delete entire row like remove column feature which open refine has

**Comment by ostephens** [comment]
Removing rows can be done from the `All->Rows` dropdown menu. It removes all the rows currently selected, so to remove a single row you have to isolate that row in a facet or filter in some way.

Often starring a row, then faceting by star is the easiest approach.

**Comment by vineetharkut** [comment]
@ostephens Thanks for such quick response
