### ISSUE TITLE
Implement "inArray" from gokbUtils extension

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1853]
The gokbUtils extension includes an 'inArray' GREL command which checks for the existence of a value in an array. This request is to migrate that function, as currently implemented in gokbutils into the core product

 https://github.com/ostephens/refine-gokbutils

**Comment by Shubhangi2901** [comment]
Hey @ostephens @wetneb I would like to take up this issue,

**Comment by wetneb** [comment]
Awesome! Thanks for volunteering!

**Comment by wetneb** [comment]
Hi @Shubhangi2901, just checking if you are still working on this - if you are stuck by anything let us know!

**Comment by Shubhangi2901** [comment]
Hey @wetneb  thanks for checking in, i was actually stuck while building openRefine. I followed the steps in the documentation to run source code on eclipse. However it failed to download some artifacts. My build fails with the following error. Please let me know if I am missing some steps while building my code, and how do I get the additional artifacts.

Failed to execute goal on project main: Could not resolve dependencies for project org.openrefine:main:jar:3.4-SNAPSHOT: The following artifacts could not be resolved: edu.mit.simile:butterfly:jar:1.0.2, marc4j:marc4j:jar:2.4, net.sf.opencsv:opencsv:jar:2.4-SNAPSHOT, edu.mit.simile:vicino:jar:1.1, com.wcohen:secondstring:jar:20100303, com.colloquial:arithcode:jar:1.1: Failure to find edu.mit.simile:butterfly:jar:1.0.2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -

**Comment by wetneb** [comment]
Ok! This will be solved if you first build OpenRefine from the command line, with `./refine build` on Linux/MacOS or `refine.bat build` on Windows. This installs the missing artifacts in your local Maven repository. After that, Eclipse should be able to find these artifacts.

**Comment by wetneb** [comment]
Actually, this would require that Maven is installed on your machine… which is probably complicated to get right on Windows. I am working on lifting this limitation: #2365. The problem should be fixed in a few days (hopefully). Thanks for your patience!

**Comment by Shubhangi2901** [comment]
Hey @wetneb  thanks for the help, got all the mavens installed and running. However I wanted to confirm this this issue is still open as per PR https://github.com/OpenRefine/OpenRefine/pull/1993 this issue has been resolved. 
I have the code running on my local system and would be happy to take any other pending issue.

**Comment by wetneb** [comment]
Oh makes sense! Sorry about that, let's close this now.

**Comment by ettorerizza** [comment]
Looks like this new function is not documented among the [array functions](https://github.com/OpenRefine/OpenRefine/wiki/GREL-Array-Functions): https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/openrefine/XIfKTL6sv0w/_LG60A7hAgAJ

**Comment by tfmorris** [comment]
Added to wiki here: https://github.com/OpenRefine/OpenRefine/wiki/GREL-Array-Functions#inarrayarray-a-string-s
