### ISSUE TITLE
Implement randomNumber function from gokbutils

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1854]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
The gokbUtils extension includes an 'randomNumber' GREL command which generates a random integer in a specified range. This request is to migrate that function, as currently implemented in gokbutils into the core product

 https://github.com/ostephens/refine-gokbutils

**Comment by tfmorris** [comment]
I've added documentation for this to the wiki. The naming doesn't really fit with the rest of the functions, so we may want to consider a `random()` or `rand()` alias.

**Comment by thadguidry** [comment]
@tfmorris you can add an alias to a GREL function and still works in Expression editor?  That would be cool.
I would vote for `rand()`

**Comment by tfmorris** [comment]
> you can add an alias to a GREL function and still works in Expression editor?

Yes, functions can be registered multiple times. For example, `strip()` is a synonym for `trim()`.
