### ISSUE TITLE
Add exception handlingto ReconOperation#run()

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#1863]
_Issue was noted in #331 but never reviewed for correctness_

Large Recon operations might overflow silently.  Suggest we review code and make appropriate changes if necessary as noted in copied thread.

> From dfhu...@gmail.com on February 12, 2011 04:58:06:
> tfmorris, looking back at my code, the run() method doesn't catch and log any exception
> 
> https://github.com/OpenRefine/OpenRefine/blob/d97d6c66b8f209de3fe686bd6c9145ef21570db6/main/src/com/google/refine/operations/recon/ReconOperation.java#L237
> 
> So memory exceptions would go unnoticed.
> 
> vinnygoffin, if you're comfortable with Java code, would you mind trying to modify that file locally, wrap the run() method's content in a try catch and see if any exception shows up? Thank you for your patience.

**Comment by tfmorris** [comment]
OutOfMemory errors aren't caught by default (and are somewhat dangerous to try to catch), but the run method only has exception handling for a very small portion of the code. It should be enhanced with a failsafe exception handler that reports back to the user rather than dying silently.

**Comment by wetneb** [comment]
This is solved in the new architecture, where the reconciliation data is stored on disk as it is fetched, so it does not need to fit in RAM.
