### ISSUE TITLE
Fix for toDate() doesn't work for dot separated values (con't issue #1759)

### ISSUE THREAD

**Issue by orr721** [OpenRefine/OpenRefine#1867]
Hi all,

As mentioned in the issue title, dots as separators result in error in the toDate() format string.

This does not work: `"21.12.2012".toDate("dd.MM.yyyy")` --> error

This works: `"21.12.2012".toDate(false,"dd.MM.yyyy")`, also
this works correctly: `"21.12.2012".replaceChars(".","-").toDate("dd-MM-yyyy")`

OpenRefine v3.1-beta, MacOS 10.13.6, Safari 12.0.1, Slovak locale (lots of countries use dots in dates, really).

It used to work flawlessly in v2.8, doesn't work from 3.0 on.

Thank you for your outstanding work. This is really an amazing tool for me.

**Comment by wetneb** [comment]
@orr721 this will be fixed in the upcoming release 3.1.
