### ISSUE TITLE
Jackson annotations ignored for extensions

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1882]
Serialization and deserialization of classes provided by extensions currently fail, even if the classes were properly migrated to Jackson and tested. The problem comes from the fact that they are loaded dynamically by Butterfly, by a classloader that does not have access to the definition of the Jackson annotations. The annotations are therefore ignored, so Jackson attempts to deserialize and serialize them without any annotations.

**Comment by wetneb** [comment]
Thanks… yeah this is an annoying one. I think it will require fixing things in Butterfly itself. That's not a big issue, we are already using a custom build of that, and it is not maintained anyway.

**Comment by jackyq2015** [comment]
@wetneb can you please provide a procedure to reproduce this issue so others can understand better about this issue?

**Comment by wetneb** [comment]
@jackyq2015 sure. From the master branch, create a sample project. Click **Wikidata** -> **Edit wikidata schema** and create a simple schema there (for instance, click **Add item**, pick "Wikidata Sandbox" in the input box for this newly-created item, and add an alias by clicking **Add term**, choosing a language and inputing some string in the input box). Save the schema with the button in the right-hand corner.

Now stop OpenRefine and start it again. Load the test project. You will find in the console an error about `this._schema.itemDocuments` not existing. This is because the schema was not serialized correctly (the Jackson annotations were ignored).
