### ISSUE TITLE
cell.recon.features not populated when 'new' item used to create a new item

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1887]
**Describe the bug**
After using 'reconcile', marking some items as 'new', then uploading statements to Wikidata, creating new items, the items previously marked as 'new' are now correctly reconciled against the new items that have been created.

However, the properties of the cell.recon.features object are not updated when a new item is created, which leads to misleading information when creating facets or transforms based on these values.

**To Reproduce**
1. Reconcile a column, marking and item as 'new'
2. Upload edits to wikidata creating new items in Wikidata
3. Find the newly created item and create a facet or transform using one of:
* `cell.recon.feature.typeMatch`
* `cell.recon.feature.nameMatch`
* `cell.recon.feature.nameLevenshtein`
* `cell.recon.feature.nameWordDistance`
4. See these all appear as `null`
5. Try using the facet `Best candidates name match` - see these entries appear as 'unreconciled' in this facet

**OpenRefine (please complete the following information):**
 - Version: OpenRefine 3.1

**Additional context**
I think the correct behaviour here would be to populate the cell.recon.features properties.
If this isn't appropriate for some reason then the `Best candidates name match` facet needs updating to check for items which have cell.recon.match properties but no cell.recon.feature properties

@wetneb what do you think?

**Comment by wetneb** [comment]
Sure, it makes sense to populate these features!
