### ISSUE TITLE
Make clustering functions extensible to support other languages and scripts

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1893]
Feature request from @isaomatsunami at the OpenRefine meetup today in Tokyo.

**Is your feature request related to a problem or area of OpenRefine? Please describe.**
Clustering functions are quite european-centric (for instance the phonetic models were designed for English, the edit distance makes little sense for the Chinese alphabet). Implementing clustering and fingerprint functions for all languages is not easily doable but it would be good to let extensions define their own clustering methods.

**Describe the solution you'd like**
Make clustering extensible: extensions should be able to register new fingerprint and distance functions.

**Comment by ostephens** [comment]
I think a more extensible set of clustering methods is a really good idea - and would have application beyond just languages. For example, when I work with data containing company names I often need to remove strings that are common prefixes/suffixes to the company name (e.g. "ltd", "plc", "GmbH")

Very much in favour of this.

**Comment by tfmorris** [comment]
Was this extensibility ever used for anything?

Note that supporting registration of distance functions isn't sufficient for all clustering use cases. For example, in the Pass-Join clustering algorithm (#983), the distance functions are standard, but the indexing/search strategy is different.

**Comment by wetneb** [comment]
I am not aware of any extension that used this.

Indeed the changes requested in #983 are not covered by this extension point.
