### ISSUE TITLE
toNumber should support numbers in various locales

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1894]
Feature request from @isaomatsunami at the OpenRefine meetup today in Tokyo.

**Is your feature request related to a problem or area of OpenRefine? Please describe.**
Just like dates, numbers are formatted in different ways depending on the country. For instance, `187 347,31`, `187.347,31`, `187 347.37` all represent the same number in different locales, and non-arabic formats such as Kansuji in Japanese also exist. At the moment `toNumber` basically ignores this diversity of formats.

**Describe the solution you'd like**
Either extend the existing `toNumber` function to accept more formats (probably using an extra parameter to indicate the format) or create other functions (possibly provided as extensions if needed) to support more formats.

@isaomatsunami could you share the insightful examples you showed at the meetup?

**Comment by ostephens** [comment]
Possibly related to #816

**Comment by wetneb** [comment]
Thanks for the pointers, I should have searched for them myself…

**Comment by tfmorris** [comment]
Closing as a duplicate of #507 (from 2011!)
