### ISSUE TITLE
A column added using "Add column from reconciled values" does not appear as a reconciled column

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1895]
**Describe the bug**
If you add a column using "Add column from reconciled values", the new column contains values that are reconciled (at the cell level) but the whole column does not appear as reconciled and so cannot be used as a reconciled column in a Wikidata schema until it has been reconciled again.

**To Reproduce**
Reconcile a column with Wikidata
1. Use "Add column from reconciled values" to add a new column
2. Note new column contains reconciled values but there is no bar at the top showing the column itself is reconciled
3. Try using column in a wikidata schema where the schema expects a reconciled value

**Current Results**
The column does not appear to be reconciled even though each value in the column is reconciled

**Expected behavior**
The column should be reconciled and be usable in wikidata schema

**Comment by wetneb** [comment]
Hmm, that's curious - I am pretty sure this worked at some point.

**Comment by wetneb** [comment]
@ostephens which version of OpenRefine did you use when you had that issue? Would you have an example project to reproduce this maybe?

**Comment by wetneb** [comment]
@ostephens I'll close this as not reproducible for now, feel free to reopen if you can narrow down the issue to a reproducible scenario.
