### ISSUE TITLE
Mock the Url Fetching Tests (because they fail too often as not reachable)

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#1904]
**Describe the bug**
When running `refine test` the UrlFetchingTests often fail.

**To Reproduce**
1. refine test

**Current Results**
[ERROR] Tests run: 558, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 60.912 s <<< FAILURE! - in TestSuite
[ERROR] testInvalidUrl(com.google.refine.tests.operations.column.ColumnAdditionByFetchingURLsOperationTests)  Time elapsed: 5.006 s  <<< FAILURE!
java.lang.AssertionError: expected [false] but found [true]
        at com.google.refine.tests.operations.column.ColumnAdditionByFetchingURLsOperationTests.testInvalidUrl(ColumnAdditionByFetchingURLsOperationTests.java:226)

**Expected behavior**
URL tests should be mocked against an http server and pass, and not depend on real sites availability.

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit
 - JRE or JDK Version: JDK 1.8.0_181 or JDK 11.0.1

**OpenRefine (please complete the following information):**
 - Version: Trunk

**Comment by thadguidry** [comment]
Not fixed quite yet.
On master, I still see the errors during `refine test` for the `com.google.refine.tests.operations.column.ColumnAdditionByFetchingURLsOperationTests.testInvalidUrl`

**Comment by tfmorris** [comment]
It doesn't look like that PR (#2141) addressed `ColumnAdditionByFetchingURLsOperationTests` at all. The behavior has changed so that the tests no longer fail, but instead are silently skipped as described in #2680.
