### ISSUE TITLE
Script : http://127.0.0.1:3333/project-bundle.js:32

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#191]
_Original author: felix.av...@gmail.com (November 11, 2010 15:05:35)_

<b>What steps will reproduce the problem?</b>
1. Everytime I try to transform cells, colums etc
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
In a window : A script may be busy or not responding. You can stop the script now or waiting for the end of the script . 
Sorry I'm french, I don't know, I let you the original window's message :
Un script sur cette page est peut-être occupé ou ne répond plus. Vous pouvez arrêter le script maintenant ou attendre pour voir si le script se terminera.
Script : http://127.0.0.1:3333/project-bundle.js:32

<b>What version of the product are you using? On what operating system?</b>
google refine 2.0

<b>Please provide any additional information below.</b>
Script : http://127.0.0.1:3333/project-bundle.js:32
I tried on google chrome ans firefox. Same problem.

Thank you.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=191_

**Comment by thadguidry** [comment]
Closing as unreproducible. @jackyq2015 has fixed #137 where the XML import was improperly merging records.
