### ISSUE TITLE
Copy references across statements in Wikidata schema

### ISSUE THREAD

**Issue by abartov** [OpenRefine/OpenRefine#1912]
Began using OpenRefine seriously, and the Wikidata support is just fantastic.  One thing that would save some time is if after adding a reference in the Wikidata schema, the reference could be "filled down" or copied and pasted, or otherwise duplicated, for cases where all the statements are supported by the same source (e.g. census data).

**Comment by abartov** [comment]
Oh, I guess I should file it against the Wikidata extension.  Doing that now.

**Comment by wetneb** [comment]
@abartov this is the correct repository for the Wikidata extension (the Wikidata extension is shipped with OpenRefine). https://github.com/wetneb/openrefine-wikibase is the repository for the small service that interfaces OpenRefine and Wikidata (running at https://tools.wmflabs.org/openrefine-wikidata/). I understand that the separation of responsibilities is not necessarily clear for users, it's fine to report issues in either repositories.

**Comment by abartov** [comment]
Ah, thanks for clarifying!  I'll file future tickets here.
