### ISSUE TITLE
Sort reconciliation candidates by inverse score

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1913]
Reconciliation services might return their candidates without sorting them by decreasing score. In that case we might want to sort them (with a stable sort) on OpenRefine's side.
Once we agree on what the correct behaviour should be, we should update the documentation of the API here:
https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation-Service-API

Original SO question:
https://stackoverflow.com/questions/53852042/openrefine-reconcile-by-second-or-third-candidate

**Comment by ettorerizza** [comment]
It seems that the feature "Match each cell with its best candidate" just takes the first one, not the one with the highest score. It is also something that should be improved.
