### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by webieseo** [OpenRefine/OpenRefine#1926]
Having problems with latest openrefine on debain when i run ./refine build as root or normal user I get errors below ?

[ERROR] Failed to execute goal on project server: Could not resolve dependencies for project org.openrefine:server:jar:3.2-SNAPSHOT: Failure to find edu.mit.simile:butterfly:jar:1.0.1 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

Regards

**Comment by wetneb** [comment]
@webieseo oops, many thanks for reporting this - there was indeed a leftover reference to butterfly 1.0.1 that I have just removed (Travis did not pick up the issue because of dependency caching). Can you `git pull`, `./refine clean` and `./refine` again?

**Comment by webieseo** [comment]
HI All,
That fixed it all working now excellent work can I just say big thank you to this project saved me hours of work. HAPPY NEW YEAR

Regards

**Comment by tuukka** [comment]
The latest release still fails with this same error I suppose: `Failure to find edu.mit.simile:butterfly:jar:1.0.1`

**Comment by wetneb** [comment]
@tuukka if you are using a released version (as downloaded from the GitHub release) then you should not need to use `./refine build`, just `./refine` should work out of the box. But it is true that you will have this issue when trying to compile OpenRefine from the corresponding git tag. Apologies for that! A new version should be released soon.

**Comment by tuukka** [comment]
No worries, and thanks in advance!
