### ISSUE TITLE
GREL forEach function should be able to iterate through cells

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#194]
_Original author: iainsproat (November 11, 2010 19:13:16)_

As requested by Guy Y:

We have the following for the row template:

|{{cells[&quot;number&quot;].value}}
|{{cells[&quot;escalation&quot;].value}}
|{{cells[&quot;short_description&quot;].value}}
|{{cells[&quot;problem_state&quot;].value}}
|{{cells[&quot;rfc&quot;].value}}

The issue is that we'd like to have the same template work regardless
of what the names of my columns are.

The suggestion was to use the following:
{{foreach(cells, c, &quot;|&quot; + c.value)}}
but this throws an error.  I think this should be a capability of GRELs forEach function.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=194_
##

**Comment by ostephens** [comment]
This can be done by using the construction:

{{forEach(row.columnNames,cn,"|"+cells[cn].value)}}

Is this sufficient to close this issue?

**Comment by thadguidry** [comment]
@ostephens yeah it is sufficient, that was @iainsproat use case many years ago, we solved it that way on the mailing list.  Closing this. And thanks for navigating through these old issues to help close them out.
