### ISSUE TITLE
Link select cursor not working in Edge 41.16 and Firefox ESR 52.7.5

### ISSUE THREAD

**Issue by richirikken** [OpenRefine/OpenRefine#1948]
After reconciliation, weblinks to different candidates cannot be clicked. The text select cursor occours instead of the link select cursor (hand). The mouse hover with the link is not visible when the mouse moves over the reconciliation candidates.

Other items like tickmarks and menues are working correctly.

Error occurs with Microsoft Edge 41.16299.785.0 and Firefox ESR 52.7.4 (64 Bit) in Open Refine 3.1. See also:

https://groups.google.com/forum/#!topic/openrefine/IKBZ1wYM1JY

**Comment by wetneb** [comment]
Hovering links does not do anything on any browser at the moment, see #1943. But clicking should do something.

**Comment by richirikken** [comment]
Clicking on the candidates is not possible in this configuration

**Comment by wetneb** [comment]
I don't really know how this could be reproduced and debugged…

**Comment by wetneb** [comment]
Closing as not reproducible.
