### ISSUE TITLE
SQLite database connector

### ISSUE THREAD

**Issue by psychemedia** [OpenRefine/OpenRefine#1951]
The current database connector supports connections to PostgreSQL, MariaDB and MySQL.

A SQLite3 connector would be useful for several reasons:

- there is lots of tooling around SQLite, so it may be possible to use it as glue between different DBMS;
- SQLite3 provides a convenient way of distributing / sharing data in a way that also makes it amenable to querying.
- SQLIte3 is a file based system so it does not require a connection to a running server.

**Comment by thadguidry** [comment]
@psychemedia Care to hack on this?  Just look at the existing connection code in the extensions database folder and have a look at the tests as well.  Ooo, also just noticed the README.md under /database needs to be touched up a bit also since we use Maven now (don't use Ant anymore)

**Comment by psychemedia** [comment]
@thadguidry I don't have any experience with Java, and don't have a Java environment to work in, so there's a startup cost there that I don't have time to invest in atm... unless maybe you have a VM somewhere I could clone and fire up in an already working state?

**Comment by tfmorris** [comment]
Does #2323 fully resolve this, or is additional documentation required?

**Comment by wetneb** [comment]
Thanks, I forgot to link the PR to the issue.

**Comment by snussik** [comment]
Sorry for posting in closed issue, but how i can connect to sqlite.db file that is locally stored. It seems that OpenRefine is waiting for some local port connection?
_3.4-beta [5597e1c]_

**Comment by antoine2711** [comment]
> Sorry for posting in closed issue, but how i can connect to sqlite.db file that is locally stored. It seems that OpenRefine is waiting for some local port connection?

Hi. Just enter the full path to your file in the last field (`/Folder/File.sqlite3` in this picture):

![image](https://user-images.githubusercontent.com/12217525/82487542-7bc85380-9aac-11ea-9cca-50b4ef3bdad6.png)

@thadguidry: maybe we should consider « Only show the database login fields when necessary #2615 » as a bug fix for question like this one.

Regards,
   Antoine

**Comment by snussik** [comment]
> Hi @snussik. Just enter the full path to your file in the last field, the one named « Database » (`/Folder/File.sqlite3` in this picture):

Thanks a lot! Didn’t think that it’s so simple. By the way, don’t know if it is a bug or feature but if I choose “SQLite” engine and  enter any string to database textfield, “test” button shows “Ok”.

**Comment by antoine2711** [comment]
> By the way, don’t know if it is a bug or feature but if I choose “SQLite” engine and enter any string to database textfield, “test” button shows “Ok”.

Thank you @snussik for pointing that out. I would classify it as a bug, indeed… ;-)

Regards,
   Antoine
