### ISSUE TITLE
Connect to a local reconciliation service

### ISSUE THREAD

**Issue by psychemedia** [OpenRefine/OpenRefine#1952]
I can create a simpe local reconciliation service on either a local server or in a Docker container running locally according to the [reconciliation service docs](https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation-Service-API#service-metadata) and see it register with OpenRefine, with a simple definition file such as:

```
metadata = {
    "name": "Person Reconciliation Service",
    "identifierSpace": "http://rdf.freebase.com/ns/type.object.id",
    "schemaSpace": "http://rdf.freebase.com/ns/type.object.id",
    "view": {
      "url": "http://127.0.0.1:8889{{id}}"
    },
    "defaultTypes": [{"id": "/people/person", "name" : "Person"}],
}
```

Whilst the service appears in the service listing, and the `defaultType` is presumably used as the basis of the reconciliation, the  following request returns an error no matter what I try to do on the service side:

```
http://localhost:3337/command/core/guess-types-of-column?project=2032794697683&columnName=Name&service=http%3A%2F%2Flocalhost%3A8889%2Freconcile
```

```
POST /command/core/guess-types-of-column?project=2032794697683&columnName=Name&service=http%3A%2F%2Flocalhost%3A8889%2Freconcile HTTP/1.1
Host: localhost:3337
Connection: keep-alive
Content-Length: 0
Accept: */*
Origin: http://localhost:3337
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
DNT: 1
Referer: http://localhost:3337/project?project=2032794697683
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: home_viewed=1548691850; PGADMIN_LANGUAGE=en; crisp-client%2Fsession%2F2787f5d1-53ec-43ea-84dc-f0589cb531d6=session_4fc9fe29-87fd-41f6-955f-69b010040046; _xsrf=2|7492911c|5b40c17ecc5a803c36fc6177d9c720cc|1549363211; username-localhost-9999="2|1:0|10:1549373357|23:username-localhost-9999|44:NTY1YzliODk0ZDM2NGQ5NjlkZjExMjYzNTIxMjQ0Yzg=|aebeb30533b977e40481539b3fc6307df36080c14b51c5cd3270588ad8a9ceba"; username-localhost-8888="2|1:0|10:1549458871|23:username-localhost-8888|44:OWZkMmQyYWFjM2NmNGNkZmFlZmQwOTMxZmFhMzlmMTI=|b0c0edca74394c5359c90b619e6a1bfb4b2a5550bd082cd21a2988feb169e379"; username-localhost-8855="2|1:0|10:1549467949|23:username-localhost-8855|44:NWIzNDJlOGNhNjY5NDE1ZDllN2VkYWEwNGI3MWVlZjc=|3107b4f9b8fbf5415fb1672f428e3c1917fe12dca930ee0b65c20e512e4b15bb"; pga4_session=fe074946-02d2-46a9-830a-71b89e6dcacc!7SecetlmT2oqa+/S+51BWiK0mwk=; host=.butterfly
```

```
{{"stack":"java.net.ConnectException: Connection refused (Connection refused)\n\tat java.net.PlainSocketImpl.socketConnect(Native Method)\n\tat java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)\n\tat java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)\n\tat java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)\n\tat java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)\n\tat java.net.Socket.connect(Socket.java:589)\n\tat sun.net.NetworkClient.doConnect(NetworkClient.java:175)\n\tat sun.net.www.http.HttpClient.openServer(HttpClient.java:463)\n\tat sun.net.www.http.HttpClient.openServer(HttpClient.java:558)\n\tat sun.net.www.http.HttpClient.<init>(HttpClient.java:242)\n\tat sun.net.www.http.HttpClient.New(HttpClient.java:339)\n\tat sun.net.www.http.HttpClient.New(HttpClient.java:357)\n\tat sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)\n\tat sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)\n\tat sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)\n\tat sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)\n\tat sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)\n\tat sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)\n\tat com.google.refine.commands.recon.GuessTypesOfColumnCommand.guessTypes(GuessTypesOfColumnCommand.java:174)\n\tat com.google.refine.commands.recon.GuessTypesOfColumnCommand.doPost(GuessTypesOfColumnCommand.java:89)\n\tat com.google.refine.RefineServlet.service(RefineServlet.java:190)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:820)\n\tat org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)\n\tat org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)\n\tat org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)\n\tat org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)\n\tat org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)\n\tat org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)\n\tat org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)\n\tat org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)\n\tat org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)\n\tat org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)\n\tat org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)\n\tat org.mortbay.jetty.Server.handle(Server.java:326)\n\tat org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)\n\tat org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)\n\tat org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)\n\tat org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)\n\tat org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)\n\tat org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n","code":"error","message":"Connection refused (Connection refused)"}
```

The Java service is presumably making a request into the server. What request?

**Comment by wetneb** [comment]
@psychemedia OpenRefine tries to reconcile the first 10 rows of your column using your service, so that it can use the types returned by your service to suggest types to the user. So the request looks like this:
```
curl -X POST http.//127.0.0.1:888/ -d '{"q6": {"query": "locus ceruleus complex", "limit": 3}, "q3": {"query": "titrant", "limit": 3}, "q4": {"query": "costal", "limit": 3}, "q9": {"query": "carbon dioxide assimilation", "limit": 3}, "q0": {"query": "Chilaiditi's sign", "limit": 3}, "q7": {"query": "endoplasmic reticula", "limit": 3}, "q1": {"query": "genioplasty", "limit": 3}, "q5": {"query": "lactococcal", "limit": 3}, "q8": {"query": "BFU", "limit": 3}, "q2": {"query": "astute", "limit": 3}}'
```

That being said the shape of the request should not matter, as it seems it cannot even connect to the server anyway. So there is probably a problem with your Docker setup - have you tried querying your reconciliation service from your browser and from the command line?

**Comment by psychemedia** [comment]
There's an example running in MyBinder here:

https://mybinder.org/v2/gh/psychemedia/jupyterserverproxy-openrefine/reconciler

This should launch a Jupyter notebook server to s/thing like:

`https://hub.mybinder.org/user/psychemedia-jup-roxy-openrefine-RANDOM/tree`

OpenRefine is then available at:

`https://hub.mybinder.org/user/psychemedia-jup-roxy-openrefine-RANDOM/openrefine`

The reconciler is on:

`https://hub.mybinder.org/user/psychemedia-jup-roxy-openrefine-RANDOM/proxy/8895/parliament/reconcile/`

(You need the trailing slash. That is perhaps one problem?)

Reconcile:

`https://hub.mybinder.org/user/psychemedia-jup-roxy-openrefine-RANDOM/proxy/8895/parliament/reconcile/?queries={%22q1%22:{%22query%22:%22Diana%20Abbot%22}}`

The service is defined in `notebooks/Reconciler.ipynb`.

I would have expected to also be able to register the service in OpenRefine with:

`http://localhost:8895/parliament/reconcile`

but that seems not to work? (Which is a bit odd, because the connection to Postgres on 127.0.0.1 works here: https://github.com/psychemedia/jupyterserverproxy-openrefine/tree/pgdemo )
 
I've also been wondering if I need to set access permissions as per [config options](https://jupyter-kernel-gateway.readthedocs.io/en/latest/config-options.html) to handle the Java URL requests? (I've no idea what those permission might need to be tho!)

**Comment by wetneb** [comment]
Ah, if you are running this in a Binder instance, then using 127.0.0.1 for the address of the reconciliation service is definitely a bad idea, as some requests to the reconciliation service are done in AJAX by the web UI (so, from your own browser). So even if you managed to get the `guess-types-of-column` command working with that setup, you would not be able to use the previews and suggest services.

**Comment by psychemedia** [comment]
I moved to 0.0.0.0 and got the same?

**Comment by psychemedia** [comment]
I tweaked an earlier fork of https://github.com/OpenRefine/reconciliation_service_skeleton just now here —  https://github.com/ouseful-backup/reconciliation_service_skeleton — that I think had the correct/required metadata fields. This gives the same connection error as above?

It'd be useful to see a working version of `OpenRefine/reconciliation_service_skeleton`.

**Comment by wetneb** [comment]
@psychemedia yes, the problem is that both `127.0.0.1`, `0.0.0.0`, `localhost` or anything like that is only going to be understood locally, on your Binder instance. You need to use an address that can be understood anywhere, including in your browser.

One such address would be `https://hub.mybinder.org/user/psychemedia-jup-roxy-openrefine-RANDOM/proxy/8895/parliament/reconcile/` for instance.

**Comment by wetneb** [comment]
And I agree we should update https://github.com/OpenRefine/reconciliation_service_skeleton, or delete this fork as we should not endorse by the organization something that is not functional.

**Comment by psychemedia** [comment]
Hmm... generally, I though 127.0.0.1 should work for localhost traffic (eg
within a container) and 0.0.0.0 would accept everything?

**Comment by wetneb** [comment]
@psychemedia please see my replies above:

> Ah, if you are running this in a Binder instance, then using 127.0.0.1 for the address of the reconciliation service is definitely a bad idea, as some requests to the reconciliation service are done in AJAX by the web UI (so, from your own browser). So even if you managed to get the guess-types-of-column command working with that setup, you would not be able to use the previews and suggest services.

> the problem is that both 127.0.0.1, 0.0.0.0, localhost or anything like that is only going to be understood locally, on your Binder instance. You need to use an address that can be understood anywhere, including in your browser.
> 
> One such address would be https://hub.mybinder.org/user/psychemedia-jup-roxy-openrefine-RANDOM/proxy/8895/parliament/reconcile/ for instance.


The communication between your browser and the MyBinder instance is not going to be local, so you should not use a local address to add the reconciliation service. Is that clearer? There is just no chance your setup is going to work - do not use a local address if you want to use the reconciliation service in a MyBinder instance. I honestly cannot think of any other way to explain this, sorry.

**Comment by wetneb** [comment]
In other words:
- your browser is running on your own machine (the one that sits on your desk or lap or whatever), let's call that "machine A"
- your OpenRefine instance is running in the cloud, on some server in some datacenter, let's call that "machine B"

For reconciliation services to work you will need "machine A" to talk to "machine B". So "machine A" needs to know where "machine B" lives, so that it can follow internet cables across the many mountains, rivers and seas that are between them! For this magic to happen, you need to give an address of "machine B" that "machine A" can understand. Local addresses such as `localhost` will typically not work as "machine A" will understand them as referring to itself.

**Comment by thadguidry** [comment]
@psychemedia You can just use Docker Compose (version 3) to handle this custom networking need (Docker lets you create any number of virtual networks and handles the routing for you (via IP Table rules it automatically creates).
1. Create 2 networks in the Docker-compose file
2. Assign 1st service (OpenRefine) to frontend network  (dunno how MyBinder works, but this might also need to be on frontend network as well)
3. Assign 2nd service (Recon Service) to backend network 

https://docs.docker.com/compose/networking/

**Comment by psychemedia** [comment]
@wetneb Agreed. So I have several test set ups and they're all failing when OpenRefine tries to connect from Java:

- MyBInder, with OpenRefine and the reconciliation server both running inside the *same* MyBinder container.
- my local machine with OpenRefine running in a Docker container with port 3333 exposed to host localhost and my reconciliation server either running on host as a Python flask app, or inside a container with ports exposed to host localhost.

I'm maybe doing something wrong with my reconciliation service and messing up the networking, as well as fundamentally misunderstanding that I seem to have got working by other means and in other situations before!

I've overspent so much time on OpenRefine stuff lately, I maybe need to take a break from the keyboard and come back to it when I've cleared my head a bit.

**Comment by wetneb** [comment]
Yes, for postgres I think all connections should be happening directly between the Java backend and the database server. What I have been trying to explain above is that this is not entirely the case for reconciliation services: communication with reconciliation services happens both from the Java backend and the web frontend. The error you are observing comes from a failure of communication between the Java backend and the reconciliation service, but fixing it will not give you a fully functional reconciliation service if the service is configured with a local address - so it is not worth trying to make that work.

Passing the full URL should work though. To debug this, you can try to access the reconciliation service manually from your own browser: check that it returns a valid service metadata, and that it responds adequately to reconciliation queries of the form mentioned above. You should also be able to add your reconciliation service with the full URL in a locally running OpenRefine instance. Good luck!

**Comment by psychemedia** [comment]
@wetneb one of the issues might be how URLs are handled. The Mybinder proxy requires a trailing slash on eh `http://URL/reconcile/?queries=...`. Is that respected as part of the URL I register the service with or is it stripped?

**Comment by psychemedia** [comment]
Also, if I look at browser developer tools reconciling against something like WIkidata (which does work), I see no calls to Wikidata in network traffic? All I see are calls to OpenRefine local services?

**Comment by wetneb** [comment]
@psychemedia Yes trailing slashes are respected.

Calls to the reconciliation service from the browser are done when previewing an item (clicking on an unmatched reconciliation candidate), configuring properties or types in the reconciliation dialog, or manually choosing a different match for a cell.

**Comment by psychemedia** [comment]
@wetneb Ok... I've not got that far. The bit that is broken is the bit where OpenRefine says to the reconciliation server - "have you got anything that sort of matches this thing?" 

Hmmm, in fact, in MyBinder it may not even get that far, it may break when I try to register the service in the first place. (In some local tests that bit was working, at least. I started a new reconciliation, the name of the new service appeared in the Reconciliation panel, then I stalled on the spinny wheel as OR tried to look up reconciliation matches down a column.)

**Comment by wetneb** [comment]
Yes, the browser also accesses the reconciliation service at registration: yet another reason not to try to register the service with a local address.

**Comment by fsteeg** [comment]
I stumbled upon this issue while trying to make sense of a discrepancy between the [docs](https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation-Service-API#query-request) (which describe an HTTP GET for the reconciliation query request) and the actual OpenRefine behavior (which uses a POST for the reconciliation query request).

I didn't dig into the details of this issue, but I noticed that @psychemedia mentions GET queries (e.g. `https://hub.mybinder.org/user/psychemedia-jup-roxy-openrefine-RANDOM/proxy/8895/parliament/reconcile/?queries={%22q1%22:{%22query%22:%22Diana%20Abbot%22}}`), while OpenRefine actually sends POST requests as described by @wetneb in https://github.com/OpenRefine/OpenRefine/issues/1952#issuecomment-461859659.

@wetneb Is this basically a mistake in the docs? Or in OpenRefine (GET does make more sense semantically)? Or am I missing something here?

**Comment by wetneb** [comment]
@fsteeg That's clearly something that ought to be better documented. I thought the docs explicitly recommended to accept both GET and POST, but apparently not.

POST is useful for big queries, GET is more convenient to debug things, so I think it makes sense to support both in general.

**Comment by fsteeg** [comment]
@wetneb Thanks for your feedback, I've added a POST example to the [Query Request](https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation-Service-API#query-request) section.

@psychemedia Could the `ConnectException: Connection refused` be your server's response to that kind of POST request coming from OpenRefine?
