### ISSUE TITLE
Reconciliation of Wikidata URIs fails with "use values as identifiers" operation

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1953]
**Describe the bug**
When using the operation "Use values as identifiers" on a column of URIs obtained from Wikidata's SPARQL endpoint, one gets items reconciled to <code>https://www.wikidata.org/wiki/Http://www.wikidata.org/entity/Q160482</code>.

**To Reproduce**
1. Import in OpenRefine the results of a SPARQL query, such as [this one](https://query.wikidata.org/#SELECT%20DISTINCT%20%3Fitem%0AWHERE%0A%7B%0A%20%20%3Fitem%20wdt%3AP31%20wd%3AQ16521%20%3B%0A%20%20%20%20%20%20%20%20wdt%3AP105%20wd%3AQ767728%20%3B%0A%20%20%20%20%20%20%20%20schema%3Adescription%20%3Fsitelink%20%0A%20%20FILTER%28LANG%28%3Fsitelink%29%20IN%20%28%22en%22%29%29%0A%20%20FILTER%20%28%20REGEX%28%3Fsitelink%2C%20%22variety%20of%20plant%22%29%20%29%0A%20%20MINUS%20%7B%3Fitem%20schema%3Adescription%20%3Flabel_fr%20filter%28lang%28%3Flabel_fr%29%20%3D%20%22fr%22%29%20.%20%7D%0A%7D)
2. Use the "Use values as identifiers" operation
3. Click on a reconciled cell and observe the error

**Expected behavior**
OpenRefine could magically understand that these cells are URIs and convert them to identifiers properly.

**OpenRefine (please complete the following information):**
 - Version 3.1

**Potential workarounds**

We could take into account the view URL of a service, and match the cell contents to the view URL to extract the URI. However, in the case of Wikidata, that would not work, as the SPARQL URIs and the view URIs used in the interface are different. I could change the view URIs of the reconciliation service to use the RDF URIs but that will require people to remove the service and add it back.

Otherwise, we could also implement a SPARQL importer (#1212) where users could type their SPARQL query, preview it, and create a project from it, directly from OpenRefine. The SPARQL importer would take care of the reconciliation.

**Comment by thadguidry** [comment]
Let's clarify what the OpenRefine values are in the column after import in step 1 and what the import method is.
this ?
`wd:Q55830412`
or this ?
`Q55830412`
or something else ?

Because when I download from SPARQL query using the "Download as TSV", I already get URLs that look like this:
```
item
http://www.wikidata.org/entity/Q55830412
http://www.wikidata.org/entity/Q55830494
http://www.wikidata.org/entity/Q55830502
etc...
```

**Comment by thadguidry** [comment]
I like the idea of a SPARQL importer.
But it wouldn't have all the nice features of WDQS online interface, right? (that isn't as powerful)
However, I don't want a lot of overhead in OpenRefine for us to maintain. (that's a worry I have)
I wonder if we could just use the existing WDQS browser interface in OpenRefine somehow...
What if we flipped things around...and WDQS had a "Download ID's" option? or "Download OpenRefine project" option?

**Comment by wetneb** [comment]
When downloading the results of a SPARQL query, the column contains full URIs (`http://www.wikidata.org/entity/Q55830494`) whereas OpenRefine expects identifiers (`Q55830494`). One can convert one from the other with an expression such that `value.split('/')[-1]` but that requires an extra step and confuses newcomers.

**Comment by wetneb** [comment]
Hmm actually we do store the schema space `http://www.wikidata.org/entity/` so we can use that too.
