### ISSUE TITLE
Add Wikidata reconciliation with GPS coordinates

### ISSUE THREAD

**Issue by Manu1400** [OpenRefine/OpenRefine#1966]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
Sometime i have a dataset with coords (GPS coordinates) but with difficult names, like this dataset: https://www.data.gouv.fr/fr/datasets/liste-des-ponts-rail/
I want to can do a reconciliation with Wikidata:
In the dataset example, the field 'coordonnees_geo' is a standard GPS coordinates.
Some wikidata items have GPS coords too.

**Describe the solution you'd like**
1/ Please, support GPS coords. (optional)
2/ Compare coords +/- X meters.

**Describe alternatives you've considered**

**Additional context**
For GeoJson, we have https://github.com/ryanfb/georefine

**Comment by wetneb** [comment]
@Manu1400 this is already supported by the reconciliation interface: https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation#comparing-values
This is demonstrated in the second video of this tutorial:
https://www.wikidata.org/wiki/Wikidata:Tools/OpenRefine/Editing/Tutorials/Video

However, note that coordinates are currently only used in scoring, not at the retrieval phase. So it can be used to distinguish between namesakes, but will still require that the names are spelt reliably enough to bring up the candidates in the first place.

**Comment by wetneb** [comment]
@Manu1400 I'm closing this per the above - if there is still an issue on your side, please report it to https://github.com/wetneb/openrefine-wikidata instead. Thanks!
