### ISSUE TITLE
Remove freebaseapps.com from scripts

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#1973]
Example:

https://github.com/OpenRefine/OpenRefine/blob/af8608e897263bd7b5cb13c0b19d80dac61e09bb/main/webapp/modules/core/scripts/project.js#L57

**Comment by jfeng43** [comment]
Let me see if I can help on this.

**Comment by thadguidry** [comment]
@jfeng43 Thanks!  Don't break functionality however.  I'm not sure how or if refineHelperService is even something that's used for context with Reconciliation in general or not.  So you'll need to ask @wetneb about all that before you begin.

**Comment by jfeng43** [comment]
@thadguidry I am quite a newbie to open source project. I thought it was a straightforward fix but when I look into the codebase, I realized it was not the case.

I want to have some context here: why do we want to remove this link from the scripts?

**Comment by wetneb** [comment]
Freebase has been shut down so any calls to their webservices will fail and are normally only made from dead code. This is therefore an exercise of removing dead frontend JavaScript code. It is mostly down to understanding how reconciliation works client-side and taking out the bits that are no longer used. You are more than welcome to ask questions here if you want to tackle this!
