### ISSUE TITLE
Add "Select all/none" button when importing multi-sheet Excel

### ISSUE THREAD

**Issue by ookgezellig** [OpenRefine/OpenRefine#1974]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
When I'm creating a new project and import data from an Excel-file that has for instance 12 worksheets, the 12 checkboxes associated with those 12 sheets are all checked by default (see screenshot). When I only need 1 sheet in my project, I now need to deselect the other 11 sheets one-by-one by hand, which is unhandy. 

![afbeelding](https://user-images.githubusercontent.com/6546244/53796992-8fce7680-3f35-11e9-98f1-b85c215f5a4f.png)
 
**Describe the solution you'd like**
I'd like a button to select/deselect all the 12 checkboxes at once. This could be placed next to (or rather: in front of) "Worksheets to Import"

**Comment by ostephens** [comment]
Closed by #2004
