### ISSUE TITLE
Extract Wikidata Q-numbers from reconciled items

### ISSUE THREAD

**Issue by ookgezellig** [OpenRefine/OpenRefine#1975]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
I often need to extract the Wikidata Q-values from reconciled items. I now do this via "Edit column --> Add column based on this column" and then using the GREL expression "cell.recon.match.id" to retrieve the Q-numbers

![afbeelding](https://user-images.githubusercontent.com/6546244/53798106-dcb34c80-3f37-11e9-9bd8-a076c824dcb8.png)

**Describe the solution you'd like**
It would be handy to have a function ("Extract Q-value", or some other description) under "Edit column" to automatically extract the Q-value and put these in a new adjecent column.

**Comment by wetneb** [comment]
Related: https://github.com/wetneb/openrefine-wikibase/issues/57.

**Comment by wetneb** [comment]
To do this, one would need to add an action in the menu, probably in `main/webapp/modules/core/scripts/views/data-table/menu-reconcile.js`. This action should prompt the user for a column name and use the existing operation to create the column (no backend change should be needed).

**Comment by madham32** [comment]
Hi! I'd like to be assigned this.

**Comment by madham32** [comment]
![Screenshot from 2020-03-09 00-36-29](https://user-images.githubusercontent.com/47317143/76169839-1b5c9200-619e-11ea-9a4a-34aee1c81cb1.png)
Just got to add a function with the query expression now and we're good to go!

**Comment by madham32** [comment]
Here's how the fix works:

![Screenshot from 2020-03-09 11-03-28](https://user-images.githubusercontent.com/47317143/76187016-027fcb00-61f6-11ea-91a9-3d22a230da9f.png)
![Screenshot from 2020-03-09 11-04-15](https://user-images.githubusercontent.com/47317143/76187019-07447f00-61f6-11ea-8f72-778449d9a185.png)
![Screenshot from 2020-03-09 11-09-42](https://user-images.githubusercontent.com/47317143/76187194-876ae480-61f6-11ea-8401-9f75e64fc938.png)
![Screenshot from 2020-03-09 11-04-59](https://user-images.githubusercontent.com/47317143/76187029-0ca1c980-61f6-11ea-837e-cde8fbc53be1.png)

**Comment by CennoxX** [comment]
I think the menu item / column /... should be renamed to "Add ID values column" / "ID values" /... or something like that. Because this extracts all ids of the cells, only in the case of Wikidata this is a Q...-value.

**Comment by wetneb** [comment]
@CennoxX the screenshot above is not the final version of this feature. Have you tried OR 3.4? Here is what it looks like there:
![image](https://user-images.githubusercontent.com/309908/86526674-35318b80-be97-11ea-9f36-a069aeb0facd.png)

**Comment by CennoxX** [comment]
Thanks for clarifing. I only read the release notes.

**Comment by fpompermaier** [comment]
Il Dom 5 Lug 2020, 08:12 Antonin Delpeuch <notifications@github.com> ha
scritto:

**Comment by thadguidry** [comment]
@wetneb Just to ensure the correct behavior; is this how @allanaaa could describe the functionality to document it? 
>... this extracts all ids of the cells, only in the case of Wikidata this is a Q...-value.

Also I wonder if "Add" was the right word choice on the menu item.  Maybe "**Extract** entity identifiers **to** column"?

**Comment by wetneb** [comment]
This feature is not specific to Wikidata in any way - it extracts the identifier of matched cells, and works regardless of which reconciliation service was used to reconcile the column.
