### ISSUE TITLE
add menu option "All / Facet / Facet by non-blank"

### ISSUE THREAD

**Issue by felixlohmeier** [OpenRefine/OpenRefine#1977]
I would like to suggest to add the custom text facet recipe [Count non-blank values in each column](https://github.com/OpenRefine/OpenRefine/wiki/Recipes#count-non-blank-values-in-each-column)
`filter(row.columnNames,cn,isNonBlank(cells[cn].value))` to the "All" menu, e.g.
* "All > Facet > Facet by non-blank"
* or "All > Facet > Count non-blank values"

I guess this recipe is a common first step to get a quick overview of your dataset, so it should be more easily available for new users.

**Comment by wetneb** [comment]
@felixlohmeier sounds like a sensible thing to do! Do you want to try submit a PR for that? It should not be too hard, you can get some inspiration from the existing facets in the menus.
