### ISSUE TITLE
Feature Request: specify character encodings on import and export

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#198]
_Original author: defensec...@mamber.net (November 12, 2010 18:23:40)_

Handling character encodings is a very common part of data cleansing for me.  At the basic level, this means giving the option of specifying a character encoding on both import and export.  Going further, if raw bytes are a supported type, you could offer character encoding/decoding as a column transformation.  To make it really rich you could suggest the mostly likely character encodings at import time.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=198_

**Comment by thadguidry** [comment]
@jackyq2015 @wetneb Don't we already handle this ?  Or only on import and we need to do more work to support giving options for changing encoding on export ?  This is an old issue and I feel we pretty much give most users what they most need regarding encoding support.  So I think we can close this, Yes ?

**Comment by wetneb** [comment]
Agreed, closing.
