### ISSUE TITLE
Can I use ARX encryption tools or other tools to encrypt text before OpenRefine transfers or saves it?

### ISSUE THREAD

**Issue by jyf1997** [OpenRefine/OpenRefine#1988]
I want to try to increase OpenRefine security

**Comment by wetneb** [comment]
@jyf1997 I am not familiar with ARX encryption. If you have an idea how to apply this technology to OpenRefine, feel free to explain your approach in more detail, so that we can give you informed feedback. You can also submit pull requests and we will comment on those.

**Comment by wetneb** [comment]
No concrete proposal about how this could be implemented in OpenRefine, closing.
