### ISSUE TITLE
Extract Operation Corrupted

### ISSUE THREAD

**Issue by nanobrad** [OpenRefine/OpenRefine#1990]
**Describe the bug**
I started using OpenRefine Version 3.2-beta [8d89a2a]. It seems to have corrupted by undo history--specifically on a number of projects that I've touched, I can no longer "Extract" my history as JSON.

Going back to version 3.1, I find that 3.1 can't extract the history either. Making an edit in 3.1 seems to fix the problem going forward, so that I can then go back to 3.2-beta and see this:
![image](https://user-images.githubusercontent.com/597719/54849365-0dbeab80-4cb2-11e9-8b07-8ce389c4c150.png)

**To Reproduce**
I can share the project via e-mail, but I haven't been able to replicate the "corruption."

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version: Version 72.0.3626.121 (Official Build) (64-bit)
 - JRE or JDK Version:
-- java version "1.8.0_121"
-- Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
-- Java HotSpot(TM) Client VM (build 25.121-b13, mixed mode)

**OpenRefine (please complete the following information):**
 - OpenRefine Version 3.2-beta [8d89a2a]

**Datasets**
Will share via e-mail

**Comment by ostephens** [comment]
@nanobrad could you send the project to me by email? owen@ostephens.com

**Comment by ettorerizza** [comment]
[Similar issue on SO](https://stackoverflow.com/questions/55688993/is-there-a-way-to-force-open-refine-to-extract-all-history-changes-into-json), but may be related to a badly configured reconciliation service (see [#1936](https://github.com/OpenRefine/OpenRefine/issues/1936#issuecomment-457781722))

**Comment by nanobrad** [comment]
For what it's worth, I haven't used any reconciliation services or changed any of their configurations.

**Comment by thadguidry** [comment]
@nanobrad Can you try again with your backed up project against a build from our master branch, as Antonin has pushed and merged a fix and we would like to see if this works well for you.
