### ISSUE TITLE
curl  and proxy

### ISSUE THREAD

**Issue by patatetom** [OpenRefine/OpenRefine#2000]
checks performed by `curl` (or `wget`) on the default interface `127.0.0.0.1` in `check_running` with `refine` shell script should never use a proxy server : the `--noproxy 127.0.0.0.1` parameter would avoid any bad network/proxy configuration.

```patch
--- refine	2019-03-28 14:43:15.710000051 +0100
+++ refine.curl	2019-03-28 15:03:26.410000074 +0100
@@ -154,7 +154,7 @@
     CHECK_STR="<title>OpenRefine</title>"
 
     if [ "$CURL" ] ; then
-        curl -s -S -f $URL > /dev/null 2>&1
+        curl --noproxy 127.0.0.1 -s -S -f $URL > /dev/null 2>&1
         if [ "$?" = "7" ] || [ "$?" = "22" ] ; then
             NOT_RUNNING="1"
         fi
@@ -167,7 +167,7 @@
 
     if [ -z "${NOT_RUNNING}" ] ; then
         if [ "$CURL" ] ; then
-            RUNNING=`curl -s $URL | grep "$CHECK_STR"`
+            RUNNING=`curl --noproxy 127.0.0.1 -s $URL | grep "$CHECK_STR"`
         elif [ "$WGET" ] ; then
             RUNNING=`wget -q -O - $URL | grep "$CHECK_STR"`
         fi    
```

I leave it to you to look for `wget`, thanks for OpenRefine :+1: , regards, lacsaP.

**Comment by tejasbhosale17** [comment]
Hi, I was working on it hope it's ok, i also have raised a PR please check.

**Comment by tejasbhosale17** [comment]
I tried making some changes please check if they are ok.

**Comment by patatetom** [comment]
at first glance, the change you've made seems to solve the issue, but unfortunately, I can't test your changes.
sorry.
regards, lacsaP.

**Comment by wetneb** [comment]
True, it looks like the `URL_LOCAL` variable was introduced in a failed attempt to translate the curl code to wget, but I don't see why it is needed at all, using `URL` should be the right thing to do there. We should fix that. Maybe it's worth opening a separate issue (or a PR directly)?
