### ISSUE TITLE
Fix errors reported by LGTM

### ISSUE THREAD

**Issue by stweil** [OpenRefine/OpenRefine#2006]
The static code analyser LGTM reports several errors which need closer examination (and in most cases a fix), see https://lgtm.com/projects/g/OpenRefine/OpenRefine/alerts/?mode=list&severity=error.

There are also some potential errors in the huge list of warnings, so these warnings should be reduced, too.

**Comment by wetneb** [comment]
PRs towards this will always be gratefully received :)

**Comment by tfmorris** [comment]
I've installed LGTM for our repos and added their badges to the README (#2747) as a step towards interest in generating actionable PRs.

There are currently 41 "errors", some of which would be relatively easy to fix by sanitizing error messages, but some of them seem excessively paranoid like hiding stack traces. In general, many of the failing checks are assuming an open network installation, not a single user installation where the sole user isn't likely to be mounting XSS attacks against themselves.

**Comment by wetneb** [comment]
XSS attacks are still possible even from an remote website to a local installation (the CSRF change fixed just that).

I am not against trying LGTM but I would expect some discussion before integrating a service like this (there are plenty to choose from). We will see if it we find it helpful as we use it, I guess. Having Codacy around was not a great experience, hopefully this one does a better job.

**Comment by tfmorris** [comment]
I'd have thought that if we disapproved of LGTM, this issue would have just been closed, along with a pointer to our preferred static checker. If you've got another checker that you prefer, I can integrate that instead -- or you can.

Generally I find these types of things much easier to evaluate in use than in the abstract from their documentation.

**Comment by wetneb** [comment]
I guess there is a difference between fixing the issues reported on an external website and adding the GitHub integration, which can be quite invasive and unhelpful (hello Codacy!). But looking at the first few PRs checked, LGTM looks much better.

**Comment by wetneb** [comment]
The LGTM integration broke a while ago so I removed it. Their website now says:

> LGTM.com will be shut down in December 2022 — we recommend that you use GitHub code scanning instead.

Therefore I am closing this, we can integrate suggestions from GitHub itself instead.
