### ISSUE TITLE
Speed of Reconcile with Wikidata

### ISSUE THREAD

**Issue by broom9** [OpenRefine/OpenRefine#2007]
Hi there,

Is there a way to know what is costing time when reconciling data with Wikidata? It feels very very slow when I try to reconcile a list of technologies names with the built-in wikidata reconciliation function (~10 minutes per entry). But when I go to wikidata to search these terms the website seems pretty fast.

I want to know what is taking time. When checking logs of OpenRefine, the only log that seems related is the following line:
```
17:32:08.047 [                   refine] POST /command/core/reconcile (29493ms)
```

Is there a way to inspect more about the communication between OpenRefine and the reconciliation service? Thanks.

**Comment by wetneb** [comment]
10 minutes per entry is definitely way too much! Even for complex queries it should not take more than a few seconds. Can you share the details of your reconciliation? Which type do you reconcile to, which properties are you using to refine the candidates?

To inspect the communication between OpenRefine and the reconciliation service, I would use a network capture tool such as Wireshark.

**Comment by broom9** [comment]
Thank you. I just found I misunderstood the "Maximum number candidates to return" option for limiting the number of entries to reconcile. After reducing the numbers of entries to reconcile, the percentage of progress went much faster. It was a couple of seconds for each entry indeed.

Both the web UI and the logging didn't show actual activities of reconciliation. Is there some way for me to tweak the logging to show which entry is being reconciled?

Thanks for the suggestion of using Wireshark. Is there a way to configure OpenRefine to use an http proxy? https://www.charlesproxy.com is a tool that is easier to use for http API debugging.

**Comment by wetneb** [comment]
I don't know about the proxy. I have migrated the issue to the relevant repository, since it is a server-side issue.
