### ISSUE TITLE
Wikidata schema - SPARQL property path

### ISSUE THREAD

**Issue by LibrErli** [OpenRefine/OpenRefine#2009]
if i enter directly the property id in the wikidata schema editor: the autocomplete dropdown list shows me 2 entries - the property itself and an entry called SPARQL: PID property path.

i don't know if this is necessary under some special conditions.
![grafik](https://user-images.githubusercontent.com/18214283/55618835-c0553a80-5797-11e9-845b-0bc086b64621.png)

(OpenRefine 3.2 beta)

**Comment by wetneb** [comment]
Moving to appropriate repository: https://github.com/wetneb/openrefine-wikibase/issues/62
