### ISSUE TITLE
Clipboard paste on Turtle file content uploads forever

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#2012]
**Describe the bug**
Pasting the contents of a valid Turtle file into the Clipboard importer causes forever loading of /command/core/get-importing-job-status

**To Reproduce**
1. Click Create Project from Clipboard
2. Paste example Turtle file content
3. Click Next

**Current Results**
See forever uploading and continuous logging in console for /get-importing-job-status

**Expected behavior**
Pasting file content and uploading should behave the same as importing a file with the same content from your computer.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version: Firefox latest
 - JRE or JDK Version: java version "1.8.0_201"

**OpenRefine (please complete the following information):**
 - Version:  OpenRefine Trunk

**Datasets**
test.ttl  
https://drive.google.com/file/d/1AG_u-ZHfPVqhUZ0l4rtcBZ8DB-ScScLG/view?usp=sharing

**Comment by ostephens** [comment]
Checked and this behaviour is also present in 3.1

**Comment by ostephens** [comment]
Also seems to affect n-triple data. e.g.
```
<http://www.w3.org/2001/sw/RDFCore/ntriples/> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Document> .
 <http://www.w3.org/2001/sw/RDFCore/ntriples/> <http://purl.org/dc/terms/title> "N-Triples"@en-US .
 <http://www.w3.org/2001/sw/RDFCore/ntriples/> <http://xmlns.com/foaf/0.1/maker> _:art .
 <http://www.w3.org/2001/sw/RDFCore/ntriples/> <http://xmlns.com/foaf/0.1/maker> _:dave .
 _:art <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> .
 _:art <http://xmlns.com/foaf/0.1/name> "Art Barstow".
 _:dave <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> .
 _:dave <http://xmlns.com/foaf/0.1/name> "Dave Beckett".
```
