### ISSUE TITLE
Importing CSV files in Simplified Chinese

### ISSUE THREAD

**Issue by Sterne5a** [OpenRefine/OpenRefine#2013]
Hi,

Am eager to use OpenRefine to clean text in Simplified Chinese but none of the common encodings listed seem to work on my CSV file as the characters still look garbled. 

Can someone help? Thank you.

**Comment by wetneb** [comment]
@Sterne5a can you share your CSV, or an excerpt of it?

**Comment by Sterne5a** [comment]
[test_CN_data.xlsx](https://github.com/OpenRefine/OpenRefine/files/3067911/test_CN_data.xlsx)
Here's a sample of what I did the test with.

**Comment by ostephens** [comment]
Thanks @Sterne5a can you confirm that you are starting with this XLSX file, rather than a CSV file?

**Comment by ostephens** [comment]
Importing that XLSX file into OpenRefine 3.1 seems to work without any problems

**Comment by Sterne5a** [comment]
Hi,

I'm using OpenRefine 3.2-beta. Unfortunately neither the CSV file nor the XLSX file were readable.
![screenshot1](https://user-images.githubusercontent.com/49467084/56128101-5582db00-5fb1-11e9-97b7-aa590bf0475a.JPG)
![screenshot2](https://user-images.githubusercontent.com/49467084/56128108-5b78bc00-5fb1-11e9-940c-7d8aec3ea16e.JPG)

**Comment by wetneb** [comment]
@Sterne5a for XLSX, it is a known bug that will be fixed in the final 3.2 version. Can you share the CSV that you are trying to import?

**Comment by Sterne5a** [comment]
Hi,

@wetneb : I could not attach the CSV file to this message as the file format isn't supported by this forum. But here's the xlsx file. Any idea when the final 3.2 version will be fixed? Thanks.

[test_CN_data.xlsx](https://github.com/OpenRefine/OpenRefine/files/3110347/test_CN_data.xlsx)

**Comment by wetneb** [comment]
Closing as non reproducible per the above.
