### ISSUE TITLE
Text Facet numeric value element is duplicated when clicked on

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#2021]
**Describe the bug**
A 2nd unnecessary element is created when clicking on a numeric value in a Text Facet.

**To Reproduce**
1. Have a column with strings and numeric values.
2. Click on Facet -> Text Facet
3. Click on one of the numeric values in the Facet.

**Current Results**
After clicking on one of the numeric values in the Facet, a 2nd element is created and highlights in Orange color.

**Expected behavior**
2nd element is not needed, just highlight and select on the element that the user clicked on.

**Screenshots**

BEFORE THE CLICK ON 222.0:
![Capture11](https://user-images.githubusercontent.com/986438/56233444-ba3d4480-6048-11e9-982b-f05ae29e1d25.PNG)

AFTER THE CLICK ON 222.0:
![Capture12](https://user-images.githubusercontent.com/986438/56233452-bc070800-6048-11e9-8f42-c3a5897fdc84.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: JRE 1.8.0_181

**OpenRefine (please complete the following information):**
 - Version: OpenRefine Trunk

**Comment by ostephens** [comment]
This will be addressed as part of #2018

**Comment by kushthedude** [comment]
@thadguidry I think this is not reproducible now, I just tried it several time ?

**Comment by thadguidry** [comment]
Fixed!  (no idea which commit fixed it however)  so closing.

**Comment by kushthedude** [comment]
Might had been some error in library or any cdn which would have fixed it.
