### ISSUE TITLE
CI: Couldn't determine a download url for 11-GPL on linux-x64

### ISSUE THREAD

**Issue by olleolleolle** [OpenRefine/OpenRefine#2028]
**Describe the bug**

When using openjdk11, `~/bin/install-jdk.sh` fails to install.

Example failed build: https://travis-ci.org/OpenRefine/OpenRefine/jobs/521872334#L416

**To Reproduce**

1. Go to https://travis-ci.org/OpenRefine/OpenRefine/jobs/521872334#L416
2. See error

**Current Results**

```
$ export JAVA_HOME=~/openjdk11
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/openjdk11" --workspace "/home/travis/.cache/install-jdk" --feature "11" --license "GPL" --cacerts
install-jdk.sh 2019-04-17
Couldn't determine a download url for 11-GPL on linux-x64
The command "~/bin/install-jdk.sh --target "/home/travis/openjdk11" --workspace "/home/travis/.cache/install-jdk" --feature "11" --license "GPL" --cacerts" failed and exited with 1 during .
Your build has been stopped.
```

**Expected behavior**

I expect it to install a JDK.

**OpenRefine (please complete the following information):**
 - Version, current `master`

---

**Further development notes**:

- You can open a new PR re-enabling `openjdk11`, to debug this issue

**Comment by wetneb** [comment]
In the meantime I have downgraded it back to openjdk9, so that we can assess other PRs in peace.

**Comment by olleolleolle** [comment]
Perhaps this is a way forward:
https://github.com/sormuras/bach/commit/fe56033959d684f85ba966b0f0760a23c34c9eba

**Comment by wetneb** [comment]
Yeah hopefully Travis will pick that up! I don't think we should/could do that on our side.
