### ISSUE TITLE
remove references to freebase in messages

### ISSUE THREAD

**Issue by msaby** [OpenRefine/OpenRefine#2029]
**Describe the bug**
One day I had a warning message mentioning Freebase, in OR 3.1... Not sure of it but I think it was this one in https://github.com/OpenRefine/OpenRefine/blob/e57228a1306f19313c52d4a967866f193fc02dfb/main/webapp/modules/core/langs/translation-en.json : 
 
"I You haven't done any schema alignment yet,\n so there is no triple to export.\n\n Use the Freebase > Edit Schema Alignment Skeleton...\n command to align your data with Freebase schemas first."

Maybe there are others.

**To Reproduce**

**Current Results**
What results occured or were shown.

**Expected behavior**
A clear and concise description of what you expected to happen or to show.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows 10, Linux, Ubuntu 18.04]
 - Browser Version: [e.g. Chrome 19, Firefox 61, Safari, NOTE: OpenRefine does not support IE but works OK in most cases]
 - JRE or JDK Version:[output of "java -version" e.g. JRE 1.8.0_181]

**OpenRefine (please complete the following information):**
 - Version [e.g. OpenRefine 3.0 Beta] : Openrefine 3.1

**Datasets**
If you are allowed and are OK with making your data public, it would be awesome if you can include or attach the data causing the issue or a URL pointing to where the data is.
If you are concerned about keeping your data private, ping us on our [mailing list](https://groups.google.com/forum/#!forum/openrefine)

**Additional context**

**Comment by wetneb** [comment]
This is relatively easy: you can search for the string "Freebase" in the translations (file `main/webapp/modules/core/langs/translation-en.json`). For each string which contains this word:
* either this UI message is still used somewhere in the UI - that means the corresponding dialog / menu / button needs to be removed there;
* or it is just not used anywhere in the code.
In both cases the message should be removed, in English and all translations.
