### ISSUE TITLE
Numeric values are not green or right-justified in Windows 10 64-bit

### ISSUE THREAD

**Issue by jerrywaller** [OpenRefine/OpenRefine#2030]
**In Windows 10 64-bit, numeric values are not visually distinct from character values**

**To Reproduce**
On Windows 10 64-bit, running the 64-bit or 32-bit Java Runtime Environment, create a new project, selecting `Parse cell text into numbers, dates, ...` 

OR 

From within a current project, convert a column of numerals into numeric values by "Edit Cells --> Common Transforms --> To Number"; or transform a column of numerals into numeric values with the GREL `toNumber(value)`

**Current Results**
In Windows 10, the numeric values are neither green nor right-justified. In MacOS 10.14.4, numeric values are green and right justified.

**Expected behavior**
Numeric values in Windows 10 should be green and right-justified (visually distinct from character values), just as they are in MacOS.

**Screenshots**
![openrefine_char_num](https://user-images.githubusercontent.com/3990374/56664989-318d5c80-6677-11e9-913e-382fc179f7a0.PNG)
![Screen Shot 2019-04-24 at 08 40 49](https://user-images.githubusercontent.com/3990374/56665041-4f5ac180-6677-11e9-806e-95239c31163f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version: Firefox 66.0.3
 - JRE or JDK Version: JRE 1.8.0_211

**OpenRefine (please complete the following information):**
 - Version: OpenRefine 3.2 beta

**Datasets**
[01-exercise.tsv](https://github.com/jerrywaller/SNCA2019/blob/master/01-exercise.tsv)

**Comment by ostephens** [comment]
@jerrywaller thanks for reporting this issue.

I'm aware (and have submitted a fix for) this issue in OpenRefine 3.2 beta but that affected all platforms as far as I know. Can you double check that on the Mac you were definitely using 3.2 beta?

**Comment by jerrywaller** [comment]
Ah! Yes, sorry. The Mac is running 3.1. I can test the beta on another Mac.

**Comment by ostephens** [comment]
Thanks @jerrywaller - I don't think you need to - that problem definitely exists in 3.2 beta and I've no reason to think it doesn't apply no matter which platform you use

**Comment by ostephens** [comment]
Fixed by #2008
