### ISSUE TITLE
Add column by fetching URLs fails on a HTTP 200 response

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#2031]
**Describe the bug**
In some cases "Add column by fetching URLs" fails to populate content into the column, even though the URL request gets a 200 OK response and accessing the URL via curl or a browser returns content

**To Reproduce**
1. Create a cell populated with the URL "https://www.trismegistos.org/place/18340/json"
2. Use "Add column by fetching URLs", check option to store error
3. Click OK
4. See new column added with cell displaying error `HTTP error 200 : OK | `

**Expected behavior**
Expected cell to be populated with JSON returned from https://www.trismegistos.org/place/18340/json

**OpenRefine (please complete the following information):**
 - tested with OpenRefine 3.1 and OpenRefine 3.2 beta

**Additional context**
Reported on Google Group https://groups.google.com/d/msg/openrefine/YAXrXTIXk-k/MQjxxuI_DAAJ
@thadguidry did a CURL dump for the URL
```
THAD's CURL DUMP on Windows 10...

THAD@DESKTOP-TJUMQT0 MINGW64 ~
$ curl -v https://www.trismegistos.org/place/18340/json
* Expire in 0 ms for 6 (transfer 0x66ac80)
* Expire in 1 ms for 1 (transfer 0x66ac80)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Expire in 0 ms for 1 (transfer 0x66ac80)

*   Trying 134.58.134.15...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x66ac80)
* Connected to www.trismegistos.org (134.58.134.15) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [106 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [3160 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=BE; L=Leuven; O=Katholieke Universiteit te Leuven; OU=ICTS - CeIF-Net; CN=trismegistos.org
*  start date: Feb 21 00:00:00 2018 GMT
*  expire date: Feb 25 12:00:00 2021 GMT
*  subjectAltName: host "www.trismegistos.org" matched cert's "www.trismegistos.org"
*  issuer: C=NL; ST=Noord-Holland; L=Amsterdam; O=TERENA; CN=TERENA SSL CA 3
*  SSL certificate verify ok.
} [5 bytes data]
> GET /place/18340/json HTTP/1.1
> Host: www.trismegistos.org
> User-Agent: curl/7.64.0
> Accept: */*
>
{ [5 bytes data]
< HTTP/1.1 200 OK
< Date: Wed, 24 Apr 2019 21:22:01 GMT
< Server: Apache/2.4.28 (Unix) PHP/5.5.38
< X-Powered-By: PHP/5.5.38
< Access-Control-Allow-Origin: *
< Content-Encoding: gzip
< Vary: Accept-Encoding
< Content-Length: 654
< Content-Type: application/json; charset=UTF-8
<
{ [654 bytes data]
100   654  100   654    0     0   1236      0 --:--:-- --:--:-- --:--:--  1233{
    "type": "Feature",
    "geometry": {
        "type": "Point",
        "coordinates": [
            6.216667,
            36.483333
        ]
    },
    "title": "Castellum Phuensium",
    "uri": "https://www.trismegistos.org/place/18340",
    "TM_Geo_ID ": "18340",
    "names": {
        "latin": {
            "name": "Castellum Phuensium - Pagus Phuensium",
            "language": "215"
        }
    },
    "links": {
        "broad matches": [],
        "close matches": [],
        "exact matches": []
    },
    "properties": {
        "status": "camp: castellum; pagus",
        "country": "Algeria",
        "provincia": "Numidia"
    }
}
* Connection #0 to host www.trismegistos.org left intact
```

**Comment by zengchu2** [comment]
Hi, I found the source of error and I think this is a tricky case ... 
**Souce of Error**
From `ColumnAdditionByFetchingURLsOperation.java`, when calling `ParsingUtilities.inputStreamToString`, the encoding type is _gzip_, which is not supported by `InputStreamReader` in `ParsingUtilities.inputStreamToString` and there is an IOException.

**Fix**
I tried to add up a `GZIPInputStream` to parse the inputstream, but the inputstream itself is not in GZIP format, it can be parsed directly using a `InputStreamReader` (If we set encoding to be UTF-8).

But I think it worths adding a GZIPInputStream parser here to parse gzip responses.

**Comment by wetneb** [comment]
Great investigation, thanks! It sounds like fixing `ParsingUtilities.inputStreamToString` would likely be quite useful, since it might be used in other places in the code (create a project by fetching a URL, for instance?).

**Comment by thadguidry** [comment]
All of this gets a bit easier if we begin to utilize a smarter HTTP library.  I highly suggest [OKHttp](https://square.github.io/okhttp/).
1. https://square.github.io/okhttp/4.x/okhttp/okhttp3/-response-body/
2. https://square.github.io/okhttp/recipes/#parse-a-json-response-with-moshi-kt-java

**Comment by zengchu2** [comment]
Hi, I just managed to use GZIPInputstream to parse gzip compressed response body , I will take a look at the OKHttp library in a short time
