### ISSUE TITLE
Cursor should show busy when Clustering dialog is updating in the background

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#2033]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
When working with many rows > 100000 and sliding the "# Rows in Cluster", it appears that nothing is happening for over 10 seconds and the entire dialog and all elements are no longer interactive or respond to user input.  The user is unaware that something is happening in the background.

**Describe the solution you'd like**
We should use a CSS property like `cursor: wait;` or `document.body.style.cursor = 'wait';`  in clustering-dialog.js so that users know "SOMETHING" is happening after an update or computeDistribution is fired. 

**Additional Context**
https://stackoverflow.com/questions/9681080/changing-cursor-to-waiting-in-javascript-jquery

**Comment by wetneb** [comment]
Removing the 3.2 milestone as this is not a bug that was introduced recently - we can fix it before 3.2 of course, much like any other issue, but it should not be required for the release.

**Comment by thadguidry** [comment]
It's an enhancement/feature that we wanted to see happen for 3.2
I guess your saying it's too hard to implement quickly?  If that is the case, sure, we can delay this.

**Comment by wetneb** [comment]
> It's an enhancement/feature that we wanted to see happen for 3.2

Where was this discussed?

**Comment by thadguidry** [comment]
NICAR feedback and R lang meetup in Dallas. (User groups)  I imagine it's also going to come up again in IRE 2019 next weekend.  It is something that users see as "unexpected" handling when using an interactive dialog where they expect some feedback but are given none.

Its fine we can keep the priority at Medium and address it when we have time.
On that note:  We have traditionally prioritized on what our Users want...not what developers think can be knocked out quickly.  And used the priority label for that.  Milestones are what we plan to deliver in a release.  I think we should do more effective planning on releases, but I understand that right now we are putting much at your mercy :) since our core developer contributions have dwindled and life events are happening and pulling folks away.  It happens, no big deal.  But still we should do better planning I guess.

Can you offer some suggestions on how we can plan what goes into a Milestone better?

**Comment by wetneb** [comment]
> Can you offer some suggestions on how we can plan what goes into a Milestone better?

Yes. Only add an issue to a milestone if either
* you are in a position to provide a pull request fixing this issue relatively soon;
* or there is agreement in the dev team that this is something we want to fix before a specific release.

It is not okay to unilaterally pick random issues you are interested in and expect that a volunteer will accept to work on them before a given release.

**Comment by thadguidry** [comment]
@wetneb I have no such expectations from volunteers.  They are free to work on whatever they want at anytime.  Tony didn't have the time to work on this when I asked him, and so this stems the conversation that we are in now.  I ask folks on the outside to help...and then that help doesn't arrive...so we make adjustments to our Milestone issues and commitments.  Its all good Antonin, don't get too worried about planning that sometimes doesn't plan out. :-)

The Milestone label is just a label, it involves no commitment, but it does help us track what we are planning to go into a Release or not.  Removing the Milestone label 3.2 on this issue was the right move, since this enhancement won't be part of 3.2

**Comment by wetneb** [comment]
Great! And also, maybe let's only use the word *we* when it actually refers to more than one person? It would make things clearer :) You are more than welcome to weigh in about the importance of each issue for users and report feedback from any meeting you attended - just leave the milestone attribution to those who do the fixes - it's a do-ocracy!

**Comment by thadguidry** [comment]
I think this problem is solved mostly now...dunno
I cannot reproduce it when I use even a large 1 million row with 500+ unique clusters throughout the rows...
The widget sliders perform well now.
This might have been some bug previously that is now fixed... or... OpenJDK 11 works really fast now with string handling in general compared to JDK 8 ?

Here's my test set attached ...
[Clustering_Test.txt](https://github.com/OpenRefine/OpenRefine/files/3614132/Clustering_Test.txt)

You can apply a Text Length Facet first... and slide it so that only shows rows with length of less than 100 chars... then try the Clustering algorithms and parameters...
when I do, all the sliders seem to work just fine.

So this might only be a problem when there are 1000's of unique clusters?

**Comment by thadguidry** [comment]
Here's a better testset for binning performance and KNN operations. 370,000 English words.
https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt

Interestingly, this test set also shows the extreme performance hit on the Javascript side where it  builds tons of HTML fragments (when there are many clusters) for the clustering view (a terrible way to approach the need).  Something we should probably handle on server-side as arrays and then push out to client-side once the Clustering grid view is needed.
![Annotation 2019-09-17 100854](https://user-images.githubusercontent.com/986438/65054848-db75ca00-d933-11e9-843e-f791208937fb.png)

**Comment by thadguidry** [comment]
@darecoder1999 Hi Ekta, so I've played with this a bit more and cannot reproduce my original description, likely because we fixed the other bug #2152 which is great!

So now... the only thing left is the false impression that users get that they can still manipulate the facet sliders in 2. `facetContainer` while 1. `compute-clusters` is running.

![image](https://user-images.githubusercontent.com/986438/83650928-8855ad00-a57e-11ea-98b0-2926bf5b720c.png)


So for this issue we can cancel your PR #2419 and close this issue specifically since it is no longer needed.

I'll open a new issue for the above remaining problem to "grey out" the `facetContainer` while `/command/core/compute-clusters` is running.

**Comment by darecoder1999** [comment]
@thadguidry: It's great the bug is resolved nearly as I wasn't able to reproduce exactly what you were trying to convey in the issue description and so I wasn't able to resolve the issue sadly. :( 

If I could be able to resolve this new issue you are pointing to, then definitely I'll raise a valid PR for that. :)

**Comment by thadguidry** [comment]
@darecoder1999 should be a piece of cake for you if you have the time... See new issue #2675
