### ISSUE TITLE
create column names from a specific row

### ISSUE THREAD

**Issue by msaby** [OpenRefine/OpenRefine#2035]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
It would be nice if OpenRefine could create column names from the 1st row, or a specific row

**Describe the solution you'd like**
A menu in the GUI for copying the values of a row into column names

**Describe alternatives you've considered**

**Additional context**

**Comment by wetneb** [comment]
This is already supported by quite a few importers - are there workflows where this cannot be done at import time?

**Comment by wetneb** [comment]
Closing this as we don't have a good use case for this - using the "header lines" options in the importers should be enough. Feel free to reopen if you can show a concrete workflow where this does not work.
