### ISSUE TITLE
Improve incomplete schema error message

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2039]
When a user tries to save a schema, upload statements or generate quickstatements, we throw an error message about the schema being incomplete. This is currently detected at parsing time in the backend. Therefore the error message does not say exactly what in the schema is missing/incorrect. We could add some front-end validation in addition to that, in order to be able to say: "missing subject item", "missing quantity in P234 statement", and so on.

Some front-end validation already exists (highlighting empty fields in red) but this does not seem to be used for the subject item - we could add that.

**Comment by hiterdorina** [comment]
Hi, I would like to work in this issue, related to a school project. Can I work on it?

**Comment by wetneb** [comment]
Sure!

**Comment by wetneb** [comment]
This has been fixed (not sure by which PR), we now have detailed information about where in the schema an element is missing.
