### ISSUE TITLE
Column Reorder leaves undeleted hidden cells.

### ISSUE THREAD

**Issue by stanakaj** [OpenRefine/OpenRefine#2041]
hi, I appriciates you for maintaining this nice tool.

**Describe the bug**
Column Reorder leaves undeleted hidden cells in case of removing column.
So you get unexpected cell data in a some condition.

**To Reproduce**
1. import a data set
![pic1](https://user-images.githubusercontent.com/44893868/57740654-de497f80-76f3-11e9-9faa-fec9e0de0c9a.png)

2. remove columns with Reorder
![pic2](https://user-images.githubusercontent.com/44893868/57740660-e73a5100-76f3-11e9-9853-c578de6a6072.png)
above instance : remove 'b', 'c' columns with Reoerder

3. split a left column
![pic3](https://user-images.githubusercontent.com/44893868/57740676-f7eac700-76f3-11e9-86a6-7f05b50299e0.png)
above instance : split 'a' column with separator '|'

4. you get some unexpected data
above instance : g,h,i is unexpected split data 

**Desktop :**
anywhere, I guess

**OpenRefine :**
 - Version 3.1

**Datasets**
project of above instance
[split-issue.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/3180421/split-issue.openrefine.tar.gz)

I  made a patch for this issue.

**Comment by thadguidry** [comment]
Hi @stanakaj Thanks for this bug report !  Are you going to be submitting the patch as a Pull Request in Github?
