### ISSUE TITLE
Labels for Text filter checkboxes are linked to first instance

### ISSUE THREAD

**Issue by yarl** [OpenRefine/OpenRefine#2044]
**Describe the bug**
Labels for checkboxes in text filters are resuing the same `ref`s and checkboxes are reusing the same `id`s

**To Reproduce**
1. Add multiple Text filters

**Current Results**
https://streamable.com/forh6

**Comment by wetneb** [comment]
Thanks for the report! If you are interested in submiting a pull request for that I am available for any help you might want :) The relevant lines are here:
https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/scripts/facets/text-search-facet.js#L104-L105

**Comment by mtricht** [comment]
@wetneb I believe this issue can be closed
