### ISSUE TITLE
build from source releases fails due to missing git directory

### ISSUE THREAD

**Issue by travisghansen** [OpenRefine/OpenRefine#2047]
**Describe the bug**
build from source releases fails due to missing git directory

**To Reproduce**
1. Download release source (ie:  wget https://github.com/OpenRefine/OpenRefine/archive/3.1.tar.gz)
1. Run `./refine build`

**Current Results**
```
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.4:revision (get-the-git-infos) on project main: .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :main
Error: Error while running maven task 'process-resources'
The command '/bin/sh -c ./refine build' returned a non-zero code: 1
```

**Expected behavior**
A clean build

**Desktop (please complete the following information):**
 - OS: linux (using latest `alpine` docker image)
 - JRE or JDK Version:
```
java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```

**OpenRefine (please complete the following information):**
 - Version: OpenRefine 3.1

**Additional context**
Trying to build docker images with a few extensions. Upstream images would be appreciated :D

**Comment by wetneb** [comment]
Thanks, that's annoying indeed. One possible workaround would be to add a minimal `.git` folder in these archives, but given that they are generated by GitHub I do not think this is possible. I will try to find a clean workaround before releasing 3.2.

**Comment by travisghansen** [comment]
Cool thanks for the update!

**Comment by wetneb** [comment]
In the meantime are you able to use the linux release at all, or is the presence of compiled files and jars there a problem?

**Comment by travisghansen** [comment]
Well, I traditionally had a handful of extensions I built into the image a couple which require the source to build against.  I'm honestly not super familiar with the process and use the project sparingly but I can send over the list of plugins I've bundled (they may not even work anymore) when back to my desk..

**Comment by travisghansen** [comment]
So here are the extensions I'm installing:

```
RUN wget https://github.com/ryanfb/georefine/archive/master.zip && \
    unzip master.zip && \
    rm master.zip

RUN wget https://github.com/fadmaa/grefine-rdf-extension/releases/download/v0.9.0/orefine-rdf-extension-0.9.zip && \
    unzip orefine-rdf-extension-0.9.zip && \
    rm orefine-rdf-extension-0.9.zip && \
    rm -rf __MACOSX/ && \
    mv orefine-rdf-extension-0.9/ rdf-extension

RUN wget -O - --no-check-certificate https://github.com/giTorto/extraCTU-plugin/archive/master.tar.gz | tar -xz && \
    cd extraCTU-plugin-master && \
    ant clean build

RUN wget -O - --no-check-certificate https://github.com/giTorto/geoXtension/archive/master.tar.gz | tar -xz && \
    cd geoXtension-master && \
    ant clean build

RUN wget -O - --no-check-certificate https://github.com/giTorto/Refine-NER-Extension/archive/master.tar.gz | tar -xz && \
    cd Refine-NER-Extension-master && \
    ant clean build

```

Looks like the latter 3 require building..

**Comment by wetneb** [comment]
okay! Any chances you can use `git clone` and then checkout the release tag? That should work:
```
git clone https://github.com/OpenRefine/OpenRefine
git checkout 3.1
# add your extensions
./refine build
```

**Comment by travisghansen** [comment]
Sure I wanted to avoid that as it takes much longer to download and results in a much larger docker image than necessary. I'm not super concerned about updating right away.

Mostly just wanted to make you aware the source images are not useful in their current state.
