### ISSUE TITLE
Feature Request: Export SqlDump

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#205]
_Original author: mcnamara.tim@gmail.com (November 15, 2010 01:02:33)_

Adding an ability to export the project as a SQL dump file[1], possibly in MySQL's format, would be beneficial. 

[1] http://dev.mysql.com/doc/refman/5.1/en/mysqldump.html

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=205_

**Comment by thadguidry** [comment]
#1277 is being worked on to handle this issue now ! :) 
#1277 will also handle the case of issue #12 MySQL Support

**Comment by wetneb** [comment]
I believe this also connects with metadata support as we would need column types to export the project as a SQL table. #778 #1096

**Comment by stevevance** [comment]
@wetneb I would like to be able to export all columns as "text" and then deal with them later in PostgreSQL/MySQL.

**Comment by thadguidry** [comment]
@stevevance we already have export as CSV which you can load into any database. This feature was to connect to a database and perform a CREATE TABLE with the selected columns in OpenRefine.  Is there something more than that feature you need ?  Let us know how you envision it working.

**Comment by stevevance** [comment]
I would like OpenRefine to export SQL with two options: (1) the CREATE statement includes a datatype for each column ("text", "varchar", "int", "bigint") based on how OpenRefine reads the data in that column; (2) the CREATE statement uses a generic "text" datatype for every column. 

For large datasets, with many columns, it's very time consuming to write or rewrite a CREATE statement that matches the (2) option above.

I normally use a GUI program to import CSV files called Navicat, instead of the COPY command in PostgreSQL.

**Comment by thadguidry** [comment]
@stevevance Right, so you'd like a nice dialog that let's you set all those column options, AND even an option that says "Set the selected Datatype on all columns" :)

**Comment by stevevance** [comment]
@thadguidry I found a program that will write CREATE statements! It's `csvsql`, which is part of `csvkit`: http://csvkit.readthedocs.io/en/0.9.1/scripts/csvsql.html

**Comment by thadguidry** [comment]
@tcbuzor I think it makes sense to have the dialog expose a dropdown for the Database vendor, and then another showing the enumerated list of Datatypes supported by that Database vendor, along with the option to check to make ALL selected OpenRefine columns to be set as the users selected SQL Datatype.  We can reuse part of our existing export dialog that currently exposes the individual Columns options.

**Comment by tcbuzor** [comment]
is someone working on this?

**Comment by wetneb** [comment]
@tcbuzor the floor is yours!

**Comment by tcbuzor** [comment]
@thadguidry , @wetneb  should this generate  a CREATE statement as well or just an INSERT statement?

**Comment by thadguidry** [comment]
@tcbuzor CREATE statement, and truncated to first 30 bytes (whitespace collapsed) of the OpenRefine Project name.

**Comment by tcbuzor** [comment]
@thadguidry Why the first 30 bytes? The user should be allowed to change the table name as he/she chooses. We also need to allow the user specify the column type and sizes...

**Comment by thadguidry** [comment]
@tcbuzor Oracle < 12.1 has a table name limit of 30 chars.

**Comment by tcbuzor** [comment]
The column names also have a limit right?

**Comment by thadguidry** [comment]
@tcbuzor Yeap column name length is 30 chars if its Oracle < 12.1

**Comment by tcbuzor** [comment]
Hi All,
What do you guys think about the proposed UI for database export attached here:
<img width="808" alt="screen shot 2018-03-20 at 8 29 52 pm" src="https://user-images.githubusercontent.com/33398757/37691233-5198d8b2-2c7e-11e8-8d72-d2b4e5aec0c0.png">

**Comment by thadguidry** [comment]
@tcbuzor I would also add hover text explaining what goes into the input boxes when you click into like we have on Wikidata Schema alignment that @wetneb has on his wikidata-extension branch.

**Comment by tcbuzor** [comment]
I'll take a look and implement something similar.

**Comment by tcbuzor** [comment]
Download tab below:
<img width="805" alt="screen shot 2018-03-20 at 11 19 06 pm" src="https://user-images.githubusercontent.com/33398757/37694438-3384c342-2c95-11e8-8b8c-856ae940ec5e.png">

**Comment by thadguidry** [comment]
@tcbuzor Should that say instead "Include Schema" ?  Wondering if "Include Structure" might confuse folks, because its kind of an Oracle naming convention, rather than universal.  Also re-read my comment above, I've updated it (don't use hover text, just text somewhere "input max values into boxes as necessary" or some such)

**Comment by stevevance** [comment]
I prefer to use TEXT instead of VARCHAR, and I would also like to see a NUMERIC (decimal/float) option.

**Comment by thadguidry** [comment]
We delivered the basic SQL Export functionality in OpenRefine 3.0 ( Thanks @tcbuzor ! )
Additional Features can be requested by opening a New Issue.
