### ISSUE TITLE
Export > Triple loader refers to incorrect info

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#206]
_Original author: mcnamara.tim@gmail.com (November 15, 2010 01:21:26)_

<b>What steps will reproduce the problem?</b>
1. Start a clean project (or delete current schemas)
2. Click Export &gt; Triple loader 
3. Watch alert 

What do you see?

   You haven't done any schema alignment yet,
   so there is no triple to export.

   Use the Freebase &gt; Edit Schema Alignment Skeleton...
   command to align your data with Freebase schemas first.

What's wrong?

I can't find the  &quot;Edit Schema Alignment Skeleton&quot; button. The Freebase button (to the right of &quot;Extensions&quot;) has:

   Align to Freebase's schemas...
   Load into Freebase...

---

   Browse data load details...
   Import QA data

<b>Please use labels and text to provide additional information.</b>

I'm running Ubuntu 10.10, SVN revision 1858

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=206_

**Comment by wetneb** [comment]
This should be adapted so that Freebase is not mentioned at all.

**Comment by thadguidry** [comment]
@wetneb Is this fixed now, where Freebase is not mentioned any longer ? If so, let's close this.

**Comment by wetneb** [comment]
"Triple loader "and "MQL write" export options should just be removed as they were specific to Freebase.
