### ISSUE TITLE
Support JDK 12

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2067]
We could investigate if JDK 12 is supported.

**Comment by wetneb** [comment]
The only issue I can find for now is a deprecation warning in Jython:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.core.PySystemState (file:/tmp/openrefine-3.1/webapp/extensions/jython/module/MOD-INF/lib/jython-standalone-2.7.1.jar) to method java.io.Console.encoding()
WARNING: Please consider reporting this to the maintainers of org.python.core.PySystemState
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
https://github.com/jythontools/jython/issues/146

We should look into graal-python to support Python 3, as it is also more actively developed.

**Comment by wetneb** [comment]
One issue I get is packaging OpenRefine for Mac using Java 12 on the build machine. The current version of the maven plugin (1.2.0) is known not to work for such Java:
https://github.com/federkasten/appbundle-maven-plugin/issues/61
We could try using a fork of this plugin.

**Comment by thadguidry** [comment]
@wetneb fork, fix, contribute back.  And thanks so much for spending incredible amounts of time in our OpenRefine ecosystem !  You really are impressing the hell out of me and others !

**Comment by wetneb** [comment]
Actually it should be fine without forking, I can just do the release process with Java 8.

**Comment by wetneb** [comment]
So I am not aware of any blocker for this anymore. Let's consider it solved, we can reopen it later if issues arise with 3.2, which should hopefully be tested more thoroughly by our user base since #2069 is solved.
