### ISSUE TITLE
Duplicate serialization of operation types

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2068]
**Describe the bug**
Operation type can be added more than once to JSON serialization, as in the following example:
```
{"op":"core/recon",
"engineConfig":{"facets":[],"mode":"row-based"},"columnName":"institution","config":{"mode":"standard-service","service":"https://reconcile.ror.org/reconcile","identifierSpace":"http://ror.org/organization","schemaSpace":"http://ror.org/ns/type.object.id","type":{"id":"/ror/organization","name":"/ror/organization"},"autoMatch":true,"columnDetails":[],"limit":0},
"description":"Reconcile cells in column institution to type /ror/organization",
"op":"core/recon"
}
```
This is deserialized correctly by the current Jackson code but not by the previous org.json code. This makes it impossible to open projects made with OpenRefine 3.2-beta with 3.1.

**Comment by thadguidry** [comment]
Didn't we have an issue about this issue before?  Reference # please? or am I remembering things wrong about an issue with not opening projects with 3.1 versus this issue with not opening projects with 3.2?

**Comment by wetneb** [comment]
Not sure, we might have had similar issue on other classes. It's clearly worth fixing before 3.2 in any case.
