### ISSUE TITLE
Feature Request: Export to Python pickle

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#207]
_Original author: mcnamara.tim@gmail.com (November 15, 2010 01:47:06)_

Would it be possible to use the Jython extension to provide serialised Python objects of the data?

Refs:
- http://code.activestate.com/recipes/252131-pickle-objects-under-jython/

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=207_
##

**Comment by wetneb** [comment]
Pickle is not designed for that at all. It has poor interoperability and portability. This would require choosing a Python data structure to represent the tables.
