### ISSUE TITLE
Thesaurus for Graphic Materials Reconciliation Extension

### ISSUE THREAD

**Issue by mlhale7** [OpenRefine/OpenRefine#2079]
**Describe the bug**
I am unable to use a "legacy" method to reconcile Library of Congress terms from the Thesaurus of Graphic Materials. I am following these instructions to achieve this - https://github.com/cmharlow/c4lMDCpres/blob/master/breakout_workflows/deriRDFexample.md

**To Reproduce**
1. Go to RDF Extension and click on Add reconciliation service based on an RDF File
2. Add the file from here - http://id.loc.gov/static/data/downloads/vocabularygraphicMaterials.nt.both.zip and select N-Triple as the format
3. Select Other and paste in http://www.loc.gov/mads/rdf/v1#authoritativeLabel
4. Service cannot be added

**Current Results**
Interface will not resolve and service is not added

**Expected behavior**
Add a new reconciliation service for the Thesaurus for Graphic Materials

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave Version 10.14.5
 - Browser Version: Chrome Version 75.0.3770.100 (Official Build) (64-bit)
 - JRE or JDK Version: 1.8.0_161

**OpenRefine (please complete the following information):**
 - Version 2.7

**Datasets**
Use the following data for the RDF file http://id.loc.gov/static/data/downloads/vocabularygraphicMaterials.nt.both.zip

**Comment by wetneb** [comment]
Hi @mlhale7, thanks for this report. Have you considered upgrading to OpenRefine 3.1 (with the corresponding version for the RDF extension)?

**Comment by mlhale7** [comment]
@wetneb - I just updated to 3.1 and re-added the RDF extension. I'm currently getting the same behavior. Any suggestions? How long should it take for the reconciliation service to be added?

**Comment by mlhale7** [comment]
@wetneb - I finally got it to work! It's slow to load, but functional. Thank you.
