### ISSUE TITLE
Enabling a conditional process to upload to Wikidata

### ISSUE THREAD

**Issue by yayamamo** [OpenRefine/OpenRefine#2080]
## Background
When uploading some data to Wikidata, there are cases where items have already existed and their labels for some languages have been filled. In this situation, there are two cases for me to do: first is to update a label with mine, second is to fill an alias. However, I'd like to do as follows: if a label for our language has already been filled, then the label to be uploaded should be filled to an alias.

## Suggestion
How about to add a feature to OpenRefine, which enables users to describe a conditional process depending on the situation of a target Wikidata item.

**Comment by wetneb** [comment]
> if a label for our language has already been filled, then the label to be uploaded should be filled to an alias.

This can already be done by selecting "Alias". When adding an alias, if no label exists in that language, the alias will automatically be promoted to a label.

In the upcoming 3.2 version we will also give more control over overriding existing labels and descriptions:

![image](https://user-images.githubusercontent.com/309908/61038586-90888500-a3cd-11e9-9328-837214f9d8f5.png)

This is already available in the development version.

in the future I would like to also give more control over the insertion process for statements.

**Comment by yayamamo** [comment]
Thanks!
