### ISSUE TITLE
Refine project file format of zip.

### ISSUE THREAD

**Issue by yayamamo** [OpenRefine/OpenRefine#2081]
## a zip file can be imported
When exporting a project to Google Drive, it is saved as a zip file.
Then, after downloading the zip file, I can import it from OpenRefine.
So, it works fine, but the label only shows tar or tar.gz as acceptable formats.

> Locate an existing Refine project file (.tar or .tar.gz):

It would be better if it could be modified to show that the zip format is also acceptable.

**Comment by sherria** [comment]
ok

**Comment by mtricht** [comment]
Edited the English source translation on weblate to reflect this: https://hosted.weblate.org/translate/openrefine/translations/en/?checksum=d3c2543d0d59aa63
Not sure when this gets commited and all other languages have to be updated as well.

**Comment by ostephens** [comment]
Thanks @mtricht. I've done the remaining languages. Weblate should raise an automatic PR to incorporate these changes soone

**Comment by wetneb** [comment]
Closed by #2082.
