### ISSUE TITLE
Blank down on rows won't work as expected

### ISSUE THREAD

**Issue by LibrErli** [OpenRefine/OpenRefine#2089]
I am trying to use the blank down function in my dataset (in row mode) to identify rows with the same ID following each other. Unfortunately the function won't work as expected. The screencast demonstrates that blank down is not working on example-ID 1018.

![openrefine_blankdown](https://user-images.githubusercontent.com/18214283/61440983-0304e200-a945-11e9-9ea3-4ffac9c93ba9.gif)

 - OS: [Ubuntu 18.04]
 - Browser Version: [Firefox 68]
 - JDK 1.80_212
 - Version [OpenRefine 3.2 Beta]

The Dataset is available: https://paws-public.wmflabs.org/paws-public/User:Mfchris84/hov_id.tsv

**Comment by wetneb** [comment]
You have changed the order of rows by sorting them on the first column. To get the Blank down operation to work in this setting, you need to persist this ordering (click on "Sort" -> "Reorder rows permanently"). If that still does not work, try removing leading and trailing blank space.

**Comment by LibrErli** [comment]
thank you antonin, that it is! now it works proper.
sorry for creating an issue based on my fault behavior.
