### ISSUE TITLE
Starting as a service

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#209]
_Original author: graham.poulter (November 15, 2010 07:30:09)_

As a user of Google Refine, I want to be start Google Refine at bootas a long-running background service on Windows Server, so that I can connect to it without using resources on my local machine, but I find no documentation on how to do it, or even whether it is possible.

&gt; sc create GoogleRefine start= delayed-auto binPath= &quot;C:\Program Files (x86)\Google Refine\refine.bat&quot; DisplayName= &quot;Google Refine&quot;

&gt; sc start GoogleRefine
[SC] StartService FAILED 1053:
The service did not respond to the start or control request in a timely fashion.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=209_
##

**Comment by thadguidry** [comment]
Closing as this is out of scope for our project. OS specific and other tooling exists to support running programs as a service.
