### ISSUE TITLE
Schema not exportable while running QuickStatements

### ISSUE THREAD

**Issue by sjoerddebruin** [OpenRefine/OpenRefine#2097]
**Describe the bug**
When you are running a QuickStatements job and want to back-up your schema for preparing  another one batch edit, you'll just get the QuickStatements windows focused instead of a local schema backup file.

**To Reproduce**
1. Open a QuickStatements window
2. Click on 'Export schema' in OpenRefine
3. The QuickStatements window gets focused instead of exporting the schema

**Current Results**
The QuickStatements window gets focused.

**Expected behavior**
The schema gets exported.

**OpenRefine (please complete the following information):**
 - 3.2-beta [8d89a2a]

**Comment by wetneb** [comment]
With my browsers (Firefox 62 and Chromium 69), the existing QS tab is indeed focused again, but its content is also updated. So the schema does get exported correctly.

I am not sure if we should force the opening of a distinct tab? What is wrong about reusing the existing tab?
