### ISSUE TITLE
New wikidata validator: description lengths and endings

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2103]
In the Wikidata extension, we could add validators to raise warnings when the following happens:
- adding a description which is too long (250 characters)
- adding a description which ends by punctuation signs (these should not be removed automatically but flagged, as they might indicate that full sentences were used as descriptions)
- any other sanity checks?

**Comment by thadguidry** [comment]
removal of racial slurs? :)  just kidding.  I think those are a start.
Only thing I can think of is:
* Removal of JSON array if found?  "[ "something description" ]" ?  I've seen on occasion from bots this happening, but from OpenRefine I guess its still possible that someone extracts a description array and creates toString and forgets about cleaning it, or didn't look through their entire column with Facets to clean it up properly?

**Comment by afkbrb** [comment]
Hi, I can work on this. I'll assign myself on this (if you agree).

**Comment by afkbrb** [comment]
According to: https://www.wikidata.org/wiki/Help:Description#Capitalization, maybe we should check whether the description begins with lowercase letter or not.

Also, according to: https://www.wikidata.org/wiki/Help:Description#No_initial_articles_(a,_an,_the), when the description begins with "a", "an" or "the", we should also throw a warning.

**Comment by afkbrb** [comment]
These checks work well with English. But it's impossible that we do the same checks for other languages.

For example, different languages have different punctuation signs, it's almost impossible to cover all in our check. And it's the same with the "a, an, the" check.

**Comment by wetneb** [comment]
We could also flag when a description and a label are identical for the same language.
