### ISSUE TITLE
Mac download.dmg image not recognized

### ISSUE THREAD

**Issue by tautme** [OpenRefine/OpenRefine#2105]
**Describe the bug**
After downloading and attempting to open the computer says the image is not recognized

**To Reproduce**
1. Go to http://openrefine.org/download.html
2. Click on Mac Kit 3.2
3. Download begins
4. See warning

**Current Results**
Image not recognized

**Expected behavior**
I expected installation to begin

**Screenshots**
<img width="365" alt="Screen Shot 2019-07-30 at 10 42 58 PM" src="https://user-images.githubusercontent.com/15580867/62225566-53853200-b37e-11e9-81be-4f0fdf45d8f2.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.6
 - Browser Version: Firefox 68.0.1
 - JRE or JDK Version: JDK 12.0.2

**OpenRefine (please complete the following information):**
 - Version OpenRefine 3.2 and 3.1

**Additional context**
I just downloaded the JDK.

**Comment by wetneb** [comment]
This might be due to the fact that the `.dmg` is not signed. Have you tried installing via Homebrew too?

Our install instructions for Mac are here:
https://github.com/OpenRefine/OpenRefine/wiki/Installation-Instructions#macos

You should not need the JDK on Mac to run OpenRefine as we ship one in the `.dmg` already.

**Comment by ostephens** [comment]
Hi @tautme it looks like you are downloading to an iOS not a macOS device? Unfortunately we do not have a version of OpenRefine that will run directly on iOS

**Comment by ostephens** [comment]
I can confirm I've been able to download and install the Mac version on macOS 10.14.5

@tautme you say the OS you are using is "iOS 10.14.6" - is that correct? (rather than a macOS?)

**Comment by ostephens** [comment]
Just to add that I've now upgraded to macOS Mojave 10.14.6 and tried downloading  via Firefox 68.0.1 and running OpenRefine and it all worked for me. My Security and Privacy settings are to allow apps downloaded from App Store & Identified developers

**Comment by tautme** [comment]
> I can confirm I've been able to download and install the Mac version on macOS 10.14.5
> 
> @tautme you say the OS you are using is "iOS 10.14.6" - is that correct? (rather than a macOS?)

using macOS, typo

**Comment by tautme** [comment]
> Just to add that I've now upgraded to macOS Mojave 10.14.6 and tried downloading via Firefox 68.0.1 and running OpenRefine and it all worked for me. My Security and Privacy settings are to allow apps downloaded from App Store & Identified developers

my settings are also to allown App Store & Identified developers

**Comment by tautme** [comment]
> This might be due to the fact that the `.dmg` is not signed. Have you tried installing via Homebrew too?
> 
> Our install instructions for Mac are here:
> https://github.com/OpenRefine/OpenRefine/wiki/Installation-Instructions#macos
> 
> You should not need the JDK on Mac to run OpenRefine as we ship one in the `.dmg` already.

I was able to download OpenRefine with homebrew.
