### ISSUE TITLE
Common Transformation "Trim Whitespace" introduced errors

### ISSUE THREAD

**Issue by LibrarPotter** [OpenRefine/OpenRefine#2106]
**Describe the bug**

When I used the Common Transformation from the drop down menu, it not only removed trailing white space, it also removed last letters from many words.

**To Reproduce**

1. Go to 'Edit Cells --> Common Tranforms'
2. Click on 'Trim leading and trailing whitespace'
3. Data in column was then missing the last character whether it was a whitespace character or not.

**Comment by wetneb** [comment]
Curious! Any chances you could you share your project to get a better sense of how this can happen?

**Comment by wetneb** [comment]
Without additional info, this issue is not reproducible.
