### ISSUE TITLE
Add menu for joining columns

### ISSUE THREAD

**Issue by msaby** [OpenRefine/OpenRefine#2109]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
The user should have the ability to join columns from a menu, without writing code. Using join() is tedious when you have a lot of columns to join. It would be the complementary operation of "Edit column > Split into several columns" menu

**Describe the solution you'd like**
I will submit soon a PR : I wrote a wrapper around "join ()" function, with some options : 

- chosing the columns to merge (menu inspired by "Custom Tabular Exporter")
- chosing a field separator
- collapsing nulls or not
- replacing nulls with a string (using "coalesce()" function)
- creating a new column or writing the result in the original column
- deleting or not the source columns

**Describe alternatives you've considered**

**Additional context**

**Comment by msaby** [comment]
For the moment I put my js code in a new doJoinColumns column in "views/data-table/menu-edit-column.js" and the HTML in a new file "views/data-table/column-join.html".

I am not sure about the difference between "views" and "dialogs" in OR code, so maybe it is not the right place... And I don't know if the strings I will create in "translations-en" should be in "core-views" or "core-dialog" namespace. Could someone give me some precisions about that ?

**Comment by thadguidry** [comment]
These are similar ideas also expressed in our old issue #68  But we'll keep both issues around to fully understand all the wants/needs around joining options that need to be exposed for 2 or more columns.  But I like the direction that you are headed with the solution description.

@msaby you can submit a "DRAFT" Pull Request to mark as a Work In Progress, that way we won't be able to merge it until you and us are comfortable and everyone has looked at the code, tested it, tried it out, etc.  Draft Pull Requests are a great way to share the code while you work on it and attach it to an issue.  Read more how to do that in 2 clicks here: https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by msaby** [comment]
here it is https://github.com/OpenRefine/OpenRefine/pull/2110

**Comment by wetneb** [comment]
Closed by #2110.
