### ISSUE TITLE
Easier way to copy the ID of a reconciled cell in a new column

### ISSUE THREAD

**Issue by msaby** [OpenRefine/OpenRefine#2114]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**

After a reconciliation, you can get the id of the object with a GREL expression : cell.recon.match.id

This is not obvious and difficult to remember.

OR should provide either a shortcut in GREL or/and a menu to do the operation without using GREL.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by thadguidry** [comment]
To clarify, you want a column menu option that says something like "Copy matched Recon IDs to a new column" ?

**Comment by msaby** [comment]
Something like that, but as we have already 

Edit cells > copy reconciliation data (which I have never used ; where is it documented?)

and

Edit columns > add columns from reconciled values

Maybe it could be added as a new choice to these menus ?

**Comment by msaby** [comment]
I would gladly work on this if you agree on the best way to display the function ;-)

**Comment by wetneb** [comment]
I think it would make sense to have an action for this in the "Reconcile" submenu.

**Comment by msaby** [comment]
I was thinking of something like that, but the UI will be a bit complex... Adaptation of the Edit cells > copy reconciliation data

![image](https://user-images.githubusercontent.com/932804/63200283-f4fbcb80-c080-11e9-8ae9-4c86360c50b5.png)

**Comment by msaby** [comment]
I think it should be a menu on its own, distinct from "copy reconciliation data" . See https://github.com/OpenRefine/OpenRefine/issues/2161

**Comment by thadguidry** [comment]
@msaby with the new found knowledge about `cell` from #2161 do you think this enhancement issue is still needed or can this be closed?

**Comment by thadguidry** [comment]
I think @msaby need in this issue can be resolved by the use of the new Reconcile -> Add entity identifiers column that was requested in #1975
