### ISSUE TITLE
Ability to mark statement as "update if pre-existing" in the Wikidata schema editor

### ISSUE THREAD

**Issue by davidhicks** [OpenRefine/OpenRefine#2116]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
WIkidata schema editing and upload.

**Describe the solution you'd like**
Ability to flag a statement in the schema editor as "statement to add or update". When uploading edits to Wikidta, OpenRefine would first search for an existing statement with the same value, and if an existing statement exists, add qualifiers and sources to the existing statement rather than creating a new/duplicate statement.

**Describe alternatives you've considered**
Pywikibot or QuickStatements.

**Comment by davidhicks** [comment]
To clarify: If a qualifier already exists on an existing statement and the schema includes this qualifier, the Wikidata schema editor would provide two options: "update if qualifier already exists" or "add new qualifier value".

**Comment by wetneb** [comment]
That is on our roadmap!

**Comment by wetneb** [comment]
This should be in the forthcoming release (3.6). In the meantime, feel free to use our [snapshot releases](https://github.com/OpenRefine/OpenRefine-snapshot-releases/#snapshot-releases) to try it out and tell us if you see ways to improve it.

**Comment by Ordoviz** [comment]
It seems that the statements setting UI (see image below) still does not allow one to choose between "update qualifier value if the qualifier already exists" or "add new qualifier value". We only have the option to "merge" statements, which I assume means to add a new qualifier value.

![statements setting UI](https://user-images.githubusercontent.com/309908/153719346-e769231f-6eba-4f59-ab00-2ce1a551a132.png)
