### ISSUE TITLE
Scatterplot

### ISSUE THREAD

**Issue by suezwicker** [OpenRefine/OpenRefine#2117]
The plots are not displaying when I do a scatterplot facet. Using the current edition of OR. Tried it in both Firefox & Mozilla on a Windows 10 Machine (scatterplots failed to display in both browsers, though the failure to display looked different in the different browsers). I tried it with two different data sets, on three different machines.

**Comment by wetneb** [comment]
@suezwicker if you can get hold of any screenshots, I think it would help understand the issue.

**Comment by suezwicker** [comment]
It’s working on the computer I’m using today.
I’ll check tomorrow when I’m back in my other office, & screenshot if it’s still not working.

Attached is a screen shot of a proper scatter plot. At the time that I put in my ticket, I was getting little ‘image missing’ icons on the top left of each box instead of a scatter plot.

Thx,
Sue

[cid:image002.jpg@01D55352.8007DBC0]

**Comment by craigca** [comment]
<img width="1401" alt="Screen Shot 2019-08-15 at 11 44 09 AM" src="https://user-images.githubusercontent.com/19333519/63106982-098d7600-bf52-11e9-8e2f-7ff5ee2d8fae.png">

Hello, I am running into a similar issue with scatterplots with version 3.2. I am using an iOS (macOS High Sierra 10.13.6), Chrome browser (Version 76.0.3809.100 (Official Build) (64-bit)) Attached is a screenshot. For the dataset, we are working with the dataset from the Data Carpentries OpenRefine for Ecologists module (https://datacarpentry.org/OpenRefine-ecology-lesson/setup.html)

Thank you

**Comment by atraxler** [comment]
Came here looking to see if anyone had the same issue. I'm using the same dataset (from Data Carpentries OpenRefine for Ecologists), but I get the same problem when I try a different file. If I View Image on one of the broken panes, or try to export a plot, I get error messages that start like this (formatting is a bit awkward, sorry):

`

code | "error"
:-- | :--
message | "Cannot deserialize value of type `int` from String \"lin\": not a valid Integer value\n at [Source: (String)\"{\"name\":\"recordID (x) vs. mo (y)\",\"cx\":\"recordID\",\"cy\":\"mo\",\"l\":500,\"ex\":\"value\",\"ey\":\"value\",\"dot\":4,\"dim_x\":\"lin\",\"dim_y\":\"lin\",\"type\":\"scatterplot\",\"from_x\":0,\"to_x\":0,\"from_y\":0,\"to_y\":0,\"base_color\":\"888888\"}\"; line: 1, column: 111] (through reference chain: com.google.refine.commands.browsing.GetScatterplotCommand$PlotterConfig[\"dim_x\"])"

`

**Comment by debpaul** [comment]
I have this same issue, no graphs return. It seems to be trying to work, but results come back. I just updated from 3.3 to 3.5 to see if it helped. Same issue. 
![image](https://user-images.githubusercontent.com/2990155/169400590-a0a61841-120a-42ae-9141-e0a595591394.png)

Note: if I click on "lin" or "log" then, for just second (a quick flash) I see "focusing on " appear near the top left corner of the white box.

**Comment by thadguidry** [comment]
@debpaul Ensure that your 2 columns are Datatype: Number (green color instead of black).  If not, then you can do a quick transform to number via the dropdown menu for Common Transforms.

**Comment by debpaul** [comment]
> @debpaul Ensure that your 2 columns are Datatype: Number (green color instead of black). If not, then you can do a quick transform to number via the dropdown menu for Common Transforms.

Thanks @thadguidry I just tried that. Same result (sadly)
![image](https://user-images.githubusercontent.com/2990155/169401677-d621c641-e9d9-4042-a633-8dbeb2e46bc4.png)

**Comment by debpaul** [comment]
@thadguidry I just closed and restarted refine (latest version). And tried again. And voila. (Chrome. Refine 3.5.2 Win10)
![image](https://user-images.githubusercontent.com/2990155/169402478-576700b5-3fb8-4160-ba54-bd621ad666e2.png)

Not sure why working now though.

**Comment by thadguidry** [comment]
@debpaul Likely a browser refresh could have also fixed the issue. :-)  There might be a small lingering bug that we have for refreshing the Scatterplot, or the cache.  The Scatterplot dialog is treated within the dialog-overlay context and I have seen a few of our dialogs in that context sometimes have browser cache issues.  Not sure what the "good fix" would be but I'm sure a JavaScript expert (@antoine2711 ?) might debug this and help us fix it for good.
