### ISSUE TITLE
Export with "Save As..." option

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#212]
_Original author: wfznimbl...@gmail.com (November 15, 2010 20:38:34)_

<b>What steps will reproduce the problem?</b>

[all exports default to project name]

<b>What is the expected output? What do you see instead?</b>

export filename = projectname.extension

<b>What version of the product are you using? On what operating system?</b>

2.0/Win 7

<b>Please provide any additional information below.</b>

Save As... filename would facilitate iterative exports for testing

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=212_

**Comment by antoine2711** [comment]
I think we can close this issue, @tfmorris. Either it was an issue with an old browser, either the special case of #585, but, in any case, getting more information from the origin seam unprobable, and this as not really been seen or reported since.

Regards, Antoine
