### ISSUE TITLE
Export to Google Sheets failing

### ISSUE THREAD

**Issue by urwa** [OpenRefine/OpenRefine#2123]
**Describe the bug**
I am unable to export the data to Google Sheets.

**To Reproduce**
1. Go to 'Export' button on top right
2. Click on 'Custom Tabular Exporter' in the drop down
3. Go to 'Upload' Tab
4. Select 'A new Google spreadsheet' radio button
5. Click on 'Upload' Button
6. Enter the name of the spreadsheet in the dialog box that appears
7. Authorize if it is the first time

**Current Results**
HTTP ERROR 404

Problem accessing /https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1VMnJttMcx2-A7vIj_rBhKb8SjP1X3gx3CIyDE9aYkVo%2Fedit%23gid%3D0. Reason:

    NOT_FOUND

Powered by Jetty://

**Expected behavior**
It should create and upload data to the new spreadsheet. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5441467/62867938-ebdfc700-bd2d-11e9-87a6-4555e61c0b68.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version: Firefox 68.0.1 (64-bit) 
- JRE or JDK Version: java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) Client VM (build 25.211-b12, mixed mode, sharing)

**OpenRefine (please complete the following information):**
 - Version OpenRefine 3.2

**Datasets**
My data is simply three columns: url, htmltext, title
Some very basic data scraping.

**Additional context**
When I go to the url mentioned in the error. The spreadsheet is actually created but no data is uploaded.

**Comment by wetneb** [comment]
Fixed by a4c4a207673ef1465c0713a7c6661f1dc071e7a0
