### ISSUE TITLE
OpenRefine 3.2 does not start on macOS Mojave

### ISSUE THREAD

**Issue by iabaro** [OpenRefine/OpenRefine#2125]
**Describe the bug**
OpenRefine 3.2 does not start on macOS Mojave

**To Reproduce**
1. Download image and install; or install through homebrew.
2. Start OpenRefine

**Current Results**
"Butterfly is still initializing..." message received in the browser windows.

**Expected behavior**
OpenRefine starting page

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser Version: Chrome Version 76.0.3809.100
 - JRE or JDK Version: JRE 1.7.0_79-b15

**OpenRefine (please complete the following information):**
 - Version: OpenRefine 3.2 for Mac

**Comment by wetneb** [comment]
@iabaro thanks for this report.

If you have installed any extension, can you remove them and try again?

**Comment by iabaro** [comment]
I tried that before going back to 3.1.

Thanks.

**Comment by kirschbombe** [comment]
Any movement on this? Or shall I just revert back to an older version?

**Comment by wetneb** [comment]
@kirschbombe have you tried 3.3 beta too?

**Comment by kirschbombe** [comment]
@wetneb - I have not! But I'll give it a shot :) I reverted back to 3.1 for now.

**Comment by antoine2711** [comment]
> @wetneb - I have not! But I'll give it a shot :) I reverted back to 3.1 for now.

@Kirschbombe : have you tried v3.3?

**Comment by tfmorris** [comment]
Since the v3.3 release has obsoleted v3.2, I'm closing this.
