### ISSUE TITLE
Add autofocus tag to separatorInput fields

### ISSUE THREAD

**Issue by katrinleinweber** [OpenRefine/OpenRefine#2130]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
I'm always frustrated when I need to move the mouse to the input field I'm using most often in a dialog. E.g. the `separatorInput` field in `Join...` or `Split multi-valued cells`. It would be easier if OpenRefine autofocussed the cursor onto that field, and others where similar user preference is expected.

**Describe the solution you'd like**

Apply [att_input_autofocus](https://www.w3schools.com/tags/att_input_autofocus.asp) to those fields. If you agree, I'll be happy to send a PR.

**Describe alternatives you've considered**
none, TBH

**Additional context**
Do you have numbers on which for example the popularity of the `by field lengths` split option?

**Comment by wetneb** [comment]
Given that OpenRefine runs locally we don't have any way to collect usage statistics (we could add calls to some hosted service for that, but I think it would be contentious). But your proposal definitely makes sense, we can use our own experience and common sense to determine which fields should be focused by default.
