### ISSUE TITLE
"Star all rows below current one"

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#214]
_Original author: wfznimbl...@gmail.com (November 15, 2010 21:19:55)_

<b>What steps will reproduce the problem?</b>

[ease of use enhancement]

<b>What is the expected output? What do you see instead?</b>

[alternative is manual starring which quickly becomes impossible]

<b>What version of the product are you using? On what operating system?</b>

[2.0/Windows 7]

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=214_

**Comment by wetneb** [comment]
This is really too specific to be added as an operation or menu item by default. It should be covered by #109.

**Comment by antoine2711** [comment]
> You could create a text facet on any column with this expression
> 
> row.index >= n
> 
> where n is the current row's index. And then select true in the face. And star all matching rows. 

I think this would only work if you don't sort your view. Because if you do sort, then, row.index is not longer the ordinal order you see…

> I just realize that row.index might be zero-based, but row indexes are displayed as one-based.

Interesting! ;-)

Regards, Antoine
