### ISSUE TITLE
can't export the data from database

### ISSUE THREAD

**Issue by mmaithani** [OpenRefine/OpenRefine#2146]
**problem during connecting with database**

error:Cannot load connection class because of underlying exception: 'java.lang.NumberFormatException: For input string: "18.136.56.185:3365"'.

**To Reproduce**
1. Go to 'Create Project'
2. Click on 'Database'
3. Fill the Database field for connection(demo)"confidential data"
 'DB Name: project_sales
Table Name: data
Host: http:18.136.56.188
Username: dm_team2
Password: NA '
4. See error -popup

**Current Results**
<blockquote class="imgur-embed-pub" lang="en" data-id="a/bxH445X" data-context="false" ><a href="//imgur.com/a/bxH445X">error- open refine</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Screenshots**

**Desktop:**
 - OS: [Windows 10]64 bit
 - Browser Version: chrome 76
- java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) Client VM (build 25.221-b11, mixed mode)

**open refine- Version 3.2 [55c921b]

**Comment by tcbuzor** [comment]
why add the http protocol to the host field?

**Comment by wetneb** [comment]
The import error is likely to be due to the inclusion of `http` in the host field, which prevents OpenRefine from connecting to the database.
