### ISSUE TITLE
Clustering not working

### ISSUE THREAD

**Issue by rafaeltcc** [OpenRefine/OpenRefine#2147]
**Describe the bug**
In 3.2 I can go to the cluster dialog. I select all results found with default algoritm and hit "Merge Selctted and recluster". Nothing happens, the page reloads and the same clusters are found. Nothing is merged.

**Current Results**
After clicking to merge and recluster the same lines appears, exactly the same number of clusters are found

**Expected behavior**
Cluster applied and rows merged

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Antergos Linux all updated
 - Browser Version: Chromiun
 - JRE or JDK Version:[output of "java -version" e.g. JRE 1.8.0_181]

**OpenRefine (please complete the following information):**
 - Version 3.2

**Comment by thadguidry** [comment]
How many rows do you have prior to doing the Edit Cells --> Cluster and Edit  ?

Does the Cluster and Edit dialog after you do the clustering with defaults, shows the same amount of rows in the top right corner of its dialog box ?
* if so, then its likely you are not finding clusters at all...and have all unique clusters (rows)
* then change from using defaults to some of the other algorithms, many of which are explained here: https://github.com/OpenRefine/OpenRefine/wiki/Clustering-In-Depth

**Comment by rafaeltcc** [comment]
Hi,

I have only 635 rows.

I tried in Linux and Windows.

It detects 343 clusters (using fingerprint). After I click Merge and
Recluster it finds the same 343 clusters... I noticed that most of the
clusters are of a single entry (i found this strange). I used the controla
to trim it to at least 2 entries. Then it detects 35 clusters, but again no
change is made.

The same happens with all the other algorithms.

I tried to downgrade to open refine 3.0. In this case nothing os detected.

Mu entries até utf8 with portuguese characteres such as ãêéí, etc.

Nothing strange in the log output in command line.

Do you want me to make a video?


Em ter, 3 de set de 2019 19:54, Thad Guidry <notifications@github.com>
escreveu:

**Comment by thadguidry** [comment]
Are you willing to share you dataset with us publicly or privately ?  if publicly, then you can export your OpenRefine project and drag and drop the *.tar.gz file into a reply comment here.   if privately, you can  email to me.

Yes, a video would be additionally helpful !

**Comment by rafaeltcc** [comment]
Hi Thad,

Thanks a lot for your attention. The problem is not in my dataset as I have
tested with a very simple one I created to test. (teste.xls attached).

I also recorded the steps I took with this windows step record app. If you
want I can also record a video, but I think the slides cover the entire
problem.

Thanks a lot again,

Rafael


Em qua, 4 de set de 2019 às 14:29, Thad Guidry <notifications@github.com>
escreveu:

**Comment by rafaeltcc** [comment]
[steps.zip](https://github.com/OpenRefine/OpenRefine/files/3577029/steps.zip)
[teste-xls.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/3577031/teste-xls.openrefine.tar.gz)

**Comment by rafaeltcc** [comment]
Sorry, I think I got it wrong. I was trying to use cluster to merge duplicated lines. I see now in the docs this is not what the cluster function does...  I have not used open-refine for some years. Thanks again for your attention and sorry for taking our time with this,

**Comment by thadguidry** [comment]
;-)  Isn't our human RAM terrific ?  No problem sir !  We'll close this issue then.

**Comment by thadguidry** [comment]
Oh, we do now have a Duplicates Facet available in the Column menus... look for it and try it out.. it shows duplicated strings... but first you might have to partition or create new columns with the values you want to inspect as duplicates... if you want you can even Concatentate now several columns using the new Concatentate menu option and then do a Duplicates Facet or even a Cluster and Merge if needed.

Have fun and ... WELCOME BACK @rafaeltcc !!!
