### ISSUE TITLE
Unable to replace null values in cell

### ISSUE THREAD

**Issue by titoesteves** [OpenRefine/OpenRefine#2153]
**Describe the bug**
I am unable to replace null values in cells. 
**To Reproduce**
1. Go to Edit cells > transform
2. Different things I have tried:
```
replace(value, 'null', 'other_text')
replace(value, null, 'other_text')
```
3. Replace method works as expected for values other than null

**Current Results**
![](https://i.imgur.com/IX0hfFQ.png)
**Expected behavior**
I expected the null values to be replaced with 'other text'
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Browser Version: [Version 76.0.3809.87 (Official Build) (64-bit)]

**OpenRefine (please complete the following information):**
 - Version [OpenRefine 3.2]

**Comment by wetneb** [comment]
The question was answered on StackOverflow:
https://stackoverflow.com/questions/57882921/replace-null-values-in-cell

**Comment by titoesteves** [comment]
The stackoverflow shows that replace does not work on null. Is that not a bug? If not, then can you update the documentation to reflect that so others will not incur the same issue?

**Comment by wetneb** [comment]
@titoesteves that is not a bug indeed! The replace function is designed to replace parts of strings by other strings, and null is not a string. Feel free to edit the wiki to make that clearer!

**Comment by thadguidry** [comment]
I tend to side with our user base here, in that we don't expose an easy button for null replacement like other data tools have.
This comes up often enough that I "think" most of our users would like to see a new function for this...perhaps a `replaceNull` 

`value.replaceNull("this value is being replaced and is no longer a null")`

**Comment by wetneb** [comment]
Sure! But then that has nothing to do with the existing "replace" function. We can open another ticket to request a new GREL function for that if you want.

**Comment by thadguidry** [comment]
DONE - see #2157

**Comment by xiaomeizi58** [comment]
if(value==null,"new",value).
