### ISSUE TITLE
Version 3.2 not starting due to Exception

### ISSUE THREAD

**Issue by yayamamo** [OpenRefine/OpenRefine#2154]
This may relate to #1939 .

**Describe the bug**
Not starting due to Exception
> Exception in thread "main" java.lang.NoClassDefFoundError: org/json/JSONException

**To Reproduce**

1. Download openrefine-mac-3.2.dmg.
2. Copy to it to the Application folder.
3. Double click the icon.

**Current Results**
The terminal shows the folloiwng:

```
/Applications/OpenRefine.app/Contents/MacOS/JavaAppLauncher ; exit;
16:29:25.565 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
16:29:25.572 [            refine_server] Initializing context: '/' from '/Applications/OpenRefine.app/Contents/Resources/webapp' (7ms)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Applications/OpenRefine.app/Contents/Java/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Applications/OpenRefine.app/Contents/Resources/webapp/WEB-INF/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
16:29:26.003 [                   refine] Starting OpenRefine 3.2 [55c921b]... (431ms)
16:29:26.003 [                   refine] initializing FileProjectManager with dir (0ms)
16:29:26.003 [                   refine] /Users/yayamamo/Library/Application Support/OpenRefine (0ms)
Exception in thread "main" java.lang.NoClassDefFoundError: org/json/JSONException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
...
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Mojave (10.14.6)
 - JRE or JDK Version:
```
$ java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```

**OpenRefine (please complete the following information):**
 - Version OpenRefine 3.2

**Datasets**

**Additional context**
There is no folder named "~/Library/Application Support/OpenRefine".

**Comment by wetneb** [comment]
@yayamamo This is probably because you have installed custom extensions which are incompatible with 3.2. Try removing these and restarting OpenRefine.

**Comment by yayamamo** [comment]
Thanks for telling me the info., but I cannot find such extensions. It may be rdf-extension, but Spotlight cannot find it in the Mac. In addition, there seems no other custom extensions in the extensions folder...
<img width="778" alt="image" src="https://user-images.githubusercontent.com/995225/64678757-341d1100-d4b5-11e9-8e6c-f4909ce0af38.png">

**Comment by wetneb** [comment]
@yayamamo can you check in `~/Library/Application Support/OpenRefine` too?

**Comment by yayamamo** [comment]
Found! Thank you very much. Now it starts normally.
