### ISSUE TITLE
3.1 -> 3.2 UI Corruption with old data

### ISSUE THREAD

**Issue by Cobra1978** [OpenRefine/OpenRefine#2156]
Updating openrefine from 3.1 to 3.2, mataining old workspace makes the ui corrupted and unusable

1. Install openrefine 3.2
2. point the data direcotry to the previously used data dir
3. start open refine
4. Ui appears as in the screenshot
![Screenshot_2019-09-11 OpenRefine](https://user-images.githubusercontent.com/33548070/64709655-ee614800-d4b6-11e9-9b2e-f22aadc5a33d.png)
![Screenshot_2019-09-11 OpenRefine(2)](https://user-images.githubusercontent.com/33548070/64709659-f02b0b80-d4b6-11e9-9bfb-7ce4c4d181a3.png)
![Screenshot_2019-09-11 OpenRefine(1)](https://user-images.githubusercontent.com/33548070/64709661-f15c3880-d4b6-11e9-9348-e9611627d594.png)

 - OS: CentOS Linux 7
 - Browser Version:Firefox 69
 - JRE or JDK Version: 
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+11)
OpenJDK 64-Bit Server VM (build 9.0.4+11, mixed mode)

 - Version 3.2

**Comment by wetneb** [comment]
Thanks for this report!

Have you installed any third-party extensions?

Can you see any error message either in the server console or in the browser console?

**Comment by Cobra1978** [comment]
We don't have any third party extension.

in the browser console i see thse errors:
```
Source map error: request failed with status 404
Resource URL: https://refine.diennea.lan/index-bundle.js
Source Map URL: jquery.contextMenu.min.js.map

```


```
TypeError: project is nullindex-bundle.js:28144:7
    _renderProjects https://refine.diennea.lan/index-bundle.js:28144
    success https://refine.diennea.lan/index-bundle.js:28130
    fire https://refine.diennea.lan/index-bundle.js:3121
    fireWith https://refine.diennea.lan/index-bundle.js:3233
    done https://refine.diennea.lan/index-bundle.js:9277
    callback https://refine.diennea.lan/index-bundle.js:9687
    send https://refine.diennea.lan/index-bundle.js:9693
    ajax https://refine.diennea.lan/index-bundle.js:9178
    _fetchProjects https://refine.diennea.lan/index-bundle.js:28125
    _buildTagsAndFetchProjects https://refine.diennea.lan/index-bundle.js:28093
    OpenProjectUI https://refine.diennea.lan/index-bundle.js:28062
    renderActionArea https://refine.diennea.lan/index-bundle.js:27688
    <anonymous> https://refine.diennea.lan/index-bundle.js:27692
    fire https://refine.diennea.lan/index-bundle.js:3121
    fireWith https://refine.diennea.lan/index-bundle.js:3233
    ready https://refine.diennea.lan/index-bundle.js:3445
    completed https://refine.diennea.lan/index-bundle.js:3476
```

and

```
TypeError: Refine.actionAreas[i].ui is undefinedindex-bundle.js:27669:7
    resize https://refine.diennea.lan/index-bundle.js:27669
```

**Comment by wetneb** [comment]
Do you have access to the server console at all? See https://github.com/OpenRefine/OpenRefine/wiki/Installation-Instructions#obtaining-server-logs-on-mac if you are using MacOS.

**Comment by Cobra1978** [comment]
> 
> 
> Do you have access to the server console at all? See https://github.com/OpenRefine/OpenRefine/wiki/Installation-Instructions#obtaining-server-logs-on-mac if you are using MacOS.

Is a linu Server, and yes i have console and root access to the server

**Comment by wetneb** [comment]
In that case, can you please paste here OpenRefine's server logs?

**Comment by Cobra1978** [comment]
yes

`Sep 11 17:23:05 openrefine-srv.arezzo.diennea.lan systemd[1]: Started OpenRefine data reconciliation tool.
Sep 11 17:23:06 openrefine-srv.arezzo.diennea.lan refine[129831]: You have 31993M of free memory.
Sep 11 17:23:06 openrefine-srv.arezzo.diennea.lan refine[129831]: Your current configuration is set to use 30G of memory.
Sep 11 17:23:06 openrefine-srv.arezzo.diennea.lan refine[129831]: OpenRefine can run better when given more memory. Read our FAQ on how to allocate more memory here:
Sep 11 17:23:06 openrefine-srv.arezzo.diennea.lan refine[129831]: https://github.com/OpenRefine/OpenRefine/wiki/FAQ:-Allocate-More-Memory
Sep 11 17:23:06 openrefine-srv.arezzo.diennea.lan refine[129831]: Starting OpenRefine at 'http://localhost:3333/'
Sep 11 17:23:06 openrefine-srv.arezzo.diennea.lan refine[129831]: 17:23:06.313 [            refine_server] Starting Server bound to 'localhost:3333' (0ms)
Sep 11 17:23:06 openrefine-srv.arezzo.diennea.lan refine[129831]: 17:23:06.315 [            refine_server] refine.memory size: 30G JVM Max heap: 32212254720 (2ms)
Sep 11 17:23:06 openrefine-srv.arezzo.diennea.lan refine[129831]: 17:23:06.324 [            refine_server] Initializing context: '/' from '/data/openrefine-3.2/webapp' (9ms)
Sep 11 17:23:06 openrefine-srv.arezzo.diennea.lan refine[129831]: SLF4J: Class path contains multiple SLF4J bindings.
Sep 11 17:23:06 openrefine-srv.arezzo.diennea.lan refine[129831]: SLF4J: Found binding in [jar:file:/data/openrefine-3.2/server/target/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
Sep 11 17:23:06 openrefine-srv.arezzo.diennea.lan refine[129831]: SLF4J: Found binding in [jar:file:/data/openrefine-3.2/webapp/WEB-INF/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
Sep 11 17:23:06 openrefine-srv.arezzo.diennea.lan refine[129831]: SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
Sep 11 17:23:06 openrefine-srv.arezzo.diennea.lan refine[129831]: SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Sep 11 17:23:06 openrefine-srv.arezzo.diennea.lan refine[129831]: 17:23:06.867 [                   refine] Starting OpenRefine 3.2 [55c921b]... (543ms)
Sep 11 17:23:06 openrefine-srv.arezzo.diennea.lan refine[129831]: 17:23:06.867 [                   refine] initializing FileProjectManager with dir (0ms)
Sep 11 17:23:06 openrefine-srv.arezzo.diennea.lan refine[129831]: 17:23:06.867 [                   refine] /data/openrefine-data (0ms)
Sep 11 17:23:08 openrefine-srv.arezzo.diennea.lan refine[129831]: WARNING: An illegal reflective access operation has occurred
Sep 11 17:23:08 openrefine-srv.arezzo.diennea.lan refine[129831]: WARNING: Illegal reflective access by org.python.core.PySystemState (file:/data/openrefine-3.2/webapp/extensions/jython/module/MOD-INF/lib/jython-standalone-2.7.1.jar) to method java.io.Console.encoding()
Sep 11 17:23:08 openrefine-srv.arezzo.diennea.lan refine[129831]: WARNING: Please consider reporting this to the maintainers of org.python.core.PySystemState
Sep 11 17:23:08 openrefine-srv.arezzo.diennea.lan refine[129831]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Sep 11 17:23:08 openrefine-srv.arezzo.diennea.lan refine[129831]: WARNING: All illegal access operations will be denied in a future release
Sep 11 17:23:10 openrefine-srv.arezzo.diennea.lan refine[129831]: 17:23:10.245 [                   refine] Running in headless mode (3378ms)
Sep 11 17:23:16 openrefine-srv.arezzo.diennea.lan refine[129831]: 17:23:16.428 [                   refine] POST /command/core/load-language (6183ms)
Sep 11 17:23:16 openrefine-srv.arezzo.diennea.lan refine[129831]: 17:23:16.489 [                   refine] GET /command/core/get-preference (61ms)
Sep 11 17:23:16 openrefine-srv.arezzo.diennea.lan refine[129831]: 17:23:16.541 [                   refine] POST /command/core/load-language (52ms)
Sep 11 17:23:16 openrefine-srv.arezzo.diennea.lan refine[129831]: 17:23:16.588 [                   refine] POST /command/core/load-language (47ms)
Sep 11 17:23:16 openrefine-srv.arezzo.diennea.lan refine[129831]: 17:23:16.809 [                   refine] POST /command/core/get-importing-configuration (221ms)
Sep 11 17:23:16 openrefine-srv.arezzo.diennea.lan refine[129831]: 17:23:16.875 [                   refine] GET /command/core/get-all-project-tags (66ms)
Sep 11 17:23:17 openrefine-srv.arezzo.diennea.lan refine[129831]: 17:23:17.097 [                   refine] GET /command/database/saved-connection (222ms)
Sep 11 17:23:17 openrefine-srv.arezzo.diennea.lan refine[129831]: 17:23:17.161 [                   refine] GET /command/core/get-all-project-metadata (64ms)
`

**Comment by wetneb** [comment]
Could you share with us the list of project metada? You should be able to obtain it like this:

`curl http://localhost:3333/command/core/get-all-project-metadata > project_metadata.json`

**Comment by Cobra1978** [comment]
Hi, there are our project metadata.

Best Regards


[project_metadata.zip](https://github.com/OpenRefine/OpenRefine/files/3642591/project_metadata.zip)

**Comment by Cobra1978** [comment]
Hi, there is any news?

Ther are other info that i can send to help you to fix the problem?

**Comment by wetneb** [comment]
Sorry I have not had time to investigate your issue further.

**Comment by thadguidry** [comment]
@Cobra1978 Hi, have you resolved your issue some other way?  I would like to know if using [OpenRefine 3.3 our newest beta version](https://github.com/OpenRefine/OpenRefine/releases) helps resolve this issue for you? Let us know, so we can close this issue.

**Comment by Cobra1978** [comment]
Hi.

I think you are thelepatic: i've isntalled the 3.3 beta some days ago and the issue is not present anymore :)

Sorry that i've forgot to write this.
