### ISSUE TITLE
Language preference not working in OR 3.2

### ISSUE THREAD

**Issue by msaby** [OpenRefine/OpenRefine#2158]
**Describe the bug**

Impossible to change the language of the UI

**To Reproduce**

Change the language to "French" or "Spanish" and apply. Nothing is changed, the UI is still in English

see this tweet https://twitter.com/daieuxdailleurs/status/1171672967648043008
**Current Results**
What results occured or were shown.

**Expected behavior**
A clear and concise description of what you expected to happen or to show.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Version: FF
 - JRE or JDK Version: 1.8.0_201

**OpenRefine (please complete the following information):**
 - Version :  OpenRefine 3.2

**Datasets**
If you are allowed and are OK with making your data public, it would be awesome if you can include or attach the data causing the issue or a URL pointing to where the data is.
If you are concerned about keeping your data private, ping us on our [mailing list](https://groups.google.com/forum/#!forum/openrefine)

**Additional context**

**Comment by CennoxX** [comment]
For anyone searching this problem: a workaround is to open preferences and add "userLang" with value "fr" for french etc.
