### ISSUE TITLE
Reconciliation dialog always sends Freebase default type to property suggest service

### ISSUE THREAD

**Issue by fsteeg** [OpenRefine/OpenRefine#2168]
**Describe the bug**

When sending a property suggest request in the reconciliation dialog (on the right, "Also use relevant details from other columns:"), OpenRefine sends the old Freebase default type identifier (`type/property`) to the suggest service, instead of the entity type selected (on the left, "Reconcile each cell to an entity of one of these types:").

**To Reproduce**

1. Add `console.log("suggestOptions.type:", suggestOptions.type);` in `standard-service-panel.js`, line 252 (after `if (type) {...}`)
2. Open Reconciliation dialog, select the Wikidata reconciliation service
4. In the area on the left ("Reconcile each cell to an entity of one of these types:"), change the type selection
5. Open your browser's web console, and check the "suggestOptions.type" output

**Current Results**

The `suggestOptions.type` is undefined, resulting in usage of the default type specified in `custom-suggest.js`, line 105 (`type/property`).

**Expected behavior**

The `suggestOptions.type` should be the type selected under "Reconcile each cell to an entity of one of these types:", like `Q5`.

**Desktop:**

- OS: Linux Mint 18.1 Cinnamon 64-bit
- Browser Version: Firefox 68.0.1 (64-bit)
- JRE or JDK Version: OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
- Version: tested in OpenRefine 3.2 and in master

**Comment by wetneb** [comment]
Nice! So that would allow services to rely on the chosen type to suggest more relevant properties, if I understand correctly. Should we consider this as a bug fix or as a new feature to the reconciliation API? It seems that the code had some sort of Freebase-specific support for that indeed, so I guess we can treat that as a fix.

That reminds me of #201, which is also related to type restriction in suggest services. Do you think this was also supported in a Freebase-specific way before?

**Comment by thadguidry** [comment]
Yes Freebase had support for Type restriction in Suggest, along with "exact_match".  It also had namespaced identifier reconciliation https://groups.google.com/d/topic/openrefine/HOITE0bvHZ0/discussion

Added this on #201 ... By the way...I found the docs for the "Search for match" feature... David said at one time that it's a last resort and doesn't support passing additional columns when doing a "Search for match".
https://groups.google.com/d/topic/openrefine/p5dYg_FjVDc/discussion

To remember things from our past, I often just use our Google Groups Forum Search https://groups.google.com/forum/#!searchin/openrefine/reconciliation%7Csort:date

**Comment by fsteeg** [comment]
> So that would allow services to rely on the chosen type to suggest more relevant properties, if I understand correctly.

Yes, you can test that with the branch from #2169 using our GND reconciliation service: https://lobid.org/gnd/reconcile

It is called like this:

https://lobid.org/gnd/reconcile/suggest/property?prefix=Ort&type=Person
https://lobid.org/gnd/reconcile/suggest/property?prefix=Ort&type=CorporateBody
