### ISSUE TITLE
Unable to open the existing project

### ISSUE THREAD

**Issue by Gautamshahi** [OpenRefine/OpenRefine#2170]
Hello,

I am using the latest version of OpenRefine 3.2, and I am not able to open the existing project, it gives an error mentioned below, I have tried different project and browser also.

Failed to find project id #2208937475861 - may be corrupt

Can you suggest some way to remove this error?

**Comment by wetneb** [comment]
Hi @Gautamshahi,

Can you show us the server logs generated when you try to open the project? These are the messages in the terminal window (white over black generally). If you use Mac OS here is how to get them:
https://github.com/OpenRefine/OpenRefine/wiki/Installation-Instructions#obtaining-server-logs-on-mac

If your data is not sensitive it would also help if you could open your projects with OpenRefine 3.1, export the project (as a native archive) and share that with us.

**Comment by wetneb** [comment]
Without more info, I cannot reproduce this issue, so I am closing it now.
