### ISSUE TITLE
Extend data preview dialog should use view URL pattern from metadata

### ISSUE THREAD

**Issue by fsteeg** [OpenRefine/OpenRefine#2177]
In `extend-data-preview-dialog.js`, preview links for reconciled properties are created by concatenating `service.identifierSpace + cell.id`. Instead, the `service.view.url` pattern should be preferred, so that the preview links point to the same location as the reconciled values in the table, after data extension is complete.

**Comment by wetneb** [comment]
Of course! Sorry about that, I was too Wikidata-centric there.
