### ISSUE TITLE
Support editing HTTP headers

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#218]
_Original author: mcnamara.tim@gmail.com (November 15, 2010 22:19:56)_

<b>What steps will reproduce the problem?</b>
1. Find a closed API that requires API key as HTTP header
2. Oh noes! Can't enter API key.

<b>What is the expected output? What do you see instead?</b>
Happy data. Zilch.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=218_

**Comment by ostephens** [comment]
I've submitted a PR #1434 which allows the user to set three http request headers:

- User-Agent
- Accept
- Authorization

Adding additional headers can be done easily either in an extension or in the core code.
The headers that can be set on the request are set in the back-end, so adding a proprietary header (which might hold an API key for example) would need to be added through an extension (the user can't just add them in on submitting the request)

**Comment by wetneb** [comment]
By the way there are also requests for support of reconciliation services with API keys (from OpenCorporates). A PR about this was filed a while back but has not made it to master (#758).

**Comment by ostephens** [comment]
Fixed by #1434
