### ISSUE TITLE
Unable to extract history

### ISSUE THREAD

**Issue by iabaro** [OpenRefine/OpenRefine#2188]
**Describe the bug**
Working on a +8000 records project with +4000 history items. When trying to extract the history, nothing happens.

**To Reproduce**
1. Go to Undo / Redo
2. Click on Extract...
3. Nothing happens

**Current Results**
No response.

**Expected behavior**
History JSON.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6 / Windows 10 Enterprise, Build 1709, 16299.1217
 - Browser Version: Firefox 69.0.3 (64-bit), Google Chrome 77.0.3865.120 (Official Build) (64-bit), Safari 13.0.2 (14608.2.40.1.2) / Win: Google Chrome 77.0.3865.90 (Official Build) (64-bit)
 - JRE or JDK Version: JRE 1.7.0_79-b15

**OpenRefine (please complete the following information):**
 - Version OpenRefine 3.1

**Comment by ostephens** [comment]
@iabaro a couple of questions:

1. are there any messages in the console when you try to do the export? (you'll see this in Windows, but probably not on Mac)
2. are you able to export the project and share it here? Obviously understand if that's not possible, but if you can it will help us diagnose the issue

**Comment by wetneb** [comment]
We do not have enough information to provide a fix to this problem.
