### ISSUE TITLE
Wikidata login: form not submitted when pressing Enter key

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2194]
When pressing the Enter key in the Wikidata login form from the Wikidata extension, one would expect the form to be submitted, which currently does not happen.

**Comment by Jataki** [comment]
Hi! Can I take this one?

**Comment by wetneb** [comment]
@Jataki please!

**Comment by Jataki** [comment]
Having an issue with my computer with no solution date. I'm sorry, but I'll have to leave this issue for others to have the opportunity to contribute. Thanks anyway and I'm so sorry!

**Comment by Bhanu-mbvg** [comment]
Hey, can I take up this issue?

**Comment by wetneb** [comment]
@Bhanu-mbvg sure, it would be great!

**Comment by wetneb** [comment]
@Bhanu-mbvg let me know if you need any help :)

**Comment by Bhanu-mbvg** [comment]
@wetneb How do I recreate Wikidata login form from the Wikidata extension

**Comment by wetneb** [comment]
* Start OpenRefine
* Open any project (or create a new one, by opening any table from your computer for instance)
* Click on the Wikidata button in the top right corner
* Click "Manage Wikidata account"
This will create the login dialog where the form can be seen.

The HTML for this dialog is stored in extensions/wikidata/module/scripts/dialogs/manage-account-dialog.html.
The Javascript code for this dialog is extensions/wikidata/module/scripts/dialogs/manage-account-dialog.js.

**Comment by Bhanu-mbvg** [comment]
#2259 Pull Request has been made. 
I resolved the issue using event listener for enter key inside the form
@wetneb can you see the PR

**Comment by Bhanu-mbvg** [comment]
Hey @wetneb , I am still getting the error of form not getting submit on Enter keypress, can you check once?

**Comment by wetneb** [comment]
When trying from the master branch, pressing Enter submits the form both with Firefox and Chromium, for me. Which browser are you using?
