### ISSUE TITLE
JSON: concatenate null value with string, result changed between 3.1 and 3.2

### ISSUE THREAD

**Issue by mnhampl** [OpenRefine/OpenRefine#2195]
**Describe the bug**
Extracting and concatenating strings from JSON gives different results in OR 3.1 and OR 3.2 if one of the string is actually not a string but a null value.

In 3.1 the null value is evaluated to the string 'null', in 3.2 the whole string concatenation seems to fail.

I don't seem to be able to find the change in the 3.2 release notes that explain this change of behaviour.

**To Reproduce**
1. create a project with two columns named 'JSON' und 'result'
2. apply the following code from my operation history
```javascript
[
  {
    "op": "core/text-transform",
    "engineConfig": {
      "facets": [],
      "mode": "row-based"
    },
    "columnName": "JSON",
    "expression": "grel:'[ \"foo\", null ]'",
    "onError": "keep-original",
    "repeat": false,
    "repeatCount": 10,
    "description": "Text transform on cells in column JSON."
  },
  {
    "op": "core/text-transform",
    "engineConfig": {
      "facets": [],
      "mode": "row-based"
    },
    "columnName": "result",
    "expression": "grel:forEach(cells['JSON'].value.parseJson(), v, 'x: ' + v).join(' || ')",
    "onError": "store-error",
    "repeat": false,
    "repeatCount": 10,
    "description": "Text transform on cells in column result."
  }
]
```

**Current Results**
In OR 3.1 this results in the value 'x: foo || x: null' in column result, in OR 3.2 it gives 'x: foo'.

**Expected behavior**
Not sure. I think 'x: foo || x: null' or maybe 'x: foo || x: ' would be correct? Or some kind of error message. Or was the behaviout in OR 3.1. erroneous The point is that the behaviour changed and I wasn't able to predict it from reading the release notes.

**Screenshots**
![or_json](https://user-images.githubusercontent.com/53606837/66834779-978bda00-ef5e-11e9-81d3-09c4d8b68220.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Browser Version: Chromium Version 77.0.3865.90 (Offizieller Build) snap (64-Bit)

 - JRE or JDK Version:
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu219.04)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu219.04, mixed mode, sharing)

**OpenRefine (please complete the following information):**
 - Version OpenRefine 3.1 [b90e413] and OpenRefine 3.2 [55c921b]

**Comment by mnhampl** [comment]
The null value is inside the JSON espression `[ "foo", null ]` so it should be a real null value -- at least it is not a string. 

As `'string' + null` evaluates to `null` in GREL I guess the 3.2-behaviour is more consistent. 

Thanks for the link to #1841

**Comment by mnhampl** [comment]
I think it is not a bug. The new behaviour seems to be consistent to me, so I'm going to close the issue.

**Comment by ostephens** [comment]
@mnhampl I think you are correct that this change should have been in release notes. While I agree that `"[ \"foo\", null ]".parseJson()[1]` should give a true `null` so this change is a positive one, I'm sorry that we let this get through without it being documented - apologies.

I'm also really not keen on the `'string' + null` -> `null` situation - but that's a whole separate discussion!

**Comment by mnhampl** [comment]
You broke down my example to a much simpler expression, thank you :)

To round it up I tried the following in 3.1 and 3.2 and wanted to share the results:

`"[ null ]".parseJson()[0]` -> `null` in 3.1 (null value, not the String)
`"[ null ]".parseJson()[0]` -> `null` in 3.2 (null value, not the String)

`"[ null ]".parseJson()[0].toString()` -> `"null"` in 3.1 (string value "null")
`"[ null ]".parseJson()[0].toString()` -> `""` in 3.2 (empty string)

**Comment by wetneb** [comment]
I agree we should be better at reporting that sort of change in the release notes. Sorry about that! I am now aiming to write them as changes get merged.

**Comment by ostephens** [comment]
It looks like this change may have (partially?) crept in as a result of the change to Jackson for handling JSON generally in OpenRefine. Comparing the types you get back from parsing JSON in 3.1 and 3.2

3.1: `"[null]".parseJson()[0].type()` -> `org.json.JSONObject$Null`
3.2: `"[null]".parseJson()[0].type()` -> `undefined`

for comparison of just a normal null value in each version

3.2: `null.type()` -> `undefined`
3.2: `null.type()` -> `undefined`

Essentially In 3.2 the `null` obtained from parsing a null from JSON is in line with a normal `null` value in OpenRefine, which wasn't the case previously.

Combined with the previous change that Thad mentioned https://github.com/OpenRefine/OpenRefine/pull/1650, this all comes to the behaviour you are now seeing.

Just for final completeness, based on your initial example above you can use the following expressions to get the different outcomes you suggest as possible desirable outcomes:

`forEach(cells['JSON'].value.parseJson(), v, 'x: ' + v.toString()).join(' || ')` -> `x: foo || x:`
OR
`forEach(cells['JSON'].value.parseJson(), v, 'x: ' + v.coalesce("null")).join(' || ')` -> `x: foo || x: null`
