### ISSUE TITLE
Add Error for GREL cross showing null values when using reference column of other type than string.

### ISSUE THREAD

**Issue by GhostKong** [OpenRefine/OpenRefine#2204]
GREL cross shows null values when using reference column of type other than text string. It is true that cross requires string value types however, it would be nice to have a check done and error handling when pointing to a value of type other for the reference column.

I ran into this when using reconcile-csv and not paying attention to import type for my unique id column. It is my fault but would be nice to see an error returned other than null. Also, adding this in case someone does something silly such as I have and it takes them a few minutes to catch as to why their cross is not showing the data.

**Comment by antoine2711** [comment]
Hi @GhostKong: well, now, the cross() function can operate with key columns that are of any type. 

If you go check: [#2461](https://github.com/OpenRefine/OpenRefine/issues/2461), you can see it. It will be in v3.4.

Regards,
   Antoine

**Comment by antoine2711** [comment]
@tfmorris: we can close this one.

Regards, Antoine
