### ISSUE TITLE
Language fallback not working in UI

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2209]
When using another language than English in the UI, if a string has not been translated it will not be displayed correctly. We want to use the English string as a fallback instead.

**Comment by thadguidry** [comment]
It's nice to see nearly 2 years worth of delays, incremental fixes, etc., to the point where this is finally fixed and merged.
Thanks so much to all that worked on this effort!  @ostephens @remram44 @wetneb !!!!
