### ISSUE TITLE
Frame size problem when using cluster and edit

### ISSUE THREAD

**Issue by kpbrunner** [OpenRefine/OpenRefine#2216]
**Describe the bug**
When I try to use the 'metaphone3' keying function, the frame that opens up is way wider than the browser window, the sliding selection boxes that usually appear in the right side of the frame are not visible, and the buttons across the bottom of the frame ('Select All', 'Unselect All', etc.) are not available.

**To Reproduce**
1. Go to 'Edit cells'
2. Click on 'Cluster and edit'
3. From the 'Keying Function' menu, click on 'metaphone3'

**Expected behavior**
'fingerprint', 'ngram-fingerprint', and 'Beider-Morse' keying functions all work fine. The problem that occurs with 'metaphone3' also occurs with 'cologne-phonetic' and 'Daitch-Motokoff', although I don't need the latter two for the work I am doing.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser Version: Firefox 68.1.0esr (64-bit)
 - JRE or JDK Version: 1.8.0_221

**OpenRefine (please complete the following information):**
 - OpenRefine 3.3 Beta

**Datasets**
Dataset is official use only.

**Comment by thadguidry** [comment]
I'm not seeing this issue when I just tested it.
Can you give us a few example rows from your dataset?
What is your screen resolution, by the way?

**Comment by tfmorris** [comment]
No response in 6 months. Closing as unreproducible.
