### ISSUE TITLE
Too long paths in 3.3 beta

### ISSUE THREAD

**Issue by PeterJPower** [OpenRefine/OpenRefine#2217]
Downloaded today  OpenRefine 3.3 Beta into  Windows 10 system.  By unzipping I got five times a warning "error Dx80010135 Path is too long". First one was "ExpessionNominaValueGrouper$indexedNominalFacetChoice.class". Downloanding failed.

**Comment by wetneb** [comment]
Interesting, thanks for reporting that. Did the extraction of zip fail in the end? Which unzipper are you using?

I'd be very interested to improve our packaging, perhaps #2107 could solve this.

**Comment by PeterJPower** [comment]
Extraction failed. I used standard Unzip feature of Resource Manager in Windows 10.  I have also 7-zip seldom used. Tested it now and had with it no difficulties to unzip 3.3 beta which also launched normally. Maybe a bug in Windows 10 Resource Manager?

**Comment by wetneb** [comment]
We do get some warnings about path lengths when generating the zip… It's not clear to me what is the best way to solve this. Are there better supported archive formats on Windows that we could use instead? Could it be our compressor's fault (perhaps there are better zip compressors which deal with this problem in a different way)?

**Comment by thadguidry** [comment]
I think this is an isolated event for Peter.
I have no such problems with right-clicking the
"openrefine-win-3.3-beta.zip" file and choosing "Extract All..." on Windows
10 Pro Build 18362
My starting folder location is "E:\Downloads\"

Thad
https://www.linkedin.com/in/thadguidry/

**Comment by PeterJPower** [comment]
Right-clicking worked also for me. So obvious bug only in Unzip feature of Resource Manager in Windows 10 remains. Be it M$'s problem!

Thanks for new version. I use OpenRefine actively for cleaning genealogical net sources.

**Comment by thadguidry** [comment]
@PeterJPower I thought I would update you with information I found from my company Group IT that might help with the general issue that you were experiencing with Resource Manager itself (which makes longer paths more likely).
The workaround is to enable `LongPathsEnabled` in the Windows Registry.  This will allow Windows to recognize up to 32,000+ chars in a Path without problems.

Here's how to do that from Microsoft: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#enable-long-paths-in-windows-10-version-1607-and-later
