### ISSUE TITLE
impossible to connect to google sheet to import a private dataset

### ISSUE THREAD

**Issue by msaby** [OpenRefine/OpenRefine#2223]
**Describe the bug**

Error message (in french, sorry) when I try to authorize Openrefine to access a private google sheet :

"La fonctionnalité "Se connecter avec Google" a été désactivée temporairement pour cette application
Cette application n'a pas encore été validée par Google et ne peut pas bénéficier de la fonctionnalité Google Sign-In."

![image](https://user-images.githubusercontent.com/932804/69223214-3c5f8f80-0b7b-11ea-836a-f17afa2119c8.png)

**To Reproduce**

Create a private google sheet
Try to sign-in in "Google Data" (by the way this naming is not good)

**Current Results**
What results occured or were shown.

**Expected behavior**
A clear and concise description of what you expected to happen or to show.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Version: Chrome
 - JRE or JDK Version : 1.8.231

**OpenRefine (please complete the following information):**
 - Version: Openrefine 3.3 beta

**Datasets**
 

**Additional context**

**Comment by msaby** [comment]
Addition : 
even with a public dataset, it is not working : 

![image](https://user-images.githubusercontent.com/932804/69223481-b7c14100-0b7b-11ea-8c58-ae1649cdc38e.png)

**Comment by wetneb** [comment]
That must be due to the fact that our OAuth tokens were included in the source code, as I pointed out in the pull request #1525.

**Comment by msaby** [comment]
ok, so for the definitive 3.3 version, you will "swap the credentials with fresh ones before packaging" as you wrote ?

**Comment by thadguidry** [comment]
@wetneb If we really need some help here with Google OAUTH expert on policy or practices, then I can certainly raise a concern with Simon Rogers and have him point us to someone to assist with answering any questions you have.  Let me know, and I can start the private email chain with you, if need be.

**Comment by wetneb** [comment]
@msaby yeah, I should have done it for the previous releases too in fact.

@thadguidry there is nothing special we need to know - the situation is clear and there is no good workaround sadly.

**Comment by wetneb** [comment]
Closing this without a code change since the OAuth tokens are not stored there.
