### ISSUE TITLE
Error importing date from ODS file

### ISSUE THREAD

**Issue by msaby** [OpenRefine/OpenRefine#2224]
**Describe the bug**

A date in a cell in a ODS file is imported as a "java.util.GregorianCalendar" and displayed as 

 java.util.GregorianCalendar[time=1546297200000,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id="Europe/Paris",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=184,lastRule=java.util.SimpleTimeZone[id=Europe/Paris,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=1,YEAR=2019,MONTH=0,WEEK_OF_YEAR=1,WEEK_OF_MONTH=1,DAY_OF_MONTH=1,DAY_OF_YEAR=1,DAY_OF_WEEK=3,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=0,ZONE_OFFSET=3600000,DST_OFFSET=0] |  

**To Reproduce**

Create a ODS file with Libreoffice

Put a date in a cell (like 1/1/2000)

Import into openrefine

**Current Results**
What results occured or were shown.

**Expected behavior**
A clear and concise description of what you expected to happen or to show.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Version: Chrome
 - JRE or JDK Version: 1.8.0.231

**OpenRefine (please complete the following information):**
 - Version :  OpenRefine 3.3 Beta

**Datasets**
If you are allowed and are OK with making your data public, it would be awesome if you can include or attach the data causing the issue or a URL pointing to where the data is.
If you are concerned about keeping your data private, ping us on our [mailing list](https://groups.google.com/forum/#!forum/openrefine)

**Additional context**

**Comment by wetneb** [comment]
Related: #533 proposes to add support for storing dates (without time) in cells.

**Comment by wetneb** [comment]
Clearing milestone since PR is abandoned

**Comment by tfmorris** [comment]
This likely has the same root cause as #1908 and is another regression which was introduced by the Java 8 Date/Time changes in OpenRefine 3.0, as described in https://github.com/OpenRefine/OpenRefine/issues/1908#issuecomment-650664131.

**Comment by tfmorris** [comment]
Although I changed this to an `OffsetDateTime`, which is what OpenRefine currently uses internally, using `LocalDateTime` might be more appropriate since OpenOffice Calc doesn't have the concept of timezones.
