### ISSUE TITLE
save/open json scripts

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#223]
_Original author: wfznimbl...@gmail.com (November 16, 2010 16:20:36)_

<b>What steps will reproduce the problem?</b>

[save/open json scripts through a file manager dialog]

<b>What is the expected output? What do you see instead?</b>

[right now I have to copy &amp; paste json scripts into notepad, then copy &amp; paste into a new project]

<b>What version of the product are you using? On what operating system?</b>

Win 7/2.0

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=223_

**Comment by antoine2711** [comment]
@tfmorris: here, if I understand correctly, he wants to be able to save and load operation history from/to file in the user file system, is that it?

Regards, Antoine

**Comment by wetneb** [comment]
Partially solved by #5022. Only the download option left. On the longer term (in the coming months) we want to hide the JSON itself and replace it by a better visualization of workflows.

**Comment by ostephens** [comment]
@wetneb when you say "one the download option left" do you mean download of the operation history - as that already exists.

Or do you mean adding support to export/import the JSON defining project download options (templates or custom tabular code)?

**Comment by wetneb** [comment]
Sorry I mixed things up indeed! It's the other option that is missing: uploading a list of operations without having to resort to copy and paste. Downloading is indeed already supported.

**Comment by ostephens** [comment]
And uploading by #5022 as you said?

**Comment by wetneb** [comment]
Looks like my attention span is getting way too short -_- Thank you!
