### ISSUE TITLE
Add new record field for count of rows in a record

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#2237]
It would be useful to have a simple field in record that returns the row count of the WrappedRecord.

**Describe the solution you'd like**
Something like  `row.record.count` which would return a String of the # number of rows contained in the WrappedRecord.
Example

```
record , data
A  , 100
   , 200
B  , 100
   , 200
   , 300
```

GREL applied on column "record" to insert a new column "count" containing count of record rows:
`row.record.count`

RESULT:

```
record , data, count
A  , 100, 2
   , 200, 2
B  , 100, 5
   , 200, 5
   , 300, 5
   , 400, 5
   , 500, 5
```

**Describe alternatives you've considered**
facetCount() does not count the actual record rows, for instance with
`facetCount(value, "cell.value", "record")`

**Additional context**
As discussed on [mailing list here](https://groups.google.com/d/topic/openrefine/6iQQzEx19oA/discussion)

**Comment by antoine2711** [comment]
I'm not sure to understand: like it was written in the mailing list discussion, a « Transform » calculation like this will give you the number of rows in a record, wouldn't it?

`with(row.record, vR, vR.toRowIndex - vR.fromRowIndex)`

Regards,
   Antoine

**Comment by thadguidry** [comment]
@antoine2711 I'm not worried about GREL row indexing support here, since the proposed new GREL command above would be performed more easily once we have Apache Spark as our new backend.  Pretty much every issue we have related to [label: records](https://github.com/OpenRefine/OpenRefine/labels/records) like this one will be easily solved.  We just need to be patient.

**Comment by tfmorris** [comment]
We have `row.record.rowCount`. Is this asking for something different? (besides the name, of course)

Here are all the fields in a WrappedRow (ie Record):

https://github.com/OpenRefine/OpenRefine/blob/cb55cdfdf6f9ca916839778dc847cce803688998/main/src/com/google/refine/expr/WrappedRow.java#L89-L100

**Comment by wetneb** [comment]
This is indeed already documented:
https://docs.openrefine.org/manual/expressions#record

Therefore closing, but counting on @thadguidry to reopen if we misunderstood the request.

**Comment by thadguidry** [comment]
@wetneb at the time I don't recall seeing rowCount documented.  Thanks!
