### ISSUE TITLE
add new option for spliting multi-valued cells: by transition between lowercase and uppercase, and number and text

### ISSUE THREAD

**Issue by msaby** [OpenRefine/OpenRefine#2238]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**

I discoverd interesting options in MS PowerQuery. It could be nice to have the same in OR : split by transition between lowercase and uppercase, split by transition between number and text

Here is the menu (in french) in PowerQuery : 

![image](https://user-images.githubusercontent.com/932804/70234028-049e3d80-1760-11ea-8ef0-bc93ea839b90.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by thadguidry** [comment]
You mentioned in the title that "for spliting columns"...
But I'm wondering if you meant splitting multi-valued cells, instead?
If so, you would like to see this box made a bit bigger and have some additional "radio button" options?

![Annotation 2019-12-05 084009](https://user-images.githubusercontent.com/986438/70244947-ec67f780-173a-11ea-82ec-8195a232ffb6.png)

**Comment by msaby** [comment]
I changed the title of the issue ;-)

It could be a new menu (like MS PowerQuery) or more options in the dialog box. I don't know what would be the best...

**Comment by msaby** [comment]
Split by capitalisation was something I was asked by a collegue. See https://stackoverflow.com/questions/58845900/how-to-split-a-string-based-on-capitalized-initials

**Comment by lisa761** [comment]
Can I take up this issue?

**Comment by thadguidry** [comment]
@lisa761 Thanks for volunteering Lisa!  Assigned to you.
I see this new feature as expanding the existing **Split multi-valued cells** dialog with 2 additional radio buttons:
* Split between a Lowercase and Uppercase letter
* Split between a Number and Letter (and vice versa)

Agree?

**Comment by lisa761** [comment]
@thadguidry yup, okay

**Comment by lisa761** [comment]
Hi, So I was thinking would it be better if we provide an option for transition between all, i.e. one from lowercase to uppercase and another for uppercase to lowercase, one from letters to numbers and one from numbers to letters? Or we just give two options and then split whenever there is a transition from either uppercase or lowercase to lowercase or uppercase respectively.

For eg. If the value was, say 'fooBarABABFooBar'

Then split for both transitions upper to lower and lower to upper case would be: 
> foo B ar ABABF oo B ar  
  
Only lower to uppercase would be:
> foo Bar ABABFoo Bar  
  
Uppercase to lowercase would be: 
> fooB arABABF ooB ar  

So should we provide all the options or only the first one?

**Comment by thadguidry** [comment]
Normal English capitalization rules tell us that only the 2 options I mentioned would be useful.
This issue is just to have some quick menu options to support those 2 common use cases.  If users have other use cases, they can resort to having the power of GREL and other languages we support.  If users REALLY want to have additional options in the menus, they can request an enhancement issue and then upvote.

As a general rule, we typically try not to over engineer until we know the usefulness based on user feedback (mailing lists, surveys, issues).

**Comment by tfmorris** [comment]
> so I was thinking would it be better if we provide an option for transition between all, i.e. one from lowercase to uppercase and another for uppercase to lowercase, one from letters to numbers and one from numbers to letters?

The PowerQuery example given by the original requestor provides all four options, although it appears that they are mutually exclusive (they each appear to be a separate drop down menu pick).

I'm not convinced that splitting on uppercase to lowercase transitions is very useful, but all four were originally requested.

**Comment by thadguidry** [comment]
@tfmorris The split from uppercase then lowercase can still be useful in scientific domains where its much more prevalent than newsrooms.
Small example:
`kPa  =  [k, Pa] = [kilo, pascal] = [1000 pascals]`
and crap like that. ;-)
