### ISSUE TITLE
Publish data model, GREL and operations in standalone Maven artifacts

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2254]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
As an extension developper, I would like to be able to import OpenRefine as a Java dependency in my extension project (using Maven, Gradle…).

**Describe the solution you'd like**
We want to break down the `main` module into smaller submodules which can be imported independently. Here is a rough draft (some might be merged or split eventually):
* the core data model: `Project`, `Row`, `Cell`, `Column`, `Recon`, `ReconCandidate`…
* the core API: only the interfaces and abstract classes such as `AbstractOperation`, `Engine`, `Facet`, `Evaluable` and so on.
* GREL
* the concrete operations and facets we supply;
* the full API, including Command, OverlayModel, Preferences… all the classes you could want to reference to build an extension
* the concrete commands we supply.

By splitting up into meaningful submodules we want to make it easy to rely on parts of the data model without pulling in loads of dependencies (typically, we want to be able to work on the data model without importing butterfly).

Splitting the `main` module like this does not require hosting the submodules in separate repositories. I propose to keep using this repository to host all these submodules.

**Describe alternatives you've considered**
At the moment, the `rdf-extension` is the main extension maintained outside this repository, and it uses a local Maven repository stored in the git repository itself:
https://github.com/stkenny/grefine-rdf-extension/blob/v1.1.7-orefine-3.2/pom.xml
This is not ideal since it forces @stkenny to build jars and store them in the git repository.

**Additional context**
If our Maven configuration can be made suitable for that, then jitpack.io could also be used (to generate a Maven repository where artifacts are built on the fly from git).

This is a first step for #1433

**Comment by fpompermaier** [comment]
It will be important to properly refactor and modularize the project history. If the project history could be automatically translated to SQL then the integration with Spark, Flink, Drill and similar would be quite straightforward (you just need to implement the proper wrapper to the UDFs)

**Comment by wetneb** [comment]
@fpompermaier this issue is only about creating the appropriate jars and uploading them to Maven, possibly by moving things around a bit in the repository - not much will change in the classes themselves.

**Comment by thadguidry** [comment]
@wetneb you mentioned a first step for #1941 is that the right issue number?

**Comment by wetneb** [comment]
Fixed!

**Comment by wetneb** [comment]
The separation is done but the actual publishing will have to wait for a release - we don't want to pollute Maven with half-baked prototypes.

**Comment by wetneb** [comment]
When this is published, we should notify users here: https://github.com/RMLio/rmlmapper-java/issues/26

**Comment by tfmorris** [comment]
Implicit in this is converting all these internal APIs into publicly supported, well engineered, stable APIs. That's a pretty big lift and I have serious reservations about committing such a tiny team to such a giant task.

**Comment by wetneb** [comment]
See my answer on the mailing list: https://groups.google.com/forum/#!searchin/openrefine-dev/ElasticSearch%7Csort:date/openrefine-dev/ijZj298lglU/-kDHaxcfCQAJ

**Comment by wetneb** [comment]
I have ended up doing this in 3.x as well. It is now done in the CI, into the Maven Central Snapshot repository for normal commits and (hopefully) into Maven Central itself for official releases.

**Comment by wetneb** [comment]
The first upload in Maven Central of our core Maven artifacts succeeded:
https://search.maven.org/search?q=openrefine
