### ISSUE TITLE
Support for reordering of independent operations

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2255]
_This is work package 5 in our [2020 roadmap](http://openrefine.org/images/czi-eoss-proposal.pdf)._

## Goal

Given two consecutive row-wise operations operating on disjoint columns, the user should be able to swap them, by drag and drop. This would not change the effects of the workflow: the state of the table would be the same after the two operations.

## Background

This feature is not very useful by itself to users: currently, people rarely care about how tidy their history looks like. In some cases it should allow users to undo an operation that is buried in the history and keep the ones after, by dragging it down. This is probably a marginal use case.
However, this feature is a crucial first step towards:
* executing independent operations in parallel (such as fetching URLs and reconciling another column at the same time)
* multi-user support, to let users work on independent parts of the project simultaneously

## Work plan

This relies on #2252 as a prerequisite.
Then, we need to add some backend logic to:
* Check if two row-wise column-based operations can be swapped;
* Perform the swap, by generating the new `Change` objects;
* Potentially update the project state if the history cursor was between the two operations exchanged.
This should all be exposed in a new command.

Frontend-side, we should add some light jQuery code to handle the drag and drop in the history. We might want to signal in some ways that operations can be swapped, although this should become clearer with graphical visualization (#2253).

**Comment by thadguidry** [comment]
Can we write down currently what the criteria rule would be for the Check that the operations could be swapped?

**Comment by wetneb** [comment]
Yes: the second operation should not depend on any column that the first one writes to.

**Comment by thadguidry** [comment]
Hmm, just thinking off the cuff here, but I wonder if the [Pregal API](https://spark.apache.org/docs/3.0.0/graphx-programming-guide.html#pregel-api) might help in some fashion directly in this issue.  Or generally as a property graph and using parts of [Spark's GraphX](https://spark.apache.org/docs/3.0.0/graphx-programming-guide.html).

**Comment by wetneb** [comment]
I have changed my mind about this: I don't see it as a meaningful first step towards concurrent operations. As it stands, it does not strike me as matching a user need either. I have found myself in the situation of realizing that I should have done a particular operation earlier, but it does not seem like a good UX to do the operation later and then use some history reordering feature to put it back into place: instead, a way to insert an operation earlier in the history would be more useful.

For instance, one thing I would find more useful would be that if I try to apply a new operation while having undone some operations before, I am given a choice between erasing the future operations (which what happens currently) and inserting the operation without discarding the future operations, when that is possible (which could still mean deleting some future entries or re-running some long-running future operations).

**Comment by thadguidry** [comment]
@wetneb So is the better way to:
1.  a rollback to a history point
2.  insert some operation
3. replay the history forwards from after that

**Comment by wetneb** [comment]
Yes exactly, I think that would be a more common use case.

**Comment by ostephens** [comment]
>So is the better way to:
> * a rollback to a history point
> * insert some operation
> * replay the history forwards from after that

I think (from my experience) the last step needs to be:
* SELECTIVELY replay the history forwards from after that

i.e. decide which of the steps are replayed and which are not.

The reason for this is usually it's not just that a step was missed (although that sometimes happens) but that a section of the process was wrong in retrospect, and the need is to do a different set of steps at that stage of the process (rather than just adding in additional steps as Thad's description suggests to me)

**Comment by wetneb** [comment]
Interesting, so you'd prompt the user to select which of the future steps should be retained? Perhaps somewhat in the spirit of the current "Extract" dialog, with checkboxes for each future operation maybe?

**Comment by ostephens** [comment]
Yes exactly that. It's not exactly a common occurrence but what I've had to do in the past is:
* Extract the steps I need to preserve and save the JSON to a file
* Step back in the history before whatever issue I had
* Correct (or just skip) the processing I need to do at that stage
* Apply the steps I extracted earlier

**Comment by thadguidry** [comment]
Agree.  Almost like PAUSING [ || ] the future steps until I am ready to PLAY [ > ] them again.

**Comment by wetneb** [comment]
@ostephens we are planning a similar sort of functionality not for inserting, but deleting operations while preserving the future ones. As part of that, we plan that OpenRefine would be able to indicate which future operations can be kept, which ones will be discarded and which ones will need recomputing.

For instance, if you are inserting an operation that modifies a column, a future operation that reconciles that column would need re-computing (since the data it runs on was modified), and OpenRefine would automatically trigger that re-computation.
Similarly, if you delete an operation that creates a new column, any operation that reads data in that column would be dropped (and transitively so: if any future operation depend on those newly-dropped operations, they would get dropped too).

With this knowledge in mind, do you think we should still give the user the option to select which of the remaining operations should be kept? Or is it sufficient to keep all the operations that can be kept based on columnar dependencies between operations?

Since we are planning to add support for deleting an history entry, I wonder if your interest in selecting which future operations to retain could be satisfied by:
* retaining as many operations as we can when the user inserts an operation
* let them delete any future operations that are not needed later on, using the dedicated button

I think that should make for simpler UIs since we wouldn't need to prompt the user for as much information as they insert an operation.

@cooperzoe has been working on mock-ups on this UI, so once we are ready to share them it might make things clearer.

**Comment by ostephens** [comment]
Thanks @wetneb. As I noted above this sort of workflow isn't a common occurrence for me so it's hard to be confident about what will/won't be appropriate (it is probably over a year since I last needed to do this type of operation). However, my initial feeling is that what you are describing would be sufficient, at least for the vast majority of situations
