### ISSUE TITLE
SQL Exporter skips null values

### ISSUE THREAD

**Issue by colognesdgs** [OpenRefine/OpenRefine#2265]
I have tried to export data as a SQL script and have used tables, that have empty columns:

```
OTS	NAME	STRS	BEZS	KLRID	EXTID	OTNAME	STATUS	STRNAME	BEZNAME	OBJECTID	ORIG_FID	OBJEKTTYP	SONSTIGES	SHAPE_LENG	HYPERLINK1	HYPERLINK2	BEMERKUNGEN	BEMERKUN_1
205	Kalscheurer Weiher	3415	2	12811	 	Zollstock	1	Zollstocker Weg	Rodenkirchen	23	23	10		1472.59572795	http://www.stadt-koeln.de/leben-in-koeln/freizeit-natur-sport/parks/65785/ 			Kiosk, barrierefrei
```

e.g. Column HYPERLINK2, BEMERKUNGEN is empty in the record.

The sql exporter generates a statement like this:

```
INSERT INTO ODC_PARKANLAGEN (OTS,NAME,STRS,BEZS,KLRID,EXTID,OTNAME,STATUS,STRNAME,BEZNAME,OBJECTID,ORIG_FID,OBJEKTTYP,SONSTIGES,SHAPE_LENG,HYPERLINK1,HYPERLINK2,BEMERKUNGEN,BEMERKUN_1) VALUES ( 205,'Kalscheurer Weiher',3415,2,12811,' ','Zollstock',1,'Zollstocker Weg','Rodenkirchen',23,23,10,1472.59572795,'http://www.stadt-koeln.de/leben-in-koeln/freizeit-natur-sport/parks/65785/ ','Kiosk, barrierefrei' ); 
```

Which leads to an error in MariaDB, for example:
```
ERROR 1136 (21S01): Column count doesn't match value count at row 1
```

I have expected the sql exporter to create a statement like this:

```
INSERT INTO ODC_PARKANLAGEN 
(OTS,NAME,STRS,BEZS,KLRID,EXTID,OTNAME,STATUS,STRNAME,BEZNAME,OBJECTID,ORIG_FID,OBJEKTTYP,SONSTIGES,SHAPE_LENG,HYPERLINK1,HYPERLINK2,BEMERKUNGEN,BEMERKUN_1) VALUES ( 205,'Kalscheurer Weiher',3415,2,12811,' ','Zollstock',1,'Zollstocker Weg','Rodenkirchen',23,23,10,NULL,1472.59572795,'http://www.stadt-koeln.de/leben-in-koeln/freizeit-natur-sport/parks/65785/ ',NULL, NULL,'Kiosk, barrierefrei' );
```

How did you solve this issue?

Best regards,
Michael

**Comment by thadguidry** [comment]
There are various things that might not be obvious with your source data being shown in OpenRefine.
We have various options for you to create the export to include NULL or not.  Please explore all of them for your use case.

My hunch is that:
It is likely that your original data that is in the OpenRefine data grid, is stored as an empty string, "", and not as a `null` value?  or something else that is causing the SQL Exporter to not understand if you truly have a blank or null cell?  Also, Non-breaking spaces in the cells or something else?  What does `value.escape('javascript')` show if you facet on some of the cells to see what hidden chars they might contain?  or a Facet -> Customized facet -> Unicode char-code facet ?  Play with facets to discover hidden chars that might be preventing an empty string (blank) or `null` to appear in the source data.

You can convert those empty strings (blanks) to a `null` value by using the column menu options:
1. Facet on the columns that have empty strings with:  Facet -> Customized facets -> facet by empty string.
2. On the facet, select the `true` values, so that you are only showing those rows that have a empty string (blank) in order to perform the next step 3.
3. On the column menu: Edit cells -> Common transforms -> To null

You can expose to show `null` values by using the **All** column menu and choose "**View**" -> "**Show/Hide 'null' values in cells**"

Also, with the above steps done... you can use the following options on export:

1. Null options on Content tab:

![Annotation 2019-12-25 144524](https://user-images.githubusercontent.com/986438/71450380-52d2ab00-2726-11ea-9dbd-2df2b734c3c5.png)

2. NULL option on Download tab:

![Annotation2 2019-12-25 144524](https://user-images.githubusercontent.com/986438/71450382-5c5c1300-2726-11ea-82e2-c2ef21360596.png)

Let us know if that resolves for you and we can close this issue.

**Comment by MikaMaracuja** [comment]
Hi Thad,

I think I have the same settings than you and still have the problem, but
it seems to be more a problem of the json reader than of the sql exporter:

dataimport
[image: grafik.png]

the original json data has mixed representation of "empty" strings and
nulls:
[image: grafik.png]


[image: grafik.png]

I have tried te import with and without "preserve empty strings".

[image: grafik.png]

[image: grafik.png]





[image: grafik.png]
[image: grafik.png]

[image: grafik.png]

The data is interpreted as null, but stored by openrefine as empty strings.
If I display all columns to show their null values, nothing is shown:
[image: grafik.png]




CREATE TABLE ODC_Parkanlagen2_json (
OTS VARCHAR(255) NULL,
NAME VARCHAR(255) NULL,
STRS VARCHAR(255) NULL,
BEZS VARCHAR(255) NULL,
KLRID VARCHAR(255) NULL,
EXTID VARCHAR(255) NULL,
OTNAME VARCHAR(255) NULL,
STATUS VARCHAR(255) NULL,
STRNAME VARCHAR(255) NULL,
BEZNAME VARCHAR(255) NULL,
OBJECTID VARCHAR(255) NULL,
ORIG_FID VARCHAR(255) NULL,
OBJEKTTYP VARCHAR(255) NULL,
SONSTIGES VARCHAR(255) NULL,
SHAPE_LENG VARCHAR(255) NULL,
HYPERLINK1 VARCHAR(255) NULL,
HYPERLINK2 VARCHAR(255) NULL,
BEMERKUNGE VARCHAR(255) NULL,
BEMERKUN_1 VARCHAR(255) NULL
);
INSERT INTO ODC_Parkanlagen2_json
(OTS,NAME,STRS,BEZS,KLRID,EXTID,OTNAME,STATUS,STRNAME,BEZNAME,OBJECTID,ORIG_FID,OBJEKTTYP,SONSTIGES,SHAPE_LENG,HYPERLINK1,HYPERLINK2,BEMERKUNGE,BEMERKUN_1)
VALUES
( '205','Kalscheurer Weiher','3415','2','12811','
','Zollstock','1','Zollstocker
Weg','Rodenkirchen','23','23','10','1472.59572795','http://www.stadt-koeln.de/leben-in-koeln/freizeit-natur-sport/parks/65785/
','Kiosk, barrierefrei' ),
( '102','Volksgarten','823','1','10458','
','Neustadt-Süd','1','Eifelstraße','Innenstadt','24','24','7','
','3930.08693801','http://www.stadt-koeln.de/leben-in-koeln/freizeit-natur-sport/parks/65812/
',' ',' ','Biergarten, Kinderspielplatz, Slackline,
Hundefreilauffläche' )


MariaDB [open_cgn_cube]> CREATE TABLE ODC_Parkanlagen2_json (OTS
VARCHAR(255) NULL,NAME VARCHAR(255) NULL,STRS VARCHAR(255) NULL,BEZS
VARCHAR(255) NULL,KLRID VARCHAR(255) NULL,EXTID VARCHAR(255) NULL,OTNAME
VARCHAR(255) NULL,STATUS VARCHAR(255) NULL,STRNAME VARCHAR(255)
NULL,BEZNAME VARCHAR(255) NULL,OBJECTID VARCHAR(255) NULL,ORIG_FID
VARCHAR(255) NULL,OBJEKTTYP VARCHAR(255) NULL,SONSTIGES VARCHAR(255)
NULL,SHAPE_LENG VARCHAR(255) NULL,HYPERLINK1 VARCHAR(255) NULL,HYPERLINK2
VARCHAR(255) NULL,BEMERKUNGE VARCHAR(255) NULL,BEMERKUN_1 VARCHAR(255)
NULL);INSERT INTO ODC_Parkanlagen2_json
(OTS,NAME,STRS,BEZS,KLRID,EXTID,OTNAME,STATUS,STRNAME,BEZNAME,OBJECTID,ORIG_FID,OBJEKTTYP,SONSTIGES,SHAPE_LENG,HYPERLINK1,HYPERLINK2,BEMERKUNGE,BEMERKUN_1)
VALUES ( '205','Kalscheurer Weiher','3415','2','12811','
','Zollstock','1','Zollstocker
Weg','Rodenkirchen','23','23','10','1472.59572795','
http://www.stadt-koeln.de/leben-in-koeln/freizeit-natur-sport/parks/65785/
','Kiosk, barrierefrei' ),( '102','Volksgarten','823','1','10458','
','Neustadt-Süd','1','Eifelstraße','Innenstadt','24','24','7','
','3930.08693801','
http://www.stadt-koeln.de/leben-in-koeln/freizeit-natur-sport/parks/65812/
',' ',' ','Biergarten, Kinderspielplatz, Slackline, Hundefreilauffläche' )
Query OK, 0 rows affected (0.01 sec)

    -> ;
ERROR 1136 (21S01): Column count doesn't match value count at row 1
MariaDB [open_cgn_cube]>

I have attached the import / test data json file.

Cheers,
Michael


Am Mi., 25. Dez. 2019 um 22:07 Uhr schrieb Thad Guidry <
notifications@github.com>:

**Comment by thadguidry** [comment]
Hi @MikaMaracuja ,  I am having a hard time understanding this.  Can you look at the Github issue directly (instead of replying by email) and **Edit** your original comment?  (We don't see the images that you tried to attach or the JSON test file.  With Github you can just drag and drop an image file into the edit box for the comment.  Just click the triple dot **...** on your comment and choose **Edit**)

**Comment by colognesdgs** [comment]
Hi Thad,

I think I have the same settings than you and still have the problem, but it seems to be more a problem of the json reader than of the sql exporter:

dataimport
![grafik](https://user-images.githubusercontent.com/49087803/71532903-04740680-28f6-11ea-85de-2fcb9d37d52f.png)


the original json data has mixed representation of "empty" strings and nulls:
![grafik](https://user-images.githubusercontent.com/49087803/71532917-12c22280-28f6-11ea-89c2-8ef47f35b746.png)

![grafik](https://user-images.githubusercontent.com/49087803/71532926-21a8d500-28f6-11ea-9266-33ee44a228bd.png)

I have tried te import with and without "preserve empty strings".
![grafik](https://user-images.githubusercontent.com/49087803/71532935-31c0b480-28f6-11ea-9196-4ad41223e744.png)

![grafik](https://user-images.githubusercontent.com/49087803/71532939-3ab18600-28f6-11ea-8b36-2adccde04422.png)


![grafik](https://user-images.githubusercontent.com/49087803/71532949-4a30cf00-28f6-11ea-9bed-55082e4fa936.png)

![grafik](https://user-images.githubusercontent.com/49087803/71532953-561c9100-28f6-11ea-83cb-1fd1699afce1.png)

The data is interpreted as null, but stored by openrefine as empty strings. If I display all columns to show their null values, nothing is shown:
![grafik](https://user-images.githubusercontent.com/49087803/71532960-66cd0700-28f6-11ea-9f33-3f71205188cf.png)

[ODC_Parkanlagen.json.txt](https://github.com/OpenRefine/OpenRefine/files/4006269/ODC_Parkanlagen.json.txt)




CREATE TABLE ODC_Parkanlagen2_json (
OTS VARCHAR(255) NULL,
NAME VARCHAR(255) NULL,
STRS VARCHAR(255) NULL,
BEZS VARCHAR(255) NULL,
KLRID VARCHAR(255) NULL,
EXTID VARCHAR(255) NULL,
OTNAME VARCHAR(255) NULL,
STATUS VARCHAR(255) NULL,
STRNAME VARCHAR(255) NULL,
BEZNAME VARCHAR(255) NULL,
OBJECTID VARCHAR(255) NULL,
ORIG_FID VARCHAR(255) NULL,
OBJEKTTYP VARCHAR(255) NULL,
SONSTIGES VARCHAR(255) NULL,
SHAPE_LENG VARCHAR(255) NULL,
HYPERLINK1 VARCHAR(255) NULL,
HYPERLINK2 VARCHAR(255) NULL,
BEMERKUNGE VARCHAR(255) NULL,
BEMERKUN_1 VARCHAR(255) NULL
);
INSERT INTO ODC_Parkanlagen2_json (OTS,NAME,STRS,BEZS,KLRID,EXTID,OTNAME,STATUS,STRNAME,BEZNAME,OBJECTID,ORIG_FID,OBJEKTTYP,SONSTIGES,SHAPE_LENG,HYPERLINK1,HYPERLINK2,BEMERKUNGE,BEMERKUN_1) VALUES 
( '205','Kalscheurer Weiher','3415','2','12811',' ','Zollstock','1','Zollstocker Weg','Rodenkirchen','23','23','10','1472.59572795','http://www.stadt-koeln.de/leben-in-koeln/freizeit-natur-sport/parks/65785/ ','Kiosk, barrierefrei' ),
( '102','Volksgarten','823','1','10458',' ','Neustadt-Süd','1','Eifelstraße','Innenstadt','24','24','7',' ','3930.08693801','http://www.stadt-koeln.de/leben-in-koeln/freizeit-natur-sport/parks/65812/ ',' ',' ','Biergarten, Kinderspielplatz, Slackline, Hundefreilauffläche' )


MariaDB [open_cgn_cube]> CREATE TABLE ODC_Parkanlagen2_json (OTS VARCHAR(255) NULL,NAME VARCHAR(255) NULL,STRS VARCHAR(255) NULL,BEZS VARCHAR(255) NULL,KLRID VARCHAR(255) NULL,EXTID VARCHAR(255) NULL,OTNAME VARCHAR(255) NULL,STATUS VARCHAR(255) NULL,STRNAME VARCHAR(255) NULL,BEZNAME VARCHAR(255) NULL,OBJECTID VARCHAR(255) NULL,ORIG_FID VARCHAR(255) NULL,OBJEKTTYP VARCHAR(255) NULL,SONSTIGES VARCHAR(255) NULL,SHAPE_LENG VARCHAR(255) NULL,HYPERLINK1 VARCHAR(255) NULL,HYPERLINK2 VARCHAR(255) NULL,BEMERKUNGE VARCHAR(255) NULL,BEMERKUN_1 VARCHAR(255) NULL);INSERT INTO ODC_Parkanlagen2_json (OTS,NAME,STRS,BEZS,KLRID,EXTID,OTNAME,STATUS,STRNAME,BEZNAME,OBJECTID,ORIG_FID,OBJEKTTYP,SONSTIGES,SHAPE_LENG,HYPERLINK1,HYPERLINK2,BEMERKUNGE,BEMERKUN_1) VALUES ( '205','Kalscheurer Weiher','3415','2','12811',' ','Zollstock','1','Zollstocker Weg','Rodenkirchen','23','23','10','1472.59572795','http://www.stadt-koeln.de/leben-in-koeln/freizeit-natur-sport/parks/65785/ ','Kiosk, barrierefrei' ),( '102','Volksgarten','823','1','10458',' ','Neustadt-Süd','1','Eifelstraße','Innenstadt','24','24','7',' ','3930.08693801','http://www.stadt-koeln.de/leben-in-koeln/freizeit-natur-sport/parks/65812/ ',' ',' ','Biergarten, Kinderspielplatz, Slackline, Hundefreilauffläche' )
Query OK, 0 rows affected (0.01 sec)

    -> ;
ERROR 1136 (21S01): Column count doesn't match value count at row 1
MariaDB [open_cgn_cube]>

I have attached the import / test data json file.

**Comment by colognesdgs** [comment]
[ODC_Parkanlagen.json.txt](https://github.com/OpenRefine/OpenRefine/files/4006276/ODC_Parkanlagen.json.txt)

**Comment by xbdeng** [comment]
I think this issue has been solved @wetneb
