### ISSUE TITLE
Coveralls integration seems broken

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2266]
https://coveralls.io/github/OpenRefine/OpenRefine has not been updated for months, coveralls info is not available on PRs: this needs to be fixed.

**Comment by wetneb** [comment]
Still failing with `Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report (default-cli) on project openrefine: I/O operation failed: No coverage report files found -> [Help 1]`, for instance here:
https://travis-ci.org/github/OpenRefine/OpenRefine/jobs/699439650#L2958

**Comment by thadguidry** [comment]
I think it might be better to switch to their new official GitHub Action.
https://github.com/marketplace/actions/coveralls-github-action

**Comment by wetneb** [comment]
That would amount to executing the tests a second time, in the GitHub action. This would only make sense if we get rid of Travis entirely, I would say.
