### ISSUE TITLE
Recognize "ij" as sometimes interchangeable for "y" when matching 

### ISSUE THREAD

**Issue by VDK** [OpenRefine/OpenRefine#2267]
In the Dutch language we have our very own digraph IJ. Up to the early 20th century people could be inconsistent in the writing of their name: sometimes writing it as a Y instead. Could OpenRefine take this into account in its algorithm when trying to find matches? I try adding the alternative spelling to the Wikidata item when dealing with dead Dutch foke but help would be appreciated.

**Comment by wetneb** [comment]
Hi!
Thanks for the suggestion! This would mostly require changes in the reconciliation service:
https://github.com/wetneb/openrefine-wikidata
Adding language-specific matching heuristics is an interesting problem. To solve it entirely we would need to run our own search index on top of Wikidata, so this require significant work and resources. However that is something I have been thinking about for a while now, so it might eventually happen!

**Comment by wetneb** [comment]
Closing this issue, let's continue the discussion in https://github.com/wetneb/openrefine-wikibase/issues/71.
