### ISSUE TITLE
Something is already running on http://127.0.0.1:3333/

### ISSUE THREAD

**Issue by Negens** [OpenRefine/OpenRefine#2277]
Hello ,

Distributor ID:	LinuxMint
Description:	Linux Mint 18.3 Sylvia
Release:	18.3
Codename:	sylvia

I've set no_proxy="localhost,127.0.0.1,127.0.0.1/8"
I also tried to set this no_proxy on refine.ini
I've tried to change the port
I've stopped the nginx server who was returning a 403 error page by default.
No services are running on the ports I've tried.

Whatever I do, I get this error.
I'm actually investigating the code to find the reason of this error.

**Comment by thadguidry** [comment]
You might try asking in the [LinuxMint forums](https://forums.linuxmint.com/) or their [Chat room](https://linuxmint.com/contactus.php).

However to get OpenRefine to startup on another port, you can follow our [FAQ ](https://github.com/OpenRefine/OpenRefine/wiki/FAQ)which details how to change the Port that OpenRefine uses.
Once you change the port in the refine.ini then start OpenRefine with `./refine` or explicitly the ip and port you wish to use `./refine -i 127.0.0.1 -p 3334`

**Comment by Negens** [comment]
Hello I also tried this option, it's the same result as modyfing the refine.ini file.

I launched some echo commands in the refine script
`$ ? = 22
URL = http://127.0.0.1:3333/
CURL -s URL | GREP =
Error: Something is already running on http://127.0.0.1:3333/ but doesn't seem to be OpenRefine. Maybe a proxy issue?
`

If the curl result is 22, the NOT_RUNNING viariable is supposed to be set, and it shouldn't go through the next steps of the check_running() function.

I checked the NOT_RUNNING "if" statement.
It doesn't enter the if statement and the NOT_RUNNING variable isn't populated.
`NOT RUNNING = `


To be sure, I tried this :
`        if [ "$?" = "7" ] || [ "$?" = "22" ] ; then
            echo "NOT RUNNING AT ALL"
            #NOT_RUNNING="1"
        fi
`
And I finally found something else that I can't explain.

if we do that :
`        curl -s -S -f $URL > /dev/null 2>&1

        echo "CURL RETURN value = "$?
        echo "CURL RETURN value = "$?
`
The result is 
`CURL RETURN value = 22
CURL RETURN value = 0
`

The $? value is changed by something or is reset to zero. I can't figure why for the moment.

**Comment by Negens** [comment]
I found the reason of the bug !
The $? variable is being reset by the first -eq statement.

Here is my test code 

`        if [ $? = 22  ] ; then
                echo "This is set to 22 !"
        fi

        if [ $? = 22  ] ; then
                echo "It should be 22 !"
        fi
`
The result :
`This is set to 22 !`


It doesn't go through the second -eq statement Now, I have to find how to fix it.

**Comment by Negens** [comment]
The solution is to put the valueof $?  into another variable:

curl -s -S -f $URL > /dev/null 2>&1
        MYRETURN=$?
        if [ $MYRETURN = "7"  ] || [ $MYRETURN = "22" ] ; then
                echo "This is OK !"
        fi


So, once I modified the code like this, it worked and I could launch the openrefine server :

 curl -s -S -f $URL > /dev/null 2>&1
MYRETURN=$?
        if [ $MYRETURN -eq "7" ] || [ $MYRETURN -eq "22" ] ; then
            NOT_RUNNING="1"
        fi

**Comment by thadguidry** [comment]
Glad you found the solution yourself!

**Comment by wetneb** [comment]
Thanks for the report @Negens! Others might have the same issue so I wonder if it would make sense to have your change in our codebase? Could you perhaps submit this as a pull request?

**Comment by Negens** [comment]
You're welcome @wetneb .
I'm not used to the github pull request system. I'm a bit lost in the branches.

**Comment by wetneb** [comment]
It's actually quite simple: you can just go here:
https://github.com/OpenRefine/OpenRefine/edit/master/refine
And this will create a fork for you. Just follow the steps and you should be able to submit the change directly from GitHub's interface, without having to deal with branches yourself.

**Comment by Negens** [comment]
@wetneb Thank you for your help. It's done.
I close the issue.
Regards !

**Comment by wetneb** [comment]
Thanks! You did not create a pull request yet though: you only created the changes in your own fork.
To create a pull request, you can go here:
https://github.com/OpenRefine/OpenRefine/compare/master...Negens:patch-1

By creating a pull request, you are proposing your changes to the main repository (https://github.com/OpenRefine/OpenRefine) rather than keeping them only in your own fork (https://github.com/Negens/OpenRefine).
