### ISSUE TITLE
Can't load data from Postgres-Database using in-build database-connectors

### ISSUE THREAD

**Issue by LibrErli** [OpenRefine/OpenRefine#2281]
Since Version **3.3 beta** the preview screen after submitting a SQL-Statement to load data from my local installed PSQL-database runs into an infinite loop.
Using Version 3.2 everything works fine. 

Unfortunately in the terminal windows there are no errors displayed during this error.

(Running OpenRefine on Ubuntu 18)

**Comment by wetneb** [comment]
Probably due to the CSRF change.

**Comment by mrcsparker** [comment]
This is fixed in #2323 

https://github.com/OpenRefine/OpenRefine/pull/2323/files#diff-954dd0488410445bcf889db15d23eb36R263

**Comment by wetneb** [comment]
Fixed by #2323
