### ISSUE TITLE
Issue creating Numeric Facets on restart after cells with numbers have been blanked out

### ISSUE THREAD

**Issue by sharun-s** [OpenRefine/OpenRefine#2285]
I created an Age column based on 2 date columns using the grel:diff function with unit years.
 
I was able to create both Text and Numeric facets on this new Age column. I am not sure what its Type was. Where dates were missing in either of the 2 date columns, the age column cells showed up as blank which was good. 

Made some fixes in some cells. certain dates/ages were wrong and I blanked out age in those cells. In this step I have to treat the value as text. If I try to blank out the cell changing type to Numeric I get an error. 

When I restarted server the next day, I was not able to create a numeric facet anymore on the Age column. It says "no numeric value present". 

I am guessing it has to do with the blanked out cells now set as Text type, So now each time I restart server, to use the numeric facet, I transform all cells in Age using toNumber. Which then doesn't allow me to edit and blank out cells with mistakes. This seems to have been reported before as #841  

I am using the linux-3.2-beta build.

**Comment by tfmorris** [comment]
Sorry no one ever replied to this, but my reading of your description is that things were working as intended. As mentioned in #841, which you referenced, numeric facets require numeric values to work with.
