### ISSUE TITLE
"Choose new match" then "search for match" discards old match, but doesn't add new one

### ISSUE THREAD

**Issue by Jheald** [OpenRefine/OpenRefine#2290]
(3,3 rc 1 / Windows 10 1809 / Chrome 79.0.3945.117)  After running reconciliation, if I "choose new match" then "search for match", put in a specific Q-number to search for, then select it, the old match is discarded but the new match isn't added, and the row goes into the "reconciliation = none" facet

**Comment by thadguidry** [comment]
Tested in 3.3 and works in Chrome and Firefox.
Tested in 3.4 (trunk) and works in Chrome and Firefox.
Closing as not reproducible.
