### ISSUE TITLE
Update GOVERNANCE.md to mention advisory and steering committees

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2292]
As part of the onboarding process to CS&S we have created advisory and steering committees.
The GOVERNANCE.md document in this repository should reflect that.

----- _I (Martin Magdinier) moved my comment from September 18 here to track progress_ ----- 

I started a draft on this commit: 73e8697eea0c488067284a81fb8266d2b7234210 and  6d9be0c - this is for discussion and review. 

## Sources 

I used the following discussion to update the governance: 
* [Inviting Mathieu Saby to the GitHub organization](https://groups.google.com/forum/#!msg/openrefine-dev/qZbO1-2Gdho/dRapCDyjBgAJ) for the difference between Guest and Organization Member
* Conflict of Interest PR #2294 
* CS&S Agreement 

## Need Feedback 

Need feedback from the community and CS&S on the document in general but most specifically on 

- [ ] Role of the release manager 
- [ ] Selection of the Advisory Committee

## To Do

- [x] Update Governance based on community feedback #3198
- [x] Polish Grammar / English of the governance document 
- [ ] Collect feedback from CS&S on the governance document
- [ ] Update of the Contributing document  - I plan to move how we reach consensus there 
- [ ] Make reference to Funding.yml #3154
- [ ] Clarify who is Github owner how they are added/removed.
- [ ] Update the GitHub permission and especially the team/contributors to reflect this document

**Comment by tfmorris** [comment]
@magdmartin @thadguidry This seems like something that either of you should be able to handle (at least drafting for review).

**Comment by thadguidry** [comment]
@magdmartin Martin has some of the drafting to do, and I was going to help and review.  I've been waiting for him to kickstart this effort as he agreed a few meetings ago :-)  But I can kickstart if he says "go for it".

**Comment by tfmorris** [comment]
It's been open since January and seems like something one of you could do to lighten the load on @wetneb.

**Comment by magdmartin** [comment]
This is on my to do list for too long. I am in vacation the first two weeks
of August. I'll try to give more attention to OpenRefine.

**Comment by thadguidry** [comment]
@magdmartin can you make the draft update by end of September?

**Comment by magdmartin** [comment]
I started a draft on this commit: 73e8697eea0c488067284a81fb8266d2b7234210 - this is for discussion and review. 

I incorporated suggestion for the Conflict of Interest PR #2294 

## Need Feedback 

Need feedback from the community and CS&S on the document in general but most specicly on 
* Role of the release manager 
* Selection of the Advisory Committee

## To Do:

* Polish Grammar / English
* Agreement 
* Update of the Contributing document 
* Make reference to Funding.yml #3154

**Comment by thadguidry** [comment]
@magdmartin Added my comments to into your draft commit: 73e8697

**Comment by wetneb** [comment]
Perhaps it's simpler to just do a pull request with these commits and comment on the PR itself? Feel free to mark it as draft if it is not quite ready yet.

**Comment by thadguidry** [comment]
@magdmartin Regarding your last bullet point, Why did we want to make a reference to Funding.yml?  What would it even say, or need to say?

**Comment by magdmartin** [comment]
The pull request for the contributing document is ready to be merged - see #3198
I move in this issue description the list of todo's

**Comment by wetneb** [comment]
Closed by #3198.

**Comment by magdmartin** [comment]
@wetneb  I suggest we keep this issue open as a master or epic ticket to track changes we need to do regarding the governance and guideline to contribute.

**Comment by trnstlntk** [comment]
I found this issue very accidentally, and it looks extremely stale (and also not super discoverable anymore, it has kind of sunk to the bottom of our very large backlog of issues)? Shall I create a new issue re: updating our governance documents based on the recently made decisions, and close this one? @magdmartin @wetneb

**Comment by wetneb** [comment]
Fine by me!

**Comment by magdmartin** [comment]
Yes, we can close this one and reopen new issues if necessary.
