### ISSUE TITLE
Investigate Dremel encoding as a potential successor for the records mode

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2298]
**The problem**

The records mode is suffers from the following deficiencies:
* Inefficient (scanning the table to delimit records takes time);
* Inaccurate, lossy (if I import a JSON file with many nested objects it is not straightforward to export it back with the same structure, #1897);
* Hard to understand for users.

See discussion on the mailing list: https://groups.google.com/forum/#!topic/openrefine/X9O8NBC1UKQ

**Possible alternative**

Transforming hierarchical data such as JSON objects to tabular formats is a fairly widespread problem. The [Dremel encoding](https://storage.googleapis.com/pub-tools-public-publication-data/pdf/36632.pdf) (used in Apache Drill) is an encoding that is designed for that, and which can be used with Parquet to store a set of hierarchical records in a columnar way. It is lossless, meaning that one can reconstruct the original records from the columnar data. However it is far from clear whether this can be integrated nicely in OpenRefine. One first hurdle is that the transformation is defined by a schema, and the files we typically import from (JSON, XML) do not generally come with a schema. Another big question mark is how this would be concretely represented in the UI, and whether it would be possible to switch between row and records mode at all, and so on.

**Comment by thadguidry** [comment]
After the import (or during) however, a schema could be constructed by the user after investigation, correct?

**Comment by wetneb** [comment]
Yes it's not clear to me what is happening in this case - they might not be using the same underlying encoding… I would need a longer dive in it.

**Comment by fpompermaier** [comment]
Dremel is the basis of Apache Parquet and Apache Arrow. The in-memory model
of Dremio (Value Vectors) represent the core of Apache Arrow [1].
And Dremio is basically a newer and boosted version of Apache Drill.

[1]  https://mapr.com/blog/apache-arrow-and-value-vectors/

Il Lun 20 Gen 2020, 17:45 Antonin Delpeuch <notifications@github.com> ha
scritto:

**Comment by wetneb** [comment]
Closing this in favour of this higher-level design discussion:
https://forum.openrefine.org/t/representing-hierarchical-data-beyond-the-records-mode/425
