### ISSUE TITLE
Drop the sample extension

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2300]
We have a `sample` extension which is meant to demonstrate the basic scaffolding to get a minimalistic extension to work.

This is not super useful since we already have quite a lot other extensions in the repository, which are actually maintained since they expose functionality that people use. There is a risk is that this extension does not get updated (because breaking it does not actually break anything for users).

Also, as an extension developer, I generally want to develop my extension in its own repository, with its own build system. The Maven set up for extensions included in this repository is not easy to translate to extensions developed outside the repository, since our own set up relies on the main OpenRefine classes being present in the reactor at build time.

Once #2254 is done, it should be easier to propose a clean Maven setup for external extensions. We could move the sample extension to a dedicated repository, which was created a long time ago but remained empty:
https://github.com/OpenRefine/refine-sample-extension

**Comment by darecoder1999** [comment]
@wetneb: Hi, I would like to work on this issue if it's not already taken. Thanks.

**Comment by wetneb** [comment]
Concerning rearranging the source into new modules and namespaces, I have done that in `4.x` and was thinking about keeping the 3.x release series with the current architecture. But I guess we could already publish the `main` module on Maven to make this issue easier. What do you think?

**Comment by darecoder1999** [comment]
Sounds good to me. It will be easier after the release is published to Maven central.

**Comment by darecoder1999** [comment]
@wetneb Are we still waiting for the release to start working on this?

**Comment by wetneb** [comment]
Unless you have ideas about how to do this without releasing to Maven, I would wait for this, yes.

**Comment by darecoder1999** [comment]
@wetneb: I suggest for a nightly release for this to proceed. Otherwise, I can release a snapshot that can be replaced later.

**Comment by wetneb** [comment]
Sure, go for it then :)

**Comment by wetneb** [comment]
Changing the title of this issue to reflect the opinion I voiced in https://github.com/OpenRefine/OpenRefine/issues/6426#issuecomment-1999565189

**Comment by wetneb** [comment]
I think it would still be useful to have a basic scaffold that people could use to start their own extensions, so I copied the sample extension to a dedicated repository here:
https://github.com/OpenRefine/sample-extension
