### ISSUE TITLE
Can't create project from big JSON file

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#231]
_Original author: julian.r...@gmail.com (November 17, 2010 15:47:46)_

<b>What steps will reproduce the problem?</b>
1. Launch Refine
2. In &quot;Create a New Project&quot; choose a big (29,4MB in my case) JSON file as data file.
3. Click &quot;Create Project&quot;

What is the expected output? 
A new project with imported data. It works fine with smaller data sets.
What do you see instead?
Nothing. The browser does nothing but seems busy. 

What version of the product are you using? 
Version 2.0 [r1836]

On what operating system?
OSX 10.6

<b>Please provide any additional information below.</b>
The structure of  the file is:

{&quot;total_rows&quot;:200885,&quot;offset&quot;:0,&quot;rows&quot;:[
{&quot;id&quot;:&quot;36ae432498bd38e7fe0d319b7902ffa4&quot;,&quot;key&quot;:[2010,9,15],&quot;value&quot;:{&quot;service&quot;:&quot;cs&quot;,&quot;segment&quot;:&quot;sms&quot;,&quot;app&quot;:&quot;fc&quot;,&quot;lang&quot;:&quot;en&quot;,&quot;device&quot;:&quot;ipad&quot;}},
/\* ... plus lot of rows */
{&quot;id&quot;:&quot;36ae432498bd38e7fe0d319b79030730&quot;,&quot;key&quot;:[2010,9,17],&quot;value&quot;:{&quot;service&quot;:&quot;cs&quot;,&quot;segment&quot;:&quot;phone&quot;,&quot;app&quot;:&quot;fc&quot;,&quot;lang&quot;:&quot;en&quot;,&quot;device&quot;:&quot;iphone4&quot;}}
]}

I've tried increasing the JVM memory as per your instructions. In that case it's worst because the whole system slows down.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=231_
##

**Comment by wetneb** [comment]
I propose to close this as non-reproducible as no test file was provided.

**Comment by thadguidry** [comment]
@wetneb yes close, and besides, this was Gridworks days at that time and some of the importers like CSV , XML, and JSON were upgraded afterwards.
