### ISSUE TITLE
Remove calls to deprecated methods from libraries

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#2312]
One note that I have thus far in trying to test the [spark-prototype](https://github.com/OpenRefine/OpenRefine/tree/spark-prototype) branch.

I saw warnings for commons-io (during compile for or-model)
```
[INFO] ----------------------< org.openrefine:or-model >-----------------------
[INFO] Building OpenRefine - model 3.3-SNAPSHOT                           [3/8]
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The artifact org.apache.commons:commons-io:jar:1.3.2 has been relocated to commons-io:commons-io:jar:1.3.2
```
and fixed by adding dependency explicitly so Maven didn't have to assume:
```
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>2.6</version>
    </dependency>
```
 But then I wondered why we are depending on commons-io for File IO handling, instead of newer java.nio.  Apache Commons IO also mentions many deprecation's along various releases: https://commons.apache.org/proper/commons-io/upgradeto2_6.html

I think we should improve the code to make use of **java.nio.xxx** more often instead of some of the older Apache IO libraries like commons-io, where it makes sense for the needs (file handling, multiple event channels).
* This will help with large file support (non-blocking, buffering, etc.) as well as easier compatibility with Linux/Mac/Windows file systems and warnings.
* In the past, David began to use java.nio in places for the reasons above.

Thoughts?

**Comment by wetneb** [comment]
Where exactly do you read that commons-io is deprecated?

**Comment by thadguidry** [comment]
Apache Commons IO is not deprecated, but some of its methods have been. Such as this one:
```
 The class org.apache.commons.io.FileSystemUtils has been deprecated.
                    Use equivalent methods in java.nio.file.FileStore instead, e.g.
                    Files.getFileStore(Paths.get("/home")).getUsableSpace() or iterate over
                    FileSystems.getDefault().getFileStores().
```
  In general, Java itself has risen up to have a lot of functionality built into it's core packages and javax extension packages over the last 7 years.  NIO and NIO2 representing improvements in Native File IO in particular.  Native file handling issues have been significantly addressed in Java's core NIO and NIO2 libraries over the years as well.  And those folks on the Apache Commons dev mailing list have said that [their best practices guide](https://commons.apache.org/proper/commons-io/bestpractices.html) needs to be updated to account for not only java.io but also java.nio and nio2, but many of those best practices guides already exist, most [on Oracle's sites like this](https://docs.oracle.com/javase/8/docs/technotes/guides/io/index.html)

Still it depends on what functionality is needed and why.
https://www.studytrails.com/java-io/io-vs-nio/

And different methods offer better performance, depending on use cases.
https://itsallbinary.com/reading-file-to-string-in-java-with-performance-io-nio-apache-commons-io-google-guava/

I'm just bringing up the issue that improvements can be made to using more of Java's core libraries and features and reduce dependencies where we can and when it makes sense, in this case with native file handling with increased performance, reduced GC, and large file support, as we venture into building better support for bigdata with Spark, etc.

This could be a GSOC effort, or other volunteer help with optimization later on.  I don't want to optimize now, what I am doing with this issue is bringing up the points about exploring more of what has been improved in Java over the years, so that others can explore this area and help to contribute.
(you can gladly rename the issue also and use whatever labeling makes sense)

**Comment by wetneb** [comment]
> Apache Commons IO is not deprecated, but some of its methods have been.

Sure, just like any other library then! :) In most IDEs, calls to these methods will be highlighted as deprecated, so they should gradually disappear as the code evolves.

If anyone wants to proactively clean up calls to deprecated methods from commons-io or any other library, that's of course very welcome! I don't think this would be a great GSoC project by itself but it could be picked up by anyone who wants to get familiar with the code base, including potential GSoC applicants.

**Comment by TejaswiKarasani** [comment]
@thadguidry and @wetneb I would like to give solve up the issue with both of your guidence

**Comment by wetneb** [comment]
Sure! Removing all calls to deprecated methods is a big task in general - and might not make sense or be desirable in many cases.

Perhaps you could look at deprecated calls from a specific library, to get a narrower focus. For instance, we use deprecated interfaces from the Apache POI library, which is used in the Excel importer and exporter. Perhaps you could have a look at that?  This requires a bit of investigation: understanding why these interfaces are deprecated, whether they have been removed in a new version of the library, whether it makes sense for us to migrate to this new version, and so on.

**Comment by TejaswiKarasani** [comment]
Ok @wetneb

**Comment by tfmorris** [comment]
This is too big to be actionable. We use dependabot to flag out of date dependencies and improve them. As @wetneb said, IDEs flag references to deprecated classes / methods and developers can make a judgement call as to whether the effort to update them is justified when they are working on a module.

As a general rule, I think just trolling through the code and rewriting it to use functionally equivalent, but more modern Java, is a waste of time. The code base is 10 years old so there's even stuff like Java 5 style iterators which are not yet used, but that code still works fine.

@TejaswiKarasani if you identify a subset to work on, like the suggested POI library, please create a specific issue for that.

@thadguidry if you have identified a specific I/O performance issue that you'd like to see fixed, please create an issue for that and we can investigate if NIO is the solution or something else.

**Comment by thadguidry** [comment]
@tfmorris there have been a few I/O issues, but actually they are now fixed in master over the last 3 months from my testing.  Some related to importing (where the interns and yourself have fixed now).  Another was transforming with large strings in cells within 100's of 1000's of records, and that's a bit better now from what I can see (Antonin is confident once we have Spark, most of that can be improved).

So, I agree on closing this issue, as dependabot is what we really needed here, and so thanks for addressing that.
