### ISSUE TITLE
spark-prototype:  loading large CSV file, takes forever, I gave up

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#2314]
**Describe the bug**
loading large CSV file's takes forever, and in fact, I just CTRL-C because it looked like it was submitting a Spark task for 1 row at a time ?  That's literally what it felt and looked like in the console 
logs:

 [openrefine_console_log.txt](https://github.com/OpenRefine/OpenRefine/files/4205548/openrefine_console_log.txt)

**To Reproduce**
1. modify the `SparkConf()` line in `RefineServlet.java` to instead `.setMaster("local[4]")` to use 4 cores if you have. I have 6
2. refine build
3. Start refine with  `refine /m 8000m`
4. Load a large CSV file (346734 rows X 8 columns) **by copy/pasting into clipboard.**
5. Click on Create Project
6. Watch loading progress and memory bar that stays at `1468/8000` for over 2 mins (weird!)
7. Watch logs that show a task submit every 1 sec
8. Give up because you will be here till 5 years from now.

**Current Results**
gave up after not seeing progress

**Expected behavior**
should have loaded project rows into project grid after a few mins at most. (on OpenRefine 3.3 on my system with 8G allocated it takes only 1 min to load the data in.)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: OpenJDK 11

**OpenRefine (please complete the following information):**
 - Version: spark-prototype

**Screenshots**
Spark detail for 1 of the jobs  (all of them being the same, and after 4 mins of waiting for CSV to load during Create Project, I had about 300 completed Stages... prior to giving up
![image](https://user-images.githubusercontent.com/986438/74551820-87d6cf00-4f19-11ea-8ef5-416e564ba823.png)

**Datasets**
Tested with this public dataset [Border_Crossing_Entry_Data.csv.zip](https://github.com/OpenRefine/OpenRefine/files/4205527/Border_Crossing_Entry_Data.csv.zip)

**Additional context**
Something not being parallelized , when it should be perhaps ?

**Comment by wetneb** [comment]
I just tried this CSV in the 4.0 branch and it now loads just fine (it's not that big, 346,733 rows). @thadguidry can I leave it to you to close it?

**Comment by thadguidry** [comment]
great, yeah, let's close this issue based on Spark not an intended need for me any longer.
