### ISSUE TITLE
Reconciliation against LCNAF takes too long; no indication of status

### ISSUE THREAD

**Issue by dezel002** [OpenRefine/OpenRefine#2315]
**Describe the bug**
I am trying to reconcile a list of 390 names against the Library of Congress Name Authority File and it keeps freezing on me at the point of selectin the LC reconciliation service

**To Reproduce**
1. Open project
2. Click on down arrow for desired column
3. Select "Reconcile"-->"Start Reconciling
4. Choose LC Reconciliation Service

**Current Results**
Pop-up "Working" appears, runs indefinitely, nothing ever happens

**Expected behavior**
The ability to choose options within the reconcile window, and click on "Start Reconciling"

**Screenshots**

![image](https://user-images.githubusercontent.com/26574684/74685653-c75d1f80-5194-11ea-99e2-d272056c1afe.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version:  Chrome 79 
 

**OpenRefine (please complete the following information):**
 - Version 3.2

**Datasets**
If you are allowed and are OK with making your data public, it would be awesome if you can include or attach the data causing the issue or a URL pointing to where the data is.
If you are concerned about keeping your data private, ping us on our [mailing list](https://groups.google.com/forum/#!forum/openrefine)

**Additional context**

**Comment by wetneb** [comment]
Hi @dezel002, thanks for this report!

Can you let us know how you added the LCNAF reconciliation service? Did you use "Add Standard Service" perhaps? Which endpoint URL did you put there?

You might also want to look at the server logs (the white text on black background) and check if you can see any errors there (while the UI is freezed).

**Comment by dezel002** [comment]
I found my problem. I forgot to start Python. It's been awhile since I've done this, and I forgot about that step. Now it's working as expected. Sorry about that!
