### ISSUE TITLE
[WD recon] "search for match" should handle more Qnn formats

### ISSUE THREAD

**Issue by VladimirAlexiev** [OpenRefine/OpenRefine#2317]
In WD recon, "search for match" handles WD id's like "Q41370" nicely.

However, it should also handle other formats:
- https://www.wikidata.org/wiki/Special:EntityPage/Q41370 (copied from WP)
- https://www.wikidata.org/wiki/Q41370 (copied from WD)
- https://www.wikidata.org/entity/Q41370 (semantic URL)
- https://tools.wmflabs.org/reasonator/?q=Q41370&lang=en (copied from Reasonator)
- https://tools.wmflabs.org/reasonator/?q=41370&lang=en (another Reasonator, notice that `Q` is missing)
- http vs https

Cheers!

**Comment by wetneb** [comment]
Makes sense! Moving this issue to https://github.com/wetneb/openrefine-wikibase/issues/75 as this is the code base that is responsible for that.
