### ISSUE TITLE
Only first reference is exported for QuickStatements

### ISSUE THREAD

**Issue by LibrErli** [OpenRefine/OpenRefine#2320]
**Describe the bug**
If your are adding multiple references to a statement, the QuickStatements export only contains the first reference. 

**To Reproduce**
1. Add two or more references to new statement in the Wikidata schema
2. Click on 'Export to QuickStatements'
3. View your QS-Export 
4. See that only the first Reference is exported.

**Expected behavior**
To handle multiple references in QuickStatements, the whole statement has to be duplicated just with the different reference. QuickStatements prevents to add a duplicate statement but is able to add a second or further reference to the pointing statement.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Version: Firefox
 - JRE or JDK Version:. openjdk 11.0.6 

**OpenRefine (please complete the following information):**
 - Version 3.3

**Datasets**
https://gitlab.com/LibrErli1/museen_burgenland/-/blob/master/museen_bgld.openrefine.tar.gz

**Comment by afkbrb** [comment]
@wetneb Can you please assign this issue to me? This issue should be a great chance for me to learn about OR and the wikidata-extension

**Comment by wetneb** [comment]
Sure, go ahead!
