### ISSUE TITLE
Extension Development - Modifying Code Coverage

### ISSUE THREAD

**Issue by petertran-21** [OpenRefine/OpenRefine#2322]
I am in a team developing an additional SNAC extension to OpenRefine and am currently tinkering with the code coverage through coveralls as it was previously set up on the base OpenRefine project. I am running into trouble excluding certain files from being counted and I was wondering if you would have any insight on that as I've been trying for a while now with little success. I'm messing with the `pom.xml`, `jacoco`, and `<excludes>` tag of the base project as well as the one for the extension but no luck. [Here is a link to the project if it helps](url)

**Comment by wetneb** [comment]
Actually for some reason our code coverage isn't currently being submitted to Coveralls - I should investigate why!

Also, the link to the project is invalid.

**Comment by petertran-21** [comment]
Oh apologies, [let's try that again](https://github.com/snac-cooperative/OpenRefine/tree/capstone-master).

**Comment by petertran-21** [comment]
Got it! I needed to move the `<excludes>` tag out a level.
