### ISSUE TITLE
Possible race condition after applying edit in Facet

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#234]
_Original author: thadguidry (November 17, 2010 18:09:19)_

<b>What steps will reproduce the problem?</b>
1. Apply an edit in a Facet
2. During which time a possible Save project condition is pending or happening.
3. Facet tries to update/refresh after applying update and then freezes.  Facet window may even disappear if you force a Refresh on the browser trying to get anything to respond.

<b>What is the expected output? What do you see instead?</b>

Frozen browser window with WORKING... or Facet window left in unusable unclickable state.

Screenshot and command line trace attached.  Last instances of command line trace is a refresh on the browser after the frozen facet state.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=234_

**Comment by thadguidry** [comment]
No longer need this fixed. Closing.
