### ISSUE TITLE
Remove freebase functions that are no longer needed

### ISSUE THREAD

**Issue by darecoder1999** [OpenRefine/OpenRefine#2345]
Freebase cleanup, remove the use of exportTrippleLoader if only used for freebase. Refer to this : https://github.com/OpenRefine/OpenRefine/pull/2341#issuecomment-592533219 by @thadguidry

**Comment by darecoder1999** [comment]
I'm working on it. :smile:

**Comment by thadguidry** [comment]
@darecoder1999 If you know this, since I've always been curious... Do any browser dev tools let you search for "unused JS functions" or is that reserved for only IDE's like I've seen ?

**Comment by darecoder1999** [comment]
@thadguidry I feel this can be done using the Coverage tab in Chrome DevTools.
