### ISSUE TITLE
Removing items that are already uploaded to Wikidata

### ISSUE THREAD

**Issue by adithyak04** [OpenRefine/OpenRefine#2353]
Consider the case where I have a total of 100 row items among which only 50 are reconciled. I have uploaded those 50 items to Wikidata. Now, inroder to remove those items from OpenRefine, I would like to know what can be done. Note: Removing needs to be done only from OpenRefine and not from Wikidata.

**Comment by wetneb** [comment]
You could (for instance) isolate these rows with a reconciliation judgment facet, and then remove these matching rows (in the menu for all columns, above the row indices).

Could you use [our mailing list](https://groups.google.com/forum/#!forum/openrefine) or StackOverflow for questions which are not about bugs or possible improvements?

**Comment by adithyak04** [comment]
Irrelevant topic
