### ISSUE TITLE
Export doesn't work when using Internet Explorer

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#236]
_Original author: aidan.wa...@gmail.com (November 17, 2010 22:52:53)_

<b>What steps will reproduce the problem?</b>
1. Trying to export to excel, etc.

<b>What is the expected output? What do you see instead?</b>

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; GIS IE 6.0 Build 20080321; .NET CLR 2.0.50727; .NET CLR 1.1.4322; MS-RTC LM 8; InfoPath.2; GIS IE 6.0 Build 20080321)
Timestamp: Wed, 17 Nov 2010 22:49:17 UTC

Message: Invalid argument.
Line: 4469
Char: 5
Code: 0
URI: http://127.0.0.1:3333/project-bundle.js

Message: Invalid argument.
Line: 4448
Char: 5
Code: 0
URI: http://127.0.0.1:3333/project-bundle.js

Message: Invalid argument.
Line: 4448
Char: 5
Code: 0
URI: http://127.0.0.1:3333/project-bundle.js

Message: Invalid argument.
Line: 4448
Char: 5
Code: 0
URI: http://127.0.0.1:3333/project-bundle.js

Message: Invalid argument.
Line: 4448
Char: 5
Code: 0
URI: http://127.0.0.1:3333/project-bundle.js

Message: Invalid argument.
Line: 4448
Char: 5
Code: 0
URI: http://127.0.0.1:3333/project-bundle.js

<b>What version of the product are you using? On what operating system?</b>
2.0

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=236_
##

**Comment by thadguidry** [comment]
Tested with newest Internet Explorer Edge on Windows 10.  Export Excel XLS and Excel XLSX works with a new tab opening up and OpenRefine tab blinking and highlighting that there is activity to see.  Clicked on OpenRefine tab and saw the download prompt at the bottom of browser window.

However I did confirm that there is another subtle issue with Apache POI error that seems to come up sometimes #1185 when trying to export an XLSX file.
