### ISSUE TITLE
Issue with the result of Url fetching based on Column

### ISSUE THREAD

**Issue by jinoytommanjaly** [OpenRefine/OpenRefine#2364]
**Describe the bug**
I have a problem with Url fetching based on Column on a particular website. 

**To Reproduce**
Steps to reproduce the behaviour:
1. A Column have several numbers listed. Example of a value - 18004
2. Go to Edit Column>Add Column by fetching Url
3. Expression Given: 
Tried both a) "https://schoolwiki.in/api.php?action=parse&page="+value+"&format=xml"
and b) 'https://schoolwiki.in/'+value
4. Throttle delay tried both 50 and 5000 milliseconds.
5. Clicked on Ok.
6. If the 'On error' is opted for 'set to blank' it will give null result and if opted for 'store error' it shows the error listed at 'Current Results'.

**Current Results**
The error code stored in the result is as below:
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Expected behavior**
Expected a result with the codes as shown in the Screenshot

**Screenshots**
Expected result
![image](https://user-images.githubusercontent.com/38123141/76147934-5f309800-60c7-11ea-930a-d73d731f0be7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version: Chrome Version 80.0.3987.132 and Brave Version 1.4.96 Chromium: 80.0.3987.132

**OpenRefine:**
 - Version OpenRefine 3.3

**Comment by wetneb** [comment]
Here is an explanation of this issue:
https://github.com/OpenRefine/OpenRefine/wiki/Troubleshooting:-Fetching-data-from-URLs#sunsecurityvalidatorvalidatorexception-pkix-path-building-failed

Leaving this issue open - how could we make it easier to add more certificates in OpenRefine?

**Comment by ostephens** [comment]
@wetneb would you be OK if we close this issue and have one specifically about making it easier to add/manage certificates?

**Comment by wetneb** [comment]
@ostephens of course!

**Comment by ostephens** [comment]
Have opened #2379 - please feel free to jump in and comment or amend my wording/title of the issue

**Comment by jinoytommanjaly** [comment]
Hi,

I was using jre environment in my computer. So the explanation not worked on my system. I found the solution from here. https://www.ibm.com/support/knowledgecenter/SS9RXT_10.1.0/com.ibm.swg.ba.cognos.tm1_inst.10.1.0.doc/t_tm1_inst_addcertificatetokeystoreopsconsole.html

**Comment by ostephens** [comment]
@jinoytommanjaly glad you got this resolved. The explanation you link to looks to me to be the same as the ones we link to from the wiki - using keytools to update cacerts. If this wasn't clear to you, then perhaps you can suggest (or even better directly make) a change to the wiki to make the explanation clearer?

**Comment by jinoytommanjaly** [comment]
@ostephens Ya. it's almost same, but seems to be little complex steps.

I was getting the error when i tried as:
'keytool' is not recognized as an internal or external command, operable program or batch file.

Since keytool is located in sub directory, i need to change the path of my drive or change environment settings in my PC. But got different errors while running cmd.

But from the above settings it just take 1 step to install the certificate. So it seems to me more easier for me.

Thank you for helping me out to figure the problem with trusted certificates.

**Comment by ostephens** [comment]
OK - thanks and no problem

Owen
