### ISSUE TITLE
Import project without file attachment

### ISSUE THREAD

**Issue by AghaSaad04** [OpenRefine/OpenRefine#2369]
**Describe the bug**
Try to import the project without a file attachment and the error will be shown.
**To Reproduce**
1. Go to 'Import project'
2. Click on the 'import project button' without a file attachment.
3. See error

If you attach a wrong file/file format and try to proceed you will see the same error.

**Current Results**
![image](https://user-images.githubusercontent.com/36513474/76165711-f6a2f300-617a-11ea-81b0-2323dcf6b456.png)

**Expected behavior**

There should be an alert and I should not be allowed to proceed without a file attachment
Similar to this :
![image](https://user-images.githubusercontent.com/36513474/76165787-ad06d800-617b-11ea-9f0c-bf03a95acfc0.png)

**Desktop (please complete the following information):**
 - OS: [Linux, Ubuntu 18.04]
 - Browser Version: [Chrome Version 80.0.3987.132 (Official Build) (64-bit)]
 - JRE or JDK Version:[openjdk version "11.0.6" ]

**OpenRefine (please complete the following information):**
 - Version [OpenRefine Version 3.4-SNAPSHOT ]

**Comment by thadguidry** [comment]
@AghaSaad04 Looking forward to your fix on this! :-)  You can do it!

**Comment by AghaSaad04** [comment]
Sure @thadguidry, I will look into this

**Comment by chetan-v** [comment]
I want to do that

**Comment by thadguidry** [comment]
@chetan-v Great Chetan!  Let us know if you need help.

**Comment by chetan-v** [comment]
> @chetan-v Great Chetan! Let us know if you need help.

Yeah sure,if I need

**Comment by chetan-v** [comment]
Please give me some guidance @thadguidry @tfmorris

**Comment by chetan-v** [comment]
Please give some hint I read alot about this.
I tried but I failed to redirect

**Comment by wetneb** [comment]
What is the specific problem you need help about? How are you planning to solve this problem and where exactly are you stuck?

**Comment by chetan-v** [comment]
Actually I just want to give a alert message when we do not choose any file and click import project button

**Comment by wetneb** [comment]
Great! These are the steps you will need to follow to solve this issue:
https://github.com/OpenRefine/OpenRefine/wiki/Your-first-pull-request
At which of these stages are you stuck?

**Comment by chetan-v** [comment]
I am unable to find the root file in which I should change.
In (create project menu) has their JS file that check the condition and give alert
but in JS file of (import project menu)  not have that condition to check and give alert.

I am confused about the type of Changes in Java or in JavaScript

**Comment by wetneb** [comment]
This will be solved in the frontend, so Javascript. You are on the right track: imitating in the import project menu the check that is done in the create project menu sounds like a great approach! Can you give me a link to these two Javascript files?

**Comment by chetan-v** [comment]
In this file they check and give message 

https://github.com/OpenRefine/OpenRefine/blob/306b541c699e7e87d5e08be1310575b85b15dbf0/main/webapp/modules/core/scripts/index/default-importing-sources/sources.js#L60


(main/webapp/modules/core/scripts/index/import-project-ui.js) I think they do their work perfectly

they only give data on screen they both are different to each other which is not a problem in (import project menu) all work is done by its backend. (ImportProjectCommand.java) 
they contains 
(doPost):-

https://github.com/OpenRefine/OpenRefine/blob/306b541c699e7e87d5e08be1310575b85b15dbf0/main/src/com/google/refine/commands/project/ImportProjectCommand.java#L64
 
function that give information or whatever to  (respondWithErrorPage)  and they dont contain the certain condition. I think the condition should be their.
 
(respondWithErrorPage):-

https://github.com/OpenRefine/OpenRefine/blob/306b541c699e7e87d5e08be1310575b85b15dbf0/main/src/com/google/refine/commands/HttpUtilities.java#L146

**Comment by wetneb** [comment]
Checking for the presence of a file and alerting the user must be done before sending anything to the backend, so you should ignore all Java files for this issue. You are right that the check you should imitate is at
https://github.com/OpenRefine/OpenRefine/blob/306b541c699e7e87d5e08be1310575b85b15dbf0/main/webapp/modules/core/scripts/index/default-importing-sources/sources.js#L60-L62

How about just doing something similar in the JS file for the "import project" pane?

**Comment by wetneb** [comment]
Closed by #2369.
