### ISSUE TITLE
List Facets dialogue box is editable

### ISSUE THREAD

**Issue by kushthedude** [OpenRefine/OpenRefine#2374]
**Describe the bug**

List Facets dialogue box is editable, which should not be.

**To Reproduce**
1. Go to `Customised Facets`
2. Click on `Word Facet`
3. List all choices 

**Current Results**

You can edit the dialogue and remove or add anything which should not be applicable as it is listing the facets.

**Screenshots**

<img height="400" width="498" alt="Screenshot 2020-03-09 at 4 04 34 AM" src="https://user-images.githubusercontent.com/44091822/76172385-37226100-61bb-11ea-9b8e-a1f0985612c1.png">
<img height="400" width="529" alt="Screenshot 2020-03-09 at 4 04 39 AM" src="https://user-images.githubusercontent.com/44091822/76172387-3984bb00-61bb-11ea-93bd-9dad68bd59ce.png">

**Comment by kushthedude** [comment]
cc: @thadguidry @wetneb

**Comment by thadguidry** [comment]
@kushthedude Historical context:  This was originally allowed by design.  User's sometimes wanted to quickly rename something and then do CTRL-A to select everything in the box and CTRL-C to copy the info so that they could paste it CTRL-V into another program.

Given that context, do you see a problem currently with this historical use case now?  You said "see error" but you didn't explain or show what the error is.

**Comment by kushthedude** [comment]
I don't see the context of renaming and editing in here. As after editing none of the changes are applied to the actual list of facets.


> You said "see error" but you didn't explain or show what the error is.

I mentioned in the bug description that the text box should is editable where it should be not. It may just allow to list all available word filter facets for users to see the options ?

**Comment by kushthedude** [comment]
> User's sometimes wanted to quickly rename something

@thadguidry What advantage would renaming give to the users when the words available are already defined in the datasets?
 It actually didn't seem logical to me as if the user is listing out and seeing the avaialble list of words which he can use to apply the filter why would he want to rename any of them, I may be wrong but if there is any use-case or an advantage of editable list, I will close the issue and it's relevant PR.

**Comment by thadguidry** [comment]
@kushthedude It was not intended to CHANGE facets, but instead to allow users to EXPORT or as David said in the commit "Copy off" the data contained within facets...via copy/paste.  You can see the [git blame's and issues](https://github.com/OpenRefine/OpenRefine/blame/10c046698a9586662668e31086bdd2d3c6aad801/main/webapp/modules/core/scripts/facets/list-facet.js) from the git history.  Specifically, https://github.com/OpenRefine/OpenRefine/commit/066fed7f3db00e7c0d84174aa26bde59dfd40a37

**Comment by kushthedude** [comment]
> @kushthedude It was not intended to CHANGE facets, but instead to allow users to EXPORT or as David said in the commit "Copy off" the data contained within facets...via copy/paste. You can see the [git blame's and issues](https://github.com/OpenRefine/OpenRefine/blame/10c046698a9586662668e31086bdd2d3c6aad801/main/webapp/modules/core/scripts/facets/list-facet.js) from the git history. Specifically, [066fed7](https://github.com/OpenRefine/OpenRefine/commit/066fed7f3db00e7c0d84174aa26bde59dfd40a37)

Yes, that's what I am saying over here. As seen from the commit the list feature was introduced to let users copy the list of choices and there count from the total available. But there is no need to make that list editable since this is a list and it should be read-only from which user can select and copy/paste the data he needs. Also making the list box editable may result into some human errors like typing of extra keywords or removal of any letter by accidental key presses which may result in wrong copy/paste.

**Comment by thadguidry** [comment]
@kushthedude Sure, just giving you the context... a few users wanted to edit in the box quickly and then copy.  Changing this mean they will just be allowed to copy and can make edits in another program.  I'm actually fine with not allowing edits in OpenRefine here and letting them edit in their own Notepad.

**Comment by kushthedude** [comment]
> @kushthedude Sure, just giving you the context... a few users wanted to edit in the box quickly and then copy. Changing this means they will just be allowed to copy and can make edits in another program. (we might upset those very few users) I'm actually fine with not allowing edits in OpenRefine here and letting them edit in their own Notepad.

I understand your use-case now. Now as we are again in the dilemma of making the textbox read-only or editable. Let's wait for another opinion from @wetneb, if the editable textbox is more beneficial then I will close the issue and it's relevant PR :).


> We could also change the title and put a smaller subtitle under it that explains more "This dialog allows you to copy the facet values (use ctrl-c) to paste into other programs"

Yeah, this will clear the use-case of the dialogue to users.

**Comment by kushthedude** [comment]
> One of the reasons I personally like Vue.js is that our whole dialog system could be much more guided with Help and Hints. Vue.js makes this easier than other frameworks from what I've seen. Anyways...I digress.

I will start working today on introducing the Vue.js to a part of our web-app as discussed in gitter and let's see how it goes 😅
