### ISSUE TITLE
URL validator absent in the Get Data from URL input

### ISSUE THREAD

**Issue by kushthedude** [OpenRefine/OpenRefine#2376]
**Describe the bug**

URL validator absent in the Get Data from URL input

**To Reproduce**
1. Go to 'Index page'
2. Click on 'import from web url'
3. Enter any random string eg:dnweferfe
4. Click on next and see the server tries to fetch the data from the wrong address

**Expected behavior**

There should be a URL Field validator which may restrain the user from entering random strings.
**Screenshots**

<img width="1220" alt="Screenshot 2020-03-09 at 5 14 06 AM" src="https://user-images.githubusercontent.com/44091822/76173374-119a5500-61c5-11ea-9b4c-c74688a57a53.png">

**Additional context**

cc: @thadguidry @wetneb If this is a valid enhancement .

**Comment by thadguidry** [comment]
wait, what?!?!  I thought for sure this was validated...someone mentioned it before and if memory serves, it was improved to check validation. (or I'm thinking of @jackyq2015 's work else perhaps)

**Comment by thadguidry** [comment]
Hmm, nope, not this one: #297 , I dunno... I'm losing my mind I guess.
Hmm... https://github.com/OpenRefine/OpenRefine/blob/9f7d5b878628c40d68a445b751fd50140d922e7d/main/webapp/modules/core/scripts/util/url.js

I dunno... it was somewhere.

**Comment by thadguidry** [comment]
Doh!  It was an Exporter, from @wetneb , not the importer.
https://github.com/OpenRefine/OpenRefine/blob/14dd4c01125b15df8fda9651c49ce19b5f32bf75/main/src/com/google/refine/exporters/CustomizableTabularExporterUtilities.java

**Comment by kushthedude** [comment]
> wait, what?!?! I thought for sure this was validated...someone mentioned it before and if memory serves, it was improved to check validation. (or I'm thinking of @jackyq2015 's work else perhaps)

URL is not validated and the transition to downloading page happens. There should be a URL Validator for textbox which may restrain the user from proceeding to the next page and show message `Please enter a valid URL`.

Currently, when I enter wrong URL and click on next, this is the behaviour : 
<img width="845" alt="Screenshot 2020-03-09 at 5 38 55 AM" src="https://user-images.githubusercontent.com/44091822/76173774-51167080-61c8-11ea-9493-1afb2b40e602.png">

**Comment by kushthedude** [comment]
> Doh! It was an Exporter, from @wetneb , not the importer.
> https://github.com/OpenRefine/OpenRefine/blob/14dd4c01125b15df8fda9651c49ce19b5f32bf75/main/src/com/google/refine/exporters/CustomizableTabularExporterUtilities.java

So I may start working on it then 😄

**Comment by thadguidry** [comment]
@kushthedude yes please.  And my memory will eventually fail completely... I.E. code comment the crap out of stuff so its easier to find when we are searching the repo :-)
