### ISSUE TITLE
Configurable OAuth credentials for gdata extension

### ISSUE THREAD

**Issue by afkbrb** [OpenRefine/OpenRefine#2383]
Currently, if we (as developers) want to use the gdata extension to import Google Stylesheet, we will need to obtain a client_id/client_secret pair first. [Here](https://github.com/OpenRefine/OpenRefine/wiki/Google-Extension) we have a wiki on how to do it. 

Then, we must put the client_id/client_secret into [GoogleAPIExtension](https://github.com/OpenRefine/OpenRefine/blob/master/extensions/gdata/src/com/google/refine/extension/gdata/GoogleAPIExtension.java), and recompile it, which is inconvenient. It's more convenient if we **make it configurable to add the client_id/client_secret pair**.

With @wetneb and @ostephens , we had a discussion about this under #2380 .

One option is to add corresponding client_key/client_secret configuration items into `refine.ini` and write some scripts to add them as JVM options. So that we can retrieve the pair by `System.getProperty`.

Probably there are better options, looking forward to your suggestions.

**Comment by afkbrb** [comment]
We can change the following code in [GoogleAPIExtension](https://github.com/OpenRefine/OpenRefine/blob/master/extensions/gdata/src/com/google/refine/extension/gdata/GoogleAPIExtension.java) :

```java
private static final String CLIENT_ID = "";
private static final String CLIENT_SECRET = ""; 
```

to:

```java
private static final String CLIENT_ID = System.getProperty("ext.gdata.clientid", "");
private static final String CLIENT_SECRET = System.getProperty("ext.gdata.clientsecret", "");
```

The second param of `System.getProperty` is the default value, which is returned when the corresponding value of the key is null.

This mechanism can be very helpful.

We can "hard code" a default client_id/client_secret pair into the two default params for release version. This way, the user won't need to acquire a client_id/client_key pair himself/herself. (But this is not a good practice. In principle, an OAuth consumer host should acquire a client_id/client_key by itself.)

If OpenRefine is started up with JVM options like: 
```
-Dext.gdata.clientid=new_client_id -Dext.gdata.clientsecret=new_client_secret
```
the default client_id/client_secret will be overridden. This way, we can use our own OAuth credentials. 

The JVM option above can be simply added to `JAVA_OPTIONS` in `refine.ini`. A better option is adding `GDATA_CLIENT_ID` and `GDATA_CLIENT_SECRET` configuration items to `refine.ini`, and adding corresponding scripts in `refine.bat` and `refine` to transform the two items to JVM options. After that, if we want to use our own OAuth credentials, we just need to set `GDATA_CLIENT_ID` and `GDATA_CLIENT_SECRET`.

**Comment by wetneb** [comment]
Sounds good to me!
