### ISSUE TITLE
ER: Ability to merge columns

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#239]
_Original author: paulschreiber (November 18, 2010 23:17:10)_

Please add the ability to merge columns. I imagine you can do this with a formula, but it's tricky, especially with nulls. It would be nice if you could select multiple columns and concatenate their values into a new column.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=239_
##

**Comment by ostephens** [comment]
Think this is a duplicate of #68 ?

**Comment by thadguidry** [comment]
Yeap this is a duplicate.
Closing this one since #68 describes the need very well and discusses options.

**Comment by wetneb** [comment]
@ostephens @thadguidry thanks for your work on cleaning up these old issues!
