### ISSUE TITLE
'Updating Preview' gets stuck in an infinite loop on clicking any config option in XML

### ISSUE THREAD

**Issue by lisa761** [OpenRefine/OpenRefine#2402]
**Describe the bug**
The 'Update Preview' gets stuck in an infinite loop if the user does not select a record element first before clicking on any configuration option when working with XML datasets.

**To Reproduce**
1. Go to Create Project
2. Open any XML dataset (e.g. https://www.govinfo.gov/bulkdata/FR/2020/03/FR-2020-03-09.xml)
3. Click any configuration option (e.g. Load at Most checkbox)

**Current Results**
Update Preview gets stuck and there is an error in console `Index 0 out of bounds for length 0`

**Expected behavior**
There should be a message that tells the user to first select an element

**Screenshots**
<img width="674" alt="2020-03-12" src="https://user-images.githubusercontent.com/52909743/76525418-cec0d180-6491-11ea-87ca-25c8ed1b9bd4.png">

**Comment by thadguidry** [comment]
#1715 is related
