### ISSUE TITLE
The Trim trailing and leading whitespace option for json/xml files does not work

### ISSUE THREAD

**Issue by lisa761** [OpenRefine/OpenRefine#2409]
**Describe the bug**
When you create a new json project which has trailing whitespace in some elements, clicking the checkbox to eliminate them does not actually work.

**To Reproduce**
1. Create a json project that has leading/trailing whitespace in some elements
2. Click on `Trim leading & trailing whitespace from strings` checkbox

**Current Results**
Nothing happens, the whitespace remains.

**Expected behavior**
The whitespace should be removed when the checkbox is clicked

**Screenshots**
<img width="960" alt="2020-03-14 (2)" src="https://user-images.githubusercontent.com/52909743/76658053-3f9ee100-6599-11ea-9dc9-8efde602a9b2.png">
As seen here, there is leading whitespace in the first row, column name, body and email
<img width="960" alt="2020-03-14 (3)" src="https://user-images.githubusercontent.com/52909743/76658055-40d00e00-6599-11ea-9283-04171decb502.png">
`Trim leading & trailing whitespace from strings` checkbox is clicked but still the whitespace remains.

**Desktop:**
 - OS: Windows 10
 - Browser Version: Google Chrome Version 80.0.3987.132
 - openjdk version "11.0.6"

**OpenRefine:**
 - Version OpenRefine 3.3

**Comment by thadguidry** [comment]
Historically, importer options (well, most of them) are supposed to perform those options upon **Create Project**, and some of them also work during **Update Preview**.

However, my personal preference has always been that the Update Preview should apply all the options a user selects onto those **preview rows** (limited to 100 by our code) and then apply to **all rows** once the user clicks **Create Project**.

A case could be made where **Update Preview** is necessary to click on or not.
On some importers, I can see some options are nice to have immediate feedback on and others its better to wait until the user clicks **Update Preview**.

It probably needs much more investigation into my thoughts above. :-)  And maybe looking at old commit subject lines to make sure my history recollection is correct.  Things certainly have changed over the last 10 years. :-)

**Comment by thadguidry** [comment]
This seems to have also helped to resolve #1095 ?
I just tested it against that issue and it seems perfect.  But perhaps a bit of auto detection of seeing those leading & trailing whitespaces in the imported file and automatically checking the new option for `Trim leading & trailing whitespace from strings` could be an improvement to close out #1095 ?
