### ISSUE TITLE
Uploading to Wikidata part is not working

### ISSUE THREAD

**Issue by BodhisattwaMandal** [OpenRefine/OpenRefine#2416]
**Uploading to Wikidata is not working**

**To Reproduce**
1. Click on 'Upload Edits to Wikidata'
2. Add 'Edit Summary'
3. 'Upload editss'
4. See 'Perform Wikibase edits
0% complete' 

**Current Results**
Instead of uploading (i.e. Perform Wikibase edits, 0% to 100% complete), the message suddenly disappears without uploading anything.

**Expected behavior**
Uploading to Wikidata should have happened.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04]
 - Browser Version: Firefox 72.0.1
 - JRE or JDK Version: 1.8.0_201

**OpenRefine (please complete the following information):**
 - Version [e.g. openrefine-3.3-SNAPSHOT]

**Datasets**

[corona-India.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/4337307/corona-India.openrefine.tar.gz)

**Additional context**

**Comment by BodhisattwaMandal** [comment]
It is uploaded now, somehow. So closing for now

**Comment by wetneb** [comment]
Might be linked to Wikidata's performance issues. We should do a better job at reporting these failures.
