### ISSUE TITLE
17 million row (68m cells) file requires more than 8G of heap to import

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#242]
_Original author: leebel...@gmail.com (November 20, 2010 03:59:57)_

<b>What steps will reproduce the problem?</b>
1. Windows 7 x64 with 8GB of physical memory
2. Large csv file (733mb)
3. In google-refine.l4j.ini, set
# max memory memory heap size

-Xmx4096M
1. Save 
2. Double click Google-refine.exe
3. Immediate error: 

Invalid maximum heap size: -Xmx4096M
1. if I set Xmx1550M (~the maximum I seem to be able to use), after about 5 minutes of importing the csv file, I get an out of stack memory error.
2. The system reports that prior to running Refine, 2gb is in use.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=242_

**Comment by thadguidry** [comment]
Closing as this is a known use case of folks needing to work with larger and larger project files.  We have plans to eventually help with this in OpenRefine 4.0+ See #1469
