### ISSUE TITLE
Importing an XML file from a URL does not auto detect the correct importer

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#2420]
**Describe the bug**
XML importer is not selected by default

**To Reproduce**
1. **Create Project** and get data from Web Addresses (URLs)
2. Paste the following URL: 
 `http://api.worldbank.org/countries/all/indicators/SP.POP.TOTL?date=2000:2001`
3. Click **NEXT**
4. Notice that **Line-based text files** is the importer detected instead of **XML files**

**Current Results**
The Line-based importer is selected

**Expected behavior**
XML importer should be automatically selected for preview.  XML files are typically detected based on file extension such as `.xml`, but retrieving a file from a URL will sometimes need to resort to additional methods such as the following:

1. the response header `Content-Type` could be `application/xml` or `text/xml`
```http
HTTP/1.1 200 OK
Date: Mon, 16 Mar 2020 16:53:17 GMT
Content-Type: text/xml; charset=UTF-8
Content-Length: 13184
Connection: keep-alive
Set-Cookie: TS019266c8=017189f9470f813515282caf2315619d07a80cfb8e6a6cf9f09b164f0c7b7c86cca54015e18e7d6df654b2231545f75eee48d6eb6d; Path=/
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: deny
``` 

2. the first line of a file contains:
 ```xml
<?xml version=
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Version: Firefox
 - JRE or JDK Version: JDK8

**OpenRefine (please complete the following information):**
 - Version: OpenRefine (master) trunk

**Comment by buntamas** [comment]
Hi ! I would like to solve this. Can I work on this issue?

**Comment by thadguidry** [comment]
Sure @buntamas , let us know if you need assistance.  We'd also expect to see some tests added as well.

**Comment by james-cui** [comment]
@thadguidry here is my pull request on the issue https://github.com/OpenRefine/OpenRefine/pull/2494
Can you review it?
