### ISSUE TITLE
Column created using "Create column based on this column" doesn't update on original column change

### ISSUE THREAD

**Issue by WilliamDiakite** [OpenRefine/OpenRefine#2425]
**Describe the bug**

When creating a column based on an other column, values of the created column don't update when changes are made to the original column. 

**To Reproduce**

1. Start reconciling a column using ULAN (Getty) vocabulary. We consider the column to reconcile is called "name"
2. Click the arrow left to "name" and click Edit Column > Add column based on this column
3. The new column is called "judgement" and is computed as such (in Python) : 
`return cell.recon.judgement`. Click "OK"
4. The column "judgement" is created and showing the reconciliation status of every record ("matched", "new" or "none")
5. When reconciling a record with a candidate (or creating new item), the "judgement" value for this perticular record is not updating.

**Current Results**

When performing a match or creating a new item, the "judgement" value for this perticular record is not updating. 

**Expected behavior**

A column created using the "Create column based on this column" functionality should update every time the column it is based on changes.
ie For an unmatched record, the associated value in the "judgement" column is "none". This value should turn to "matched" when reconciliation is performed or to "new" when "create new item" is clicked

**Screenshots**

Let's consider this : after reconciling a few items, I create the "judgement" column using the steps described above.  In my example, since the first two items have been dealt with (no match so I create new item for both of them), "judgment" is indicating "new" for them. Because the third and last item is still untunched at this point, judgement is showing "none". So, at this point everything's ok.

<img width="389" alt="Screenshot 2020-03-17 at 11 36 11" src="https://user-images.githubusercontent.com/16724487/76850904-9da52000-6848-11ea-9bed-cdd948b5dd6c.png">

As I am dealing with the third and last record, nothing changes is the "judgement" column. The value should change from "none" to "new" but isnt'.

<img width="387" alt="Screenshot 2020-03-17 at 11 36 31" src="https://user-images.githubusercontent.com/16724487/76851288-50757e00-6849-11ea-8763-3d92b4c79deb.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser Version: Firefox 74.0 (64 bits)
 - JRE or JDK Version: 
java version "13.0.2" 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)

**OpenRefine (please complete the following information):**
 - Version: OpenRefine 3.3 [58b839b]

**Datasets**

**Additional context**

This task is performed in order to differenciate the different reconciliation status of my records. ("matched" if record is matched with a candidate, "new" if a new record had to be created, "none" if the record has not been dealt with already)
I believe this is a bug because when the expression used to compute a new column is based on the value of the original column, the newly column updates correctly. Here, the expression is based on the cell which might not trigger anything on state change.

**Comment by wetneb** [comment]
Hi William,

That is indeed how OpenRefine works - and it is by design, not by accident :) Cell values are fixed, they are not formulae as they can be in Excel for instance.

However it is possible to use formulae in facets, and the contents of these facets will be updated as you change the underlying values.

Feel free to discuss possible alternatives for your own workflows on our mailing list:
https://groups.google.com/forum/#!forum/openrefine
