### ISSUE TITLE
Adding description to Wikidata reconciliation schema halts the process

### ISSUE THREAD

**Issue by susannaanas** [OpenRefine/OpenRefine#2426]
**Describe the bug**
When I add and save a description in the termbox in the reconciliation interface, the Wikidata import becomes unavailable.

**To Reproduce**
1. Go to 'Wikidata > Edit Wikidata Schema'
2. Click on 'Add term'
3. Select 'Description'
4. The Issues and Preview sections become empty

Playing around with the values, it accepts one field but not the other as value. They are both of type text, both produced by retrieving values from Wikidata with 'Add columns from reconciled values' and then extended with 'Edit cell > Transform...'

**Screenshots**

Normal behavior
<img width="1141" alt="Näyttökuva 2020-3-17 kello 15 33 18" src="https://user-images.githubusercontent.com/4725416/76862633-0d2a0800-6867-11ea-8030-2c9f3fb760cf.png">
<img width="1139" alt="Näyttökuva 2020-3-17 kello 15 34 00" src="https://user-images.githubusercontent.com/4725416/76862623-0bf8db00-6867-11ea-86e5-fa5962329b9d.png">
<img width="1140" alt="Näyttökuva 2020-3-17 kello 15 34 14" src="https://user-images.githubusercontent.com/4725416/76862619-0b604480-6867-11ea-9de1-1eb4fdac4b42.png">

Problem behavior
<img width="1140" alt="Näyttökuva 2020-3-17 kello 15 33 33" src="https://user-images.githubusercontent.com/4725416/76862627-0c917180-6867-11ea-8d93-eb550c65f335.png">
<img width="1137" alt="Näyttökuva 2020-3-17 kello 15 33 42" src="https://user-images.githubusercontent.com/4725416/76862626-0c917180-6867-11ea-8bc3-defcc8f7bb7e.png">
<img width="1140" alt="Näyttökuva 2020-3-17 kello 15 35 01" src="https://user-images.githubusercontent.com/4725416/76862609-08655400-6867-11ea-91c5-8ddf3f78d3e3.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser Version: Chrome 80.0.3987.132
 - JRE or JDK Version: Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)

**OpenRefine (please complete the following information):**
 - Version 3.3 [58b839b] (Also with beta)

**Datasets**
Happens with several datasets

**Comment by susannaanas** [comment]
I did 'Edit cells > Common transforms > To text' on the problem field, and it changed two values after which this column worked.

**Comment by wetneb** [comment]
Could it be that issues and preview are not available simply because you haven't filled the language and value field for the description? At least I would not expect anything to work in this current state:
![image](https://user-images.githubusercontent.com/309908/76864535-1f9d4500-6859-11ea-968e-3f6187bf45ed.png)

Should we simply add messages in the preview / issues tabs to warn the user about the schema being incomplete?

**Comment by susannaanas** [comment]
I found out that it would not accept null values. I only suspect they are null.

**Comment by susannaanas** [comment]
<img width="286" alt="Näyttökuva 2020-3-17 kello 16 21 48" src="https://user-images.githubusercontent.com/4725416/76865463-6e53da80-686b-11ea-87ca-16b5f6699966.png">

**Comment by wetneb** [comment]
> I suspect the reconcilation process does not accept null values.

It should ignore all null cells but that should not prevent it from generating unrelated edits. I just tried adding a description from a column with null cells and that worked fine. With an empty string too.

> It works now after I transformed the columns to text.

Curious, I am not sure what could be the cause then - creating descriptions from numbers seems to work too…

**Comment by susannaanas** [comment]
This dataset was created by copying and pasting data from an Excel spreadsheet opened in Google Sheets on Mac.

**Comment by susannaanas** [comment]
I repeated the workflow with a French title and this did not happen.

**Comment by susannaanas** [comment]
Thanks again for a very quick response!

**Comment by wetneb** [comment]
Well, I hope we will somehow find the root cause of this issue! Next time it happens, you could perhaps look for errors in your browser's console, and perhaps check the server logs too:
https://github.com/OpenRefine/OpenRefine/wiki/Installation-Instructions#obtaining-server-logs-on-mac

**Comment by antoine2711** [comment]
> I did 'Edit cells > Common transforms > To text' on the problem field, and it changed two values after which this column worked. There are two empty fields in the column so they are likely the ones.
> 
> I repeated this with another column and it worked out in a similar way. So perhaps this is a bug report, but I can now manage my data.

Hi @susannaanas, I just want to say that I did experience the same thing as you. It was strange. And it happened more than once. Doing something like « toString() », or « To text » or « To null » in « Edit cells -> Common transforms » fixed the problem. 

It's weird. Regards, Antoine

**Comment by jinoytommanjaly** [comment]
Hi too facing the save problem with saving the scheme... Could not save the scheme if any terms is just selected.

**Comment by wetneb** [comment]
Agreed, the new error reporting there should make it clearer what the problem is. Happy to have another issue about counting validation issues in the tab header as you suggest.
