### ISSUE TITLE
Remove or replace the calls made to freebase.com

### ISSUE THREAD

**Issue by darecoder** [OpenRefine/OpenRefine#2435]
Context: Freebase reconciliation services have been shut down now. So, there's a need to clean up the code which is redirecting the call to freebase.com which will eventually cause an error 404. Code including freebase.com in it should be removed or replaced accordingly without disturbing any other functionality.

Such code can be found: https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/importers/ExcelImporter.java
https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/importers/OdsImporter.java

and many other places may be.

**Comment by thadguidry** [comment]
Here's a query of those files including "freebase.com".
https://github.com/OpenRefine/OpenRefine/search?q=%22freebase.com%22&unscoped_q=%22freebase.com%22

**Comment by thadguidry** [comment]
Only 5 more files to cleanup on this!
https://github.com/OpenRefine/OpenRefine/search?q=%22freebase.com%22&unscoped_q=%22freebase.com%22
