### ISSUE TITLE
Page reloads when creating project from URL and press ENTER

### ISSUE THREAD

**Issue by darecoder1999** [OpenRefine/OpenRefine#2437]
**Describe the bug**
When I try to create a project by adding URL from `Web Addresses (URLs)` option and press ENTER, the page reloads and switches back to `This computer` choose file option.

**To Reproduce**
1. Go to `Web Addresses (URLs)`
2. Add a valid URL to create a project
3. Press ENTER
4. See the response

**Current Results**
Page reloads and switches to `This computer` choose file option

**Expected behavior**
Either it should create the project from that URL or doesn't show any unexpected behavior like this.

**Screenshots**
![issue](https://user-images.githubusercontent.com/42637982/77048806-0af1b600-69ed-11ea-81e8-8425e6ab11b0.gif)

**Comment by AghaSaad04** [comment]
I am not able to reproduce this.

OS: Ubuntu 18.04
Browser: Chrome
Open Refine version: Version 3.4-SNAPSHOT

**Comment by darecoder1999** [comment]
@AghaSaad04 I feel you didn't press ENTER after entering the URL. you might have clicked on Next button.

**Comment by AghaSaad04** [comment]
@darecoder1999 oh yeah my mistake. Thanks for the quick response :)
