### ISSUE TITLE
Broken Link in documentation 

### ISSUE THREAD

**Issue by zengchu2** [OpenRefine/OpenRefine#2448]
**Describe the bug**
Link page not found.
**To Reproduce**
1. Go to 'https://github.com/OpenRefine/OpenRefine/wiki/Write-An-Extension'
2. Click on 'example'  under **Directory Layout**
3. See error

**Expected behavior**
Go to a 'Page not found page'
**Screenshots**
![image](https://user-images.githubusercontent.com/32441682/77210903-eb3bba00-6ae0-11ea-9d94-fc143c3c1e6a.png)

**Comment by antoine2711** [comment]
> **Describe the bug**
> Link page not found.
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to 'https://github.com/OpenRefine/OpenRefine/wiki/Write-An-Extension'
> 2. Click on 'example'  under **Directory Layout**
> 3. See error

Check-it, it should be fixed. A.

**Comment by antoine2711** [comment]
@wetneb : but there is still 2 other bad links at the bottom of the page, and I'm not sure where to point them.

**Comment by wetneb** [comment]
Ouch this documentation is massively outdated, let me fix that quickly.
