### ISSUE TITLE
Add Gitpod configuration

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2449]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
Setting up an IDE to work on OpenRefine can take a bit of time. Web-based IDEs are becoming popular and they make it easy to offer a pre-configured environment for prospective developers.

**Describe the solution you'd like**
[Gitpod.io](https://gitpod.io/) is one of them, and we could embed default configuration files for it.
We would mention the integration in the documentation, [alongside our current explanations about how to set up Eclipse](https://github.com/OpenRefine/OpenRefine/wiki/Building-OpenRefine-From-Source).

**Describe alternatives you've considered**
There are other web-based IDEs available (such as Eclipse Che), we could also look into providing configuration for them.

**Additional context**
@antoine2711 is interested in this and opened #2447 for that.

**Comment by thadguidry** [comment]
I am currently working on the Eclipse Che integration now.  Almost have most of this done (Maven, Java, GitHub Pull Requests, with Build/Run commands, & a custom Welcome page) within a single `devfile.yaml` that you can run locally or in Eclipse SaaS cloud (free with 1 workspace, but you have to accept the RedHat terms, but that's essentially the same with Gitpod also)  I'll put this on my fork so we can try it out first and see any problems.

So I think we should at a minimum provide both the `devfile.yaml` for Eclipse Che, as well as Gitpod (which is free up to 50 hours/month for open source projects).

**Comment by kushthedude** [comment]
@wetneb Does it still needed when github is rolling out codespaces?

**Comment by wetneb** [comment]
Personally I have never needed that - I would wait to see what codespaces are, it's probably a bit early to tell.

**Comment by thadguidry** [comment]
This is now fixed thanks to the amazing talents of GitHub engineering team.

Hit . dot while looking at the OpenRefine GitHub repo.  Bam!  Instant VSCode IDE!

Closing this.
