### ISSUE TITLE
Columns named « toString » are displayed as collapsed

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#2451]
**Describe the bug**
Using the name « toString » for a column creates a column with no name and not popup arrow. You must use « Re-order / remove columns... » to clean that up…

**To Reproduce**
1. Go to 'Add column based on this column...'
2. Enter the text for the column name to « toString »
3. See the error in the table view.

**Current Results**
Unusable column.

**Expected behavior**
Seeing a normal column named « toString »

**Screenshots**
Command:
![image](https://user-images.githubusercontent.com/12217525/77234992-b3884d00-6b88-11ea-97ad-c79a225aa5e3.png)

Result (see the column after column « ValDiv »:
![image](https://user-images.githubusercontent.com/12217525/77235005-ca2ea400-6b88-11ea-8acc-fa564eee263f.png)

**OpenRefine (please complete the following information):**
 - Version 3.3

**Comment by antoine2711** [comment]
@wetneb Hi Antonin, I created this issue, but I still can't apply labels, unlike you said. 

Regards, Antoine

**Comment by wetneb** [comment]
That's my fault, I did not add you to the relevant team. It should be fixed now.

**Comment by james-cui** [comment]
@wetneb and @antoine2711 , can I work on this issue?

**Comment by antoine2711** [comment]
> @wetneb and @antoine2711 , can I work on this issue?

Sure James, be my guest. Don't hesitate if you have questions.

Regards, Antoine

**Comment by james-cui** [comment]
@antoine2711  here is the pull request https://github.com/OpenRefine/OpenRefine/pull/2531

**Comment by james-cui** [comment]
@antoine2711  @wetneb   just updated the pull request

**Comment by wetneb** [comment]
Thanks @antoine2711 for discovering and reporting this!
