### ISSUE TITLE
Have separate menu items for « Export to file… » and « Export to Google Drive… »

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#2453]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
Now, if you want to export your project (to file), you go in the menu, and you have to answer a dialog where you choose either « to file » or « to Google Drive ».

Also, using the term « Export to local » is vague, « Export to file » (or even « Export to OpenRefine ZIP » would be better tho the latter is a bit too verbose… ;-)

**Describe the solution you'd like**
It would be much better if there where 2 items in the menu, named « Export to file… » and « Export to Google Drive… ». It would save clicks for exporting to file, which is the operation most of our user do, and it would be clearer in the interface that OpenRefine can export the whole project to Google Drive. 

**Describe alternatives you've considered**
Doing the same as now. But if we want to add interface elements for Export to gDrive, it will clutter the interface.

**Additional context**
![image](https://user-images.githubusercontent.com/12217525/77237738-02da7780-6ba1-11ea-9d52-a14bf1e077fc.png)

**Comment by AghaSaad04** [comment]
@wetneb I was thinking of solving this issue :)

**Comment by wetneb** [comment]
It's true that export to Google services are not very well exposed at the moment. We could add menu items for:
* Export to Google Sheets
* Export to Google Drive

But "Export project to file" is too vague: most of the other export options can also be seen as exporting the project to some file. How about "Export as OpenRefine project" or "Export as OpenRefine archive"?

**Comment by antoine2711** [comment]
« Export as OpenRefine archive » is good because its an internal archive
(ZIP).

Le dim. 22 mars 2020 à 06:59, Antonin Delpeuch <notifications@github.com> a
écrit :

**Comment by antoine2711** [comment]
Thinking about it, 
« OpenRefine archive to file… »
« OpenRefine archive to Google Drive… »
might be better?

And then, we could also have:
« Google Sheet… »

Just to conform with how it's written elsewhere in the menu. It's the Export menu. Maybe every item could be preceded  by « As » or « To », like « To Excel (.xls) ».

And, to continue the uniformisation, « Export to QuickStatement « would be « To QuickStatement » and « Export Wikidata schema » become « Wikidata schema to file »?

And « Custom tabular exporter… » would be something like « Thru custom tabular exporter… »?

@wetneb what do you think of that?

**Comment by antoine2711** [comment]
Another clarification…
![image](https://user-images.githubusercontent.com/12217525/77249893-a320b280-6c1a-11ea-89d1-a5434ab91fff.png)
@ostephens @thadguidry @wetneb

**Comment by wetneb** [comment]
Definitely not "Thru", that is informal, and they do not add anything.
I would remove all the "To", they are unnecessary too.

**Comment by antoine2711** [comment]
![image](https://user-images.githubusercontent.com/12217525/77250063-b08a6c80-6c1b-11ea-9ca0-b0701d15b753.png)
?

**Comment by AghaSaad04** [comment]
> Definitely not "Thru", that is informal, and they do not add anything.
> I would remove all the "To", they are unnecessary too.

@wetneb  what about **"..."** after each export option? Should we add them or remove them from all options?

**Comment by wetneb** [comment]
Good point, I think "..." should only be added to exporters which require further configuration (in some dialog or prompt). That's the convention, I think.

Also, the "..." should be included in the message itself (so they can be translated too), not concatenated afterwards.

**Comment by wetneb** [comment]
And of course changing messages has a cost (it invalidates them for translators), so we should do it as sparingly as possible.

**Comment by antoine2711** [comment]
They should stay as they indicate that a dialog/manual interaction is
coming before the real action.

Regards, A.

Le dim. 22 mars 2020 à 09:21, Agha Saad Fraz <notifications@github.com> a
écrit :

**Comment by wetneb** [comment]
> They should stay as they indicate that a dialog/manual interaction is
> coming before the real action.

In your screenshot, you added them to exporters which do not use any dialogs.

**Comment by antoine2711** [comment]
> > They should stay as they indicate that a dialog/manual interaction is
> > coming before the real action.
> 
> In your screenshot, you added them to exporters which do not use any dialogs.

Hi Antonin,
   If you choose a menu, and after that you still have a user interaction, then, I requires an ellipsis.

  That why I put an ellipsis to most (if not all) of the items.

   Also, spreadsheet file is not redundant: the spreadsheet can be saved to the cloud or elsewhere. But in my proposition, the menu item is precise, it tells you when you will generate files.

Regards, Antoine
