### ISSUE TITLE
Menus in an alternate language sometimes are too small

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#2454]
**Describe the bug**
If you choose a different language than english for OR, sometimes the menu's length is not good.

**To Reproduce**
1. Go to the « All Rows » menu.
2. See error

**Current Results**
Text overflows out of the menu.

**Expected behavior**
The menu should adapt and be bigger.

**Screenshots**
![image](https://user-images.githubusercontent.com/12217525/77241855-8ced0500-6bce-11ea-9984-a22b739699a0.png)

**Desktop (please complete the following information):**
- MacOS X.14, Chrome latest

**OpenRefine (please complete the following information):**
 - Version 3.3

**Comment by AghaSaad04** [comment]
Hi @antoine2711, @wetneb, How about this? Is this a good solution for the above problem? 

![image](https://user-images.githubusercontent.com/36513474/77246177-75516300-6c46-11ea-8186-e6b57327eae2.png)

**Comment by wetneb** [comment]
That would be pretty great I would say. I guess the alternative would be to let the menu become wider to accommodate for the longer text? I don't have strong feelings about either.

**Comment by antoine2711** [comment]
> Hi @antoine2711, @wetneb, How about this? Is this a good solution for the above problem?
> 
> ![image](https://user-images.githubusercontent.com/36513474/77246177-75516300-6c46-11ea-8186-e6b57327eae2.png)

> Item's text will be divided into multiple lines.

I'm buying that perfectly. This solution will accommodate VERY long translation, and, who knows when it might be needed.

I find this a working quick fix for a small cosmetic problem.

Bravo. @wetneb, should he do a PR?

**Comment by wetneb** [comment]
Sure, if someone strongly prefers enlarging the menus, they should be able to change that later anyway.

**Comment by magdmartin** [comment]
We discussed something similar in #974
