### ISSUE TITLE
In « Upload edits to Wikidata », pressing [RETURN] just make the dialog disapear

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#2459]
**Describe the bug**
When you are in the « Upload edits to Wikidata » dialog, if you press [RETURN], it never does what it should.
But, mainly, if you type text in the « Edit summary » text field, and then press [RETURN], it will just make the window go away, nothing more.

**To Reproduce**
1. Have a valid WD schema, at least one selected row with a reconciled item. Make sure that something is going to be edited.
2. Click on the menu item « Upload edits to Wikidata » in the Wikidata extension menu.
3. Type some text in the « Edit summary » text field. While the cursor is still in the text box, press [RETURN]
4. See error, nothing happens.

**Current Results**
Nothing happens

**Expected behavior**
The edits of Wikidata operation should go on.

**Screenshots**
![Upload edits to WD fails if return key #2 (OR)](https://user-images.githubusercontent.com/12217525/77268879-aef19080-6c7d-11ea-9829-c8076a350b5c.gif)

**Desktop (please complete the following information):**
 - MacOS X.14
 - Chrome latest

**OpenRefine (please complete the following information):**
 - Version 3.3

**Comment by antoine2711** [comment]
Please note that the [ESCAPE] key should also be taken care of properly, which is not the case right now.

**Comment by wetneb** [comment]
The escape key should already work in the master branch (not 3.3) since this was added for all dialogs.

**Comment by antoine2711** [comment]
> The escape key should already work in the master branch (not 3.3) since this was added for all dialogs.

Yes, you are right. It’s working for [ESCAPE].
