### ISSUE TITLE
Improvements to our nightly releases

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2462]
I have fixed the GitHub Actions workflow to publish snapshots of our master branch to [this repo](https://github.com/OpenRefine/OpenRefine-nightly-releases/releases) (the releases are currently empty but the next commit on master will trigger the upload of a release there).

Things to improve:

- [x] Add JRE in the Mac build, it is currently missing
- [x] Delete old releases after some time? Otherwise this is likely to become quite crowded.
- [x] We could potentially try to switch the build environment to Mac so that we can compress the Mac `.dmg` with `hdiutil`. Some commands (such as `apt-get install`) would need to be adapted.
- [ ] Use authentication header rather than get parameter for the API key to create releases

The release process is documented here:
https://github.com/OpenRefine/OpenRefine/wiki/Releasing-Version

**Comment by thadguidry** [comment]
Instead of time based, I would use the Maven convention of keeping X number of SNAPSHOT's and perhaps only the last 3.

**Comment by thadguidry** [comment]
Hmm, seems it did run and work...sorta kinda...but not fully.

When I expand the hierarchy for this here:
https://github.com/OpenRefine/OpenRefine/runs/781393861?check_suite_focus=true
it shows this:
```
Delete older releases
9s
    GITHUB_TOKEN: ***
Run dev-drprasad/delete-older-releases@v0.1.0
  with:
    repo: OpenRefine/OpenRefine-nightly-releases
    keep_latest: 10
  env:
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.252/x64
    JAVA_HOME_8.0.252_x64: /opt/hostedtoolcache/jdk/8.0.252/x64
    OR_VERSION: 3.4-beta-139-gae58bc0
    API_RELEASE: https://uploads.github.com/repos/OpenRefine/OpenRefine-nightly-releases/releases/27651323/assets{?name,label}
    GITHUB_TOKEN: ***
💬  found total of 30 active releases
🍻  found 20 older release(s)
👍🏼  20 older release(s) deleted successfully!
```

Ah, I bet he needs to change his code!  Digging in...
I read here:  https://help.github.com/en/enterprise/2.16/user/github/administering-a-repository/editing-and-deleting-releases#deleting-a-release
that 
> Tip: You must delete all binary files attached to a release before you can delete the release.


Ah, files are considered "assets"?  hmm.
https://developer.github.com/v3/repos/releases/#list-release-assets

So maybe the GitHub Action author needs to add another parameter.  "deleteAssetsForRelease" or something like that?

**Comment by wetneb** [comment]
I think it should just delete at most 20 releases with the current setup, we will see what happens when we push more commits.

**Comment by thadguidry** [comment]
@wetneb no, it's not fully deleting the release assets.  So the tags remain with attached assets (files).  See: https://github.com/OpenRefine/OpenRefine-nightly-releases/releases?after=3.4-beta-109-g4e9d365
So I've opened an issue above to have Prasad add another parameter to delete assets along with each release.

**Comment by wetneb** [comment]
Great! Hopefully we should just need to update the version number in our config file when this is fixed on their side.

**Comment by tfmorris** [comment]
I've updated the issue to be a checklist, but would it be better to have separate issues for each of the items?

**Comment by wetneb** [comment]
Fine with me either way.

**Comment by wetneb** [comment]
All the tasks in this issue are solved now that we migrated to using the Maven Central Snapshot Repository instead of automatically generated Github releases to publish our snapshots.
