### ISSUE TITLE
feature request: data has column shifts in some rows

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#247]
_Original author: PhilaDe...@gmail.com (November 22, 2010 19:08:15)_

<b>What steps will reproduce the problem?</b>
1. Open a space-delimited file of names with some one-part names (such as &quot;SMITH&quot;) and some two-part names (such as &quot;DI GREGORIO&quot;) in Google Refine
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
Well, this isn't a bug report, it's a feature request -- I see &quot;SMITH&quot; and &quot;DI&quot; in my last_names column, and in the DI GREGORIO record all columns to the right are shifted. I'd like to be able to combine columns in selective batches, and also move column entries in selective batches.

<b>What version of the product are you using? On what operating system?</b>
Google Refine version 2.0, on Windows XP Pro.

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=247_

**Comment by thadguidry** [comment]
Not enough detail. Closing.
