### ISSUE TITLE
Adding refine.ini to git-ignore

### ISSUE THREAD

**Issue by kushthedude** [OpenRefine/OpenRefine#2480]
I am proposing to add refine.ini to git-ignore as after setting up Gdata credentials the file will always show as a change to be committed.

**Comment by wetneb** [comment]
Adding `refine.ini` to `.gitignore` still shows the file as to be committed on my system, since `refine.ini` is still tracked. Does it change something for you, perhaps using a different Git client?

**Comment by kushthedude** [comment]
> Adding `refine.ini` to `.gitignore` still shows the file as to be committed on my system, since `refine.ini` is still tracked. Does it change something for you, perhaps using a different Git client?

Yes, It does show in the git-cli but doesn't show git-sublime client weird. Any idea you have ?

**Comment by wetneb** [comment]
Well, if it improves your own workflow, I don't see a reason not to add it to .gitignore, it does not deteriorate the experience on CLI either…

**Comment by kushthedude** [comment]
@wetneb What about moving the secret key and client id to environment variables and then using from there ?
Most of the project use `.env` to store keys and confidential stuff. 
I can PR to have the same.

**Comment by wetneb** [comment]
I am not sure what is the conceptual difference between an `.ini` file and an `.env` file - both separate the configuration from the code. I don't think replacing the ini file by something in another format would change much.

We could have a template of `.ini` file, which would be copied by the `./refine(.bat)` scripts to `refine.ini` if that file does not exist yet, and that would not be tracked. But then we are making it a bit harder to run OpenRefine from an IDE without ever using CLI.

**Comment by afkbrb** [comment]
I think we can have a `refine-dev.ini` and change `refine` / `refine.bat`. So if there are both `refine-dev.ini` and `refine.ini`, `refine` / `refine.bat` will use `refine-dev.ini` and ignore `refine.ini`. The `refine-dev.ini` should be added to `.gitignore`, so that it will not be tracked.

This way, `refine.ini` can still be used by default and tracked. Developers can copy it and rename it to `refine-dev.ini` to override it.

**Comment by wetneb** [comment]
Note that the Linux distribution of OpenRefine uses the `./refine` script itself, so the `./refine` needs to look at `refine.ini` at least in that case.

**Comment by afkbrb** [comment]
@wetneb Sorry I don't get what you mean. I mean both `refine.bat` and `./refine` will still look at `refine.ini` if `refine-dev.ini` doesn't exist. Will there be some issues for the Linux distribution?

**Comment by wetneb** [comment]
Sure, that works then!

**Comment by kushthedude** [comment]
This sounds nice to me too!
