### ISSUE TITLE
While creating wikidata schema I-beam pointer appears for drag and drop

### ISSUE THREAD

**Issue by darecoder1999** [OpenRefine/OpenRefine#2484]
**Describe the bug**

On hovering over the items to be selected and drag & drop for creating wikidata schema, I-beam pointers appears over there which is not appropriate if it is having a feature of drag & drop. 

**To Reproduce**
1. Open any project in OpenRefine
2.  Go to 'Extensions : Wikidata' 
3. Scroll down to 'Edit wikidata schema'
4. Then click on 'Add item' 
5. Move on to any item shown above to drag and drop that item & observe the cursor.

**Current Results**

I-beam cursor is appearing over the item.

**Expected behavior**

Grabbing cursor or any other apt cursor should appear.

**Screenshots/ GIF**
![issue-cursor](https://user-images.githubusercontent.com/42637982/77748251-0c069100-7046-11ea-967e-7e80a0e42d01.gif)
![cursor](https://user-images.githubusercontent.com/42637982/77748546-8df6ba00-7046-11ea-8942-ae042a9e570a.jpeg)

**OpenRefine (please complete the following information):**
 - Version [e.g. OpenRefine 3.0 Beta]

**Comment by wetneb** [comment]
Absolutely!

**Comment by thadguidry** [comment]
Either a Cross , or a Grab Hand.  Whatever is currently the norm for most applications.
