### ISSUE TITLE
Enhance cross() with empty "project name" calling parameter to represent the current project and empty column name to represent the index

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#2504]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
The `cross()` function can get data from an external project, but also from the current project (kind of a self-join). In order to minimize the text to write (and read), if the project name parameter could be set to an empty string, it would help or visibility, and for reusability, has the SAME transformation formula can be used in 2 different projects that share some data structure (or on the same project that would have changed name since).

Also, in order to be able to do a cross with the index of the row, I would let empty value for the column name. In that case, the value (first parameter of `cross()`) should be of type number.

**Describe the solution you'd like**
if `cross()` is called with an empty project name, then it should mean that the current project is the one to use. Ex.: `cross(1, "", "ID")[0]`.
if `cross()` is called with an empty column name, then the cross should be done not with a column, but with the internal index of the row, in a numerical match.

**Describe alternatives you've considered**
Writing the full column name, like now. Creating a column in the related project with the index as the value of each row.

**Comment by antoine2711** [comment]
Hi @wetneb, @thadguidry, @ostephens, @tfmorris, @magdmartin, dear lead developers, mentors, and/or long time contributors, I respectfully ask your attention regarding this issue.

Since the major enhancement of cross() 2 weeks ago, that made `cross()` 1) not only available when creating a new column, but also when transforming an existing column, but 2) also when creating the new column not only from the index column but from any column in the table, here are new propositions that could have, I believe, a great impact on the usefulness of the `cross()` function.

@afkbrb, once again, coded in a short period of time a PR that seams to cover the new angles of this issue. There as not been a lot a test, so that would still have to be done. Before that, since no one commented on this issue, I think it is now time to have the opinion of the community on this proposition, as to make it go forward, change it, or just drop it.

In short, this issue will provide 2 enhancements to the `cross()` function.
1. the 2nd parameter, projectName, can now be empty (""), in order to reference the current project. With this, you can copy/paste a calculation from one project to another, and, with commun field structure, the function would work without any changes. It also makes it easier to use self-cross in a project, and a saved calculation will continue to work even if you change your project name.
2. In the 3rd parameter, columnName, can be put to an empty string ("") to access the internal index value of the referenced project. So, without building any reference column in an external project (or the current project in itself), you can still access its rows data with the `cross()` function.

I think those both changes would be great enhancements. But, of course, it's up to the community to choose. In any case, we seams to be in a capacity to deliver these changes pretty soon, if the go is given.

Regards, Antoine

**Comment by antoine2711** [comment]
Oh, I forgot, this is worth mentioning (from @afkbrb in PR #2518):
> One interesting thing is that we already have an embedded "rowIndex" variable for GREL, so we can use `cross(rowIndex + offset)` to access a row relative to the current row.

So `cross(rowIndex + 1)[0]` gets you next row and `cross(rowIndex - 1)[0]` gets you your previous row… kind a bit like the old `R[-1]C[0]` notation… ;-)
 
A.

**Comment by thadguidry** [comment]
What if we also just got smarter with inspecting the argument values themselves?

GIVEN Only 1 argument
WHEN argument represents a valid column name in current project
THEN  perform the cross against valid column name in current project

Instead of this unneeded verbosity...

![image](https://user-images.githubusercontent.com/986438/79640080-40f19980-8155-11ea-80d1-78008cbe3bd5.png)

We make it easier with simpler syntax because we know a few things already from argument inspection (where `cell` and `project` are not specified)

![image](https://user-images.githubusercontent.com/986438/79639960-8366a680-8154-11ea-9a98-19302792db89.png)

**Comment by gitonthescene** [comment]
> Oh, I forgot, this is worth mentioning (from @afkbrb in PR #2518):
> 
> > One interesting thing is that we already have an embedded "rowIndex" variable for GREL, so we can use `cross(rowIndex + offset)` to access a row relative to the current row.
> 
> So `cross(rowIndex + 1)[0]` gets you next row and `cross(rowIndex - 1)[0]` gets you your previous row… kind a bit like the old `R[-1]C[0]` notation… ;-)
> 
> A.

This is terrific!  It’s probably worth updating some of the [recipes](https://github.com/OpenRefine/OpenRefine/wiki/Recipes#finding-previous-row) when this is available.
