### ISSUE TITLE
« Split into several columns » should have the option to fill the columns created in a reverse order

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#2505]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
Let's say you use the « Split into several columns » function, and that [1, 2, 3] would be filled in in the first, second and third column created, with 1 in the first, end 3 in the last. 

**Describe the solution you'd like**
But, with this option, 3 would go in the first column, and 1 in the last.

**Describe alternatives you've considered**
Reverse the data IN the column first, then do the column split. (Sometimes this will not be doable or easy.)

**Comment by wetneb** [comment]
Let's not mark this as a good first issue until we have reviewed it - just to make sure new contributors don't get the bad surprise of us disagreeing about the feature after having spent time on a PR.

**Comment by antoine2711** [comment]
It does seams to be wanted/needed, so I will just close this issue I opened.

Regards, 
   Antoine
