### ISSUE TITLE
Transform multiple columns at once

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#251]
_Original author: conley...@gmail.com (November 24, 2010 23:12:49)_

My apologies if this is already possible, or there is a work around, but I couldn't find a way to transform data in multiple columns at once.  This would be very useful where a dataset has a large number of columns that all (or some subset) have a format that needs to be changed.  For instance all text fields could have underscores that need to be converted to spaces.  This is an enhancement request.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=251_
##

**Comment by thadguidry** [comment]
The idea of Macros plays here, which OpenRefine does not have, but basically begin recording a Macro (a set of operations against 1 column) that you can then Replay over any number of columns of your choosing)

**Comment by magdmartin** [comment]
Alternatively that could be done via the *All* drop down menu where the user can select which column to apply the operations (all, on a subset with point and click selection like the remove rearrange function)

**Comment by thadguidry** [comment]
@magdmartin Agreed, overall it needs to be highly intuitive and easily selectable for various rearrangements.  There's plenty of implementations of Jquery plugins that would help our cause with this issue. http://plugins.jquery.com/?s=table

**Comment by ostephens** [comment]
Is this delivered (at least partially?) by https://github.com/OpenRefine/OpenRefine/commit/20acc17c05c3d76a643908fe8918d788abc2cf6f

**Comment by thadguidry** [comment]
Yes @ostephens , I think it does, so closing this one.
Supporting Macros is in issue #109
