### ISSUE TITLE
true.type() return « java.lang.Boolean » and not « boolean »

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#2510]
**Describe the bug**

Expression|Result|Expected result
-- | -- | --
true.type()|**"java.lang.Boolean"**|_"boolean"_
(1).type()|"number"|"number"
"A".type()|"string"|"string"
now().type()|"date"|"date"
[].type()|"array"|"array"
null.type()|"undefined"|~~"null"~~ "undefined"

**To Reproduce**
1. Go to 'Edit cells -> Transforms…'
2. Enter 'true.type()' in the Expression field
3. See « java.lang.Boolean » in the preview

**Current Results**
true.type() -> "java.lang.Boolean"
null.type() -> "undefined"

**Expected behavior**
true.type() -> "boolean"
~~null.type() -> "null"~~

**OpenRefine (please complete the following information):**
 - Version v3.3

**Comment by antoine2711** [comment]
Hi @tfmorris, 
 
> `boolean` is a bug, but it's also (technically) a breaking change to fix it.

Yes, it would be a breaking change, but a very logical one. I try to find and fix those as soon as possible. Since we are moving to a model that takes more into account datatype (at least, we are aiming for it), I think this will be use more and more. It's seam a bit inevitable to me…

> `null` isn't a thing, so it can't have a type.

Now, this is a very particular case. null is inherently distinct of all the other datatypes, because it at the same time a **data value** AND a **datatype**. 

Nobody will do `null.type()`. What people do is `vUnknownVar.type()`. And when you do that, undefined is of no use. Of course, you can either go by elimination, or do a second check, but why forced it? Knowing it's a null is all you need to know to go on.

I understand it's weird, but for me, it would be VERY valuable. Does that make sense to you? Should I explicitly request other people input (if so, how? namely? who?).

Regards, Antoine

**Comment by Shubhangi2901** [comment]
Hi @antoine2711 I would love to work on this

**Comment by antoine2711** [comment]
> Hi @antoine2711 I would love to work on this

Hi @Shubhangi2901. I wonder. This issue is new, and as a few potential problems. There is a « breaking » issue, and there is a contested opinion that has only be discussed by the creator o the issue. As such, even if you provide a valid PR that fix all of this issue, it might be refused.

Also, I've seen what you did, and you are WAY to good for this issue. This is an issue at the entry level, which are useful for starters to get a feel of the project. There are many other issues that come to my mind that would be much more rewarding for you, and that would have a greater impact on the project. Are you game to raise the level of difficulty?!

Regards, Antoine

**Comment by antoine2711** [comment]
As a follow up on this issue, I'd like to bring to the attention of contributors that `type(value)` on a column with store value should also return "error" and not throw or raise the error.

Also, `isError(type(value))` return true because type failed to tell us the type of a STORED variable, and instead, just raised again the same error (with no calculation or operation involved).

Type should never result in an error. At the worst, it should return an empty string or `undefined` (as it does now, most of the time). But how could a worst situation be? This is an utility function, and as such, it should be robust.

I think type() should also intercept errors like this:
Expression|Result|Expected result
-- | -- | --
value.type()|raise the error|error
type(parseJson("a"))|`parseJson failed: Unrecognized token 'a': was expecting ('true', 'false' or 'null') at [Source: (String)"a"; line: 1, column: 3]`|error
isError(type(value))|true|false

Visual representation of the problem:
![image](https://user-images.githubusercontent.com/12217525/78468983-ac198580-76ea-11ea-854f-cf43ef45c353.png)

**Comment by thadguidry** [comment]
The comments in this issue are assuming a lot of things about a lot of other things, and I think it is distracting.  I think we should try to focus on 1 problem with GREL syntax and 1 GREL function at a time.
1. Type Error [[1](https://docs.python.org/3.8/library/exceptions.html#TypeError)]
2. Value Error [[2](https://docs.python.org/3.8/library/exceptions.html#ValueError)]

**Comment by thadguidry** [comment]
In regards to the origin of this issue...

1. I agree with @antoine2711 when the value is a `boolean` that we should improve the returned value of `type(value)` to be simply `boolean` and not `java.lang.Boolean`.
2. I agree with @tfmorris that the type of `null` should continue to return `undefined`.

![image](https://user-images.githubusercontent.com/986438/78499324-9ff6ed80-7715-11ea-82af-1512faf4c785.png)

**Comment by antoine2711** [comment]
@thadguidry: there is a global scope here to this issue, and it's « how does `type()` function behave ».

Yes, `null.type()` would be 1) breaking, 2) semantic change. My point here is that undefined is a value, not a datatype, which is what we expect of type(). But I'm not pushing that issue. I'd be happy that is continues to return `"undefined"` for `null`. It's a purist thing.

Now, I think that `type(eErr)` where eErr is an error object (like what `parseJson("a")` returns), that is an issue. It's doesn't trap the error, like isError(eErr) would do. I think this is also a real problem, and I don't think this is as breaking as the other issues.

Regards, Antoine

**Comment by thadguidry** [comment]
`undefined` is an error response.

**Comment by antoine2711** [comment]
@thadguidry: note that I did consider to widen even more the discussion by bring around that:

Expression|Result|Expected result
--- | -- | :------:
row.type()|com.google.refine.expr.WrappedRow|"object: row" 
row.record.type()| com.google.refine.expr.WrappedRow$WrappedRecord |"object: record"
cell.type()| com.google.refine.expr.WrappedCell |"object: cell"
cells.type()| com.google.refine.expr.CellTuple |"object: cells"
cell.recon.features.type()]| com.google.refine.model.Recon$Features |"object: features"
row.record.cells.type()| com.google.refine.expr.WrappedRow$RecordCells |"object: cells"

Note that "object: cells" could also just be "object" or could be written "cells object".

For reference:
Expression|Result|Expected result
--- | -- | :------:
cell.recon.match.type.type()|"array"|"array"
rowIndex.type()| "number" |"number"
row.columnNames.type()| "array"|"array"
row.starred.type()| "java.lang.Boolean"|"boolean"
cell.recon.judgment.type()| "string"|"string"

But I think it would be better to discussed this in another thread, with the scope: « How does type( _anObject_ ) behaves ».

Regards, Antoine

**Comment by antoine2711** [comment]
Hi @thadguidry: in a quick follow-up, this is what we have in our doc:
![image](https://user-images.githubusercontent.com/12217525/78689583-7d570700-78c4-11ea-9700-bb0febb99426.png)

Null is stated to be a type (and error also). If we change our vocabulary, we should be consistent. I really think `type()` should return those same values.

A quick question: I think we should add « array » to the list of (data) types. What do you think? Should we say it's a datatype, or just a type?

Regards, Antoine.

**Comment by thadguidry** [comment]
> A quick question: I think we should add « array » to the list of (data) types. What do you think? Should we say it's a datatype, or just a type?

Many times we have talked about adding `array` as a new datatype before in some of [these issues](https://github.com/OpenRefine/OpenRefine/issues?q=is%3Aissue+is%3Aopen+array), but no one has created a dedicated issue for that yet.

**Comment by antoine2711** [comment]
> Many times we have talked about adding `array` as a new datatype before in some issues.

@thadguidry: I removed from the title and the description of this issue `null.type() == "null"`. So now, this issue would be only about `true.type() == "boolean"`. That is a consensus, do you agree?

I will add documentation for array datatypes.

Regards, A.

**Comment by thadguidry** [comment]
@antoine2711 Sure why not. :-)

**Comment by antoine2711** [comment]
> Hi @antoine2711 I would love to work on this

@Shubhangi2901: if you want to do this issue like you asked 2 weeks ago, it is yours.

Regards, A.
