### ISSUE TITLE
set focus on find-field for replace command

### ISSUE THREAD

**Issue by LibrErli** [OpenRefine/OpenRefine#2514]
**Enhancement Suggestion**
If you click on `Edit Cells > Replace` it would be very great if the cursor focus will be set automatically to the input field for the `find`-string (`id#text-to-find-..`.)

**Environment**
* OpenRefine 3.3
* Firefox 74
* Ubuntu 18.04

**Comment by kovacskarolina** [comment]
Hello, I think I've solved this issue. Can you assign it to me?

**Comment by HeroicHitesh** [comment]
@LibrErli Does this issue need further fixes or is it resolved? I see there's a merged PR, so if the issue is resolved by @kovacskarolina PR kindly close this issue to avoid confusion.

**Comment by wetneb** [comment]
Thanks for catching this, this one should have been closed indeed.
