### ISSUE TITLE
Hyperlink is created for cell value even when invalid and text datatype is choosen

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#2519]
**Describe the bug**
Hyperlink is created for cell value, even when text is specified as the datatype.

**To Reproduce**
1. Edit a cell's value
2. Choose datatype: Text
3. Paste the following text exactly (includes whitespace):
```
https://www.wikidata.org/wiki/Property:P670 https://www.wikidata.org/wiki/Property:P669 are now mapped to https://schema.org/streetAddress via https://www.wikidata.org/wiki/Property:P2235
```

4. Click Apply

**Current Results**
Notice that cell value is shown completely as a clickable hyperlink rather than just text.

**Expected behavior**
The cell's value should be rendered with only those pieces which represent valid URLs hyperlinked. For the example above, there should be four hyperlinks with unlinked text " are now mapped to " and " via " between them.

Browsers now have native support for URL detection and we should take advantage of that.  See comment https://github.com/OpenRefine/OpenRefine/issues/2519#issuecomment-612645821

**Screenshots**
![image](https://user-images.githubusercontent.com/986438/78576770-c3dc3100-77f2-11ea-93c4-c0942636048c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: JDK8

**OpenRefine (please complete the following information):**
 - Version: Trunk (master)

**Additional Context**
The use case that I actually had here in #2519 was that of a cell of text that might contain multiple URLs would be convenient to be able to click on the URLs and it open a browser for quick verification during reconciling processes.

As long as scrolling the grid still works, editing the cells still works, running GREL operations on the cell text, and exporting the cells still works, then I think it satisfies most of the needs that will come up within GLAM reconciling processes with multiple URLs in a cell text for clicking and verifying.

**Comment by wetneb** [comment]
About the expected behaviour, we could also decide to create hyperlinks, but for each hyperlink in the cell text, not for the cell as a whole. But not adding any hyperlinks is a sensible choice too.

**Comment by thadguidry** [comment]
Here, I specifically wanted just Text datatype and not a General datatype.
Historical perspective:  We originally added the hyperlinking to make it easy for Freebase MID querying via the URL after doing some column additions ...and this way of handling stayed around.

We now need to be strict when a user explicitly says Text datatype.
AGREE - Additionally, we can have a General datatype (or whatever we call it) as most spreadsheets do that would work as you stated and created hyperlinks that were valid within the cell text...and test and ensure that all our Exporters work as expected of course.

**Comment by kushthedude** [comment]
@thadguidry Found the bug. Fix on the way!

**Comment by thadguidry** [comment]
@kushthedude Thanks, but I'd rather have some option (even if a global preference) for changing the cell value representation and allow a user to control that.  I don't want OpenRefine to have final control of this, we should be lifting this up to a user's choice.  (Later, of course, we can introduce new datatypes like spreadsheets do to make this a transform option with a General datatype that performs as Text does now (highlighting, URL hyperlinking, etc.)...and then a real pure Text datatype with no cell visual representation other than a String and optionally representing URLs in %-escaped form)

There are guidelines for URL rendering: https://url.spec.whatwg.org/#url-rendering
And here's the standards with guidelines:
https://url.spec.whatwg.org
https://developer.mozilla.org/en-US/docs/Web/API/URL/URL
https://chromium.googlesource.com/chromium/src/+/master/docs/security/url_display_guidelines/url_display_guidelines.md#escaping

For now, I think we can simplify this file with the below functions only and strip out the rest (given that `URL` and by inclusion, `USVString` are part of web standards today.

```javascript
/*

Copyright 2010, Google Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

 * Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the
distribution.
 * Neither the name of Google Inc. nor the names of its
contributors may be used to endorse or promote products derived from
this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,           
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY           
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

 */

URL.getParameters = function() {
  var r = {};

  var params = window.location.search;
  if (params.length > 1) {
    params = params.substr(1).split("&");
    $.each(params, function() {
      pair = this.split("=");
      r[pair[0]] = decodeURIComponent(pair[1]);
    });
  }

  return r;
};

URL.looksLikeUrl = function(s) {
  try {
    url = new URL(s);
    return url
  } catch(e) {
    return false // not a URL per WHATWG spec https://url.spec.whatwg.org/
  }
}
```

**Comment by thadguidry** [comment]
Also we should be careful in our own APIs on naming with `URL`.
https://url.spec.whatwg.org/#url-apis-elsewhere

**Comment by ektasinghai** [comment]
I would like to work on this issue. Please help me in getting started

**Comment by wetneb** [comment]
@ektasinghai have a look at @kushthedude's earlier attempt: #2540 and https://github.com/OpenRefine/OpenRefine/wiki/Your-first-pull-request.

If you have any specific questions let us know!

**Comment by singhakshita** [comment]
I want to work on this issue ,can i ?

**Comment by singhakshita** [comment]
hey ,if i m not wrong ,proper check of the text in the cell ,should fix this  right?

since i m new to this open source contribution ,it might take a bit more of a time ,but i m working on it ,
thanks

**Comment by singhakshita** [comment]
singhakshita:fixes#2519-hyperlink-issue #3542 

the following issue has been fixed 
please let me know if any change is required

**Comment by singhakshita** [comment]
for some Reason the functions in the comments is not showing any url as valid ,can u please guide me a bit

**Comment by tfmorris** [comment]
> @tfmorris et. al. - The use case that I actually had here in #2519 was that of a cell of text that might contain multiple URLs would be convenient to be able to click on the URLs and it open a browser for quick verification during reconciling processes.
> 
> The example test was just a sentence structure that I found quickly that had the elements and spacing considerations to take into account for parsing.
> The use case, as I said, is that where users would see the columns of cell text and have clickable URLs within the cells text. Nothing more, nothing less.
> 
> As long as scrolling the grid still works, editing the cells still works, running GREL operations on the cell text, and exporting the cells still works, then I think it satisfies most of the needs that will come up within GLAM reconciling processes with multiple URLs in a cell text for clicking and verifying.

OK, based on that (which contradicts the current "Expected Behavior" text), I will update the ticket to match the behavior that is implemented by the PR.
