### ISSUE TITLE
GREL variable cells.colName returns null when cell contains null value

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#252]
_Original author: jcreena...@gmail.com (November 25, 2010 04:10:55)_

<b>What steps will reproduce the problem?</b>
1. Click column header -&gt; Edit Cells -&gt; Transform
2. Enter GREL expression cells.colName, where colName is a column that contains both null and non-null values
3. In preview tab, rows with non-null colName value show '[object Cell]'. Rows with null colName value show 'null'
4. Enter GREL expression cells.colName.value
4. In preview tab, rows with non-null colName value show cell value. Rows with null colName value show 'Error: Cannot retrieve field from null'

<b>What is the expected output? What do you see instead?</b>
I would expect that cells.colName always returns a cell object and that cells.colName.value returns null if the value is null

<b>What version of the product are you using? On what operating system?</b>
Refine 2.0-r1836
Chrome 9.0.587.0 dev
Windows XP Pro SP2

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=252_

**Comment by thadguidry** [comment]
Fixed in #1539 and #1598
