### ISSUE TITLE
Wikidata login fails since 2020-04-07 due to a server-side change in cookie handling

### ISSUE THREAD

**Issue by Atudu** [OpenRefine/OpenRefine#2526]
**Describe the bug**

I am using OpenRefine 3.3 version but unfortunately facing problem with the upload edits to wikidata and also facing problem during log in.
**To Reproduce**
1. Go to edit wikidata schema
2. Click on upload edits to wikidata
4. Invalid credentials and facing problem with log in

**Current Results**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows 10, Linux, Ubuntu 18.04]
 - Browser Version: [e.g. Chrome 19, Firefox 61, Safari, NOTE: OpenRefine does not support IE but works OK in most cases]
 - JRE or JDK Version:[output of "java -version" e.g. JRE 1.8.0_181]

**OpenRefine (please complete the following information):**
 - Version [e.g. OpenRefine 3.0 Beta]

**Datasets**

**Additional context**

**Comment by afkbrb** [comment]
Hi, maybe that's a network connection problem. Can you visit Wikidata on the browser?

**Comment by afkbrb** [comment]
If you need to use a proxy to visit https://www.wikidata.org/wiki/Wikidata:Main_Page on the browser, you should configure the proxy in refine.ini.

**Comment by Atudu** [comment]
Yes I visited wikidata in browser... But in open refine I unable to log in
for last 2 days

**Comment by Atudu** [comment]
Yes I visited wikidata in browser... But in open refine I unable to log in
for last 2 days

**Comment by antoine2711** [comment]
> **Describe the bug**
> 
> I am using OpenRefine 3.3 version but unfortunately facing problem with the upload edits to wikidata and also facing problem during log in.

I have the same problem.

Maybe the Recon Server for WD is down? I guess @wetneb must still be sleeping, but I bet he could fix that right away.

Regards,
   Antoine

**Comment by antoine2711** [comment]
> If you need to use a proxy to visit https://www.wikidata.org/wiki/Wikidata:Main_Page on the browser, you should configure the proxy in refine.ini.

The problem is even with v3.3 shipped. I don't think configuration will help.

Regards, Antoine

**Comment by afkbrb** [comment]
Yeah it's not a problem with proxy here. It seems to be a problem with the MediaWiki API of Wikidata, not the reconcilication service, because we can't even login now.

> 12:02:38.227 [..kibaseapi.ApiConnection] API warning [main]: Subscribe to the mediawiki-api-announce mailing list at <https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce> for notice of API deprecations and breaking changes. Use [[Special:ApiFeatureUsage]] to see usage of deprecated features by your application. (109410ms)
12:02:38.228 [..kibaseapi.ApiConnection] API warning [login]: Fetching a token via "action=login" is deprecated. Use "action=query&meta=tokens&type=login" instead. (1ms)
12:03:29.689 [..kibaseapi.ApiConnection] NeedToken: Token or session ID is missing. (51461ms)

**Comment by wetneb** [comment]
I am reporting this bug to Wikidata now.

**Comment by afkbrb** [comment]
It's weird the login API works fine on Postman.
![1](https://user-images.githubusercontent.com/29347603/78747903-30932f00-799d-11ea-9e7b-f7d9e4848e46.PNG)

But if I write a test like this:
```java
    @Test
    public void testLogin() throws LoginFailedException {
        ApiConnection connection = ApiConnection.getWikidataApiConnection();
        connection.login("username", "password");
    }
```

Still got the message "NeedToken: Token or session ID is missing."

**Comment by wetneb** [comment]
This could be due to some missing headers not added by Wikidata-Toolkit, which Wikidata has started to require, perhaps?

**Comment by wetneb** [comment]
Phab task: https://phabricator.wikimedia.org/T249680
Related WDTK pull request: https://github.com/Wikidata/Wikidata-Toolkit/pull/490

**Comment by wetneb** [comment]
@Atudu thanks for reporting this. You can download a snapshot version of OpenRefine where this bug is fixed: get the latest one at https://github.com/OpenRefine/OpenRefine-nightly-releases/releases

**Comment by Atudu** [comment]
Hi all, but the problem is remain same. Yesterday I tried.. but same result.

**Comment by wetneb** [comment]
@Atudu as of today, both the patched version above and the 3.3 release should work since Wikidata has been patched server side for this bug. Can you retry today?

**Comment by Atudu** [comment]
Yes, today I will try.

**Comment by Atudu** [comment]
Thanks to all of you. Yes it's working now.
