### ISSUE TITLE
New exporter: markdown table

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2532]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**

It would be useful to have an exporter to represent a table in Markdown. The format is specified in the Github-Flavoured Markdown guide:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables

And in the specs: https://github.github.com/gfm/#tables-extension-

**Describe the solution you'd like**

Given

| Field   | Data                  |
|---------|-----------------------|
| Name    | Galanthus nivalis     |
| Color   | White                 |
| IUCN ID | 162168                |
| Name    | Narcissus cyclamineus |
| Color   | Yellow                |
| IUCN ID | 161899                |

we would get

```markdown
| Field   | Data                  |
|---------|-----------------------|
| Name    | Galanthus nivalis     |
| Color   | White                 |
| IUCN ID | 162168                |
| Name    | Narcissus cyclamineus |
| Color   | Yellow                |
| IUCN ID | 161899                |
```

Note the need to add spaces to pad the cell values to the same length.

**Describe alternatives you've considered**
I don't think the custom tabular exporter has support for this sort of cell padding. If we add support for padding in it, we could potentially reuse it. But the export workflow would be more cumbersome (since the exporter would need to be configured every time).

**Additional context**

This could be based on an existing Java library, such as https://github.com/Steppschuh/Java-Markdown-Generator

If we are to include examples of tables in our Markdown documentation, this could be very useful.

**Comment by thadguidry** [comment]
gfm is a flavor of commonmark.  It has it's own table style different from others (pipe tables, which are simpler, etc.)  When I was reviewing Pandoc I used the gfm extension within it to control the options to do the conversion from creole to md.  I enabled gfm as the target (and creole as the from) and then it toggled all the right options on for me, just by using `-t gfm`, like so:
```
pandoc -s --file-scope -f creole -t gfm -o Whats-New.md Whats-New.creole
```

Here's the 4 different kinds of table styles within flavors of md:  https://pandoc.org/MANUAL.html#tables

**Comment by wetneb** [comment]
Yes, it might make sense to support multiple flavours of tables (it's a pity there are so many variations).

**Comment by thadguidry** [comment]
I would not support the other flavors.  That way we help commonmark [finally push tables into core](https://talk.commonmark.org/t/tables-in-pure-markdown/81/159) when the time comes.  Just use gfm.  I was only telling a bit of history in case folks later ask, why do you only support pipe table syntax in the markdown output?  Our answer: because its the best :) and many editors support it, even though its not in the core of commonmark yet.

**Comment by Unnamed-1408** [comment]
Hello. I want to have a try, can you assign this issue to me ? Thanks!
