### ISSUE TITLE
RDF Importer Turtle is creating extra statements

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#2536]
**Describe the bug**
Importing the Open Graph Protocol turtle file gives odd rows for SPO.

**To Reproduce**
1. Import URL  http://ogp.me/ns/ogp.me.ttl
2. Facet on `subject` column with GREL `value.startsWith("http")`
3. Select `false` rows
4. Notice the 9th columns' values that correlate with the comment on `ogc:determiner_str` Datatype

**Current Results**
Parsing creates extra rows unnecessarily. 

**Expected behavior**
I would expect that the parser would escape the rdfs:comment correctly for this entity in the file? (but I didn't dive into Jena's handling for that comment.)
While debugging, the extra statements made however can clearly be seen by setting a breakpoint here:
https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/importers/RdfTripleImporter.java#L109

```
ogc:determiner_str a rdfs:Datatype ;
  owl:oneOf ("" "the" "a" "an" "auto") ;
  rdfs:label "determiner"@en-US ;
  rdfs:comment "The lexical space: \"\", \"the\", \"a\", \"an\", and \"auto\"."@en-US ;
  rdfs:isDefinedBy ogc: ;
  rdfs:subClassOf xsd:string .
```

**Screenshots**
![image](https://user-images.githubusercontent.com/986438/79055423-9f2cf280-7c12-11ea-9b42-1890f2fe5baf.png)

Inspecting the triples stored in the model's store:

![image](https://user-images.githubusercontent.com/986438/79055918-7a3a7e80-7c16-11ea-93d2-4d5f62a631cd.png)

One of the elements in question:

![image](https://user-images.githubusercontent.com/986438/79055938-b53cb200-7c16-11ea-9993-56ed28dfa6bd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: JDK8

**OpenRefine (please complete the following information):**
 - Version:  Trunk (master)

**Additional context**
Online validators that use Apache Jena, do not seem to have an issue with parsing the file content.
http://rdfvalidator.mybluemix.net/

**Comment by tfmorris** [comment]
Those giant pictures don't have anything to do with the problem. The line that is creating those triples is not the one that you've highlighted in yellow, ie

> rdfs:comment "The lexical space: \"\", \"the\", \"a\", \"an\", and \"auto\"."@en-US ;

which you can find present in the OpenRefine project. It is this one:

> owl:oneOf ("" "the" "a" "an" "auto") ;

which gets split apart (correctly, as far as I can see) into triples for each of its alternatives.

The only unusual thing that I can see is that Jena is apparently not unescaping escaped quotes, but that's cosmetic, easily remedied and, if a bug, Jena's not ours.
