### ISSUE TITLE
Unable to load files in

### ISSUE THREAD

**Issue by rileyhun** [OpenRefine/OpenRefine#2552]
**Describe the bug**
I deployed an OpenRefine server using docker on Google Kubernetes Engine. It seemed to be working initially, and then after uploading maybe the 5th csv file, it returns an error. I am not quite sure what's causing this issue but my GKE cluster has 5 nodes, each equipped with 8 cpus and 30 GB of memory: 

Error: 
```
No such import job
No technical details.
```

**Screenshots**

<img width="1076" alt="Screen Shot 2020-04-15 at 11 52 23 AM" src="https://user-images.githubusercontent.com/20649466/79376854-a05e6800-7f0f-11ea-9fdc-6646dbdbb075.png">

**Desktop:**
 - OS: Linux (Debian10)
 - Browser Version: Chrome

**OpenRefine:**
 - Version 3.3

**Dockerfile**
#We can use the smaller JRE rather than the JDK
FROM openjdk:8-jre-alpine as builder

MAINTAINER 

#Download a couple of required packages
RUN apk update && apk add --no-cache wget bash

ARG RELEASE=3.3

ENV RELEASE=$RELEASE

#Download a distribution archive file
RUN wget --no-check-certificate https://github.com/OpenRefine/OpenRefine/releases/download/$RELEASE/openrefine-linux-$RELEASE.tar.gz

#Unpack the archive file and clear away the original download file
RUN tar -xzf openrefine-linux-$RELEASE.tar.gz  && rm openrefine-linux-$RELEASE.tar.gz

#Create an OpenRefine project directoryqtqqqqtttqtq
RUN mkdir /mnt/refine

#Mount a Docker volume against the project directory
VOLUME /mnt/refine

#Expose the server port
EXPOSE 8080

CMD openrefine-$RELEASE/refine -i 0.0.0.0 -p 8080 -d /mnt/refine

**Comment by thadguidry** [comment]
What are you trying to do with your CSV files?
(that you couldn't do with some ETL program like Apache NiFi or Pentaho ?
or even just sed ?)

If you can explain your processing needed for those CSV files, then we
might offer some good alternative workflows and programs to help you.

Thad
https://www.linkedin.com/in/thadguidry/

**Comment by rileyhun** [comment]
> What are you trying to do with your CSV files? (that you couldn't do with some ETL program like Apache NiFi or Pentaho ? or even just sed ?) If you can explain your processing needed for those CSV files, then we might offer some good alternative workflows and programs to help you.

Thanks @thadguidry. I'm aware of other ETL programs I can use. But we are trying to use OpenRefine as more of a presentation tool due to its clean UI interface. The main objective of OpenRefine is to integrate some APIs and use them as facets/extensions to apply against a dataset is loaded.

**Comment by thadguidry** [comment]
We don't know what this could be.
1. It depends also on how you are loading the CSV files (from a massive zip file or 1 by 1)?
2. Are you using the UI itself?  or one of our community written API's to drive OpenRefine programmatically? Which one?
3. Can you give us the portion of the Docker logs for the OpenRefine output?  It's possible they're more detail there like a Java exception since OpenRefine is a Java application.
4. Did you ensure that OpenRefine has a valid Workspace folder configured to save the Project files during creation?  (our command line startup option `-d <datadir>`) that is also accessible to it from within Docker? more correctly that the folder is available to the Java process that OpenRefine runs under? (since your dealing with Docker and mounted volumes, so all those wonderful access permissions need to be double checked)

**Comment by rileyhun** [comment]
> We don't know what this could be.
> 
> 1. It depends also on how you are loading the CSV files (from a massive zip file or 1 by 1)?
> 2. Are you using the UI itself?  or one of our community written API's to drive OpenRefine programmatically? Which one?
> 3. Can you give us the portion of the Docker logs for the OpenRefine output?  It's possible there is more detail there like a Java exception since OpenRefine is a Java application.
> 4. Did you ensure that OpenRefine has a valid Workspace folder configured to save the Project files during creation?  (our command line startup option `-d <datadir>`) that is also accessible to it from within Docker? more correctly that the folder is available to the Java process that OpenRefine runs under? (since your dealing with Docker and mounted volumes, so all those wonderful access permissions need to be double checked)

**Comment by rileyhun** [comment]
(1) Loading the CSV files one by one. Keep in mind that it seems to work some of the times, and then eventually fails after a while
(2) Using the UI itself
(4) Yes - it has access to that project folder

**Comment by thadguidry** [comment]
Hmm, well, if you can send the logs over (even privately if you need to my email thadguidry@gmail.com) then we can take a look.

Other than that, I'm stumped.

**Comment by rileyhun** [comment]
> Hmm, well, if you can send the logs over (even privately if you need to my email [thadguidry@gmail.com](mailto:thadguidry@gmail.com)) then we can take a look.
> 
> Other than that, I'm stumped.

Yeah - I was trying to find the logs on Kubernetes but wasn't able to recover them for this specific service. I'll try to dig for it. Thanks in advance.

**Comment by thadguidry** [comment]
@rileyhun Let's close this issue and move the conversation over to the mailing list for getting troubleshooting help for you and GKE with the rest of our community eyes and ears.  Someone else might have a hunch and can also help you.

**Comment by kishore0709** [comment]
Hi @rileyhun  , I'm planning to implement openrefine on k8s cluster. Could you please help provide me helm chart repo(if it is deployed with helm). If it is not implemented with helm, can you provide some insights on implementation side. 

Thanks!
Kishor.

**Comment by rileyhun** [comment]
@kishore0709 - 

You can use this article as a reference for building your docker container: 

https://blog.ouseful.info/2019/02/07/how-to-create-a-simple-dockerfile-for-running-openrefine/

Then all you need to do is deploy that docker container on Kubernetes. You can use a simple load balancer.

**Comment by kishore0709** [comment]
Thanks @rileyhun for the link... It really helps me.

**Comment by rileyhun** [comment]
> Thanks @rileyhun for the link... It really helps me.

No problem @kishore0709 - happy to help!
