### ISSUE TITLE
Minimize and maximize a facet at will to manage facets footprints

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#2553]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
I would like to be able to minimize a facet. 

**Describe the solution you'd like**
A little button just beside the close button. It would change of visual when the facet is minimized or when it's fully displayed.

**Describe alternatives you've considered**
Deleting and recreating the facets not used.

**Additional context**
Here's two pictures and a full video demo (6 Mb .GIF file). Facets are minimized and maximized at will:
![image](https://user-images.githubusercontent.com/12217525/79430191-903d9b80-7f96-11ea-87a0-44a498523f78.png)

All minimized:
![image](https://user-images.githubusercontent.com/12217525/79430229-a0557b00-7f96-11ea-98d2-ddf79bb0ee4e.png)
![KINO-Cellules - OpenRefine5](https://user-images.githubusercontent.com/12217525/79423841-4b613700-7f8d-11ea-84ff-cc8b207f5327.gif)

**Comment by thadguidry** [comment]
@antoine2711 Someone needs to teach you how to make smaller sized animated gifs. 🥇 
👍 Nice improvement I think!

**Comment by antoine2711** [comment]
> @antoine2711 Someone needs to teach you how to make smaller sized animated gifs. 🥇

@thadguidry, what's the recommended max size for an animated .GIF?
Regards, A.

**Comment by thadguidry** [comment]
depends, but 1 meg or 2.  But depends on length, resolution, and number of colors.  Here's a decent guide on things to try:  https://litmus.com/blog/animated-gifs-in-email-10-tips-for-keeping-files-sizes-small
