### ISSUE TITLE
How to Run Custom Python Library as a Facet Transformation?

### ISSUE THREAD

**Issue by rileyhun** [OpenRefine/OpenRefine#2557]
**Describe the bug**
I packaged my module and now it resides in my python2.7 site-packages. Now, when I go to OpenRefine and try to transform a column into a new column using this python module, it doesn't do anything.

**Code**
```
import sys
sys.path.append('/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages')
from openrefinepylib.military_gov_id import classify
return classify(value, '/Users/rihun/secrets/daodl_access.json')
```
**Current Results**
The new column is created but without any values

**Expected behavior**
There should be values for this new column

**Screenshots**
<img width="571" alt="Screen Shot 2020-04-16 at 9 33 14 AM" src="https://user-images.githubusercontent.com/20649466/79482185-55069100-7fc5-11ea-8c10-6b36708e97e3.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Version: Chrome

**OpenRefine (please complete the following information):**
 - Version 3.3

**Comment by rileyhun** [comment]
For added context,

Here is my python module that I've packaged:

from google.auth.transport.requests import AuthorizedSession
from google.oauth2 import service_account
import json

```
def classify(entity_name, service_account_file):

    party_names = [entity_name]

    TARGET_AUDIENCE = <TARGET_AUDIENCE>
    URL = <API_URL>

    creds = service_account.IDTokenCredentials.from_service_account_file(
            service_account_file,
            target_audience=TARGET_AUDIENCE)

    authed_session = AuthorizedSession(creds)

    payload = {
            "entity_name": party_names
        }

    resp = authed_session.post(URL,
                               headers={'Content-Type': 'application/json'},
                               json=payload)

    return json.loads(resp.text)[0]['predicted_classification']
```

I then installed jython2.7.2 separately and used pip to install the custom module and its required dependencies.

When I try to import this module from jython2.7.2 site-packages in OpenRefine, I get the following error: 

`ImportError: cannot import name oauth2`

This is an odd error because oauth2 and google-oauth2 are installed in jython2.7.2

**Comment by thadguidry** [comment]
@rileyhun Jython as our extension on its own path is what gets added to our classpath via Butterfly.  So instead of your Python sys path...use the Jython one.  Alternatively, you can download Jython independently, add it to your path, and then use pip or drop in your package into the locally installed `jython\Lib\site-packages\` folder.

I wrote some of this up already here, if you haven't seen it yet:
https://github.com/OpenRefine/OpenRefine/wiki/Extending-Jython-with-pypi-modules

**Comment by thadguidry** [comment]
@rileyhun Specifically, you might be hitting this problem that I mentioned in the wiki guide?

> NOTE : if you already have a Python version installed, pip install <module> will install the module in your first Python distribution, not in Jython. To work around the problem, use this command instead :
> 
>   C:\Users\Thad>jython -m pip install address-formatter

**Comment by rileyhun** [comment]
> @rileyhun Jython as our extension on its own path is what gets added to our classpath via Butterfly. So instead of your Python sys path...use the Jython one. Alternatively, you can download Jython independently, add it to your path, and then use pip or drop in your package into the locally installed `jython\Lib\site-packages\` folder.
> 
> I wrote some of this up already here, if you haven't seen it yet:
> https://github.com/OpenRefine/OpenRefine/wiki/Extending-Jython-with-pypi-modules

Thanks @thadguidry, I am also trying it with the jython site-packages I've installed and I'm getting this error still. 

Code Example:

```
import sys
sys.path.append('/Users/rihun/jython2.7.0/Lib/site-packages')
from openrefinepylib.military_gov_id import classify
return classify(value, '/Users/rihun/secrets/daodl_access.json')
```

**Comment by rileyhun** [comment]
Just for experimentation purposes, I disregarded my custom module, and just tried to see if openrefine had access to my local jython site-packages. So I tried this block of code:

```
import sys
sys.path.append('/Users/rihun/jython2.7.0/Lib/site-packages')
import requests
r = requests.get('http://cbc.ca')
return r.text[0]
```
It returned that same error regarding oauth2

`ImportError: No module named oauth2`

For some reason jython is having trouble reading oauth2.

**Comment by thadguidry** [comment]
Can we try to explicitly tell Jython to append the path for oauth2 ?
And in the meantime...I'm firing up my environment to try to mimic this now...

**Comment by rileyhun** [comment]
> Can we try to explicitly tell Jython to append the path for oauth2 ?
> And in the meantime...I'm firing up my environment to try to mimic this now...

Could you kindly clarify what you mean? ouath2 is already in the jython2.7.0 site-packages and I've appended the path to this.

**Comment by thadguidry** [comment]
ok, understood now.  trying to reproduce...

**Comment by thadguidry** [comment]
Jython is running on the JVM, it's all pretty fast for general use cases.

You would have to probably just log some statements you need out to a file, something kinda like this:
```python
import logging
import logging.handlers
import os
 
handler = logging.handlers.WatchedFileHandler(
    os.environ.get("LOGFILE", "/var/log/yourapp.log"))
formatter = logging.Formatter(logging.BASIC_FORMAT)
handler.setFormatter(formatter)
root = logging.getLogger()
root.setLevel(os.environ.get("LOGLEVEL", "INFO"))
root.addHandler(handler)
 
try:
    exit(main())
except Exception:
    logging.exception("Exception in main()")
    exit(1)
```

**Comment by thadguidry** [comment]
You might also look into outputting INFO or DEBUG logs for the various libraries you are utilizing if they have options.

**Comment by thadguidry** [comment]
Anyways, glad you solved your issue.  I'll close this now.  For Python help, look to the Python communities on [Stackoverflow](https://stackoverflow.com/questions/tagged/python) or the `#Python` channel on Freenode IRC.

**Comment by rileyhun** [comment]
Well this is working for the the experiment I tried. Still not working with the custom python library I developed.
