### ISSUE TITLE
type(an error) should return the string "error"

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#2562]
**Describe the bug**
`type(value)` on a column with an error stored as a value raise the error instead of returning the string "error".

`type()` should never result in an error. At the worst, it should return an empty string or `undefined` (as it does now, most of the time). This is a utility function, and as such, it should be robust.

Current code (probably since a lots of years…):
https://github.com/OpenRefine/OpenRefine/blob/d7d567439eb39957e149e1b67576fe67c7836a10/main/src/com/google/refine/expr/functions/Type.java#L51-L66

**To Reproduce**
1. Go to 'Edit Cells -> Transform'
2. Type '`type(parseJson("a"))`'
4. See error and not "error"

**Current Results**
An error is raised, interrupting the process.

**Expected behavior**
I think `type()` should also intercept errors like this (where value is a previously stored error):
Expression|Result|Expected result
-- | -- | --
value.type()|raise the error IF value is a stored error|"error"
type(parseJson("a"))|raise the error: `parseJson failed: Unrecognized token 'a': was expecting ('true', 'false' or 'null') at [Source: (String)"a"; line: 1, column: 3]`|"error"
type(vfdsf)|"undefined"|"undefined"

**Screenshots**
![image](https://user-images.githubusercontent.com/12217525/78468983-ac198580-76ea-11ea-854f-cf43ef45c353.png)

**OpenRefine (please complete the following information):**
 - Version 3.3

**Comment by antoine2711** [comment]
In the PR « Fix the true.type() == "boolean" #2586 », @wetneb noted that `type()` being a function, it will never have the opportunity to inspect its arguments if they contain errors. He suggested it « might » be converted to a control. 

But, @tfmorris said that this choice would be breaking, as the Dot Syntax functionality would no longer work.

So, the idea of extending the Dot Syntax for control is now discussed (Extending the dot syntax for controls #2618). This would open a non-breaking path to this issue, by transforming it into a control, while still retaining its Dot Syntax functionality.

Regards, Antoine

**Comment by tfmorris** [comment]
Evaluation of parameters happens before the `type()` function gets control, so it's never going to see the error. Also, an error isn't a data type. Data types, which is what `type()` returns are things like String, Date, etc.

If you want to know whether an expression will result in an error (or have a cell which contains an error, rather than a value), use the `isError()` control. Because it's a control rather than a function, it doesn't have its operands evaluated ahead of time.
