### ISSUE TITLE
OpenRefine not saving

### ISSUE THREAD

**Issue by bcohn13** [OpenRefine/OpenRefine#2577]
**Describe the bug**

**To Reproduce**

**Current Results**

![OpenRefine](https://user-images.githubusercontent.com/44617211/79893648-5aebe000-83d2-11ea-9620-dd9713ce97d6.PNG)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows 10, Linux, Ubuntu 18.04]
 - Browser Version: [e.g. Chrome 19, Firefox 61, Safari, NOTE: OpenRefine does not support IE but works OK in most cases]
 - JRE or JDK Version:[output of "java -version" e.g. JRE 1.8.0_181]

**OpenRefine (please complete the following information):**
 - Version [e.g. OpenRefine 3.0 Beta]

**Datasets**

**Additional context**

**Comment by kushthedude** [comment]
@bcohn13 Did you even create any project?
The above details you provided are insufficient to analyse what is the problem from our end?
It would be great if you could provide more details like dataset, OpenRefine Version, How to reproduce error & what platform are you on?

**Comment by tfmorris** [comment]
No response. Closing.
