### ISSUE TITLE
Add Edit on GitHub link to documentation

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2578]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**

On pages like https://docs.openrefine.org/operations/key_value_columnize.html, it would be good to have an edit link, pointing to:
https://github.com/OpenRefine/OpenRefine/edit/master/docs/src/operations/key_value_columnize.md

**Describe the solution you'd like**
Integrate it nicely in the design (there might be native things in Docusaurus for that).

**Comment by thadguidry** [comment]
Most the the site configuration for Docusaurus that we'll want to review eventually is done via siteConfig.js
Specifically, this should do it https://docusaurus.io/docs/en/site-config#editurl-string
Submitted a PR for that above.
