### ISSUE TITLE
OpenRefine not loading the data 

### ISSUE THREAD

**Issue by Ananthsubray** [OpenRefine/OpenRefine#2585]
**Describe the bug**

I am using OpenRefine on Ubuntu 19.10, from past few weeks I am not able to load the data sets more than 30 cells in open refine. Anything less than that is working completely fine.

**Comment by magdmartin** [comment]
@Ananthsubray  can provide to the team a bit more information:
* version of OpenRefine
* version of the browser used 
* jre or jdk version
* can you share your dataset (if it contains no confidential data)

thank you.

**Comment by tfmorris** [comment]
Closing due to lack of response. 

@Ananthsubray feel free to reopen if you can provide data or steps to reproduce the problem.
