### ISSUE TITLE
XlsExporter mime types for excel are not standard

### ISSUE THREAD

**Issue by pjfanning** [OpenRefine/OpenRefine#2595]
**Describe the bug**

XlsExporter.java has https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/exporters/XlsExporter.java#L68

https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

* .xls application/vnd.ms-excel
* .xlsx application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

I can provide a PR if this issue is deemed worth fixing.

**OpenRefine (please complete the following information):**
 - Version - latest master branch

**Comment by wetneb** [comment]
Thanks for reporting this, it would indeed be worth fixing this.

It would also be worth adding these MIME types to `main/webapp/modules/core/MOD-INF/controller.js`, in the map from MIME types to importers (without replacing the existing ones - we should just add new entries in the map).

**Comment by wetneb** [comment]
Closed by #2596
