### ISSUE TITLE
Support wildcards in importer MIME type registry

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2598]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
We hold a mapping from MIME types to our supported import formats in `main/webapp/modules/core/MOD-INF/controller.js`.
MIME types can vary and so it would be useful to support wildcards in this mapping: https://github.com/OpenRefine/OpenRefine/pull/2596#discussion_r415296082

**Describe the solution you'd like**

Improve `ImportingManager` to support wildcards in the keys of `mimeTypeToFormat`. The lookup should still be efficient.

**Additional context**

If I remember correctly this was also brought up by @tfmorris recently in another context but I cannot remember where.

**Comment by tfmorris** [comment]
The specific case that I was talking about (and I don't remember the context off-hand) was supporting the use of [Structured Syntax Name Suffixes](https://tools.ietf.org/html/rfc6838#section-4.2.8) as a fallback for importers.

Currently we support `rdf+xml` and know that it's more specific than the generic `text/xml` so we should try the RDF importer before the XML importer, but if we encounter an unknown type with a syntax suffix, we don't prioritize the appropriate importer.

The idea would be that if we were to encounter `application/3gpdash-qoe-report+xml` or `application/activity+json` (to pick the first ones on the [list](https://www.iana.org/assignments/media-types/media-types.xhtml#application)), we would suggest the XML and JSON importers, respectively, as the first fallback options.

This is something we could implement directly in the importer framework, so perhaps it's orthogonal to the idea that @wetneb had for this issue.

**Comment by tfmorris** [comment]
In looking back at the original usage https://github.com/OpenRefine/OpenRefine/pull/2596#discussion_r415296082, the wildcard was used in place of two different types, and was a different use case than the one that I was discussing. Since MIME types are registered individually and are bounded in number, I think wild card support is pretty low priority.

**Comment by tfmorris** [comment]
I'd like to see us drop this (and the associated PR) now that we have #2805. I can't think of a use case that justifies it and any implementation is going to add complexity to the simple table lookup that we have now.
