### ISSUE TITLE
Rod Whiteley's GREL Quick Reference (PDF) link is dead

### ISSUE THREAD

**Issue by rileygr** [OpenRefine/OpenRefine#2605]
The "Rod Whiteley's GREL Quick Reference (PDF)" link http://co-synergy.com/GREL%20Quick%20Reference.pdf
in the GitHub "Documentation For Users" Wiki page 
https://github.com/OpenRefine/OpenRefine/wiki/Documentation-For-Users
points at a place-holder domain.  The URL would be better if it pointed at the PDF in GitHub.

**Comment by tfmorris** [comment]
@allanaaa This is a candidate for you -- along with with any others that have the [documentation](https://github.com/OpenRefine/OpenRefine/labels/documentation) tag.

**Comment by thadguidry** [comment]
We now have the official GREL Reference completely documented at https://docs.openrefine.org/manual/grelfunctions
Along with using Expressions in general at https://docs.openrefine.org/manual/expressions

@rileygr Our user community is free to add useful links (like Rod Whiteley's GREL reference) however on this page: https://github.com/OpenRefine/OpenRefine/wiki/External-Resources

Closing this as unnecessary.
