### ISSUE TITLE
Feature Request: Import new columns from file

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#261]
_Original author: sande...@gmail.com (November 27, 2010 23:10:51)_

<b>What steps will reproduce the problem?</b>
<b>1.</b>
Import data with 50 rows and 1 column from CSV file
<b>2.</b>
Want to import new column from different CSV file with 50 rows and 1 column
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
New column in existing project with a value in each row corresponding to the value in the CSV file for that row.

<b>What version of the product are you using? On what operating system?</b>
Version 2.0 for Mac OSX

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=261_

**Comment by wetneb** [comment]
It'd argue what you want here is a join on the rowId. I would say this is too narrow a use case to be worth adding dedicated support for it.

**Comment by antoine2711** [comment]
@thadguidry, @tfmorris & @wetneb: I think that with a new project and a cross() call, we can do this in 2 steps.

I'd say we close this one as « can be done in another way ». What's your take?

Regards, Antoine
