### ISSUE TITLE
Add a preference to control the choice of row quantity displayed (i.e. other than [5, 10, 25, 50])

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#2624]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
I would like to be able to decide what's would be my choices. A simple preference would do the trick, where I could enter: `[100, 500, 1000, 5000]`.

**Describe the solution you'd like**
Set `ui.gridPaginationSize = [100, 500, 1000, 5000]` in the preferences.

**Describe alternatives you've considered**
Just more paging.

**Comment by wetneb** [comment]
Adding @lisa761 in the loop about this, since she is working on grid pagination.

**Comment by lisa761** [comment]
I think it's a great feature, although I am not too sure about not having a maximum limit to what this preference could be. It might affect the performance. 

About the GSoC project, this would be good to have if we do keep pagination as an alternative. I was thinking of sending out a mail to both the developers and the users group about whether we should keep it or not, today.

**Comment by antoine2711** [comment]
> I think it's a great feature, although I am not too sure about not having a maximum limit to what this preference could be. It might affect the performance.

@lisa761: thanks for your comments.

You probably missed it, but here, in a comment, I said that I was going to limit to 10,000 the max. I tried it on my machine (an average machine), it takes 60 s. to load. Then, it slowly scroll. As all the burden of managing the rows is on the browser, I think this figure is pretty safe. Personally, I would stick at 1000, but I feel the user should choose. And since this feature is a prefs bound one, only savvies users will use it.

Regards,
   Antoine
