### ISSUE TITLE
Add checksums to releases

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2635]
We could consider publishing checksums of our released artifacts.

I would normally expect to provide checksums for the entire archives, not the individual binaries, although that is what was requested today on the mailing list. Given that our binaries are just launchers and all the code resides in class files, I am not sure what guarantees binary checksums give.

This is related to the fact that our packages are unsigned, which displays scary messages to Mac users (and Windows too, I think) when they install the software. The process (and cost) to fix this depends on the target operating system.

https://groups.google.com/forum/#!topic/openrefine/1g957CEbtKI

**Comment by tfmorris** [comment]
I think the downloadable artefacts are the correct things to checksum. The standard flow is download, verify checksums, install/build. Packaging signing is only tangentially related, in my mind.

**Comment by wetneb** [comment]
This has been done in the past few releases.
