### ISSUE TITLE
Follow HTTP redirects in reconciliation calls

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2667]
**Describe the bug**

At the moment, if a reconciliation service updates its URL (via some HTTP redirect) after a user added the service to OpenRefine, subsequent reconciliation operations with this service will fail because we use POST to send reconciliation queries, and there is no way to redirect POST queries in HTTP.

This bug will soon manifest itself with the Wikidata reconciliation service (current deadline: 15th June), so adding this to the 3.4 milestone.

We should ensure that in all places where we send POST requests to a reconciliation service, we first issue a GET request and update the service URL with the redirected URL (if any). For long sessions of POST requests (such as when reconciling a column) we should check for a redirected URL only once, at the beginning of the batch.

**OpenRefine (please complete the following information):**
 - Version 3.4 or earlier

**Additional context**
Issue to mention this in the specs themselves:
https://github.com/reconciliation-api/specs/issues/46

Request for additional time to implement this:
https://phabricator.wikimedia.org/T254172

**Comment by tfmorris** [comment]
We could use [LaxRedirectStrategy](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/LaxRedirectStrategy.html) for the POSTs, but that's not going to help all the clients which have already been deployed.

I think we need to mount a publicity campaign that warns people that there Wikidata reconciliation is going to break and how to fix it (presumably delete and re-add the new end point). It's simple enough for people to work around this that I don't think it's a crisis.

**Comment by wetneb** [comment]
I have sent out an email on mailing lists (openrefine and wikidata) to encourage users to migrate to a new endpoint:
https://wdreconcile.toolforge.org/

**Comment by wetneb** [comment]
Actually, I do not seem to be able to observe this bug! It seems that `HttpURLConnection` follows redirects for POST requests by default (contradicting the standard AFAICT), which is pretty great.
https://docs.oracle.com/javase/7/docs/api/java/net/HttpURLConnection.html#setFollowRedirects(boolean)

**Comment by wetneb** [comment]
This isn't high priority anymore since the redirects are currently followed, although not in a very efficient way. We could just make this a bit more efficient by updating the endpoint URL just once instead of following redirects at each request.

**Comment by tfmorris** [comment]
Do we want to leave this targeted for the 3.4 milestone?

Also, on a more general note, it seems like we should probably re-fetching the service manifest on a periodic basis to pick up any changes. That would provide a mechanism for services to change endpoints, settings, etc.

**Comment by wetneb** [comment]
It should not be a blocker for a release, but I will try to get a simple fix for it in the coming days.

**Comment by tfmorris** [comment]
Now that we've got some basic tests in place, my plan is to replace the HTTP code and use the same client as project import and fetch URL. That would take care of redirects implicitly. But, I wasn't going to try to squeeze it into 3.4.

**Comment by wetneb** [comment]
Redirects are already implicitly taken care of (both for the backend and the frontend) - the problem is that there is still a noticeable overhead if you keep calling the old endpoint, because you are making twice more HTTP requests. For instance for the auto-suggest widgets, it is far from ideal.

So I agree re-fetching the service manifest feels like a good solution. Perhaps just doing it every time the user selects the service in the reconciliation dialog would already take care of most issues and would be safe enough to add to 3.4.

**Comment by tfmorris** [comment]
Seems like this has morphed from a bug report into an enhancement request.

**Comment by wetneb** [comment]
Yeah, let's not try to squeeze this in 3.4.

**Comment by wetneb** [comment]
This was solved by the migration to the Apache HTTP client.

**Comment by gitonthescene** [comment]
Mind if I ask how?  I know it’s solved but I’d like to understand.  Is the idea that there is a fixed proxy fronting the service so that redirects are not needed?  Is the overhead lower because you’re not posting redirects back to the clients but rather routing with the Apache server?  Not related but does the Apache server also take care of flow control?

**Comment by wetneb** [comment]
It was done by https://github.com/OpenRefine/OpenRefine/pull/3237: now that our HTTP calls are done through this library, HTTP redirects are handled by the library directly. We certainly don't introduce any proxy :)
