### ISSUE TITLE
Add tag "openrefine-3.5" to Wikidata

### ISSUE THREAD

**Issue by afkbrb** [OpenRefine/OpenRefine#2669]
The lastest master branch version has been updated to 3.5, but the tag "openrefine-3.5" hasn't been added to Wikidata yet (see https://www.wikidata.org/wiki/Special:Tags), so developers will get the following error when uploading edits to Wikidata via the Wikidata extension:

> ...
> 21:44:36.248 [                   refine] POST /command/wikidata/perform-wikibase-edits (10ms)> 
> 21:44:36.270 [..mWikibaseEditsOperation] Performing edits (22ms)
> 21:44:36.272 [..ting.EditBatchProcessor] Requesting documents (2ms)
> 21:44:38.524 [..ting.EditBatchProcessor] MediaWiki error while editing [badtags]: The tag "openrefine-3.5" is not allowed to be manually applied. (2252ms)
> ...

**Comment by wetneb** [comment]
Requested: https://www.wikidata.org/wiki/Wikidata:Administrators%27_noticeboard

**Comment by afkbrb** [comment]
The tag has been successfully added, https://www.wikidata.org/wiki/Wikidata:Administrators%27_noticeboard#Tag_creation:_openrefine-3.5, I'll close this now.
