### ISSUE TITLE
Network tests being silently skipped

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#2680]
One of the HTTP tests relies on the external endpoint `http://headers.jsontest.com` but if this service is overquota and returning 503s (like it is today), the related tests are silently skipped.

https://github.com/OpenRefine/OpenRefine/blob/5351e9f41c9188006f156c27eadbd6a838cb152d/main/tests/server/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperationTests.java#L285-L298

We should figure out a better way to do this, which doesn't rely on an unreliable external service. One possibility would be to self-host the servlet https://github.com/jsontest/jsontest

**Comment by wetneb** [comment]
I think the best way would be to make the test spin a local test server itself like @afkbrb did recently when mocking other HTTP-based tests.

**Comment by afkbrb** [comment]
Yes I've been using https://github.com/square/okhttp/tree/master/mockwebserver recently for mocking external web services, it's really powerful.
