### ISSUE TITLE
Register OpenRefine in Windows application registry to avoid cleanup of app data

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2681]
**Describe the bug**

There are reports that recent versions of CCleaner could potentially erase workspace files of OpenRefine on Windows:
https://groups.google.com/forum/#!topic/openrefine/pE9kXmiNRqU

**To Reproduce**
Not sure if this is reproducible, someone with a Windows machine should investigate.

**Current Results**
All projects are deleted.

**Expected behavior**
CCleaner should detect the application data for OpenRefine should not be deleted by default. Perhaps this data is deleted because OpenRefine is not formally installed in the application registry, so we might want to ship proper Windows installers (such as with InnoSetup) which do this.

**Desktop:**
 - OS: Windows

**OpenRefine :**
 - All versions are probably affected.

**Comment by Nukecad** [comment]
I am a forum helper/moderator at the CCleaner forum and have investigated this issue.

CCleaner is not removing the workspace itself.
However if a user runs 'Health Check' in CCleaner then as part of the process CCleaner runs a software updater which will find if OpenRefine has a newer version available.
The user does have the option not to update any apps that the software updater finds, but by default Health Check will launch the apps own updater.

**It is the OpenRefine update which is removing the workspace, as it always does.**

For more info see my replies here on a thread on the CCleaner forum:
https://community.ccleaner.com/topic/58424-delete-good-workspace-when-updating-a-software/?tab=comments#comment-320365

It is an issue that users using Health Check may not be aware that they don't have to accept any updates found/offered, and this has been elevated to the attention of the CCleaner staff.

**Comment by wetneb** [comment]
Thanks for chiming in!

> It is the OpenRefine update which is removing the workspace, as it always does.

OpenRefine certainly does not delete the workspace when it is updated - we maintain compatibility with existing workspaces, which are read from the application data.

I do not think CCleaner is able to detect updates for OpenRefine since it is not even installed in the apps registry…

**Comment by Nukecad** [comment]
Sorry, but your own update page and backup page clearly state that a user should backup their workspace before updating.

CCleaner does not clean anything from OpenRefine by default.

The only problem we have ever seen reported with OpenRefine is that one particular thread where the user clearlt states that OpenRefine had been updated by the user running Health Check and getting 3/4 software updates.

Obviously if CCleaner had been set to somehow clear his workspace then it would have happened before.

**Comment by Nukecad** [comment]
PS the user on the CCleaner forum appears to be the same guy who posted on google groups, your link in your OP.

**Comment by Nukecad** [comment]
PPS. as it is only this one person who is reporting this then I'm wondering if the actual issue is something else.

If CCleaner was indeed clearing OpenRefine workspace then I'd expect to see a lot more reports of that.

**Comment by Nukecad** [comment]
I've been working with the affected user and they report that **this issue is resolved** and they have their workspace back.

They had run the Registry Cleaning tool in CCleaner, which seems to have deleted an entry that was redirecting from appdata\roaming to appdata\local.

So although the OpenRefine data was still there in 'Local' OpenRefine was looking in 'Roaming' for it.

They have now copied the data from Local to Roaming and it's working again for them.

I've advised not to run the Registry Cleaner (or any Registry Cleaner) again.

(PS. I wish that CCleaner would make that Reg Cleaner less prominent so people weren't tempted to use it. They have promised to do so but it's not happened yet).

Sorry for my earlier misunderstanding about the update.
