### ISSUE TITLE
Internet Explorer (IE 8) has significant issues with Refine numeric facets and others features

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#269]
_Original author: DanielJo...@gmail.com (November 30, 2010 20:26:08)_

<b>What steps will reproduce the problem?</b>
1.Run Google-Refine from the EXE or BAT file
2.select Excel spreadsheet data with 26,000 rows
3. Tell it to only imporet the first 1000
4.  It will import all of them.
5. Tell it to do a numeric facet on one column.
6. It goes into forever waiting loop.

<b>What is the expected output? What do you see instead?</b>
I would have expected to import only 1000 rows and then I would expect to see the kind of distribution information on my numeric column that I saw in the demo.

<b>What version of the product are you using? On what operating system?</b>
I am using Version 2.0 [r1836] on Windows XP service pack 3 with Java release 6

<b>Please provide any additional information below.</b>

I previously has no success with any filters on the new project window, but I have had very good success with text facets on this very same dataset.  I am using Internet Explorer 8 as my browser

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=269_
##

**Comment by thadguidry** [comment]
Closing. We won't support IE8 (or its tricks)
