### ISSUE TITLE
Browser Out of Memory Error on first screen

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#272]
_Original author: aldo.buc...@gmail.com (December 02, 2010 06:07:25)_

When loading a particular CSV file of around 100k rows, GR gets tricked into thinking that it should show the rows as records.
This causes the first state of the webapp to load with several hundred loaded rows in the grid, which subsequently kills the browser.

I could not escape this in any other way than doing some crazy browser tricks and then clicking &quot;rows&quot; instead of records.

GR: 2.0-r1836
Server: Custom Linux
Client: Mac OSX - Chrome

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=272_

**Comment by wetneb** [comment]
In 4.0, I have changed the way the records mode is turned on to only trigger when the importer created a record structure on purpose (XML / JSON) or if an operation created records later on, as suggested here https://github.com/OpenRefine/OpenRefine/issues/5661, which solves this.
