### ISSUE TITLE
"Import Project" screen misstatement

### ISSUE THREAD

**Issue by allanaaa** [OpenRefine/OpenRefine#2753]
**Describe the bug**
The "Import Project" screen incorrectly states that OpenRefine project exports can be accepted in .zip and .tar, as per https://groups.google.com/forum/#!topic/openrefine-dev/g5UUWpAQMYM 

**Expected behavior**
Should say "Locate an existing Refine project file (.tar.gz):"

**Screenshot**
![unnamed](https://user-images.githubusercontent.com/28012148/85065298-e982a080-b17a-11ea-907d-34e6f1940ee5.png)

Thanks!

**Comment by wetneb** [comment]
Congrats for finding this!

To solve this, we just need to change the UI text. Changing it in English is enough, as Weblate is able to flag outdated translations to contributors (but in many languages it should not be hard to fix it directly I guess).

**Comment by chetan-v** [comment]
I want to work on it

**Comment by thadguidry** [comment]
Sure @chetan-v !

**Comment by chetan-v** [comment]
Hi @thadguidry I am look on this issue but I cant find the source file to fix this issue

**Comment by thadguidry** [comment]
@chetan-v Whenever you see labels (text written) somewhere in OpenRefine, you can do a file content search in the repo for that bit of text written, then it will show which file contains that text.
So do a file search(locally in your IDE or in GitHub) for some of that text: `Locate an existing Refine project file`

**Comment by allanaaa** [comment]
It turns out I was mistaken about this issue: 
When you export a project archive to Google Drive, it creates a .zip. 
You can download that .zip and import it back into OpenRefine successfully. 
So, it accepts .zip and .tar.gz. 

I see that #2797 suggests there is a file-type error here; all I know is that OpenRefine successfully interprets its own exported zips as project archives.

**Comment by allanaaa** [comment]
Whoops, just saw that #2829 will make this note obsolete. Ignore!

**Comment by tfmorris** [comment]
Although named .zip by Google Drive, the contents are actually a .tar.gz. The importer lucks out because the logic tests for != .tar, so anything other than a .tar is assumed to be a .tar.gz. No unzip utility will be able to read those files.
