### ISSUE TITLE
Google Sheets uploads are limited to 26 columns (ie A-Z)

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#2760]
**Describe the bug**
From a particular file, if I try to export, I get an empty gSheet, even if I can see 500 rows in OR.
There is no error on the Java/server side, but in the browser, I get an error in the console.

Note that this happens in 25 % of the 12 projects I tried to export.

**To Reproduce**
1. Open the particular project in OR
2. Click on 'Export -> Google Sheet'
3. Open the resulting gSheet, and see no data (empty sheet)

**Current Results**
Empty gSheet.

**Expected behavior**
gSheet with the data of the project.

**Screenshots**
![image](https://user-images.githubusercontent.com/12217525/85174156-c9b6af80-b242-11ea-97d0-f1c5f8c26784.png)

**Desktop:**
 - MacOS

**OpenRefine :**
 - Version v3.4b1

**Datasets**
Here's a dataset that you can import as .CSV and then try to export to gSheets, and that will give you an empty sheet.

[DebugRep.csv.zip](https://github.com/OpenRefine/OpenRefine/files/4810544/DebugRep.csv.zip)

**Comment by thadguidry** [comment]
@antoine2711 Notice, why the `/fr/fr` and `/fr/en` in your screenshot>

**Comment by antoine2711** [comment]
@thadguidry: They are always since, since very long.

This is the same export, done with v3.3. Same result, but the console log is not the same.

![image](https://user-images.githubusercontent.com/12217525/85174897-52821b00-b244-11ea-9205-3760323169cd.png)

Regards,
   Antoine

**Comment by wetneb** [comment]
Rather than the JS console I would look at the server logs for something like this.

**Comment by antoine2711** [comment]
> Rather than the JS console I would look at the server logs for something like this.

```
15:27:47.110 [            refine_server] Starting Server bound to 'or.s-o.beaubien.qc.ca:3333' (0ms)
15:27:47.112 [            refine_server] refine.memory size: 3072M JVM Max heap: 3221225472 (2ms)
15:27:47.127 [            refine_server] Initializing context: '/' from '/Volumes/Nomade II HD/Dev/OpenRefine_Antoine2711/OpenRefine/main/webapp' (15ms)
15:27:47.228 [            refine_server] Starting autoreloading scanner...  (101ms)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Volumes/Nomade%20II%20HD/Dev/OpenRefine_Antoine2711/OpenRefine/server/target/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Volumes/Nomade%20II%20HD/Dev/OpenRefine_Antoine2711/OpenRefine/main/webapp/WEB-INF/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
15:27:49.704 [                   refine] Starting OpenRefine 3.5-beta [02209dd]... (2476ms)
15:27:49.704 [                   refine] initializing FileProjectManager with dir (0ms)
15:27:49.704 [                   refine] /Users/antoine/Library/Application Support/OpenRefine (0ms)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.core.PySystemState (file:/Volumes/Nomade%20II%20HD/Dev/OpenRefine_Antoine2711/OpenRefine/main/webapp/../../extensions/jython/module/MOD-INF/lib/jython-standalone-2.7.1.jar) to method java.io.Console.encoding()
WARNING: Please consider reporting this to the maintainers of org.python.core.PySystemState
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
15:27:57.279 [                   refine] POST /command/core/load-language (7575ms)
15:27:57.314 [                   refine] GET /command/core/get-preference (35ms)
15:27:57.351 [                   refine] POST /command/core/load-language (37ms)
15:27:57.366 [                   refine] POST /command/core/load-language (15ms)
15:27:57.438 [                   refine] POST /command/core/get-importing-configuration (72ms)
15:27:57.470 [                   refine] GET /command/core/get-all-project-tags (32ms)
15:27:57.540 [                   refine] GET /command/core/get-all-project-metadata (70ms)
15:27:57.720 [                   refine] GET /command/core/get-csrf-token (180ms)
15:27:57.779 [                   refine] GET /command/core/get-languages (59ms)
15:27:57.898 [                   refine] GET /command/core/get-version (119ms)
15:27:58.038 [                   refine] GET /command/database/saved-connection (140ms)
15:27:58.065 [                   refine] GET /command/core/get-csrf-token (27ms)
15:27:58.120 [                   refine] POST /command/core/importing-controller (55ms)
15:28:19.795 [                   refine] POST /command/core/load-language (21675ms)
15:28:19.810 [                   refine] GET /command/core/get-preference (15ms)
15:28:19.810 [                   refine] GET /command/core/get-preference (0ms)
15:28:19.816 [                   refine] POST /command/core/load-language (6ms)
15:28:19.842 [                   refine] POST /command/core/load-language (26ms)
15:28:19.847 [                   refine] POST /command/core/load-language (5ms)
15:28:19.855 [                   refine] POST /command/core/load-language (8ms)
15:28:19.900 [                   refine] GET /command/core/get-project-metadata (45ms)
15:28:20.288 [                  project] Loaded project 1898917846406 from disk in 0 sec(s) (388ms)
15:28:20.297 [                   refine] GET /command/core/get-models (9ms)
15:28:20.315 [                   refine] POST /command/core/get-all-preferences (18ms)
15:28:20.375 [                   refine] GET /command/core/get-history (60ms)
15:28:20.379 [                   refine] POST /command/core/get-rows (4ms)
15:28:20.445 [                   refine] GET /command/core/get-history (66ms)
15:28:28.089 [                   refine] GET /command/core/get-csrf-token (7644ms)
15:28:28.103 [                   refine] POST /command/gdata/upload (14ms)
15:29:29.196 [           ProjectManager] Saving all modified projects ... (61093ms)
15:29:29.375 [        project_utilities] Saved project '1898917846406' (179ms)
```
Here's my Java server log, @wetneb.

Regards,
   Antoine

**Comment by wetneb** [comment]
Thanks! Not super informative indeed.

**Comment by tfmorris** [comment]
This sounds like it could easily be related to #2306.

@antoine2711 It would be helpful if you could find a small, non-proprietary project which reproduces the issue (or identify a common pattern among all the ones which don't work).

**Comment by tfmorris** [comment]
@thadguidry @antoine2711 Could one of you please create an issue for the language requests that 404, if you haven't already done so? Let's try and make that a standard pattern when we identify bugs.

**Comment by antoine2711** [comment]
> This sounds like it could easily be related to #2306.
> 
> @antoine2711 It would be helpful if you could find a small, non-proprietary project which reproduces the issue (or identify a common pattern among all the ones which don't work).

@tfmorris: I'm now trying to create a very small dataset. It would be helpful. I'm almost there. 10 lines, 20 or so column. I will be back.

Also, even if I didn't explicitly engaged myself, @thadguidry comment is enough for me to create an issue with that (language requests that 404). I have a lot a little bugs like that that I see, but don't do Issues yet, because I'm still gathering information.

Regards,
   Antoine

**Comment by antoine2711** [comment]
@tfmorris: I've just added an Dataset to this Issue. It's a CSV, with 4 lines.

Regards,
   Antoine

**Comment by tfmorris** [comment]
> @tfmorris: I've just added an Dataset to this Issue. It's a CSV, with 4 lines.

Thank you. I've got my dev environment set up with Google secrets and can reproduce the problem.

An error is being returned, but apparently not being shown to the user:

```
com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
POST https://sheets.googleapis.com/v4/spreadsheets/1uGVSlDg87vZWMlEDmStE0PDGSQZfcRWYf5B1X9e8KEE:batchUpdate
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Invalid requests[0].appendCells: Attempting to write column: 26, beyond the last requested column of: 25",
    "reason" : "badRequest"
  } ],
  "message" : "Invalid requests[0].appendCells: Attempting to write column: 26, beyond the last requested column of: 25",
  "status" : "INVALID_ARGUMENT"
}


```
