### ISSUE TITLE
Editing preferences in another language doesn't show i18n strings

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#2765]
**Describe the bug**
If I go to the « Préférences » window, with the French language selected, I get the raw i18n codes.

**To Reproduce**
1. Set OR’s language to something else than English
2. Go into the « Preferences » window.
3. See error of bad texts.

**Current Results**
We see the i18n codes strings.

**Expected behavior**
Seeing the text in the localized language.

**Screenshots**
![image](https://user-images.githubusercontent.com/12217525/85208140-f67acd80-b2fb-11ea-8017-445a3b492ffb.png)

**Desktop:**
- Mac X.14, Chrome

**OpenRefine :**
 - Version v3.3, v3.4b1, v3.5-SNAPSHOT

**Comment by thadguidry** [comment]
Seeing **what** text?  The values? keys? both? :-)  Can you highlight what you mean in another screenshot?  Where's the **error** you mention in your screenshot?

**Comment by antoine2711** [comment]
> Seeing **what** text? The values? keys? both? :-) Can you highlight what you mean in another screenshot? Where's the **error** you mention in your screenshot?

@thadguidry: I edited my screenshot. It is more obvious now.

Regards,
   Antoine
