### ISSUE TITLE
Improve error handling for JSON Import during Create Project

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#2770]
Attempting to import invalid JSON leaves the UI in an inconsistent state.

### To Reproduce
1. Import this data from the clipboard:
```
[
{"foo":NaN},
{"bar":Infinity}
]
```
2. Select "JSON Files" for "Parse data as..." 
1. Note that the preview doesn't show any data except for the JSON delimiters
1. Click on `{}` and note the error "Non-standard token 'NaN': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow"
1. Dismiss the error alert dialog 
1. Note that the screen continues to show spinner with "Updating preview..."

### Expected behavior

* The "Updating Preview..." spinner should be dismissed on error (or when the error dialog is dismissed)
* The parse error should be shown immediately without the user having to select a record

### Versions
- Browser Version: Chrome 83
- OpenRefine  3.4-SNAPSHOT (HEAD of current master)

**Comment by WaltonG** [comment]
@antoine2711 I would like to work on this issue
