### ISSUE TITLE
Simple preference to control the facet width

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#2771]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
I want to be able to change the width of the facet panel (left one).
~~`ui.toolPanelWidth=300`~~ or `ui.toolPanelWidth=500`, at the user’s will.
**Changed to `ui.facetsHistoryPanelWidth`**.

**Describe the solution you'd like**
A simple preference that controls the width of the panel.

**Describe alternatives you've considered**
Go into the console and play with JS.

**Screens shapshots**
![image](https://user-images.githubusercontent.com/12217525/82875686-b6474b80-9f05-11ea-98d4-d7522bd7d559.png)

Regards,
   Antoine

**Comment by thadguidry** [comment]
@antoine2711 What does it look like if you click on the `Change` link in the top right of the facet? Does the expression display also stretch horizontally with the facet?

**Comment by antoine2711** [comment]
> @antoine2711 What does it look like if you click on the blue `change` link in the top right of the facet? Does the expression display also stretch horizontally with the facet?

![image](https://user-images.githubusercontent.com/12217525/85210256-714be480-b30c-11ea-8eee-04b4ccc36780.png)

After « cancel »:
![image](https://user-images.githubusercontent.com/12217525/85210264-7e68d380-b30c-11ea-9ea1-fea3aaf74fb1.png)

Firefox:
![image](https://user-images.githubusercontent.com/12217525/85210287-abb58180-b30c-11ea-9ee4-1dfc4ca28595.png)

@thadguidry: as far as I see, everything is normal. Chrome + Firefox. 

Regards,
   Antoine

**Comment by antoine2711** [comment]
> @antoine2711 What does it look like if you click on the blue `change` link in the top right of the facet? Does the expression display also stretch horizontally with the facet?

Yes @thadguidry. It is always full width.

![image](https://user-images.githubusercontent.com/12217525/85210644-b45b8700-b30f-11ea-8ba2-66e21a970176.png)

Regards,
   Antoine
