### ISSUE TITLE
Google Sheets exporter uploads multiple copies of rows

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#2786]
I suspect I fixed this in #2784, but recording it so that I remember to check.

When uploading a project with ~4,000 rows, I ended up with ~20,000 rows in Google Sheets, I suspect because it's not clearing upload batches, so every 1000 rows results in another duplicate upload.

**Comment by tfmorris** [comment]
I just tested this on the branch for #2784 and confirmed that that fixes it.

**Comment by wetneb** [comment]
Closed by #2784.
