### ISSUE TITLE
Reconciled columns not being draggable to item inputs in Wikidata schema

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2803]
**Describe the bug**

In some situations, reconciled columns cannot be dragged and dropped to inputs that expect Wikidata entities.

**To Reproduce**
The exact steps are not clear to me, but this can be observed in the following screencast at 40:00:
https://www.twitch.tv/videos/659297903

**Desktop:**
 - OS: Windows
 - Browser Version: Firefox
 - JRE or JDK Version: 

**OpenRefine :**
 - Version 3.3

**Comment by camelCaseNick** [comment]
Just recently I had a similar issue. It seemed to be the case, that https://github.com/OpenRefine/OpenRefine/blob/master/extensions/wikidata/module/scripts/dialogs/schema-alignment-dialog.js#L109 was executed before https://github.com/OpenRefine/OpenRefine/blob/master/extensions/wikidata/module/scripts/dialogs/schema-alignment-dialog.js#L132.
I was able to reproduce it multiple times with OpenRefine 3.2 and 3.3. After in the project the `_reconService` was properly initialized however, the problem disappeared mystically.
