### ISSUE TITLE
Prompt user for recon service when applying reconciliation judgments to unreconciled column

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2819]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
If you apply reconciliation judgment actions to an unreconciled column (such as "Create a new item for each cell"), the cells will be marked as reconciled to a null service. I cannot think of a use case where this is the desired outcome.

**Describe the solution you'd like**
If the user uses a judgment action on a column which does not have a `ReconConfig` in its column metadata, then the UI should prompt them to select a service just like the "Use values as identifiers" operation does.

**Describe alternatives you've considered**
None.

**Additional context**
As far as the backend is concerned, this affects  `ReconJudgeSimilarCellsOperation` and `ReconMarkNewTopicsOperation`.

**Comment by MariaAngella** [comment]
I'm Maria Angella, an Outreachy participant willing and excited to work on this issue.
Kindly assign me this task for this period.
Thank you

**Comment by wetneb** [comment]
Duplicate of #4985.
