### ISSUE TITLE
RDF N-Triples import fails with noSuchMethod error

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#2824]
This is probably a regression introduced by recent dependency updates:

```
org.apache.jena.ext.com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: org.apache.commons.codec.digest.MurmurHash3.hash128x64([B)[J
	at org.apache.jena.ext.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at org.apache.jena.ext.com.google.common.cache.LocalCache.get(LocalCache.java:3943)
	at org.apache.jena.ext.com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4865)
	at org.apache.jena.atlas.lib.cache.CacheGuava.getOrFill(CacheGuava.java:58)
	at org.apache.jena.riot.lang.BlankNodeAllocatorHash.alloc(BlankNodeAllocatorHash.java:99)
```

### To Reproduce

Use https://researchworks.oclc.org/researchdata/fast/FASTTopical.nt.zip to create a new project.

The preview never renders and the stack trace shows on the server log.

### Comments

It looks like it's looking for Apache `commons-codec` which we've included at various points in the past, but don't currently. Not sure if it's Jena's packaging that's messed up or the way we're picking which dependencies to include.

**Comment by tfmorris** [comment]
We should test 3.4-beta1 to see if the problem exists there too or just on `master`.

**Comment by wetneb** [comment]
Bug is present in master, not in 3.4, so it is indeed probably due to dependency updates.

**Comment by xsfang** [comment]
I also have this exception. I am using 3.16.0. Can it be solved by using 3.9.0?

**Comment by wetneb** [comment]
@xsfang apparently it did solve the issue in our case, yes.

**Comment by xsfang** [comment]
@wetneb Thank you very much for your reply. I move back to use Jena 3.9.0 and it works! Adding commons.codec package possibly can also solve the problem. I have not tried.

**Comment by tfmorris** [comment]
@xsfang Can you clarify which version of OpenRefine you are seeing this error with?

**Comment by xsfang** [comment]
Sure. I was using Jena 3.16.0. It is the latest version now.
