### ISSUE TITLE
Attempting to edit a cell causes js error in Internet Explorer

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#283]
_Original author: mvbroc...@gmail.com (December 14, 2010 16:38:15)_

<b>What steps will reproduce the problem?</b>
1. Open Google Refine
2. Load a dataset
3. Click &quot;Edit&quot; in a cell.
4. View error console.

<b>What is the expected output? What do you see instead?</b>
Should see cell edit dialog, instead get a js error: &quot;Not Implemented&quot;, cell-ui.js, line 460, char 5

<b>What version of the product are you using? On what operating system?</b>
Google Refine 2.0
Windows 7
Internet Explorer 8.0

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=283_

**Comment by thadguidry** [comment]
Browsers have been updated significantly now in 2018.  Closing.
