### ISSUE TITLE
404 on /fr/fr.json during Project Open

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#2835]
**Describe the bug**
When loading a project, in the console, if you choose a userLang different than `en`, you get two error lines, `
Failed to load resource: the server responded with a status of 404 (Not Found)` and `:3333/fr/en.json:1 Failed to load resource: the server responded with a status of 404 (Not Found)`

**To Reproduce**
1. Choose another language than english
2. Load a project
3. Open JS Console

**Current Results**
Note that in english, you have just ONE error line for `EN`.

**Screenshots**
![image](https://user-images.githubusercontent.com/12217525/85959399-4ac02600-b96a-11ea-844f-1cdab0b2916a.png)

**Desktop:**
 - OS: MacOS X.14.6
 - Browser Version: Chrome latest
 - `usarLang` = '`fr`'

**OpenRefine :**
 - Version v3.5 (master)

**Comment by tfmorris** [comment]
A cursory look at the call stack indicates this is a bug in the database extension.

**Comment by wetneb** [comment]
Closed by #2847.
