### ISSUE TITLE
Creating a project from a URL - HTTP errors are ignored

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#2837]
**Describe the bug**
OpenRefine does not show HTTP errors when creating a project from a URL.
Instead it acts like it downloaded successfully but there is nothing shown in the preview data grid.

**To Reproduce**
1. Create new project from URL
`https://download.data.world/file_download/associatedpress/covid-impact-survey-public-data/COVID_W2_toplines.zip`
2. Click on Next>>
3. No error is given
4.  Preview data grid screen shows as if download completed successfully but is blank

**Current Results**
Preview data grid screen is blank. No HTTP error is shown to user

**Expected behavior**
Should not have gone to preview data grid screen because a 401 error was returned in the response.

**Screenshots**

![image](https://user-images.githubusercontent.com/986438/85963283-7fd47480-b97a-11ea-94d2-e96666a69677.png)
![image](https://user-images.githubusercontent.com/986438/85963305-91b61780-b97a-11ea-86d8-117a9a87d368.png)

**Desktop:**
 - OS: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: JDK8

**OpenRefine :**
 - Version:  OpenRefine (trunk)

**Comment by tfmorris** [comment]
I noticed this the other day and thought I created an issue, but can't find it. The status is being fetched, but then never checked.

https://github.com/OpenRefine/OpenRefine/blob/4b146acc6ef8a4f41168824db0967e24d7efb45c/main/src/com/google/refine/importing/ImportingUtilities.java#L311-L317

This is not limited to 401. Any non-2xx status will end up using the contents of the error page without warning the user.

**Comment by chetan-v** [comment]
I want to do that

**Comment by chetan-v** [comment]
I want to do that

**Comment by urvashigupta7** [comment]
Hi, I would like to work on this issue.

**Comment by wetneb** [comment]
@urvashigupta7 fantastic! Let us know if you need any help.
