### ISSUE TITLE
XML files not guessed with .txt extension

### ISSUE THREAD

**Issue by chetan-v** [OpenRefine/OpenRefine#2858]
**Describe the bug**
XML file not be guessed when we change the extension. 

**To Reproduce**
1.  Go to 'OpenRifine'
2. Click on 'Choose files'
4. choose the XML file with .txt extension. [test.txt](https://gist.github.com/djangofan/3186223/raw/ee3840f937e745d5683b046a85cc4a0337e18428/test.xml)

**Current Results**
When I use XML file with .txt Extension :-

![Screenshot from 2020-07-01 20-57-16](https://user-images.githubusercontent.com/63091769/86262434-7f87e380-bbdd-11ea-9211-f81b25f26b6b.png)

**Expected behavior**

It will work with or without or any extensions.

**Desktop:**
 - OS: Ubuntu 18.04
 - Browser Version: chromium
 - JRE or JDK Version:  JDK version "11.0.7" 2020-04-14

**Comment by wetneb** [comment]
Looking at your screenshots, you are trying to load a PDF file, not an XML file.

**Comment by chetan-v** [comment]
I make changes in the Issue
Please check

**Comment by thadguidry** [comment]
@chetan-v It's also helpful to include the Test File that you saw the issue with (attach the .txt file in your first comment on this issue).  Then if you would like to work on this, we can assign this issue to you.

**Comment by chetan-v** [comment]
> @chetan-v Generally, when you make a new issue that is file related, it is also helpful to include that Test File that you saw the issue with (attach the .txt file in your first comment on this issue). Then if you would like to work on this, we can assign this issue to you.

I got it.
Yes, I want to do that

**Comment by tfmorris** [comment]
This is the same bug as #2820, but I suspect you knew that. When you upload your test file, please make sure that it has the name that you intend. Although the anchor text says `Test.txt` the actual filename is `test.xml` so it needs to be renamed when downloaded.

**Comment by chetan-v** [comment]
> This is the same bug as #2820, but I suspect you knew that. When you upload your test file, please make sure that it has the name that you intend. Although the anchor text says `Test.txt` the actual filename is `test.xml` so it needs to be renamed when downloaded.

 I think, I should close this Issue. it has no meaning Now.
