### ISSUE TITLE
Can not log out of wikidata if my wikidata session has already ended

### ISSUE THREAD

**Issue by addshore** [OpenRefine/OpenRefine#2873]
**Describe the bug**

If I am logged into wikidata, but my session expires or I get logged out for some reason I can not use the log out button in the app.

**Current Results**

When I do click logout I see the following in the console and the app continues to think that I am logged in.

```
17:33:56.920 [                   refine] GET /command/wikidata/login (9487ms)
17:33:56.948 [                   refine] POST /command/core/get-all-preferences (28ms)
17:33:58.792 [                   refine] GET /command/core/get-csrf-token (1844ms)
17:33:58.807 [                   refine] POST /command/wikidata/login (15ms)
17:33:59.078 [      connection_mananger] [assertuserfailed] You are no longer logged in, so the action could not be completed. (271ms)
```

This is probably due to the assertuser option being used for this login call?

**Expected behaviour**

Clicking the logout button in this situation should detect that I am no longer logged in and thus allow me to re login to the app.

**Screenshots**

Stuck here in the app, can not log out

![image](https://user-images.githubusercontent.com/3308769/86486475-42ddf880-bd53-11ea-8111-c44b1d4b39b2.png)

**Desktop:**
 - OS: Windows 10
 - Browser Version: Firefox 76.0.1 (64-bit)
 - JRE or JDK Version: 
```
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**OpenRefine :**
 - Version 3.3

**Comment by wetneb** [comment]
Thanks Adam, we are honored to have you here! :) This is a good catch! We should fix that upstream, in Wikidata-Toolkit, so adding an issue there.

**Comment by addshore** [comment]
> Thanks Adam, we are honored to have you here! :) This is a good catch! We should fix that upstream, in Wikidata-Toolkit, so adding an issue there.

Aaah, WDTK is used, love it!
I've had a great first weekend of using OpenRefine! :) Thanks for the speedy fix!
