### ISSUE TITLE
Importer data type guessing description shouldn't include "dates"

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#2883]
The textual description of the text table importer option currently says "Parse cell text into numbers, dates, …" but the code doesn't actually attempt any date conversion.

Change the text to read "Attempt to parse cell text into numbers". ~~Bonus points for updating any easily fixable translations.~~

**Comment by morrme** [comment]
Hi!

I can push a change to the text as desired.

Additionally, I can remove the mention of "dates" from all but 3 of the translations, but I'm not sure I'd be able to accurately localize "Attempt to" in them. Would removing the "dates" part help?

**Comment by wetneb** [comment]
Thanks for offering to help! It is best if you only touch translations in languages where you are completely confident about your edit. Weblate will flag outdated translations to translators anyway.

**Comment by morrme** [comment]
Sure! I can confidently get rid of the term that corresponds to dates in nearly all of them, but I would not add the "Attempt to" text. 

If that won't be of much help, I can stick to the text from the original request.

**Comment by tfmorris** [comment]
Yes, please only do languages that you write fluently. I've retracted my ill-advised "bonus points" comment. :)

**Comment by morrme** [comment]
@tfmorris  I think somehow my questions were missed (or perhaps "lost in translation"? 🤣 ) so I just updated the single line per the original request.
