### ISSUE TITLE
Facet UI remains hidden when left panel set to be hidden

### ISSUE THREAD

**Issue by lisa761** [OpenRefine/OpenRefine#2891]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
When using facets with the data-table set to full width (added by #2616), the left panel does not reappear to show the facet UI. The facet happens, and the user will need to toggle the left panel back to visible to be able to see it. 

**Describe the solution you'd like**

Since we are not telling the user that it has happened in anyway (except for the table going back to the first row), the left panel should automatically reappear to show the results. We could also just send a message that tells the user to toggle the panel back to see it. Although, the former is more user-friendly.

<img width="960" alt="2020-07-06 (7)" src="https://user-images.githubusercontent.com/52909743/86592053-5639cf80-bfb0-11ea-9f49-520e91c283ea.png">

<img width="960" alt="2020-07-06 (8)" src="https://user-images.githubusercontent.com/52909743/86592056-576afc80-bfb0-11ea-9d3c-6d5dc378a8d3.png">

**Comment by thadguidry** [comment]
This comes down to how often folks would apply various facets and want to interact with the facets themselves.
And that often comes down to how messy or clean the data is originally.
Your suggestion would be a minor inconvenience for me;  The toggle is no longer a strong toggle, but only temporary.
But then currently it's a minor inconvenience for others with it being a strong toggle.

👎 Hmm, I think I prefer the way it is now, staying as a strong toggle.  I typically would keep the data table wide, and apply various different filters (custom text facets) while scrolling up and down to check things.  I would have to click the toggle to close it over and over.  Only when I really would want to interact with some Facets would I toggle it open.

We'll probably need some more votes or hear more opinions.

**Comment by wetneb** [comment]
I don't see why a user would want to create a facet without either:
- looking at it to inspect the statistics it provides
- or configuring it straight away to filter rows (as in the case of the text filter)
In both cases they need to see the facet, so it makes sense to show the left panel without requiring any other action from them. So @lisa761's proposal makes perfect sense to me.

One thing to be careful about though: sometimes applying an operation creates facets in the same go (for instance reconciling does) - in that case you probably do not want to change the state of the left panel.

**Comment by thadguidry** [comment]
@wetneb We introduced the toggle for a reason (for folks that really don't need to see the Facets until they are ready to see them).  So, then I don't understand why we implemented the toggle, if we don't want to continue to give users the choice.  This issue pulls the choice or opinion out of a users hands and places it into our hands for certain operations.  Not wise or kind to our users, I think.

**Comment by lisa761** [comment]
It's not just a problem with one facet. Even clicking on the `Text Filter` does not open up any dialog box (since it's set in the left panel). It's the case with every option that opens up the UI for interaction in the left panel like `Timeline Facet`, `Word Facet` etc. (Most of the facets provided come in this category). A user might not know that they are supposed to check there.

If we do show a message somewhere, the user would repeatedly need to toggle it back on to interact with the facet. I am not sure how great a strong toggle would be in such case, since I imagine a lot of users would want to see what's happening.

**Comment by thadguidry** [comment]
@lisa761 Ah, you are talking about the modals (popup dialogs)!  Then I would say if the modals are tied to the left panel, then that probably needs to be redesigned better and enhanced so they are not tied to it.

**Comment by lisa761** [comment]
> So Lisa, how do you envision this issue getting resolved while still allowing those that want to apply Custom Text Facet and Text Filter over and over while keeping data table wide?

I think we could skip the toggle for options that have a modal dialog box. Since Text Filter and many others are in the left panel, we could perhaps make this behavior default for only those options (as the interfaces for these two are generated from different places).

**Comment by ostephens** [comment]
@thadguidry to understand the issue better-  what is the scenario where you decide to create a new facet or filter but don't want to see the result immediately?

**Comment by thadguidry** [comment]
@ostephens typing out several regex's, or contains() statements.  When the data is large, with long strings in cells, it's helpful to see as much as possible so you can filter quickly by just typing out what you see you need to filter.  That's my use case.  My alternative would be creating "several Custom Text Facet's" or constantly modifying one, which is not efficient.  Instead it would be much easier if a small GREL input box could be optionally stuck at the top of the grid (that auto expanded and shrank when you clicked in or out of it or hit ENTER) and I could just type a large Boolean and() nicely nested with my filter rules.

So as I see it, this discussion is about saving only 1 or 2 minutes of time (various clicking around or not) for users, so not a critical area for me, but only an annoyance that I think we could rethink of how we present some of our Filtering mechanisms to users, by having a Width view while still allowing a small filter input above the grid.  There's lots of wasted space sometimes depending on the users need. I've always wanted a bit more control on the **view** of OpenRefine (and perhaps we'll offer more there in the future).

**Comment by ostephens** [comment]
That makes sense @thadguidry but feels like a substantially different issue to the problem @lisa761 is reporting here?

I can agree we might re-think the UI. But while the UI is as it is, I think we have to show the panel when a new facet or filter is added - otherwise we are basically doing things that are invisible to the user. 

I think we have to solve the current problem as Lisa suggests.
Changing the UI to the extent you suggest is a big job and not really part of fixing the panel toggling behaviour IMO

**Comment by wetneb** [comment]
> I want to see the result immediately, in full width data grid.

You want to see the result of what exactly? Clicking on "Text filter" will not make any change to the grid by itself - you need to input things in the text filter first, and for that you need to see the text filter.

Perhaps you could make a small video demonstrating how the current behaviour (not showing the facet panel when creating a new facet) is useful to you?

**Comment by thadguidry** [comment]
@wetneb It's fine Antonin.  I'm bowing out of this issue now.  This is not something that is super critical for me and I'll leave you to it for this current iteration to address usability issues that Lisa brought up.  It's not ideal and it sounds like I got my points across for where I would like to see us explore better designs.  Thanks team!  Good luck on this issue @lisa761 and good eyes catching these usability issues for us!

**Comment by antoine2711** [comment]
@lisa761: good catch. I should've see that coming. But, just to be sure, we are talking about showing the tool panel (facet panel) when a new panel is created, but not when the choices of a facet changes, right?

Regards,
   Antoine

**Comment by lisa761** [comment]
@antoine2711 Yes I think the problem is with newly created facets and other operations tied to the left panel. I am not sure what you mean by changing the choice of facets though?

**Comment by antoine2711** [comment]
A bug has been found and a fix is proposed.
