### ISSUE TITLE
Wikidata password sent in cleartext with every OpenRefine request

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#2902]
It appears that the Wikidata extension saves passwords unencrypted in a cookie which is sent in the clear with every request (since we don't use HTTPS).

`Cookie: host=.butterfly; wb-username=tfmorris1; wb-password=xxxx`

This is unacceptable from a security point of view and the user isn't warned of the exposure.

**Comment by wetneb** [comment]
That is curious, I did not realize that cookies were used at all since we were still in a single-user setting? @afkbrb I assume this was just a leftover of your plan to introduce multi-user support?

**Comment by afkbrb** [comment]
I checked the code and the tested again, the  `wb-username` and `wb-password` are not used and set in the latest version of the code. The cookies must be set when you test a previous version. That version was not merged into the master branch, so only both you and me are affected. I think simply delete the cookies manually should solve the problem.

**Comment by tfmorris** [comment]
OK, I'll try deleting the cookies and see if they return.
