### ISSUE TITLE
Form to add a reconciliation service should be submitted when pressing Enter in the endpoint input

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2905]
**Describe the bug**

Open the dialog to add a new reconciliation service using its endpoint. Type the URL and press Enter.

**Current Results**
Nothing happens.

**Expected behavior**
The form should be submitted.

**Desktop:**
 - OS: Linux
 - Browser Version: Firefox 68.9
 - JRE or JDK Version: 11

**OpenRefine :**
 - Version 3.4 beta2

**Comment by urvashigupta7** [comment]
Hi..I would like to work on this issue 😄

**Comment by wetneb** [comment]
Fabulous! The floor is yours :)
