### ISSUE TITLE
Service remove button click event propagates to underlying element 

### ISSUE THREAD

**Issue by VDK** [OpenRefine/OpenRefine#2910]
**Describe the bug**

When trying to remove a service the service gets selected 
**To Reproduce**
1. Reconcile ➡ Start reconcile... 
2. Click little cross symbol 
3. Service start loading 

**Current Results**
On selecting the cross precisely (it's small) it is still the underlying element that responds. When reloading the page the old service has been removed. 

**Expected behavior**
The service is removed, not loaded 

**Desktop:**
 - OS: Windows 
 - Browser Version: Chrome 
 

**OpenRefine :**
 - Version 
OpenRefine 3.4 beta 2

**Comment by sonukushwaha403** [comment]
I want to work on it

**Comment by wetneb** [comment]
Thanks! Looking forward to your PR.

**Comment by Gomaa** [comment]
Hi there,
Can I get this issue assigned to me?

**Comment by tfmorris** [comment]
It's yours now. Good luck!
