### ISSUE TITLE
Toggle on services dialog after adding standard services does not work

### ISSUE THREAD

**Issue by urvashigupta7** [OpenRefine/OpenRefine#2913]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/41363633/87054421-b59e1680-c220-11ea-9941-d95f4e6f723e.gif)

Before adding any standard service toggling service dialog works fine. But, after adding service it doesn't.

**Comment by wetneb** [comment]
This is a much better explanation of this issue: #1658
