### ISSUE TITLE
SchemaAlignmentDialog - Uncaught TypeError: Cannot read property 'suggest' of undefined

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#2920]
When attempting to load this particular project, which was apparently reconciled against Wikidata, the loading spinner stays up forever and the Javascript console shows that it's trying to reference a null reconciliation service variable:

    endpoint = this._reconService.suggest.entity;

```
project-bundle.js:47051 Uncaught TypeError: Cannot read property 'suggest' of undefined
    at Object.SchemaAlignmentDialog._initField (project-bundle.js:47051)
    at Object.SchemaAlignmentDialog._addItem (project-bundle.js:46463)
    at Object.SchemaAlignmentDialog._reset (project-bundle.js:46358)
    at Object.SchemaAlignmentDialog.setUpTabs (project-bundle.js:46274)
    at Array.<anonymous> (project-bundle.js:47432)
```

Reloading the page is successful, so it's apparently a race condition with something not properly synchronized, but with this particular project it has failed 3 out of 3 times on the first load attempt.

### Current Results

Uncaught TypeError: Cannot read property 'suggest' of undefined
    at Object.SchemaAlignmentDialog._initField (project-bundle.js:47051)
    at Object.SchemaAlignmentDialog._addItem (project-bundle.js:46463)
    at Object.SchemaAlignmentDialog._reset (project-bundle.js:46358)
    at Object.SchemaAlignmentDialog.setUpTabs (project-bundle.js:46274)
    at Array.<anonymous> (project-bundle.js:47432)
    at project-bundle.js:31080
    at project-bundle.js:31057
    at project-bundle.js:33638
    at Object.<anonymous> (project-bundle.js:31676)
    at fire (project-bundle.js:3121)
SchemaAlignmentDialog._initField @ project-bundle.js:47051
SchemaAlignmentDialog._addItem @ project-bundle.js:46463
SchemaAlignmentDialog._reset @ project-bundle.js:46358
SchemaAlignmentDialog.setUpTabs @ project-bundle.js:46274
(anonymous) @ project-bundle.js:47432
(anonymous) @ project-bundle.js:31080
(anonymous) @ project-bundle.js:31057
(anonymous) @ project-bundle.js:33638
(anonymous) @ project-bundle.js:31676
fire @ project-bundle.js:3121
fireWith @ project-bundle.js:3233
done @ project-bundle.js:9277
callback @ project-bundle.js:9687
XMLHttpRequest.send (async)
(anonymous) @ VM745:1
send @ project-bundle.js:9633
ajax @ project-bundle.js:9178
next @ project-bundle.js:31670
Ajax.chainGetJSON @ project-bundle.js:31684
HistoryPanel.update @ project-bundle.js:33631
(anonymous) @ project-bundle.js:31062
(anonymous) @ project-bundle.js:31057
Refine.update @ project-bundle.js:31122
ProcessPanel._runOnDones @ project-bundle.js:34154
ProcessPanel._render @ project-bundle.js:34123
(anonymous) @ project-bundle.js:33991
(anonymous) @ project-bundle.js:31676
fire @ project-bundle.js:3121
fireWith @ project-bundle.js:3233
done @ project-bundle.js:9277
callback @ project-bundle.js:9687
XMLHttpRequest.send (async)
(anonymous) @ VM745:1
send @ project-bundle.js:9633
ajax @ project-bundle.js:9178
next @ project-bundle.js:31670
Ajax.chainGetJSON @ project-bundle.js:31684
ProcessPanel.update @ project-bundle.js:33987
ProcessPanel @ project-bundle.js:33964
initializeUI @ project-bundle.js:30914
(anonymous) @ project-bundle.js:31350
(anonymous) @ project-bundle.js:30981
fire @ project-bundle.js:3121
fireWith @ project-bundle.js:3233
done @ project-bundle.js:9277
callback @ project-bundle.js:9687
XMLHttpRequest.send (async)
(anonymous) @ VM745:1
send @ project-bundle.js:9633
ajax @ project-bundle.js:9178
jQuery.<computed> @ project-bundle.js:9324
(anonymous) @ project-bundle.js:30969
fire @ project-bundle.js:3121
fireWith @ project-bundle.js:3233
done @ project-bundle.js:9277
callback @ project-bundle.js:9687
XMLHttpRequest.send (async)
(anonymous) @ VM745:1
send @ project-bundle.js:9633
ajax @ project-bundle.js:9178
jQuery.<computed> @ project-bundle.js:9324
getJSON @ project-bundle.js:9307
(anonymous) @ project-bundle.js:30955
fire @ project-bundle.js:3121
fireWith @ project-bundle.js:3233
done @ project-bundle.js:9277
callback @ project-bundle.js:9687
XMLHttpRequest.send (async)
(anonymous) @ VM745:1
send @ project-bundle.js:9633
ajax @ project-bundle.js:9178
jQuery.<computed> @ project-bundle.js:9324
getJSON @ project-bundle.js:9307
Refine.reinitializeProjectData @ project-bundle.js:30945
onLoad @ project-bundle.js:31348
fire @ project-bundle.js:3121
fireWith @ project-bundle.js:3233
ready @ project-bundle.js:3445
completed @ project-bundle.js:3476

### Expected behavior

Project loads successfully.

### Screenshots
![Screen Shot 2020-07-11 at 7 58 03 PM](https://user-images.githubusercontent.com/82178/87236010-515e8c80-c3b1-11ea-9d59-b6585be1571a.png)

### Versions
- OS: macOS Mojave
- Browser Version: Chrome 83
- java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
- OpenRefine 3.5-SNAPSHOT

**Comment by tfmorris** [comment]
The project also takes over 5 seconds to fully load even though it's only 172 rows and is warm and in-memory in the server. The last ~1.5-2 seconds are ~100 calls to the Wikidata endpoint of the form:

`https://www.wikidata.org/w/api.php?callback=jQuery111105041745081701958_1594515851456&action=wbformatvalue&generate=text%2Fhtml&datavalue=%7B%22value%22%3A%7B%22language%22%3A%22en%22%2C%22text%22%3A%22Jose+Alfredo+Moron%22%7D%2C%22type%22%3A%22monolingualtext%22%7D&options=%7B%22lang%22%3A%22en%22%7D&format=json&datatype=monolingualtext&_=1594515851457
`

**Comment by wetneb** [comment]
Seems related to #2872. 
Concerning the calls to Wikidata, these should normally only be used by the preview tab of the Wikidata extension, so it should not block the rest of the UI: if it is, then we need to change the structure of callbacks to make sure this is happening in the background.
Unfortunately there is no Wikidata API to format many values at once. The rendered values are cached (if I remember correctly) in the frontend.

**Comment by tfmorris** [comment]
This area of the code has changed substantially and there are much more active users of Wikidata than me, so if they're not complaining, I'm going to assume that this is no longer an issue.
