### ISSUE TITLE
XPath support for creating columns from XML would be nice

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#293]
_Original author: cv4...@gmail.com (December 22, 2010 10:36:50)_

I keep finding that Refine's heuristics for grabbing data from XML don't match my needs and lack the control I'd like to have.

To me it would seem very useful to have XPath support for XML data, so one could specify one XPath pointing to the XML elements that make up the records and another array of XPaths pointing to the fields inside those records.

That may not be quite as automatic as the current approach. But it would mean I could feed data directly into Refine without a need for preprocessing.

I also suspect that this approach will provide a workable solution for other situations in which data has to be extracted from a web page, say (e.g. case 56).

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=293_

**Comment by thadguidry** [comment]
We have a nice XML importer with UI selector capability.  Closing this issue.
If folks want/need an Xpath expression box on the importer itself, they can open a new issue for that.
