### ISSUE TITLE
Default Windows workspace directory got changed

### ISSUE THREAD

**Issue by allanaaa** [OpenRefine/OpenRefine#2936]
**Describe the bug**
In the process of changing a number of installation settings for OpenRefine (including changing JAVA_HOME, installing Java, installing JDK, changing the workspace directory in the .ini file and then removing it, changing memory, etc.), OpenRefine's default behaviour changed from storing my workspace directory in
`C:\Users\(user id)\AppData\Local\OpenRefine`
(where it had been since I installed it)
to 
`C:\Users\(user id)\AppData\Roaming\OpenRefine`
(where it found nothing).

Specifically, I:
- installed OpenRefine (a long time ago)
- created lots of projects in the default Local directory (a long time ago)
- changed the workspace directory using the .ini file (last week)
- deleted that line in the .ini file (last week)
- started OpenRefine (yesterday) and discovered that it was using Roaming, and thus not finding any projects.

For the time being I am manually setting the .ini file:
`-Drefine.data_dir=C:\Users\Allana\AppData\Local\OpenRefine`

**To Reproduce**
I am not sure which change I made caused this issue, since I made a number of changes last week. (I did not uninstall or reinstall OpenRefine itself.)
I think generally knowing when OpenRefine uses Local and when it uses Roaming will help narrow it down. 

**Expected behavior**
OpenRefine should always default back to the same workspace directory where no manual settings exist, no matter what changes happen later.

**Desktop:**
 - OS: Windows 10
 - Browser Version: Firefox 78.0.2
 - JRE 1.8.0_251 

**OpenRefine:**
 - Version 3.4 beta 2

**Log**
> 11:44:05.950 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
> 11:44:05.961 [            refine_server] Initializing context: '/' from 'D:\Program Files\openrefine-3.4-beta2\webapp' (11ms)
> 11:44:09.549 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (3588ms)
> 11:44:09.551 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (2ms)
> SLF4J: Class path contains multiple SLF4J bindings.
> SLF4J: Found binding in [jar:file:/D:/Program%20Files/openrefine-3.4-beta2/server/target/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: Found binding in [jar:file:/D:/Program%20Files/openrefine-3.4-beta2/webapp/WEB-INF/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
> SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
> 11:44:09.718 [                   refine] Starting OpenRefine 3.4-beta2 [c67e13b]... (167ms)
> 11:44:09.718 [                   refine] initializing FileProjectManager with dir (0ms)
> 11:44:09.719 [                   refine] C:\Users\Allana\AppData\Roaming\OpenRefine (1ms)

**Comment by mmaithani** [comment]
uninstall the java and openrefine once and install again both

**Comment by VojtechDostal** [comment]
My workspace directory got lost during the change of memory allocation settings too. I cannot find any of my projects anymore :(

**Comment by tfmorris** [comment]
Sorry this took so long to triage. At this distance in time, I'm not sure we'll be able to offer much useful analysis, it's possible that the default data directory changed from Local to Roaming over the years, but we usually put a lot of effort into because compatibility, including searching for old Gridworks and Google Refine data directories.

The Roaming profile is the right place for OpenRefine data, I believe, and that's what it currently uses as the default, so I'd suggest backing up and moving your directory there when it's convenient so that it's aligned with the current defaults. 

I'm going to close this, but if you think there's something which could be improved please feel free to reopen it.
