### ISSUE TITLE
Error in response: Missing or invalid csrf_token parameter when accessing OpenRefine through API

### ISSUE THREAD

**Issue by asyrul21** [OpenRefine/OpenRefine#2957]
Hi OpenRefine community,

I would like to run OpenRefine in the background and communicate with it from my app through the OpenRefine API. So far, I followed instructions outlines here: [OpenRefine API](https://github.com/OpenRefine/OpenRefine/wiki/OpenRefine-API)

I'm running Open Refine version 3.3, and attempted to upload my files through the API both from Postman and my Python App and got the response error '**Missing or invalid csrf_token parameter**'. I also found another [issue](https://github.com/OpenRefine/OpenRefine/issues/2239) raised regarding the same problem, but it was already closed.

My postman request looks like this:

![Screenshot 2020-07-18 at 15 24 55](https://user-images.githubusercontent.com/29390954/87854773-19ed6400-c90c-11ea-807f-ea1e215b1b25.png)

### Expected Behavior

I would expect the request to upload my file(s) and create a new project, as described in the documentation.

### Versions
 - Operating System: Mac OS X cataline
 - Browser Version: Safari 13
 - JRE or JDK Version: 13
 - OpenRefine: 3.3

**Comment by wetneb** [comment]
Hi @asyrul21, you will need to retrieve a CSRF token before making the request with `GET command/core/get-csrf-token`.
See https://github.com/OpenRefine/OpenRefine/wiki/Changes-for-3.3#csrf-protection-changes for more details about this.
Because this is not a bug and working as intended, I will close this, but feel free to comment back if you need more info. In general, questions like this should go to the user or developer mailing lists.

**Comment by tfmorris** [comment]
I've updated the wiki with a link to the CSRF docs and a warning that the API is internal-only and subject to change at any time (as you've just discovered).

**Comment by asyrul21** [comment]
Dear @tfmorris and @wetneb,

Thank you for your prompt response and action. I have managed to complete the POST request successfully.

Thanks!

**Comment by NamanGuptacs** [comment]
Hi @asyrul21 

Will you please tell me how you have passed the csrf_token in python code

Thanks in advance

**Comment by nguyenducduc2110** [comment]
I'm running Open Refine version  and attempted to upload my files through the API both from Postman and my Python App and got the response error 'Missing or invalid csrf_token parameter'.

My postman request looks like this:
curl --location 'http://localhost:3333/command/core/create-project-from-upload' \
--header 'Cookie: host=.butterfly; host=.butterfly' \
--form 'csrf_token="l0IpIxzMUX1fn8TAyjKEzfze940gu2pJ"' \
--form 'project-file=@"/D:/compare_data.csv"' \
--form 'project-name="EVN"'
