### ISSUE TITLE
Refactor Importer APIs to support filename and archive name cleanly

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#2963]
In 818e139b430ecb6afe89c3b1c68176d0b4875eef the `NotImplementedException` throwing behavior of the methods in the base class got [removed](https://github.com/OpenRefine/OpenRefine/commit/818e139b430ecb6afe89c3b1c68176d0b4875eef#diff-972882453affea1078cdd88bbc4aef18L148-R151) so that they're now silent no-ops if someone calls them for a subclass where they are not implemented. This is unsafe and misleading behavior that just cost me a good chunk of time to track down.

It looks like TreeImportingParserBase suffers from the same issue: https://github.com/OpenRefine/OpenRefine/commit/818e139b430ecb6afe89c3b1c68176d0b4875eef#diff-fc818390bcd00535a45c7ef1f5dfc8d2L177-R178

**Comment by tfmorris** [comment]
OMG, this is such a mess! Not only did the `NotImplementedException`s get removed, but the subclasses are now explicitly calling these methods for the new side effect code that got place there. This has polluted the entire `Importer` class hierarchy and when I restore some of the previous behavior, 95 tests fail. Ugh!! What a nightmare...

**Comment by thadguidry** [comment]
I guess we need a miracle...I think he goes by the name of Tom? :-)

**Comment by wetneb** [comment]
Yes the architecture of our importers is not ideal at the moment. Also we rely on the CSV importer in many tests to create a test project, which we should not do (that is my fault). I am working on this architecture in the Spark migration and I have removed the dependency to the CSV importer in tests, so perhaps it is not worth duplicating this effort in 3.x?

**Comment by tfmorris** [comment]
These issues are orthogonal to use of the CSV importer to create test cases.

After ripping out all this code, all the tests pass again, so I guess the metadata functionality has zero test coverage. :( 

As part of the investigation, I also realized that the recent addition of optionally saving archive filename broke the public importer API with an incompatible change which is uncool, so that will need to be redone.

**Comment by tfmorris** [comment]
It looks like this mess started with #1055, which was merged without review, and has snowballed from there. It's too late to restore compatibility for pre-2015 era importers, but we can at least a) not break current importers for 3.5 and b) try to create something which can be stabilized going forward.
