### ISSUE TITLE
Wikidata Edits very slow, sometimes not responding at all

### ISSUE THREAD

**Issue by mshd** [OpenRefine/OpenRefine#2975]
### To Reproduce
I often have problems uploading Wikidata Edit statements, sometimes it just works, other times it doesn't do anything, regardless the amount of edits

I don't know if that log is related
```
00:08:57.267 [..baseapi.WbEditingAction] [maxlag] Waiting for all: 18.083333333333 seconds lagged. -- pausing for 194581 milliseconds. (453ms)
00:08:57.268 [..baseapi.WbEditingAction] Gave up after several retries. Last error was: org.wikidata.wdtk.wikibaseapi.apierrors.MaxlagErrorException: [maxlag] Waiting for all: 18.083333333333 seconds lagged. (1ms)
00:08:57.268 [..ting.EditBatchProcessor] MediaWiki error while editing [maxlag]: Waiting for all: 18.083333333333 seconds lagged. (0ms)
```
it just stays like this
```
Perform Wikibase edits
0% complete
```

### Explanation
I don't know it's a bug, because it does work sometimes, it seems like there's a connection problem sometimes. It would be nice if openRefine could timeout, and maybe try again...

### Versions
 - Operating System:  Ubuntu 18.04
 - Browser Version: Firefox 6
 - JRE or JDK Version: 
 - OpenRefine: =OpenRefine 3.4 Beta -->

### See also
 #2061

**Comment by wetneb** [comment]
Hi @mshd, this is just because Wikidata is overloaded and is asking OpenRefine not to do any edits. We should just get better at reporting this to the user.

**Comment by mshd** [comment]
Yes, great that makes sense, is there any page where one can see the usage of the Wikidata server, so maybe I can find a time spot where less people are active.

**Comment by wetneb** [comment]
You can have a look at this:
https://grafana.wikimedia.org/d/000000156/wikidata-dispatch?orgId=1&refresh=1m&fullscreen&panelId=22&from=now-6h&to=now&var-dispatchServerDatasource=eqiad%20prometheus%2Fops&var-dispatchServer=mwmaint1002
When the bars go above the red line, OpenRefine edits will not go through by default.

**Comment by wetneb** [comment]
We have added the possibility to set the maxlag parameter when uploading edits, so I am tentatively closing this.
