### ISSUE TITLE
Create Project > multiple files > preview: "Back" button not displaying properly

### ISSUE THREAD

**Issue by allanaaa** [OpenRefine/OpenRefine#2980]
When you start a project by loading an archive file with multiple files inside, there is a "Back" button loaded next to "Start Over" on the preview page. But the "Back" button isn't actually displaying. 

### To Reproduce
1. Create a project with a .zip or etc. 
2. Then, you see a file-selection screen.
3. Finally, the preview screen loads with a malfunctioning "Back" button.

### Screenshots
![back-button-not-loading](https://user-images.githubusercontent.com/28012148/88209242-6b556600-cc20-11ea-9c55-355864399b4a.JPG)

### Versions
3.4 beta 2
Windows 10
Firefox, and I reproduced it in Chrome

**Comment by chetan-v** [comment]
@tfmorris Can I do that
