### ISSUE TITLE
Dialog to add a reconciliation service does not open

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2990]
_Originally posted at https://github.com/wetneb/openrefine-wikibase/issues/84 by @pyrog_ 

On **Safari** Version 13.0.4 (14608.4.9.1.4), the box to add a reconciliation service don't open.
Work fine on **Chrome** and **Firefox**.

Console:
```
SyntaxError: Unexpected token '}'
(fonction anonyme) — project:74
project-bundle.js:10335

```
<img width="630" alt="Can't add a reconciliation service on Safari" src="https://user-images.githubusercontent.com/2158081/88482061-205c8b00-cf5f-11ea-99fd-3a26a0b00e79.png">

**Comment by pyrog** [comment]
![cant reconcile on Safari](https://user-images.githubusercontent.com/2158081/90138239-ff75a180-dd76-11ea-8618-3da60a3a5138.gif)

**Comment by tfmorris** [comment]
This is the offending line of code:

    <script type="text/javascript">var theProject = { id :  };</script>

On Chrome it has the project ID filled in:

    <script type="text/javascript">var theProject = { id : 2321259574266 };</script>

**Comment by Abbe98** [comment]
Is this still present? I tried to reproduce it in another Webkit browser but couldn't.

**Comment by wetneb** [comment]
Given that this is very old and that @Abbe98 could not reproduce this, let's assume this was fixed. Please reopen or comment if you think the problem is still present.
