### ISSUE TITLE
Unintended deletion of statements in Wikidata upload

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2999]
Deleting statements with a Wikidata schema is not currently supported (but it should be). In the meantime, it seems that existing schemas do generate statement deletions in some cases:

https://editgroups.toolforge.org/?tags=wbremoveclaims-remove&tool=OR

In particular, edits like this one:
https://www.wikidata.org/wiki/index.php?diff=801809908&oldid=801809730

### Expected Behavior
With the current features it supports, OpenRefine should never delete any statement during upload.

### Additional context
This could be a bug in Wikidata-Toolkit. I have not attempted to reproduce this on my side.

**Comment by tfmorris** [comment]
That edit history looks weird. The author was added 3 times and removed twice.

https://www.wikidata.org/w/index.php?title=Q59247909&action=history

**Comment by wetneb** [comment]
Those deletions were actually normal: when an item already has duplicated statements, editing it deleted those additional statements. This is no longer the case with the new Wikidata-Toolkit API (which has no deduplication anymore), so we can close this. I am reimplementing deduplication in a more configurable was on OpenRefine's side in #4520.
