### ISSUE TITLE
Assertion failed: Input argument is not an HTMLInputElement

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3002]
While helping @tfmorris with testing Jquery on #2933 and using latest SNAPSHOT OpenRefine `openrefine-3.4-beta-388-g1dcc832` and using Firefox latest the Debugger throws an error:

### To Reproduce
1. Open Developer Tools - Console on Firefox
2. Create new project with Clipboard
3. Paste in `a,b,c`
4. Hit Enter key

### Current Results
`TypeError: n is undefined`
thrown in onloadwff.js:71

seems to be around the if() condition for `if("password"===n.type)` ?
```
Assertion failed: Input argument is not an HTMLInputElement onloadwff.js:71:836526
```
### Expected Behavior
not sure what is currently supposed to happen.  I'm not sure why the focus is changing, since the cursor was blinking after the `a,b,c` in the clipboard prior to me hitting the ENTER key.
I assumed that the Enter key is mapped to the Next button on the Clipboard importer?
And should have clicked it for me and gone to Preview screen?  dunno for sure now with current OpenRefine keyboard shortcut key handling or with changes with FF debugger handling and it's causing some weird issue?

#### Screenshots

* OpenRefine Clipboard prior to hitting ENTER key:
![image](https://user-images.githubusercontent.com/986438/88715904-da7cff80-d0e3-11ea-96af-44ee1406de28.png)

* Debugger is immediately thrown up for me in Firefox:
![image](https://user-images.githubusercontent.com/986438/88714939-20859380-d0e3-11ea-8c59-243e25efd567.png)

* Console:
![image](https://user-images.githubusercontent.com/986438/88715002-36935400-d0e3-11ea-8f2a-e2563671a5b0.png)

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox latest
 - JRE or JDK Version: JDK8
 - OpenRefine: openrefine-3.4-beta-388-g1dcc832

**Comment by tfmorris** [comment]
This only happens in debug mode, so I'd just ignore it until it gets in the way of someone's debugging.

**Comment by thadguidry** [comment]
@tfmorris Ah! so you get this also, right?  You can close this issue in that case.
