### ISSUE TITLE
Review all text inputs and text areas for spellcheck=false

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3004]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
Many text inputs or text areas in OpenRefine's UI are meant to store code or structured data. For those, it does not make sense to have the contents spell-checked. Spell-checking also comes with a performance cost which can be significant for large bodies of text.

**Describe the solution you'd like**
Review all the text inputs and text areas, and add `spellcheck="false"` if the spell checker should be disabled for them.
For example, the text area where the history JSON is shown should not be spell-checked.

**Additional context**
Brought up here: https://github.com/OpenRefine/OpenRefine/pull/2982#issuecomment-665295387

**Comment by sujay2306** [comment]
i would like to handle this issue!
can i please take it

**Comment by wetneb** [comment]
Thanks for volunteering, it's all yours!

**Comment by optimm** [comment]
Hey @wetneb if this issue is open can i please work on this , i am all new to open source and looking for bit of guidance.

**Comment by wetneb** [comment]
@optimm sure, go ahead! We have this guide for your first contribution: https://docs.openrefine.org/technical-reference/contributing#your-first-code-pull-request

**Comment by optimm** [comment]
Hey @wetneb i have reviewed the html files for spell check in input types text and made it false where spellcheck is not required , can you please tell me what other kind files i should check in as a example , your help would be greatful

**Comment by wetneb** [comment]
@optimm that's great, I don't think there should be any other files to review. You should be good to submit a PR!

**Comment by optimm** [comment]
@wetneb thank you so much would make a pr asap

**Comment by optimm** [comment]
hey @wetneb  sir i have made a pull request - https://github.com/OpenRefine/OpenRefine/pull/4170 - , please review and let me know if any changes are required , thank you very much

**Comment by khadijm** [comment]
hi, @wetneb  please can you assign me this issue to me

**Comment by khadijm** [comment]
thanks assign me this ticket

**Comment by khadijm** [comment]
please @wetneb can you review my PR https://github.com/OpenRefine/OpenRefine/pull/4636
