### ISSUE TITLE
Column rename isn't recognized by facet

### ISSUE THREAD

**Issue by allanaaa** [OpenRefine/OpenRefine#3018]
If you create a facet, and then rename the column, the facet breaks rather than updates to the new column name. 

### To Reproduce
1. Create a facet from a column.
2. Rename the column to something else.
3. Finally, look at the facet in the sidebar. In this case, I just shortened the column name so that it would display more cleanly.

![columnrename](https://user-images.githubusercontent.com/28012148/89063135-a1d46480-d335-11ea-8910-8a998b00745e.PNG)

### Expected Behavior
The facet display in the sidebar should just refresh to display the new column name.

### Versions
 - OpenRefine: https://github.com/OpenRefine/OpenRefine-snapshot-releases/releases/tag/3.4-beta-410-g6eea757

**Comment by allanaaa** [comment]
My bad, I forgot to search to see if this was already open!

**Comment by tfmorris** [comment]
Duplicate of #133
