### ISSUE TITLE
If Refinery or Sign-in is blocked by filtering or firewall, then show error message

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#302]
_Original author: thadguidry (January 07, 2011 05:22:48)_

Sometimes folks are blocked because of filtering software within an enterprise or firewall issues and can't make a connection to Refinery or sign-in after clicking Load into Freebase.

Aligning the schema and then trying to sign-in doesn't properly show sign-in dialog box but only plain white box tested on Google Chrome. (will test this further tomorrow at work and see if I can reproduce with screenshots)

Better error handling might be needed for this issue.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=302_
##

**Comment by wetneb** [comment]
Refinery does not exist anymore, closing.
