### ISSUE TITLE
ToDate("2012-03-01","XXX") test failure & wasted conversion attempts

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#3026]
I'm investigating a local test failure which I'm unsure whether is specific to OS X or just how timezones are set up on my particular machine.

The failing test is:

      Assert.assertEquals(invoke("toDate", "2012-03-01","XXX"), invoke("toDate", "2012-03-01"));

which returns 2012-03-01T01:00:00 instead of 2012-03-01T00:00:00

This appears to have something to do with the default fallthrough case here, perhaps due to Daylight Savings Time: https://github.com/OpenRefine/OpenRefine/blob/306b541c699e7e87d5e08be1310575b85b15dbf0/main/src/com/google/refine/expr/functions/ToDate.java#L170-L172

While investigating this, I came across this code:

https://github.com/OpenRefine/OpenRefine/blob/306b541c699e7e87d5e08be1310575b85b15dbf0/main/src/com/google/refine/expr/functions/ToDate.java#L135-L145

which I don't completely understand, but in the test case creates an array with 160 copies of the (invalid) code "XXX" which it then uses to attempt to parse the date 160 times, always failing, before falling back to the code above

**Comment by wetneb** [comment]
This date parsing code is a mess, thanks for looking into that!

**Comment by tfmorris** [comment]
The two bugs here are:
- if the local timezone is in daylight savings time, but the parsed date isn't, the conversion to UTC is off by an hour
- If a list of formats was provided, it would try the first format ~160 times before moving on to the others. I *think* this was only a performance issue, but should double check our test coverage.
