### ISSUE TITLE
Problem saving Wikidata schema and uploading Wikidata edits

### ISSUE THREAD

**Issue by dezel002** [OpenRefine/OpenRefine#3029]
In the process of editing a Wikidata Schema, something stopped working. The "Issues" and "Preview" tabs are blankk, and the "Preview" says "Your schema is incomplete, fix it to see the preview.". But I see nothing wrong with my schema, and there are no "Issues" to tell me what's wrong. The "Save Schema" button is greyed out, and nothing happens when I click on it. 
[schema.txt](https://github.com/OpenRefine/OpenRefine/files/5022741/schema.txt)

Upload Edits to Wikidata doesn't work. I successfully used this process as recently as 7/28/2020; now it's not working, with no indication of what is wrong.

**Comment by MatthiasWinkelmann** [comment]
I ran into this as well, and "fixed" it by removing and re-adding labels and descriptions. First place to look for an actual error message would be the browser's JS console.

**Comment by thadguidry** [comment]
Uploads to Wikidata were somewhat problematic in 2020, but should be resolved now, so closing this old issue as more of a question likely already resolved.  Feel free to open a new issue or better yet, start a [new support topic on our forum](https://forum.openrefine.org/c/support/12)
