### ISSUE TITLE
Empty project from upload

### ISSUE THREAD

**Issue by LaChope** [OpenRefine/OpenRefine#3052]
Once I create a project from upload, the project is empty.

### To Reproduce
1. First, create project from upload via API

### Current Results
Project is created, but empty

### Expected Behavior
Should display rows and columns from csv file

### Screenshots
![image](https://user-images.githubusercontent.com/57750426/89785979-7d3d7100-db1b-11ea-9732-36ad166ba7f0.png)

### Versions
 - Operating System:  Windows 10 & Linux Ubuntu 18.04
 - Browser Version: Chrome 19 & Firefox 61
 - JRE or JDK Version: openJDK 11
 - OpenRefine: OpenRefine 3.3

### Datasets
id,firstname,surname
person1,p1firstname,p1surname
person2,p2firstname,p2surname

**Comment by tfmorris** [comment]
The internal API isn't supported for external use, but if you're using someone's client library to access it in an unsupported fashion, you should report any problems to them.
