### ISSUE TITLE
TSV based content from Clipboard importer is detected as Excel

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3061]
### To Reproduce
1. Using Clipboard importer, paste in the below Dataset TSV content example
2. Click Next

### Current Results
Error message:

> Attempted to parse as an Excel file but failed. Try to use Excel to re-save the file as a different Excel version or as TSV and upload again.

### Expected Behavior
**CSV / TSV / separator-based files** Importer should have been detected first.

### Screenshots
![image](https://user-images.githubusercontent.com/986438/89930217-03b38a80-dbd0-11ea-985b-82bfbee4965c.png)

![image](https://user-images.githubusercontent.com/986438/89930158-eaaad980-dbcf-11ea-86aa-65b0960824c0.png)

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox latest
 - JRE or JDK Version: JDK8
 - OpenRefine: openrefine-3.4-beta-458-g109aa78

### Datasets

TSV content
```tsv
Species	BodyWeight(kg)	BrainWeight(kg)	Brain-to-Body-Weight_Proportion
Newborn_Human	3.2	0.374984813	0.117182754
Adult_Human	73	1.349981613	0.018492899
Pithecanthropus_Man	70	0.925010921	0.013214442
Squirrel	0.8	0.007620352	0.00952544
Hamster	0.15	0.001406136	0.009374242
Chimpanzee	50	0.419981176	0.008399624
Rabbit	1.4	0.011521246	0.008229462
Dog_(Beagle)	10	0.071985109	0.007198511
Cat	4.5	0.029982456	0.006662768
Rat	0.4	0.001995806	0.004989516
Bottle-Nosed_Dolphin	400	1.49998461	0.003749962
Beaver	24	0.044996363	0.001874848
Gorilla	320	0.502489628	0.00157028
Tiger	170	0.263491808	0.001549952
Owl	1.5	0.002222603	0.001481735
Camel	550	0.761989823	0.001385436
Elephant	4600	5.999983798	0.001304344
Lion	187	0.239995723	0.0012834
Sheep	120	0.139978605	0.001166488
Walrus	800	0.925010921	0.001156264
Horse	450	0.502489628	0.001116644
Cow	700	0.441481454	0.000630688
Giraffe	950	0.532018491	0.000560019
Green_Lizard	0.2	9.07185E-05	0.000453592
Sperm_Whale	35000	7.799974401	0.000222856
Turtle	3	0.000317515	0.000105838
Alligator	270	0.008391459	3.10795E-05 
```

**Comment by wetneb** [comment]
@thadguidry do you think you could check if this affects the 3.4 branch? It feels like an important bug to fix before a release.

**Comment by thadguidry** [comment]
@wetneb 
### master branch 
```
06:13:31.958 [..importers.ExcelImporter] Error generating parser UI initialization data for Excel file (32ms)
org.apache.poi.poifs.filesystem.NotOLE2FileException: Invalid header signature; read 0x0973656963657053, expected 0xE11AB1A1E011CFD0 - Your file appears not to be a valid OLE2 document
        at org.apache.poi.poifs.storage.HeaderBlock.<init>(HeaderBlock.java:151)
        at org.apache.poi.poifs.storage.HeaderBlock.<init>(HeaderBlock.java:117)
        at org.apache.poi.poifs.filesystem.POIFSFileSystem.<init>(POIFSFileSystem.java:229)
        at org.apache.poi.poifs.filesystem.POIFSFileSystem.<init>(POIFSFileSystem.java:170)
        at org.apache.poi.poifs.filesystem.POIFSFileSystem.<init>(POIFSFileSystem.java:153)
        at com.google.refine.importers.ExcelImporter.createParserUIInitializationData(ExcelImporter.java:90)
        at com.google.refine.importing.DefaultImportingController.doInitializeParserUI(DefaultImportingController.java:216)
        at com.google.refine.importing.DefaultImportingController.doPost(DefaultImportingController.java:91)
        at com.google.refine.commands.importing.ImportingControllerCommand.doPost(ImportingControllerCommand.java:68)
        at com.google.refine.RefineServlet.service(RefineServlet.java:187)
```

### 3.4 branch
No error

**Comment by thadguidry** [comment]
@wetneb The Clipboard importer should not try using the ExcelImporter?  Clipboard importer should only attempt to parse those limited amount of text files that we support, such as text, json, xml, rdf, n3, etc.  The containerized files like ODS and ExcelImporter should only apply to the following importers:
- This Computer
- Web Addresses (URL)
- Google Data

So perhaps an importer exclusion list is what is needed for the Clipboard importer to make this dirt simple.

![image](https://user-images.githubusercontent.com/986438/90010242-2a6fd080-dc65-11ea-9159-6f084290e540.png)

**Comment by tfmorris** [comment]
I've posted a fix. Until it is reviewed and merged, you simply need to click the "TSV" button to import your file.

**Comment by wetneb** [comment]
Given the user experience we get here, I am wondering if our architecture could be adapted slightly to avoid guessing a type and then failing to run the corresponding importer.
Intuitively, if parsing for import preview is not too expensive, it should be possible to try the guessed importer, and if that fails fall back on the next one in the queue, until possibilities are exhausted.
I would say it's beyond the scope of this particular issue though.

**Comment by tfmorris** [comment]
> I would say it's beyond the scope of this particular issue though.

Yes, definitely.
