### ISSUE TITLE
Importer names not internationalized (i18n)

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#3069]
These strings in controller.js need to be internationalized so that they can be translated:
![Screen Shot 2020-08-12 at 12 19 23 PM](https://user-images.githubusercontent.com/82178/90040780-5eafb500-dc96-11ea-827f-ab9efb4dfb68.png)

https://github.com/OpenRefine/OpenRefine/blob/0ce5c5de13e63ad63c95af08366a4d5a4ba2aadd/main/webapp/modules/core/MOD-INF/controller.js#L207-L229

I haven't looked into how they are being fetched/used, so this may not be completely straightforward.

**Comment by chetan-v** [comment]
I did something for it. please check
