### ISSUE TITLE
Reconciliation : Left panel "Services" bounce

### ISSUE THREAD

**Issue by pyrog** [OpenRefine/OpenRefine#3072]
When clicking on "Services", the panel is "closing" but immediately "reopening" like it bounce.

### To Reproduce
1. Adding a new reconciliation service
2. Click on the services title or on the label icon
3. The panel is "moving" left normally
1. The panel automatically "move" to the right

### Current Results
All the filed behind the panel are hidden

### Expected Behavior
The panel should stay "closed"

### Screenshots
![OpenRefine - left panel bounce](https://user-images.githubusercontent.com/2158081/90117992-ec070e00-dd57-11ea-9e19-749ea346732a.jpg)

### Versions
- Operating System: **macOS** Mojave 10.14.6 (18G4032)
- Browser Version: **Firefox** 79.0 Firefox Release July 28, 2020
- JRE or JDK Version:
  - java version "1.8.0_74"
  - Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
  - Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

 - OpenRefine: Version 3.4-beta-327-g0645c2a (1)

**Comment by thadguidry** [comment]
Hi @pyrog Yes this is a known issue #1658 , so marking as duplicate.  Hopefully we get this resolved soon in an upcoming release.
