### ISSUE TITLE
Remove old classmappings for extension support with com.metaweb.* and com.google.*

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3073]
https://github.com/OpenRefine/OpenRefine/blob/f50efb3699012ea539e9f0f4cfc63399a5ea7b12/main/src/com/google/refine/RefineServlet.java#L333

They are added for backward compatibility for extensions.
They can be removed at some point in future version of OpenRefine.

Will mark as "extension" label so we can find this issue easier in the future when discussing extension support.

**Comment by wetneb** [comment]
I think we can keep these indefinitely, no? What is the benefit of removing them?

**Comment by thadguidry** [comment]
Oh well... yeah, that's technically true. :-)  Up to you and @tfmorris  I guess it depends on if we want the code to also encourage extension authors to move ahead with us.  So there, we probably just need a comment in the code, rather than removal.  And furthermore, I guess additional encouragement should be done in "writing an extension" document in our Technical Reference as to the proper class registration we expect.

**Comment by tfmorris** [comment]
I agree that investing in removing them (or even discussing removing them) isn't a priority.

It **is** an interesting indication, though, of just how important extension compatibility used to be. We need to get back to that. Every extension that I've looked at recently, except for perhaps the RDF extension, is neither binary nor source compatible any more.

When/if we do remove support for something like this, we need to announce it ahead of time with a deprecation period that allows extension writers to adapt their code.

**Comment by wetneb** [comment]
Closing since we agree that those class mappings can be kept.
