### ISSUE TITLE
Improve handling of dates in cell editing UI

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3082]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**

Say you want to manually edit a cell to input a date there. This is what it currently looks like:
![image](https://user-images.githubusercontent.com/309908/90312398-82783280-df04-11ea-9874-d3db4d36f7b9.png)

The problems are:
* As a user, how do I know which formats are supported? Especially if I start with a text value and want to transform it to a date, I should not have to refer to the user manual to find out how to format it.
* When I try to input a wrong date, a JS alert pops up: "Not a valid date." That is not very helpful!

**Describe the solution you'd like**

Find a way to add a short description of the supported format(s) to the dialog itself, and/or improve the error message to mention the formats.

**Describe alternatives you've considered**

We could consider using an off-the-shelf date picker but it is not clear to me whether that would be really more user-friendly in a data cleaning context. Perhaps it could be used optionally, with still the ability to modify the date textually?

**Additional context**
Brought up in a documentation meeting with @allanaaa and @thadguidry.

**Comment by thadguidry** [comment]
Within that text input element... maybe it could just use [ACE](https://ace.c9.io) embeddable code editor with a bit of linting, and Syntax highlighting perhaps? (Other uses of ACE could be in our Expression Editor, but [that's another issue](https://github.com/OpenRefine/OpenRefine/pull/2350#issuecomment-674434712))
