### ISSUE TITLE
Coveralls test coverage report flaky

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#3083]
This build: https://coveralls.io/builds/32777994
was "failed" by Coveralls because coverage supposedly fell 0.06% with 25 newly uncovered existing lines in 8 different files.

The only problem with that is that there's no way that the very minimal changes in the PR affected any of those files, which are all in the database and Wikidata extensions.

This would seem to indicate that either our tests flaky/non-deterministic or Coveralls is. Looking at the files listed, one suspicion is that on this run the database extensions did **not** throw an exception which it through on the previous base run. Unclear whether the intended behavior is with or without the thrown exception.

LINES | COVERAGE | ∆ | FILE
-- | -- | -- | --
1 | 74.59 | -0.55% | extensions/database/src/com/google/refine/extension/database/DatabaseImportController.java
1 | 95.24 | 0.0% | extensions/wikidata/src/org/openrefine/wikidata/schema/WbReferenceExpr.java
1 | 96.0 | 0.0% | extensions/wikidata/src/org/openrefine/wikidata/schema/WbStatementGroupExpr.java
3 | 55.45 | -2.97% | extensions/database/src/com/google/refine/extension/database/DBQueryResultImportReader.java
3 | 83.05 | -2.54% | extensions/database/src/com/google/refine/extension/database/mysql/MySQLDatabaseService.java
3 | 87.69 | -4.62% | main/src/com/google/refine/logging/IndentingLayout.java
5 | 0 | -27.78% | extensions/database/src/com/google/refine/extension/database/DatabaseServiceException.java
8 | 76.74 | 0.0% | extensions/wikidata/src/org/openrefine/wikidata/schema/WikibaseSchema.java

**Comment by wetneb** [comment]
One way to mitigate this would be to change the threshold below which Coveralls marks builds as failed. I have just changed it from -0.01% to -0.07%

**Comment by tfmorris** [comment]
Thanks. That should help generate fewer failed builds, but still leaves the question of why the database extension unit tests are sometimes, apparently, throwing exceptions and sometimes not.

I also find the Coveralls report hard to interpret. The wikidata module reports are showing things like the closing brace of an empty method as being "uncovered" which doesn't seem very useful, although perhaps that's more a JaCoCo problem than Coveralls problem.

I'll leave this open for a bit in case I get some free time (hah!) to check into the non-determinism, but marking as low priority.

**Comment by tfmorris** [comment]
Coveralls has been disabled for months, so this isn't really relevant.
