### ISSUE TITLE
Improve naming of snapshot releases

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#3095]
Our current naming for the snapshot releases is a little misleading since they are based on the most recent tag due to the way `git describe` works, but that tag is typically on a different branch. As an example, a recent build was named `snapshot 3.4-beta-482-gf74e3e0` despite that fact that it is really a 3.5 snapshot built off the master branch.

### Proposed solution
Perhaps using the version from Maven's POM in conjunction with the date and/or git commit would make for a more relevant version that users could correlate with the code that it came from.

**Comment by wetneb** [comment]
Yes, it was appropriate when we did not do release branches but now it's not ideal. It's just a matter of finding the version string that works for us in the git-commit-id-plugin.

**Comment by wetneb** [comment]
This has been solved now that we are not using Github Releases to publish our snapshot releases, but Maven Central instead.
