### ISSUE TITLE
Support CORS for propose_properties

### ISSUE THREAD

**Issue by pyrog** [OpenRefine/OpenRefine#3107]
OpenRefine use only JSONP to call [data extension property proposal service](https://reconciliation-api.github.io/specs/latest/#dfn-data-extension-property-proposal).
### To Reproduce
1. From a reconciled column select `Edit column` → `Add columns from reconciled values…`

### Current Results
After a timeout, the form is displayed but **Suggested Properties** list is empty.
The service log :
```
"GET /fr/propose_properties?type=cinema&callback=jQuery111103759655054445933_1597936961626&_=1597936961650 HTTP/1.1" 200 -
```

### Expected Behavior
OpenRefine must call the service first with **CORS**, and if the service don't respond, retry with **JSONP**.

### Versions
 - Operating System: macOS
 - Browser Version: Firefox
 - JRE or JDK Version: 1.8.0_74
 - OpenRefine: Version 3.5-SNAPSHOT [0645c2a]

**Comment by wetneb** [comment]
I am wondering if this is still current - we now have quite a few services which only support CORS and I think propose_properties works for them too. I am thinking about the Wikimedia Commons service for instance (https://commonsreconcile.toolforge.org/en/api).

**Comment by wetneb** [comment]
I just checked and CORS is used to contact the Wikidata recon service, so it is indeed supported:
![image](https://user-images.githubusercontent.com/309908/207950788-48513456-1fc0-4cad-a844-8a3626607129.png)
