### ISSUE TITLE
Change "Add column by fetching URLs" throttle delay to 1000ms

### ISSUE THREAD

**Issue by allanaaa** [OpenRefine/OpenRefine#3127]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
The default throttle delay in the program is 5000ms. It should be 1000ms.

![fetchingURLs](https://user-images.githubusercontent.com/28012148/91198049-10ed7080-e6ca-11ea-8157-14e351cbf748.PNG)

**Describe the solution you'd like**
I think the edit needs to be made to this page: 

https://github.com/OpenRefine/OpenRefine/blob/9f7d5b878628c40d68a445b751fd50140d922e7d/main/webapp/modules/core/scripts/views/data-table/add-column-by-fetching-urls-dialog.html

**Comment by tfmorris** [comment]
> It should be 1000ms.

I don't know if it "should" be any particular value. What is your recommendation based on?

One improvement that we might consider is making the value sticky, either for a given host or for the user/project in general.

**Comment by allanaaa** [comment]
We (@thadguidry @wetneb) looked at this pull request and there was consensus around your comment that 1 second seemed like a good default. 
https://github.com/OpenRefine/OpenRefine/pull/3103#discussion_r475835761

**Comment by thadguidry** [comment]
Looking back at a chat history with David... he told me the reason why 5 secs instead of 1 sec was to error on the side of caution to prevent users from getting banned.  Hmm, I did forget about that.  Up to you guys.

**Comment by tfmorris** [comment]
#3129 relates to this.

Certainly we should err on the conservative side, but the interwebs have changed "somewhat" in the past decade. Even 5 years ago, my usual recommendation to students was that they lop a zero off for a 500 msec value, making for 2 requests/second.

In a quick informal survey, I didn't find any limits under 1 request / second. AWS is 20 rps for reads, 5 rps for writes. Microsoft is all over the map with request limits per day, per 15 minutes, per minute, per 10 seconds, etc depending on the service. Google is 50 rps for geocoding, 10 rps for Analytics.

If we fix #3219, I think 1000 msec is a good conservative default until we move to a more flexible rate limiting implementation.

**Comment by wetneb** [comment]
This default value has already been lowered to 500ms: closing.
