### ISSUE TITLE
Fix Fetch URL delay calculation

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#3129]
As a side effect of the introduction of caching (782a2f5b48d54dd839398b14b72c878f7b526a10), the delay calculation got changed, reverting the fix (000c0a38a8965a20fbd3a44b6424526609bb64ea) for #721. Mixing multiple different functional changes in a single commit isn't ideal to start with, but I don't agree with this comment: 

https://github.com/OpenRefine/OpenRefine/blob/5ca5f3cb7b6cc1be1813e9e196a3c0f669298a4c/main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java#L286-L290

I believe users will most commonly think of this as the inverse of the request rate (ie a delay of 500 msec is equivalent to 2 requests/sec). As a matter of fact, perhaps a rate would be a better way to specify it. Since the requests are issued in a single threaded fashion, there is already natural throttling going on based on the server's response time. Adding an additional delay to that makes it impossible to hit a consistent request rate due to the variability.

Longer term we probably want to let the user specify a rate per second/minute/hour, maximum number of requests outstanding at a time, and handle 429 responses when being throttled, but for now we should fix the delay calculation.

**Comment by thadguidry** [comment]
@tfmorris Kinda Agree.  Rates are even posted by various organizations sometimes... like Nasa's API's with 1,000 requests per hour.  Scroll down on https://api.nasa.gov/

**Comment by wetneb** [comment]
The previous approach only introduced a throttling when the sleeping delay was reduced down to zero by the server's response time, which is not as polite as sleeping for a fixed amount of time between two requests.

The new strategy means that the throttling is continuous, meaning that if you have a pool of clients following this strategy, their request rate will converge to an equilibrium that matches what the server can afford.

Feel free to change this if you feel strongly about it, but please do not call that a "fix": this just would be reverting an intentional change of throttling strategy. Thanks!

**Comment by tfmorris** [comment]
> The previous approach only introduced a throttling when the sleeping delay was reduced down to zero by the server's response time, which is not as polite as sleeping for a fixed amount of time between two requests.

I'm not sure how you are using the word "throttling" here. Do you mean additional throttling over and above the specified inter-request delay? Before if you asked for a delay of 500 msec between requests, that's what you'd get whether the server responded in 100 msec or 400 msec. If the server took 600 msec to respond, the delay requirement of 500 msec had already been satisfied.

> The new strategy means that the throttling is continuous, meaning that if you have a pool of clients following this strategy, their request rate will converge to an equilibrium that matches what the server can afford.

The current behavior means that the inter-request interval for the above example will be 600, 900, and 1100 msec and the user has no way of controlling what the actual delay between requests is. The phrase 

> an equilibrium that matches what the server can afford

infers an intentional behavior that I don't think is supported by the general case. Response latency can be a function of network delay, cost of the request, other load on the server and it's a leap to assume that it means that a specific individual client should modify it's behavior based on observed latency for the previous request.
