### ISSUE TITLE
Improve accuracy of returned error message for toString()

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3133]
`toString()` can also be used for Number formatting (not only Date formatting) as evidenced by @tfmorris on the mailing list today.

We should improve the `toString()` error message output here:
https://github.com/OpenRefine/OpenRefine/blob/ded6ca07d1fb1f88f1b7f9bae7e1de6d3c22e311/main/src/com/google/refine/expr/functions/ToString.java#L67

replacing the line with this would help more:

```java
return new EvalError(ControlFunctionRegistry.getFunctionName(this)  +
    " accepts an object and an optional second String argument containing a date format or number format");
```

**Comment by sjathin** [comment]
I would like to work on this issue, It would be helpful if I can get an example of the parameters that will be passed to the function.

**Comment by thadguidry** [comment]
@sjathin see updated comment above

**Comment by tfmorris** [comment]
Let's try to keep related issues linked. I'm not sure this is worth documenting https://github.com/OpenRefine/OpenRefine/issues/816#issuecomment-682195356

**Comment by elroykanye** [comment]
Hello @thadguidry , I'd like to take on this. Is that okay?

**Comment by thadguidry** [comment]
@elroykanye Sure.  I think just something ending with ... `containing a Date or Number format string` ?

**Comment by elroykanye** [comment]
Noted!😉
