### ISSUE TITLE
Enhance randomNumber() function

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#3143]
The `randomNumber()` function currently takes two Number arguments, converts them to integers and returns a random number in the open interval.

### Proposed solution

I think the following changes would improve the function:
- shorten the name to just `random()`
- create a 0-arg version which returns a Double in the interval 0.0 - 1.0
- provide two alternatives for the 2-arg version which return either an Long or a Double, depending on type of the parameters which are passed in

### Alternatives considered
- the 2-arg integer version could have a different name like `randint` a la Python
- a variant that accepts a seed value could be useful for those who want reproducible results

**Comment by SustechcsKing** [comment]
Hi, sir, I just add a function. First, it generates a random number by random(). Second, it can generate a random Long or random double by argument, but it still needs the typecasting when getting the number, because its return type is Object. I think this may meet your standard. Thank you.

**Comment by elroykanye** [comment]
@wetneb , I noticed this was taken but not completed and pr closed. Please can I take and work on it?
