### ISSUE TITLE
conda build fails with dependencies not found

### ISSUE THREAD

**Issue by wolfv** [OpenRefine/OpenRefine#3161]
I am trying to add OpenRefine to conda-forge. It would be very cool to be able to install openrefine through conda (which is a cross-platform package manager).

I am using Maven, and get the following error:

```
[ERROR] Failed to execute goal on project main: Could not resolve dependencies for project org.openrefine:main:jar:3.3: The following artifacts could not be resolved: edu.mit.simile:butterfly:jar:1.0.2, marc4j:marc4j:jar:2.4, net.sf.opencsv:opencsv:jar:2.4-SNAPSHOT, edu.mit.simile:vicino:jar:1.1, com.wcohen:secondstring:jar:20100303, com.colloquial:arithcode:jar:1.1: Could not find artifact edu.mit.simile:butterfly:jar:1.0.2 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

I am not a Java expert and thus don't know how to fix it. I think master works fine. Are you plannign to make a new release with these issues fixed soon?

https://github.com/conda-forge/staged-recipes/pull/12280
https://github.com/conda-forge/staged-recipes/pull/12280/checks?check_run_id=1071908416 (link to build output)

**Comment by wetneb** [comment]
Thanks for looking into this!

It is not clear to me where this could come from, I am not familiar with your build environment. You could perhaps look for other Java-based projects packaged with conda-forge and see if they had to invoke the build process differently?

**Comment by wolfv** [comment]
the error says:

Could not resolve dependencies for project org.openrefine:main:jar:3.3: The following artifacts could not be resolved: edu.mit.simile:butterfly:jar:1.0.2, marc4j:marc4j:jar:2.4, net.sf.opencsv:opencsv:jar:2.4-SNAPSHOT, edu.mit.simile:vicino:jar:1.1, com.wcohen:secondstring:jar:20100303, com.colloquial:arithcode:jar:1.1: Could not find artifact edu.mit.simile:butterfly:jar:1.0.2 in central (https://repo.maven.apache.org/maven2) -> [Help 1

I don't think this is related to conda (as I said master seemed fine) it's just that the packages are somehow not available anymore? Is that possible? I don't know maven very well...

**Comment by wetneb** [comment]
> I don't think this is related to conda

Well, if OpenRefine's master branch compiles fine in our CI, on your computer and on my computer, and not in conda's build system, then I would say that there must be something specific about conda's environment which causes this failure.

> it's just that the packages are somehow not available anymore? Is that possible?

No.

**Comment by wolfv** [comment]
Sorry if I wasn't clear. This is about the latest release 3.3 that doesn't work anymore. I am looking for a minimal patch to get it to build again :)

**Comment by wolfv** [comment]
we wouldn't release a non-tagged version to conda-forge

**Comment by wetneb** [comment]
Let's take this to your PR on the other repository.
