### ISSUE TITLE
Add column containing entity identifiers does not allow ENTER key press

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3163]
Pressing ENTER key has no effect on dialog for adding a new column containing entity identifers (from the Reconcile menu)

### To Reproduce
1. Reconcile a few cells in a column  (already done, see attached OpenRefine project to import)
2. On Species column, choose Reconcile -> Add entity identifiers column
3. Type in a new column name into the input box and press ENTER

### Current Results
nothing more happens

### Expected Behavior
I was expecting that the ENTER key was bound to the OK button and would close the dialog and my new column would appear.

### Versions
 - Operating System: Windows
 - Browser Version: Firefox latest
 - JRE or JDK Version: JDK8
 - OpenRefine: openrefine-3.4-beta-514-gaa43445

### Datasets
[SCOR-Data.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/5178053/SCOR-Data.openrefine.tar.gz)

**Comment by sjathin** [comment]
I would like to work on this issue.

**Comment by thadguidry** [comment]
@sjathin Sure!
