### ISSUE TITLE
Upgrading to xstream 1.4.13-java7 breaks the packaging workflow

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3171]
This is not a bug per se, just a note that we should hold off from upgrading xstream to 1.4.13-java7 (as in #3169) since it breaks the packaging workflow:
https://github.com/OpenRefine/OpenRefine/runs/1081398250

I think we have had this issue before. We would need launch4j 3.13 to be formally released to solve this.

**Comment by tfmorris** [comment]
#2644 #2752

**Comment by wetneb** [comment]
And #3174

**Comment by wetneb** [comment]
Launch4j 3.14 has been released and we have successfully updated xstream, closing.
