### ISSUE TITLE
Display the logo of each Wikibase instance in the login form and Wikibase selection dialog

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3186]
The Wikibase login form now shows the Wikibase logo on the left hand side:

![image](https://user-images.githubusercontent.com/309908/93014913-409ae480-f5b5-11ea-90e0-1536ceffb940.png)

It would be nice if we could have the logo of the selected Wikibase instance instead. This would be immediately recognizable to the user, who would therefore be less likely to enter credentials for another instance.

These logos could also be shown in the UI where we select which instance to work against.

![image](https://user-images.githubusercontent.com/309908/93014924-60320d00-f5b5-11ea-8e0a-c1db08af197b.png)

### Proposed solution

The URL of the logo used by the Wikibase instance can be fetched via the API:
https://daap.bannerrepeater.org/w/api.php?action=query&meta=siteinfo&siprop=general%7Cnamespaces%7Cnamespacealiases%7Cstatistics
Which gives a logo URL: https://daap.bannerrepeater.org/w/resources/assets/wiki.png

This would give something like this:
![image](https://user-images.githubusercontent.com/309908/93015008-03832200-f5b6-11ea-937b-a5f5c00a6d0f.png)

### Alternatives considered
The logo could be added to the manifest, but if we can fetch it from the MediaWiki instance directly I think it simplifies everyone's life if we do that.

### Additional context

We need to think about whether fetching these images from the frontend directly from the remote site could cause security or privacy issues. It seems that it is not more dangerous than visiting the Wikibase instance itself (since that loads the logo too), so I think is is acceptable?

**Comment by sjathin** [comment]
Hello, I would like to work on this issue.

**Comment by wetneb** [comment]
@sjathin wonderful! I have invited you to the organization: that should let you assign issues to yourself, help with issue tagging and other things like that.

**Comment by sjathin** [comment]
@wetneb Thank you so much for the invitation !!!

**Comment by thadguidry** [comment]
@sjathin welcome aboard!

**Comment by sjathin** [comment]
I am facing the following issue: 

I am trying to get the URL of the logo(```https://www.wikidata.org/w/api.php?action=query&meta=siteinfo&format=json```) using the following :

`$.ajax({url: <url-shown-above>, async: false, dataType: 'json', success:.....});`
But this gives a CORS issue. if I try the same request using an API Client such as postman I get a response,
  
Not exactly sure as to why I am facing this CORS issue. Any thoughts on why the CORS issue and how I can resolve this?

**Comment by wetneb** [comment]
Curious, I would expect CORS headers to be set correctly for this API. Have you inspected the headers of the response you get in postman? Have you tried JSONP too?

**Comment by sjathin** [comment]
Yes I did try with JSONP, it works fine, but the problem that I faced is that I cannot do JSONP as async:false

**Comment by gitonthescene** [comment]
Did the CORS issue resolve itself?  I’m happy to take a look if it’s still an issue.

**Comment by sjathin** [comment]
Yes, it did resolve, making the ```dataType``` as ```jsonp``` fixed it.
