### ISSUE TITLE
Identical score if only one of two identifiers match

### ISSUE THREAD

**Issue by hroest** [OpenRefine/OpenRefine#3191]
When doing reconciliation with Wikidata for example, a match will often produce a score of 100% if only name matches to the lemma or any alternative identifiers. This is the case even if a second column is provided that can be used as an external identifier. The score will still be a 100 even if the second identifier does not match and there is one match where both columns match, basically making the single-column match indistinguishable from the two-column match.

Maybe I am doing this wrong, I would appreciate some help.

### Proposed solution
The score should be higher for the match where both the Lemma name and the identifier match and lower for those that do not match.

### Alternatives considered
* there are none, I have to go through all Lemmata by hand to find the right one

### Additional context

I am working with data where there is often items that have the same name and need a secondary identifier to be distinguished.

An example:

Lemma: Teufen
External Identifier: 007804
External Identifier used: HLS https://www.wikidata.org/wiki/Property:P902
Correct match: https://www.wikidata.org/wiki/Q67209

Here is how I do the reconciliation:
![image](https://user-images.githubusercontent.com/464014/93481079-2cfcc000-f8cc-11ea-94f1-d49f64aa457b.png)

Here is the result:
![image](https://user-images.githubusercontent.com/464014/93481874-12771680-f8cd-11ea-8435-389212b97a26.png)

**What I expect:** I expect that the correct match  https://www.wikidata.org/wiki/Q67209 where the Lemma *and* the external identifier P902 match will get the highest score. 

**What happens instead:** 

There are 5 hits that all have 100 match score:
* https://www.wikidata.org/wiki/Q99371460 "von Teufen"
* https://www.wikidata.org/wiki/Q22479398 "Teufen (Switzerland)"
* https://www.wikidata.org/wiki/Q2407310 "Teufen family "
* https://www.wikidata.org/wiki/Q334493 "shaft sinking"
* https://www.wikidata.org/wiki/Q67209 "Teufen"
This is simply based on matching the Lemma and does not take the HLS identifier into consideration at all.

**Comment by wetneb** [comment]
Hi @hroest,

Thank you very much for bringing this up. I am transferring it to the repository responsible for the scoring:
https://github.com/wetneb/openrefine-wikibase/issues/89
