### ISSUE TITLE
Add instructions to install new HTTPS certificates on Windows

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3192]
In #3103 we document how to install missing certificates (to solve some errors when fetching URLs), but we only have instructions for the Mac bundle.

### Proposed solution
Figure out how to install extra certificates on Windows (both with the embedded JRE and the JRE installed independently from OpenRefine).

### Alternatives considered
There might be ways to improve the way we handle this in the software itself - ideally, ways to install certificates inside OpenRefine directly (in a platform-independent way), but I am not sure this is technically possible.

**Comment by allanaaa** [comment]
For your reference, in the v3.4 documentation, this is the latest draft of the text: 

>**“error: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure”**
> Note that for Mac users and for Windows users with the OpenRefine installation with bundled JRE, these updated cipher suites need to be dropped into the Java install within the OpenRefine application: 
> * On Windows: `\server\target\jre\lib\security`.
> ...

>**"sun.security.validator.ValidatorException: PKIX path building failed"**
> Note that for Mac users and for Windows users with the OpenRefine installation with bundled JRE, the `cacerts` file within the OpenRefine application needs to be updated. 
> * On Windows: `\server\target\jre\lib\security\`.

Otherwise it links to instructions on updating an independent JRE installation. 

> You can find directions on how to add a security certificate to the list of trusted certificates for a Java installation [here](http://magicmonster.com/kb/prg/java/ssl/pkix_path_building_failed.html) and [here](http://javarevisited.blogspot.co.uk/2012/03/add-list-certficates-java-keystore.html).

Happy to elaborate more on either set of instructions.

**Comment by tfmorris** [comment]
Since I fixed the error reporting, this

>**"sun.security.validator.ValidatorException: PKIX path building failed"**

should now be 

`javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed`

or perhaps 

`javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

If you are still seeing the fragmentary error message, we should figure out where it's coming from.

**Comment by allanaaa** [comment]
So, 

> **“javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed”** or **“javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested targe”** can occur when you try to retrieve information over HTTPS but the remote site is using a certificate not trusted by your local Java installation. You will need to make sure that the certificate, or (more likely) the root certificate, is trusted.

?

Or can I just put **“javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed”** instead of both?

**Comment by tfmorris** [comment]
Yes, that's fine. It will only be one of the two, but I'm not sure which. The shorter version is close enough for people to be able to recognize/find it.

**Comment by wetneb** [comment]
I just checked the docs about this for Windows and they seem clear to me, so closing.
