### ISSUE TITLE
OpenRefine 3.4 stable release for Mac is showing Version 3.4-beta2 [6443506]

### ISSUE THREAD

**Issue by uofmsean** [OpenRefine/OpenRefine#3196]
### To Reproduce
1. Download from https://github.com/OpenRefine/OpenRefine/releases/download/3.4/openrefine-mac-3.4.dmg
2. Verify SHA as f0aa34025b3137c6ccd6b49ee243cbdf06195995
3. Install and replace older version 3.3 in Applications folder
4. Start OpenRefine and check Version listed on home page

### Current Results

Version on home page shows as 3.4-beta2 whereas the Mac About version shows as Version 3.4 (1)

### Expected Behavior

Version should not show as beta2. Not sure if the released .dmg is even for the stable 3.4 release.

### Screenshots

![image](https://user-images.githubusercontent.com/43143083/93611854-6a2c8500-f994-11ea-8d44-2ce463f1366d.png)

### Versions
OpenRefine 3.4 stable release

**Comment by wetneb** [comment]
Thanks for reporting this!
It is curious because commit 6443506 does correspond to the 3.4 tag. I'll investigate.

**Comment by wetneb** [comment]
Closing by releasing 3.4.1.
