### ISSUE TITLE
Mac-3.4 no mountable file systems

### ISSUE THREAD

**Issue by ajtripper** [OpenRefine/OpenRefine#3199]
### To Reproduce
1. First, downloaded the dmg
2. Tried opening after giving MacOS permission to do so
3. Get error saying disk image could be open since there is no mountable file system

**Comment by wetneb** [comment]
This could be due to the code-signing process that we have introduced. Which version of MacOS are you using?

**Comment by ajtripper** [comment]
Hello Antonin,

I’m using MacOS Big Sur version 11.0 Beta (20A5374i). I had the permissions issue but was able to force the OS to open the dmg file before getting the message.

Thank you for your work on OpenRefine, it is one of my favorite data science utilities.

Kind regards,
Tony

**Comment by tfmorris** [comment]
We've had another report of the same issue on the Big Sur beta. It hasn't been tested on that platform. Since the beta has clearly changed/broken something I'd suggest opening a bug report against macOS.

**Comment by wetneb** [comment]
This was solved by dropping the codesigning process. We need to reintroduce it properly by using our CI to do the entire packaging process on Mac.
