### ISSUE TITLE
Importer for Google Data login returns a Error 400: invalid_request

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3205]
### To Reproduce
1. Click on Google Data importer
2. Click on button **sign in and authorize**
3. Browser dialog box appears with the following:

### Current Results
- URL https://accounts.google.com/signin/oauth/error?authError=
- **Error 400: invalid_request**
- Missing required parameter: client_id
- [Learn more](http://code.google.com/apis/accounts/docs/OAuth2.html)

### Expected Behavior
Login box and entering credentials should work as it does in OpenRefine 3.3

### Screenshots

![image](https://user-images.githubusercontent.com/986438/93948010-e6abc480-fd02-11ea-8d6e-4e79ce2dab68.png)

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox latest
 - JRE or JDK Version: embedded
 - OpenRefine: OpenRefine 3.4 with embedded java

**Comment by tfmorris** [comment]
Relevant code is here:

https://github.com/OpenRefine/OpenRefine/blob/bc540a880eceb88e54f85ca43eb54769de3bfa4f/extensions/gdata/src/com/google/refine/extension/gdata/GoogleAPIExtension.java#L36-L39

but I don't see anything in the build scripts that inject the production client ID and secret.

**Comment by tfmorris** [comment]
As a workaround, I've confirmed that both OpenRefine 3.3 and 3.4-beta2 work correctly.

**Comment by wetneb** [comment]
There is indeed a problem with the 3.4 build: I did not add the production settings correctly, because it was not mentioned on the release instructions page. Sorry about this! I have added it to the release page now. I propose that we release a 3.4.1 with these credentials added, which should also solve #3196.
