### ISSUE TITLE
Support Wikibase editing for entity types other than Item

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3210]
Wikibase has a notion of entity types. These determine which sorts of fields entities can store. At the moment, I am aware of the following entity types:
- Items (such as https://www.wikidata.org/wiki/Q42), which OpenRefine currently supports;
- Properties (such as https://www.wikidata.org/wiki/Property:P3500)
- Lexemes (such as https://www.wikidata.org/wiki/Lexeme:L345)
- Forms (such as https://www.wikidata.org/wiki/Lexeme:L345#F1)
- Senses (such as https://www.wikidata.org/wiki/Lexeme:L345#S1)
- MediaInfo (such as https://commons.wikimedia.org/entity/M74698470, look for the "Structured data" tab)

In a given Wikibase instance, a given namespace is associated to a single entity type.

### Proposed solution

There are a few high-level design questions to solve, to enable editing other entity types:
* Should the reconciliation service associated to the Wikibase instance work for all entity types stored in the instance, or should we have one reconciliation service per entity type? (They could all be exposed by the same code base: currently, a single instance exposes one reconciliation endpoint for each language).
* How should it look like in the schema editor? At the moment we have a "add item" button to create an edit template for an item, we could add other links for other supported entity types. Or we could simply change "add item" to "add entity" and then make the corresponding template more flexible (for instance, add a field for the "datatype" of a property), but it feels to me that this would get messy pretty quickly (typically for lexemes).

### Additional context

Figuring out the general architecture of this would be a good first step towards #2144 and #2240.

**Comment by thadguidry** [comment]
> Should the reconciliation service associated to the Wikibase instance work for all entity types stored in the instance, or should we have one reconciliation service per entity type? (They could all be exposed by the same code base: currently, a single instance exposes one reconciliation endpoint for each language).

@wetneb Hi Antonin, if it helps in anyway on some decision for that question:

I sometimes deal with mixed types within a single column.  For example, Lexemes and Items.  The item whale, and the word "whale" in the same column.  Additional columns give me the hints I need to sometimes filter rows to recon to only items or words, but not always.  Sometimes I have enough hints to partition the data into nice neat columns of only those entity types, but a lot of times it's really hard to do so and I depend on the recon service to basically help with some of that disambiguation (sometimes having to do multiple recon on the single column or others)

Wouldn't a single instance and endpoint help more easily with a scenario like that, compared to me having to do more work as a user and try to partition my data, which sometimes I actually cannot partition it well enough, and am actually using the recon service to help with that.  I don't know if single or multiple recon instances help me reduce or increase the amount of recons?  (Of course this is assuming that OpenRefine's recon processing stays unparalleled, and can't recon 2 or more columns at the same time)

**Comment by trnstlntk** [comment]
More detail in #4268.

**Comment by wetneb** [comment]
Duplicate of #4268.
