### ISSUE TITLE
Support multiples URLs in one cell

### ISSUE THREAD

**Issue by pyrog** [OpenRefine/OpenRefine#3215]
### To Reproduce
1. Edit a cell and add 2 or more URLs separated by space, comma, newline…<br/>For example:<br/>https://www.openstreetmap.org<br/>https://commons.wikimedia.org
2. Click on one link

### Current Results
Open a new tab in the web browser and display an error.
The link is the concatenation of the 2 URLs : [https://www.openstreetmap.orghttps//commons.wikimedia.org](https://www.openstreetmap.orghttps//commons.wikimedia.org)

### Expected Behavior
Open a new tab and display one of the 2 web pages:
- https://www.openstreetmap.org
- https://commons.wikimedia.org

### Versions
 - OpenRefine: Version **3.4.1** [437dc4d]

### Additional context
Seem that this bug or feature is in the javascript code that add a link for all the cell.
- https://github.com/OpenRefine/OpenRefine/blob/9f7d5b878628c40d68a445b751fd50140d922e7d/main/webapp/modules/core/scripts/util/url.js#L92
- https://github.com/OpenRefine/OpenRefine/blob/6095c44cb714f7b1ea6a1eac961b0394ac138a8b/main/webapp/modules/core/scripts/views/data-table/cell-ui.js#L99
- https://github.com/OpenRefine/OpenRefine/blob/9f7d5b878628c40d68a445b751fd50140d922e7d/main/webapp/modules/core/scripts/index/parser-interfaces/preview-table.js#L100
- https://github.com/OpenRefine/OpenRefine/blob/6095c44cb714f7b1ea6a1eac961b0394ac138a8b/main/webapp/modules/core/scripts/index/parser-interfaces/fixed-width-parser-ui.js#L338

**Comment by thadguidry** [comment]
@pyrog Can you fix the version info you reported? I think you meant 3.4.1

**Comment by tfmorris** [comment]
Per the discussion here https://github.com/OpenRefine/OpenRefine/pull/2540#pullrequestreview-391997062 our intent is to switch to just using Javascript's built-in `URL()` constructor which would presumably fail on this text and not link the cell.

**Comment by thadguidry** [comment]
OK, I misread the need as described by @pyrog and I don't think I agree with their need.
Instead, I think the need to have clickable links is still attainable by storing URLs in Record rows, where 1 URL per cell is encountered.

But @pyrog wants to just hand edit cells?  That's not really what OpenRefine is designed for.  I don't think that kind of suggested handling is needed at all.  If there is a cell that has multiple values of URLs, then it can be easily split into Record rows by using GREL `smartSplit()` or the menu option Edit Cells -> Split multi-value cells.

So, I would suggest closing this.

**Comment by tfmorris** [comment]
As a convenience, OpenRefine links cells who's contents consist of a well-formed URL. It shouldn't link cells where the text is not a well formed URL (e.g. multiple URLs concatenated together). If we fix the `looksLikeUrl` function, this problem will go away.

**Comment by thadguidry** [comment]
@tfmorris Are you suggesting that there is a better way and that a "clickable" URL link could be exposed on the Javascript side?  This would work even with URLs that are within very long strings or sentence paragraphs in a cell?  If you think that is possible, then that sounds like agreeable.  I just didn't think it was possible, but I guess anything can be made "clickable" in Javascript if you parse it correctly and dynamically create hrefs?

**Comment by tfmorris** [comment]
No, I'm not proposing that we parse megabytes of XML looking for dozens of URLs to highlight. I'm proposing that only cells who's entire content consists of a single well-formed URL get linked. That would address this case of a malformed link being created (ie the cell would not be linked).

**Comment by pyrog** [comment]
>But @pyrog wants to just hand edit cells? That's not really what OpenRefine is designed for. I don't think that kind of suggested handling is needed at all.

Of course not. It was an example to reproduce the bug 😉 
I work on a file of 55113 contacts.

>If there is a cell that has multiple values of URLs, then it can be easily split into Record rows by using GREL smartSplit() or the menu option Edit Cells -> Split multi-value cells. And then they would get nice single URLs in each cell and would be clickable within OpenRefine.

Yes.

The issue is if OpenRefine build a link, it must be valid 😃 

To solve this issue, I see two solutions:
* check  if the URL contain all the cell, or just a part in `URL.looksLikeUrl()`
* add the `<a href="…">…</a>` tags inside the `looksLikeUrl()` so it will work for one or more URLs inside a cell.<BR/>In this case you just have to parse 50 X Columns, not "megabytes of " data.

**Comment by singhakshita** [comment]
@wetneb @thadguidry @tfmorris  after the PR #2519  ,i guess this issue must have been automatically resolved?

**Comment by singhakshita** [comment]
i guess after the PR for the issue #2519 this issue must have automatically been resolved?

**Comment by wetneb** [comment]
Thank you, indeed!
