### ISSUE TITLE
Add "remove duplicate rows" menu item

### ISSUE THREAD

**Issue by stragu** [OpenRefine/OpenRefine#3218]
After fixing inconsistencies with the clustering and merging functionality, I assume it is a common to want to remove potentially duplicate rows.

### Proposed solution

It would be great to add an item to the `All -> Edit rows` menu to be able to quickly remove duplicated rows, named for example "Remove duplicate rows".

This functionality could be either:

* Simple version: check the data in _all_ the columns and only remove rows that have exactly the same values in all columns.
* More complex, with more options: add an intermediate dialogue that allows the user to choose which columns are checked for exact duplication (with all columns checked by default).

### Alternatives considered

Currently, a few tutorials and videos [are](https://programminghistorian.org/en/lessons/cleaning-data-with-openrefine) [floating](https://kb.refinepro.com/2011/08/remove-duplicate.html) [around](https://guides.library.illinois.edu/openrefine/duplicates) with instructions like the following:

1. Sort by columns that will guarantee that duplicates will be grouped together
1. Make the sort permanent with `Sort -> Reorder rows permanently`
1. Blank columns down with `All -> Edit columns -> Blank down`
1. Facet by blank on a column that is expected to have data for all unique items
1. Select the blank rows (i.e. the `true` value)
1. Remove all matches with `All -> Edit rows -> Remove matching rows`

This is hardly intuitive nor straight-forward.

**Comment by wetneb** [comment]
This issue was brought up in today's community call as useful addition to OpenRefine. I have also heard this need expressed multiple times. I'd intuitively go for the more complex approach described above, because I think checking the data in all columns is not going to be too simplistic to be widely useful. Perhaps it would be good to have a proposed UI for this @cooperzoe?

**Comment by wetneb** [comment]
> Is there an extra "not" in there?
Good catch!

> I'd be wary of such a destructive operation without any way to preview its affect.

As long as it can be undone just like any other operation, to me it doesn't feel so much more destructive than, say, removing columns or rows. I am also not sure how to present a preview in this case, what would it look like?

>  Would this be better implemented as a facet, perhaps extending the Duplicates Facet to work on multiple columns, which could then be used to delete all matching rows?

The problem with using the duplicates facet is that it would only let you remove all rows in a group of duplicates.
To me it would be useful if the operation could keep the first row of each group of duplicates. (Maybe that would even be a sensible default?)

**Comment by sunilnatraj** [comment]
@wetneb Created an implementation for duplicate rows removal. Can you review the flow.


https://github.com/user-attachments/assets/109f8e71-5b08-431c-8bb7-70bb793aece4

**Comment by ostephens** [comment]
@sunilnatraj can you explain the "Confirmation deletion of project history" step? I don't understand how or why this action is overwriting history entries, and I don't understand the two history entries identified in that dialogue?

**Comment by sunilnatraj** [comment]
@ostephens I also noticed the overwrite confirmation, let me get details and share.

**Comment by sunilnatraj** [comment]
@ostephens The project history deletion confirmation came up because I had reverted to a previous version of project data, so when I performed the "remove duplicate rows" action, the confirmation prompt came up.

>> changes that have been undone and will be erased by any new operation applied in this state

**Comment by ostephens** [comment]
Thanks @sunilnatraj. So this has no connection to the remove duplicate rows but just happened because you were working in a situation where this change happened to create a new history - got it!

**Comment by sunilnatraj** [comment]
@ostephens @wetneb Let me know if the flow is as expected

**Comment by magdmartin** [comment]
@sunilnatraj  thank you for working on this. A lot of users will appreciate it!
* Is it possible to see the history after applying the operation? I am curious about how it will be presented
* in the pop-up (10 sec in your video), we can make the text more explicit, like `Select the columns to analyze to identify duplicate rows.`. 
* How do you select which rows are preserved? Is it based on the row id? This is related to @wetneb points above:
> To me it would be useful if the operation could keep the first row of each group of duplicates. (Maybe that would even be a sensible default?) At least that's the behavior of all three workarounds mentioned in the issue description.

**Comment by sunilnatraj** [comment]
@magdmartin Thanks for reviewing & the feedback. PFB responses to your queries

- Remove duplicates operation history - see attached file
- Will this be a better label to use -> "Choose the columns to analyse for identifying duplicate rows."
- The first row in duplicates is preserved

[removeDuplicates-OpHistory.json](https://github.com/user-attachments/files/17954705/removeDuplicates-OpHistory.json)

**Comment by sunilnatraj** [comment]
@wetneb @magdmartin Shall i raise a PR for this ?

**Comment by wetneb** [comment]
Yes please, we can continue refining the design in a PR.
