### ISSUE TITLE
Allow easier install and uninstall on Windows

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3224]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24500%20Rewarded-%237E24E3.svg" />](https://oss.issuehunt.io/r/OpenRefine/OpenRefine/issues/3224)

On Windows, OpenRefine currently has a manual process to extract, install, and create desktop shortcuts and configuration.
 
### Proposed solution
- Create a native installer for OpenRefine on Windows (one that produces an .exe or .msi) that runs without any dependency or other software needed to be preinstalled.
- Install and Uninstall should be available in Add/Remove Programs for OpenRefine.
- Ensure custom folder path input is available during install.
- Have option to create desktop shortcut and add OpenRefine to Start menu.
-

#### INNO
----

[Inno Setup](https://jrsoftware.org/isinfo.php) is the most likely candidate for helping packaging a proper installer for Windows with automatic desktop shortcut handling and uninstall.
Inno provides automation through both Inno Setup Scripts (.iss files) as well as Pascal scripting (modern Delphi-like Pascal)

Licensing - Inno seems to have a compatible license, and a simple acknowledgement in our docs is all that is needed, I think.  Item 3 in Inno Setup License: https://github.com/jrsoftware/issrc/blob/main/license.txt

CI/CD and packaging methods - I think using the GitHub Actions VM image Windows Server 2019 would provide the necessary toolkits that are required for Inno Setup as it already includes InnoSetup 6.0.5 (latest stable version) as well as the .Net CORE components.  See https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md

#### NSIS
----

[Nullsoft Scriptable Install System - SourceForge.net](https://sourceforge.net/projects/nsis/) (NSIS)
https://github.com/NSIS-Dev

There is a Maven plugin: https://github.com/DigitalMediaServer/nsis-maven-plugin (which seems to be cross-platform itself too)
VSCode has the NSIS Plug-ins for IntelliSense https://github.com/idleberg/vscode-nsis-plugins

### Alternatives considered
[WiX Windows Installer](https://wixtoolset.org/) was considered but it doesn't leverage the latest Windows 10 SDK handling.

### Additional context
none for now

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $500.00)

- [<img src='https://avatars.githubusercontent.com/u/2538880?v=4' alt='openrefine' width=24 height=24> openrefine](https://oss.issuehunt.io/u/openrefine) ($500.00)

### Submitted pull Requests
- [#5833 Add Windows installer using InnoSetup 6](https://oss.issuehunt.io/r/OpenRefine/OpenRefine/pull/5833)
---

### Tips

- Checkout the [Issuehunt explorer](https://oss.issuehunt.io/r/OpenRefine/OpenRefine/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://oss.issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by tfmorris** [comment]
`jpackage` may be something worth keeping an eye on as it matures. https://openjdk.java.net/jeps/343

> but it doesn't leverage the latest Windows 10 SDK handling.

Can you explain what the impact of this is for those not au fait with the latest Windows developments?

**Comment by thadguidry** [comment]
@tfmorris Notifications.  When a program is installed or uninstalled or has a problem installing, Inno like other modern installers for Windows 10 can notify the user through the action center. https://support.microsoft.com/en-us/help/17203/windows-10-find-notifications.  I think it also might be possible to have [Toast Notifications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-desktop-apps) for upgrade versions to show up in the action center as well, from my reading on the Inno support forums, but didn't dive into all the details, and might not work in our case.  This is all about details with [UWP and Fluent Design](https://docs.microsoft.com/en-us/windows/uwp/)...something I also am not 100% up to date on either, but know it well enough from a user perspective and meandering the UWP platform a few years ago to try to code a custom disk driver notification.

Yes, I've mentioned `jpackage` before (some issue we have prior), but not sure how much it leverages UWP features, and would have to research more.  I do know that it is still a big wish for OpenJDK to enhance it even more, but its been prioritized less.  It still needs Wix.

> Dependencies
> Native packages will be generated using tools on the target platform. For Windows, there is an additional tool that developers will need to install if they want to generate native packages:
>
>    Wix, a third-party tool, is required to generate msi or exe packages
>
>There are efforts underway to enhance jlink to generate native launchers in a future version of the JDK. Some level of coordination may be needed between jlink and jpackage.

At any rate, totally open to others helping research all this a bit for all of our benefit.  Even prototyping `jpackage` and happy to test on my system.

**Comment by wetneb** [comment]
We should also consider NSIS, a popular alternative to Inno Setup, which seems to be able to run cross-platform.

There is a Maven plugin: https://github.com/DigitalMediaServer/nsis-maven-plugin (which seems to be cross-platform itself too)

Note that installing programs can require administrator rights that users might not have. So it might still be useful to offer a `.zip` archive for those use cases. Potentially, the `.zip` archive could be a portable version of OpenRefine (which stores its workspace in a subdirectory of the application folder, so that it can be run off a USB key for instance).

**Comment by thadguidry** [comment]
@wetneb Yeah the old Nullsoft Scriptable Install System (NSIS) is a great alternative to Inno.
It is good enough for now perhaps.
I don't think it can produce the MODIFY arguments for Windows 10 installations, but that's fine, if folks want to modify the installation location of OpenRefine, they can just UNINSTALL/REINSTALL.
I also don't think it supports the Windows 10 Notifications?, but again, that's fine and just a convenience mostly.
Our users have simple needs here, and even this helps those that want to massively deploy and setup OpenRefine on multiple workstations in student labs via scripts.
Speaking of which we do still have those Start and Stop scripts in our repo, but that's orthogonal, and they can stay as is and don't have impact on a Windows installer.

From a development perspective, I do see that VSCode has the NSIS Plug-ins for IntelliSense which is nice.
https://github.com/idleberg/vscode-nsis-plugins

**Comment by abitrolly** [comment]
Does https://community.chocolatey.org/packages/openrefine work?

**Comment by wetneb** [comment]
@abitrolly I would expect a non-portable install as well (with installer / uninstaller). This is what this issue is focusing on.

By the way the OpenRefine project has funding available to work on this. Do you know someone who would be able to get this fixed? Send them our way!
https://openrefine.org/blog/2022/09/30/windows-macos-packaging.html

**Comment by EmidioStani** [comment]
Izpack seems still maintained

**Comment by thadguidry** [comment]
@EmidioStani The problem with lzpack is that it is non-native (it requires users to have JVM installed already).  We would like to avoid that and use something that can create a native installer.
@wetneb should we update the proposal to list that requirement of being a native installer (one that produces an .exe or .msi) that runs without any dependency or other software needed to be preinstalled?

**Comment by EmidioStani** [comment]
Hello @thadguidry I understand your point (no requirements for the installer), however Java is required for OpenRefine itself.

**Comment by wetneb** [comment]
Yes, but we want to make it possible to install OpenRefine without having installed Java beforehand (by embedding Java in OpenRefine, like we currently do for one of the windows zip files). Downloading Java on the fly during install would also be an option, I think.

**Comment by thadguidry** [comment]
>  Downloading Java on the fly during install would also be an option, I think.

Jbang helps with that, but again, it's another tricky thing to install for probably many users prior to using OpenRefine.

**Comment by wetneb** [comment]
Here is a summary of what I see as possible approaches for this issue:

## Requirements

* The installer that users download should be able to run even if Java is not installed yet. The installer should be able to install Java alongside OpenRefine, either by including a Java runtime environment in the installer or by downloading it on the fly during the install process
* The generation of the installer should be integrated in our Maven build files (in `packaging/pom.xml`). It should run in our CI system (hosted on GitHub Actions). See [examples of those runs](https://github.com/OpenRefine/OpenRefine/actions/workflows/snapshot_release.yml) - the packaging work is currently happening in the `mac_test_and_deploy` subtask (running on MacOS). If the tool adopted is not cross-platform, then the packaging task to create this installer could take place in a Windows job (such as the one we use in the [pull request workflow](https://github.com/OpenRefine/OpenRefine/actions/workflows/pull_request.yml)).
* The tool used to generate the installer should be available under a license that makes it compatible with OpenRefine's BSD license

## Tools that could be used

### InnoSetup

* Either called directly from Maven via an antrun goal, which is [what Gephi does](https://github.com/gephi/gephi/blob/9c2ec9e2bd2760e1728721cfa8ef77481678dc6f/modules/application/pom.xml#L622-L652)
* Or via a Maven plugin such as [JavaPackager](https://github.com/fvarrui/JavaPackager)

InnoSetup can only be run on Windows, so we would need to run this packaging goal on the Windows job of the CI.

### NSIS

* Either called directly from Maven via an antrun goal (similar to the above)
* Or via a Maven plugin such as [nsis-maven-plugin](https://github.com/DigitalMediaServer/nsis-maven-plugin) (but beware, this one does not seem actively maintained)

One advantage of using NSIS over InnoSetup is that it can be run on other platforms (so we could keep the packaging task on the MacOS job of the CI, for instance).

### jpackage

The [jpackage](https://docs.oracle.com/en/java/javase/14/docs/specs/man/jpackage.html) tool, part of the JDK, can be used to generate installers in `.msi` format. (See for instance [this example video](https://www.youtube.com/watch?v=0Q04rZYjsNU).)

This could likely be called from Maven as well (either via antrun or some Maven plugin). This would only be possible on Windows, too.

### Others?

Perhaps other tools fit the bill mentioned above.

**Comment by tfmorris** [comment]
> The installer should be able to install Java alongside OpenRefine, either [...] or by downloading it on the fly during the install process

Requiring heavy downloads can be challenging in a teaching environment where an entire class is trying to download at once, so I'd lean towards bundling a JRE, if possible.

**Comment by abitrolly** [comment]
Are there installers for Windows that are capable of using WSL for running software in containers or just native apps from Linux environment?

**Comment by magdmartin** [comment]
@thadguidry @wetneb should we close this issue?
