### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#3226]
As [announced in 2018](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps) travis-ci.com is to be used for both open source and commercial projects. In December 2020, travis-ci.org will be [going away](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom), so we need to move before then.

Migration instructions are here: https://docs.travis-ci.com/user/migrate/open-source-repository-migration

The travis-ci.org builds will become read-only after the migration, so they can't be restarted, etc, but activity seems pretty low right now, so I don't know if we need to do any upfront coordination of the migration. Opinions?

**Comment by wetneb** [comment]
Thanks for taking care of this! I can't think of anything that would be conflicting with it.

**Comment by tfmorris** [comment]
Migration complete for the main OpenRefine repo and it doesn't look like any of the other repos have Travis CI builds enabled.
