### ISSUE TITLE
Patch for /trunk/main/src/com/google/refine/ClientSideResourceManager.java

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#324]
_Original author: thadguidry (January 28, 2011 23:00:42)_

StringBuffer can be replaced with StringBuilder

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=324_
##

**Comment by wetneb** [comment]
@thadguidry should this (#322) be re-submitted as pull requests?

**Comment by thadguidry** [comment]
@wetneb Close this one.  There's additional work that will eventually happen in the java 8 refactor branch along with the StringBuilder replacement.

As for #322 There are little things around general code cleanup that will be done, most of those come from hints from IDE's and code coverage tools like Jacoco, etc ... all of which we plan to do systematically in several phases.  Some of which is hinged on the performance enhancements first I think.

I would prefer that we tag more issues into our 3.0 Milestone and mark them with several Parent issues that have a label or Milestone.   The individual tasks in the issues are marked as Github Task Lists.  Basically, just start organizing all these old issues and as well as the cleanup that your doing (and thanks for that!).  You can create more Labels as well.  Here's how to do task lists. (there's a button at the top of the issue editor)
`- [] This is first task`
`- [] This is second task`
- [ ] This is first task
- [ ] This is second task

**Comment by wetneb** [comment]
Yep, I have used this syntax a few times already, for instance in #1213 .
