### ISSUE TITLE
Allow option for comments in Json files to be ignored during import

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3243]
Json comments are not supported with the Json Importer and it would be nice if an option was added.

### Proposed solution
Add checkbox option to Json Importer to **Allow  comments in json files**
When selected, `/*...*/` blocks and the line comments `//`, and `#` are interpreted as comments and get ignored (instead of causing silent errors within Jackson importer, I think)

The following would be parsed with the Json Importer and when the option is checked, it will ignore all the comment lines and parse the remaining Json object without errors.  If unchecked, then it would parse and detect an error and advise user onscreen somehow (popup, or directly within the preview panel as an error text string, whatever works best to notify user at this current architecture level of OpenRefine).

```json
/* These are a block of
line comments for this JSON file and
should not cause errors ...
*/
/* This is also a block */
// This line is also ignored instead of causing errors
# This line is also interpreted as comments and gets ignored instead of causing errors
[{
  "foo":"bar"
}]
```

### Alternatives considered
keep silent as we currently do without any clue to the user why they are staring at no data on the preview and no errors or sign of something happening.

### Additional context
Jackson supports this option https://github.com/FasterXML/jackson-core/wiki/JsonParser-Features#support-for-non-standard-data-format-constructs

> ALLOW_COMMENTS (default: false) (for textual formats with concept of comments)
>
>    For textual formats that do not have official comments, but for which "de facto" conventions exist (like JSON), determines whether use of such unofficial comments is allowed or not
>    Supported for: JSON
>    For JSON: enabling the feature allows recognition and handling of "C comments" (/* ... */) and "C++ comments" (// ....)
>    YAML supports its own "hash comments" regardless of this setting

**Comment by wetneb** [comment]
Although this is not part of the standard, if Jackson supports it, it might not be hard for us to also support that.
Marking as a good first issue for this reason.

**Comment by SeliasB** [comment]
Hi, I am currently working on it, hope it's ok !

**Comment by SeliasB** [comment]
I was wonering if the gui has been generated by a framework, or do I have to manually add the checkbox and the binding of it ?

**Comment by thadguidry** [comment]
@SeliasB Thanks for volunteering to work on this issue.  We use Jquery, pure Javascript for customizations, and Java backend.  You'll see bindings of lots of options in the various **importers** that you can get an idea from and copy from for a checkbox style to be added to the JSON importer (which already has some options already within it).

**Comment by SeliasB** [comment]
@thadguidry 
thanks for the answer, I'm having a trouble at the moment. I added the checkbox and binded to the options in Javascript but it is not added on server side (in the request response) so not sure how the link is made on client side to make it available on the backend.
any tips plz?

**Comment by tfmorris** [comment]
The original ask was for an option, but this seems to be a hard coded change to the default behavior. Is that intentional?

The lack of any error message, as originally reported, indicates to me that the error handling needs to be cleaned up, so I've created #6454 to cover that aspect of things.

**Comment by wetneb** [comment]
> The original ask was for an option, but this seems to be a hard coded change to the default behavior. Is that intentional?

To me yes, see the rationale here: https://github.com/OpenRefine/OpenRefine/pull/4834#pullrequestreview-965406561
But if you see a use case for an option, I'm open.

**Comment by thadguidry** [comment]
The use case of having an option was so that users could edit and use the data that is sometimes inside the comment lines. Using facets they can filter out the first X rows, and also copy/paste metadata from within comment lines into actual real row cell values as necessary. The comment lines sometimes hold partial schema annotations and metadata. That's why the option to keep the comment lines is useful, thereby letting the users data wrangle with the lines themselves and create a full project for export that includes the incorporated metadata into JSON record row headers and then export.

@wetneb Please make this a checkbox option with default OFF. We want to continue to give choices to users, not make them for them. "Smart defaults with options - always." Thanks.

**Comment by wetneb** [comment]
I don't understand how turning this off would let people extract metadata from JSON comments. If we make this option, then:
* when the option is on, JSON files with comments would be successfully imported (ignoring the comments)
* when the option is off, JSON files with comments would be rejected.

Can you think of a use case where it would be important to make sure the import fails if the JSON file contains any comment?

I suspect you have another option in mind (which could be indeed interesting to have): one that would turn on importing the contents of those comments in the OpenRefine project.
The challenges to support that are that:
* I don't know if our JSON parser makes it possible to parse JSON files with comments and inspect the contents of such comments.
* We would need to decide how those comments should be inserted in the table generated by our tree to table machinery. Since those comments can probably show up anywhere, I can imagine it being a bit messy

**Comment by wetneb** [comment]
Thanks for the example! It would be interesting to also have an example of the sort of table you would want OpenRefine to create out of such a JSON file, importing comments in the table. But I would propose we do this in a new issue, because if you read again your issue statement above, it's pretty unambiguous that it's about *ignoring* JSON comments.

**Comment by thadguidry** [comment]
This absolutely would be a new feature.  Another layer to JSON importer (hell even maybe an extension? dunno).
I'll create the new issue for extending the JSON importer to support this and give examples.
In the meantime, I guess we can close this issue, if the option to ignore comments, or otherwise return a JSON parsing error...is forthcoming from the PR and Tom's other PR later?

**Comment by thadguidry** [comment]
Actually, My old team needed the JSON metadata comment to rows feature.  My new team (just asked them), are just fine with manually handling the comments and the ignore comments option is all they needed.  IF anyone from my old team pings me that they need that comments to rows feature, I'll open the new issue...until then...thanks all for completing this issue!
