### ISSUE TITLE
Replace log4j 1.2

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#3247]
Apache log4j 1.2 was EOL'd in 2015 http://logging.apache.org/log4j/1.2/index.html

It needs to be replaced with either log4j 2.x http://logging.apache.org/log4j/2.x/log4j-slf4j-impl/index.html
or another SLF4J compatible implementation. I suspect log4j 2.x is the way to go.

**Comment by thadguidry** [comment]
And in working on this issue,  I imagine it should also resolve my issue #1832

**Comment by bradthurber** [comment]
Should this be closed now that OpenRefine is using log4j 2?
