### ISSUE TITLE
Support for custom data types in OpenRefine-Wikibase integration

### ISSUE THREAD

**Issue by lozanaross** [OpenRefine/OpenRefine#3263]
There is a problem when trying to work with custom data types in the OR-Wikibase integration extension.

### To Reproduce
1. First, reconcile data to Rhizome's custom Wikibase.
2. Then, build schema which includes property with custom data type (in this case – media file that is not Commons media file).
3. Finally, try to upload to Rhizome's Wikibase instance.

### Current Results
Right now I get a message that indicates the desired data type is unsupported when adding the new property to the schema. The corresponding value field goes red initially, but then it still allows me to drag a column with values into it and even renders a correct preview. I am then able to select Upload option, but get stuck at 0%.

### Expected Behavior
If this feature doesn't work, it should't even allow me to get to Preview and Upload stage. It would be great if custom data types were supported in the future, though. At least custom media files, as this is pretty fundamental feature to every independent Wikibase instance outside Wikidata.

### Screenshots
![Screenshot 2020-10-14 at 14 46 18](https://user-images.githubusercontent.com/25489750/95993518-e309ea00-0e37-11eb-859e-7e7d01858f32.png)
![Screenshot 2020-10-14 at 14 46 29](https://user-images.githubusercontent.com/25489750/95993530-e604da80-0e37-11eb-87c3-d100c97a9219.png)
![Screenshot 2020-10-14 at 14 46 42](https://user-images.githubusercontent.com/25489750/95993536-e8673480-0e37-11eb-8020-53beaefc3119.png)

### Versions
- Operating System: MacOS Catalina 10.15.6
- Browser Version: Google Chrome Version 84.0.4147.135 (Official Build) (64-bit)
- JRE or JDK Version: JRE 1.8.0_261
- OpenRefine: OpenRefine master branch as of 14.10.2020->

### Datasets
Property in question is here: https://artbase.rhizome.org/wiki/Property:P126

### Additional context
Thanks to a new extension built by Professional.wiki, Wikibase instances can now use a new data type for custom images that are not Commons media files. In the future even further data types could be added. This is not handled well within the current OR interface, but it is an important feature moving forward.

**Comment by wetneb** [comment]
There are two subtasks to this:
* Improving the user experience with unsupported datatypes (making sure the schema cannot be built at all in this case). I would suggest making the property input invalid (red).
* In general we cannot add support for arbitrary datatypes as we just don't know what sort of data they expect. But many new datatypes use string datavalues and we can support these uniformly. We should find out if we can detect the datavalue type of an unknown datatype through the API. Failing that, we could add support for local media files as developed in this Wikibase extension.

**Comment by lozanaross** [comment]
Thanks @wetneb – do you want me to split this into two issues: one being a bug about the UI not giving enough meaningful user feedback, the second being a feature request to support new data types. I will request at least support for the local media data type, I think that would be the most significant for now.

**Comment by wetneb** [comment]
Thanks, that would be useful! We could keep this one for the support for new datatypes and open another one for the UX for unsupported ones, perhaps?

**Comment by lozanaross** [comment]
Sure, I'll do that – writing two more UX-related issues right now :) Sorry for being such an annoying user!

**Comment by lozanaross** [comment]
@wetneb – do you have any ideas when you might consider integrating any new data types into OR. If you have no availability until end of the year or so, that's totally fine, but could you let me know, because we have several thousand images to move at Rhizome by the end of the year and if we can't use OR, we'll need to work on an alternative via a bot. Thanks!

**Comment by wetneb** [comment]
I haven't planned to work on this soon.

**Comment by lozanaross** [comment]
OK, I understand, we'll do some temp fix at Rhizome for now.
