### ISSUE TITLE
Unable to get "Auto-match candidates with high confidence" working when reconciling to custom Wikibase

### ISSUE THREAD

**Issue by lozanaross** [OpenRefine/OpenRefine#3271]
This used to be possible and over the last week or so, it seems to be a problem, I can't get any "Auto-match candidates with high confidence" for text data. I can't identify that I'm doing anything else differently than usual, so not sure what's the issue other than a bug?

### To Reproduce
1. First, choose to reconcile text data (i.e. NOT ID numbers) against a custom Wikibase endpoint
2. Then, pick the right type to reconcile against & tick "Auto-match candidates with high confidence" 
3. Finally, see that none of the data is matched to anything & you have to do it all manually.

### Current Results
No columns with text data get matched to their high probability candidates. It has to be all done manually.

### Expected Behavior
Get auto-match suggestions, as usual.

### Screenshots
![Screenshot 2020-10-16 at 18 20 35](https://user-images.githubusercontent.com/25489750/96283576-18076f80-0fe5-11eb-8047-a6fdc27efcc3.png)
![Screenshot 2020-10-15 at 23 33 53](https://user-images.githubusercontent.com/25489750/96283593-1dfd5080-0fe5-11eb-854f-3f800521f6b3.png)

### Versions
- Operating System: MacOS Catalina 10.15.6
- Browser Version: Google Chrome Version 84.0.4147.135 (Official Build) (64-bit)
- JRE or JDK Version: JRE 1.8.0_261
- OpenRefine: OpenRefine master branch as of 14.10.2020

### Datasets
I have tried to reconcile against two available endpoints and get same issue with both:
https://reconciliation.artbase.rhizome.org/
http://rhizome-artbase.reconci.link/

**Comment by tfmorris** [comment]
The reconciliation service isn't returning any candidates at all, let alone high scoring ones. You should contact the maintainer of the reconciliation service(s), if you think it should be returning matches for your queries.

**Comment by wetneb** [comment]
Indeed, migrating to https://github.com/wetneb/openrefine-wikibase/issues/92.
