### ISSUE TITLE
Better UI feedback when building a schema with an unsupported Wikibase data type 

### ISSUE THREAD

**Issue by lozanaross** [OpenRefine/OpenRefine#3272]
I was trying to upload data to a custom Wikibase instance associated with a new property, which has a local media file data type (a new data type, non existing in Wikidata). Right now I get a message that indicates the desired data type is unsupported when adding the new property to the schema. The corresponding value field goes red initially, but then it still allows me to drag a column with values into it and even renders a correct preview. I am then able to select Upload option, but get stuck at 0%.

### Proposed solution
The property field should go red if user attempts to add a property with custom data type that is not yet supported by OpenRefine and its Wikibase extension. User should not be allowed to proceed until they rebuild their schema with different properties.

### Additional context
This relates to issue #3263

**Comment by wetneb** [comment]
No longer needed since custom datatypes are now supported as well.
