### ISSUE TITLE
Search/find for column headers

### ISSUE THREAD

**Issue by jquartel** [OpenRefine/OpenRefine#3289]
I work with data sets that can have dozens (or hundreds) of columns and I won't know where in this set a particular column resides, or if it even exits in my current data. As it stands, I think the only thing I can do is scroll along until I spot the header I'm looking for. The browser's text search helps except:
  In Apple Safari (14.0) the text can be found but the interface is subsequently broken and nothing is visible except the column headers. You have to close the project and reopen it to get the data view back.
 In Google Chrome (Version 86.0.4240.111), the text is highlighted but the data window isn't moved to where the found text is visible, so if the column is off-screen you still need to scroll to find it.
In both cases the data window is searched as well, so it's not very satisfying.

I tried using the list in 
  _All > Edit Columns > Re-order / remove columns..._
and although this is a little easier to scroll down through, you can't search it at all in Safari. Chrome does find the text but again, if it's off the window you need to scroll down until you find it.

### Proposed solution

I think it would good to add a column header search or filter tool, perhaps under the All > Edit Columns menu. It would also be handy to be able to search within the _Re-order / remove columns..._ dialog window.

**Comment by thadguidry** [comment]
@jquartel Can you be more descriptive on the Proposed solution?  What happens when you do the search and then a match is found (where and what does the search look like, where is it located in the UI, what options are there?) ... would you want to type into the search box and the data grid would scroll horizontally to the first matching column name into view as you type?  or something completely different. (an quick prototype viz for Project searching is in #2749 so take a look...are you suggesting something similar for columns?)  Just edit your original comment above to improve the proposal.  And thanks for this!

**Comment by tfmorris** [comment]
I think #213 is more closely related than #2749. Perhaps we could include the option to restrict it to column headings.

As an aside, browser Find in the Edit Columns display works for me in Chrome.

**Comment by jquartel** [comment]
@thadguidry , yes in the simplest scenario, the browser's search functionality should work the way you describe. As it stands, Safari finds the text perfectly like this, but the data window is completely broken afterwards. Chrome finds the text without breaking the data view, but doesn't scroll to the found column. @tfmorris , this is also true in the Edit columns display (Chrome finds the text but you my have to do a lot of scrolling until you find the highlighted find), and if you use Safari then not only does it not search in the Edit columns dialog, but it breaks the data view in the way I mentioned earlier.

But thinking about it more, I think the Re-order / remove columns... dialog can do with a bunch of enhancements and the search could just be one of them.

It really needs a way to select multiple items from the list from one side to the other. As it stands, you can only move one at a time, so if you have 100 columns and you only want to use 3 of them, you'd had to move 97 items one at a time to the "Drop columns here to remove" space. What you want is to be able to Ctrl-A or Cmd-A select-all, move them all to the remove column, and then select the few you want to keep and move them back. Then if you add a magnifying class text search window in this dialog you will also be able to find the columns you want, and then select and drag them as necessary.

I'll try to add screen shots of the current search behavior when I get a moment.

**Comment by iomicifikko** [comment]
@jquartel Hi there, I cannot help you with the problem to visually identify a particular column but I'd like to share what I do to check a project consinstency about its columns using the **columnNames** field of the **row** object which gives as output an array containing all column names ordered as in the project, from left to right.

1. create a column that will contain all checks output (ex: _LOG_) and set is value to ""
2. 
   a. check if a column exists inside the project: `with("NameOfTheColumn", x, if(row.index==0, if(forEach(row.columnNames, y, if(y==x, 1, 0)).sum()==1, value, value + "[ERROR] The column "+x+" doesn't exist|"), value))`  This control is useful to find a mandatory column in a document where columns order is not important 
   b. check on the whole structure of the project `if(row.index==0, if(row.columnNames.join("|")=="columnListPipeSeparated", value, value+"[ERROR] Column list is not as expected|"), value)`. This is a more general control where columns inside the project shoud have a particular order.

The **row.index==1** inside the **if** statement is useful to limit the output of a general (not row related) check on the first row.

_example of step n.2a_
![image](https://user-images.githubusercontent.com/61201406/98977556-0304fa00-2519-11eb-9e1c-1ff86f93c082.png)

**Comment by jquartel** [comment]
Thanks for this tip @iomicifikko! I found I could do this a little more succinctly (though with less descriptive message) with something like: `if(cells["NameOfColumn"]==null,"Doesn't exist","Is ok")`
But I would still like to be able to find the the column as well.

**Comment by jquartel** [comment]
3.5-beta appears to have fixed the issue with text Find operations on MacOS Safari (i.e. the interface is no longer broken after doing a find) so this is great, thank you! I still think it would be good to enhance the functionality of the "Re-order / remove columns" window, especially with the ability to select and move multiple items rather than only one at a time. If you have a few hundred columns and you only want to see 6, then the current functionality doesn't make this easy.

**Comment by jquartel** [comment]
I can confirm that the search issue with Chrome (where it wouldn't scroll the window to the located match) is also rectified in the 3.5-beta . I would say this issue is fully resolved. I might open a feature request for the extra functionality I described for the "Re-order / remove columns" window.

**Comment by wetneb** [comment]
Thank you @jquartel for the good news :)
