### ISSUE TITLE
Dead code + inaccuracy in the Find function documentation

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3291]
In #2095 we updated the `find` function to support two types of arguments: regex (`/[a-z]/`) and simple string (`"[a-z]"`).

There are two things we need to clean up there:
* The embedded description of the function does not reflect that:
https://github.com/OpenRefine/OpenRefine/blob/ac7b5a0a19c1ecaefa1ac1d9d0d26ea9baceacee/main/src/com/google/refine/expr/functions/strings/Find.java#L75
* There is a bit of dead code here:
https://github.com/OpenRefine/OpenRefine/blob/ac7b5a0a19c1ecaefa1ac1d9d0d26ea9baceacee/main/src/com/google/refine/expr/functions/strings/Find.java#L59
(at this point the `p` variable cannot be a `String`, we already know it's a `Pattern`).

**Comment by rubyAnneB** [comment]
I'll give this a try
