### ISSUE TITLE
Unit tests for the "reinterpret" GREL function

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3292]
The `reinterpret` function is supposed to help fix encoding errors, by encoding and re-decoding strings to their correct encoding.

We want to unit tests for this function, demonstrating how it can be useful. Some of these examples should be included in the documentation.

@ostephens reports mixed success with using this function in practice.

The documentation of this function should mention than in most cases, encoding errors should be solved by re-importing the project in the correct encoding. This function should only be used when dealing with inconsistent encoding in a given file.

**Comment by thadguidry** [comment]
I found 2 conversations from the past that might be looked at for use cases and tests.

https://groups.google.com/g/openrefine-dev/c/nRSRppateJw/m/HWUpjaxfIzEJ
https://groups.google.com/g/openrefine-dev/c/KtbsO6QmXqw/m/RHDAZu4QaA0J

And you can follow the early history of reinterpret by scrolling through here:
https://groups.google.com/g/openrefine-dev/search?q=reinterpret

**Comment by thadguidry** [comment]
I've also found a documentation issue for `reinterpret()` and will submit a PR to fix that now.

**Comment by thadguidry** [comment]
Also, at the bottom of this old commit to the old wiki, you can see [Stefano's `=== Part 2 - Faceting for Encoding Analysis ===`](https://markmail.org/message/esrasibbkrbms743?q=stefano+mazzocchi+reinterpret+list:com%2Egooglegroups%2Egoogle-refine-dev&page=1) which explains some usage.

We later added an optional `source decoder` parameter to `reinterpret()` that never got documented correctly, so I've submitted PR #3308

**Comment by tfmorris** [comment]
re: mixed success - Many types of character encoding (decoding) screwups are not reversible. 

Also, the web (and data) landscape has changed dramatically in the last 10 years and UTF-8 is nearly ubiquitous, so there should be much less need for things like `reinterpret()`

**Comment by thadguidry** [comment]
Yes, totally agree with Tom on those points.  But we have `reinterpret` and we should at least clean up its docs and ensure we provide basic tests for it and then be done here.
