### ISSUE TITLE
Reconciliation dialog: clicking on "Reconcile against no particular type" should select this option

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3293]
We are missing a `<label>` tag properly associated with radio buttons in the reconciliation dialog. We should check that all labels are correctly marked as such on this dialog.

### To Reproduce
1. First, click "Reconcile" -> "Start reconciling" and choose a service
2. Then, click on the text "Reconcile against no particular type" (not the radio button, the text itself)

### Current Results
Nothing happens.

### Expected Behavior
The corresponding radio button should be selected.

### Versions
 - Browser Version: Firefox 68
 - OpenRefine: master branch (3.5 snapshot)

**Comment by rachittiwari8562** [comment]
I want to work on this issue.

**Comment by wetneb** [comment]
Thanks for volunteering! Looking forward to your pull request. Let me know if you get stuck at any point.

**Comment by rachittiwari8562** [comment]
I have created a pull request for this issue.Please review it.If you find anything wrong please let me know.
