### ISSUE TITLE
Local build test fails with Wikibase testFallbackLangCodes()

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3316]
Code:  https://github.com/OpenRefine/OpenRefine/blob/692b533f683dfa961c8526a2b86f387b0596ac5c/extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbLanguageConstantTest.java#L59

Failing test for me when doing `refine build` `refine test` locally.

```
[ERROR] Tests run: 334, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.612 s <<< FAILURE! - in TestSuite
[ERROR] testFallbackLangCodes(org.openrefine.wikidata.schema.WbLanguageConstantTest)  Time elapsed: 0.604 s  <<< FAILURE!
java.lang.AssertionError: expected [null] but found [de]
        at org.openrefine.wikidata.schema.WbLanguageConstantTest.testFallbackLangCodes(WbLanguageConstantTest.java:60)

[INFO] 
[INFO] Results:
[INFO]
[ERROR] Failures: 
[ERROR]   WbLanguageConstantTest.testFallbackLangCodes:60 expected [null] but found [de]
[INFO]
[ERROR] Tests run: 334, Failures: 1, Errors: 0, Skipped: 0
```

Should this test be skipped if not on CI or not having a Wikibase instance?

Hmm, or perhaps some env variable check needs to be added to our Maven `default-test` for the **wikidata** extension?
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project wikidata: There are test failures.
```

**Comment by tfmorris** [comment]
Is this a hard failure (ie it happened more than once)? It works fine for me locally.

As an aside, the assert (and thus error message) is backwards - it's expecting "de" but got null.

**Comment by thadguidry** [comment]
@tfmorris yes I can repeat it with a `refine test` on our master.

**Comment by wetneb** [comment]
Weird, that test should not need any network access.

**Comment by wetneb** [comment]
This test has been passing reliably in the Windows and Linux CI, so closing this.
