### ISSUE TITLE
Add Apache Groovy as an Expression language

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3320]
## Update
I've begun working on this issue and coding (and was/mostly working) the Groovy extension:
https://github.com/thadguidry/refine-groovy

## Original Issue
[Groovy ](https://groovy-lang.org/documentation.html)has a syntax that is concise and straightforward, almost GREL like in nature at times.  ([Gpath expressions](https://docs.groovy-lang.org/latest/html/documentation/core-semantics.html#_expressions) and deconstruction are super powerful in Groovy! And [Groovy Truth](https://docs.groovy-lang.org/latest/html/documentation/core-semantics.html#Groovy-Truth) is typically how many of our users already think about things.)

Its sugary syntax and available helper utilities built into Groovy make it ideal for manipulating text, dates, numbers, string interpolation (Gstrings), JSON XML Slurping, and has a powerful way to create domain specific languages DSL, it also can allow our users to easily create and store custom Groovy functions via Groovy scripts and even statically compiled for faster execution.

### Proposed solution
The Groovy jar can be dropped in and a extension could be made to allow access to Groovy from the Expression editor.
Although which of the 4 ways to handle integration into OpenRefine probably needs a quick read to determine the most appropriate path for our users needs.

#### A choice to make when implementing the integration, which one?
https://groovy-lang.org/integrating.html
* Eval
* GroovyShell
* GroovyClassLoader
* GroovyScriptEngine

I'm unsure if thread safety is a concern or not.  If not, then perhaps GroovyShell can simply be used, otherwise GroovyClassLoader or GroovyScriptEngine ?

#### Custom functions for our users (their own GREL creations when they need)
One of the nice things of integrating Groovy in some of those ways can allow users to write custom Groovy scripts save them to a file folder (that Groovy can read from by default when OpenRefine is started), and then users can handle writing scripts and also importing their custom functions/classes to use within the Expression editor.

#### Dependencies can pull down automatically, but should they?
[Grape](https://groovy-lang.org/grape.html) is Groovy's dependency manager, already built-in and allows a script to do things like this:
```groovy
@Grab('org.springframework:spring-orm:3.2.5.RELEASE')
import org.springframework.jdbc.core.JdbcTemplate

doSomethingWithSpring
```

Don't know if there is some security concern here by allowing Grape configured enabled by default?
But the cool thing is allowing sharable custom functions and scripts between users by just exchanging a Groovy script, and not tons of libraries as well.  Something we envisioned for our users to be able to share GREL recipes, but with Groovy this is even more powerful.
>Grape (The Groovy Adaptable Packaging Engine or Groovy Advanced Packaging Engine) is the infrastructure enabling the grab() calls in Groovy, a set of classes leveraging Ivy to allow for a repository driven module system for Groovy. This allows a developer to write a script with an essentially arbitrary library requirement, and ship just the script. Grape will, at runtime, download as needed and link the named libraries and all dependencies forming a transitive closure when the script is run from existing repositories such as JCenter, Ibiblio and java.net.

#### Overriding env variables
It probably will also be useful to expose a few of Groovy's env variables in OpenRefine refine.ini or elsewhere so that users can override certain features of Groovy, for example, Grape's default download directory when you do a `@Grab`:

`groovy -Dgrape.root=/repo/grapes yourscript.groovy`

### Additional context
Groovy [has some differences with Java](https://groovy-lang.org/differences.html).
Groovy [has design patterns](https://groovy-lang.org/design-patterns.html) that are sometimes even easier to apply with it versus Java!
It's important to note [that in scripts, undeclared variables are assumed to come from the Script binding](https://docs.groovy-lang.org/latest/html/documentation/core-semantics.html#_variable_definition).

**Comment by tfmorris** [comment]
There's a comment here: https://github.com/OpenRefine/OpenRefine/pull/6851#issuecomment-2359918222 which suggests there might exist an extension which satisfies this need. 
@thadguidry do you have a link?

**Comment by thadguidry** [comment]
I probably SHOULD update my own issues, huh!?!?! ;-)

https://github.com/thadguidry/refine-groovy

**Comment by thadguidry** [comment]
This is now done, but the refine-groovy extension doesn't currently work without an error during startup with the OpenRefine release.  It does however work when added OpenRefine is a development built version.

Closing this as done.  New issue to be opened for the OpenRefine packaging fixes that are needed.
