### ISSUE TITLE
Are we giving users availability of all possible Locales for Date parsing and conversions?

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3322]
OS: Windows 10
OpenRefine Version:  3.4.1

Looking over things now... I'm a bit worried that we are not supporting all possible locales for our users?

https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html#SimpleDateFormat-java.lang.String-java.util.Locale-

> public SimpleDateFormat(String pattern, Locale locale)
> 
> Constructs a SimpleDateFormat using the given pattern and the default date format symbols for the given locale. Note: This constructor may not support all locales. For full coverage, use the factory methods in the DateFormat class.

usage on
https://github.com/OpenRefine/OpenRefine/blob/0990531908187e2756cdc6c437e32579f8f54d6d/main/src/com/google/refine/expr/functions/ToDate.java#L163

**Comment by thadguidry** [comment]
Additionally, which might need a separate issue as well... I cannot seem to do inline conversions? It does seem our code has the close capability in order to do this, but we don't take advantage of DateFormat and SDF in completely the write way to pull this off?  Interestingly, this is not throwing an error.

Parse a Spanish date string, convert to date, convert to Chinese locale with pattern and output as String:
```
"4, enero, 1867".toDate("es", "dd, MMMM, yyyy").toDate("MMM", "zh").toString()
```

**Comment by tfmorris** [comment]
I can't tell if this is a question, a bug report, or a feature request. @thadguidry Can you please pick one and edit it to include the appropriate information (versions, expected vs actual behavior, reproducers, etc)

**Comment by thadguidry** [comment]
@tfmorris It's a set of questions, and actually asking how some of these features work in the current code of OpenRefine.  It might just need to be explained to me more, but I still have yet to understand some of your previous comments about Locale handling from our mailing list and on the replies to @allanaaa in docs...and figure out how to manipulate Locales interactively in real-time with OpenRefine Dates.  Maybe it's not possible, but really thought it is, or could be.  Some of this I can actually do in other tools, but stumped on how to do it in OpenRefine.

I want to know how to convert Locales in OpenRefine Dates.  Would love some help. (yes, this is not necessarily a bug, but more discovery, that might led to a bug found or feature requests needed.  I felt putting it into an GitHub Issue would be better to allow us to more easily discuss and point to review code lines, etc. and come to some conclusions on Locales and Date handling.

And so I really need your expert help here, Tom.
As shown in my example, it doesn't seem to convert using the Locale as part of the String formatter.
I tried this and it gives unusual output:
**GREL:**
`"4, enero, 1867".toDate("es", "dd, MMMM, yyyy").toDate("MMM").toString("NO")`

**OUTPUT:** 
`0GMT`

This will probably make more sense to you... I have the same question as this person, but within OpenRefine GREL transforms:
https://stackoverflow.com/questions/1661325/simpledateformat-and-locale-based-format-string

**Comment by tfmorris** [comment]
There are a couple of misunderstandings here:
* `toDate()` of a date is a no-op https://github.com/OpenRefine/OpenRefine/blob/0990531908187e2756cdc6c437e32579f8f54d6d/main/src/com/google/refine/expr/functions/ToDate.java#L76-L77 Perhaps it should be an error if it's called with additional arguments which don't make any sense. 
* `toString()` has no locale support. It works in the default locale only. The function `toString("NO")` is going to interpret the string "NO" as a Java [DateTimeFormatter](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/time/format/DateTimeFormatter.html#ofPattern(java.lang.String))  format string, returning `nano-of-day` (N) and `localized zone-offset` (O) which is the result you are seeing. https://github.com/OpenRefine/OpenRefine/blob/0990531908187e2756cdc6c437e32579f8f54d6d/main/src/com/google/refine/expr/functions/ToString.java#L58 

Please create separate bug/enhancement issues for either of these things which you'd like see fixed / enhanced.

**Comment by thadguidry** [comment]
@tfmorris thanks for responding.  And what or how is this method used for in toDate() https://github.com/OpenRefine/OpenRefine/blob/0990531908187e2756cdc6c437e32579f8f54d6d/main/src/com/google/refine/expr/functions/ToDate.java#L134

**Comment by tfmorris** [comment]
https://github.com/OpenRefine/OpenRefine/blob/0990531908187e2756cdc6c437e32579f8f54d6d/main/src/com/google/refine/expr/functions/ToDate.java#L156

**Comment by thadguidry** [comment]
@tfmorris I understand now and thanks for the comment on the other issue.

I'll close this issue now, since we seem to agree that we have a documentation issue remaining in #5351 (which I also just noticed and was typing up just now which I'll discard.
