### ISSUE TITLE
Style issue in Docusaurus docs

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3329]
We have too much padding on menu entries in the left-hand side bar of the docs:

![image](https://user-images.githubusercontent.com/309908/98966100-2628ad00-250b-11eb-9027-29f097ee8426.png)

This was probably introduced by mistake in #3178.

We should restore this padding to Docusaurus' defaults - the area that needed more padding is on the right-hand side (see PR discussion).

Mentioned by @allanaaa in today's documentation meeting.

**Comment by allanaaa** [comment]
Yep, this was my fault! I wasn't clear enough about which "table of contents" might benefit from some padding.

**Comment by leoshrey** [comment]
hi @wetneb , Can you please tell me which version is this so that I can try to resolve this issue ? as I am not able to find such screen 
https://github.com/OpenRefine/OpenRefine/issues/3329#issue-741737101

**Comment by wetneb** [comment]
@leoshrey you should be able to observe this with the current master branch: https://docs.openrefine.org/

**Comment by leoshrey** [comment]
Thanks, got it

**Comment by leoshrey** [comment]
I am working on this issue. Can you please assign it to me?
