### ISSUE TITLE
Phonetic GREL function should raise an error 

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3330]
The `phonetic` GREL function does not validate its second argument, the phonetic encoding, and silently falls back to metaphone.

For instance, `"open refine".phonetic("metaphone3")` evaluates to `"APNRFN"` and so does `"open refine".phonetic(undefined_value)` or `"open refine".phonetic(null)`.

In these last two cases, we should instead throw an error, similar to the one we get with `"open refine".phonetic("invalid_encoding")` (`Error: phonetic doesn't know how to handle the 'invalid encoding' encoding.`).

**Comment by rachittiwari8562** [comment]
I think the error should be "phonetic expects second argument to be a string" because if we make a call to "open refine".photenic(soundex) the soundex argument is translated to null object  so the error should be to that a string argument is expected.

**Comment by rachittiwari8562** [comment]
I have looked into this issue and found that if second argument is a string or character without " " then the object corresponding is treated as null and in file OpenRefine/main/src/com/google/refine/expr/functions/strings/Phonetic.java there is no else case for handling this.

**Comment by wetneb** [comment]
That sounds like you identified the bug here!

**Comment by rachittiwari8562** [comment]
The first was accidentaly done so please ignore it.
