### ISSUE TITLE
Wynn and Thorn in Old English text does not get fingerprinted correctly

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3348]
Using `fingerprint` and `ngramFingerprint` should correctly transliterate (fold) the Wynn `Ƿƿ` and thorn `þ` grapheme's for modern composition.

### Current Results

`ngramFingerprint('ƿiges ƿarne')`
```
aeginrsƿ
```

`fingerprint('ƿiges ƿarne')`

```
ƿarne ƿiges
```

`fingerprint('Ƿenne bruceþ, þe can ƿeana lyt')`
```
bruceþ can lyt þe ƿeana ƿenne
```

### Expected Behavior
`ngramFingerprint('ƿiges ƿarne')`
```
aeginrsw
```

`fingerprint('ƿiges ƿarne')`

```
warne wiges
```

`fingerprint('Ƿenne bruceþ, þe can ƿeana lyt')`
```
bruceth can lyt the weana wenne
```

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: JDK8
 - OpenRefine: 3.4.1

### Additional context
https://en.wikipedia.org/wiki/Wynn
https://en.wikipedia.org/wiki/Thorn_(letter)
(Thad spent his weekend playing with Gensim (TF-IDF) and playing with Vector Space Models on some Old English texts and wanting further analysis and tried a few experiments in OpenRefine additionally and hit upon this issue)

**Comment by tfmorris** [comment]
Thorn was already supported (as was eth), so the fix just adds wynn.
