### ISSUE TITLE
Add UI tests to the CI/CD

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3352]
The CI/CD must run cypress tests
With:
* Integration to the Cypress dashboard
* Multiple browser tests
* Proper matrix configuration, maybe there's no need to trigger tests on multiple browsers for each branch

### Proposed solution
Update the travis configuration.
Run tests on 
* Linux / firefox
* Linux / chrome 
* Osx / chrome
* Osx / firefox
* Linux / Edge

### Alternatives considered
CircleCI, does OpenRefine usr Circle CI ?

**Comment by wetneb** [comment]
We do not use Circle CI at all at the moment.

**Comment by fgiroud** [comment]
@wetneb Can you please add two variables in Travis ?
* CYPRESS_PROJECT_ID
* CYPRESS_RECORD_KEY

![Screen Shot 2020-11-24 at 15 21 44](https://user-images.githubusercontent.com/6267288/100106444-d7fb9e00-2e68-11eb-9097-bb5bd4814731.png)

You will find the [values in Cypress.io](https://dashboard.cypress.io/projects/s5du3k/settings)

Thx

**Comment by wetneb** [comment]
Sure, done.

**Comment by fgiroud** [comment]
@wetneb Did you put the variable to "All branches" ?
looks like the build did not had access to them

https://travis-ci.com/github/OpenRefine/OpenRefine/jobs/449880589

**Comment by wetneb** [comment]
Yes:
![image](https://user-images.githubusercontent.com/309908/100744367-05eb6000-33de-11eb-9e74-a1b06d0852e0.png)

**Comment by wetneb** [comment]
Could also be related to #3377?

**Comment by fgiroud** [comment]
No, this build has been triggered before the Travis credits issue
Will investigate
