### ISSUE TITLE
Applying preparations to datasets

### ISSUE THREAD

**Issue by robsims1973** [OpenRefine/OpenRefine#3353]
Hi,

Apologies if this is a basic question, I just can't seem to find the functionality.

Am I able to store a preparation and apply it to a new dataset? Alternatively, can I update a dataset within a preparation?

Thanks,

Rob.

**Comment by wetneb** [comment]
Hi Rob,

For questions like this one, could you use our mailing list:
https://groups.google.com/forum/#!forum/openrefine
It is read by much more people than the GitHub issues, which should only be used for bug reports or improvement requests.

Thank you!
