### ISSUE TITLE
Speed up OpenRefine during UI tests

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3361]
During UI tests we run an OpenRefine instance in the CI and we would like to make sure that OpenRefine runs as fast as possible. We thought about the following options:
- disable saving projects to disk with auto-save
- disable fetching the latest version number from GitHub - this could also be worth exposing to users for privacy reasons (they do not want to show their IP address to GitHub every time they start OpenRefine).
- any other optimizations?

Brought up by @fgiroud during a testing meeting.

**Comment by thadguidry** [comment]
@wetneb Disable some of the extensions from auto-starting (Butterfly config) if not needed?  Don't know if that helps in some testing scenarios.  Then again, we could parallelize across a few CI nodes and run suites of tests that need whichever component parts...disabling for that particular suite any component parts that are not applicable via Butterfly?

**Comment by fgiroud** [comment]
Other ideas, specific to Cypress
* replace the API call to `core/create-project-from-upload` by `core/import-project` to speed-up project creation
* disable cleanup of project (Travis only, as tests runs on an ephemeral VM)
* use a single, immutable project for the tests that doesn't update anything (6 tests on 30 so far)

**Comment by tfmorris** [comment]
Just stumbled across this when looking for something else.

Is there are performance goal for this? The current e2e tests take about 3 1/2 minutes in CI.

**Comment by thadguidry** [comment]
I think 3 1/2 minutes is perfectly fine to test it all.  When developing locally, it's easy enough to limit to only the test(s) you need.

I think this issue should be closed.  It's only an issue when we initially developed the Cypress tests and were having to wait those 3 1/2 minutes for the CI to complete.  We now have better coverage, resolved most of the testing bugs, and so this is no longer an issue I'd say.

**Comment by tfmorris** [comment]
Since I wrote my comment I came across an email which said that the test suite was taking almost an hour, so I'm pretty sure this is obsolete.

@wetneb please reopen if you disagree.
