### ISSUE TITLE
"Help" link on custom tabular exporter window doesn't work

### ISSUE THREAD

**Issue by allanaaa** [OpenRefine/OpenRefine#3362]
### To Reproduce
![custom-tab-exporter](https://user-images.githubusercontent.com/28012148/100375640-20879880-2fdc-11eb-9238-20c25cecdeec.png)

### Current Results
When you click on the "Help" link (in the section about date formatting) it opens up a new tab and reloads the same project. 

### Expected Behavior
It should link to the new docs, I suppose? To 
https://docs.openrefine.org/manual/exploring#data-types
(Although I haven't yet explicated very thoroughly the different date format options shown here.)

If someone could confirm what the link was supposed to point to (a page on the wiki, or some other text) that would be helpful.

### Versions
 - Browser Version: Firefox
 - OpenRefine: 3.4.1

**Comment by rachittiwari8562** [comment]
I would like to work on this issue.

**Comment by rachittiwari8562** [comment]
one question though ..should i add the link directly into the html file or via javascript.

**Comment by wetneb** [comment]
I haven't checked how it is currently defined but you could just follow that, replace the existing link by the new one.

**Comment by rachittiwari8562** [comment]
Thats the problem the link is no where defined its just left blank.

**Comment by rachittiwari8562** [comment]
Also should i paste the samelink which @allanaaa has given above?

**Comment by thadguidry** [comment]
@rachittiwari8562 It's bound to `or_dialog_help`.  Doing a quick search in our repo shows these: https://github.com/OpenRefine/OpenRefine/search?q=or_dialog_help

Long story short...  It was added as part of Fabio's help 8 years ago with internationalization of our dialogs (see the Git blame).  The intent of that particular help link was to point to the Date formatting convention that OpenRefine recognizes (which is Java based).  I'm not 100% certain where that help link should point to now, but in the past on our Wiki ([and currently](https://github.com/OpenRefine/OpenRefine/wiki/GREL-Date-Functions#todateo-boolean-month_first--format1-format2--)), we link to the Java SimpleDateFormat https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html   You can check our code to see if that Custom field on the dialog is in fact still accepting only SimpleDateFormat:
```
<label for="$custom-exporter-date-custom" bind="or_dialog_custom"></label>
<input size="35" class="lightweight" bind="dateCustomInput" />
<a href="" target="_blank" bind="or_dialog_help"></a>
```
In this case, searching our repo for that bind `dateCustomInput` function and inspecting the code for the acceptable Type.

**Comment by thadguidry** [comment]
@rachittiwari8562 Did you verify that it's using SimpleDateFormat for that field? or some Javascript date library?  I did say "I'm not 100% certain", so you will have to investigate yourself.  I was just pointing to some info that I had after quick analysis, and I am not an authority...our code is the authority :-)  So double check or better yet, debug in your IDE, to ensure the code path its taking and what it's expecting, because at that point, on that dialog, and 8 years past...we have no idea. :-)  Let us know what you find in your reply.

**Comment by rachittiwari8562** [comment]
yes i have checked it.
