### ISSUE TITLE
Broken escaping in templating export

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3381]
Curly braces are used in the templating exporter to delimit expressions from the rest of the template text. Therefore if we want to use curly braces in the expressions they need to be escaped. According to the code, we are supposed to do this with `\{`, but that does not actually work.

### To Reproduce
1. First, open any project
2. Then, open the templating export dialog
3. Finally, input the following template:
```
{{"\}\}"}}
```

This is supposed to evaluate to just `}}` for each row.

### Current Results
We get `{{"\}\}"}}` instead.

### Expected Behavior
We should get `}}`

### Versions
 - Operating System: Linux
 - Browser Version: irrelevant
 - JRE or JDK Version: 11
 - OpenRefine: 3.4.1

### Additional context

Brought up while trying to document the templating exporter.

**Comment by allanaaa** [comment]
Just a note that when this is resolved we should update the text here: https://deploy-preview-3336--openrefine-docs.netlify.app/manual/exporting/#templating-exporter

(soon to be at https://docs.openrefine.org/manual/exporting#templating-exporter)
