### ISSUE TITLE
Templating exporter should have clear error reporting

### ISSUE THREAD

**Issue by allanaaa** [OpenRefine/OpenRefine#3382]
Currently when your code in the Templating exporter has a problem, the Preview window will just show "Updating..." forever. 
It would be good to have a timeout after a few seconds and report back the line/character causing the problem. If not that, then just a generic error message would be an improvement.

When your code (inside double curly braces) isn't resolving correctly (e.g. because of an extra closing curly brace) the entire expression including the curly braces just outputs as a string instead. 
This should have its own error message, instead of the string output. 

![templating](https://user-images.githubusercontent.com/28012148/101056103-9fd71800-3558-11eb-9215-176028a60e0c.PNG)

**Comment by wetneb** [comment]
At the moment the error is reported in the server logs.

**Comment by sjathin** [comment]
Hey, I would like to work on this, I tried to reproduce this, I don't see the error reported in the server logs (always) for instance when I add an extra closing curly brace there was no error on the server logs. Please correct me if I am wrong, I think this is an issue with the parser, as it does not throw an exception when the string pattern is incorrect.

**Comment by wetneb** [comment]
Ah, then perhaps I was wrong in my comment above. Your observation seems to indicate that the template is parsed incorrectly, without throwing an error?

**Comment by sjathin** [comment]
Yes, that's correct, in the screenshot below - the highlighted region shows that I have added a few extra curly braces, but there is no exception thrown. 


![Screenshot 2021-05-23 at 16 06 26](https://user-images.githubusercontent.com/29340368/119263857-10deba80-bbe1-11eb-880f-52db1dc4ca8d.png)

**Comment by wetneb** [comment]
Ok, thanks for the investigation! Feel free to assign yourself this issue if you want to work on it :)
