### ISSUE TITLE
Error on XML to CSV transformation

### ISSUE THREAD

**Issue by amaltese** [OpenRefine/OpenRefine#3387]
Hello - trying to run a batch of XML files (like attached) through to transform and export in CSV format. 

Regularly getting the following errors that make the process fail:
javax.xml.stream.XMLStreamException: ParseError at [row, col]:[59,25]
Message: The entity name must immediately follow the '&' in the entity reference. 
....
....

Working on PC with Windows 10 installed and using Chrome browser.
 
[1800011.zip](https://github.com/OpenRefine/OpenRefine/files/5645657/1800011.zip)

Thanks for suggestions on how to troubleshoot/correct this issue.

**Comment by tfmorris** [comment]
Did you get a template to fill in when you created this issue? It should have asked you what version of OpenRefine you are using.

I was able to successfully import your example file with both OpenRefine 3.4.1 and the current development version.

**Comment by amaltese** [comment]
It’s 3.4.1

No I didn’t see a template when posting.

**Comment by tfmorris** [comment]
This has gotten stale, but I'm guessing that since the attached file is "like" the ones that failed, it wasn't actually one of the failing cases. 

If you can find a reproducible failure, please re-open this issue and attach it so that we can investigate.
