### ISSUE TITLE
Choose Files no longer popping up file browser dialog in Safari

### ISSUE THREAD

**Issue by jquartel** [OpenRefine/OpenRefine#3402]
I'm using OpenRefine 3.4.1 and I found that after an update of Safari (version indicated below) the 'Choose Files' button in the 'Create Project' startup window has no effect - that is, it does not pop up the browser dialog. It is working fine in Chrome (under the same MacOS).

### To Reproduce
1. First, do ...
2. Then, ...
3. Finally, ...

### Versions
 - Operating System:  MacOS 10.14.6
 - Browser Version:  Version 14.0.1 (14610.2.11.51.10)
 - JRE or JDK Version: 
 - OpenRefine:  3.4.1

**Comment by baronmax** [comment]
Same issue - Mojave 10.14.6, Safari 14.0.1

**Comment by tfmorris** [comment]
It work fine for me using Safari Version 14.0.1 (15610.2.11.51.10, 15610) on OS X  10.15.7 with OpenRefine 3.4.1.

Do you see any errors on the Javascript Console (Develop menu)? For the file pickers in other web apps work? This is pretty basic functionality which is implemented entirely by the browser/operating system. Our only involvement is putting the <input> field on the web page, so it's strange that it would break (although Apple is always finding wondrous and bizarre new ways to break things).

**Comment by jquartel** [comment]
Can you tell me how to get to the develop menu? I don't know of many other sites that open the the browser for file upload but after dong a bit of digging I do think that this functionality is indeed broken on other sites as well. And it looks like this is only with OS X 10.14.6 (Mojave). So probably we can chalk this up to a Safari+Mojave bug, rather than OpenRefine.

**Comment by jquartel** [comment]
Looks like Safari 14.0.2 (with Mojave) still has the issue, and it's with all web applications, not just OpenRefine.

**Comment by wetneb** [comment]
If this happens with all web applications, let's close this as there is nothing to fix on our side.

**Comment by jquartel** [comment]
Agreed.
