### ISSUE TITLE
Add UX Test for the projects list

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3413]
Improve the tests we have on the projects list page (project management)

![Screen Shot 2020-12-16 at 13 08 48](https://user-images.githubusercontent.com/6267288/102346960-ff451700-3f9f-11eb-80ba-bf1e18df9b41.png)

#### Test the "About" panel

* Editing of metadata
* test the panel

#### Test the Delete behavior

Test project deletion and ensure it's been really deleted, not only removed from the list.

#### Test the sorting of tagging list
To be tested

* Sort by tags
* Filter by tags

**Comment by kushthedude** [comment]
Hi @fgiroud, I just had a doubt, are we scraping the projects which we are creating while testing? I see a few random projects which were created during tests not being deleted.
<img width="1075" alt="Screenshot 2021-01-09 at 11 09 08 PM" src="https://user-images.githubusercontent.com/44091822/104104706-bac34780-52cf-11eb-8c7b-d734aeccedc5.png">

**Comment by fgiroud** [comment]
Yes, supposedly, see `support/index.js`, this file contains a hook that is executed after each test. And it's supposedly cleaning the projects.
Is that possible that failed scenarios do not execute the hook?

**Comment by kushthedude** [comment]
> Is that possible that failed scenarios do not execute the hook?

Yes, failed scenario doesn't execute the hook, as well a few projects still remain even after a successful test.

**Comment by tfmorris** [comment]
Remember that the OpenRefine server only saves to disk every few minutes, so if it's killed before the project deletion has been persisted, they may still remain.

**Comment by kushthedude** [comment]
> Remember that the OpenRefine server only saves to disk every few minutes, so if it's killed before the project deletion has been persisted, they may still remain.

Will this error occur if I use openrefine UI to perform each deletion?
