### ISSUE TITLE
Add UX Test for controls at the row level

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3414]
This tests intent to ensure the behaviors of the features at the row-level

![Screen Shot 2020-12-16 at 13 12 56](https://user-images.githubusercontent.com/6267288/102347280-7b3f5f00-3fa0-11eb-99c7-2349cc157159.png)

### Proposed solution

Add test for controls that sit at the very left of each row in the grid.

### Flag

Flag, unflag one and several rows. Ensure that the flag icon is colored in yellow.

### Star

Star, unstar one and several rows. Ensure that the star icon is colored in yellow.

**Comment by S-Harshit** [comment]
I would like to work on this.

**Comment by S-Harshit** [comment]
@fgiroud How can I check that flag and star are colored yellow, do I have to do a visual test?.

**Comment by thadguidry** [comment]
> 
> 
> @fgiroud How can I check that flag and star are colored yellow, do I have to do a visual test?.

They are png/svg.  We don't need to check color for tests.
We need to only test:
1. Star and Flag appear on a row.
2. Star and Flag can be toggled and verify this perhaps visually or with some attrib or selector

**Comment by S-Harshit** [comment]
@fgiroud Thank You, Can you also tell what should be the name of the test file and where it should  be placed

**Comment by fgiroud** [comment]
@S-Harshit the files should be
* grid/all-column/star.spec.js
* grid/all-column/flag.spec.js

You do not need to do visual testing, you can just check that the links have `have data-table-star-off/on`, same for flags
Another way of doing it would be tocheck with cypress assertions `expect($el).to.have.css('background-image'`, but I think testing a class is agnostic, and therefore a better way to do testing
