### ISSUE TITLE
Add UX Test for the grid header / show as records-rows

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3416]
Add test for the feature that shows records as rows, as records

![Screen Shot 2020-12-16 at 13 21 58](https://user-images.githubusercontent.com/6267288/102348151-bd1cd500-3fa1-11eb-9f64-0a666e00923c.png)

### Proposed solution

Add a test to show as rows, records and
* load a project of CSV data, show as row/records, ensure nothing changes
* load JSON data, and test the rendering as rows, as records

Exact expected behavior of this feature to be reviewed

**Comment by thadguidry** [comment]
Let's make sure the JSON has at least 3 levels of hierarchy to ensure a good Records handling basic test.

**Comment by fgiroud** [comment]
Looks like this test is failing from time to time, detached element from the dom

- https://dashboard.cypress.io/projects/s5du3k/runs/713/overview
- https://dashboard.cypress.io/projects/s5du3k/runs/702/overview
