### ISSUE TITLE
Add UX tests for the sorting

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3418]
Enrich and improve the tests we have on the sorting
Test all sorting capabilities of OpenRefine, with a given project

![Screen Shot 2020-12-16 at 13 27 47](https://user-images.githubusercontent.com/6267288/102348775-a75bdf80-3fa2-11eb-84d2-a77dc062a565.png)

#### Test for sorting from the column dropdown

Test sorting behaviors from the column dropdown

* test the sorting of the Water column, using text sort, number sort, the sort should be different
* Cast a column to a boolean, test the boolean sort
* Test the text sort a-z, z-a, and with case-sensitive values
* With a given sort, test the different combinations for Blanks, Valid values, Errors

#### Test the sorting from the grid header

Once a sort is added from the column dropdown, sorting controls appear in the grid header

* Ensure the "Sort/remove sort" button is working
* Ensure the "Reorder permanently" is working by refreshing the page
* Test the reverse sort
* Remove the sort

**Comment by fgiroud** [comment]
Looks like some sorting tests are failing, see the failed runs in the Cypress dashboard
https://dashboard.cypress.io/projects/s5du3k/runs/302/overview

Detached element from the dom, again ;-)

**Comment by kushthedude** [comment]
Yes I have got the bug, will push fix asap
