### ISSUE TITLE
Add a complete test suite about all the facetting capabilities

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3420]
Following ticket #3419 , tests should be added for the most important facets

![Screen Shot 2020-12-16 at 13 39 32](https://user-images.githubusercontent.com/6267288/102349897-5cdb6280-3fa4-11eb-9164-29de16af1792.png)

This can be split into separate issues if the scope is too big to be implemented in a single PR.

#### Text
/project/column/facets/text.spec.js
Test a simple text facet.

#### Numeric
/project/column/facets/numeric.spec.js
* Test add a facet on a text value, ensure "no numeric value present"
* Test add a facet on a numeric value, ensure "no numeric value present", then cast the value and verify the facet is now working

#### Timeline
Use a dataset that contains dates to add a timeline facet, ensure the graph is there and working

#### Custom text Facet

How is that different from a simple "Text" facet"?

#### Custom numeric Facet

How is that different from a simple "Numeric" facet"?

#### Customized / Word

Add a customized / word facet and ensure some words have determined occurrences.  
Example: Using food.small, MILK should have 14 occurrences using a word facet
Test to add a word facet on a numeric value.

#### Customized / Duplicates

Add such facet, test by false/true, and count the number of occurrences in the grid

#### Customized / Test length

Add such facet, ensure the range-slider is there

#### Customized / Log of text Length

The exact scope of this test to be determined

#### Customized / Facet by null, by an empty string, by blank

Use a dataset with null values, apply the facet, check the count of rows

#### Tests where community input is required 

Scatterplot: @webneb do you have some inputs to generate a scatterplot? mines a blank
I am not sure if this is a bug or me that doesn't understand the purpose of this feature

The following tests also need to be implemented, with feedback from the community on the expected behaviors of those controls

* "customized / numeric log"
* "customized / 1-bounded numeric log"
* "customized / numeric log"
* "customized / Unicode to char-code"
* "customized / Facet by error"
* "customized / Facet by error log"
* "Customized / 1-bounded"

**Comment by fgiroud** [comment]
Note for contributors: All remaining tests does not necessarily needs to be implemented in one single PR for this issue, a good start would be to cover
- text facet
- numeric facet
- custom text facet
- custom numeric facet

**Comment by haarsh01** [comment]
Hey, I am a beginner and want to contribute in Open Source. As I know Java Script language.I want to work on this. So can I do it ?

**Comment by fgiroud** [comment]
Hi @haarsh01 
Thanks for your interest

To get started, you can start by reading those two articles in OpenRefine documentation
* [Contributing to OpenRefine](https://docs.openrefine.org/technical-reference/contributing/)
* [Tests technical reference](https://docs.openrefine.org/technical-reference/functional-tests)

Once you're okay with the setup, just let us know, and we will attribute this issue to you

**Comment by haarsh01** [comment]
Ok, I will let you know after reading the articles.

**Comment by haarsh01** [comment]
Hey, I read the two documents and cloned the code on my machine and then downloaded Java JDK but got confused after this point in downloading Apache Maven. And I want to contribute to Javascript language so why I downloaded java JDK. Please guide me in further steps.

**Comment by wetneb** [comment]
Hi @haarsh01, this thread is not suitable for asking for general help on setting up your development environment. Please use the Gitter channel or the openrefine-dev mailing list for that: https://groups.google.com/g/openrefine-dev

**Comment by fgiroud** [comment]
Scatterplots are now out of scope of this issue, and have a dedicated one, see #3754

**Comment by fgiroud** [comment]
Sure @riteshsoni123 , i also pinged you on another issue where the tests are a bit more useful IMO

**Comment by riteshsoni123** [comment]
Can I work on this issue?

**Comment by riteshsoni123** [comment]
Hello @fgiroud sorry I was inactive for few days as I was occupied in other work. I will start working on this issue in a day.
I have one doubt about the above message you sent. 
By "utility function" you mean code in file "commands.js" that need to be added to make the test light, right?
correct me if I am wrong.

**Comment by fgiroud** [comment]
Yes, absolutely, those provides additional commands to cypress tests, that are not part of the regular cypress library. We use it to avoid writing again and again the same lines of code.

**Comment by riteshsoni123** [comment]
Hello @fgiroud I saw the code written in file "facets.spec.js" which is the test for text facet. I was wondering if I could write the test for numeric facet in same way as written for text facet making necessary changes. By "writing the code in same way" I mean writing test for each small thing in the process.

**Comment by fgiroud** [comment]
Hi, yes you can get inspiration from facets.specs.js
However, those tests are testing the general behavior, not something tied to a specific facets, your tests should be as minimal as possible, testing only what's relevant and specific to a given facet

**Comment by riteshsoni123** [comment]
Hello @fgiroud in custom text facet and numeric text facet according to my knowledge everything is same as text facet and numeric facet respectively except the dialog box that appears in the beginning. I am little bit clueless on what type of test should be written for those. Almost all the test is written for dialog box in the file "facet.spec.js" after that everything is almost same.
Can you please help me with this?

**Comment by riteshsoni123** [comment]
Yes I agree with you. 
For now I have added test for numeric facet and made a pull request.
