### ISSUE TITLE
Add UX Test for column / Text filter

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3421]
Test the Column / Text filter

![Screen Shot 2020-12-16 at 13 48 08](https://user-images.githubusercontent.com/6267288/102350636-79c46580-3fa5-11eb-837f-f93cfb2d14db.png)

### Proposed solution

Add a test for the behavior with
* an exact string, check the number of occurrences
* a partial string, also check the number of occurrences
* Test case sensitive
* Test a regular expression

**Comment by thadguidry** [comment]
Also:
1. click the blue colored **reset** and **invert** links on the Text Filter facet.  (What the heck do they do?!?!?  lololol)

**Comment by fgiroud** [comment]
@thadguidry , invert/reset are to be added in #3419, because those behaviors are common to all facets

**Comment by thadguidry** [comment]
I'm saying, we need to document first...and then do the test setup for the text filter because I'm not sure of the answers for:
1.  what a **reset** does when you have a regex filter applied?  
2. what a **invert** does when you have a regex filter applied?

I'd have to go back and spin up OpenRefine 2.7 and verify how that works.  But maybe others can confirm.

**Comment by ostephens** [comment]
`Invert` finds all the rows/records that don't match the filter. It doesn't matter if the filter is a regex or plain text filter

**Comment by ostephens** [comment]
`Reset` clears all the options (invert, text in the filter box, case-sensitive, regular expression) of the filter

**Comment by ostephens** [comment]
Behaviour was documented in the PR https://github.com/OpenRefine/OpenRefine/pull/1327

**Comment by S-Harshit** [comment]
Can I work on it?

**Comment by fgiroud** [comment]
@S-Harshit can you wait a bit (few days max)? We need to finalize a few things, add the linter, then you can work on it

**Comment by ritika4554244** [comment]
plzz.. help how I can contribute in this repo

**Comment by ritika4554244** [comment]
can I work on it??

**Comment by fgiroud** [comment]
@S-Harshit @ritika4554244 thanks for your patience, we are about to merge several PRs that will contain the foundations for the tests and lots of examples, from there we will create more issues like this one, and you will be able to dig-in.
To start I suggest that you read the [OpenRefine testing documentation](https://docs.openrefine.org/technical-reference/functional-tests) and the [contributing guidelines](https://docs.openrefine.org/technical-reference/contributing) if it's your first contribution to OpenRefine
Again, thanks for your interest

**Comment by fgiroud** [comment]
@S-Harshit still intereted ? PRs have been merged and you can tackle this one if you wish
@ritika4554244 there are other issues tagged with `good first issue`, feel free to show your interest there and I will assign
Thx

**Comment by S-Harshit** [comment]
@fgiroud Thank You, Yes I will work on it.

**Comment by ritika4554244** [comment]
@fgiroud , @S-Harshit  
after running all the instruction . facing this error .
what to do now??how to proceed further.
<img width="1440" alt="Screenshot 2021-02-02 at 10 43 06 PM" src="https://user-images.githubusercontent.com/77883250/106638138-8e86a800-65a9-11eb-8e46-e3f3768983e8.png">

**Comment by fgiroud** [comment]
@ritika4554244, for getting help about the installation process of Cypress tests, please reach the dev mailing list
This ticket is only to discuss what's specific about the Text Filter test
