### ISSUE TITLE
Add UX Test for clustering

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3422]
In-depth testing is probably good for clustering
This is a placeholder ticket for far, where the community can discuss what to test for the clustering

![Screen Shot 2020-12-16 at 13 54 11](https://user-images.githubusercontent.com/6267288/102351104-328aa480-3fa6-11eb-933f-dc1cb816e71b.png)

**Comment by fgiroud** [comment]
@wetneb by any chance, do you have the dataset referenced[ in the doc for clustering](https://docs.openrefine.org/manual/cellediting#cluster-and-edit) ?, (The one with the districts, SWABBYS HOME, BALLARDS)

**Comment by fgiroud** [comment]
Also @wetneb , I am trying to play with clustering, but I am probably missing something
I have this very simple dataset, but when hitting edit cells/clustering, no clusters are detected
I was expecting to have at least "BALLARDS RIVER", with a cluster of size 2

![Screen Shot 2021-07-07 at 11 30 03](https://user-images.githubusercontent.com/6267288/124735844-b55d5780-df16-11eb-9e84-e6ec36a817e4.png)
[CLUSTER.tsv.zip](https://github.com/OpenRefine/OpenRefine/files/6776053/CLUSTER.tsv.zip)

**Comment by wetneb** [comment]
Hmm, the doc about this is not actually very helpful! It should show an example where *different* values are clustered together. I think the screenshot in the docs was taken before #4004 was fixed.
So, as a dataset you could try this:
```
SWABYS HOME
SWABYS   HOME
BALLARDS river
BALLARDS River
```

**Comment by elebitzero** [comment]
Looks like @fgiroud didn't get around to completing this. I'll take a look to see if I can finish it so we can have a Cypress test for the cluster and edit dialog.
