### ISSUE TITLE
Add UX Test for column / Edit cells

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3423]
To test every behavior under Column / Edit Cells
 
 
![Screen Shot 2020-12-16 at 13 50 24](https://user-images.githubusercontent.com/6267288/102350838-cf990d80-3fa5-11eb-9f45-16bf1e739766.png)

### Proposed solution

Add multiple tests

#### Transform

Add a simple test to append a string to a value `value+"test"`
Ensure the modification is in the grid 

#### Common Transforms

Those transforms are very straightforward and do not need to be specified.   
Simplify add a test for each one of them and ensure the values are properly modified   

#### Fill down, Blank Down

Use "Sugar Tot" on food.small dataset and 
* ensure lines 8,10 have the value of the previous cell when using "Fill down"
* ensure line 2 is blank when using "Fill blank"

#### Split multi-valued cells

Ensure several rows are created when using "Split multi-valued cells" on "Shrt_Desc"
Ensure no new rows are created when using "Split multi-valued cells" on "Water" (or any column that does not contains ",")

#### Join multi-valued cells

How does this feature works?

#### Cluster and edit

See #3422 

#### Replace

Replace a simple string in column "Shrt_Desc", such as "BUTTER" replaced by "TEST" and ensure the modification is in the grid.

**Comment by fgiroud** [comment]
I am curious about the expected behavior of split & join
See the PR

### Split

#### Splitting by length 

When splitting a cell by field length, given one single number as input, the function doesn't do anything
Bug or expected behavior ?

#### Splitting by transition

Split by transition from lowercase to uppercase
Given a grid with one single cell `BuTtEr` 
I am expecting to have one row per letter, if my understanding is correct, each time there's a transition, there should be a new cell createdright ?
So I am expecting
``` 
B
u
T
t
E
r
```

Instead I've got
```
Bu
Tt
Er
```

Bug or expected behavior ?

#### Splitting by transition

Using the examples given by the UX, the function doesn't produce any results
Tried for example
Two cells `11Abc`, `Def22` then `split by transition from lowercase to uppercase`, but it doesn't do anything
Is that the example that is not good, or OpenRefine having a bug ?

Same with `11` and `AbcDef22`. Clicking on `Test a split by transition from numbers to letters` doesn't produce any results

**Comment by fgiroud** [comment]
Looks like all of those are expected behaviors of OpenRefine
Splitting by transition works when a part of the strings is in lowercase, followed by uppercase

**Comment by fgiroud** [comment]
Actually @wetneb I still have one question
How does the join works ?
I have tried the following

```
1
2
3
4
# Expecting one cell with 1234
```
```
1,
2,
3,
4,
# Expecting one cell with 1,2,3,4,
```

But nothing seems to work

**Comment by tfmorris** [comment]
Split by case transition is directional with separate cases for lower->Upper and Upper->lower, so the behavior that you're seeing is expected.

`join` takes an array, so you'd want `[1,2,3,4].join(',')` to get your second case (unless I've got the parameters backwards).

If you're talking about "Join multi-valued cells", it's designed to work with records and join the values for the rows in the record, so you'd need a starting point like

```
a 1
  2
  3
  4
b 5
  6
```
which would give you
```
a 1,2,3,4
b 5,6
```
where a,b and 1,2,3,4 are in separate columns.
