### ISSUE TITLE
Add UX tests for column / View

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3427]
Test the Column / View dropdowns

![Screen Shot 2020-12-16 at 14 13 59](https://user-images.githubusercontent.com/6267288/102353191-06245780-3fa9-11eb-8bcd-1eafb884a7fb.png)

### Proposed solution

Add four tests,
* collapse.spec.js
* collapse_all.spec.js
* collapse_left.spec.js
* collapse_right.spec.js

The test should basically collapse one or more columns, and ensure that the columns labels are empty (or possibly just hidden).

### Additional context

See also #3415, with some very similar tests about collapsing
When collapsing, column labels are not hidden, they are removed from the DOM.

**Comment by AhwiniMirajkar** [comment]
I want to work on 3

**Comment by pcmourya** [comment]
I am interested to work on this, may I proceed with this.

**Comment by wetneb** [comment]
Let's first ask @AhwiniMirajkar if they are still working on this.

**Comment by pcmourya** [comment]
Sure sir.

**Comment by riteshsoni123** [comment]
can I work on this issue??

**Comment by riteshsoni123** [comment]
@wetneb with all due respect I would like to ask that is there a mistake in assigning this issue because I asked permission to work on this issue.

**Comment by wetneb** [comment]
@riteshsoni123 sorry, indeed!

**Comment by fgiroud** [comment]
@riteshsoni123 for inspiration, you might want to have a look at this tests : `OpenRefine/main/tests/cypress/cypress/integration/project/grid/all-column/view.spec.js`

There's a similar feature on OpenRefine, when you click on the "all" column, where you can collapse/expand, and definitively a good idea to cover this behavior at the column level.

Thx !

**Comment by riteshsoni123** [comment]
Thanks @fgiroud for the suggestion, it was really helpful.
