### ISSUE TITLE
Feature : Google Refine to use all processors

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#343]
_Original author: vincent....@gmail.com (February 28, 2011 17:54:52)_

Hi,

Would be nice if Google refine could use all processors / cores available on a server. Seems, for the moment, only one proc / core is used.
Parallelization may speed up things (I'm using GRefine on big files : from 4 go to 12 go).

Ps : very nice software. Congrats and keep up the good work.  ;)

[root@myserver google-refine-2.0]# mpstat 1 -P ALL
Linux 2.6.21.7-2.ec2.v1.2.fc8xen (myserver)     02/28/11

12:50:31     CPU   &#37;user   &#37;nice    &#37;sys &#37;iowait    &#37;irq   &#37;soft  &#37;steal   &#37;idle    intr/s
12:50:32     all   50.00    0.00    0.00    0.00    0.00    0.00    0.00   50.00   1053.00
12:50:32       0    0.00    0.00    0.00    0.00    0.00    0.00    0.00  100.00     53.00
12:50:32       1  100.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   1001.00

12:50:32     CPU   &#37;user   &#37;nice    &#37;sys &#37;iowait    &#37;irq   &#37;soft  &#37;steal   &#37;idle    intr/s
12:50:33     all   49.75    0.00    0.00    0.00    0.00    0.00    0.00   50.25   1029.00
12:50:33       0    0.00    0.00    0.00    0.00    0.00    0.00    0.00  100.00     28.00
12:50:33       1  100.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   1000.00

12:50:33     CPU   &#37;user   &#37;nice    &#37;sys &#37;iowait    &#37;irq   &#37;soft  &#37;steal   &#37;idle    intr/s
12:50:34     all   50.00    0.00    0.00    0.00    0.00    0.00    0.00   50.00   1035.00
12:50:34       0    0.00    0.00    0.00    0.00    0.00    0.00    0.00  100.00     35.00
12:50:34       1  100.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   1000.00

12:50:34     CPU   &#37;user   &#37;nice    &#37;sys &#37;iowait    &#37;irq   &#37;soft  &#37;steal   &#37;idle    intr/s
12:50:35     all   50.00    0.00    0.00    0.00    0.00    0.00    0.00   50.00   1028.00
12:50:35       0    0.00    0.00    0.00    0.00    0.00    0.00    0.00  100.00     28.00
12:50:35       1  100.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   1001.00

12:50:35     CPU   &#37;user   &#37;nice    &#37;sys &#37;iowait    &#37;irq   &#37;soft  &#37;steal   &#37;idle    intr/s
12:50:36     all   50.00    0.00    0.00    0.00    0.00    0.00    0.00   50.00   1030.00
12:50:36       0    0.00    0.00    0.00    0.00    0.00    0.00    0.00  100.00     29.00
12:50:36       1  100.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   1000.00

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=343_

**Comment by wetneb** [comment]
This is already solved by the new architecture, available in the 4.0 branch.

**Comment by tfmorris** [comment]
I'm going to close this as stale since it's almost a decade and a half old. Some of the things touched on are:
- better use of available processors / cores 
- better progress reporting to the client during long running operations
- better support of large files

Please create new issues for specific areas which could be improved with regard to multiple processors.
