### ISSUE TITLE
workspace.old.json is created twice when OpenRefine starts and recovers workspace.json

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3432]
### To Reproduce
1. First, delete all old and regular `workspace.json` files from OpenRefine workspace folder so that there are only Project folder and no `workspace.json` or `workspace.old.json` files.
2. Then, start OpenRefine and let it scan and parse the Project folders and metadata.json files within them.
3. Notice that it properly rebuilds the `workspace.json` and contains all the project id's it scanned. Great!
4. Then, import a file such as csv or Excel to preview it, but **don't click Create Project yet**.

### Current Results
Notice that there are now 2 `workspace.old.json` files in the OpenRefine workspace folder.

### Expected Behavior
The regular `workspace.json` file should be in folder and not overwritten or changed yet until the Project Create button has been clicked.  Since errors can happen or a crash during importing, etc.  we should leave `workspace.json` file alone until a new project is truly successfully created.  Then we can safely rename the `workspace.json` to `workspace.old.json` and immediately make the new `workspace.json` file which should include the additional new project id after user clicks the Project Create button (but does not, see additional new bug create for this #3433 )

If the Create Project button is clicked, the Project folder is not created in the workspace yet, nor is it added to the workspace.json file immediately.
It is only have 5 mins that the automatic ProjectManager saving modified projects finally saves the Project and adds the Project ID to the workspace.json file.

Users would expect that the Project folder is created when they have indeed clicked Project Create...yet it does not happen in sync with the operation because **ProjectManager save function is not immediately called when clicking the Project Create button.**

### Screenshots
![image](https://user-images.githubusercontent.com/986438/102695239-8e923a80-41eb-11eb-91d8-494e301b9ac2.png)

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: JDK8
 - OpenRefine: 3.4.1 win embedded Java

### Datasets
workspace.old.json  (1st)
```json
{"preferences":{"entries":{"scripting.starred-expressions":{"top":2147483647,"list":[],"class":"com.google.refine.preference.TopList"},"scripting.expressions":{"top":100,"list":[],"class":"com.google.refine.preference.TopList"}}},"projectIDs":[2542748512461,2578758975005,2562750745258,2558854639586]}
````

workspace.old.json (2nd)
```
{"preferences":{"entries":{"scripting.starred-expressions":{"top":2147483647,"list":[],"class":"com.google.refine.preference.TopList"},"scripting.expressions":{"top":100,"list":[],"class":"com.google.refine.preference.TopList"}}},"projectIDs":[2542748512461,2578758975005,2562750745258,2558854639586]}
```

**Comment by tfmorris** [comment]
Your operating system allows two different files with the same name in a directory? That's very odd. Are you sure your GUI isn't just confused and showing you the same file twice?

**Comment by thadguidry** [comment]
@tfmorris Positive Tom.  I watched it happen in realtime.

**Comment by elroykanye** [comment]
![workspace json](https://user-images.githubusercontent.com/68631069/160222986-0983f270-52a9-4f78-8121-7da356e84a39.png)
Tried to reproduce this. A new workspace.json file was created and the old was moved to workspace.old.json
Do I have to try doing this with v3.4?

**Comment by thadguidry** [comment]
That's perfect.  Did you test with latest 3.5.2 ?

**Comment by elroykanye** [comment]
> ![workspace json](https://user-images.githubusercontent.com/68631069/160222986-0983f270-52a9-4f78-8121-7da356e84a39.png) Tried to reproduce this. A new workspace.json file was created and the old was moved to workspace.old.json Do I have to try doing this with v3.4?

This is how it works with the latest. I haven't tested with v3.4 instead.

**Comment by thadguidry** [comment]
Awesome, then... working as expected, so... closing!  Thanks so much @elroykanye !  You are truly awesome !

**Comment by elroykanye** [comment]
😁 thanks for the help @thadguidry !
