### ISSUE TITLE
Move to cypress github action

### ISSUE THREAD

**Issue by kushthedude** [OpenRefine/OpenRefine#3434]
We are right now using cypress as a bare-metal yarn dependency, moreover, for a multi-browser test like on edge, we first grep the edge and then run cypress.

### Proposed solution

Cypress-io provides a Github-action to run cypress on multiple browsers, with headless mode, with option to records results too. I suggest we should utilize official cypress action instead of grabbing cypress with yarn and cypress cli commands. commands being used.
### Alternatives considered

None
### Additional context
Find the action over here https://github.com/cypress-io/github-action

**Comment by wetneb** [comment]
It is not clear to me why we would want to do this move. I think there is value in having the CI call the `./refine` script with the same arguments as what developers would use to run the tests locally, no? Concretely, what is the benefit of using the dedicated GitHub Action?

**Comment by kushthedude** [comment]
Having standard cypress action will:
- save us from the complex ci logic of testing on different browsers, https://github.com/cypress-io/github-action#browser.
- give us the ability to wait for the server without any script in the YAML config itself, https://github.com/cypress-io/github-action#start-server.
- give us the ability for parallel jobs, https://github.com/cypress-io/github-action#parallel.
- give better readability for CI configuration, also having the standard action for UI tests can open us to multiple configs options https://github.com/cypress-io/github-action#examples with the ability to custom build-ids and artifacts management.

For me, using action is just for easier maintainability and better readability and nothing else.

**Comment by wetneb** [comment]
I am still not convinced - we already have parallel jobs at the moment. I would say developers should find it easier to reproduce failures locally if they can see directly from the build logs how to run the tests (with `./refine ui_test`). But if @fgiroud agrees that it is better to use the GitHub Action, just go ahead!

**Comment by tfmorris** [comment]
I think configuring an Action, for the things that it is good at, is OK, **as long as**, as @wetneb mentions it stays aligned with or uses the same commands that the developers use locally. They may be composed in a slightly different manner by `./refine test`and the CI action, but they shouldn't diverge and we don't want to maintain parallel setups.

**Comment by kushthedude** [comment]
Looks like we don't need this as of now. Closing the issue as we are already using the homemade script for `./refine ui_tests`
