### ISSUE TITLE
Row count is returned as 0 occasionally from the server while fetching metadata

### ISSUE THREAD

**Issue by kushthedude** [OpenRefine/OpenRefine#3475]
While writing tests for project_metadata #3474 , I encountered an occasional bug. Table row metadata is being returned as zero sometimes from the openrefine server and hence Rows is being shown as 0.
### To Reproduce
1. Visit the `Open Project` page
2. See table columns, row is sometimes returned as 0 from the server

### Response returned by the server

```json
{
    "projects": {
        "2610263550897": {
            "created": "2021-01-15T17:30:02Z",
            "modified": "2021-01-15T17:30:02Z",
            "name": "1610731802333",
            "tags": [],
            "creator": "",
            "contributors": "",
            "subject": "",
            "description": "",
            "rowCount": 0,
            "title": "",
            "version": "",
            "license": "",
            "homepage": "",
            "image": "",
            "importOptionMetadata": [
                {
                    "includeFileSources": false,
                    "includeArchiveFileName": false,
                    "encoding": "US-ASCII",
                    "ignoreLines": -1,
                    "headerLines": 1,
                    "skipDataLines": 0,
                    "storeBlankRows": true,
                    "storeBlankCellsAsNulls": true,
                    "separator": ",",
                    "guessCellValueTypes": false,
                    "processQuotes": true,
                    "quoteCharacter": "\"",
                    "trimStrings": true,
                    "projectName": "1610731802333",
                    "fileSource": "food.mini.csv",
                    "archiveFileName": null
                }
            ],
            "customMetadata": {}
        }
    }
}
```
<img width="1409" alt="Screenshot 2021-01-16 at 1 00 52 AM" src="https://user-images.githubusercontent.com/44091822/104770361-78e64580-5796-11eb-8247-e4c04f23fe8b.png">

Meanwhile, when I click on the project, it shows two rows.
<img width="821" alt="Screenshot 2021-01-16 at 1 01 01 AM" src="https://user-images.githubusercontent.com/44091822/104770319-679d3900-5796-11eb-96aa-4c61c00d5757.png">

**Comment by tfmorris** [comment]
Is any more detail available on the circumstances under which this occurs? I'm refactoring this, but as it currently stands there are (at least) two ways that this could occur:
1. If you have a project which was created before the row count as added to ProjectMetadata and haven't opened it since
2. If you create a project programmatically, adding rows and saving it, but not opening it.

The row count is only updated in the GetRows command (which is huge hack) so if the project hasn't been opened and displayed in the browser, the count will be stale/wrong/zero.

**Comment by tfmorris** [comment]
I don't have proof-positive that the changes fix this issue since there's no reproduction criteria, but I consider it highly likely to be fixed.
