### ISSUE TITLE
Unwanted symbol in project version metadata dialogue

### ISSUE THREAD

**Issue by kushthedude** [OpenRefine/OpenRefine#3481]
Project about dialogue has a weird symbol ahead of its info in the metadata.
### To Reproduce
1. Create a project
2. Then, click on it's about tab
3. Finally, see the bug

### Current Results

The weird symbol `$1` appears ahead of it
### Expected Behavior

No unwanted characters should be present
### Screenshots

<img width="1388" alt="Screenshot 2021-01-16 at 11 01 59 PM" src="https://user-images.githubusercontent.com/44091822/104818678-11400100-584f-11eb-8743-7ba053fdd70a.png">

**Comment by wetneb** [comment]
Closed by #3482.

**Comment by tfmorris** [comment]
We need a different fix for this.

**Comment by wetneb** [comment]
Ah thanks! My mistake for merging that too quickly.
