### ISSUE TITLE
Add a generic test about expressions (Python, Grel, ...)

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3498]
Many UX components are related to expressions.
Expressions can be written in 
* GREL
* Python
* Clojure

The same panel is used for
* facets expressions
* transforms
* potentially others

![Screen Shot 2021-01-19 at 11 26 32](https://user-images.githubusercontent.com/6267288/105022082-9c84e680-5a49-11eb-9bb2-08f3a54e560a.png)

### Proposed solution

The goal is to have a generic test to cover those features, but not necessarily specific to facets or transforms, this is more a test about writing expression and their previews

The test should

* try an expression with a syntax error (Internal error)
* try an expression that is invalid `value.thisDoesNotExists()` or something similar
* test the three different languages
* check the preview

**Comment by fgiroud** [comment]
@thadguidry, do you have any idea about the expected behavior of "starred" and "history" ?
Thx

**Comment by thadguidry** [comment]
**History** - expressions will show here after the user clicks OK on to perform the expression.  It continually grows.

**Starred** - Users click on the History and can then click on the Star next to an item to mark it as a favorite, which then shows in the Starred tab.  Those favorites are permanently stored within the `metadata.json` file inside each of the Project subfolders in the OpenRefine workspace folder.

**Comment by fgiroud** [comment]
@thadguidry I've implemented many tests in PR
Do you think the behavior of the panel is inconsistent (and is that a bug ?)
You can review either by running the tests, or give a try to [the Cypress dashboard](https://dashboard.cypress.io/projects/s5du3k/runs/257/overview)

See the following

- Grel syntax error: Parsing error in red on the right side of the input
- Python syntax error: Internal error in red on the right
- Clojure syntax error: Syntax error in red on the right

So far so good, but now let's look at a language error

- Grel language error: Parsing error in red on the right side of the input
- Python language error: Nothing on the right side, Raw Python error in the preview
- Clojure language error: Nothing on the right side, Raw Clojure error in the preview

Also noticed that Python language needs a `return` statement, whereas other language are fine with just typing any expression in the input. Is that expected?

**Comment by thadguidry** [comment]
@fgiroud Yes, also watched the video and it all looks expected.

**Comment by thadguidry** [comment]
Oops, I see somethings unexpected with these...

Test the history behavior, ensure expressions are stored.
Test the reuse of expressions from history

That one should open the expression editor, type a valid expression such as `value + "testPassed"`, click OK, create custom facet again on same column, click the History tab, and verify that 1st row in history indeed has the `value + "testPassed"` value.

However currently, it actually preemptively fails with an Parsing error (invalid expression) , take a look where I slowed down the video to .25x as seen in lower right corner :
![image](https://user-images.githubusercontent.com/986438/106289371-d48ce600-620e-11eb-9817-f336231336cb.png)
