### ISSUE TITLE
Expression history show expressions from other projects

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3499]
When loading a new project, the expression history is loaded with expression from other projects

### To Reproduce
1. First, create a project A
2. Then, add a custom text facet with `value.toLowercase()`
3. Then, create a project B
4. Then, add a custom text facet
5. Click 'history'
6. See that the history already contains `value.toLowercase()` from project A

### Expected Behavior
Either expressions should be marked as "Project A", instead of "current project"  

### Versions
 - Operating System: MacOs
 - Browser Version: Version 87.0.4280.141 (Official Build) (x86_64)
 - JRE or JDK Version: Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
 - OpenRefine: Master

**Comment by thadguidry** [comment]
@fgiroud I don't think this is a bug, it's universal history, as I explained before in #3498  "history" is basically last 100 expressions used (no matter the project) and if users want to favorite some, then they click the star next to one.

**Comment by fgiroud** [comment]
Thx for the clarification @thadguidry, let's reject this
