### ISSUE TITLE
Add link checker to documentation CI

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#3529]
The dead links from #3524 are something that we should be able to catch by checking the links when running CI on the docs build.

W3C has an online checker here: http://validator.w3.org/checklink?uri=https%3A%2F%2Fdocs.openrefine.org%2F&hide_type=all&depth=&check=Check
but there are local utilities which can be used as well.

**Comment by thadguidry** [comment]
@tfmorris should we add you as a team member on the Netlify site management you think, just in case, so you can see and help us manage things?
However, I did find the Checklinks plugin along with others that we can easily enable.
https://app.netlify.com/teams/openrefine-team/plugins
![image](https://user-images.githubusercontent.com/986438/106077889-05b6ca80-60d8-11eb-9263-8e53e9dbe077.png)


We'll also need to doublecheck we disabled the Netlify config for `Pretty URLs` per this: https://v2.docusaurus.io/docs/deployment#deploying-to-netlify

I logged in and looked on the Netlify site config but didn't see that `Pretty URLs` setting.
@kushthedude do you have any idea where that one is at and configured?

**Comment by wetneb** [comment]
I thought that was supposed to be already supported by https://github.com/OpenRefine/OpenRefine/issues/3031, but clearly it's not working so far. Perhaps it would be worth checking if we need to enable anything in our Docusaurus config for this feature to be enabled.

**Comment by kushthedude** [comment]
Hi @thadguidry , you will most probably find the `Pretty URLs` setting here *`Site settings > Build & deploy > Post processing > Asset optimization`*

**Comment by thadguidry** [comment]
Ah yes...hmm, but looks like it's already checked to skip the Asset processing altogether, so all of these are already effectively disabled?

![image](https://user-images.githubusercontent.com/986438/106185109-039c4c80-6168-11eb-9e85-34b7768348b1.png)

**Comment by kushthedude** [comment]
Yes then

**Comment by thadguidry** [comment]
> 
> 
> I thought that was supposed to be already supported by #3031, but clearly it's not working so far. Perhaps it would be worth checking if we need to enable anything in our Docusaurus config for this feature to be enabled.

@wetneb that Docusaurus setting `onBrokenLinks` only seems to work if you actually do a production build [according to their docs](https://v2.docusaurus.io/docs/docusaurus.config.js/#onbrokenlinks):
>( ! ) NOTE
>
>The broken links detection is only available for a production build (`docusaurus build`).

So we probably do want to enable that Netlify plugin [Checklinks](https://github.com/munter/netlify-plugin-checklinks#readme) to easily help us with keeping things unbroken.

**Comment by tfmorris** [comment]
> that Docusaurus setting `onBrokenLinks` only seems to work if you actually do a production build [according to their docs](https://v2.docusaurus.io/docs/docusaurus.config.js/#onbrokenlinks):

Why don't we want to be doing a production build?

**Comment by thadguidry** [comment]
@tfmorris I have no idea.  I'm not the Netlify deploy expert.  But Netlify is configured it seems with the `yarn build` currently.

@kushthedude do you know why it's done as such (I forgot), since we don't have a `netlify.toml` file it seems the build/deploy for docs is tied up with the Netlify config you helped us with somewhere?  Looking around...
We should have some of our CI/CD setups like for Netlify and processes actually documented.  Like mentioning that things are configured under here: https://app.netlify.com/sites/openrefine-docs/deploys  ?
![image](https://user-images.githubusercontent.com/986438/106209512-c1d0cd80-618a-11eb-88bb-37735c756e2c.png)

**Comment by wetneb** [comment]
I think we should definitely enable production builds for Docusaurus.
