### ISSUE TITLE
Cleanup previous UX test suite

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3552]
Since the migration to Cypress, some leftover folders are still in the codebase.

I assume we can delete `main/tests/client`, but can we also delete `main/tests/data` and `main/tests/server` or are those files used by some backend tests in Java?

Thx

**Comment by wetneb** [comment]
Yes `main/tests/client` can be deleted, but the other ones are needed by the backend tests.

**Comment by tfmorris** [comment]
Why wouldn't we use `main/tests/client` for our client tests? They currently seem to be rooted at `main/tests/cypress/cypress` which seems both tool specific and somewhat obscure (as well as redundant).

**Comment by wetneb** [comment]
On the longer term I would like to adopt Maven's conventions for folder structures. The goal of using something standard is to reduce the friction in discovering the project, packaging it and making the build files simpler. But I haven't investigated how frontend files (and their tests) are generally stored in this layout.

**Comment by tfmorris** [comment]
Switching to Maven sounds fine if it'll produce a tangible benefit, but why wouldn't we stick with the existing convention while deciding what the new convention is going to be?
