### ISSUE TITLE
Add UX Test for column / Edit cells / Common transforms

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3553]
This issue is following the work implemented for issue #3423 in [PR 3541](https://github.com/OpenRefine/OpenRefine/pull/3541)

The goal is to cover all functionalities under column / edit cells / common transforms

![Screen Shot 2021-02-02 at 09 17 51](https://user-images.githubusercontent.com/6267288/106571627-acb3c000-6537-11eb-9dae-ff7185a459b1.png)

### Proposed solution

Write the remaining tests for

- Convert Smart quotes with ascii
- to titlecase
- to uppercase
- to lowercase
- to text
- to null
- to empty string

**Comment by majjikishore007** [comment]
I would like to work on this issue

**Comment by wetneb** [comment]
I think it should not be necessary to test *all* of them, since they are just using different GREL expressions under the hood. If it is cheap to test them all, fine, but if we want to spare a bit of running time, this menu is a good candidate for skipping items.

**Comment by AhwiniMirajkar** [comment]
I want to work on this

**Comment by S-Harshit** [comment]
If no one is working on this, I would like to work on it.

**Comment by S-Harshit** [comment]
@fgiroud How should I test 'Convert Smart quotes with ascii' and to text' should I use fixtures for it?

**Comment by fgiroud** [comment]
@S-Harshit, you should be able to use fixtures directly in your test, without using the common food.mini or food.small

See
```javascript
const fixture = [
      ['a', 'b', 'c'],

      ['0a', '0b', '0c'],
      ['1a', 1b, '1c']
    ];

    cy.loadAndVisitProject(fixture);
```
