### ISSUE TITLE
Migrate from Coveralls to Codecov

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3558]
We currently use Coveralls to keep track of our server-side test coverage.

Migrating to Codecov would let us upload code coverage results from GitHub Actions without specifying a secret key. We did this in Wikidata-Toolkit: https://github.com/Wikidata/Wikidata-Toolkit/pull/525.

Eliminating this secret key could help us use the `pull_request` GitHub event instead of `pull_request_target` one as we are doing now (which is a vulnerability, although none of our environment secrets are actually very sensitive). Currently the pull request workflow uses another secret (`CYPRESS_RECORD_KEY`) so we would not be immediately able to switch to the `pull_request` event, but it would be one step towards that.

Codecov has some nice features to analyze and report the coverage of diffs. Perhaps the reports it generates on pull requests (example: https://github.com/Wikidata/Wikidata-Toolkit/pull/526) are a bit verbose to my taste, but I suspect we can tweak that.

What do people think?

**Comment by thadguidry** [comment]
@wetneb yes I saw you folks did that on Wikidata-Toolkit. Nice! I think anything that helps simplify our lives with the CI/CD and still offers similar functionality is a "good idea".

So you would directly use their GitHub Action https://github.com/codecov/codecov-action ?  And if so, does it support everything you need currently or do we need to ask their team for any feature in their action that's missing that we need?

**Comment by tfmorris** [comment]
As you say, none of our secrets really need a lot of protecting. 

I really like the trend graphs that Coveralls provides. Does the proposed service offer anything similar? 

When I try to click through to the example that you linked, I get "Unauthorized." Do they provide a way to make reports publicly available without login? 

Not really a fan of the tree map. I don't think it adds any value over our current linear rollup.

I'm not specifically opposed, but it seems like work that we should defer if we can unless there's a significant benefit, which isn't clear to me.

**Comment by wetneb** [comment]
Good point that Codecov is login-protected, I did not realize that. It's a bit annoying.
Let's close this for now. I'll evaluate codecov on WDTK for a while and I'll reopen this if I feel like it is really better than Coveralls despite that issue.
