### ISSUE TITLE
Migrate extensions to new architecture

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3559]
So far the extensions have been left out of the migration out of the in-memory data model.
We should update them accordingly.

While we do this process, it would be good to write down a migration guide, similarly to the breaking changes we have done before:
https://github.com/OpenRefine/OpenRefine/wiki/Migration-guide-for-extension-and-fork-maintainers

This is a very big breaking change so there is no hope to do a very detailed step-by-step guide like for other changes, but we can at least give an overview of the main changes.

**Comment by tfmorris** [comment]
Perhaps we should put some thought into an extension API which can be stable and maintainable and migrate extensions to that. Most extensions have pretty simple needs, so it should be possible to define an API that can be kept stable for them.

**Comment by wetneb** [comment]
The new architecture is one step in that direction, since it abstracts away the concrete storage mechanism for project data (extensions can no longer rely on the fact that the project grid is stored in memory, or in another particular backend). So the migration consists mostly in replacing direct accesses such as `project.rows.get(0)` by accesses which go through the API (`project.getCurrentGridState().getRow(0L)`).

**Comment by wetneb** [comment]
This is now done!
