### ISSUE TITLE
Restore pagination behaviour

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3562]
In the new architecture, the API offered by the backend for grid pagination has changed slightly.

Before, a page was defined by:
* a page size
* the number of rows/records before the page

In the new architecture, the backend expects instead (as long as there is no sorting in place):
* a page size
* the minimum row id to start the page from

If there are facets applied, this is different from the previous parameters (the minimum row id might be greater than the number of rows in the previous pages if some rows have been filtered out).

This change makes it more efficient to locate the page in the partitions of the dataset. But maybe this is actually superfluous and we should keep the previous behaviour, since it has the advantage of not being dependent on the sorting.

**Comment by thadguidry** [comment]
Yeah, the sorting context is a really good question.  Even I don't know.  I think we'll have to try it out on large datasets with Records and test sorting and compare to previous OpenRefine versions.

Do you know how efficient the page lookup is?  Say if I have 2 million records viewing 50 at a time and want to get to page 39990 (40000 pages), how long does it take to return it? Any idea yet?

**Comment by tfmorris** [comment]
> we should keep the previous behaviour, since it has the advantage of not being dependent on the sorting.

I'm not following this. The current pagination **is** dependent on the sort order, isn't it? And, actually, I would have thought that all pagination schemes would have to be to be useful to the user.

**Comment by wetneb** [comment]
What I mean is that currently, in the new architecture, the meaning of the `start` parameter in `GetRowsCommand` is dependent on whether a sorting configuration is applied or not:
* if there is no sorting configuration, `start` is interpreted as a lower bound on the row ids to return
* if there is a sorting configuration, `start` is interpreted as the number of rows to skip before generating the page

This feels a bit sloppy to me - I would at least use different parameter names for this. I think it would still be worth passing the row id of the last skipped row when no sorting configuration is used, because it would make browsing more efficient, but it could be passed as a different parameter.

**Comment by wetneb** [comment]
This was fixed by #5411.
