### ISSUE TITLE
Expression window resize issues

### ISSUE THREAD

**Issue by allanaaa** [OpenRefine/OpenRefine#3565]
When changing the browser window size, parts of the expression editor window do not resize.

### Current Results
![window-resize-problem](https://user-images.githubusercontent.com/28012148/106795918-b10bd600-6628-11eb-914d-004fdd96ea67.PNG)

Not a big issue but perhaps it's an easy fix.

### Versions
 - Operating System: Windows
 - Browser Version: Firefox
 - OpenRefine: 3.4.1

**Comment by wetneb** [comment]
Yes, it's really annoying!

**Comment by Mo-hamdy2000** [comment]
Could I work on this issue ?

**Comment by wetneb** [comment]
It's all yours!

**Comment by AhwiniMirajkar** [comment]
Can I work on this

**Comment by wetneb** [comment]
@AhwiniMirajkar no, as you can see it is already assigned.

**Comment by KaranSingh1301** [comment]
@Mo-hamdy2000  hey, Are still working on this?

**Comment by Mo-hamdy2000** [comment]
> @Mo-hamdy2000 hey, Are still working on this?

@KaranSingh1301 Yes, I opened a pull request to be reviewed.

**Comment by Mo-hamdy2000** [comment]
@wetneb I have made the required changes in the pull request, kindly could you review it ?

**Comment by wetneb** [comment]
Closed by #3587.
