### ISSUE TITLE
Links on docs are sometimes getting changed with extra doc id

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3572]
### To Reproduce
1. Visit https://docs.openrefine.org/technical-reference/build-test-run/
2. Scroll down and find the section **Testing**
3. Hover over the link for [you must go through the installation process](https://docs.openrefine.org/technical-reference/build-test-run/functional-tests)
4. Click on link and another page comes up with **Page not found**

### Current Results
It adds in an extra `/build-test-run/` into the URL erroneously as
[https://docs.openrefine.org/technical-reference/build-test-run/functional-tests](https://docs.openrefine.org/technical-reference/build-test-run/functional-tests)
Interestingly, sometimes if I refresh my browser, then the link does appear correctly, and other times it adds in the extra `/build-test-run/`
### Expected Behavior
I expected that the link would navigate to
[https://docs.openrefine.org/technical-reference/functional-tests](https://docs.openrefine.org/technical-reference/functional-tests) 
which is a usable and valid link, but instead 

### Screenshots
![image](https://user-images.githubusercontent.com/986438/106901884-d8f94900-66bd-11eb-92ba-d45a3524e3fd.png)

**Comment by ostephens** [comment]
I think this might just be some bad links in the technical reference section - I'll take this and check through it all

**Comment by ostephens** [comment]
Ah - no if its intermittent obviously it's not just bad links. I'll investigate

**Comment by wetneb** [comment]
It does not seem intermittent to me, the link is just always broken.

**Comment by wetneb** [comment]
This should have been fixed by #3821. @thadguidry can you confirm?

**Comment by wetneb** [comment]
I think this is indeed solved by #3821. Closing, feel free to reopen if it happens again.
