### ISSUE TITLE
Fix help and documentation for record variables

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#3578]
The current help for the `record` variable in the web client points to https://github.com/OpenRefine/OpenRefine/wiki/Variables#record, but that's just a stub that includes a generic link to the top level of the user manual.

It could be updated to point to https://docs.openrefine.org/manual/expressions#record, but it would be better to just include the documentation in the help, like everything else except the `record` variable.

Also, the manual's documentation could use improvement. For `row.record.cells` it says "The cells of the row" when it's a slice of cells from the record for the given column.

**Comment by allanaaa** [comment]
I'm working on the in-tool help text right now, so that part is assigned to me.

I will take a look at the manual text after that, unless someone else gets to it first.

**Comment by tfmorris** [comment]
OK, thanks, but in the meantime, I don't think it's very friendly to just be pointing folks at what is effectively a dead end. Any fix to the help is only going to affect future versions, not all the versions that are out in the field.

**Comment by allanaaa** [comment]
That part is up to @ostephens. Owen is taking care of manually redirecting the newly-blanked wiki pages to specific parts of the manual, so I will leave it to him whether he wants to do so for the URLs included in the Help text.

(In our spreadsheet I did mark a handful of wiki pages that are still in the codebase, but I didn't include the URLs that appear in the Help text.)

**Comment by tfmorris** [comment]
@ostephens Please do not replace _specific_ content with _generic_ links. I've fixed this page, but if there are any others, please fix them.

**Comment by ostephens** [comment]
@tfmorris sorry I was in the process of putting in the specific links last night but didn't get them all done before I had to stop. Those are all done.
