### ISSUE TITLE
Add a link to the GREL reference in the expressions editor window

### ISSUE THREAD

**Issue by allanaaa** [OpenRefine/OpenRefine#3580]
Currently the expressions editor window supplies an in-tool Help tab, but it would also be nice to refer people to the GREL functions reference: https://docs.openrefine.org/manual/grelfunctions

![helpdisplay](https://user-images.githubusercontent.com/28012148/106949620-2fd14380-66fb-11eb-8617-a3d94380f589.PNG)

It seems likely that the manual will usually be more up-to-date than the help text inside whatever version of OpenRefine people are using. You may wish to provide the link to the appropriate version fork of the docs as you go forward, or supply a simple link and warn users to select their respective version from the dropdown. 

### Proposed solution
This link could go inside the Help tab itself, the first line at the very top (presuming #3579 is possible and completed), or it can appear as a button elsewhere inside the expressions editor window (perhaps to the right of the tabs). Maybe a button could appear to the right of the language dropdown when GREL is selected. Wherever it makes sense to take up some space.

**Comment by singhakshita** [comment]
can i work on this?

**Comment by wetneb** [comment]
Sure!

**Comment by singhakshita** [comment]
@wetneb just wanted to confirm that whatever language is chosen ,GREL,python,.. the help dialog content remains the same ,
so is the excepted behaviour is to show to GREL link always or should it disappear when a language other than GREL is chosen?

**Comment by singhakshita** [comment]
@wetneb  this issue has some connection with issue #1122  as well , so will the entire GREL reference link added on the top would do ? 
<img width="571" alt="Screenshot 2021-02-16 at 1 54 54 PM" src="https://user-images.githubusercontent.com/52077474/108040206-0a312c00-7063-11eb-81e3-21303915bced.png">
will this be sufficient?

**Comment by wetneb** [comment]
I think it would be good to make it clearer that the variables are actually language-independent. The functions are indeed only documented for GREL. We could consider only showing them (and the associated documentation link) when GREL is selected, but perhaps that's out of the scope of this issue.
