### ISSUE TITLE
EPIC - Cleanup and consolidate the root folder as possible

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3590]
On a previous call while discussing documentation and governance, we thought it might be nice to begin to try to consolidate the root folder.  One of the reasons was to push up the README.md file view for folks visiting our repo as well as making it easier for new contributors.  Many other projects throughout GitHub are successful in doing this, and GitHub provides a few mechanisms that help.

### Proposed solution
1. Review [GitHub documentation for our community profile](https://docs.github.com/en/github/building-a-strong-community/accessing-a-projects-community-profile) to discover where we can relocate certain files into subfolders while still maintaining GitHub functionality.  And make a decision on if `/docs` might be a good new home for various files.  For example, GitHub explains for CONTRIBUTING.md:

> Decide whether to store your contributing guidelines in your repository's root, docs, or .github directory.

2. We might also look into moving or removing certain files such as:
 - AUTHORS.md
 - CHANGES.txt
 - WeLoveOurBackers.md
 - CODE_OF_CONDUCT.md
 - etc.

3. [GitHub's community profile check under Insights](https://github.com/OpenRefine/OpenRefine/community) helps to ensure the files are still findable by GitHub's features.

4. All CI/CD `.yml` files might be able to move into the .github folder?

5. Can `settings.xml` be moved under `conf` or another existing folder?

6. Finally, can we move away from our legacy ANT structure and embrace MAVEN [Standard Directory Structure](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html)?  Consolidating where possible into a single root folder called simply `src` ?

**Comment by wetneb** [comment]
I would also remove the `start.sh` and `stop.sh` scripts which are not actually shipped in releases anyway.
