### ISSUE TITLE
Change eslint default printWidth

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3623]
JS test code is formatted by prettier

Default print width of 80 makes the tests extremely difficult to read
Example in create_project.spec.js

Can we switch to 120 at least?

**Comment by kushthedude** [comment]
Hi @fgiroud I am not sure I understood the issue, can you please point me to the line which is difficult to read in the create_project?

**Comment by tfmorris** [comment]
Prettier is an "opinionated" formatter. If we're changing the options, perhaps we want a different tool.
https://prettier.io/docs/en/options.html

**Comment by kushthedude** [comment]
> Prettier is an "opinionated" formatter. If we're changing the options, perhaps we want a different tool.

I won't suggest changing the tools, the same set of rules doesn't apply for all projects, that's why prettier has a config file where we can override any rules. Not to mention prettier is just a code beautifier for better readability, so it actually depends upon the community which way they would want to bend the rules.

**Comment by fgiroud** [comment]
@kushthedude example
```
cy.get('.create-project-ui-source-selection-tab-body.selected').contains(
      'Locate one or more files on your computer to upload'
    );
    
cy.get(
      '.create-project-ui-source-selection-tab-body.selected button.button-primary'
).click();
``` 
This should be on one single line, instead, we have 3

@tfmorris prettier is opinionated, and everything stated in the link you provided is actually very true. The thing is that this really make sense in the context of application/software development.
But when writing tests, we often end-up with very long lines because either CSS selectors or the texts we verify are long

**Comment by kushthedude** [comment]
Isn't breaking each cypress command on its own line providing better readability? All of our test files have been broken this way from each cypress command to get better readability of list of operations being performed by the cypress. Increasing it to 120 will make other changes like

```js
  cy.getCell(1, 'Water')		
      .trigger('mouseover')		
      .find('a.data-table-cell-edit')		
      .click();
``` 
#### to
`cy.getCell(1, 'Water').trigger('mouseover').find('a.data-table-cell-edit').click();`


I dont' have any strong opinions here, I can change it to 120 if it's more appropriate

**Comment by fgiroud** [comment]
Good point! So I guess we need to test the two configs 80/120 and see what brings the best readability

**Comment by fgiroud** [comment]
@kushthedude thinking about my last comment, actually breaking the lines is not linked to the print width.
Even with 80, you would still have `cy.getCell(1, 'Water').trigger('mouseover').trigger('somethingelse');` on one single line
So keeping 80 doesn't really enforce breaking cypress commands, this is just a side effect that works in many cases

Voting for 120, for a better tests readability :-)

**Comment by fgiroud** [comment]
@kushthedude @tfmorris 
Looks like I am the only one requesting a change at this level, so I suggest to close this.
Another reason is that if we change the linting rules now, all Opened PR will failed, time for the community to resynch all their forks
Let's close this for now, we can revisit this option later if necessary
