### ISSUE TITLE
Support Wiki table formats

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#363]
_Original author: techtonik@gmail.com (April 16, 2011 15:47:13)_

<b>What steps will reproduce the problem?</b>
1. http://wiki.python.org/moin/PythonEditors?action=edit&amp;editor=text 2. Copy data, save into a file
3. Import using || separator

<b>What is the expected output? What do you see instead?</b>
1. empty columns to be removed automatically
2. '''bold''' formatting removed from headers
3. links should not be split into columns - they use single pipe | character

<b>What version of Google Refine are you using?</b>
2.0-r1836

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=363_
##

**Comment by wetneb** [comment]
This is solved by aa4517ba5.

**Comment by thadguidry** [comment]
Should we also support the one-line format for wiki tables ?
https://en.wikipedia.org/wiki/Wikipedia:Advanced_table_formatting


The wikitext for any one row can be compressed onto a single line by joining columns with double-bars 
"||" between them and ending each row with "<tr>".
```
Example row 1: |fmtspec|AA||fmtspec|CC||fmtspec|EE<tr>
Example row 2: |fmtspec|BB||fmtspec|DD||fmtspec|FF<tr>
```

**Comment by wetneb** [comment]
@thadguidry Yes, this format is also supported.
