### ISSUE TITLE
The ability to send a subset of data to data owner for correction.

### ISSUE THREAD

**Issue by HichemDax** [OpenRefine/OpenRefine#3631]
This feature is critical in our job, we receive data that need cleansing but most of the times we cannot update ourselves so we need to send the marked lines to the data owner for correction with a column stating the remarks.
We are currently doing it via Excel only but facing many issues in the versioning and get lost in the emails.

### Proposed solution
To have the ability to send marked for review lines with comments to the data owner using a url so data owner can open and 
 rectify. has to be restricted to modify only those lines with and recording the changes.

### Alternatives considered
Export the marked lines for review with OpenRefine internal Id, send it to data owner and have the ability to reimport it once modified with full replace.

**Comment by wetneb** [comment]
Hi @HichemDax, thanks for this feature request!

It would be good if you could elaborate a bit on this use case. At the moment it is not clear to me what exactly you need to change in OpenRefine to make this workflow possible. It is currently possible to export a selection of lines and send it to someone (although the sending itself is not handled by OpenRefine). In your alternative workflow you mention "remiporting" the data, perhaps the feature request could be there?

**Comment by wetneb** [comment]
I am closing this issue in the absence of more details on the desired workflow, I can reopen it if these details become available.
