### ISSUE TITLE
Deleting a reconciliation service fires of a reconciliation attempt against it.

### ISSUE THREAD

**Issue by gitonthescene** [OpenRefine/OpenRefine#3632]
### To Reproduce
1. First, select Start Reconciling to bring up the Reconciliation dialog
2. Then, click the [x] to remove a reconciliation service
3. Finally, notice that instead of simply removing the service it tries to reconcile against it and you have to quit that operation.

This is a minor nit since canceling the run is easy enough.  I just thought it worth reporting.

### Current Results
Reconciliation runs when removing a service.

### Expected Behavior
Expect service to simply disappear from the list of options and potentially wait for you to choose one of the remaining options.  Alternatively simply close the dialog when a service is deleted.

### Versions
 - Operating System: iOS
 - Browser Version: Firefox 84.0.1
 - JRE or JDK Version: java version "1.8.0_281" (I'm not sure this is the version used by OpenRefine...)
 - OpenRefine: 3.4.1

**Comment by wetneb** [comment]
I think I remember seeing a fix for this, so it probably has been resolved on master but the fix has not been released yet.

**Comment by gitonthescene** [comment]
FWIW, I did try to search through the issues first before posting.  I didn't see it mentioned.

**Comment by wetneb** [comment]
Already fixed on master.
