### ISSUE TITLE
Database extension tests are not run

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3633]
The backend tests for the database extension (support for SQL import/export) are not currently run, when running tests locally. In the CI, they are run (because we use a specific configuration file in that context).

It is good that tests requiring a database engine are not run by default (we do not want OpenRefine developers to have to run multiple database engines just to run the tests, especially if they are working on an independent aspect of the tool). But we should at least run the tests which do not rely on any such external database.

### To Reproduce
Run `./refine test` and observe that 0 tests are run for the database extension.

This is due to an incorrect configuration file for the test suite, which I seem to be responsible for. Oops.

**Comment by thadguidry** [comment]
@wetneb Thanks for addressing this.  Curious, then should the file or maybe folder itself be renamed then to match the usage; that of CI tests?
FROM:  extensions/database/tests/conf/tests.xml
TO:  extensions/database/tests/ci_conf/ci_tests.xml

**Comment by wetneb** [comment]
It's precisely the file that is *not* for the CI. The ones that are for the CI are `appveyor_tests.xml` and `github_actions_tests.xml`.

**Comment by thadguidry** [comment]
@wetneb Ah, understood.
