### ISSUE TITLE
Require branched to be sync in master before merging

### ISSUE THREAD

**Issue by kushthedude** [OpenRefine/OpenRefine#3636]
https://github.com/OpenRefine/OpenRefine/pull/3626#issuecomment-778817086

- As we can see accidentally unlisted code was committed into the repo due to the pull_request_target event. It is utmost necessary that we should prevent such mishaps till the that we don't shift into pull_request event.

- To assure that merged branches from a PR are up-to-date with the master, GitHub provides us with a great utility radio button in repo settings 
<img width="1409" alt="Screenshot 2021-02-14 at 11 50 13 PM" src="https://user-images.githubusercontent.com/44091822/107885322-8cb0d300-6f1f-11eb-89b3-5a136949e636.png">

**Comment by wetneb** [comment]
I would be happy with trying this out, perhaps as a temporary measure until we properly fix our GitHub Actions setup. But I could not find this option in the settings, do you know where to find them @kushthedude?

**Comment by kushthedude** [comment]
> I would be happy with trying this out, perhaps as a temporary measure until we properly fix our GitHub Actions setup. But I could not find this option in the settings, do you know where to find them @kushthedude?

This would be available under `branch protection rule`,
- Go to Settings>Branches
- Under the heading `Branch Protection Rules` if there is any rule present for master branch then click on edit and enable the above radio button.
- If no rule is present then click on add rule, add `master` as branch name pattern and enforce the rules as required.

**Comment by wetneb** [comment]
Ok thanks, I found it. @tfmorris would you be open to trying this?

**Comment by tfmorris** [comment]
I've enabled it and made the Java 14 status check mandatory (we can add other checks as mandatory too, but we need at least one for this to work).

The one thing I'm not super keen on is that the "Sync" button encourages developers to merge `master` to the PR branch, rather than rebasing the PR branch on `master` which seems like it'll pollute the commit history with lots of extra merge commits.

**Comment by wetneb** [comment]
As long as we remember to always use the "Squash" option rather than the "Merge" one (except for Weblate PRs), then merging master into PR branches should be fine.

**Comment by kushthedude** [comment]
Looks like this has been already enabled!
