### ISSUE TITLE
Wikibase schema serialization issues

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3656]
In the migration to arbitrary Wikibase support, some changes to the Wikibase schema serialization were introduced.
The following fields were added:
* `mediaWikiApiEndpoint`
* `editGroupsURLSchema`

I can see two problems with this:

### Lack of serialization of `editGroupsURLSchema`

This field is currently marked as `@JsonIgnore` so it is not serialized to the schema. This means that when re-opening a project, the schema will be restored without this parameter, causing OpenRefine to edit without EditGroups link.

### Potential lack of backwards-compatibility with schemas serialized with previous versions
It would be nice to still support schemas serialized by previous versions. We should ensure that we can still import the schema without these two parameters. Namely, these could be retrieved from the list of installed manifests (since we have the `siteIri` to identify which instance we are talking about). Or even simpler: the absence of the `mediaWikiApiEndpoint` parameter indicates that the schema was made by a version of OpenRefine which only supported Wikidata, so we can directly prefill those parameters with constants in that case.

**Comment by tfmorris** [comment]
I'm surprised the backward compatibility is considered a "nice to have."  OpenRefine has traditionally tried to always migrate smoothly from one version to the next.

If we're going to address this, it needs to be done for OpenRefine 3.5.

**Comment by wetneb** [comment]
Yes, my wording was imperfect, I agree with you on the severity of this. I did not to phrase it too harshly because I haven't actually checked that we currently have a backwards-incompatibility here. Perhaps @afkbrb has thoughts about this?

**Comment by afkbrb** [comment]
>  Or even simpler: the absence of the mediaWikiApiEndpoint parameter indicates that the schema was made by a version of OpenRefine which only supported Wikidata, so we can directly prefill those parameters with constants in that case.

That's exactly what the following code is doing:

https://github.com/OpenRefine/OpenRefine/blob/1e47c612d9bd7dc3fddf9897604ffec20ebc183f/extensions/wikidata/module/scripts/schema-alignment.js#L259-L265

https://github.com/OpenRefine/OpenRefine/blob/1e47c612d9bd7dc3fddf9897604ffec20ebc183f/extensions/wikidata/module/scripts/dialogs/import-schema-dialog.js#L41-L47

**Comment by afkbrb** [comment]
As for `mediaWikiApiEndpoint` and `editGroupsURLSchema`, now I think **both could be marked as `@JsonIgnore`**. They are kept in the `WikibaseSchema` class because they are needed in the following code:

https://github.com/OpenRefine/OpenRefine/blob/1e47c612d9bd7dc3fddf9897604ffec20ebc183f/extensions/wikidata/src/org/openrefine/wikidata/schema/WbLanguageVariable.java#L59-L62

https://github.com/OpenRefine/OpenRefine/blob/1e47c612d9bd7dc3fddf9897604ffec20ebc183f/extensions/wikidata/src/org/openrefine/wikidata/operations/PerformWikibaseEditsOperation.java#L195-L207

Serializing `siteIri` should be enough, because:
 - It is the "key" to get the manifest
 - The values of `mediaWikiApiEndpoint` and `editGroupsURLSchema` are decided in the frontend, provided by the manifest.

**Comment by wetneb** [comment]
Thanks a lot for the explanations @afkbrb!

It feels to me like this fallback logic should be in the backend, not the frontend, otherwise it is likely to be missed in some workflows.
Example:
* I create a project and save a Wikibase schema there
* I shut down OpenRefine and start it again the next day
* I make edits on the target Wikibase without editing the schema again.

In this scenario I think the schema used for the editing is the one that is obtained by deserialization from the project data, directly in the backend. So it is deserialized without the EditGroups link, and so edits are made without EditGroups support. Do I understand this correctly @afkbrb?

**Comment by wetneb** [comment]
@afkbrb have you got thoughts about the workflow above? If you can confirm that the fallback will not work in such a case, I will try to fix this by moving this fallback to the backend.

**Comment by afkbrb** [comment]
> It feels to me like this fallback logic should be in the backend, not the frontend, otherwise it is likely to be missed in some workflows.
> Example:
> 
> * I create a project and save a Wikibase schema there
> * I shut down OpenRefine and start it again the next day
> * I make edits on the target Wikibase without changing the schema again.

I did forget to consider these scenarios. The fallback does need to appear in the backend. We should still keep `mediaWikiApiEndpoint` and `editGroupsURLSchema` serialized then.
