### ISSUE TITLE
is Orient Db solution currently working for Open Refine? 

### ISSUE THREAD

**Issue by nitin-orolabs** [OpenRefine/OpenRefine#3690]
is Orient Db solution currently working for Open Refine? 
I want to do  transformations on  a 20gb file.  Is there any way to solve this problem using open refine using some disk based solution?

**Comment by wetneb** [comment]
Hi @nitin-orolabs,

Could you please ask this question on our mailing list instead? Perhaps by giving a bit more background on what Orient Db is - that might make it easier for the community to help you.

Thank you!

**Comment by tfmorris** [comment]
Most likely this: 
- https://groups.google.com/g/openrefine/c/TOgkfvI4ZV4/m/JIHtnZGKMzkJ
- https://github.com/lvca/OpenRefine

but I agree that the mailing list is the correct place for the discussion.
