### ISSUE TITLE
timestamp for Wikidata export: +2021-00-00 versus +2021-01-01

### ISSUE THREAD

**Issue by emu-at** [OpenRefine/OpenRefine#3694]
When exporting dates with a precision smaller than days, OpenRefine (Version 3.4.1) seems to export the year 1883 (as a random example) as +1883-01-01T00:00:00Z both with the export tool and QuickStatements.

However, if I understand those links correctly, it should be +1883-00-00T00:00:00Z (even though this isn’t ISO style):

https://www.wikidata.org/wiki/Help:Dates#Time_datatype
https://www.wikidata.org/wiki/Wikidata:Project_chat/Archive/2021/02#Dates_with_%3C11_precision
https://www.mediawiki.org/wiki/Wikibase/DataModel#Dates_and_times

While an argument could be made that Wikibase should normalize those entries, this isn’t the case at the moment, so I wondered if you could adjust OpenRefine’s behaviour. Thank you!

**Comment by loulankxh** [comment]
Sir, I'd like to work on this issue and I wonder if I can get this assignment. Thanks

**Comment by loulankxh** [comment]
For better understanding, it's deeply appreciated if the further information on how I can reproduce this problem(specifically where I can choose to export dates) could be given. Thanks again.

**Comment by wetneb** [comment]
Hi @loulankxh, how is it going? If you get stuck at any point feel free to reach out.

**Comment by loulankxh** [comment]
Sorry sir. I got a little busy several days ago and I'm currently considering this issue.
