### ISSUE TITLE
End to End testing for OpenRefine

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3709]
Since the introduction of Cypress, more and more features of OpenRefine are tested.
The approach was to test individual functionalities of OpenRefine such facetting, reconciliation and so on ...
Now it would be good to have tests that reproduce a real user behavior, with a project tested from end to end.

It will allows us to test combos of functionalities, for example facetting + filtering + reconciliation + re-facetting.

[Started as a thread on the mailing list](https://groups.google.com/g/openrefine/c/ZFx5w2Gld9w)

### Proposed solution

Implement fully, or partially the tutorials by @ostephens as Cypress tests https://librarycarpentry.org/lc-open-refine/

**Comment by wetneb** [comment]
We already have some tests which are drawn from tutorials, so I wonder if this can be closed, or if we want more of them?

**Comment by thadguidry** [comment]
@wetneb I think that as long as we have tests that incorporate transforms with history changes that also utilize all the object types @fgiroud mentioned, then I think we have things covered.  Generally, the object types and ensuring that memory/state is maintained well and restored well, no matter our object types (recon, etc.).  Which I think we already do.  So I think we can probably close this.

**Comment by fgiroud** [comment]
Yes, i think we cover the cases we wanted to have there
