### ISSUE TITLE
Group similar or same Proper Name

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#371]
_Original author: horn...@gmail.com (April 27, 2011 13:53:34)_

Would like a way to group Proper Names / Nouns, especially people, such as:
  William - Bill

This is similar to issue, 174 Anonymise Names, which is also an excellent idea, especially if need to re-expose the data after doing analysis.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=371_

**Comment by thadguidry** [comment]
@wetneb Hmm, I wonder how much Wikidata or Wikidata Lexemes might eventually help with this?  I wonder how much is possible now in OpenRefine 3.2 beta?

**Comment by wetneb** [comment]
It's not clear to me what this issue is requesting to be honest! If it's about reconciling first names, yes Wikidata can help as it stores first names ("Bill" https://www.wikidata.org/wiki/Q18245781 is "said to be the same as" "William" https://www.wikidata.org/wiki/Q12344159).

**Comment by thadguidry** [comment]
Thanks, I'll close this issue since we do not know the intent and have no way to contact the OP.
