### ISSUE TITLE
Regex match on string with newlines not working

### ISSUE THREAD

**Issue by ianengelbrecht** [OpenRefine/OpenRefine#3714]
Trying to do .match on a string with newlines does not return a result.  See example dataset

### To Reproduce
1. First, copy/paste the data below into a .csv file and import into OpenRefine.
2. Then, add column based on 'verbatimLocality', with expression: value.match(/.*(karkloof).*/i)
3. This does not return ['Karkloof'] for the first row as expected.
4. However, value.replace(/\s+/, ' ').match(/.*(karkloof).*/i), does return ['Karkloof'] for first row.
5. So replacing newlines with single spaces allows the match. 
6. Same for any of the first five rows that include newlines
7. Does not happen for last five rows which have no newlines. 

### Versions
 - Operating System: Windows 10
 - Browser Version: Chrome 89.0.4389.72
 - JRE or JDK Version: 
openjdk version "1.8.0_242"
OpenJDK Runtime Environment Corretto-8.242.07.1 (build 1.8.0_242-b07)
OpenJDK 64-Bit Server VM Corretto-8.242.07.1 (build 25.242-b07, mixed mode)

 - OpenRefine:  3.4.1

### Datasets
country,stateProvince,minorarea,gazetteer,verbatimLocality
,,,,"Mt Gilboa Estate, Karkloof,
KwaZulu-Natal.

side path"
,,,,"Amatikulu N.R., KZN North
Coast."
,,,,"Transkei
Mzamba.
Wild Coast Casino."
,,,,"Opposite Jock's stores, Hooper
Rd, Crestholme."
,,,,"Kloof to east of Magwa
Gorge"
South Africa,Eastern Cape,,,Frazer's Falls   E. Cape.
South Africa,KwaZulu-Natal,,,"Giants Castle, KZN."
South Africa,KwaZulu-Natal,,,"Summerveld part of Assagay, KwaZulu-Natal, South Africa"
South Africa,KwaZulu-Natal,,,"Summerveld part of Assagay, KwaZulu-Natal, South Africa"
South Africa,KwaZulu-Natal,,,"Summerveld part of Assagay, KwaZulu-Natal, South Africa"

**Comment by ostephens** [comment]
The `match` function requires that the expression fully matches the content of the cell - not just a partial match. I also don't think the `match` function accepts switches on the regular expression - so the `i` at the end of the expression is not doing anything in this case.

Use `find` instead to do a more traditional regular expression, with switches

value.find(/.(karkloof)./i)

**Comment by wetneb** [comment]
Thanks @ostephens! It looks like there is no bug here, so we can probably close this?
