### ISSUE TITLE
Output filename with exotic characters is corrupted

### ISSUE THREAD

**Issue by isaomatsunami** [OpenRefine/OpenRefine#3724]
East Asian Characters in Project name are corrupted in exported files.

### To Reproduce
1. First, import the attached xls file, which has a filename of German-Japanese-French-Chinese characters.(and contains such characters inside cells too). Project names are not corrupted.
[äöüßいろはにàçéùè§繁體字.xls.zip](https://github.com/OpenRefine/OpenRefine/files/6144916/aouss.aceue.xls.zip)
2. Then, Export data as tsv/csv/excel
3. Finally, the output filename is "äöüß????àçéùè§???-xls.csv". German/French are preserved but Japanese /Chinese are not.

### Versions
 - Operating System: Mac OS
 - Browser Version: Firefox 61, Safari
 - JRE or JDK Version: java version "11.0.1" 2018-10-16 LTS/Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)/Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode
 - OpenRefine: 3.5-SNAPSHOT 

### Additional context
The problem of the same kind on importing files with exotic characters is perfectly resolved. Huge thanks to dev team!

**Comment by gitonthescene** [comment]
Possibly related to https://github.com/OpenRefine/OpenRefine/issues/3277?

**Comment by gitonthescene** [comment]
Actually, it looks like the filename is set [here](https://github.com/OpenRefine/OpenRefine/blob/82b1cf0bfaf3c8ab57a12e0f2004bdeb71432383/main/src/com/google/refine/commands/project/ExportRowsCommand.java#L107) and passed to the browser in the `Content-Disposition` header.

[This doc](https://greenbytes.de/tech/webdav/rfc6266.html) seems to suggest the unicode needs to be url encoded with a byte-encoding specified.

In short, this looks fixable.
