### ISSUE TITLE
Option to split output to multiple files in the Custom Tabular Exporter

### ISSUE THREAD

**Issue by iomicifikko** [OpenRefine/OpenRefine#3732]
I'd like to export data to multiple files  in a zip archive.

### Proposed solution
I'd like to set a maximum _row limit_ or _weight size_ per file in the **Download** tab inside the **Custom Tabular Exporter** windows.

**Comment by gitonthescene** [comment]
Can you imagine explain the motivation a bit more?  How does this help your workflow? Exported how?  As csv?

*nix platforms have the [split commamd](https://man7.org/linux/man-pages/man1/split.1.html) which has a few options.

**Comment by iomicifikko** [comment]
Hi there,

I need to export CSV files in Windows to be loaded in another software that cannot import large files.
Same problem if large data sets must be read by human with spreadsheet software.

Regarding the suggestion to use an external software, "problems" could be the following:
- need to use a different app :)
- put the header row on all the files
- correct cut at the end of the row if you need to split by weight size (this is just a guess)

**Comment by gitonthescene** [comment]
I see.  I’m still not sure that this is general purpose enough to merit adding this feature but I’ll let other people weigh in.

Another workaround is for you to apply a facet and export the the file in pieces.  You could first add a row with the GREL expression `floor(row.index / numrows)` where `numrows` is the number of rows you want in each chunk and then filter on each value on that column using a text facet.  You may even be able to [automate](https://docs.openrefine.org/manual/running/#automating-openrefine) these steps.

**Comment by iomicifikko** [comment]
Thank you for the link! I'll give it a look for use.

**Comment by gitonthescene** [comment]
FWIW, the first link in the doc referred to is broken.  It should point [here](https://docs.openrefine.org/manual/running/#reusing-operations).  I'm submitting a fix shortly.

**Comment by iomicifikko** [comment]
Got it, thank u.

**Comment by thadguidry** [comment]
Closing as won't fix, since there are several different options available to users to handle splitting a large file (and many are freeware and open source even on Windows such as HJSplit and 7zip)
