### ISSUE TITLE
Cant edit individuall cells.  Overtyping value generates a window saying null

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#376]
_Original author: southan_...@hotmail.com (May 05, 2011 13:51:03)_

<b>What steps will reproduce the problem?</b>
1.Hover over specific cell
2.Click edit 
3.Overtype value in pop up 
4. Hit enter 
5. Ge message from webpage saying 'null'

What is the expected output? What do you see instead? I expect to see entered value populate cell

What version of Google Refine are you using? Version 2.0 [r1836]
What operating system and browser are you using?  Windows 7 with IE 9.08112

Is this problem specific to the type of browser you're using or it happens in all the browsers you tried? not tried it in another browser as refine always opens IE9.  I have Chrome installed.  
<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=376_

**Comment by thadguidry** [comment]
Closing since IE9 browser is no longer supported
