### ISSUE TITLE
Fix flaky test 'create_project'

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3764]
Create_project.spec.js is overall flaky and creates a lots of noise in builds and cypress dashbaord

Example of failed builds

- [782](https://dashboard.cypress.io/projects/s5du3k/runs/782/overview)
- [780](https://dashboard.cypress.io/projects/s5du3k/runs/782/overview)
- [777](https://dashboard.cypress.io/projects/s5du3k/runs/782/overview)
- [773](https://dashboard.cypress.io/projects/s5du3k/runs/782/overview)

**Comment by fgiroud** [comment]
@kushthedude do you want to fix this one ?
I don't mind to have a look if you want

**Comment by kushthedude** [comment]
I made sure the tests have no error from my previous PR of limiting the timeouts, looks like the error is in the support cypress function which checks for the 404 HTTP page, I will try to see a workaround for this asap.
