### ISSUE TITLE
Not seeing a NaN when expected on initial import

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#377]
_Original author: PaulMake...@gmail.com (May 10, 2011 17:48:18)_

<b>What steps will reproduce the problem?</b>
1. Import the attached file (containing simply the number 0 and a header)
2. Edit cells -&gt; Transform: value / value

<b>What is the expected output? What do you see instead?</b>

Expect to see NaN - see instead null.

<b>What version of Google Refine are you using?</b>

2.0

<b>What operating system and browser are you using?</b>

Windows Chrome

<b>Please provide any additional information below.</b>

If I transform the column to text and then back to numbers I get the expected NaN as though the initial import missed something in construction.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=377_

**Comment by wetneb** [comment]
To rephrase this issue: `0 / 0` should evaluate to `NaN` in GREL.

**Comment by thadguidry** [comment]
It's really nice to see this issue finally closed after all these years.  It pops up for me every now and again.  So, many thanks @elroykanye for fixing this.
