### ISSUE TITLE
Improve Wikidata login experience by showing Logged in dialog box after login

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3773]
When a user first logs into Wikidata, or logs out through the **Manage Wikidata account** option of the Wikidata extension and then logs in, the UX leaves the user wondering what happened since the login dialog disappears, leaving the user to assume they logged in successfully.

### Proposed solution
Ideally, the current "logged in" dialog (`bind="explainLogin"`) could actually be shown immediately after login instead to give a better login experience for the user.
Then the user has a nice visual confirmation and can be satisfied and simply close the dialog.

![image](https://user-images.githubusercontent.com/986438/112659860-cdefa900-8e22-11eb-8ec8-514d121bd3d0.png)

### Alternatives considered
Keeping the current login experience which hides what has happened, I.E. a successful login.

**Comment by wetneb** [comment]
I think that makes sense when the user spontaneously accesses the dialog by themselves.
But there are also cases where the login dialog is shown as a prerequisite to accessing another dialog, such as the upload edits dialog. In that case, the current behaviour might be better, since it's better to take the user to the dialog they requested in as little clicks as possible.

**Comment by thadguidry** [comment]
@wetneb But you agree that at a minimum there should be **some confirmation to the user that they have successfully logged in** ?

**Comment by wetneb** [comment]
Yes, but I think in the specific case where the log in dialog was brought up because the user tried to access the upload dialog, the upload dialog serves as a sufficient confirmation (since it is written there "You are logged in as MyUsername").

**Comment by thadguidry** [comment]
Ah!  I finally see it... not very prominent, I missed it... here's the steps...

1. Clicked **Upload edits to Wikidata**
![image](https://user-images.githubusercontent.com/986438/113038715-6e640700-915c-11eb-8f26-4ffc5490f4ce.png)

2. Then have the **Upload edits to Wikidata** dialog, which indeed has a small logged in confirmation.
![image](https://user-images.githubusercontent.com/986438/113038818-92bfe380-915c-11eb-92a5-c7a7ad58f703.png)

I'll close this issue then.
