### ISSUE TITLE
Rewrite in Python using WikibaseIntegrator

### ISSUE THREAD

**Issue by dpriskorn** [OpenRefine/OpenRefine#3784]
WDYT?
We would get lexeme support, probably commons structured data support also.

**Comment by tfmorris** [comment]
Thanks for the suggestion/request, but could you provide more context please? What are you proposing be rewritten in Python? What would the benefit be to OpenRefine users?

Answering the above will probably answer the rest of the questions, but what is "lexeme support" in the context of OpenRefine? I know what lexemes are, but I can't resolve the extreme shorthand to an OpenRefine feature. 

"Commons structured data" sounds vaguely like a Wikipedia thing. Is that correct? Can you expand on what the phrase means in this context and how it benefits the OpenRefine user community?

**Comment by wetneb** [comment]
If I understand correctly they suggest to rewrite OpenRefine in Python.

@dpriskorn the fact that OpenRefine is written in Java is not at all an obstacle to adding support for the things you mention. And it is a lot more effort to rewrite OpenRefine in another language compared to simply adding support for those features. It would be like buying a new house because you want to change the colour of your bed sheets. You can do it, but I would not recommend it.

**Comment by dpriskorn** [comment]
Interesting, I'm not very familiar with Java or openrefine. I recommend changing to wikibaseintegrator for uploading.
it support most things and the Dev is very responsive. 
https://github.com/LeMyst/WikibaseIntegrator

**Comment by gitonthescene** [comment]
@dpriskorn - I agree with @tfmorris’s post above that a more explicit description of how you think this might work is necessary to even consider if this is worth taking on.  Is there something you tried to do with OpenRefine as it is and couldn’t do?

Please provide an example, ideally with screenshots and/or sample input and output.

**Comment by dpriskorn** [comment]
oh, I thought you knew that we in wikidata would love to add identifiers to lexemes and be able to reconcile based on lemmas.
I have a list of 128000 words from saob that I would like to find the corresponding Swedish lemmas of and add the identifier to.
I ending up writing a custom script because openrefine could not do any reconciliation on lemma and language.

**Comment by gitonthescene** [comment]
Ah, so this is about reconciliation.  Reconciliation is actually handled by services to which OpenRefine connects.  Is your script a reconciliation service?  Could you share it?  Maybe it can be turned into a service.

There are a examples at the [reconciliation census](https://reconciliation-api.github.io/census/libraries/) for how to build a service.  In particular, `reconcile-demo` is written in Python.  [csv-reconcile](https://github.com/gitonthescene/csv-reconcile) is a bit more fleshed out example on the same model.

Is this also about using the Wikidata schema extension to upload Lexemes to Wikidata?  It might be good to make a separate issue explicitly for adding this.

**Comment by wetneb** [comment]
We already have #2240 for this :)

**Comment by dpriskorn** [comment]
big thanks @gitonthescene ! As I understood it the interface of openrefine might also need to change.
Your links seem very valuable to get started 😃
I am gonna work on a grant application or something to get this done.
