### ISSUE TITLE
Workspace files being written unnecessarily

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#3805]
### Current Results

It looks like all of the individual projects' `metadata.json` files are getting written every 5 minutes, even if the project hasn't been modified in any way - or even opened. This is both wasteful and error prone because it provides many more windows for project corruption when no file write is needed.

### Expected Behavior
File updates should be minimized and restricted to those that are actually needed. Unmodified files should not be re-written.

### Screenshots
![Screen Shot 2021-04-10 at 8 20 00 PM](https://user-images.githubusercontent.com/82178/114288229-a6f8c000-9a3b-11eb-938f-48fc93ca16ea.png)

### Versions
 - Operating System: macOS 11.2.3 Big Sure
 - Browser Version: Chrome Version 89.0.4389.90 (Official Build) (x86_64)
 - JRE or JDK Version: bundled
 - OpenRefine: 3.4.1

**Comment by ComgLq24** [comment]
Hi @tfmorris , I am interested in this issue, can you assign it to me to have a try?

**Comment by tfmorris** [comment]
I reopened this because every project is getting written every time OpenRefine starts up. I've started a branch which fixes that and a few other issues.
