### ISSUE TITLE
Type-ahead property selection fails with CORS exception in data-extension panel

### ISSUE THREAD

**Issue by matthieuj** [OpenRefine/OpenRefine#3809]
### To Reproduce
Configure OpenRefine with a reconciliation service that provides a property suggestion service. 

The manifest for such service includes:

	"suggest": {
		...
		"property": {
			"service_path": "/suggest/property",
			"service_url": "http://dock05:8080",
			"flyout_service_path": "/flyout/property?id=${id}"
		},
		...
		

Reconcile against that reconciliation server, then on the reconciled column menu select "Edit column" then "Add columns from reconciled values".

Start typing in the "Add property" text box

### Current Results
Instead of receiving suggestions as expected the browser consoles shows: "Sorry, something went wrong. Please try again later"

At the same time the browser console shows:

    project-bundle.js:10439 Cross-Origin Read Blocking (CORB) blocked cross-origin response http://dock05:8080/suggest/property?callback=jQuery112406009935240625213_1618220980169&prefix=d&spell=always&exact=false&scoring=schema&prefixed=true with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by wetneb** [comment]
@matthieuj thank you very much for the report and the fix!
