### ISSUE TITLE
Provide web hosted version of Refine (a la Google Docs or Fusion Table)

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#381]
_Original author: JasonMVi...@gmail.com (May 16, 2011 14:51:04)_

I would love to see Google refine hosted by Google as a document type in Google docs.  Perhaps some of the features used here could be fused together with Google spreadsheets?

I find that it's difficult with my machines to run the JRE due to conflicts with other JRE versions I need to keep running on my machine.  

This would also allow me to more easily collaborate with my refine projects.

Thanks!
Jason

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=381_
##

**Comment by pmackay** [comment]
http://refinepro.com/hosting/ seems to provide some options for this. I havent tried.

**Comment by thadguidry** [comment]
This is still open ?  Gosh, I need to start triaging our old backlog of things we (OpenRefine contributors) will NEVER DO BUT THANKS ANYWAYS.
