### ISSUE TITLE
Support BCE dates in Wikibase upload

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3816]
The Wikibase extension does not currently let the user upload "negative" dates (in the Julian/Gregorian calendars).

The currently supported formats are documented here: https://www.wikidata.org/wiki/Wikidata:Tools/OpenRefine/Editing/Schema_alignment#Dates

### Proposed solution
Introduce a new syntax for those dates. For instance `-YYYY` or `YYYY BCE` could be used. Both are supported by Wikibase's UI.

### Alternatives considered
We already support setting arbitrary calendars so in theory users could just use a calendar whose origin is before the date they want to represent, but that's really complicated and Wikibase will not convert between calendars by itself.

### Additional context
Requested on the mailing list:
https://groups.google.com/g/openrefine/c/nBLMNsq98k4

**Comment by wetneb** [comment]
Marking as a good first issue since this is fairly self-contained: changes should be contained to this class and its corresponding test class:
https://github.com/OpenRefine/OpenRefine/blob/master/extensions/wikidata/src/org/openrefine/wikidata/schema/WbDateConstant.java

**Comment by loulankxh** [comment]
Hi, sir. I want to have a try at this issue but I encountered a problem when I try to build, compile the wikidata extension before running the tests. The error message is "Failed to execute goal on project wikidata: Could not resolve dependencies for project org.openrefine:wikidata:jar:3.5-SNAPSHOT: org.openrefine:main:jar:tests:3.5-SNAPSHOT was not found in https://oss.sonatype.org/content/repositories/snapshots/ during a previous attempt." and the website "https://oss.sonatype.org/content/repositories/snapshots/" is permission denied. I have tried many mirrors to try to get the dependency wikidata jar, however none of them succeed for this problem. I wonder if you know some possible reasons. Thanks

**Comment by wetneb** [comment]
Hi @loulankxh, thanks for giving this a try! Yes this is a known issue about our build setup. Have you tried `mvn compile test-compile`?

Is this a problem you have through some IDE? On the command-line I would recommend to use the `refine` wrapper with `refine build`.

**Comment by loulankxh** [comment]
Thanks really! The problem has been solved and now I can run tests for the wikidata module successfully. I will continue to fix this issue.
