### ISSUE TITLE
Command line options documentation are inconsistent

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3818]
In https://docs.openrefine.org/manual/running we indicate `-Drefine.headless=true` as the option to add to run OpenRefine in headless mode. But trying it with `./refine -Drefine.headless=true` does not work. Instead `./refine -x refine.headless=true` does.

There seems to be a discrepancy between the syntax on the command line (`-x`) and in `refine.ini` (`-D`). The documentation should make that clear. Ideally we should probably avoid this difference of syntaxes.

### To Reproduce
Run `./refine -Drefine.headless=true`

### Current Results
The syntax is rejected.

### Versions
 - Operating System: Linux
 - OpenRefine: master branch

**Comment by AtharvaParkale** [comment]
I would like to work on this issue.

**Comment by wetneb** [comment]
Thank you!

**Comment by AtharvaParkale** [comment]
Hey, you just want changes in documentation right?
Can you tell me something more about your issue?

**Comment by wetneb** [comment]
The simplest way to fix this would indeed be to update the documentation :)

**Comment by AtharvaParkale** [comment]
> The simplest way to fix this would indeed be to update the documentation :)

OKay, I got it.

**Comment by Shatakshi0805** [comment]
I have created a PR that might fix this issue. @wetneb
