### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3819]
As pointed out by @gitonthescene in https://github.com/OpenRefine/OpenRefine/issues/3629#issuecomment-820787026, some links in https://docs.openrefine.org/manual/expressions/#grel-supported-regex are broken, for instance the "contains" GREL function which links to https://docs.openrefine.org/manual/expressions/grelfunctions#containss-sub-or-p.

We should:
- [x] make sure the CI detects this
- [x] fix those links

**Comment by wetneb** [comment]
So after some investigation in #3820 it turns out those broken links are actually generated by Netlify, which "prettified" URLs by adding trailing slashes to them, which broke relative links in those pages. I have disabled this feature, however pages will still load when they have a trailing slash. We need to remove this trailing slash with a redirect to keep the internal links functional.

**Comment by gitonthescene** [comment]
FWIW, when I click on [this link](https://docs.openrefine.org/manual/expressions/#grel-controls) I'm taken to https://docs.openrefine.org/manual/expressions/grel and not https://docs.openrefine.org/manual/expressions#grel nor https://docs.openrefine.org/manual/expressions/#grel.  These last two links work.  That is to say it looks like it's the missing `#` to me and not a trailing `/`.

**Comment by wetneb** [comment]
Ah good point. Docusaurus does not validate the anchors yet (https://github.com/facebook/docusaurus/issues/3321), so that can still be broken. But still I am surprised that when you go to https://docs.openrefine.org/manual/expressions/#grel-controls you are taken to https://docs.openrefine.org/manual/expressions/grel, for me I simply land at https://docs.openrefine.org/manual/expressions/#grel-controls (with no scrolling anywhere, the anchor is apparently not found).

**Comment by gitonthescene** [comment]
Is this client side routing?  I'm using FF 87.0, but I just checked and I get the same result with Chrome 90.0.4430.72.

Checking the links, it looks like clojure goes to https://docs.openrefine.org/manual/expressions/jythonclojure#clojure instead of https://docs.openrefine.org/manual/jythonclojure#clojure which works.  Similarly for jython, so it seems to be a different issue than GREL.

**Comment by wetneb** [comment]
I am not quite sure what is going on here - can you just check whether those links work for you in the deploy preview of the associated PR? For instance if you go to https://deploy-preview-3821--openrefine-docs.netlify.app/manual/expressions/, the links should work as expected.

**Comment by gitonthescene** [comment]
The GREL link worked here, but it's still pointing to https://deploy-preview-3821--openrefine-docs.netlify.app/manual/grel.  The clojure and Jython links worked as well with names that look similar to the above.  If it works, I'm happy, but it is odd that you see different links than I do.  Is it possible something is cached on my client?  Do we need to force some cache to expire when it's updated?  (I forget the name for this technique, but the idea is to put a timestamp in the name of the url and set it to never expire.)

**Comment by wetneb** [comment]
Ok, I think this is just a communication issue then - I think we see the same links, and they work, so that's great.

**Comment by thadguidry** [comment]
@wetneb The CI doesn't seem to be detecting the broken links actually.  We still have a few on our docs site.

My local testing with `yarn build` exposed the following (which I have created PR #4475 to fix
```
√ Client

* Server █████████████████████████ cache (99%) shutdown IdleFileCachePlugin

Exhaustive list of all broken links found:

- On source page path = /3.4/manual/running:
   -> linking to ../technical-reference/translating-ui (resolved as: /3.4/technical-reference/translating-ui)

- On source page path = /3.4/manual/troubleshooting:
   -> linking to ../technical-reference/translating-ui (resolved as: /3.4/technical-reference/translating-ui)

    at Object.reportMessage (E:\GitHubRepos\OpenRefine\docs\node_modules\@docusaurus\utils\lib\index.js:358:19)
    at Object.handleBrokenLinks (E:\GitHubRepos\OpenRefine\docs\node_modules\@docusaurus\core\lib\server\brokenLinks.js:142:17)
    at async buildLocale (E:\GitHubRepos\OpenRefine\docs\node_modules\@docusaurus\core\lib\commands\build.js:160:5)
    at async tryToBuildLocale (E:\GitHubRepos\OpenRefine\docs\node_modules\@docusaurus\core\lib\commands\build.js:32:20)
    at async Object.mapAsyncSequencial (E:\GitHubRepos\OpenRefine\docs\node_modules\@docusaurus\utils\lib\index.js:313:24)
    at async Object.build [as default] (E:\GitHubRepos\OpenRefine\docs\node_modules\@docusaurus\core\lib\commands\build.js:68:25)
    at async serve (E:\GitHubRepos\OpenRefine\docs\node_modules\@docusaurus\core\lib\commands\serve.js:23:15)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

E:\GitHubRepos\OpenRefine\docs>
```

Do you want to reopen this issue?
There's some good info here:
https://docusaurus.io/docs/deployment#deploying-to-netlify
https://docusaurus.io/docs/api/docusaurus-config#onbrokenlinks

**Comment by thadguidry** [comment]
@wetneb hmm, how the hell can we see that onBrokenLinks actually triggered (or ran) in our CI/CD ?  I must be looking at Netlify wrong or something's not logging correctly?

**Comment by wetneb** [comment]
As far as I can tell it does work, for instance in this run from one of your recent PRs:
https://app.netlify.com/sites/openrefine-docs/deploys/61f4d31a6ca34500074172f4
(Note that this feature only checks for internal broken links, so all the ones that started with `https://docs.openrefine.org/` were not checked, and this is expected.)

**Comment by thadguidry** [comment]
@wetneb OK then.  And as far as you are aware, our Netlify config is OK?  I.E. we don't need to change anything that is concerned in that Red warning box in Docusaurus docs about Netlify deploy? https://docusaurus.io/docs/deployment#deploying-to-netlify

If no, we don't need to change anything for Netlify currently... than we can close this issue now I guess, since there's nothing more to do here?
