### ISSUE TITLE
Cannot sign in for loading with Safari

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#382]
_Original author: Duncan.O...@gmail.com (May 18, 2011 10:51:48)_

<b>What steps will reproduce the problem?</b>
1. Prepare data for a refinery load (clean data, align schema, etc.)
2. Go to &quot;Load into Freebase…&quot; and try to sign into Freebase
3. Attempt to connect to Google Refine with Freebase log in 

<b>What is the expected output? What do you see instead?</b>
Expected: Window closes, and account is logged in for Google Refine
Instead: Connect page reloads and prompts for connection again

<b>What version of Google Refine are you using?</b>
2.0

<b>What operating system and browser are you using?</b>
Mac OS X 10.6.7
Safari 5.0.5

<b>Is this problem specific to the type of browser you're using or it happens</b>
<b>in all the browsers you tried?</b>
Google Chrome (11.0.696.68) works

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=382_
##

**Comment by thadguidry** [comment]
Freebase is gone.  Closing.
