### ISSUE TITLE
Restore progress reporting support in new architecture

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3826]
In the new architecture, the reporting of the progress of importers or long-running operations was temporarily disabled. For instance, when running a reconciliation operation, progress will jump from 0% to 100% without any intermediate steps. We need to restore this functionality.

### Architecture

Some progress reporting callbacks can be passed through the datamodel interface, when running some specific long-running operations (such as saving a `ChangeData` object to disk, which is where long-running operations actually spend their time fetching/computing).

This will also require us having a way to estimate the total size of the object being written / computed. For ChangeData this should hopefully be derived from the parent GridState (via its own cached count).

### For the testing runner

We can just increment progress at random places in the loop, no problem.

### For the local runner

We need a way for multiple threads to increment a shared progress counter and call the progress reporting callback at a sensible frequency. I have looked into various primitives (such as `AtomicLong.getAndAdd()`, it's still not clear to me what is the best performance-wise. It also depends on the sorts of guarantees we want to have (for instance ensure that progress never goes backwards artificially).

### For the Spark runner

Unfortunately, there does not seem to be any simple way to report progress in a granular way. There is the notion of [accumulators](https://spark.apache.org/docs/latest/rdd-programming-guide.html#accumulators) which would be a perfect fit, but unfortunately their value is only updated at the end of tasks, not during the task, so it would not make progress reporting much more granular than it is at the moment.

**Comment by thadguidry** [comment]
For Spark, I'm less worried about that? After all, anyone with some Spark experience can actually debug the Tasks themselves and see what's happening and get a feel for the progress from the Spark web interface.

For the Local runner, I think we can just do lots more benchmarking and testing various large datasets and then circle back to this issue and make some tuning or adjustments to the approach.  Even if we just start with something simple like the progress is a "best guess that 25%, 50%, 75% done"...that at least is feedback enough that users won't CTRL-C and stop the whole process.

**Comment by wetneb** [comment]
This has been implemented in [484fd92](https://github.com/OpenRefine/OpenRefine/commit/484fd92104011c048cf2b40aeac7980d465f23f9).
