### ISSUE TITLE
Windows10 cannot find or load com.google.refine.Refine

### ISSUE THREAD

**Issue by samaritanhu** [OpenRefine/OpenRefine#3828]
> refine.bat
Using refine.ini for configuration
Getting Java Version...
java version "13.0.1" 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
=====================================================
Getting Free Ram...
Error: Cannot find or load com.google.refine.Refine
Reason: java.lang.ClassNotFoundException: com.google.refine.Refine

### Versions
 - Operating System: Windows10 
 - JRE or JDK Version: 13
 - OpenRefine: latest version (git pulled before running the `refine.bat`)

**Comment by wetneb** [comment]
Did you try doing `refine.bat clean` before?

**Comment by samaritanhu** [comment]
Hi @wetneb. Yes I tried this, and it appears that 
`Using refine.ini for configuration`
`Windows cannot find the specified file directory.`

**Comment by wetneb** [comment]
Maybe @thadguidry can help debug this?

**Comment by thadguidry** [comment]
Hi @samaritanhu 
You likely might be having a system environment issue.
Your JDK looks OK enough so we just need to ensure that the Maven Build is working correctly, so try:
1. `refine clean`
2. `refine build`
3. `refine.bat`

Ensure that the build completes successfully and you have no Maven build errors.
By default, it should have downloaded Maven for you, but you can also use an existing Maven install and ensure `MVN_HOME` env variable is set correctly.

We've had many folks, such as myself, contribute to our detailed steps here: https://docs.openrefine.org/technical-reference/build-test-run
Let us know if those steps and optional steps detailed don't work, then we can try some more advanced Maven commands to see where the problem may lie with your system environment.

**Comment by samaritanhu** [comment]
> Hi @samaritanhu
> You likely might be having a system environment issue.
> Your JDK looks OK enough so we just need to ensure that the Maven Build is working correctly, so try:
> 
> 1. `refine clean`
> 2. `refine build`
> 3. `refine.bat`
> 
> Ensure that the build completes successfully and you have no Maven build errors.
> By default, it should have downloaded Maven for you, but you can also use an existing Maven install and ensure `MVN_HOME` env variable is set correctly.
> 
> We've had many folks, such as myself, contribute to our detailed steps here: https://docs.openrefine.org/technical-reference/build-test-run
> Let us know if those steps and optional steps detailed don't work, then we can try some more advanced Maven commands to see where the problem may lie with your system environment.

I successfully built!
My main problem is using `maven clean` and `maven build`. In openrefine project, we need to use `refine clean` instead. 

Thanks for helping!
