### ISSUE TITLE
Request: Tools for data verification and comparison.

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#384]
_Original author: EHOPstore@gmail.com (May 19, 2011 19:28:50)_

Tools for data verification and comparison. 

Ultimately, I would like to be able to compare to a valid set of data A to a unrefined set B returning a &#37; in validity. I'm not asking for a simple exact match of string but rather contextual sense of correctness. 

E.G&gt; refining a list of addresses. Users may input erroneous or invalid entries which need to be corrected; common typos. These addresses may be similar enough to be matched and refined by comparing it to another set of data containing valid addresses.

Much like the function of Google search which suggests correction for mistyped values.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=384_

**Comment by wetneb** [comment]
Closing as this is too fuzzy to suggest a clear path to add support for this use case.
