### ISSUE TITLE
Add 'Windows-1252" to the Common Encodings List

### ISSUE THREAD

**Issue by iomicifikko** [OpenRefine/OpenRefine#3862]
It might sound a bit pretentious but I would suggest adding **windows-1252** to the list of common character encodings as well.
In my experience most of the documents I deal with are **UTF8** or **windows-1252**.

Also according to wikipedia "[It is the most-used single-byte character encoding in the world](https://en.wikipedia.org/wiki/Windows-1252)" :)

![image](https://user-images.githubusercontent.com/61201406/116696092-ba0b0a00-a9c1-11eb-8d40-a9006a068721.png)

**Comment by gitonthescene** [comment]
FWIW, the list appears to come from [here](https://github.com/OpenRefine/OpenRefine/blob/577caabec1cce968df56156d7561a1ffde4b01c4/main/webapp/modules/core/scripts/util/encoding.js).  It might be nice if it was a resource file that end users could modify.

**Comment by gitonthescene** [comment]
@iomicifikko I'm happy to try to make this change.  Any suggestions for how best to test this?  Did you have any particular text you were interested in?  Mind posting it if you have?

**Comment by iomicifikko** [comment]
Thank you!
Here it is: [test01.zip](https://github.com/OpenRefine/OpenRefine/files/6409197/test01.zip)

_**utf-8 encoding selected**_

![image](https://user-images.githubusercontent.com/61201406/116776810-d911a680-aa6a-11eb-9e83-03933d1de91b.png)

_**windows-1252 encoding selected**_

![image](https://user-images.githubusercontent.com/61201406/116776826-f181c100-aa6a-11eb-9390-ad1786bd29a4.png)

**Comment by gitonthescene** [comment]
Hmm..  I'm a little confused here.  First off, here's what I get when opening your sample with OpenRefine 3.4:

<img width="1091" alt="Screen Shot 2021-05-01 at 6 05 42 PM" src="https://user-images.githubusercontent.com/45531702/116777174-0b8dc480-aaa8-11eb-988f-4eaaa30664d5.png">

i.e.  it's auto-detecting `windows-1252`.  Does it do the same for you?

Also, I don't understand where that second screenshot comes from.  Did you get it from the auto-detected encoding?  Did the first screenshot come from selecting `UTF-8`?

Is the only issue the ability to ___select___ `windows-1252`?
