### ISSUE TITLE
No error message when you have 5 or less rows of XML

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#387]
_Original author: jinyoung...@gmail.com (May 22, 2011 20:06:00)_

<b>What steps will reproduce the problem?</b>
1. Have an XML file with 5 or fewer rows.
2. Open it up in Google Refine.
3. No rows are shown, no error is mentioned.

<b>What is the expected output? What do you see instead?</b>

I expect either an error saying that there needs to be an minimum of 6 rows or to see the rows even if there are only 5 rows.

<b>What version of Google Refine are you using?</b>

Version 2.0 for Mac.

<b>What operating system and browser are you using?</b>

Mac OS X 10.6.7, Firefox 3.6.13

<b>Is this problem specific to the type of browser you're using or it happens</b>
<b>in all the browsers you tried?</b>

Didn't try other browsers.

<b>Please provide any additional information below.</b>

We thought for a while that our app was outputting data in a odd way because it seemed to not import into Google Refine.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=387_

**Comment by WaltonG** [comment]
@antoine2711 @wetneb Can I work on this ? I have confirmed the system hangs with no error message when uploading an xlm file with rows less than or equal to 5
