### ISSUE TITLE
bad error message when giving -m less than 256M

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#388]
_Original author: jeff.al...@gmail.com (May 22, 2011 22:48:28)_

<b>What steps will reproduce the problem?</b>
1. ./refine -m 128M
2. Get error &quot;incompatible min and max heap size&quot; or something.

<b>What is the expected output? What do you see instead?</b>

I expected it to just work, even on my little machine. It didn't. I discovered the -m argument. I expected it to work, it didn't. I read the shell script and realized I had to hack it to lower the default 256M to 128M.

What version of Google Refine are you using?  r1836

What operating system and browser are you using? Linux, Firefox

<b>Is this problem specific to the type of browser you're using or it happens</b>
in all the browsers you tried? No

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=388_

**Comment by aakankasha028** [comment]
@thadguidry I would like to take up this issue so as to make the first contribution. I propose the following changes 

1. Update the usage message for -m by adding the line "values less than 256M are not allowed"
2. While parsing the command line arguments, if the value for -m is less than 256 ( if [ $1 -lt 256  ) then, show them the usage and exit (or show them an error message and exit)
3. Add a comment in the wiki page

**Comment by wetneb** [comment]
Sounds like a great plan to me!

**Comment by aakankasha028** [comment]
@wetneb I have made the changes to the shell script and the PR is at https://github.com/OpenRefine/OpenRefine/pull/2489. The electricty went off just as I pushed my changes so had to rebase them all over again and then create the PR, hence the delay between the push and the creation of PR

Please review the same. Post that, I will update the wiki page as well.

**Comment by wetneb** [comment]
Ok, I am a bit confused by the result. Could you perhaps re-submit the PR as a single commit? Start a new branch from master, cherry-pick your commit from the old branch, push the new branch and submit it as a PR?

**Comment by aakankasha028** [comment]
Sure, I'll do that!
