### ISSUE TITLE
Use explicit anchor ids in documentation

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3888]
When translating the docs, the section titles will change, meaning that the auto-generated anchor ids for them will also change.

Docusaurus recommends setting explicit ids in the markdown files for the headings:
https://docusaurus.io/docs/next/i18n/tutorial#use-explicit-heading-ids

### Proposed solution

We could potentially auto-add all of them with a script as a one-off solution. Ideally, we should have a CI job that checks that those ids are always set, but it's going to be pretty annoying for people writing documentation I would say.

### Alternatives considered

Let the hashes vary by language, but that makes the translators' life pretty horrible, I guess.

**Comment by thadguidry** [comment]
> Ideally, we should have a CI job that checks that those ids are always set, but it's going to be pretty annoying for people writing documentation I would say.

Why annoying, can you explain further?

**Comment by wetneb** [comment]
Because they will need to add all these ids manually :)

**Comment by wetneb** [comment]
Actually, Docusaurus has a CLI command for this! So it should not be hard at all.

https://docusaurus.io/docs/cli#docusaurus-write-heading-ids-sitedir
