### ISSUE TITLE
Support localized user interface

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#39]
_Original author: iainsproat (May 14, 2010 16:24:08)_

Gridworks should (eventually) be available in multiple human languages.  The 
code does not currently support internationalisation.

With regards to Java code, all messages and strings should be read in from an 
external resources file.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=39_
##

**Comment by wetneb** [comment]
OpenRefine is now available in multiple languages and uses jQuery's i18n features for that.
