### ISSUE TITLE
Update user manual and in-app documentation for splitByLength()

### ISSUE THREAD

**Issue by mgutierrez98** [OpenRefine/OpenRefine#3934]
The documentation, specifically for splitByLength() does not inform the user that they have the possibility to only return values within a given range of indices, Iv since updated the document but wanted to make a bug report on it for submitting the PR.

ex: 
`"123456789012345678901234567890".splitByLengths(3,4,5)[0,2]`
`returns [ "123",  "4567" ]`

More about this issue can be seen in this thread: https://github.com/OpenRefine/OpenRefine/issues/3929

**Comment by Maezzzzz** [comment]
@wetneb if you want to assign me to this I should be able to get a PR today.

**Comment by Maezzzzz** [comment]
having not worked with docusaurus or node before, if anyone knows, how do I get my local changes to show on localhost?  they seem to not want to show up and instead uses the weblink to grab the grelfunctions doc from the repository.

**Comment by Maezzzzz** [comment]
welp, first time committing with git, went pretty bad. If you need me to fix the discrepancies between the grelfunction files let me know, the versioned doc is the proposed change the other grel file was what I used to attempt to build the new doc site before realizing I had to edit the versioned documents.

**Comment by TheTrailblazer09** [comment]
Hi could I be assigned to this?
