### ISSUE TITLE
Support splitting a string to an array based on a set of repeated string lengths

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#3948]
Originated in #3929.
**Minor Update 2021-05-28:** Make sure to see comments below about preference to create new operation rather than amending splitByLengths() as in proposal

Currently there is no easy way to split a string into an array based on a set of repeated string lengths. For example if a cell contains a string that concatenates several fixed length strings together with no separators there is no straightforward way of splitting that string back to the original fixed length strings.

Example 1:
Cell contains a string created by concatenating four ID numbers each four digits long. The original IDs are:

- 1234
- 5678
- 9012
- 3456

The cell content is `1234567890123456`

The desire is to get an array with the four IDs separator: `["1234", "5678", "9012", "3456"]`

Example 2:
Cell contains a string created by concatenating pairs of fixed length strings. Each pair consists of two book identifiers - the 10 character OCLC number and the 13 character ISBN. The original string pairs are:

- 1128883299,9780399208539
- 0890160519,9780007586547

The cell content is `1128883299978039920853908901605199780007586547`

The desire it to get an array: `["1128883299", "9780399208539", "0890160519", "9780007586547"]`

### Proposed solution
Modified from original proposal by @thadguidry in # #3929

Enhance the existing GREL splitByLengths() function to support final boolean argument indicating whether the list of split lengths should be used as a repeated pattern for the whole length of the string.

`"12345678".splitByLengths(4,true)`
would output
`["1234", "5678"]`

`"12345678".splitByLengths(3,1,true)`
would output
`["123", "4", "567", "8"]`

The boolean value should default to `false` - i.e. if it is omitted then `false` is used so both of

- `"12345678".splitByLengths(4)`
- `"12345678".splitByLengths(4,false)`

Output `["1234"]`

If the repeated pattern does not exactly match the length of the string, the remaining characters should be included as the last item in the array. i.e.

`"12345678".splitByLengths(3,true)`
would output
`["123", "456", "78"]`

This is consistent with the current behaviour of splitByLengths() (`"12345678".splitByLengths(3,3,3) -> `["123", "456", "78"]`)

If this proposal were implemented the two example cases above could be resolved using:

- Example 1: `value.splitByLengths(4, true)`
- Example 2: `value.splitByLengths(10, 13, true)`

### Alternatives considered
Create a new operation that works as specified, that can exist alongside the current "splitByLengths()" operation. e.g. "splitByRepeatedLengths()" or "splitRepeatLengths()" (latter suggested in a comment below for increased brevity). I do not believe this is necessary if we implement as described here because there is no breaking change to the existing splitByLengths operation. If the implementation leads to a situation where the behaviour of "splitByLengths" introduces a breaking change, then we should consider a new operation instead. An advantage of having a new separate operation (as noted by @wetneb below) is that the boolean argument is no longer needed, keeping the inputs to just a list of integers for both the existing and the new operation

Similar outcomes to the proposed function might be currently achieved by:

- Using `match` with an appropriate regular expression 
- Fully specifying the set of repeated splits within splitByLengths()

But these are more complex or time consuming or require certain assumptions to be made about the total repetitions in the starting string

### Additional context
Originally proposed by @thadguidry in #3940. That issue was closed only to allow for a clean start with the proposal

**Comment by wetneb** [comment]
I think it is really worth considering adding this as a new GREL function as you mention. It would feel cleaner not to have to add a boolean argument after a variable list of numerical ones.

**Comment by thadguidry** [comment]
I also think creating a new GREL function might make things cleaner and less risky.  Maybe shorten the function name to `splitRepeatLengths` but I'm not strongly opposed to any name as long as it works as well documented.

**Comment by winkle29** [comment]
Hi @ostephens, I would like to work on this issue if it's okay?

**Comment by wetneb** [comment]
Before someone else opens a PR about this, I would be interested to understand better in which use cases such a function would be useful. @thadguidry do you remember what prompted you to request this? Not having much context about it, it feels like a pretty niche functionality.

**Comment by thadguidry** [comment]
@wetneb I had several database dumps of specialized GIS data (not PostGIS but using using its formats at times) where I needed to split the field values because they are stored in a binary hexadecimal format (WKB) and sometimes just in text/strings [WKT](https://handwiki.org/wiki/Well-known_text).  OpenRefine as a power tool is useful in many domains and this function would save time for those processing scientific data that often is in compressed textual formats with a repeated pattern from systems that could later be uploaded for knowledge sharing to Wikidata and elsewhere.

As far as being niche, I would say it is not, but more a convenience function over `splitByLengths()` when you have many repeated lengths to manage or extract, I.E. saves much boring repeated typing.  This function would be most useful for those getting data from databases where fields were compressed, I.E. not everyone is working with compressed data, so maybe niche in that sense.

Alternative now:  I am saving my repeated patterns and copy/pasting them instead of just typing them out.  I cannot use starred expressions because of the larger data cleaning transformations via GREL that I need to do across these projects, unfortunately.

**Comment by wetneb** [comment]
Thanks for the details!
Looking at WKT and WKB I cannot find an example string where splitting by repeated lengths is necessary - would you have an example of that?

If this feature is inspired by those formats specifically then I would say your needs would be served better by a dedicated WKT/WKB parsing library. This could be a Python library that you use via Jython or a set of GREL functions exposed by an OpenRefine extension.

**Comment by thadguidry** [comment]
Of course, many ways to solve the problem and I've already solved it.  This issue was about having a more convenient GREL function.  Let's close it until others have a similar need.
