### ISSUE TITLE
jquery.lavalamp.min.js is non-free

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3957]
[Posted by Markus Koschany on the openrefine-dev mailing list](https://groups.google.com/g/openrefine-dev/c/eJbPPYnqJiw):
> 
> Lavalamp is licensed under BY-NC 3.0 which makes it technically non-free and it
> cannot be included in Debian main because of the non-commercial clause. If I
> remove the file obviously some of the functionality of the main startpage is
> removed. I believe it should be possible to work around it or replace the
> plugin with a similar effect. In any case I had to remove the file from the
> sources for now.

This is a blocker for OpenRefine's packaging for Debian. Therefore we should investigate as soon as possible how to get rid of this dependency.

**Comment by ostephens** [comment]
Seems like this is used only to add an animation to the tags panel at the top of the Open Project screen. It could removed without losing any functionality. While the animation emphasises which tag you currently have your mouse over, it feels like a very minor aspect of the UX
