### ISSUE TITLE
Preview update with no effect is initiated after changing unused parameters

### ISSUE THREAD

**Issue by jquartel** [OpenRefine/OpenRefine#4009]
After loading a new file and coming to the Configure Parsing Options page, you have the ability to modify the parsing rules, which I do pretty frequently with the kinds of (mostly tsv-like) files that I get. Most frequently I need to change the "Ignore first" and "Discard initial" parameters and since I usually need both of these and since my files are large and complex enough for the preview update to take some time, I try to save time by changing the parameters before they are checked/enabled. However, I find that even with the parameters left unenabled, changing their value results in an "Updating preview" pause even though the preview isn't changed (as it shouldn't be because the parameter isn't enabled).

### To Reproduce
1. Open a data file (a csv, say) and continue to the "Configure Parsing Options" page
2. Change the "Ignore first" value without checking the enable box 
3. Observe the pause while "Updating preview", even though nothing about the preview is changed (until you enable the "Ignore first" value and then there is another pause and a correct preview update).

### Expected Behavior

I don't expect there to be any preview update when changing values of unchecked (unenabled) parsing parameters. Either that or the parameter should be enabled when you change the value, and then the preview updated accordingly. It might be good to have some way to hold off all preview updates until you explicitly press the Update Preview button, since I usually want to to change a few parameters and waiting for the update after each one is time consuming.

### Screenshots
<img width="582" alt="Screenshot 2021-06-24 at 14 28 27" src="https://user-images.githubusercontent.com/36742596/123272756-f65a7280-d4f9-11eb-9c0b-c5e6648abf51.png">

### Versions
 - Operating System: MacOS 10.14.6
 - Browser Version: Chrome 91.0.4472.114
 - JRE or JDK Version: Unknown
 - OpenRefine: Version 3.5-beta1 [1b9907e]

**Comment by johnvl2** [comment]
@wetneb Hello, I have been working this issue. Could you go ahead and assign me?

**Comment by wetneb** [comment]
Sure, thanks for working on this!

**Comment by johnvl2** [comment]
@wetneb I'm trying to manually test this out for Google Data and Database parsing but I'm unable to get either type working (on my branch and even on master). I'm trying to use the google doc mentioned in #3604 and the public database specified here: https://docs.rfam.org/en/latest/database.html (this db is mentioned in the manual). Google data gets stuck on the "Preparing..." screen and Database gives me a "error:Unauthorized" message. if you have any tips or could point me in the right direction, I would really appreciate it.

**Comment by wetneb** [comment]
@johnvl2 to test the Google Sheets importer, it looks like you do need to provide an API key (in `refine.ini` for instance). Sadly that seems to be necessary even for public Google Sheets documents. We have some instructions for how to get those: https://github.com/OpenRefine/OpenRefine/wiki/Google-Extension

For the database import, how about trying with a SQLite database? You can get a sample one here for instance: https://www.sqlitetutorial.net/sqlite-sample-database/

**Comment by johnvl2** [comment]
@wetneb That worked for the database, thank you! 

Unfortunately I'm still unable to get the google data tab working even after following the instructions in the link above. My error message is "Error 400: invalid_request, missing client_id", but I have my client_id retreived from the link's instructions, along with the client secret key and API key populated in the refine.ini file. After doing this, I simply did a ".\refine build" and then ".\refine" to rerun. Maybe I'm missing some info in the API setup: I have all required fields populated but there is no instruction for some of the other fields along the way.

Also, where can I find the current state of the test suite? Currently even on the master branch I am seeing the same two server test failures and five UI test failures in Cypress.

Thanks again for the help.

**Comment by wetneb** [comment]
Interesting!

The test suite should normally work. I suspect the two server test failures are due to Daylight Saving Time and have been fixed in https://github.com/OpenRefine/OpenRefine/pull/4295, so I would hope that pulling the master branch would solve those.

For Cypress, I also get some failures locally, but I thought it was because my machine was too slow for the timeouts that are set there - so if you are having them too, then there is a real problem! I will investigate.

**Comment by johnvl2** [comment]
@wetneb Pull request is up.

Some test evidence (see added case at bottom):
![image](https://user-images.githubusercontent.com/90931628/142555048-9a5ef720-e98d-408a-b309-aca11adcba86.png)

And evidence of the new feature (see "Disable auto preview" checkbox):
![image](https://user-images.githubusercontent.com/90931628/142555147-42deca74-b9d3-46eb-88d3-d8e9d8c36beb.png)
