### ISSUE TITLE
LGTM and Appveyor should not run when only /doc path is touched on PR

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#4019]
On a recent Draft Pull Request, I noticed that LGTM and Appveyor both ran, even though only files under `/docs` where touched.
We need to tweak our CI/CD workflows to exclude the `/doc` path as documented here: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-ignoring-paths

It also might make sense or be easier if we split up the CI/CD into multiple workflow files and then reference them as needed.  GitHub presents this as a solution for advanced job/step handling, instead of trying to do everything in 1 workflow file.

We might have a "update-docs.yml" file, along with others as needed.

### To Reproduce
1. Submit a PR or Draft PR with only change a file under `/docs` and notice LGTM and Appveyor fail with errors, but Netlify then continues.

### Current Results
LGTM and Appveyor are not skipped

### Expected Behavior
LGTM and Appveyor steps/jobs should be skipped entirely when only `/docs` path is touched.

### Versions
 - Operating System: 
 - Browser Version: 
 - JRE or JDK Version: 
 - OpenRefine:

**Comment by wetneb** [comment]
I don't think we should tag CI-related issues as "good first issue" or "help wanted" since it's not so easy to fix them when you are new to the project (people could need some privileges to access the corresponding services and configure them).

**Comment by wetneb** [comment]
This seems to be solved already, for instance see https://github.com/OpenRefine/OpenRefine/pull/4280
