### ISSUE TITLE
Update cross() documentation for version 3.5

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#4020]
As described in comment https://github.com/OpenRefine/OpenRefine/issues/2504#issuecomment-869328758 we should update our user manual for version 3.5 about the `cross()` function showing the project name is optional now, and can use an empty project, and also work with `rowIndex` quite nicely.  Since this is new in 3.5 version, this probably depends on our better supporting our doc versioning itself such as in 

- [x]  #4018 

, and it might also be good to mention the example use of `rowIndex` as demonstrated in that comment to help folks that want to `cross()` within their own project's columns.  Since this is non-obvious but a quick sentence like mentioned would help expose that potential to users.

**Comment by wetneb** [comment]
The versioning architecture for this and the changes specific to the cross function were done in https://github.com/OpenRefine/OpenRefine/pull/3847.

See the difference between those two:
- https://docs.openrefine.org/manual/grelfunctions#crosscell-s-projectname-s-columnname
- https://docs.openrefine.org/next/manual/grelfunctions#crosscell-s-projectname-optional-s-columnname-optional

So if you want to improve those descriptions, you should not need to improve the versioning mechanism at all.

**Comment by gitonthescene** [comment]
I've added a note to [this recipe](https://github.com/OpenRefine/OpenRefine/wiki/Recipes#using-cross-within-a-single-project) and [this one](https://github.com/OpenRefine/OpenRefine/wiki/Recipes#finding-previous-row) to indicate the new functionality.

**Comment by wetneb** [comment]
@gitonthescene thanks! @thadguidry is there anything left to do here or can we close this issue?

**Comment by thadguidry** [comment]
@wetneb I think its good now. Closing.
