### ISSUE TITLE
Load QA data spins forever if no QA data available (freebase extensions)

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#403]
_Original author: tfmorris (June 13, 2011 17:37:41)_

If you select Extensions-&gt;Freebase-&gt;Load QA Data for a job which has no QA data, the browser spins forever at the &quot;Working&quot; display.

The browser console shows:

3333/command/freebase-extension/import-qa-data?project=1510987358432

Failed to load resource: the server responded with a status of 404 (Not Found)

The error should be handled and reported to the user in a reasonable manner.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=403_

**Comment by wetneb** [comment]
This is Freebase specific so it does makes sense today.
