### ISSUE TITLE
Docusaurus broken link detection does not mark builds as failed

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4031]
We use a feature in Docusaurus to detect broken links in the docs but it only prints errors into the logs without failing the builds at the moment, so we are introducing broken links without noticing!

See for instance this build:
https://app.netlify.com/sites/openrefine-docs/deploys/60df5ce94f1a5f00077e1a61

We should probably change the `onBrokenLinks` option from `error` to `throw`?

**Comment by thadguidry** [comment]
Yes throw
