### ISSUE TITLE
Fix documentation for clustering

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4048]
[The documentation about clustering](https://docs.openrefine.org/manual/cellediting#cluster-and-edit) shows a screenshot of the clustering dialog where all the values in a given cluster look identical, which should not normally happen. This screenshot was taken before #4004 was fixed, which probably explains that. This screenshot should be replaced by a screenshot which shows different values being clustered together.

Current image:
![image](https://user-images.githubusercontent.com/309908/124904703-91b51280-dfe5-11eb-8bad-7d91a47f00ba.png)

Additionally it could be useful to rework the text to make the clustering feature clearer because it looks like the current documentation does not convey the intended usage very well.

This was noticed in #3422 by @fgiroud.

**Comment by wetneb** [comment]
With @fgiroud we plan to use the same dataset for documentation and for UX testing.

**Comment by Babi-B** [comment]
`With @fgiroud we plan to use the same dataset for documentation and for UX testing.`

@wetneb I'll like to do this. However,  would it be possible to work on the documentation given that I don't have the require dataset?

**Comment by antoine2711** [comment]
> However, would it be possible to work on the documentation given that I don't have the required dataset?

For the dataset, @Babi-B, it is suggested in the discussion to use a file from the UI Tests. Can you find one with appropriate text data, and create a new screencapture to replace the flawed one?

(They are called « Functional Tests » in the doc… https://docs.openrefine.org/technical-reference/functional-tests)

Regards, Antoine

**Comment by Babi-B** [comment]
Hello @antoine2711. I think I can. Could you assign me to this issue?
