### ISSUE TITLE
Want to unhide columns en masse

### ISSUE THREAD

**Issue by jenyoung** [OpenRefine/OpenRefine#4067]
Sometimes after I have already collapsed a bunch of columns, I'd like to unhide them en masse instead of one by one. This is very frustrating since I deal with projects that easily have 50 columns. Right now, I have to click on each column individually.

Edit: I missed that unhiding is available under All - it would be nice to also have it available under the column View menu with the left/right options available as well.

### Proposed solution
To the View Menu, add

- Show all other columns
- Show all columns to left
- Show all columns to right

### Alternatives considered
The only alternative is clicking one by one or exiting and reopening the project.

**Comment by thadguidry** [comment]
@jenyoung Hi!  You probably missed this, but it's already available under the **All** menu dropdown.
Hmm, but looking and thinking about this, perhaps you are right in your thinking...maybe it would be good to at least have another copy of the "All" -> "Expand all columns" additionally in the View menu so folks don't miss it?
Is that something you would expect as a better user experience?  If so, then feel free to edit your above comment to that specific ask and well try to work on this in the future.

**Comment by jenyoung** [comment]
Well probably since I didn't realize it was also under All ha!. However, it would be nice to also be able to do all to the left/right which is not available at all.
