### ISSUE TITLE
URLs with uncoded blanks are only partially recoignised by OpenRefine3.5 beta1

### ISSUE THREAD

**Issue by ToVie** [OpenRefine/OpenRefine#4070]
### Current Results
URLs with uncoded blanks are only partially recoignised by OpenRefine3.5 beta1. The string up to the unencoded blank is recognised as URL and the string after the blank is not recognised. This is a regression compared to OpenRefine 3.4.1, which recongnises URL with unencoded blanks.
- URL without unencoded blank is recognised: http://siibns.ch/german/display_before91.asp?cdu=Ebersberg&folder=bns\00023359&cursor=2
- URL with unencoded blank is partially recognised: http://siibns.ch/german/display_before91.asp?cdu=Ellikon an der Thur&folder=bns\00023471&cursor=2 

I tested on different browsers and operating systems. The result stays the same regardless of OS and browser.

### Expected Behavior
URL with unencoded blanks should be completely recognised.

### Screenshots
Both screenshots show one URL with unencoded blanks and one without.
#### OpenRefine 3.5 beta1 (incorrect)
![Screenshot OpenRefine URL 3 5beta1](https://user-images.githubusercontent.com/3183064/126891687-f81753d2-f67f-4bb1-9ebd-3dbcb978a557.png)

#### OpenRefine 3.4.1 (correct)
![Screenshot OpenRefine URL 3 4 1](https://user-images.githubusercontent.com/3183064/126891685-d0a5a4aa-304e-46d4-8388-7625b4d44fdd.png)

### Versions
 - Operating System:  macos 10.14.6, Windows 10 Enterprise 1909
 - Browser Version: macos: Firefox 90.0.2, Safari 14.02; win10: Edge 92
 - JRE or JDK Version: bundled version
 - OpenRefine: OpenRefine 3.4.1 and OpenRefine 3.5beta1

### Datasets
[01_Konkordanz-GEO_portioniert_E-F-(korr)-abgeschlossen-export.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/6873534/01_Konkordanz-GEO_portioniert_E-F-.korr.-abgeschlossen-export.openrefine.tar.gz)

**Comment by thadguidry** [comment]
This was a determined change we made.  Before, we treated the whole string in a Cell as a URL and didn't do any detection of a valid URL.  Whitespaces are not allowed in URLs. So just use a GREL transform on the column to encode for URL first.

**Comment by ToVie** [comment]
Hi @thadguidry. Ok, thanks for the info! I close this issue.

**Comment by thadguidry** [comment]
@ToVie If you need a quick way to validate a column of URLs, I typically just use this short Java interop expression with Clojure as my expression language. It attempts to convert the cell value to a URI, and then asks if the converted value is a URI.  You can optionally check the box to Store the error if you want in a new column, or use this in a Custom Text Facet.
```clojure
(uri? (.toURI (java.net.URL. value)))
```
![image](https://user-images.githubusercontent.com/986438/126904395-825b3f14-2775-46e9-9c33-c548ee3a3dc1.png)
