### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [OpenRefine/OpenRefine#4081]
https://github.com/OpenRefine/OpenRefine/blob/409cf2c30097ae7a5981e941d4bbee49896cd590/extensions/gdata/src/com/google/refine/extension/gdata/UploadCommand.java#L149

The program can potentially fail to release a system resource.

**Comment by WaltonG** [comment]
@wetneb Can I be assigned this ?
