### ISSUE TITLE
Enhancement FingerprintKeyer - normalize German ß to ss

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#409]
_Original author: bun...@gmx.net (June 14, 2011 08:43:17)_

Could you please extend the FingerprintKeyer with a normalization for the German Eszett &quot;ß&quot; to &quot;ss&quot;. This would help in common cases like Strasse = Straße.

The code would then look like

case '\u00DF':
  return 'ss';

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=409_

**Comment by thadguidry** [comment]
ICU4J could be used to provide normalize() and transliterate() commands The most recent bikeshedding discussion is here on our mailing list: https://groups.google.com/d/topic/openrefine/6hY1-GI0KAI/discussion
