### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by hagaiwech** [OpenRefine/OpenRefine#4092]
Hi OpenRefine team,

I tried to contact you through openrefine-coredev@googlegroups.com but it seems the group no longer exists or unable to receive messages.

I approach to you regarding security issues found, please get back to me at hagai.wechsler@whitesourcesoftware.com

Thanks,
Hagai

**Comment by wetneb** [comment]
Thanks, I am getting in touch.

**Comment by thadguidry** [comment]
@wetneb Will you fix the private email issue, or do we need to put another private email address in our SECURITY.md file https://github.com/OpenRefine/OpenRefine/edit/master/SECURITY.md

**Comment by wetneb** [comment]
@thadguidry it would indeed make sense to make openrefine-coredev publicly reachable but I don't seem to be the owner/admin/… of that list, can you check if you could do it on your side?

**Comment by thadguidry** [comment]
@wetneb the original idea for using openrefine-coredev email was that for security matters to have a private email to allow outside users to send an email to our team and where the messages are not seen publicly as our other email mailing lists.  The openrefine-coredev Google group is private and has the current description of "OpenRefine Project Management Committee (PMC)" private mailing and @magdmartin is the actual owner of that one.  So...

@magdmartin Thoughts ?
