### ISSUE TITLE
Open Refine opens with logo only when running on Java 16

### ISSUE THREAD

**Issue by P3rCo** [OpenRefine/OpenRefine#4106]
### To Reproduce
1. Click on open refine Application

### Current Results
2. This window appears:
3. 
![image](https://user-images.githubusercontent.com/89087309/129763348-5ea6f617-03d8-43fc-889d-2b9cec64d4b1.png)
4. This page appears
5. 
![image](https://user-images.githubusercontent.com/89087309/129763413-9f71ea36-5a20-4a3e-b079-eb1fe1934e4e.png)
6.I have installed the embedded Java version:
![image](https://user-images.githubusercontent.com/89087309/129763476-9d5707ff-98e0-4f98-af53-fb295a7247cb.png)
7.I have run it as adminstrator same results.

8. Tried to run the batch file
9. Same results: 
![image](https://user-images.githubusercontent.com/89087309/129764156-be788373-3b43-4ff6-bff2-afed0f7151ce.png)
10. Tried firefox
11. 
![image](https://user-images.githubusercontent.com/89087309/129764321-5b18991d-5330-4e2b-a56f-fc32072fa1e1.png)

### Expected Behavior
Open Refine page appears

### Versions
 - Operating System: Edition	Windows 10 Pro
Version	20H2
Installed on	‎17/‎03/‎2021
OS build	19042.1165
Experience	Windows Feature Experience Pack 120.2212.3530.0

 - Browser Version: 
![image](https://user-images.githubusercontent.com/89087309/129764189-7a54e277-0aed-4ea9-b043-52e03b0faa47.png)

 - JRE or JDK Version: 
 - Using embedded but:
 - 
![image](https://user-images.githubusercontent.com/89087309/129764400-6afd092a-659b-4e4f-a1d2-1df0e1c1f1d7.png)

 - OpenRefine: 3.4.1

**Comment by P3rCo** [comment]
Thanks a lot for any help guys, really stumped.

**Comment by orothad** [comment]
Do you still have an environment variable in Windows set for `JAVA_HOME` ?
If so, can you try temporarily removing that and trying to launch OpenRefine again ?

**Comment by P3rCo** [comment]
![image](https://user-images.githubusercontent.com/89087309/129797839-e0348bf5-2a16-41e6-8776-7615f057c37d.png)
Same result
![image](https://user-images.githubusercontent.com/89087309/129797873-a45487a5-0f53-4da4-9fe6-0a5111debf0a.png)
System variables (there was a java home, deleted it)
![image](https://user-images.githubusercontent.com/89087309/129797998-7a5a6ff4-86b7-446d-8b45-96d6b5e6b51d.png)

**Comment by thadguidry** [comment]
Thanks for reporting this bug.

Right, I suspect that your Java 16 is still somewhere on your PATH.
Right now it seems we have an small issue with OpenRefine launching and working correctly with Java 16.
Can you update your PATH and JAVA_HOME so that it using a JAVA version lower than 16?
Then OpenRefine should work.

**Comment by thadguidry** [comment]
Also, I've opened a separate issue #4108 for OpenRefine 3.5.1 where I'm seeing that if started with `OpenRefine.exe`, it does not respect JAVA_HOME any longer, but it does if `refine.bat` is used to launch.

**Comment by P3rCo** [comment]
Right,
![image](https://user-images.githubusercontent.com/89087309/129808087-2b3c0a6f-5e2e-4175-97e3-85deaee12366.png)
Java version changed.
My G.
![image](https://user-images.githubusercontent.com/89087309/129808194-c151e604-8874-4b0c-ac16-e63f66500df8.png)
Right, so Java 16 bad, Java 18 ok?

**Comment by thadguidry** [comment]
I don't know yet what is going on with our 3.5.1 release and Java 16.
I myself have not compiled OpenRefine against Java 18 yet... so no idea, but you are [welcome to try](https://jdk.java.net/18/).
16 only reached GA on 2021/03/16
17 is expected on 2021/09/14

**Comment by ylan1** [comment]
@thadguidry
Thank you so much for all your help. After deleting jdk 16 from the PATH and changing JAVA_HOME to C:\Program Files\Java\jdk-14.0.2, I was able to run OR. However, when I tried to run it with openrefine.exe, it did not work, but with .bat, it worked. But I got the following output: 
![bat](https://user-images.githubusercontent.com/77898472/129819430-04b227b5-53dc-48a4-b2e9-e5a7aa56fe51.PNG)
Is this an expected behavior? Anyway, I am so happy that it is working now.

**Comment by thadguidry** [comment]
@ylan1 Expected (for now)

**Comment by ylan1** [comment]
@thadguidry 
I see. Thank you!

**Comment by VladimirAlexiev** [comment]
@thadguidry @wetneb Confirming it doesn't work on Java 16.
Java version:
```
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7)
OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (build 16.0.2+7, mixed mode, sharing)
```
Error in browser console:
```
Uncaught ReferenceError: Refine is not defined
    at (index):68
```

OpenRefine version: 3.5.1beta.
This also happened on an earlier version.

Console messages:
```
>refine.bat
Using refine.ini for configuration
Getting Java Version...
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7)
OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (build 16.0.2+7, mixed mode, sharing)
=====================================================
find: ‘version’: No such file or directory
Getting Free Ram...
log4j:WARN No appenders could be found for logger (org.eclipse.jetty.util.log).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/prog/openrefine/webapp/WEB-INF/lib/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/prog/openrefine/server/target/lib/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
15:02:08.171 [                   refine] Starting OpenRefine 3.5-beta1 [1b9907e]... (0ms)
15:02:08.178 [                   refine] initializing FileProjectManager with dir (7ms)
15:02:08.181 [                   refine] C:\Users\vladimir.alexiev.000\AppData\Roaming\OpenRefine (3ms)
```

**Comment by VladimirAlexiev** [comment]
hi @thadguidry what's the ETA on this issue? Should I downgrade Java?

**Comment by thadguidry** [comment]
@VladimirAlexiev Don't use >= Java 16 for now.  No idea on ETA...maybe next Spring? probably.

**Comment by wetneb** [comment]
I agree this should be pretty high priority. Hopefully 3.5 should fix this.

**Comment by itplainedge** [comment]
Same problem. Had installed Minecraft Java which wanted a newer version of JDK which I installed 16.1. I previously only had Java Runtime 1.8.   After I uninstalled JDK 16.1 I got it to work (both versions with java embedded and without since I had JRE 1.8 installed already)

**Comment by wetneb** [comment]
This will first require making Butterfly compatible with Java 16:
https://github.com/OpenRefine/simile-butterfly/pull/32

**Comment by wetneb** [comment]
I've had a look at this and it's a significant chunk of work, which could involve upgrading quite a few libraries. In the process we can introduce all sorts of bugs / incompatibilities which will require extensive testing. So I don't think we should do this for 3.5, otherwise this will delay this release even more.

**Comment by thadguidry** [comment]
Agree, so where do we do the work? In 4.0 branch? Or a 3.6 branch with expectations of 3.6 also including SDC work and other new features? I personally think that 4.0 might be better for all if we focus dev efforts all together into that branch and will make the merge nightmare much more reduced. My thoughts are that 4.0 can be our next target and with the mindset we release maybe 1 year from now with Java 16 compatible, SDC ext builtin, and working PLL and tuning.

**Comment by wetneb** [comment]
I need to do more research to find out what the problem actually is, so yes, 3.6 or 4.0 depending on the scale of the problem.

**Comment by wetneb** [comment]
The blocker for this is Java 16 compatibility of the Rhino Javascript engine. We are waiting for 1.7.14 to be released (https://github.com/mozilla/rhino/issues/966).
There might be other blockers though!

**Comment by carlosame** [comment]
> The blocker for this is Java 16 compatibility of the Rhino Javascript engine.

I see that this project is using the `rhino-runtime` artifact. Unfortunately, that artifact contains packages which are also present in the main Rhino jar, which [according to MVNRepository](https://mvnrepository.com/artifact/org.mozilla/rhino/1.7.13/usages) is carried as a direct dependency by at least 58 open source projects and therefore may end being in your modulepath as a transitive dependency. In that case, you'd be experiencing a "split packages" problem.

If that is the case (just guessing), and until the packaging of the Rhino project is modified (as part of a full modularisation that I have suggested, see https://github.com/mozilla/rhino/issues/1075#issuecomment-950907384), you could switch to the main `rhino` artifact as a workaround.

**Comment by wetneb** [comment]
Thanks for chiming in @carlosame.

I am a bit puzzled, I did not realize OpenRefine depended on rhino directly. Our web framework "butterfly" does rely on it (depending on `rhino`, not `rhino-runtime`), but OpenRefine does not use it directly as far as I know. So ideally we would delete this dependency altogether! Also, `mvn dependency:analyze` agrees with me.

And it seems to run fine without it. Really puzzling.

Anyway, I do not understand modular compilation as well as you, but I do not think modular compilation is the source of the problem here: what is blocking is the "illegal reflexive accesses" that we have been warned about for a long time now. Upgrading Butterfly's dependency to Rhino to the latest release candidate does solve the problem.

**Comment by wetneb** [comment]
I have opened https://github.com/OpenRefine/OpenRefine/issues/4314 and #4315 to fix this spurious dependency.

**Comment by carlosame** [comment]
> Upgrading Butterfly's dependency to Rhino to the latest release candidate does solve the problem.

That's good to know :-)

There is a pending PR with reflective access fixes (related to issues with protected fields and methods) which may be included in the final Rhino 1.7.14.

**Comment by jkjkjkjkjk** [comment]
Seems to be same problem with Java 17 (no surprises)
![Clipboard01](https://user-images.githubusercontent.com/16571133/142760578-128ce259-0b71-45e3-b2bc-b84c75b7abf5.png)
.

**Comment by wetneb** [comment]
@nikhilp3 may I ask why you unpinned this?

**Comment by nikhilp3** [comment]
Sorry @wetneb must've been on accident
