### ISSUE TITLE
OpenRefine 3.5-beta1 is not respecting the JAVA_HOME variable

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#4108]
**Disregard the fact below that OpenJDK 16 will not let OpenRefine work correctly and folks will get a blank logo when starting OpenRefine - I.E. they must use lower then 16 at this current moment**

**This bug report is created while testing for the above issue that I suspected was happening and suddenly found that OpenRefine 3.5.1 is no longer respecting the JAVA_HOME path when launched by OpenRefine.exe, but does respect JAVA_HOME if it is launched by refine.bat**

----

I suspect some weird bug or config changed or perhaps with Launch4j config & packaging is not allowing the OpenRefine.exe to even see JAVA_HOME correctly when a user sets this correctly on their Windows 10 system.

### To Reproduce
Correctly setup my Windows 10 system to have the PATH and JAVA_HOME pointing to OpenJDK 16 installation path.
Proved it's set correctly with the following:

```
Microsoft Windows [Version 10.0.19044.1165]
(c) Microsoft Corporation. All rights reserved.

C:\Users\thadg>java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

C:\Users\thadg>
```

Then launch OpenRefine.exe from the 3.5.1 beta1 folder installation.
Watch OpenRefine startup just fine.
However, OpenRefine 3.5.1 beta1 is instead using JDK 8 and not the correctly set JAVA_HOME which has OpenJDK 16 path configured as seen in VisualVM.

![image](https://user-images.githubusercontent.com/986438/129805402-b9ca504a-afbe-4221-9a6e-073d97b379e7.png)

Scratch my head...

I then start `refine.bat` to see the difference from the OpenRefine.exe launching...
And notice it is now correctly using OpenJDK 16 from my JAVA_HOME as shown in Windows terminal output:
```
Microsoft Windows [Version 10.0.19044.1165]
(c) Microsoft Corporation. All rights reserved.

C:\Users\thadg>E:

E:\>cd E:\Downloads\openrefine-win-3.5-beta1\openrefine-3.5-beta1

E:\Downloads\openrefine-win-3.5-beta1\openrefine-3.5-beta1>refine /m20G
Using refine.ini for configuration
Unknown Refine command called "/m20G", type "refine /?" for proper usage.

E:\Downloads\openrefine-win-3.5-beta1\openrefine-3.5-beta1>refine /m 20G
Using refine.ini for configuration
Getting Java Version...
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
=====================================================
Getting Free Ram...
log4j:WARN No appenders could be found for logger (org.eclipse.jetty.util.log).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/E:/Downloads/openrefine-win-3.5-beta1/openrefine-3.5-beta1/webapp/WEB-INF/lib/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/E:/Downloads/openrefine-win-3.5-beta1/openrefine-3.5-beta1/server/target/lib/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
16:21:00.328 [                   refine] Starting OpenRefine 3.5-beta1 [1b9907e]... (0ms)
16:21:00.329 [                   refine] initializing FileProjectManager with dir (1ms)
16:21:00.329 [                   refine] C:\Users\thadg\AppData\Roaming\OpenRefine (0ms)
```

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: openjdk version "16.0.1" 2021-04-20
 - OpenRefine: 3.5.1 beta1

**Comment by wetneb** [comment]
I don't think we have released 3.5.1 yet, do you mean 3.4.1 or 3.5-beta1?

**Comment by thadguidry** [comment]
@wetneb Sorry, yes, 3.5 beta1

**Comment by thadguidry** [comment]
Hi @wetneb How can a user have the ultimate control in their environment? JAVA_HOME env variable has the long standing tradition of being that and where other applications like IDE's also respect it as priority.

**Comment by thadguidry** [comment]
@wetneb Yes it respects JAVA_HOME variable now! Good job!
Tested with `openrefine-win-3.5-beta1-266-gcf8b140-dirty.zip`
