### ISSUE TITLE
Allow changing the autosave period via refine.sh/bat on command line

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#4113]
I have some large projects that require launching where I really need the autosave period to be closer to 60 minutes.  I use a few Windows shortcuts on my desktop for some common large OpenRefine projects that I sometimes cross with, etc.  The problem is that I cannot easily use the Windows shortcuts to launch these particular large OpenRefine projects because I cannot also save the shortcuts with a command line parameter to control the autosaving.  I can only control autosaving period from the `refine.ini` file.

a custom `refine.ini` path also is not a parameter that can be passed to the refine.sh/bat which probably would be the best solution all around.

### Proposed solution
allow passing a custom `refine.ini` path as a parameter for the `refine.sh/bat` launcher.
We already have in the scripts a "endConfigReading" section that could be re-used and parameterized for consuming a custom `refine.ini` path such as 
```sh
refine /c C:\Users\thadg\bigfile_refine.ini
```

**Comment by tejasrbhat** [comment]
@thadguidry I raised a PR for this. Can you please review it ?
