### ISSUE TITLE
Fetching URLs from Web Services instability

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#413]
_Original author: xco...@gmail.com (June 21, 2011 19:29:21)_

Using extensibly the Fetching URLs from WebServices functionality I have found many problems: incomplete process, aborted operation, etc. 

<b>What steps will reproduce the problem?</b>
1. Use the &quot;Add Column by fetching URLs...&quot; with 2,000 rows.
2. Invoke any Json API using &quot;value&quot; for input, name the New Column and set Throttle Delay to 2000.
3. Wait for the process to complete ...

<b>What is the expected output? What do you see instead?</b>
The more common scenarios are:

1) In the process of invoking the Web Services for +2,000 rows, the progress window suddenly closes, and the new Column isn't even created. All the progress is lost (this indeed a big issue when the invokes are calling a paid service).
2) Sometimes the process is completed, but the new Column doesn't show up, a restart for Refine is needed to be able to display the new Column.
3) Sometimes the column is created, but all the cells are empty.
4) Sometimes the process just hangs up, and you need to Cancel the operation (and lost all the progress)

At least the possibility to keep all the progress (before the crash) is needed, so you don't lost all the rows that have been invoked. (Maybe this will need a two-step approach, firs creating the Column and then invoking the Web Service)

<b>What version of Google Refine are you using?</b>
I have tried with 2.0 and 2.1 RC1

<b>What operating system and browser are you using?</b>
Mac OSX, Chrome

<b>Is this problem specific to the type of browser you're using or it happens</b>
<b>in all the browsers you tried?</b>
I have tried Firefox 4.x and Chrome 11.x, same behavior.

<b>Please provide any additional information below.</b>

Using this feature in 1,500 rows or less work great. I have tried setting the Throttle delay to 2000, the default (5000) or longer, sometimes improves the probability that the process completes, but sometimes even with this values the process doesn't work.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=413_
##

**Comment by wetneb** [comment]
I have used the URL fetching capabilities for more than 2000 rows and have not encountered this problem. It was most likely solved by the fix mentioned above. Should we close this?

**Comment by ultrageek** [comment]
I have seen this problem with both sub- and over-2000 rows, on both Mac and Win 10. Problem is, on Mac OS X as of El Capitan, the fetch no longer works - at least not for me. There's a certificate error hiding behind the problem, but I fixed it in the commandline. Fetch still works in Win 10, but as of today, I'm finding it hanging at 88% for one group of rows. When I took a slightly smaller slice of the same rows, it hangs at 98%. (But note: i have not yet updated Refine; just reporting that I started seeing similar problems as of about 1.5-2 years ago)

**Comment by wetneb** [comment]
@ultrageek it would help if you could provide OpenRefine's logs (the white text in the black window) when you stumble on the issue again - I suspect some exception must show up there.

**Comment by ostephens** [comment]
For certificate/SSL issues on Mac see #1265 - it works through the different levels of problem and solution

If you are using OpenRefine 2.7 it's possible on Windows you are seeing #1219 - which is fixed in 2.8 and can be avoided in 2.7 by unchecking the 'cache' option when fetching URLs. (I'd recommend updating to 2.8 generally)

As @wetneb says - if you can provide further information about any errors displaying in the console that would help with analysis.
