### ISSUE TITLE
Wikimedia Commons categories as 'starting point' for an OpenRefine project

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#4143]
Part of #2144 (Wikimedia Commons support in OpenRefine).

When editing batches of Wikimedia Commons files, regular Commons and GLAM contributors will typically take one or more [Wikimedia Commons categories](https://commons.wikimedia.org/wiki/Commons:Categories) as input or 'starting point' in various tools. Examples include [AC/DC](https://commons.wikimedia.org/wiki/Help:Gadget-ACDC), the [ISA Tool](https://commons.wikimedia.org/wiki/Commons:ISA_Tool), and [VisualFileChange](https://commons.wikimedia.org/wiki/Help:VisualFileChange.js). It would be great if that would be possible in OpenRefine too (rather than asking users to start with a list of file names).

### Alternatives considered

In the earlier [integration scenarios](https://hackmd.io/dqq4TBogSxK95ezsTmOiFg?view), we kind of assumed that users would start off with lists of file names.

However, this does produce some extra hurdles to users (which may be especially difficult and annoying to newcomers). They would have to use other tools in order to get a list of file names on Wikimedia Commons, which complicates the workflow.

Typically, users would resort to
- [PetScan](https://petscan.wmflabs.org/) outputting csv, tsv, plain text or a PagePile ([example query](https://petscan.wmflabs.org/?psid=20057301))
- the [Wikimedia Commons query service](https://wcqs-beta.wmflabs.org/) ([example query](https://is.gd/8lWBFp)) (much less frequently though, as WCQS is not yet very actively used)

These tools are not rocket science, but they're not super intuitive either. It's absolutely possible to help users figure this out through documentation and by providing sample queries that are very easy to modify. That said, it will be a more smooth and seamless and less frustrating experience if OpenRefine itself covers this workflow 😄 

### Additional context

On Wikimedia's Phabricator, we recently [talked about the option to have this functionality as part of the (to be developed) Wikimedia Commons reconciliation service](https://phabricator.wikimedia.org/T290089) - however, this does not fit the existing [reconciliation API specifications](https://reconciliation-api.github.io/specs/latest/). It makes more sense to have this as a functionality in OpenRefine itself.

**Comment by orothad** [comment]
We'll need more thought on this and a mockup to get a sense of what the UX in OpenRefine needs to be like minimally and what the minimum options might be.  For example, ISA allows specifying the subcategory depth:

![image](https://user-images.githubusercontent.com/88521629/132693864-45154255-33da-4f40-8b50-5358f41419df.png)
![image](https://user-images.githubusercontent.com/88521629/132694412-acbf3fd4-3bd4-4940-8899-0433b9435335.png)
![image](https://user-images.githubusercontent.com/88521629/132694461-f91c43e9-cbf1-4493-a6f4-4d8983d2e6f8.png)

**Comment by trnstlntk** [comment]
> We'll need more thought on this and a mockup to get a sense of what the UX in OpenRefine's importer extension needs to be like minimally and what the minimum options might be. For example, ISA allows specifying the subcategory depth:

The ISA Tool indeed does this in a very nice way. 

In most cases, I think users will start from a single category, but it will indeed be convenient if they can indicate multiple categories at once.
It's important that users can specify the subcategory depth. Sometimes files have been actively divided into several levels of subcategories.

[PetScan](https://petscan.wmflabs.org/) offers another, simple, way of specifying a set of categories with varying depth:
![image](https://user-images.githubusercontent.com/9881645/132717810-fa33a2cc-8524-498a-b63b-b0b51af68c90.png)
([link to this example](https://petscan.wmflabs.org/?psid=20057301))

**Comment by wetneb** [comment]
I propose we move this to the repository for the extension, where this should be implemented:
https://github.com/OpenRefine/CommonsExtension

**Comment by trnstlntk** [comment]
Moved to https://github.com/OpenRefine/CommonsExtension/issues/3 🥸
