### ISSUE TITLE
Schema import dialog improvements

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4145]
The "Import schema" dialog from the Wikibase extension has two issues:
* the Cancel button does not have a proper label
* importing the schema should close the dialog (currently one has to click the Cancel button afterwards, which is counter-intuitive since we do not want to cancel the import)

### To Reproduce
1. First, open the dialog
2. See the improper label of the Cancel button and behaviour of the import button

### Expected Behavior
Proper label, dialog closes on import.

### Screenshots
![image](https://user-images.githubusercontent.com/309908/132846764-c4c38a0c-cc6d-4339-90b5-b83215aa8427.png)

### Versions
 - Operating System: Linux
 - Browser Version: Chromium
 - JRE or JDK Version: 14
 - OpenRefine: master

**Comment by RaviAnand111** [comment]
hey @wetneb  I want to contribute, but I don't know how to do and what to do ? I know java and all the tech but can you tell me how to do it. I am still new to open source

**Comment by wetneb** [comment]
Hi @RaviAnand111, thanks for volunteering! We have a high-level overview of the contribution process:
https://docs.openrefine.org/technical-reference/contributing#your-first-code-pull-request
Let me know if anything is unclear there or if you get stuck anywhere.

**Comment by RaviAnand111** [comment]
There are so many things to do,. Just tell me what to do to open this dialog box, I clone the repo, installed jdk and maven. now what ? 
./refine was processing for atleast 5 minutes so I stopped it in middle. What are the next steps

**Comment by wetneb** [comment]
To open this dialog box, you first need to run OpenRefine. You can do this by running `./refine` and not stopping it in the middle.

**Comment by RaviAnand111** [comment]
sure, I will try

**Comment by wetneb** [comment]
Great! Then once you got it running you need to open a project, click the "Wikibase" button in the top right corner, and then click the "Import schema" menu item. Good luck!

**Comment by wetneb** [comment]
Hi @tejasrbhat thanks for looking at this! I think we should really find out why this error is thrown and avoid it in the first place: we should not have to catch it manually :)
@RaviAnand111 I would give the green light to @tejasrbhat to open a PR for this unless you are still working on this? @tejasrbhat let's say that if @RaviAnand111 hasn't replied in the next two days we can assume they have moved on.

**Comment by tejasrbhat** [comment]
Sure @wetneb. Meanwhile I have a doubt

I have debugged and `onDone` in `Refine.postProcess` of import-schema-dialog is calling `SchemaAlignment._discardChanges()`
which is internally calling `this._changesCleared()`

In schema-alignment.js `_changesCleared()` method `_unsavedIndicator and _schemaElmts` are going as undefined.
That's why we are getting the exception.

I don't know when should those be populated in the flow. Need your help on this.

**Comment by wetneb** [comment]
I haven't checked but it looks like this could be happening when trying to import a schema while the schema alignment tab hasn't been opened yet (which would explain why those attributes haven't been defined yet). Perhaps it's just a matter of checking for that in the `_discardChanges` method?

**Comment by RaviAnand111** [comment]
yeah @tejasrbhat you can go ahead and make a PR

**Comment by tejasrbhat** [comment]
@wetneb I added a check and now its getting closed. Raised PR. Please review and let me know if anything is needed.
