### ISSUE TITLE
Cypress build stability on PRs / master branch

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4150]
It seems to me that Cypress tests are much more stable when run from a pull request compared to when run on the master branch. I have the impression that very often, the build succeeds on the pull request, and then when I merge it in master, the build fails.

One notable difference between the two workflows is that in pull requests, we test for Chrome only, and on master we test for both Chrome and Edge. So, it's natural that the master build is more likely to fail.

With those quasi-systematic failures I have learned to disregard failures on the master branch and only pay attention to build statuses on pull requests, which is not ideal. So I would be interested in bringing the CI on the master in line with that for pull requests, so disabling Edge there.

I would be curious to see if it solves the problem or if there are more differences between the two environments that could explain this pattern. Perhaps it's also a bias on my side (when a test fails on a pull request, it's easy to trigger a rebuild by merging master into the branch, which I cannot do on master).

**Comment by wetneb** [comment]
@fgiroud interested in your thoughts on this :)

**Comment by fgiroud** [comment]
Definitively make sense, let's face it, edge tests are not stable enough!
Let me submit a PR to disable edge on merge requests
