### ISSUE TITLE
Proposal to remove reconciliation tests

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#4159]
Reconciliations tests are overall flaky, despite many attempts to fix them using various tips & tricks (long time outs, different methods to check the dom)

Having those unstable tests has introduced an anti-pattern, where OR developers don't trust the CI/CD anymore and we are merging PRs that don't pass the tests.

I propose to first make a PR to first completely remove them from the CI/CD, then we can restore confidence in the test suite for the community

Then, rewrite them from scratch, maybe using something else than the CSV recon server.
And eventually, run them at scale on a dedicated cypress account, we need maybe 20 to 50 successful runs before merging again.

The issue is that they are passing locally, also on CI/CD, they just have a very high flakiness rate.

@wetneb @kushthedude what do you think?

**Comment by wetneb** [comment]
It's not clear to me how we can get rid of something like the CSV recon server. If there are really reliable public reconciliation servers out there (aka not the Wikidata one) then /maybe/ those would be more reliable than a local service, but I doubt it. Anyway, happy to experiment of course :)
