### ISSUE TITLE
Export to SQL contains an invisible character in the name of the "id" column

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4168]
According to [this tweet](https://twitter.com/RhesusNegatif/status/1440319559714496522) ("Absolument épuisée par un caractère invisible qui s'invite dans le nom de la 1e colonne (id) à chaque fois que j'exporte une table SQL dans OpenRefine"), there is an invisible a character in the name of the "id" column, which is present every time the SQL exporter is used.

**Comment by wetneb** [comment]
Marking this as a good first issue although I have not reproduced it myself. The first step to solve this issue would be to check if this can be reproduced.

**Comment by WaltonG** [comment]
Hi @wetneb am learning OpenRefine fuctionalities and codebase. Would like to work on this issue.

**Comment by WaltonG** [comment]
> Marking this as a good first issue although I have not reproduced it myself. The first step to solve this issue would be to check if this can be reproduced.

@wetneb The issue can be reproduced. The exported sql statements do not include the uid field (primary key). On executing the statements in a database, the initial column is empty
![image](https://user-images.githubusercontent.com/52596583/154849252-47fcb873-aa84-4d77-80dd-9324decaf1a7.png)

![image](https://user-images.githubusercontent.com/52596583/154849320-583deb98-5ce8-4884-983d-342331300066.png)

![image](https://user-images.githubusercontent.com/52596583/154849401-ddec3b86-06d5-4d6e-a8ea-c5a0abdcfac6.png)

**Comment by wetneb** [comment]
That does not seem to be the problem described by this person. They complain that in the name of the first column that is exported (which happens to be an identifier in their case) there is an invisible character.
* Either OpenRefine indeed introduces an invisible character in the name of the first column in SQL export, in which case there is indeed a bug to fix
* Or this invisible character was in their data before, in which case the exporter itself is working as expected. One could investigate which importer was used to create the project and whether it would make sense to improve this importer to delete such invisible characters, but from a single tweet it is hard to tell.

**Comment by thadguidry** [comment]
@wetneb So directly, it was reported there was some kind of invisible character either before or after the column label, `id` ?

**Comment by WaltonG** [comment]
Hi @xiao2k Sure you can work on it. Thank you for volunteering

**Comment by thadguidry** [comment]
@wetneb circling back to this issue, so we agreed in #4802 that we need to test more importers than just CSV, to see which importers retain the non-breaking space chars `U+00A0` in a column name and within those importers we should detect and throw a warning dialog to the user and offer to replace the non-breaking space chars in the column names with regular spaces?  How do we offer that?  add a checkbox option on the importers to "clean and trim hidden chars from column names"?

**Comment by wetneb** [comment]
Closing as not reproducible.
