### ISSUE TITLE
Extend operator functionality to arrays

### ISSUE THREAD

**Issue by jquartel** [OpenRefine/OpenRefine#4185]
I sometimes need to compute values from multi-valued cells in order to make new multi-valued cells, so it would be great if some of the operators and math functions could work on arrays. For instance:

1) Scalar distributed to array elements:
 with numbers:  `[1, 2, 3] * 2`  could return  [2, 4, 6] . 
 with strings:  `"b" + ["ay", "oy"]`  could return  ["bay", "boy"]

2) Element-wise operations with arrays of same length:
 with numbers:  `[1, 2, 3] + [2, 1, 0]`  could return  [3, 3, 3]
 with strings:  `["fr", "fl"] + ["og", "ag"]`  could return  ["frog", "flag"]

3) Math functions on arrays of numbers:
   `abs([-1, 3])` could return [1, 3]

**Comment by wetneb** [comment]
Thanks for the suggestion!
I think this is a legitimate ask, but other users could also have legitimate and conflicting expectations about what these expressions should return. For instance, `[1, 2, 3] * 2` could as well evaluate to `[1, 2, 3, 1, 2, 3]` and `[1, 2, 3] + [2, 1, 0]` to `[1, 2, 3, 2, 1, 0]` (as it would in Python).
So I would be careful about extending the language in an ad-hoc way.

**Comment by jquartel** [comment]
Not being a Python programmer, I wasn't aware of that method of array concatenation, but I see your point. Currently, though, GREL doesn't support this either, so I guess it's up to you to determine what most users would prefer/understand. Perhaps you could make new operators for distributed or element-wise array operations, like `.*` (as used in Matlab to disambiguate from a matrix multiply), or just make a separate function for array concatenation (e.g. `cat(array1, array2)`). I don't think either way would be seen as ad-hoc, but my vote would be for the latter (and use the standard operators in the way I described originally).  I need to do this fairly frequently for math operations (I never need to concatenate arrays) and currently I have to split the multivalued array into columns, then apply the formula to each column and then join (or, worse still, port the whole table into a spreadsheet application, do the calculation, and bring it back into OpenRefine). Having a way to do this in one hit (or fewer hits, at least) would be very helpful.

**Comment by wetneb** [comment]
I guess my background feeling about this is that designing a programming or scripting language is a real project, which should come with clear stability guarantees and sort of a principled and unified approach, rather than small patches as we come across use cases. I observe that in the OpenRefine project we do not really have the capacity to do this. So as far as I am concerned I would rather put more energy into bringing better support for widespread languages (Python, R, Lua…) into OpenRefine and encourage people to use these rather than our own half-baked GREL.

That is the reason why I am a bit reluctant to make fundamental changes to how GREL works. That being said I totally think your use case is legitimate and so I would be happy to introduce dedicated functions for it (rather than overloading operators).

**Comment by jquartel** [comment]
Understood, though I think one may as well use the operators if they are there. Personally I think GREL is fantastic and Python isn't particularly well suited for these spreadsheet-like operations which I think are a common requirement for the kinds of data tables people use (this is certainly true for me). I guess I'm just more used to languages like Matlab (or even Excel, ergh) where array/vector/matrix operations are commonplace and the operators are overloaded in a way which feels logical when working with mathematical objects. To use Python for one of these examples, this seems to work
`return [sum(x) for x in zip([1,2,3], [2,1,0])]`
but I think it would be tricky to do anything much more complex (my recent use case required scalar*array1 + array2). I haven't got my head around Clojure but it doesn't look any easier than Python for this. 
In any case, thanks for the consideration!

**Comment by ostephens** [comment]
While I appreciate that it's nice to be able to write concise expressions, the scenarios are all achievable in GREL using `forEach` and `forEachIndex`:

forEach([1, 2, 3],v,v*2) -> [2, 4, 6]
forEach(["ay", "oy"],v,"b"+v) -> ["bay", "boy"]
forEachIndex([1,2,3],i,v,v+[2,1,0][i]) -> [3,3,3]
forEachIndex(["fr", "fl"],i,v,v+["og", "ag"][i]) -> ["frog", "flag"]
forEach([-1,3],v,v.abs()) -> [1,3]

Concatenating two arrays (i.e. the [1, 2, 3] + [2, 1, 0] to [1, 2, 3, 2, 1, 0] example) feels like the odd one out here in that there's no obvious way to do this except to convert both to strings with a join, concatenate the string, then split the resulting string into an array - which is definitely not concise!

I'm not completely arguing against extending operators to work on arrays, but it feels like small gains since the operations are already possible

**Comment by jquartel** [comment]
These are great alternatives, thanks Owen! I had originally looked into using forEach but I had thought there was no way to deal with two or more arrays (i.e. I hadn't spotted the `forEachIndex` control). And I see one could also use the `with` control to simplify the expressions part when you want to refer the same array more than once (e.g. if you wanted to do something like array1 + array2*(array2+1)). I would still say it's somewhat more cumbersome than allowing the math operators to work logically with arrays, but I'm happy to sit back and see if others would like this feature. Incidentally, I don't have any use cases for concatenating arrays - this was just something that Antonin mentioned might be the assumed behaviour when using `+` with two arrays (because apparently Python works this way).

**Comment by thadguidry** [comment]
Although I appreciate the use case, I disagree that we need to overload the operators to support it.  Documenting the overloading will be a nightmare as well and expectations are different for everyone coming from different backgrounds.  `[1,2,3] + 2 can yield [3,4,5] but it doesn't yield an appended form as in [1,2,3,2] nor does it apply a pop-like stacking behavior [2,1,2]`

I'd like to close this feature request please.

**Comment by thadguidry** [comment]
abs() in all other languages that I have used only works on a single number and for good reason...
absolute value of each number in the array returns another array, a number?
absolute value of both numbers first added together, subtracted, multiplied, divided?
this can go on and on.
there's a lot of ambiguity until you actually can read a reference definition of a function.
I'd suggest to write those definitions down that you would like to see supported in GREL.  And a strong case made why a given syntax might support that definition well.
Then the syntax of how we implement those function definitions can more easily surface.
"Devil is in the details" ... so write down the details.
Ex. https://docs.python.org/3/library/functions.html#abs

**Comment by jquartel** [comment]
I guess it comes down to what you're used to (e.g. https://www.mathworks.com/help/matlab/ref/abs.html ). I'm happy to accept that I might be alone in thinking of arrays as mathematical objects, but I do wonder if GREL users are more inclined to think like Python programmers than, say, Excel spreadsheet users (certainly the people I've introduced OpenRefine to come from the latter camp). In Excel, if you had your 'array' as cells A1 and B1 then your 'formula' for my abs example would be `=ABS(A1:B1)` and this works element-wise (and the +-*/ operators work element-wise as well). All this being said, I do think the constructs using `with` and `forEachIndex` are adequate - they were just somewhat less intuitive for me than using operators on the arrays.

**Comment by thadguidry** [comment]
I felt the same way and had assumptions of how people use or think about GREL and data transformations while helping design it in the early stages of it's life... until I gave my first talk at a local meetup for OpenRefine data cleaning and saw the wide variation on users backgrounds, experiences, and use cases. Data scientists, Journalists, etc.
"Embrace our differences"

**Note:**  typically we avoid overloading in GREL and instead create new functions, in that way we avoid lots of ambiguity, make it much easier for testing, and MUCH MUCH easier for documentation. :-)  So I'm not opposed to a new function of `absArray()` if you feel like writing up a reference definition.

**Comment by jquartel** [comment]
Strictly speaking you're already overloading the math functions and operators since (most of them) work with both floats and integers. Just sayin ;)

**Comment by tfmorris** [comment]
> you're already overloading the math functions and operators since (most of them) work with both floats and integers. 

Yes, GREL uses both operator overloading and duck typing pretty liberally. I'm not sure what the basis of assertion to the contrary was.
