### ISSUE TITLE
Improve EvalError output in Expression preview for HTML/XML GREL functions

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#4193]
We could improve the Error: output to a user shown in the expression preview to tell them what the Type() is for a parameter being passed that is not compatible with the parameter type being expected.

### Proposed solution
On our various HTML/XML GREL functions (htmlText(), wholeText(), ownText(), etc.) add the `new Type().call(bindings, args)` to the EvalError and rephrase the error text as needed slightly to be more friendly to users.

Example:

```java
return new EvalError(ControlFunctionRegistry.getFunctionName(this) + "() cannot work with this '"
                        + new Type().call(bindings, args) + "'"
                        + " but instead needs a jsoup DataNode from style, script tags, etc. to work with."
                        + " See https://jsoup.org/apidocs/org/jsoup/nodes/Element.html#data()"
                        + " For arrays, you might select an index or loop over them with forEach()."
                        + " dataNodes() is currently not implemented.");
```

**Comment by nikhilp3** [comment]
I can work on this!
