### ISSUE TITLE
toString() and parseJson() are not compatible with JSON spec

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#4194]
Per JSON Spec...

> A value can be a string in double quotes, or a number, or true or false or null, or an object or an array. These structures can be nested.

But we throw away (or don't handle properly for some reason) any double quotes in a JSON array when we convert `toString()`.

- Double Quotes retained correctly when encapsulated as expected by single quotes
```
'[ "dentsu mcgarrybowen Regents Place 10 Triton Street", "London NW1 3BF", "+44 (0)20 3640 5592", "For new business enquiries please contact our Marketing and New Business Director, Oli Richards", "For everything else please email us", "© 2020 mb - uk", "22 Torrington Place London, WC1E 7HJ 0203 640 5592" ]'.toString()
```
### To Reproduce
Import the below provided Dataset `test.openrefine.tar.gz` project file as a test case.

1. Try to Add a column based on FETCH column with the following GREL expression to convert the parsed out array to a String:

```
forEach(value.parseHtml().select("p"),v,v.htmlText()).toString()
```

2. Notice that in Preview and after clicking OK in the column that double quotes were **not retained** and useful structure that was needed by retaining the quotes is now lost completely.

### Expected Behavior
I would expect this String value representation with Double Quotes retained for JSON structure to be stored in the cell as such:
`[ "dentsu mcgarrybowen Regents Place 10 Triton Street", "London NW1 3BF", "+44 (0)20 3640 5592", "For new business enquiries please contact our Marketing and New Business Director, Oli Richards", "For everything else please email us", "© 2020 mb - uk", "22 Torrington Place London, WC1E 7HJ 0203 640 5592" ]`

### Screenshots
Good JSON array structure I want to keep as a String and push into a cell
![image](https://user-images.githubusercontent.com/986438/135726322-87389aff-ec93-451f-b986-5d9861b8135a.png)

But the type is an `array`

![image](https://user-images.githubusercontent.com/986438/135726341-bc7c6ea2-3b9b-4b4c-ad72-d2d0c57d944c.png)

Shown below we see `toString()` mangles and loses that good structure where by default it should keep it. If necessary perhaps a parameter option added IF we wanted to throw away that structure or manipulate the formatting of the String ( #816 concerns numbers not JSON arrays as strings.)

![image](https://user-images.githubusercontent.com/986438/135726780-ab8f9bae-83fd-486d-ac66-047035cb4383.png)

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox latest
 - JRE or JDK Version: JDK15
 - OpenRefine: OpenRefine 3.5 Beta1

### Datasets

[test.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/7271903/test.openrefine.tar.gz)

### Additional context

Looking at the array possibilities on https://www.json.org/json-en.html

I think our test cases could also probably be expanded and improved for not only `parseJson()` but also `toString()` to include JSON values that are **string in double quotes**, along with **another array**,  and not only **number, true, false, null** as we currently test.

**Comment by wetneb** [comment]
Hi @thadguidry and @Mengfan-Zhu,

I do not think `toString` is meant to be an inverse to `parseJson`. The role of the `toString` function is to provide a representation of the given object as a string, there is nothing relating it to JSON a priory. Sure, in some cases it might coincide, but that is by accident rather than by design.

I think that instead of "fixing" the `toString` function, we should rather:
* introduce a `toJson` function which would be the inverse to `parseJson`
* clear up any confusion in the documentation implying that `toString` should be used as inverse of `parseJson` (I have not checked if the documentation is misleading about that)

Another advantage of introducing a new function is that we are sure not to break any workflows which rely on the current behaviour of this function. Also, it avoids the addition of obscure new parameters to the `toString` function, which would require the user to have a close look at the documentation to understand what they are.

**Comment by thadguidry** [comment]
@wetneb Sure, we can call a new function `toJson`.

**Comment by Mengfan-Zhu** [comment]
@wetneb @thadguidry Thank you for your reply. If I understand correctly, do you want a new function ``toJson`` instead of adding a parameter for ``toString``? The functionality of ``toJson`` is still what @thadguidry describes above, right?

**Comment by wetneb** [comment]
That's right! Adding more comments on your PR.

**Comment by Mengfan-Zhu** [comment]
> That's right! Adding more comments on your PR.

OK. I will do modification and update later

**Comment by wetneb** [comment]
Hmm I just tried updating the documentation for this and realized we already have a `jsonize` function actually… that is unfortunate! So we should just have closed the issue without change.
