### ISSUE TITLE
Java 8 compatibility of the 4.0 branch

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4199]
The current 4.0 branch is not compatible with Java 8.
Either:
- make this compatible with Java 8
- adapt the `./refine` script and `refine.bat` to throw an error when trying to run with Java 8

**Comment by thadguidry** [comment]
Java 8 ? It works fine for me. Do you mean Java 9 or higher?

**Comment by wetneb** [comment]
Since we are dropping Java 8 support in 3.x (#4278), there is no point in supporting it in 4.x either.
