### ISSUE TITLE
Resizing of Expression Box Causes CSS Overlapping

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#421]
_Original author: randy123...@gmail.com (July 19, 2011 19:41:23)_

<b>What steps will reproduce the problem?</b>
1. Open up a text transform on column
2. Resize expression box, so you're not working in a small textbox, I love this feature because working in predefined textbox sizes is so 1985.
3. 3 boxes seem to overlap across outer div, namingly, Preview Tab, the language selection dropdown, and Syntax error box (in grey) &quot;No Syntax error&quot;

<b>What is the expected output? What do you see instead?</b>

The outer div should scale with them or the boxes should be inside of the main div.

What version of Google Refine are you using? 2.1x64 (newest)

What operating system and browser are you using? Firefox - Win7/x64 Ubuntu/x64   

<b>Please provide any additional information below.</b>

Screenshot attached.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=421_

**Comment by kushthedude** [comment]
@wetneb I think this issue has been addressed.

**Comment by antoine2711** [comment]
> @wetneb I think this issue has been addressed.

@kushthedude: 
when I resize the input field, I get this:
![image](https://user-images.githubusercontent.com/12217525/79060922-834c3f80-7c58-11ea-8a73-814d2b4274a8.png)

I think this is what the issue is about.
Now, for me, the real question is: are you going to tackle this with Vue.js?! ;-)

I'm kidding, but I bet you are fierce enough!

Regards, Antoine

**Comment by elebitzero** [comment]
This issue appears to be fixed. I can expand the expression and the dialog adjusts correctly.  I tested this on Brave, Chrome, Firefox, and Edge on Windows 10. This issue should be closed unless there are any objections. Thanks.
