### ISSUE TITLE
Reconciliation UI only shows one of the available default types

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4224]
The reconciliation UI does not always show all the default types announced by reconciliation services.

### To Reproduce
1. First, add the reconciliation service `https://reconciliation.brickschema.org/reconcile`
2. Then, try to reconcile any column

### Current Results

The dialog only shows the `BrickClass` type whereas the manifest of the service offers two other types.

### Expected Behavior
All three default types should be offered.

### Screenshots
![image](https://user-images.githubusercontent.com/309908/137932970-e9ad1396-759f-438a-858f-91174dc73247.png)

### Versions
 - Operating System: Linux
 - Browser Version: Firefox
 - JRE or JDK Version: 11
 - OpenRefine: master

### Additional context
Brought up in the W3C Entity Reconciliation CG.

**Comment by thadguidry** [comment]
@epaulson Is there an expected change in OpenRefine that you think should happen differently, perhaps always using the manifest first for the types? Is that what you are suggesting as a change for the better in OpenRefine in this issue?

**Comment by epaulson** [comment]
Yes. OpenRefine should present as options in the UI the classes that the manifest says are available. 

As an optimization/hint to the user, if OpenRefine wants to send a small sample of values to run as a "preflight" query and use those returned types as some kind of higher sort ranking in the UI, that's great, but not at the expense of making all non-returned  types in that preflight query completely unavailable. I can imagine for services where the list of possible types is very large (such as Wikidata) the manifest will either be empty or very, very large.
