### ISSUE TITLE
simile-vicino: depends on ancient commons-compress library

### ISSUE THREAD

**Issue by apoleon** [OpenRefine/OpenRefine#4228]
Hello,

as part of the effort to package OpenRefine for Debian I discovered that simile-vicino depends on an ancient commons-compress artifact. I couldn't open an issue there, so I hope it makes sense to file a bug report here.

<dependency>
      <groupId>commons-compress</groupId>
      <artifactId>commons-compress</artifactId>
      <version>20050911</version>
</dependency>

The problem is that Debian and other Linux distributions try to ship only one library version to reduce code duplication and possible security vulnerabilities in the distribution. The latest commons-compress version in Debian does not ship the required CBZip2OutputStream class in src/edu/mit/simile/vicino/distances/BZip2Distance.java anymore.
Interestingly at some point in time the Ant project imported the exact same code, so it would be possible to depend on Ant and still be able to compile vicino.

Of course depending on another Java build system makes no sense. I see two solutions. Either we could replace the CBZip2OutputStream class / functionality or import the necessary code into vicino. At the moment I did the latter in Debian. zip file is attched.

[CBZip2OutputStream.zip](https://github.com/OpenRefine/OpenRefine/files/7380766/CBZip2OutputStream.zip)

**Comment by wetneb** [comment]
Hi Markus,
Thanks for the report! As far as I can tell, this distance is not exposed in OpenRefine, so we could as well consider removing it from Vicino altogether.

**Comment by thadguidry** [comment]
I agree with @wetneb that for now we could remove it from Vicino.

**Comment by tfmorris** [comment]
This was an oversight from when I put together the simile-vicino POM in 2020. There's no need for the ancient dependency.

I've put a PR with a fix up in https://github.com/OpenRefine/simile-vicino/pull/5 which will require a bump of OpenRefine's dependency after it's published.

**Comment by tfmorris** [comment]
Reopening until we update the dependency here to pull in the fixed version.

**Comment by tfmorris** [comment]
This was merged after 3.8-beta1 and wasn't backported to the 3.8 branch, so I've removed the 3.8 milestone.
