### ISSUE TITLE
Label for "regular expression" checkbox of text filter not deduplicated

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4243]
The labels of the "regular expression" checkboxes are not properly linked to the corresponding checkbox.

### To Reproduce
1. First, open a project and create two text filters
2. Then, click on the label (not the checkbox) "regular expression" in the second text facet

### Current Results
![bug](https://user-images.githubusercontent.com/309908/138558817-712dbebc-23cf-44aa-a64a-25e35d29b707.gif)

### Expected Behavior
Clicking on the label should tick/untick the right checkbox.

### Versions
 - Operating System: Debian
 - Browser Version: Firefox 78 ESR
 - JRE or JDK Version: 11
 - OpenRefine: 3.5-beta1

**Comment by LENHUTDUY-8120** [comment]
I'm interested to work on this issue!

**Comment by wetneb** [comment]
Hi @LENHUTDUY-8120, be my guest! Thanks for volunteering :)

Let me know if you get stuck at any point.

**Comment by nikhilp3** [comment]
Hey @LENHUTDUY-8120 sorry didn't see you wanted to work on this until after I submitted a PR. You can take a look at my PR tho and let me know if you think that is the correct way to solve this bug.

**Comment by nikhilp3** [comment]
@wetneb do you think this is ready to merge?
