### ISSUE TITLE
Make Wikibase extension compatible with other entity types than Items

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4268]
Wikibase stores data in "entities". There are various types of entities: items, properties, lexemes, mediainfo entities…
Currently, the Wikibase extension is only able to edit items. However, the functionality we have developed in the Wikibase extension could be useful in other entity types as well.

### Proposed solution

Assume that a reconciliation service is returning entities which are not items (for instance, the Commons service, which returns MediaInfo items). We want to be able to edit those via the Wikibase extension in the same way that we can currently edit items.

In this first version of the feature, nothing in the user interface would change. We would simply change the Java backend so that all the classes which are involved in the Wikidata editing no longer refer to:
* `ItemIdValue` (for the Wikibase item id): that would be replaced by `EntityIdValue`
* `ItemDocument` (for the content of the Wikibase item): that would be replaced by `TermedStatementDocument`.

Once that change is made, it should be possible to edit MediaInfo entities in the same way that items can currently be edited. If one develops a reconciliation service for Wikibase propreties, those could be edited too.

However, in this state it will **not yet** be possible to add statements with reconciled items from Wikidata as values. For instance, the following workflow will not be possible yet:
* Reconcile files to MediaInfo entities
* Extract metadata from the wikitext (via data extension)
* Reconcile some of the extracted metadata to Wikidata
* Add this metadata back to Commons by adding the reconciled information in a Commons schema (for instance, depicts statements)

But it will be possible to add statements whose datatype does not require reconciliation (for instance, geographical coordinates)

### Additional context
Part of the Commons integration project. First step of #2144.

**Comment by wetneb** [comment]
This issue could be broken down into multiple refactoring steps:
* [ ] change the `org.openrefine.wikidata.updates.ItemUpdate` class so that the `qid` is an `EntityIdValue` instead of `ItemIdValue`. And then propagate this change throughout the code base, by following compilation errors. Rename this `ItemUpdate` to `EntityUpdate` class (or `TermedStatementEntityUpdate` to emphasize that it is still specific to entities which have terms and statemens, maybe?). This is already a big task, since it will have repercussions in a lot of areas of the code.
* [ ] change the `org.openrefine.wikidata.schema.WbItemDocumentExpr` class so that the `subject` field has type `WbExpression<? extends EntityIdValue>` instead of `WbExpression<? extends ItemIdValue>`
* [ ] create a `WbEntityVariable` class along the lines of our existing `WbItemVariable` which evaluates to an `EntityIdValue` instead of an `ItemIdValue`. It should do so by picking the right entity type based on the format of the id. This will require the introduction of some new classes `ReconPropertyIdValue`, `ReconMediaInfoIdValue` (and others if we feel like it) following our existing `ReconItemIdValue`.
* [ ] adapt the UI (javascript code) so that the schema editor creates the serialization of a `WbEntityVariable` rather than that of a `WbItemVariable` for the subject entity id of `EntityUpdates`
* [ ] testing time! Try adding some statements to some MediaInfo entities (with a non-entity datatype, for instance quantity or string)

Of course we might encounter unexpected things that need adapting along the way.

**Comment by trnstlntk** [comment]
Also see #3210.

**Comment by wetneb** [comment]
Thanks! >_<

**Comment by wetneb** [comment]
Tada! @j-sal already ticked the first box in the list above! I just reopened the issue because there are other boxes to tick.

**Comment by wetneb** [comment]
Incorrectly closed by an unrelated PR, sorry.
