### ISSUE TITLE
Error message unclear when upload to Wikidata fails

### ISSUE THREAD

**Issue by mshd** [OpenRefine/OpenRefine#4273]
When uploading/updating items to Wikidata I sometimes get the error
` [..ting.EditBatchProcessor] MediaWiki error while editing [failed-save]: The save has failed. 
`
I'm not sure why, and this only happens on some days. Would be nice to have a more clear error message.

**Comment by wetneb** [comment]
Those error messages in logs should obviously be exposed in the UI: that's #1782.

But I don't really see how we could improve this error message itself, as it is produced by Wikibase: there is little chances we can improve on it on our side. This could be improved in Wikibase itself instead.

**Comment by wetneb** [comment]
Actually we can improve it because the API does expose a better error message under the hood.
