### ISSUE TITLE
3.5-beta2 - headers bar's appearance is weird.

### ISSUE THREAD

**Issue by hpiedcoq** [OpenRefine/OpenRefine#4274]
Hi,
I recently deployed 3.5-beta2 and the header of the columns has a strange behaviour (css?).

![image](https://ibb.co/yVqF1p9)

<a href="https://ibb.co/yVqF1p9"><img src="https://i.ibb.co/yVqF1p9/Firefox-Screenshot-2021-11-05-T14-19-21-041-Z.png" alt="Firefox-Screenshot-2021-11-05-T14-19-21-041-Z" border="0" /></a>

It doesn't fit the table, which make the selection pretty hard.

(Linux/Firefox)

**Comment by wetneb** [comment]
Hi @hpiedcoq, thanks for the report! It is curious - this should not happen. Have you tried a hard refresh (CTRL-F5)?

If that does not work, may I ask which version of OpenRefine you were using earlier? Also, I am wondering if the VIB-Bits extension you have is actually compatible with this new version. I find it strange that the Wikidata extension does not show up properly, at least. It could be helpful to try running OpenRefine without VIB-Bits (or other extensions you have installed).

To reproduce the bug, it would be helpful to know:
* the screen resolution where this happens
* ideally, a sample project with some instructions about how to get to this state

**Comment by hpiedcoq** [comment]
Hi Antonin!
Previous version was 3.4.1, working fine.
F5 does the trick and fixes the problem.

Sorry for bothering! And thank you for the quick answer.
