### ISSUE TITLE
Reconciling against a Wikibase instance with federated properties (from Wikidata) fails at the point of value entry

### ISSUE THREAD

**Issue by lozanaross** [OpenRefine/OpenRefine#4287]
When connecting OpenRefine to a private Wikibase instance on WBStack which includes federated properties, reconciliation and property selection works fine, but when you need to enter values in the schema, the value entry field does not appear.

### To Reproduce
1. First, connect to this reconciliation endpoint: https://labs.tib.eu/reconcile/lodwgfedereated/ with this manifest: https://labs.tib.eu/reconcile/lodwgfedereated/manifest.json
2. Then, reconcile some items (feel free to add test items, this is a blank test wiki, no real data shall be harmed).
3. Finally, try to build a schema. 

### Current Results
It is not possible to enter values in the statements.

### Expected Behavior
It should be possible to complete schema built just like with other Wiki instances. 

### Screenshots
![grafik](https://user-images.githubusercontent.com/25489750/141111255-e72bbdb9-eb73-4c30-80c9-e5d3bc6ede1a.png)
![grafik](https://user-images.githubusercontent.com/25489750/141111736-67d23f27-f54b-475d-a2d3-08089cb9fa8b.png)

### Versions
 - Operating System:  Windows 10
 - Browser Version: Firefox 91
 - JRE or JDK Version: whatever was packages with the latest release
 - OpenRefine: OpenRefine 3.5

**Comment by wetneb** [comment]
Fascinating! Thanks for trying it out. This is likely to be relevant for the SDC project since Commons also has federated properties. To investigate as part of #4269.

**Comment by wetneb** [comment]
This should be solved now, but we might need more documentation about how to write a manifest using the new format, for the federation scenario to be exposed properly.

**Comment by wetneb** [comment]
This is now supported and requires a new manifest to be written for the Wikibase instance. This is documented here:
https://docs.openrefine.org/next/manual/wikibase/configuration#the-format-of-the-manifest
