### ISSUE TITLE
CSV importer: confusing behaviour of checkboxes

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4299]
In the configuration options for the CSV/TSV importer, two checkboxes are linked as if one of them had to be checked.

This is a bad pattern: if those checkboxes are really meant to be grouped, then they should be radio buttons and be positioned next to each other.

### To Reproduce
1. First, open a CSV/TSV file
2. Then, click on the "Parse next 1 lines as column headers"

### Current Results

![import_options](https://user-images.githubusercontent.com/309908/141753318-2946d3eb-e865-4017-884a-3edd98f479de.gif)

### Expected Behavior

In this case I was actually trying to get both checkboxes to be not checked (so that my project gets created with `Column 1`, `Column 2`… as column headers). I can achieve this by keeping the `Parse next…` checkbox on and setting the number of lines to 0 but that is a bit counter-intuitive.

### Versions
 - Operating System: Debian
 - Browser Version: Firefox
 - JRE or JDK Version: 11
 - OpenRefine: master (3.6 SNAPSHOT)

**Comment by rachittiwari8562** [comment]
I have tweaked the ui a little bit . Does it look fine?
![Screenshot from 2022-02-13 12-50-17](https://user-images.githubusercontent.com/54476275/153743245-bcdab71e-cafc-4f88-a2fa-bffc7a94dfd0.png)

**Comment by rachittiwari8562** [comment]
I think both of the options should be connected as when the user is trying to enter the column names himself , then the parse next   checkbox should be turned off .

**Comment by wetneb** [comment]
I absolutely love it!

**Comment by thadguidry** [comment]
Maybe the Use character could be moved above the Trim ?

**Comment by rachittiwari8562** [comment]
![Screenshot from 2022-02-13 22-51-04](https://user-images.githubusercontent.com/54476275/153766731-51bdabcf-5566-4ebe-95f8-0eeaa74d1293.png)


Does this fulfil the requirement...?

**Comment by rachittiwari8562** [comment]
In addiion to this I have tried to add some visual seperation between the 3sections . 
![Screenshot from 2022-02-14 19-44-36](https://user-images.githubusercontent.com/54476275/153880720-dc367a81-51ac-41a0-aeaf-5a0534de150a.png)

Should I move forward with this design or revert to back to previous one..

**Comment by thadguidry** [comment]
@rachittiwari8562 The visual separation is optional and we don't have that in the other import loaders so I would remove those vertical section separators here in the CSV importer for now.  Then I think we can merge.  There are many many things that visually I would like to see changed and restyled throughout OpenRefine, but first we need a comprehensive plan and that will likely come after or along with OpenRefine 4.0 in phases.
