### ISSUE TITLE
Cluster values by distance or bins defined by an expression

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4301]
We offer two distances to cluster values together: Levenshtein and PPM. Sometimes, with knowledge of the data I could come up with a better distance, and express it as a GREL function (or another expression language). OpenRefine currently does not allow such user-defined functions.

### Proposed solution

Offer the possibility to use a custom function that takes two arguments (say `a` and `b`) and returns their distance. Then, do clustering based on that distance. For instance, I could use the following function: `1 - len(LCP(s,t)) / avg(len(s), len(t))` (taken from the mailing list, see below).

### Alternatives considered

Currently, users would need to develop their own OpenRefine extension to define such a distance.

### Additional context

Requested on the mailing list: https://groups.google.com/g/openrefine/c/ABxaEFQS8mU/m/DKGkYaFKAgAJ

--------------------------
_This is a [proposed Outreachy project in 2022](https://github.com/OpenRefine/OpenRefine/wiki/GSoC-Outreachy-2022%C2%A0Ideas). If you are **not** planning to apply for an internship via Outreachy/GSoC, we kindly ask that you do not work on this task yet, in order to leave the floor to potential interns._

**Comment by wetneb** [comment]
This could also be considered for our other binning strategy: binning. In this case, the expression would take a single argument (the value being clustered) and return its corresponding bin. Perhaps that is actually easier to start with.

**Comment by thadguidry** [comment]
Note: Our Key Collision method to users is also known as our Binning method.

**Comment by wetneb** [comment]
I have proposed this as a potential Outreachy project (and maybe GSoC if we participate to that as well). This means I think it should be a good topic for a 3 months internship. This is therefore not suitable as a first issue: have a look at [our list of good first issues](https://github.com/OpenRefine/OpenRefine/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) instead.

**Comment by gitonthescene** [comment]
Since clustering is really a [special case](https://github.com/OpenRefine/OpenRefine/issues/2003#issuecomment-792545880) of reconciliation, tools which do this sort of reconciliation can be repurposed to do clustering.

**Comment by ostephens** [comment]
@gitonthescene - can you clarify what you mean when you say

> Since clustering is really a https://github.com/OpenRefine/OpenRefine/issues/2003#issuecomment-792545880 of reconciliation

As I don't really recognise this description of clustering and so it's unclear to me what you intend by "tools which do this sort of reconciliation" and how that would apply to this issue.

Thank you

**Comment by gitonthescene** [comment]
As I mentioned in the linked issue if you extract the unique items from a column and put them in a table, then reconciling against that table will return which items are “closest” to each value.  The interface to reconciling is different than reconciliation but the mechanism is largely the same.  If there was a spec for clustering like there is for reconciliation, people writing reconciliation servers could probably support clustering as well.

**Comment by ostephens** [comment]
Thanks @gitonthescene. I'm not sure I agree with this way of framing clustering although I can see that algorithms used to find clusters could also potentially be used to find reconciliation candidates.

In terms of this issue (allow the user to define a custom Nearest Neighbour or Binning function) I'd been keen on keeping the focus on this as a specific outcome rather than repositioning Clustering as part of Reconciliation (or vice versa). It might be useful to carry on discussion about how clustering relates to reconciliation either in another issue or on the dev mailing list? As it stands this issue looks quite tightly scoped and I'm concerned that we don't lose that in the discussion.

**Comment by gitonthescene** [comment]
Fair enough.  I’m from the school that believes fewer moving parts makes software more reliable and easier to maintain, but I’m not running this project.

**Comment by antoine2711** [comment]
> Fair enough. I’m from the school that believes fewer moving parts makes software more reliable and easier to maintain, but I’m not running this project.

@gitonthescene : It's not about « having more parts » (or not), it's about the fact you are OT (Off-Topic) in this issue. You could start a new one on « creating a Clustering spec » and it wouldn't be a problem to discuss it. Just not here on a related, but different and specific issue.

Regards, Antoine

**Comment by gitonthescene** [comment]
FWIW, your reply was simply not necessary.  I’ll leave you to do whatever you please.

**Comment by antoine2711** [comment]
> FWIW, your reply was simply not necessary. I’ll leave you to do whatever you please.

I'm sorry if that what you get from my comment. I think your idea and concept are interesting. That why I wanted to make sure you knew it was worth another new issue on that subject. It was meant to be positive.

Regards, Antoine

**Comment by gitonthescene** [comment]
If there was any interest, it didn’t come across.  In any event, I’ve linked issues I thought were related.  None of them got much attention.  Should interest pick up it should be easy to track down.

**Comment by tfmorris** [comment]
> Note: Our Key Collision method to users is also known as our Binning method. 

We should really clean up the documentation/UI and try to be more consistent about the terminology. It's a confusing enough topic without introducing extra confusion. The documentation uses "binning" for both 1) key collision & 2) edit distance less than threshold. Also, threshold distance is called "radius" in the UI for some reason.

> This could also be considered for our other binning strategy: binning.

In UI terms, this would be stated as "our other clustering method: key collision"

A third potential area of customization is the blocking algorithm which currently uses character N-grams, where the only thing the user can vary is the length of the N-gram. Depending on the strings involved, this can lead to very "lumpy" buckets where a different algorithm might produce more homogenous bucket sizes.

Lastly (slightly OT), I don't think the current implementation provides very good feedback to the user on what the potential effects will be of changing the various parameters. Providing better feedback would probably both help users work better with the current algorithms as well as guide them in the creation of custom algorithms.

**Comment by tfmorris** [comment]
What remains to be done to close this?

**Comment by wetneb** [comment]
Nothing indeed!

**Comment by tfmorris** [comment]
Just to recap and link everything together, this issue was selected as a Google Summer of Code (GSoC) 2024 project. Related issues created as part of this include #6613 & #6698 . The functionality was implemented in PRs #6612, #6705, #6738, #6755, and #6793.
