### ISSUE TITLE
Reconcile Wikidata by Qualifier

### ISSUE THREAD

**Issue by mshd** [OpenRefine/OpenRefine#4318]
I would like to reconcile Wikidata with a certain qualifier. Is it that possible, if not, could you implement it?

### Exampl
![Screenshot from 2021-11-23 14-47-56](https://user-images.githubusercontent.com/17379661/143035892-0615aecc-cfab-42dc-ba9b-a9cc9afac358.png)
Set qualifier property to North Sumatera III. or give me all people which ever had a candidacy at this district.

**Comment by wetneb** [comment]
Hello @mshd, that is a totally valid feature request! But this feature would be implemented in the reconciliation service, not OpenRefine itself, so the correct repository for this is here: https://github.com/wetneb/openrefine-wikibase/issues/72. I am recording your use case there.

**Comment by mshd** [comment]
Ok appreaciate it!
