### ISSUE TITLE
Lack of descriptive message when adding an incorrect schema manifest

### ISSUE THREAD

**Issue by j-sal** [OpenRefine/OpenRefine#4324]
### To Reproduce
1. First, add access the menu in the top right corner 'Extensions: Wikidata' -> 'Select Wikibase instance' -> 'Add Wikibase'
2. Then, paste/write your manifest containing syntax mistakes (see screenshot)
3. Finally, select 'Add Wikibase' in the bottom right corner of the window

### Current Results

The error "Invalid Wikibase manifest." appears in red letters.

### Expected Behavior

A more descriptive error would help narrow down and fix the mistakes.

### Screenshots

![Issue](https://user-images.githubusercontent.com/26920450/143579457-eaaf9544-ea2e-477e-b5a0-c9399938f315.JPG)

### Versions
 - Operating System: Ubuntu 18.04
 - Browser Version: Chrome 95
 - JRE or JDK Version: jdk 11
 - OpenRefine: 3.6

### Datasets

Extract:
{
  "version": "1.0",
  "mediawiki": {
    "name": "Wikimedia Commons",
    "root": "https://commons.wikimedia.org/wiki",
    "main_page": "https://commons.wikimedia.org/wiki/Main_Page",
    "api": "https://commons.wikimedia.org/w/api.php"
  },
//..
  "wikibase": {
    "site_iri": "https://commons.wikimedia.org/entity",
    "maxlag": 5,
    "properties": {
      "instance_of": "P31",
      "subclass_of": "P279",
    }
}

### Additional context

n/a

**Comment by wetneb** [comment]
Closed by #4341.
