### ISSUE TITLE
Download JRE on the fly during the packaging process

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4333]
We currently rely on the `settings.xml` file for the developer to specify where they have downloaded Mac and Windows JREs, to package them into the `.dmg` and `.zip` packages.

Instead, we could download those JREs on the fly in the packaging process. This is [what Gephi does](https://github.com/gephi/gephi/blob/master/modules/application/pom.xml) (using an `antrun` maven goal).

The advantage would be that the developer does not have to care about this step (simplifying our release process greatly).
That does not solve the fact that the JRE URLs must still be regularly updated to make sure we are bundling a fresh JRE at each release.

**Comment by subhamgcon** [comment]
Hello @wetneb , I am a beginner in Open source and I would like to fix this issue as my first issue. Can you help in getting started with it?

**Comment by wetneb** [comment]
Hi @subhamgcon, I am not really sure this is a suitable task for a beginner. I would rather recommend [our good first issues](https://github.com/OpenRefine/OpenRefine/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).
To get started on any of those, you could follow this guide: https://docs.openrefine.org/technical-reference/contributing#your-first-code-pull-request
