### ISSUE TITLE
Logging during Fetching from URLs should provide better sense of GETs themselves (not status pings)

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#437]
_Original author: thadguidry (August 24, 2011 21:33:09)_

General logging needs to be improved a bit more during Fetches to help folks deduce problems when connections drop, or timeouts occur.

A good default perhaps is to start at a timeout of 1 min on a response ? dunno.

Currently the console shows &quot;status pings&quot; every .5 seconds that do not coincide with expectations for the Throttle delay timing users choose, such as 5000ms or whatever.

(already reported to David via chat, and creating new issue so we don't lose track of this general logging improvement during fetches)

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=437_

**Comment by tfmorris** [comment]
@thadguidry This is very underspecified. Can you flesh out the description of how you'd like to see the status improved (or close this if it's already been improved suffciently)?

I think the biggest problem with the current status reporting is the reliability of it if there's a problem server-side or an issue with client/server communication. If those are fixed, is there anything else that needs to be done?

**Comment by thadguidry** [comment]
It’s improved enough for now. Closing.
