### ISSUE TITLE
In 4.0 with LocalDatamodelRunner, UTF-8 encoding is lost in cells after import

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#4391]
### To Reproduce
1. Import a CSV file with Unicode (such as [Havas-Group-SCRAPE-csv.csv](https://github.com/OpenRefine/OpenRefine/files/7784942/Havas-Group-SCRAPE-csv.csv))
2. Notice preview shows accent characters with UTF-8 encoding detected.
3. Create the project, and notice the encoding is lost and shows U+FFFD � REPLACEMENT CHARACTER in places in the cell values.

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: JDK 17
 - OpenRefine: 4.0 branch

**Comment by wetneb** [comment]
Thanks! In fact, encoding support for the CSV/TSV, the line-based and the fixed-width importers had not been added back since the migration. The commit above (13323f7) should fix it.

**Comment by wetneb** [comment]
@thadguidry I just tried this in 4.0 and it seems to be fixed as far as I can tell. If you agree, can you close this?
