### ISSUE TITLE
Many unneeded dependencies pulled in from odftoolkit

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4397]
We currently pull in a lot of unneeded dependencies from the `odftoolkit` Java library. Thankfully this has happened after 3.5.1, so we have not released anything with those dependencies yet.

See https://github.com/tdf/odftoolkit/issues/142

Additionally, version 0.10.0 of this toolkit depends on `org.json`, which was not the case in `0.9.0`. Therefore we need to roll back to 0.9.0.
https://github.com/tdf/odftoolkit/issues/144

**Comment by thadguidry** [comment]
odfdom bumped in #6258
