### ISSUE TITLE
Problems with special characters in project name

### ISSUE THREAD

**Issue by b2m** [OpenRefine/OpenRefine#4402]
This issue describes problems with special characters in the project name and other fields from `metadata.json`.

### To Reproduce
1. Create a project with special characters in the project name ("Testing äüöß").
2. Close OpenRefine and check `metadata.json` (everything ok!)
3. Reopen OpenRefine and check special characters in the project name ("Testing Ã¤Ã¼Ã¶ÃŸ").
4. Close OpenRefine and check `metadata.json` (not ok!)
5. Reopen OpenRefine and check special characters in the project name ("Testing ÃƒÂ¤ÃƒÂ¼ÃƒÂ¶ÃƒÅ¸")

### Current Results

The special characters are somehow completely wrong and their number doubles with each restart of OpenRefine.

### Expected Behavior

Reading and writing metadata to `metadata.json` preserves special characters.

#### After creating the project (step 1):

![openrefine_special_chars_1](https://user-images.githubusercontent.com/135298/147916474-adc673c8-7f8a-45b5-9b30-7725135b77ae.png)

#### First restart (step 3):

![openrefine_special_chars_2](https://user-images.githubusercontent.com/135298/147916480-0ba3ebf8-f807-4609-bb68-563257f847a8.png)

##### Second restart (step 5):

![openrefine_special_chars_3](https://user-images.githubusercontent.com/135298/147916932-552aca94-6423-49ca-840d-84f279de8060.png)

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox 95
 - JRE: 11.0.13 (using the bundled version "openrefine-win-with-java-3.5.1.zip")
 - OpenRefine: observed in 3.5.0 and 3.5.1

### Additional context

1. The list of garbled up characters grows exponentially which results in realy large `metadata.json` files and OutOfMemory errors.
2. This might be related or even be the same problem as described in #3431.
3. I also observed this problem in `metadata.json` in the fields `.importOptionMetadata` and `.preferences.entries."exporters.templating.template"`.

**Comment by ashwini-m-hub** [comment]
i want work on it

**Comment by wetneb** [comment]
Thanks for volunteering! This might be easier to reproduce on Windows (but it is potentially also doable on Linux).
We have a guide for first contributions here: https://docs.openrefine.org/technical-reference/contributing#your-first-code-pull-request
Let me know how it goes!

**Comment by ashwini-m-hub** [comment]
Sir I'm new to open source
After setting it on local environment 
What is the next step

**Comment by wetneb** [comment]
The steps are outlined in the link I gave you above. If you point me to a more concrete problem with any of these steps I will do my best to help you.

**Comment by elroykanye** [comment]
@ashwini-m-hub are you still working on this?

**Comment by WaltonG** [comment]
Hi @elroykanye, Are you still interested on this ?

**Comment by elroykanye** [comment]
Hi @WaltonG , didn't notice @ashwini-m-hub was unassigned.
I am still interested in this.

**Comment by b2m** [comment]
As I am now receiving more reports from colleagues regarding this issue I am adding some context to enhance the visibility in the search and add some mitigation strategies. Colleagues are reporting that they suddenly receive an `HTTP ERROR 500 java.lang.OutOfMemoryError: Java heap space` immediately after starting OpenRefine.

The natural reaction is to enhance the `max memory heap size` in `openrefine.l4j.ini`, but this is not a long term strategy because the special characters will double each time OpenRefine is opened (exponential growth).

To mitigate the problem you first have to identify affected projects.
For that find out [where your OpenRefine projects are stored](https://docs.openrefine.org/manual/installing#set-where-data-is-stored).

Then identify unusually big `metadata.json` files, where "unusually big" depends on your projects.
If a `metadata.json` has a size that is measured in megabytes (or bigger!) I usually have a look at it.

To find big `metadata.json` files let tools help you to analyze the OpenRefine projects folder.

Some tools that might do the job for your are for Windows: [TreeSize](https://www.jam-software.com/treesize), [WinDirStat](https://windirstat.net/) or alternatives; for Linux: [Disk Usage Analyzer](https://wiki.gnome.org/Apps/DiskUsageAnalyzer), [QDirStat](https://github.com/shundhammer/qdirstat) or alternatives; for Mac: [Disk Inventory X](http://www.derlien.com/), [GrandPerspective](http://grandperspectiv.sourceforge.net/) or alternatives.

You can then isolate the affected projects by removing their id from `workspace.json` and maybe move their folders to a temporary location.

There is a solution to fix the `metadata.json` files using a combination of `find` and `jq` described in the issue [Out of memory errors from large metadata.json files being parsed during OpenRefine Project Open
](https://github.com/OpenRefine/OpenRefine/issues/3431#issuecomment-748682968).

If using command line tools is not your thing you might open the files in a text editor and manually tidy the files up.
In my experience it is easier to copy the "clean" JSON parts into a new file instead of trying to delete megabytes of garbage.

If you are affected by this behavior you might want to switch early to [OpenRefine v3.6-rc](https://github.com/OpenRefine/OpenRefine/releases/tag/3.6-rc1) (or a later release) where this bug is fixed.

**Comment by tfmorris** [comment]
As mentioned above, this was first mentioned in #3431. The problem was introduced by #2657 which was attempting to 
fix #2543 #2544 #2627, but was incomplete, forcing save to UTF-8, but not doing the same for load (and for some reason the test didn't catch it).

I think the problem affects 3.4 & 3.5 on systems which don't use UTF-8 as their default encoding.
