### ISSUE TITLE
down-arrow image path broken on custom installation

### ISSUE THREAD

**Issue by patrickwyler** [OpenRefine/OpenRefine#4407]
I setup a docker image with OpenRefine 3.5.1 and found out that the down-arrow image path is broken. It would be ok if the image would have the same path as the logo.

### To Reproduce
1. Deploy OpenRefine in a Docker container
2. Then, import some dummy data into a project
3. Finally, the down-arrow button is broken

### Screenshots
![screenshot](https://user-images.githubusercontent.com/23375188/148195699-db68962c-1f2c-4725-8791-75ca2e2bafdd.png)

### Versions
 - Operating System: Linux/Docker
 - Browser Version: Latest Chrome
 - JRE or JDK Version: 11
 - OpenRefine: 3.5.1

**Comment by wetneb** [comment]
Hi Patrick,

Thanks! It is interesting that this causes a problem in your context. Although one could argue that this is a problem with your deployment, I do not think it would be a problem to reorganize this if it helps. The main thing to keep in mind is that each module (the `main` one or extensions) should be able to include its own images independently of others. Therefore, requiring that all images used by the frontend come from the same source directory is not feasible.

**Comment by patrickwyler** [comment]
Hi Antonin

Just created a PR, on a local installation http://127.0.0.1:3333/ it's working on both ways. It's just a problem if OpenRefine isn't running in the root context. 

![Screenshot 2022-01-05 at 11 06 11](https://user-images.githubusercontent.com/23375188/148199680-4dd31530-29d7-41e2-9fb5-0736f1b42175.png)

**Comment by wetneb** [comment]
I am considering releasing this as 3.5.2, including a further log4j update.
