### ISSUE TITLE
Question: Is it possible to disable the update notice?

### ISSUE THREAD

**Issue by ToVie** [OpenRefine/OpenRefine#4410]
**Description**: If a new version of OpenRefine is available a message is displayed: "New Version Download OpenRefine v3.5.1 now."

**Question**: Is it possible to disable this message?

**Rationale**: We run OpenRefine in a controlled environment, in which any software needs to be packaged and signed. The user cannot update the software. Therefore it would be nice not to display that message.

**Comment by subhamgcon** [comment]
@wetneb I want to work on this issue but I am a beginner, Can you please help me to get started?

**Comment by wetneb** [comment]
Thanks @subhamgcon! Have you had a look at https://docs.openrefine.org/technical-reference/contributing#your-first-code-pull-request yet?

**Comment by subhamgcon** [comment]
Hey @wetneb I am getting this error on my Mac, How can i resolve it? Please help  #2191

**Comment by wetneb** [comment]
See my reply there: https://github.com/OpenRefine/OpenRefine/issues/2191#issuecomment-1009937760

**Comment by subhamgcon** [comment]
Hello @wetneb I downloaded the OpenRefine version 3.5.1, Sorry to bother you but how can I reproduce this issue? Really sorry to bother you

**Comment by wetneb** [comment]
Assuming you have set up your development environment (https://docs.openrefine.org/technical-reference/build-test-run) you should be able to see the update notice by manually downgrading your version number (for instance to 3.4.1) in `RefineServlet.java` and recompiling. Then, the task consists in introducing a new configuration parameter (for instance in `refine.ini`) which controls whether this update notice is displayed.
