### ISSUE TITLE
Publish a POM for org.openrefine.dependencies.wdtk correctly

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#4429]
If a developer wishes to purge their local Maven repo then currently it fails for OpenRefine project.

### To Reproduce
1. Clone repo
2. `refine build`
3. `mvn dependency:purge-local-repository`

### Current Results
```
[WARNING] The POM for org.openrefine.dependencies.wdtk:wdtk-util:jar:0.12.0-20200615.121842-1 is missing, no dependency information available    
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-compress/1.20/commons-compress-1.20.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-compress/1.20/commons-compress-1.20.pom (18 kB at 703 kB/s)
[WARNING] The POM for org.openrefine.dependencies.wdtk:wdtk-wikibaseapi:jar:0.12.0-20200615.122004-1 is missing, no dependency information available
[WARNING] The POM for org.openrefine.dependencies.wdtk:wdtk-datamodel:jar:0.12.0-20200615.121912-1 is missing, no dependency information available
[WARNING] The POM for org.openrefine.dependencies.wdtk:wdtk-util:jar:0.12.0-20200615.121842-1 is missing, no dependency information available    
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for OpenRefine 3.6-SNAPSHOT:
[INFO]
[INFO] OpenRefine ......................................... FAILURE [ 21.681 s]
[INFO] OpenRefine - main .................................. SKIPPED
[INFO] OpenRefine - server ................................ SKIPPED
[INFO] OpenRefine - extensions ............................ SKIPPED
[INFO] OpenRefine - Jython extension ...................... SKIPPED
[INFO] OpenRefine - Wikidata extension .................... SKIPPED
[INFO] OpenRefine - Database extension .................... SKIPPED
[INFO] OpenRefine - Gdata extension ....................... SKIPPED
[INFO] OpenRefine - PC-axis extension ..................... SKIPPED
[INFO] OpenRefine - Phonetic clustering extension ......... SKIPPED
[INFO] OpenRefine - packaging ............................. SKIPPED
[INFO] OpenRefine Java JMH benchmarks ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  22.174 s
[INFO] Finished at: 2022-01-13T09:08:33-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.2.0:purge-local-repository (default-cli) on project openrefine: Failed to refresh project dependencies for: org.openrefine:wikidata:jar:3.6-SNAPSHOT: required artifacts missing:
[ERROR]   org.openrefine.dependencies.wdtk:wdtk-wikibaseapi:jar:0.12.0-SNAPSHOT
[ERROR]   org.openrefine.dependencies.wdtk:wdtk-datamodel:jar:0.12.0-SNAPSHOT
[ERROR]   org.openrefine.dependencies.wdtk:wdtk-util:jar:0.12.0-SNAPSHOT
[ERROR]
[ERROR] for the artifact:
[ERROR]   org.openrefine:wikidata:jar:3.6-SNAPSHOT
[ERROR]
[ERROR] from the specified remote repositories:
[ERROR]   snapshots (https://oss.sonatype.org/content/repositories/snapshots/, releases=false, snapshots=true),
[ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### Expected Behavior
A clean purge with no errors about missing POM for wdtk

### Versions
 - Operating System: Windows 10
 - Browser Version: na
 - JRE or JDK Version: JDK-15
 - OpenRefine: master branch

### Additional context
Reference; https://maven.apache.org/plugins/maven-dependency-plugin/examples/purging-local-repository.html

**Comment by thadguidry** [comment]
Actually, I don't see that Group as published ... https://search.maven.org/search?q=g:org.openrefine.dependencies
Did we expect a missing `wdtk` suffix in the group name?  Because others do not include it as seen in that maven central link.
And if I just search for one of the artifacts themselves with the `a:` filter ...  https://search.maven.org/search?q=a:wdtk-util
It shows a published Group as `org.wikidata.wdtk` ?

@wetneb whats the future forward plan?

**Comment by wetneb** [comment]
@thadguidry that dependency is only published in the Maven Central Snapshots repository, not the one for official releases.

I suspect it is normal that your mvn struggles to find that version of the dependencies since it must have been overridden by the latest release I pushed there. I think that is how the snapshots repository works: you basically only have the latest version available.

**Comment by wetneb** [comment]
In any case, the best solution is that we ask WDTK to do a proper release before doing an OpenRefine release ourselves. But it is better to do some testing on our side beforehand, so that we have the opportunity to fix any bugs in WDTK before that.

**Comment by thadguidry** [comment]
@wetneb OK understood about the testing.

You'll see the issue also if you do what is suggested on this Stackoverflow thread https://stackoverflow.com/a/58505996

I tried his suggestion and of course got that directory not found error:
`mvn org.apache.maven.plugins:maven-dependency-plugin:3.2.0:purge-local-repository -DmanualInclude=org.openrefine.dependencies`

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.745 s
[INFO] Finished at: 2022-01-13T17:33:17-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.2.0:purge-local-repository (default-cli)
on project openrefine:
 Unable to purge directory: E:\M2_REPO\org\openrefine\dependencies -> [Help 1]
```

Do you want to close this issue, since I can manually just delete the entire `/org/` subfolder in my M2 local repo (as a means of trying to keep our Maven on Windows build/test cycles fully usable for contributors of OpenRefine - Our CI doesn't cover the local experience)
Or is it useful to keep this issue open for you as a maintenance issue still for WDTK?

**Comment by wetneb** [comment]
Yes let's go for the manual option. The problem will disappear when we switch to an officially released version.
