### ISSUE TITLE
Add documentation (and screen snippet) of new "Go to page" feature

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#4452]
We forgot to close an old issue and update the documentation for the new "Go to page / Jump to page" feature kindly done by @antoine2711 

### Current Results
There is no documentation for the new "Go to page - Page number" input box feature in the "Grid" section of docs - https://docs.openrefine.org/manual/running#the-grid

### Expected Behavior
Have a paragraph that describes:
- Changing numbers to go to a page
- Clicking in number input box and then using arrow keys UP/DOWN on keyboard can also advance/reverse page numbers
- Include a small screen snippet of the grid header area or better yet, the entire grid (`div#right-panel` in OpenRefine)

### Versions
 - Operating System: all
 - Browser Version: all
 - JRE or JDK Version: n/a
 - OpenRefine: 3.5+

### Additional context
As designed, discussed, tested in Issue #2638 and PR #2639

**Comment by wetneb** [comment]
It is not really clear to me how much documentation this actually requires - the UI seems fairly intuitive to me, no? I am not opposed to adding one or two sentences about it but I think we should not over-do it either.

**Comment by IMPranshu** [comment]
@thadguidry sir, I would like to contribute to this project. I understand that we are trying to document https://github.com/OpenRefine/OpenRefine/issues/2638 this feature in the documentation.

**Comment by wetneb** [comment]
Thanks for volunteering!

**Comment by IMPranshu** [comment]
I was going through the repo. I think I have to follow https://github.com/OpenRefine/OpenRefine/tree/master/docs these instructions in order to start building the docs. Any advice?

**Comment by IMPranshu** [comment]
@wetneb I have tried to implement the above in #4469. please check.
