### ISSUE TITLE
Update all dialogs to have a consistent design regarding Cancel/OK buttons

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#4457]
### Proposal
Most applications typically have OK button in dialogs in a lower right corner.  This has become nearly an industry norm in application designs.

OpenRefine should have a consistent design of button orders regarding Cancel / OK.

### Needed Design Changes in frontend 
- Change OpenRefine's dialogs to have a consistent design of button ordering regarding Cancel / OK.
- In dialogs, the OK button should appear in lower far right, then any Cancel button to it's left, then any other buttons as necessary.
- Buttons should not be renamed, in order to prevent breaking our UI tests. (However, if necessary, changes can be reviewed and tests updated)
- We still need to review other buttons such as APPLY and later make decisions on those changes; so far now we will not change APPLY button dialogs in this issue, but only Cancel / OK buttons.

### Screenshots 
(dialog after changes)
![Screenshot 2022-01-23 095028](https://user-images.githubusercontent.com/986438/150686809-d2702320-8dcc-411c-ab95-be3fe3664716.png)
("edit this cell" dialog that has APPLY button, so no changes necessary for now)
![image](https://user-images.githubusercontent.com/986438/150686966-816ac4d6-5e4f-40ec-96b5-c5d4c0148d4b.png)

**Comment by wetneb** [comment]
I agree it is worth making sure this is uniform but I would double check first what the other dialogs do (I do not think it is the norm to have "the OK on far left (other buttons in between) and then any Cancel on the far right.")

**Comment by thadguidry** [comment]
@wetneb I checked many; even our cell edit dialog.

**Comment by antoine2711** [comment]
> (I do not think it is the norm to have "the OK on far left (other buttons in between) and then any Cancel on the far right.")

On the Mac, the OK button is always on the far right, and other buttons go on the left from there. 

Also, the Ok, when triggered by RETURN key, is in a different style. 

Regards,
   Antoine

**Comment by wetneb** [comment]
> On the Mac, the OK button is always on the far right, and other buttons go on the left from there.

I feel like this is the sort of de-facto standard everywhere else, and would support normalizing OpenRefine to that.

**Comment by thadguidry** [comment]
I also agree on normalcy of OK button on the right.  Let me update the proposal.

**Comment by wetneb** [comment]
Thanks for updating the issue, @thadguidry! Are you sure about this though?

> the OK button should appear in lower far right (other buttons in between as necessary) and then any Cancel button on the lower far left.

I would rather expect the Cancel button be next to the OK button (to its left, no?)

**Comment by thadguidry** [comment]
@wetneb Ah yes.

**Comment by nicholas-otto** [comment]
Hello, I would love to be assigned to this issue. I am in a class in university that requires several open source contributions as a part of the curriculum and feel that I would be able to apply myself well here.

**Comment by wetneb** [comment]
Thanks for volunteering, the floor is yours!

**Comment by wetneb** [comment]
Closing this in favour of #4564 where a survey of our existing dialogs is done.
