### ISSUE TITLE
Exporting 'Extract operation history' as JSON

### ISSUE THREAD

**Issue by kieranjol** [OpenRefine/OpenRefine#4498]
Currently if I want to export the Extract Operation History list of actions, I manually copy paste the JSON and save as a .json file. Would it be possible to add an Export button with a traditional 'save as' dialog?

**Comment by nicktz1408** [comment]
Hello, I would be interested on working on this!

**Comment by nicktz1408** [comment]
I have pushed some code! What are the next steps?

Thanks! :)

**Comment by kieranjol** [comment]
Oh wow amazing, thank you! Can’t wait to try this out!

**Comment by wetneb** [comment]
If you literally cannot wait then we have snapshot releases for you: https://github.com/OpenRefine/OpenRefine-snapshot-releases/ (not that the Google integration does not work in them yet).
