### ISSUE TITLE
Running OpenRefine on Windows without Java points to Oracle website

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4511]
When running OpenRefine without Java on Windows, users are redirected to https://java.com/en/download/manual.jsp, which proposes to download Java 8. That is a bad idea, since OpenRefine 3.6 will not be compatible with Java 8 anymore (only Java 11+).

We should consider updating this link (if it is possible) and changing it to a user-friendly alternative.

**Comment by thadguidry** [comment]
As well as update our link for setting up JDK in our technical docs:
https://docs.openrefine.org/technical-reference/build-test-run#set-up-jdk

I am absolutely OK to point users to OpenJDK https://openjdk.java.net/
or directly to the latest GA (General-Availability) release of JDK which it links to currently here https://jdk.java.net/17/

JRE is no longer "built" by Oracle for consumers and stopped after Java 8+ and is now subscription only.  So users on Windows can 1. build JRE themselves or 2. use the Reference Implementations already built from the OpenJDK source code and stored at jdk.java.net

**Comment by thadguidry** [comment]
Or better yet... which is what Microsoft is doing...pointing folks to this:  https://adoptopenjdk.net/
They do this in their Azure stack as well as directly in some of their products like VSCode etc.
