### ISSUE TITLE
Fully rename the Wikidata extension into the Wikibase extension

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4525]
The Wikidata extension has been generalized to work with third-party Wikibase instances.
But there are still a couple of places where Wikidata is mentioned but it should really be Wikibase:
* The extension menu (in the top right corner of the project screen)
* The directory `extensions/wikidata` in the repository should be `extensions/wikibase`
* The namespace `org.openrefine.wikidata` should be `org.openrefine.wikibase`
* Probably other places I forgot about

It would be worth doing these changes, ideally when no other open PR touches the Wikidata extension.

**Comment by wetneb** [comment]
There are also a lot of references to Wikidata in the translations of the Wikibase extension, they should also be cleaned up.

**Comment by khadijm** [comment]
hi, I am a newbie, I am interested   to work on this issue in order to get started with the communicating

**Comment by wetneb** [comment]
Thank you for volunteering, please go ahead!

**Comment by elroykanye** [comment]
Hello @wetneb , this issue has not been resolved yet and I actually noticed this and have had confusions when reading it 😄
Anyway, I'd like to help with this if that is alright?

**Comment by wetneb** [comment]
Let's first check if @khadijm is still working on it.

**Comment by elroykanye** [comment]
Alright

**Comment by khadijm** [comment]
thanks @wetneb i still working on it, i will a PR soon

**Comment by khadijm** [comment]
@wetneb  additional detail are needed 

there are 2 directory wikibase and wikidata as you can see in this folder. 
![Screenshot from 2022-03-28 21-00-58](https://user-images.githubusercontent.com/88087734/160477592-a4d053a7-9435-4528-a37a-2e5fd1d312c3.png)

we cannot rename The directory extensions/wikidata to extensions/wikibase because there is already a directory wikibase.

**Comment by khadijm** [comment]
are we to delete the current wikibase directory before renaming wikidata to wikibase ? @wetneb

**Comment by wetneb** [comment]
I am not sure what happened on your side, but in the repository, there is currently only a `wikidata` directory, not a `wikibase` one:
https://github.com/OpenRefine/OpenRefine/tree/master/extensions
Or am I looking at the wrong location?

**Comment by khadijm** [comment]
thanks @wetneb  i see the problem, i am pulling from my  fork https://github.com/khadijm/OpenRefine instead of pull from https://github.com/OpenRefine/OpenRefine

**Comment by antoine2711** [comment]
@khadijm: are you still working on this issue?

Regards, Antoine

**Comment by thadguidry** [comment]
@wetneb thanks for finishing this up!!!
