### ISSUE TITLE
Chevrons not rendered correctly in "undo" notification

### ISSUE THREAD

**Issue by hughlilly** [OpenRefine/OpenRefine#4540]
Chevrons (`«»`) are not rendered correctly in the "undo" notification.

### To Reproduce
1. Run the "Replace smart quotes with ascii" common transform on a text column
2. Observe that the "undo" notification contains replacement characters instead of chevrons

### Current Results
Chevrons appear in the history list OK, but not in the "undo" notification, which times out and disappears.

### Expected Behavior
The chevrons should be accurately rendered in this modal.

### Screenshots
<img width="413" alt="image" src="https://user-images.githubusercontent.com/12046008/154407674-8b5eaf87-7eb7-4c4b-92d6-e1008251f365.png">

<img width="503" alt="image" src="https://user-images.githubusercontent.com/12046008/154406942-68695787-4810-4612-ba2d-8ca28e436ba3.png">

### Versions
 - Operating System: macOS 12.1 (21C52)
 - Browser Version: Safari 15.2 (17612.3.6.1.6)
 - User-agent string: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"
 - JRE or JDK Version: Sorry, I can't get this info immediately; if there is a separate fix for this issue or if my system is not set up correctly please let me know.
```
❯ which java
/usr/bin/java
~ 
❯ java --version
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
```
 - OpenRefine:  3.5.2 [e3efd4e]

### Datasets
I don't believe this is caused by my data but am happy to attach it here if doing so would help fix the bug.

Thanks
Hugh

**Comment by trnstlntk** [comment]
The yellow notification thingy at the top shows encoding errors quite frequently. I also see it a lot while doing manual reconciliation.

Screenshot:
![Screen Shot 2022-03-10 at 20 25 36](https://user-images.githubusercontent.com/9881645/157740274-189b1913-490a-4c88-9987-8928b49a0806.png)

To reproduce: 
* take a list of e.g. person names with many diacritics 
* reconcile in such a way that you'll have quite a few entries to match by hand
* do that
* see the encoding issues

Here's a small dataset with many person names with diacritics for testing: [documenta-13-artists.csv](https://github.com/OpenRefine/OpenRefine/files/8226776/documenta-13-artists.csv)

**Comment by thadguidry** [comment]
Hi @trnstlntk is it only the notification banner, or do you see that [unicode replacement char U+FFFD �](https://en.wikipedia.org/wiki/Specials_(Unicode_block)) in other display dialogs or areas of OpenRefine?

**Comment by trnstlntk** [comment]
I remember only seeing it in the yellow notification banner, but I'll keep my eyes peeled for other occurrences.
