### ISSUE TITLE
Invalid URL detection in cell UI

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4546]
Sometimes the cell UI gets URL boundaries wrong.

### To Reproduce
Create a project and put the following string in a cell:
```
{{Information
|Description    = {{en|1=<br>
:'''Species''' {{Species-inline|vernacular=Wood Duck|binominal=Aix sponsa}}
:'''Recordist''' Jonathon Jongsma
:'''Remarks''' Bird seen. Several widely-spaced and rather strange hoarse 'screams' from a female wood duck sitting about 15m directly above my head in a large cottonwood at the edge of an urban park pond. Recording quality is rather poor because all I had with me was a mobile phone.
:'''Bird seen''' yes
:'''Elevation''' 250 m
:'''Country''' United States}}
|Source         = [http://www.xeno-canto.org/101287
|Author ](http://www.xeno-canto.org/101287|Author)        = Jonathon Jongsma
|Date           = 2012-05-10 07:53
|Permission     = 
|other_versions = 
}}{{Location dec|44.942|-93.259}}
{{Xeno-canto}}

=={{int:license-header}}==
{{cc-by-sa-3.0}}

[[Category:Sound files uploaded by Fæ]]
[[Category:Xeno-canto]]
[[Category:Audio files of Aix sponsa]]
```

### Current Results

![image](https://user-images.githubusercontent.com/309908/154635358-97b4b3c6-1045-4814-ad6d-bd4dcc9cee25.png)

### Expected Behavior

The URL should not continue on the following line.

### Versions
 - Operating System: irrelevant
 - Browser Version: Firefox
 - JRE or JDK Version: irrelevant
 - OpenRefine: master branch

**Comment by WaltonG** [comment]
@wetneb Am voluteering to work on this issue

**Comment by Binita-tech** [comment]
@wetneb , please assign me this issue.

**Comment by Binita-tech** [comment]
@wetneb I created project and I had some confusion - Do I have to put above string in marked(black) one(below Image) to reproduce the issue?
![image](https://user-images.githubusercontent.com/78761614/160887300-ae7b4a3b-b459-42c1-b3eb-33f08c0d16a0.png)

**Comment by wetneb** [comment]
> Do I have to put above string in marked(black) one(below Image) to reproduce the issue?

I cannot parse your sentence, I am not sure what you mean, sorry! The issue involves URLs so to reproduce it you will definitely need to have some URLs in your cell values, and I cannot see any URLs in your screenshot.

**Comment by Binita-tech** [comment]
Thanks @WaltonG 
@wetneb I am able to reproduce the issue
![image](https://user-images.githubusercontent.com/78761614/161250865-2bc60c9c-1221-4b7c-838c-1a86fa239a1b.png)
I saw on the previous PR that you suggest to adapt the regex so that it does not accept newlines anywhere inside the URL.
So, I am planning to use url.replace(/\n/g,''''); to solve this bug, am I going in right direction?

**Comment by wetneb** [comment]
I would try to adapt the regex that detects the URL so that it does not accept newlines directly. It is a complicated regex though!
