### ISSUE TITLE
Edit distance facet should be case-insensitive

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#457]
_Original author: tfmorris (October 03, 2011 00:14:43)_

The edit distance facet in the Reconcile-&gt;Facets-&gt;Best candidates edit distance thinks these two strings have an edit distance of 8:

 &gt;What We Talk About When We Talk About Love
  What we talk about when we talk about love

I think the edit distance should be (at least optionally) 0 instead of 8.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=457_

**Comment by TheTrailblazer09** [comment]
Can I be assigned to this please?

**Comment by TheTrailblazer09** [comment]
I am not able to generate the issue.  Could you please help in selecting the reconciliation service. I tried with multiple services, in most cases it comes null

**Comment by wetneb** [comment]
What comes null?

**Comment by TheTrailblazer09** [comment]
best candidate name's distance : cell.recon.features.nameLevenshtein

**Comment by TheTrailblazer09** [comment]
Facets are shown. I am not able to generate the distance as 8. It is sometimes null or 0 as shown in attached image. It appears I am not selecting the right reconciliation service/url. 
![facet](https://user-images.githubusercontent.com/59418361/164582437-56fa1207-c830-4959-96fc-9ad56d3afd49.png)
l

**Comment by wetneb** [comment]
You can try to use this dataset:
https://opendata.paris.fr/explore/dataset/lieux-de-tournage-a-paris/information/?disjunctive.type_tournage&disjunctive.nom_tournage&disjunctive.nom_realisateur&disjunctive.nom_producteur&disjunctive.ardt_lieu
and reconcile the "Titre" column to Wikidata (it is a list of films).

**Comment by ostephens** [comment]
I think this issue might have already been resolved based on looking at https://github.com/OpenRefine/OpenRefine/blob/235b5957e22c73328e9f84d6fac44a9cb92318f5/main/src/com/google/refine/model/recon/StandardReconConfig.java#L563

It looks to me like the cell text and the best candidate are converted to lowercase before the Levenshtein is calculated.

In the UI I see the same behaviour as @TheTrailblazer09 - there is no difference in the distance whether upper or lower case is used

**Comment by wetneb** [comment]
Thanks for looking into this Owen! Let's close this then.
