### ISSUE TITLE
Search for Match and Reconciliation DIVS get cutoff at bottom on smaller screen resolutions

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#458]
_Original author: thadguidry (October 05, 2011 22:29:45)_

On smaller screen resolutions the divs for &quot;Search for Match&quot; and &quot;Reconcile column&quot; get cutoff at the bottom.

Users have to manually drag the container div up in order to see more.  This is especially cumbersome for the &quot;Search for Match&quot; which uses the Freebase Suggest widget, and &quot;view more&quot; becomes inaccessible for the user.

Tested on Standard Laptop 15&quot; 1280x800 resolution.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=458_

**Comment by thadguidry** [comment]
This has now been verified as fixed tested and using latest `Version 3.5-beta1 [1b9907e]`
Closing.
