### ISSUE TITLE
Today's OpenRefine MacOS snapshot release seems corrupt

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#4580]
Today's (March 1, 2022) OpenRefine [snapshot release](https://github.com/OpenRefine/OpenRefine-snapshot-releases) for MacOS seems corrupt. When opening the application, it produces the following dialog window:

![image](https://user-images.githubusercontent.com/9881645/156208419-c736b9a5-1651-44aa-9c93-b2a9dafe069d.png)

May need investigating? I have used 3 previous snapshot releases which ran without any problem. Perhaps a one-off thing.
I am now running today's Linux snapshot release instead, and that one works fine on my mac.

I'm not sure if previous snapshot releases are archived somewhere, so [here's the actual dmg](https://drive.google.com/file/d/1z56DngoPsCDgRsSNFYlc6rWR7RzwNGF2/view?usp=sharing).

### To Reproduce
1. Download the dmg
2. Copy the application to Applications folder or anywhere you fancy
3. Open the application and notice the error dialog

### Expected Behavior

OpenRefine should run.

### Versions
 - Operating System: Mac OS X 10.13.6
 - OpenRefine: 3.6 snapshot release of March 1, 2022

**Comment by wetneb** [comment]
I downloaded your DMG and I can run it fine on my MacOS VM. I also downloaded a recent snapshot and it opens fine too. I suspect this could depend on your security settings, perhaps this message shows up because we attempted to notarize the DMG but failed to do so? Anyway, I have disabled notarization for the snapshots a few days ago so hopefully that helps?

**Comment by trnstlntk** [comment]
Could it be related to age of Mac hardware and OS usage?

I just tested on my two macs. 

On my 2014 Macbook Air, which can only run OS X 10.13.6, today's snapshot release again refuses to open, with the same error message as mentioned above. Specs of this machine are (let me know if I need to look up more, or other, info):

```
  Model Name:	MacBook Air
  Model Identifier:	MacBookAir6,1
  Processor Name:	Intel Core i5
  Processor Speed:	1,3 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	8 GB
```

On my (also 2014) miniMac, which however does run the current MacOS 12.2.1, the snapshot release indeed launches just fine! 🤷‍♀️

I can imagine that not so many folks are using such old hardware/OS.

**Comment by wetneb** [comment]
This has been solved in the meantime.
