### ISSUE TITLE
“Info.plist” is on a read-only volume and cannot be unlocked

### ISSUE THREAD

**Issue by thais-lobo** [OpenRefine/OpenRefine#4603]
I'm using the OpenRefine latest version on a Mac and couldn't follow the FAQ instructions to increase memory allocation. When I try to edit the “Info.plist” file, the following message appears:

<img width="678" alt="Screenshot 2022-03-09 at 20 06 15" src="https://user-images.githubusercontent.com/84020632/157525236-c4cd94a0-c5ac-4544-a6a4-999c7b119a82.png">

**Comment by wetneb** [comment]
Thanks for reporting this! Did you first move OpenRefine to your Applications folder, before launching it, or are you launching it from the DMG volume directly?

**Comment by thais-lobo** [comment]
No, I haven't. Just done it now and it works! Thank you so much for the tip
:)

**Comment by thadguidry** [comment]
Thanks for the report.

Let's improve our docs there in that case...
https://github.com/OpenRefine/OpenRefine/pull/4604/files

Thad
https://www.linkedin.com/in/thadguidry/
https://calendly.com/thadguidry/
