### ISSUE TITLE
"Only the best rank" in "Add columns from reconciled columns" should not output deprecated values

### ISSUE THREAD

**Issue by VojtechDostal** [OpenRefine/OpenRefine#4607]
In "Add columns from reconciled columns", you can configure settings to get "Only the best rank". At least in some cases, though, this will also output deprecated values, if none other are available. 

From Wikidata: https://www.wikidata.org/wiki/Help:Ranking: **A statement with best rank is a statement with preferred rank, if there is none: a statement with normal rank.**

### To Reproduce
1. Add table with [Q58633433](https://www.wikidata.org/wiki/Q58633433) in the first column and reconcile it to Wikidata.
2. Add columns from reconciled columns with P691 
3. OpenRefine will output a value for Q58633433 even though this value is deprecated.

<img width="509" alt="Bez názvu" src="https://user-images.githubusercontent.com/21329813/157621961-4a545146-5f05-449e-81e0-3ae8248e6429.png">

Using OpenRefine 3.5.2.

**Comment by wetneb** [comment]
Thanks for the report! Transferring it to https://github.com/wetneb/openrefine-wikibase/issues/133
