### ISSUE TITLE
Form label style is inconsistent

### ISSUE THREAD

**Issue by elebitzero** [OpenRefine/OpenRefine#4639]
The Wikidata dialogs and the create/import project panels append (:) to the labels which are not consistent with the rest of the application.

In general for web applications, colons are no longer used in modern web design.

> Don’t add a colon (:) at the end of a field label to imply that the label text applies to the field it accompanies. The design of the component already communicates the relationship between the label and the input field.
Reference: https://spectrum.adobe.com/page/field-label/

**Comment by elroykanye** [comment]
Hello @wetneb , I'd like to to work on this

**Comment by elebitzero** [comment]
Hey @elroykanye, I should have mentioned earlier that I have a PR in progress for this issue.

**Comment by elroykanye** [comment]
Oh! It is alright then :)
