### ISSUE TITLE
Patch for /wiki/GettingStarted.wiki

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#464]
_Original author: thadguidry (October 14, 2011 14:43:23)_

add FAQ to GettingStarted page under &quot;Get help&quot; section, since we provide troubleshooting there also.  The menu option for FAQ is a little TOO hidden currently.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=464_
##

**Comment by wetneb** [comment]
Patch does not apply anymore, closing.
