### ISSUE TITLE
Add simple example of Regex usage to description of replace()

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#4640]
We currently have this description for GREL `replace()` function: 
 https://github.com/OpenRefine/OpenRefine/blob/083c7feba3b84d97ec884f3c2b38b6f1f0249640/main/src/com/google/refine/expr/functions/strings/Replace.java#L68

We should probably extend that last sentence to also say the Regex pattern should start and end with `/` or just include a simple example showing the Regex pattern usage , perhaps something simple like:

`value.replace(/\n/, " ")`
`value.replace(/\\n\\n/," ")`

and improve [our official reference docs](https://github.com/OpenRefine/OpenRefine/blob/master/docs/docs/manual/grelfunctions.md) for `replace()` as well regarding that.

**Comment by elroykanye** [comment]
Hello @thadguidry , I would like to work on this

**Comment by Redeem-Grimm-Satoshi** [comment]
........
