### ISSUE TITLE
Invalid URL for downloading Maven while first building the project

### ISSUE THREAD

**Issue by SIXIN-LI** [OpenRefine/OpenRefine#4644]
On Mac, with no Maven installed, **./refine build** command throws an error: 

        tar: Error opening archive: Unrecognized archive format
        Error: Error while expanding apache-maven-3.8.4-bin.tar.gz

I have found the issue is in the mvn_prepare() function in _refine_ script. The following URL no longer has a 3.8.4 folder, as the below screenshot. Instead, it has a 3.8.5 folder now. So changing 3.8.4 to 3.8.5 in the script will work.

` MVN_VERSION="3.8.4" `

`    MVN_URL="https://dlcdn.apache.org/maven/maven-3/${MVN_VERSION}/binaries/apache-maven-${MVN_VERSION}-bin.tar.gz"`

### To Reproduce
1. First, git clone the project repo.
2. Then, follow the build steps like [How to build, test, and run](https://docs.openrefine.org/technical-reference/build-test-run#building-testing-and-running-openrefine-from-intellij-idea)
3. Finally, enter ./refine build command in the terminal.

### Current Results

The project is not built successfully with no maven installed.

### Expected Behavior

The project should be built successfully.

### Screenshots

![Screen Shot 2022-03-28 at 2 03 17 AM](https://user-images.githubusercontent.com/45926850/160364747-31086830-6a55-4376-801a-907342080603.png)

### Versions
 - Operating System:  iOS
 - Browser Version:  Chrome 99
 - JRE or JDK Version:  openjdk version "17.0.2"
 - OpenRefine:  3.5.2 [e3efd4e]

**Comment by wetneb** [comment]
Please do, thank you for reporting and volunteering!
