### ISSUE TITLE
OpenCorporates reconciliation endpoint incompatible with OpenRefine 3.6

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4645]
Since #3731, the OpenCorporates reconciliation endpoint (https://opencorporates.com/reconcile) does not work correctly in OpenRefine.

### To Reproduce
1. First, reconcile some list of companies to OpenCorporates
2. Then, click one of the reconciliation candidates

### Current Results
You land on a 404 page because the slash characters in the URL are incorrectly escaped.

### Expected Behavior
Working URLs.

This could be achieved by:
* keeping the previous behaviour for services which do not declare any protocol version in their manifest (i.e. they are following 0.1)
* adjusting the specs (and OpenRefine's code) to specify in the templates whether escaping is expected or not (https://github.com/reconciliation-api/specs/issues/39)

### Versions
 - OpenRefine: 3.6-SNAPSHOT

**Comment by shriyasankhyan** [comment]
I would like to try to solve this issue as no good first issues are available. Can you please assign me this issue so that at least I can try to solve this?

**Comment by shriyasankhyan** [comment]
If you can guide me towards some first issue, then I would be glad.
