### ISSUE TITLE
Unclear documentation in "Set where data is stored" of installing section

### ISSUE THREAD

**Issue by SIXIN-LI** [OpenRefine/OpenRefine#4656]
**Problem 1**: 
It is confusing where to find the workspace when first reading the user manual.

The reason is as below (screenshots below):

- The first appearance of the term "workspace directory" in section _Back up your data_ doesn't point to the correct section #**set-where-data-is-stored**, which now points to #where-is-data-stored. 

-  But **Set where data is stored** section's instruction is not clear enough.

- The clearest guidance to find the workspace is under section **Find the right place to install**

**Problem 2**: the default location of program files cannot be reached. As there is a space in the path, copying and pasting this path in the terminal with cd command gives 

> string not in pwd: Application error.

`~/Library/Application Support/OpenRefine/`

### To Reproduce
1. First, go to [set where data is stored](https://docs.openrefine.org/manual/installing#set-where-data-is-stored)
2. Then, copy path and paste in the terminal.

### Current Results

1. Cannot find workspace directory
2. Cannot locate the program directory using the path.

### Expected Behavior

1. Find program files in the web app.
2. Find program files in the local directory

### Screenshots

![image](https://user-images.githubusercontent.com/45926850/160774993-1fb27831-76ab-4f16-a69d-12f1ced87648.png)

![image](https://user-images.githubusercontent.com/45926850/160775077-a330d3d7-fb68-4596-a6ab-792b53413e5c.png)

![image](https://user-images.githubusercontent.com/45926850/160775134-1171053a-9600-4b67-bf4e-c44b3dcd51df.png)

### Versions
 - Operating System:  iOS
 - Browser Version:  Chrome 99
 - JRE or JDK Version:  openjdk version "17.0.2"
 - OpenRefine:  3.5.2 [e3efd4e]

**Comment by SIXIN-LI** [comment]
I would like to take this issue. My solution is listed below.

As for problem 1, I will write a new instruction based on the current version, and post it here for some review as there may have some wording requirements. 

For problem 2, modifying the path to "~/Library/Application\ Support/OpenRefine/" would work.

**Comment by wetneb** [comment]
Hi @SIXIN-LI, I am not really sure I understand the problem but I assume it will be clearer with your pull request.

**Comment by SIXIN-LI** [comment]
> Hi @SIXIN-LI, I am not really sure I understand the problem but I assume it will be clearer with your pull request.

Thank you for the feedback! I have tried to make the problem clearer and made a pull request for it.
