### ISSUE TITLE
NullPointerException Could Be Thrown When Getting savedConnections

### ISSUE THREAD

**Issue by WaltonG** [OpenRefine/OpenRefine#4693]
In the file DataBaseUtils.java located at /database/src/com/google/refine/extension/database/DatabaseUtils.java "savedConnections" is nullable hence a "NullPointerException" could be thrown in the following scenario

![image](https://user-images.githubusercontent.com/52596583/161567254-264f01f2-7e2e-4719-8877-0b38e249a6a7.png)

1. IOException is thrown at line 98
2. IOException is caught at line 106

![image](https://user-images.githubusercontent.com/52596583/161572771-8b6f5257-addd-4cf5-aad0-2a363e6c29fd.png)

3. getSavedConnections can return null which implies savedConnections can be null in line 232
4. savedConnections is dereferenced  hence could through a NullPointerException line 234

**Comment by wetneb** [comment]
Hi @WaltonG, thanks for this! Instead of code screenshots, feel free to use code blocks in markdown (introduced with `` ```java `` and closed with `` ``` ``).
Also, it would be great to have a more concrete scenario (described from the perspective of a user) to reproduce this issue.

**Comment by WaltonG** [comment]
@wetneb Thanks for the review. Will action on the recommendations

**Comment by sherrif10** [comment]
Hello @WaltonG  am intrested in working on this, do you mind assigning it to me.

**Comment by WaltonG** [comment]
Hi @sherrif10 I will assign you however as per the review a concrete scenario to reproduce the issue is recommended

**Comment by sherrif10** [comment]
Yes thanks will reproduce it first

**Comment by sherrif10** [comment]
Hello @WaltonG , Am trying to reproduce this locally ,Do you mind sharing simple step or scenario am likely to expect.

**Comment by WaltonG** [comment]
Hi @sherrif10 I think that would be a long shot considering that it was raised from a developers perspective and not from actual interactions with OpenRefine

**Comment by wetneb** [comment]
Then we should probably close this as not reproducible.

**Comment by wetneb** [comment]
Let us close then this: feel free to reopen with a concrete scenario from a user perspective in which a NullPointerException happens.
