### ISSUE TITLE
Update the OpenRefine user manual with changes to « Use values as identifiers »

### ISSUE THREAD

**Issue by WaltonG** [OpenRefine/OpenRefine#4702]
When the Use values as identifiers option of Reconcile menu is chosen for a given column, the identifiers will not be reconcilled as expected by the user. Issue #3172 

Changes proposed in PR #4666 will notify the user that identifiers will not be reconciled. This information needs to be added to the user manual in the Reconciliation topic

**Comment by WaltonG** [comment]
@wetneb @antoine2711 I think the label should be changed from enhancement to documentation

**Comment by WaltonG** [comment]
@antoine2711 Can I work on this to facilitate merging of PR #4666

**Comment by wetneb** [comment]
Actually i think the documentation already makes that clear, no?

**Comment by WaltonG** [comment]
> @WaltonG @wetneb I think there's a few small improvements that could be made to that section in the docs. Which I have addressed in #4711

@thadguidry @wetneb The proposed changes in #4711 supersets the proposed changes in this PR.  When #4711 is merged the proposes changes in this PR will be captured

**Comment by wetneb** [comment]
closed by #4711
