### ISSUE TITLE
Project folder should be configurable (so that Refine + Projects can run off of a USB key)

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#471]
_Original author: stefa...@google.com (October 26, 2011 15:29:41)_

Currently Refine stores project data in a OS-specific location but the user is not allowed to reconfigure it. It should be possible instead to allow Refine to store data in a folder relative to where it is installed, thus allowing one to run Refine directly from portable media (such as USB keys) along with its projects.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=471_

**Comment by wetneb** [comment]
I am pretty sure we can define the location of the workspace directory in `refine.ini`, so I am wondering if this can be closed?
Currently we only document command-line options for that: https://docs.openrefine.org/manual/installing#set-where-data-is-stored
But we could improve the documentation to mention the `refine.ini` solution (see https://docs.openrefine.org/manual/running#modifications-set-within-files).

It would be worth checking if this path can be set to a relative one (which would be useful to run OpenRefine off a USB drive).

**Comment by thadguidry** [comment]
### For Windows
Prior to Windows 8 this would have been a small issue, but is no longer with newer versions of Windows where you can get and map a consistent drive letter for USB drives inserted.  Hence, a relative path isn't needed on Windows.  I have tested with a setting in refine.ini of `E:\openrefine_workspace` where OpenRefine is completely installed on `E:\`

**Comment by wetneb** [comment]
> I have tested with a setting in refine.ini of E:\openrefine_workspace where OpenRefine is completely installed on E:\

But is that `E:` letter going to persist if you plug your USB drive in another machine?

**Comment by thadguidry** [comment]
NOPE !  and definitely not when I plug into a Linux or Mac. :-)
So the relative path would be useful, which essentially could make OpenRefine a true portable USB app, which I'm thinking was the OP's original intention.

**Comment by wetneb** [comment]
I just checked and it is indeed possible to use a relative path for the workspace directory, so this can be closed.
