### ISSUE TITLE
If you rename a column after OR has created the Wikidata schema, the column name doesn't change in the schema

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#4723]
If you rename a column after OR has created the Wikidata schema, the column name doesn't change in the schema.

### To Reproduce
1. Build a Wikidata schema
2. Go to the rows, rename a column, go back to the schema. The schema will still have the old column name.
3. Try to push data to Wikidata

### Current Results
A boring generic error message when you try to push the data.

### Expected Behavior
Update of the column name in the schema.

### Screenshots
![image](https://user-images.githubusercontent.com/12217525/162548603-027cb82e-e726-429b-9b70-1649a9d1b1de.png)

### Versions
 - Operating System: N/A
 - OpenRefine: v3.5.x and below.

**Comment by sherrif10** [comment]
This looks good issue

**Comment by sherrif10** [comment]
The easiest way is ti use a very simple csv file otherwise i have used a big csv and its taking much time to reconcile.

**Comment by sherrif10** [comment]
Hello @antoine2711  , i have reproduced this on openRefine 3.4.1 and all is well. could i be reproducing it on different version probably.

**Comment by elroykanye** [comment]
Hello @sherrif10 , still working on this?

**Comment by Jheald** [comment]
still seeing this in Open Refine 3.6.0

You can drag and add the old name of the column to the schema, but that qualifier or whatever is then ignored when previewing the edits

**Comment by wetneb** [comment]
I do not think QuickStatements should work better than direct upload, since both rely on the schema which will not be evaluated at all as long as it relies on non-existent columns. Or did I misunderstand the use case you are refering to?

**Comment by antoine2711** [comment]
> The difficulty is that having renamed a column, there is then not any way to push the data to wikidata -- other than falling back to QuickStatements ?

Well, in the schema, if you replace the old column name with the new column name, it would work and can then be pushed to Wikidata (or Wikibase).

Regards, Antoine
