### ISSUE TITLE
Saving the Wikidata Schema sometimes gives an error message that is imprecise and unhelpful. The problem should be describe instead.

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#4724]
We have non-negligeable problems in the Wikidata Schema’s validation process. A lot a times, even if the schema is good (what's visually in our face), the validation fails with a genereic and very unhelpful error message that can make a normal user grow some impatiance trying to find why it failed.

This is also for the error when saving a schema. Sometime, when there's problems, it just says it can't save the schema.

### Proposed solution
A clue to what might actually be not working not just a simple and obvious « I won't do it ».
I would like to know EXACTLY where the problem is.

- if it's the data, which column (and maybe the index of fautive rows?)
- if it's a schema field, which one? Item # + Term ID or Statement #, Reference # and/or Value # if also applicable.
- I could live with only the next error.

### Alternatives considered
Either search everything till it works, or cry…

### Additional context
[Please note that I did experience that issue a lot and it might have an impact on how I describe this issue.]

### Screenshots
![image](https://user-images.githubusercontent.com/12217525/162548603-027cb82e-e726-429b-9b70-1649a9d1b1de.png)

**Comment by Aizko** [comment]
I have been going through some of these issues lately myself. The screenshot above (default at the start of the schema) is the smallest of them, but gives a clue, with no clear idea of what is going wrong really. More clues as to the error would be appreciated in order to put a remedy.

**Comment by antoine2711** [comment]
> More clues as to the error would be appreciated in order to put a remedy.

@Aizko: I would go as far as to say that to DEBUG this problem, more precise error messages are going to be mandatory. It’s too obscure in the front-end code.

Regards, Antoine

**Comment by Aizko** [comment]
Thanks for the hints, Antoine. This is not my worst issue right now with OpenRefine, the worst being I cannot upload the project despite progress starting, but actually blocked (see the googlegroups conversations). Will remember this conversation if I see vague messages appearing again. See the [googlegroups conversations](https://groups.google.com/g/openrefine/c/oOSg-0MelBQ). Regards

**Comment by WolfgangFahl** [comment]
Personally i think this part of OpenRefine is what makes it a showstopper to be used for mere mortals.
