### ISSUE TITLE
All Lincense Headers should be on top of package not inside package

### ISSUE THREAD

**Issue by sherrif10** [OpenRefine/OpenRefine#4735]
### Feature Request

I am proposing this change in our code base, All linces Headers should come on top of package, this is to fix is really very small but it brings the aspect of clean code. Let me hear from your suggestions.

**Comment by sherrif10** [comment]
Added a quick fix https://github.com/OpenRefine/OpenRefine/pull/4736

**Comment by antoine2711** [comment]
@sherrif10 : it could be interesting, but I'm really not the person to evaluate this. I will pass it on to @wetneb, who can respond to your suggestion.

Regards, Antoine

**Comment by sherrif10** [comment]
Thanks for your reply
