### ISSUE TITLE
The exported file is inconsistent with the original

### ISSUE THREAD

**Issue by Unnamed-1408** [OpenRefine/OpenRefine#4738]
### To Reproduce
1. First, import any ods file(such as A.ods) and create project
2. Then, export this ods project to ODF spreadsheet(A-ods.ods)
3. Finally, import the A-ods.ods, and this ods file is different from the original one

### Current Results

1.  create the project and export to ODF spreadsheet
![image](https://user-images.githubusercontent.com/62083755/162771112-29af2b1d-f394-4a63-8d1e-b29eb445df93.png)
![image](https://user-images.githubusercontent.com/62083755/162771208-2a138b72-33ad-4007-a6e9-6ae3e16a4fa1.png)

2.  import the ods files that exported
![image](https://user-images.githubusercontent.com/62083755/162772549-488983e9-c92b-4564-8dbc-0a9d79bfe2bc.png)

3.  is different with original one
![image](https://user-images.githubusercontent.com/62083755/162772694-a0f83780-7db2-4954-b856-aaac03eac270.png)

### Expected Behavior

same with original file
### Versions
 - Operating System:  Ubuntu 18.04
 - Browser Version: Chromium Version 100.0.4896.75 (Official Build) snap (64-bit)
 - JRE or JDK Version: OpenJDK 11
 - OpenRefine: OpenRefine 3.6

### Datasets

the original files : 
[Sample.ods](https://github.com/OpenRefine/OpenRefine/files/8465447/Sample.ods)
After export : 
[Sample-ods.ods](https://github.com/OpenRefine/OpenRefine/files/8465453/Sample-ods.ods)

### Additional context

The content of the original file seems to be in a different sheet and moved down by 3 lines as a whole

**Comment by Unnamed-1408** [comment]
Hi @wetneb  , I've fixed this bug few days ago, can you give me some suggestions and review this pr, thanks a lot!

**Comment by wetneb** [comment]
Sure, will do as soon as I can, unfortunately the PR backlog is quite big and I have limited time. Thanks for your patience!
