### ISSUE TITLE
Trying to upload a large CSV file with 2M rows

### ISSUE THREAD

**Issue by shubhransh-locale** [OpenRefine/OpenRefine#4744]
We have converted the openrefine code in the linux environment into a custom Docker image using JDK-11 base image. 
We are running using the parameter `-m 8000M ` and also increased refine memory to 8000M for JVM. 
But still when we are uploading a file of size of 1.4GB, when doing `creating project` it get stuck

### To Reproduce
1. Create docker image for openrefine using JDK-11
2. Update parameters as defined
3. Upload large file

### Current Results
File create project is not working

### Expected Behavior
It should work

### Versions
 - Operating System: Kuberneters 
 - JRE or JDK Version: JDK 11
 - OpenRefine: openrefine 3.5.2

**Comment by wetneb** [comment]
Have you tried the 4.0-alpha1 version?

**Comment by shubhransh-locale** [comment]
Till now not. Will try that for sure and update here then

**Comment by wetneb** [comment]
Have a look here: https://github.com/OpenRefine/OpenRefine/releases/tag/4.0-alpha1

**Comment by shubhransh-locale** [comment]
@wetneb , according to you, is the config used correct, or should I update those as well

**Comment by wetneb** [comment]
For the 4.0 version the RAM settings should not matter much, when parsing a CSV.

**Comment by shubhransh-locale** [comment]
Okay, thanks for update

**Comment by shubhransh-locale** [comment]
Hello,
So I used the version you suggested. 
Config used:
8 GB Ram
4 core CPU
It was able to `read` the file, but after that when it need to show the data for doing transformations it is getting stuck.

From top command what I saw was, all my CPU's are running at 100%, do I need to make some changes so that it can work?

**Comment by shubhransh-locale** [comment]
So after it took 6 minutes to show the data, when I started doing operations, it is kind of stuck again (its still processing the data, but taking lot of time).

So according to you, should we reduce the number of rows in file/file size so it can be used in openrefine. 

Right now we have 12.5M rows and 2GB of data

**Comment by shubhransh-locale** [comment]
Another performance update:
I took a smaller file 1.5M rows

To rename a column in V4-alpa took around 2 mins, while in 3.5.2 it took less than 30 seconds. I am assuming, it could be because all the data is in RAM and hence it is fast. Do correct me if I am wrong here

**Comment by wetneb** [comment]
Thanks for the feedback, I hope to find the time to work on those issues soon (when the Outreachy contributing period is over, it should hopefully be a bit more manageable).

**Comment by wetneb** [comment]
Hi @shubhransh-locale, I have optimized the 4.0 architecture quite a bit and I would be interested to know how it feels on your end. Could you try again with those versions:

- Linux:
https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.openrefine&a=packaging&v=4.0-SNAPSHOT&c=linux&p=tar.gz

- Mac OS:
https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.openrefine&a=packaging&v=4.0-SNAPSHOT&c=mac&p=dmg

- Windows (in you already have Java installed): https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.openrefine&a=packaging&v=4.0-SNAPSHOT&c=win&p=zip

- Windows (with Java included): https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.openrefine&a=packaging&v=4.0-SNAPSHOT&c=win-with-java&p=zip

**Comment by wetneb** [comment]
Given that I tested this on my side with much larger datasets and the original poster is not around anymore, I am closing this for now. @shubhransh-locale I am keen to reopen it if there are still problems with this version.
