### ISSUE TITLE
Trying to log out gave "/command/wikidata/login" log in the terminal

### ISSUE THREAD

**Issue by SIXIN-LI** [OpenRefine/OpenRefine#4756]
After clicking "log out" button, I was successfully logged out but the log in the terminal is "POST /command/wikidata/login". This is a minor log problem.

### To Reproduce
1. First, log in your wikidata account.
2. Then, click "wikidata" on the top right, and click "manage wikibase accounts".
3. Finally, click the "logout" button

### Current Results

The terminal logged "POST /command/wikidata/login".

### Expected Behavior

The terminal logged "POST /command/wikidata/logout".

### Versions
 - Operating System:  iOS
 - Browser Version:  Chrome
 - JRE or JDK Version:  OpenJDK 17
 - OpenRefine:   OpenRefine 3.5

**Comment by WaltonG** [comment]
@SIXIN-LI I think console log typos should not be categorised as a bug considering the function of logout was achieved. Cosole

**Comment by SIXIN-LI** [comment]
> @SIXIN-LI I think console log typos should not be categorised as a bug considering the function of logout was achieved.

Thank you! Just removed it.

**Comment by antoine2711** [comment]
> "POST /command/wikidata/login"

@SIXIN-LI: This is actually an API call. If the same call answers multiple functions, then you will see the same API in the log.

Regards, Antoine

**Comment by SIXIN-LI** [comment]
> > "POST /command/wikidata/login"
> 
> @SIXIN-LI: This is actually an API call. If the same call answers multiple functions, then you will see the same API in the log.
> 
> Regards, Antoine

I found the following post request is answering to "POST /command/wikidata/login". I thought this is what is logged. Is this not the case?
![image](https://user-images.githubusercontent.com/45926850/163660732-28fdb073-6eb9-40f0-9d59-fbc222f2acaf.png)

**Comment by antoine2711** [comment]
> I found the following post request is answering to "POST /command/wikidata/login". I thought this is what is logged. Is this not the case?

From what I understand, this can't be it, as this is JS, and its the Java server that writes the log. This is the front-end call to the API, that the Java server handles. Find in the Java code where it answers the API call, you'll be close to the logging code.

Regards, Antoine

**Comment by WaltonG** [comment]
@SIXIN-LI The API call is answred by 
https://github.com/OpenRefine/OpenRefine/blob/d6a3e8465bc05bf90a45f3144c2c53f841bf0845/extensions/wikidata/src/org/openrefine/wikidata/commands/LoginCommand.java#L96-L102

The logout fuctionality is performed by 
https://github.com/OpenRefine/OpenRefine/blob/d6a3e8465bc05bf90a45f3144c2c53f841bf0845/extensions/wikidata/src/org/openrefine/wikidata/commands/ConnectionManager.java#L175-L192

**Comment by SIXIN-LI** [comment]
> @SIXIN-LI: This is actually an API call. If the same call answers multiple functions, then you will see the same API in the log.
@antoine2711 @WaltonG Thank you for the clarification! I finally understand this. Please forgive and forget my dumb question.

**Comment by antoine2711** [comment]
> > I finally understand this. Please forgive and forget my dumb question.

No need to ask for forgiveness, @SIXIN-LI. The important is the end result. With this new knowledge, you will be able to better understand the tool. Though it doesn't seams complex at first, it is!

Thank you for you efforts! And yes, it more rewarding sometimes than others. ;-)

Regards, Antoine
