### ISSUE TITLE
Sort command allows multiple instances to be run

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#476]
_Original author: thadguidry (November 04, 2011 16:05:48)_

<b>What steps will reproduce the problem?</b>
1. On a larger data set, use Sort command, then wait a few seconds and use Sort command again, wait a few seconds and use Sort command again.

<b>What is the expected output? What do you see instead?</b>

Java heap grows with every instance of using the Sort command, even though the previous initial Sort is not finished yet.  The user does not know this, and is not given a progress bar or &quot;Working... panel&quot; to note that Refine is still processing the initial Sort.  I also suspect Refine (via programmatically such as with Paul Makepeace's Python client) will also allow a Sort command to continue to be accepted and run before it has finished with the first one.  Refine should probably return an error of some kind if this happens.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=476_

**Comment by jackyq2015** [comment]
I can take on this task. 

 I will put a busy box at at the front end and put some synchronizer at the SortingRowVisitor class. what do you guys think? or I should submit separate PR?

**Comment by tfmorris** [comment]
Yes, please put any proposed fix on its own feature branch and submit a PR for it.

There are other examples around that you should be able to copy.  One that comes to mind is the "Add column by fetching URL" command.  The LongRunningProcess class might be useful, but it's been a while since I looked at the sorting code.

**Comment by jackyq2015** [comment]
WIll do. 

The dialog.js utility provided dismiss function and it's by level(ie if you dismiss the level 2 and the level 3 will be also dismissed). I will add one function to allow it dismiss specified level so the "Working" dialog can survive after the main dialog is gone. 

For the back end, I will change two methods:
public synchronized FilteredRows getAllRows() 
public synchronized FilteredRecords getAllRecords() 
It will handle all the cases which processing the rows and records to prevent the reentry. Hopeful it's not overkill.

Please suggest.

**Comment by jackyq2015** [comment]
Put a PR #993 (prevent the multiple sorting) for this issue.
