### ISSUE TITLE
Outreachy 2022: The SPARQL Importer plan, Last Week

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#4785]
Fixes #1212

**Hi to you, fellow Outreachy 2022 applicants,**

We now have 7 days left before the closing of the application process for Outreachy 2022 for the SPARQL Importer.

We currently have 6 applicants that have officially registered themselves for this project. It is now time for the last sprint, in order to finalize the choice.

**Evaluation criteria**

- We look at applicants based on the work they submitted through PRs. Here's some general aspect we look at:

   - the quality of the code you wrote
   - your process to understand an issue and how you approach solving it
   - your interaction with the community

Summarizing: we look at the whole process, with an emphasis on the code that is produced at the end. A tool is there to help its users, and as such, the way you bring more power and you make the tool easier to use is taking it into account. 
**The plan for « Project SPARQL Importer »**
[Outreachy: implement-a-sparql-importer](https://www.outreachy.org/outreachy-may-2022-internship-round/communities/openrefine/#implement-a-sparql-importer)

The next phase, and the last one after the « Pull Request » and Issue resolving, is to send plan to explain how you would implement this project. You have one full week (+ 1h!) starting from now, the 20th at 23:00 UTC-4, and we stop receiving plans at 00:00 UTC-4 on the 2022-04-28.

- Antoine Beaubien, @antoine2711, is mentoring this project. Yes, that’s me. ;-)
- I will look at your application based on the general criteria mentioned above. In addition, I also ask for a text document explaining how you anticipate to code the project.
- This document could contain:
   - One or two short paragraphs that describe what users need
     - i.e. they want to write a text SPARQL query and get a project with column already reconciled when opening for the first time
     - i.e. they want to save a query
     - This is to show what you understand of the users needs.
   - A simple bullet list of the features
     - Please number them from F1, F2…
(F for feature)
     - No description or detail. Just a few words to name it.
A simple plan of the steps you are going to take to code
     - Please number them from S1, S2…
(S for Step)
     - i.e.: first, I'll write the input part for the query
then I will transform the JSON and…
then add Fx, etc.
     - Please put the features F1, F2, in these steps.
     - This is not an explanation of the coding. Just the enumeration of the step with a simple title yet informative enough
   - In the rest of the document, please detail all you want, with references to features (Fx, like F1…). You should also be in the steps order (Sx like S1…) but that is not required, as long as you cover all the steps.
     - This part of the document is free form. Use it like you want to show you understand the user's need, the technologies involved, the present code base and how you will merge your stuff in it.

Please use Google Docs. I will exchange with you on a Google Docs document. For the Outreachy project, if they want you to download a file, so you can download a PDF or a Word document, but put a link in that document at the top a link to the Google Docs document. I think they also ask for a timeline. You can put the short version there, and elaborate in the plan.

You can ask me any questions. All the technical questions I will  answer will also be published in a public room on Gitter, [https://gitter.im/OpenRefine/outreachy-sparql-importer](https://gitter.im/OpenRefine/outreachy-sparql-importer). This room will only exist for a few weeks, its purpose is for the SPARQL Importer.

**Communications in the OpenRefine community**
Just a quick reminder about communication in the OpenRefine community
 - If you have a general question on how to use OpenRefine, the Google Group https://groups.google.com/g/openrefine is the place to ask those questions
 - If you have a general question on how to contribute to OpenRefine, or on technologies used in OpenRefine, or that could be used in OpenRefine, then the Google Group https://groups.google.com/g/openrefine-dev is the place to ask those technical questions.
 - If you have a question on an issue, about the user's problems or needs, how he came to this problem, and what could be a long term solution, the GitHub issue is the good place to discuss it. Technological questions can also be discussed on the issue, if it's pertaining to that issue's discussion. 
 - But, if the question is about a current implementation for an issue, it must be discussed on the Pull Request that tries to implement it. 

Most of this should come naturally, but sometimes, we tend to stay where our problem is, when the solution must be searched at another level.

Only a week, 7 days left, till 20220428T00:00-4UTC. Register to your desired project thru Outreachy web site. I look forward to your questions and proposals.

Best Regards,
    Antoine

P.S. All Outreachy applicant for the SPARQL Importer should go to this page: https://www.outreachy.org/outreachy-may-2022-internship-round/communities/openrefine/implement-a-sparql-importer/contributions/

**Comment by WaltonG** [comment]
Hi @antoine2711 Actually the deadline is  April 22, 2022 at 4pm UTC
>We now have 7 days left before the closing of the application process for Outreachy 2022 for the SPARQL Importer.

**Comment by antoine2711** [comment]
> Hi @antoine2711 Actually the deadline is April 22, 2022 at 4pm UTC
> 
> > We now have 7 days left before the closing of the application process for Outreachy 2022 for the SPARQL Importer.

@WaltonG: yes, it's an official dealine for REGISTERING into the SPARQL Importer project, at the Outreachy level. Here, I'm talking about when I will stop receiving first draft of a plan. It's not the same thing.

Official choosen intern will be annonced Mat 4th, if I understand correctly.

Regards,
   Antoine

**Comment by WaltonG** [comment]
> > Hi @antoine2711 Actually the deadline is April 22, 2022 at 4pm UTC
> > > We now have 7 days left before the closing of the application process for Outreachy 2022 for the SPARQL Importer.
> 
> @WaltonG: yes, it's an official dealine for REGISTERING into the SPARQL Importer project, at the Outreachy level. Here, I'm talking about when I will stop receiving first draft of a plan. It's not the same thing.
> 
> Official choosen intern will be annonced May 4th, if I understand correctly.
> 
> Regards, Antoine

Thanks for the clarification

**Comment by khadijm** [comment]
where are we to submit the draft document and the final document. on Outreachy website or  to you @antoine2711

**Comment by antoine2711** [comment]
> where are we to submit the draft document and the final document. on Outreachy website or to you @antoine2711

Outreachy web site. They have a process for that. After it is submitted, then I start to read it and comment it, so you can reply and continue your work. Even if you submit tomorrow, you will be able to improve the document until the end of the week. After that, we make no garanty to take it in consideration, but doors won't be close to improvements, just for first draft sending, and that will be at Outreachy level, so it would be out of our reach.

Regards, Antoine

**Comment by sherrif10** [comment]
> Outreachy web site. They have a process for that. After it is submitted, then I start to read it and comment it, so you can reply and continue your work. Even if you submit tomorrow, you will be able to improve the document until the end of the week. After that, we make no garanty to take it in consideration, but doors won't be close to improvements, just for first draft sending, and that will be at Outreachy level, so it would be out of our reach.

ohh thanks for clarification. It makes sense now.

**Comment by khadijm** [comment]
![Screenshot from 2022-04-21 07-57-28](https://user-images.githubusercontent.com/88087734/164392883-713de59e-1628-4b4f-83d7-afc6843f919b.png)
@antoine2711  there is not option to submit a pdf document on oureachy website.

**Comment by khadijm** [comment]
are we to submit only the google doc links ? or

**Comment by antoine2711** [comment]
> are we to submit only the google doc links ? or

@khadijm: that can be enough, but I really think they ask for a document. Maybe ask on Gitter to other Outreachy. As long as it's recorded by OUtreachy, I'm fine with just a link.

Regards, Antoine

**Comment by niyolynate** [comment]
Data Clustering;
![Uploading SQL Importer.png…]()


![NiyoLynate Clustering](https://user-images.githubusercontent.com/98440370/164718668-ec8e8082-5098-408f-9474-d24d3f60d4ea.png)

**Comment by trnstlntk** [comment]
Thanks, everyone, for your interest in this project, and @antoine2711 for looking at all applications as a mentor for the SPARQL importer!

We will review all applications that have been entered now. You will hear back from us (and Outreachy) in May.

Many greetings, Sandra (Outreachy coordinator for OpenRefine in this round).

**Comment by sherrif10** [comment]
Thanks @trnstlntk
