### ISSUE TITLE
Standardize ordering of Java modifiers

### ISSUE THREAD

**Issue by sherrif10** [OpenRefine/OpenRefine#4808]
This is issue is very low and the main idea is to emphasis clean code. i know we might overlook but its much vital in organisation code of conduct  cc @antoine2711  @wetneb

**Comment by wetneb** [comment]
I would not do such a normalization by hand without enforcing it in our linter in the CI.

**Comment by sherrif10** [comment]
Thanks for quick response. Do you mind helping me enforce it in or linter in the ci. We would definately enforce it.

**Comment by wetneb** [comment]
Sorry I do not have time to work on this and it is not clear to me why we would need this normalization.

**Comment by sherrif10** [comment]
The idea to me is to have a standadized code of conduct. Am thinking in the next 10 years from now if this code is not having a clear code convention, it would not be appropriate. That's my kind of thinking.

**Comment by antoine2711** [comment]
> The idea to me is to have a standadized code of conduct. Am thinking in the next 10 years from now if this code is not having a clear code convention, it would not be appropriate. That's my kind of thinking.

@sherrif10: I think that way you are raising here, are kind of issues that are not simple, nor short term planification. It involves so many variables, and also, which is very costly, a LOT of community discussions. And just that, while we are in the middle of the Outreachy project here at OR, it's an overwhelming tasks. So, if you really care about this kind of issue, I suggest that you come back in a month with it. And prepare yourself for a few weeks of discussions. This is not, unfortunatelty, a trivial task! ;-)

To understand the timing, you have to take in consideration that the quantity of task on Antonin's list are pretty numerous. For a month, he will not have time to discussion this kind of issue.

Regards, Antoine

**Comment by tfmorris** [comment]
The Checkstyle static checker could be used to check/enforce this. https://checkstyle.sourceforge.io/config_modifier.html#ModifierOrder

I'm not sure it's worth the churn in the code base, but if it ever were to be done, it'd be good to combine with as many other normalizations (e.g. import ordering, etc) as can be reasonably bundled together.

**Comment by wetneb** [comment]
I wonder if our existing linter would be able to enforce that too (it is based on Eclipse style files). If that is the case, then all it would require is a change in the configuration file and re-linting: the integration in the CI is already there.

**Comment by wetneb** [comment]
Given that there is not a huge appetite in tackling this specific linting change, I am closing this.
