### ISSUE TITLE
Note for Outreachy 2022 (May cohort) candidates

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#4814]
Hello Outreachy candidates! Thank you so much for your interest in OpenRefine and for your contributions to its codebase so far.

@wetneb and @antoine2711 are this Outreachy edition's mentors for OpenRefine, and I (@trnstlntk) am OpenRefine's Outreachy coordinator for this round.

We will review all applications that have been entered now. You will hear back from us (and Outreachy) in May.

Many greetings!

**Comment by wetneb** [comment]
Let me see if we can keep it pinned while closed.
