### ISSUE TITLE
Better display of which reconciliation service a specific column is reconciled against

### ISSUE THREAD

**Issue by lozanaross** [OpenRefine/OpenRefine#4824]
Currently a default OpenRefine workflow supposes users only reconcile data against a single service, e.g. Wikidata, and then proceed towards schema building and data upload with this single service in mind. However, in reality - with the introduction of the possibility to reconcile against and upload data edits to any arbitrary Wikibase (and soon Wikimedia Commons too, thanks to the work on the Commons extension) - users may wish to work across several services at once. For example enriching (or extending) a dataset from one Wikibase with data from another, in addition to also including data from various other authority control sources (e.g. GND, Getty’s ULAN, VIAF, etc). Currently, however, once a reconciliation operation is carried out — there is no easy visual cue to a user to specify what each column has been reconciled against, leading easily to making mistakes during schema building. 

## Proposed solution
The proposal here is to introduce small logos of the reconciliation service in question right underneath the column name (and column options menu), adjacent to the status bar that indicates if a column has been fully reconciled or not:
![Image](https://user-images.githubusercontent.com/25489750/166152862-50cce6bf-d023-4f07-ad41-f0c4f4136173.png)

In addition these logos could also be integrated in the UI during Schema building, like so: 
![Image](https://user-images.githubusercontent.com/25489750/166152651-ddecd52c-8b48-4d6b-9bf3-cd35eef4f41c.png)

A further complication here is that reconciliation service maintainers will need to include a logo in their manifest in order for the OpenRefine UI to be able to display it then in the two locations identified above. If no logo is provided, the name of the service may need to be spelled out in full - although this solution is not ideal due to potential of having to display long names in small font sizes (see below in Alternatives considered). The latter also won’t be practical in the schema building UI and therein column rendering should remain as it has been until now.

## Alternatives considered
Alternative considerations included a change in color scheme for each service. However this can easily introduce issues with regards to accessibility: if random colors are assigned to each service - making sure there is enough contrast between different colors and between different states (i.e fully reconciled vs partially reconciled) would add additional complexity to the UI. Furthermore, this would be a departure from currently established OpenRefine branded color palette. 

Another solution was to spell out the name of the service in type beneath the green bar indicating state of the reconciliation completion, but this would also be difficult to balance in terms of size of font (so that it's legible) vs length of the title of the service.

## Additional context
This issue concerns a UI enhancement proposed during the design process for the Wikimedia Commons extension (see the wireframes where this solution was first introduced here: https://commons.wikimedia.org/wiki/File:Structured_Data_on_Commons_file_upload_in_OpenRefine_-_wireframes_draft_v2.pdf), however it is not specific to that extension alone, but rather can be useful to the core OpenRefine UI, too.

**Comment by thadguidry** [comment]
@lozanaross @wetneb I'm fine with the logos, but I think the logos additionally should have hover text for the service name coming off the manifest?

**Comment by wetneb** [comment]
Sounds sensible indeed!

**Comment by lozanaross** [comment]
> @lozanaross @wetneb I'm fine with the logos, but I think the logos additionally should have hover text for the service name coming off the manifest?

@thadguidry Great, yes - I agree.

**Comment by wetneb** [comment]
@ayushrai206 here is a test service which advertises a logo:
http://wdreconcile.pintoch.ulminfo.fr/en/api
You should be able to use this to test your work on this issue.
