### ISSUE TITLE
Add [[Category:Uploaded with OpenRefine]] to each file uploaded to Commons with OpenRefine

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#4829]
We already have a nice [OpenRefine tag on Wikimedia Commons](https://commons.wikimedia.org/w/index.php?title=Special:RecentChanges&tagfilter=openrefine-3.6). However, it would also be great to add a tracking category to each file that is uploaded to Wikimedia Commons with OpenRefine. With such a tracking category, we can more easily run metrics to [measure usage / uptake of files in Wikipedia and other Wikimedia projects](https://glamtools.toolforge.org/glamorous.php?mode=category&doit=1&category=Uploaded_with_OpenRefine), and their [page views](https://glamtools.toolforge.org/glamorgan.html?&category=Uploaded_with_OpenRefine&depth=0&year=2022&month=5). 

I have created one for this purpose: [Category:Uploaded with OpenRefine](https://commons.wikimedia.org/wiki/Category:Uploaded_with_OpenRefine) which basically imitates [the one that the Pattypan tool uses](https://commons.wikimedia.org/wiki/Category:Uploaded_with_pattypan).

**Comment by trnstlntk** [comment]
This now works, so I will take the freedom to close this issue (or is there anything that still needs fixing or improving?).

**Comment by wetneb** [comment]
The category name should ideally be configurable in the wikibase manifest, so my intention was to keep this open until then, but after all maybe this is not needed.
