### ISSUE TITLE
Unclosed Statement and ResultSet Resources

### ISSUE THREAD

**Issue by glagou** [OpenRefine/OpenRefine#4839]
After working on issue #4080, we reliazed that Statement and ResultSet resources are not properly closed inside any of the DatabaseService classes. 

A Pull Request has already been made by us for the MariaDBDatabaseService class, but the same issue seems to appear on MySQLDatabaseService, SQLiteDatabaseService, etc.

### Current Results

Statement and ResultSet instances are not handled properly after they are created

### Expected Behavior

Statement and ResultSet resources are closed in a proper way (try-with-resources / finally-block)

### Screenshots

![image](https://user-images.githubusercontent.com/72858319/167708323-a1eabece-54d7-4cb8-9e55-b5eb33d8eb0f.png)
![image](https://user-images.githubusercontent.com/72858319/167708492-c37fed80-84e3-4a7b-92e1-e09d7909c488.png)

**Comment by glagou** [comment]
Hey @wetneb. 

I saw that you left a comment on the Pull Request created by shihlei. If you do not manage to reach her, could you please assign this issue to me?

 I will provide a fix similar to the one I did before at https://github.com/OpenRefine/OpenRefine/commit/bbd7c955975557c2c5b00db44e0fdb2da82f98bf

Thanks in advance! :)

**Comment by wetneb** [comment]
sure!
