### ISSUE TITLE
"Use values as identifiers" doesn't turn column into a reconciled column that can be dropped into a schema

### ISSUE THREAD

**Issue by VDK** [OpenRefine/OpenRefine#4841]
I've got a table with the media identifier of a file on 'Commons, (i.e. M11083877 for [File:Dorpsstraat 30-32, Zoetermeer.jpg](https://commons.wikimedia.org/wiki/File:Dorpsstraat_30-32,_Zoetermeer.jpg) ). When I reconcile this column to in OR with the Commons Reconciliation Service the "use values as identifiers" option then it instantly matches, but I can still not use it when I'm putting together a schema. The item of this column doesn't have a green underline and it can't be dropped as a reconciled column.

### To Reproduce
1. Import a table with media identifiers
2. Column options > Reconcile > "Use values as identifiers"
3. Try to build up a schema, can't drop the column as an item to be edited.

### Current Results
Column that's reconciled with the "Use values as identifiers" option can't be used as a reconciled column.

### Expected Behavior
I can use the column as a reconciled column after reconciliation

### Versions
 - Operating System: Win11
 - Browser Version:  Chrome 101.0.4951.54
 - JRE or JDK Version: java version "1.8.0_331"
Java(TM) SE Runtime Environment (build 1.8.0_331-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.331-b09, mixed mode)
 - OpenRefine: 3.5.2 [e3efd4e]

### Datasets

M10908798 | File:Cadillac Brougham Limousine K6   (1987).jpg |   https://www.flickr.com/photos/38891071@N00/3860807379
M12271274 | File:Coşkun Çörüz (2007) cropped.jpg |   https://www.flickr.com/photos/38891071@N00/437797332
M5032859 | File:GerardJoling.JPG |   https://www.flickr.com/photos/38891071@N00/2726459052

**Comment by antoine2711** [comment]
Have you tried to save your schema, and click the « permalink » link? This could make it work.

Regards, Antoine

**Comment by VDK** [comment]
I figured it out: "select Wikibase instance" needed to be set to Wikimedia Commons. The [Wikimedia Commons reconciliation information page](https://commonsreconcile.toolforge.org/)  should probably link to the [manual on entry on connecting OR to a Wikibase instance](https://docs.openrefine.org/next/manual/wikibase/configuration)
