### ISSUE TITLE
"manifest.version should match pattern "^1\.[0-9]+$"" error for 'Commons manifest version 2.0

### ISSUE THREAD

**Issue by VDK** [OpenRefine/OpenRefine#4847]
The regex should be changed to ^[1-9]{1,3}\.[0-9]+$, the current version of the Wikimedia Commons manifest is 2.0, and thus creates this error.
Secondly: there should be a space and not a period in its error message. 

### To Reproduce
1. Go to the Wikibase schema
2. The "Wikidata" dropdown in the top-right corner, pick "Select Wikibase instance"
3. "Add Wikibase" option
3. [Wikimedia Commons wikibase manifest](https://raw.githubusercontent.com/OpenRefine/wikibase-manifests/master/wikimedia-commons-manifest.json), either copy it or put in this URL
4. "manifest.version should match pattern "^1\.[0-9]+$""

### Current Results
Unable to add Wikimedia Commons as a Wikibase Instance

### Expected Behavior
Not this error.

### Versions
 - Operating System: Windows 11
 - Browser Version: Chrome 101.0.4951.54 
 - JRE or JDK Version: java version "1.8.0_331"
Java(TM) SE Runtime Environment (build 1.8.0_331-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.331-b09, mixed mode)
 - OpenRefine: Version 3.5.2 [e3efd4e]

### Additional context
As a side note: "manifests for some public Wikibases can be found [here](https://github.com/OpenRefine/wikibase-manifests)" should be changed to "See the overview of [public Wikibases manifests](https://github.com/OpenRefine/wikibase-manifests)".  Read more about [why you shouldn't label links with "click here"](https://www.w3.org/QA/Tips/noClickHere)

**Comment by wetneb** [comment]
So, this error was encountered when trying to use a manifest with a version of OpenRefine that does not support such a new version of the manifest syntax.

It is good that we are preventing the user to add the manifest in this case, but we could have a better error message, indicating that the user needs a more recent version of OpenRefine to work with this manifest.
