### ISSUE TITLE
ODS exporter adds an additonal empty sheet to the project

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4864]
The ODF exporter creates files with two sheets: the first is empty, and the second contains the project data. We should remove the first one.

### To Reproduce
1. First, export any project to ODF
2. Then, open it (for instance with LibreOffice)

### Current Results
The exported file contains two sheets, the first one being empty.

### Expected Behavior
The exported file should contain a single sheet with the project data.

### Versions
 - Operating System: Debian
 - JRE or JDK Version: 11
 - OpenRefine: 3.6-SNAPSHOT

### Datasets

Example exported file: [Clipboard.ods](https://github.com/OpenRefine/OpenRefine/files/8716506/Clipboard.ods)

### Additional context
Similar to #4738

**Comment by vdimopoulos** [comment]
Can you assign me to this one? Thank you in advance!

**Comment by xiao2k** [comment]
I think we can use `getTableByName("Sheet1")` and `defTable.remove();` to solve this issue.

**Comment by wetneb** [comment]
@xiao2k since @vdimopoulos was assigned to this issue, it is nice if you can check with them first if they are still working on this issue before working on it yourself. No worries for this time though, I think 10 days is indeed enough to tackle something like this :)
