### ISSUE TITLE
Possible lingering bug that we have for refreshing the Scatterplot and other dialog-container

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#4871]
>Likely a browser refresh could have also fixed the issue. :-)  There might be a small lingering bug that we have for refreshing the Scatterplot, or the cache.  The Scatterplot dialog is treated within the dialog-overlay context and I have seen a few of our dialogs in that context sometimes have browser cache issues.  Not sure what the "good fix" would be but I'm sure a JavaScript expert (@antoine2711 ?) might debug this and help us fix it for good.  (ensuring that any datatype changes a user does are considered part of the "must refresh data cache" processing on our backend always.)

_Originally posted by @thadguidry in https://github.com/OpenRefine/OpenRefine/issues/2117#issuecomment-1132202044_

1. The user had strings in her columns when attempting to perform a Scatterplot and the display within its dialog was blank entirely.
2. She was instructed to transform the columns to Datatype: Number and try the Scatterplot again, but was blank again.
3. She then restarted OpenRefine and tried to display the Scatterplot facet again within the same project and this time the plot dots where shown correctly in the dialog.

**Comment by elebitzero** [comment]
I'm not able to reproduce this with the sample data set food.csv

Steps

1. Create Project. Choose file foods.csv
2. Next then Create Project
3. Select Calcium Column Menu-> Facet -> Scatterplot Facet
[Comes up blank]
4. Calcium Column Menu-> Edit Cells->Common Transforms-> to Number
5. Calcium Column Menu-> Facet -> Scatterplot Facet
[Comes up blank]
6. Water Column Menu-> Edit Cells-> Common Transforms-> to Number
7. Calcium Column Menu-> Facet -> Scatterplot Facet
[Works]

For scatterplot facet to work on the desired column, that column must be numeric, and there must be another column that is numeric.  There is a bug that no error message is displayed when the column is not numeric.  I filed a new issue #4890 for that.

**Comment by thadguidry** [comment]
Thanks, then let's close this one.  I think it was just a browser cache issue they had which is hard to pin down right now.
