### ISSUE TITLE
Release OpenRefine's documentation under a Creative Commons license

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#4876]
I looked up some documentation yesterday, and it struck me that the footer at every https://docs.openrefine.org/ page says _"Copyright © 2022 OpenRefine contributors"_. I would find it fitting for an open source project to release our documentation under a [Creative Commons license](https://www.creativecommons.org). 

At first sight, Attribution-ShareAlike 4.0 (or a more liberal 4.0 license) sounds like a good choice to me (most recent version of the CC licenses, compatible with the [Definition of Free Cultural Works](https://freedomdefined.org/Definition), compatible with licenses used in Wikimedia projects). The 'ShareAlike' component would make it into a [viral license](https://en.wikipedia.org/wiki/Viral_license) and we could even drop that part.

I totally imagine that the current _©_ setting/footer is just there because it is the default built into the Jekyll theme used for our documentation, and we never thought about modifying it ;-)

### What do other open source projects do?
I did a quick check of licensing used by other open source projects for their documentation, and it's interesting :-) More examples will give more inspiration.
* [Jupyter](https://docs.jupyter.org/en/latest/) and [Inkscape](https://inkscape-manuals.readthedocs.io/en/latest/) also have © - probably also just the result of going with the default offered by the themes of their documentation portal, I assume.
* OpenStreetmap has most of its documentation on a [MediaWiki wiki](https://wiki.openstreetmap.org/wiki/Beginners%27_guide), and they use CC BY-SA 2.0.
* [LibreOffice](https://documentation.libreoffice.org/en/english-documentation/) uses CC BY-SA 3.0
* Mozilla's MDN Web Docs mostly has [CC BY-SA 2.5 and later](https://developer.mozilla.org/en-US/docs/MDN/About#copyrights_and_licenses).

### Additional context and thoughts
Some of our documentation has been written by a contractor, and we may want to check their contract again and check back in with them for an agreement (maybe it's not necessary).

**Comment by wetneb** [comment]
I think we have had that discussion before: in my understanding, the documentation is released under the same license as OpenRefine (since it is hosted in the same repository). It would be good to update the docs template to reflect that indeed. The license is mostly equivalent to CC-BY so we could also go for that.

**Comment by thadguidry** [comment]
@trnstlntk  yeah, as Antonin said, it should be CC-BY equivalent.  That "copyright" tag is just from the template and we simply overlooked it, or not squinted our eyes hard enough ;-) So thanks for catching that!
