### ISSUE TITLE
Waiting screen while guessing reconciliation types should be internal to the reconciliation dialog

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4877]
Currently, when opening the reconciliation dialog, we have the following user experience:
1. user selects the reconciliation service
2. a "Working…" screen appears while OpenRefine guesses reconciliation types. The user cannot do anything while this is shown.
3. the reconciliation configuration dialog appears and the user can start configuring the reconciliation

Sometimes the guessing of reconciliation types actually takes quite some time (depending on the recon endpoint, the internet connection speed, the specifics of the dataset…) and it can be quite frustrating to wait for this process to complete - especially if you already know which type you want to reconcile the data to, or if the service does not use types at all.

### Proposed solution
Instead of having this "Working…" screen, we should directly show the reconciliation configuration dialog. We would have a waiting spinner (similar to the one used in data extension preview) in the sub-area of the dialog which shows guessed types. It could look like this (with an animated spinner):
![image](https://user-images.githubusercontent.com/309908/169650402-2759f441-ba17-4f46-b679-19bb378b5cb4.png)

### Alternatives considered

None

### Additional context
Problem observed in a session at Dataharvest 2022 (in a conference room with pretty bad wifi)

**Comment by antoine2711** [comment]
I was saying that exactely 2 days ago. 👍

**Comment by ayushrai206** [comment]
hey,i would like to work on this issue,please assign it to me.
