### ISSUE TITLE
Invalid "distclean" option in scripts

### ISSUE THREAD

**Issue by AtesComp** [OpenRefine/OpenRefine#4889]
The refine scripts:
* refine
* refine.bat

contain the invalid "distclean" option.

For maven, "distclean" is not a processable goal or directive for any plugin.  It is not included in the clean plugin.

### To Reproduce
1. ./refine distclean

### Current Results

An error.

### Expected Behavior

The"distclean" option should likely perform a process including the "mvn clean" command along with several forced directory removals to clean the distribution compiles.

### Screenshots

None

### Versions
 - Operating System: N/A
 - Browser Version: N/A
 - JRE or JDK Version: N/A
 - OpenRefine: All

### Datasets

N/A

### Additional context

None

**Comment by wetneb** [comment]
I think `mvn clean` already includes deleting the packaged versions of the software (the `.jar` files and `packaging/target/`) so I would be in favour of just removing the `distclean` option.

**Comment by v1scal** [comment]
Hi, could I work on this one? I've already looked at the code and think it's pretty straightforward.
