### ISSUE TITLE
Log in / close buttons not visible when logging in in third party wikibase

### ISSUE THREAD

**Issue by D063520** [OpenRefine/OpenRefine#4931]
### To Reproduce
1. Take the current snapshot release (I took for mac)
2. Make a project to upload data to a third party wikibase
3. Upload edits when not logged in

### Current Results
<img width="1728" alt="Screenshot 2022-06-06 at 17 29 52" src="https://user-images.githubusercontent.com/10883585/172193769-9b5be487-9814-4a1b-b546-eaf448db99f0.png">

### Expected Behavior
<img width="1728" alt="Screenshot 2022-06-06 at 17 30 00" src="https://user-images.githubusercontent.com/10883585/172193798-5f773163-7926-4e24-b3ca-2f7bbafc8c01.png">

NOTE: the screenshots show also the solution of the problem, some css problem 

### Versions
 - Version 3.6-SNAPSHOT [153eb2a]

**Comment by wetneb** [comment]
I think the intention was only to hide a message inviting users to log in with OAuth. In the meantime the buttons have changed location and have ended up in this area, so they are unintentionally hidden. Thank you for reporting it, we should be able to fix it before the next 3.6 release! In the meantime I suspect 3.5 should not have this bug.

**Comment by D063520** [comment]
I had another problem somehow with 3.5. but I have a local fix for this, so it is fine : )
