### ISSUE TITLE
Wikidata reconciliation service unavailable

### ISSUE THREAD

**Issue by CollectieDIVA** [OpenRefine/OpenRefine#4968]
Hi all,

I am currently reconciling data for a cultural institution using the Wikidata reconciliation service, but as of this morning there seems to be an issue. When I try to reconcile data, I get the following message in the pop-up window that normally fetches and displays the data:

_Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Apache/2.4.38 (Debian) 

Server at wikidata.reconci.link Port 443_

See image attached.
![OpenRefine_bug_Wikidata_reconciliation](https://user-images.githubusercontent.com/73224676/174269012-20107836-d107-41c3-a60a-eeeeded4c2d2.png)

Does this problem occur to anyone else?

**Comment by wetneb** [comment]
Thanks for the notice! I have restarted the service and this seems to be solved.
