### ISSUE TITLE
Import Project and Language buttons are not visible

### ISSUE THREAD

**Issue by fabiolinus** [OpenRefine/OpenRefine#4972]
Hi. I have this type of errors when I open chrome devloper tools. I use Win 10 but I can't see Import Project and Language buttons on the left. Is sounds very strange. Thanks for any help.

Uncaught TypeError: Cannot set properties of null (setting 'id')
    at Refine.OpenProjectUI._renderProjects (index-bundle.js:64956:18)
    at Object.success (index-bundle.js:64942:26)
    at fire (index-bundle.js:3234:31)
    at Object.fireWith [as resolveWith] (index-bundle.js:3364:7)
    at done (index-bundle.js:9842:14)
    at callback (index-bundle.js:10313:8)
    at Object.send (index-bundle.js:10323:7)
    at Function.ajax (index-bundle.js:9740:15)
    at Refine.OpenProjectUI._fetchProjects (index-bundle.js:64937:7)
    at Refine.OpenProjectUI._buildTagsAndFetchProjects (index-bundle.js:64913:10)
index-bundle.js:64486 Uncaught TypeError: Cannot read properties of undefined (reading 'resize')
    at resize (index-bundle.js:64486:32)
index-bundle.js:64486 Uncaught TypeError: Cannot read properties of undefined (reading 'resize')
    at resize (index-bundle.js:64486:32)
    at dispatch (index-bundle.js:5228:27)
    at elemData.handle (index-bundle.js:4880:28)

**Comment by wetneb** [comment]
Thanks for reporting this! It could be useful to have:
* a screenshot
* details of which extensions you have installed
* which operating system and browser you use

Thank you!

**Comment by fabiolinus** [comment]
Thanks a lot, Antonin.
1) screenshot in this mail2) No extensions installed3) Windows 10 and Chrome Versione 102.0.5005.115 (Build ufficiale) (a 64 bit). Both of them are updated.
    Il sabato 18 giugno 2022, 22:03:12 CEST, Antonin Delpeuch ***@***.***> ha scritto:  
 
 


Thanks for reporting this! It could be useful to have:
   
   - a screenshot
   - details of which extensions you have installed
   - which operating system and browser you use

Thank you!

**Comment by wetneb** [comment]
We cannot see your screenshot, I think you need to post it directly on GitHub. Also, it would be useful to know which version of OpenRefine you are using.

**Comment by fabiolinus** [comment]
Hi and thanks a lot. Here is waht you wanted.
![Untitled](https://user-images.githubusercontent.com/33990409/174455841-8f9af73d-d1e6-4b92-a7c1-3fbbf3c0b135.png)

**Comment by fabiolinus** [comment]
Some buttons on the left are missing. I think that import project and Language are missing. Under the openrefine logo i see nothing.

**Comment by wetneb** [comment]
Thanks! Do you know which version of OpenRefine you installed?

**Comment by fabiolinus** [comment]
I use last version of openrefine OpenRefine 3.6-beta2 but It was the same with the last stable version (3.5.2?)

**Comment by fabiolinus** [comment]
Thanks a lot, Operefine is art!!!!!!!!

**Comment by thadguidry** [comment]
From the screen shot it appears that the Italian language has already been chosen, but it seems it might be causing a display issue for that particular language?
Puzzling, I cannot find that translated phrase `Nessun file selezionato` in our Italian translation file https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/langs/translation-it.json

**Comment by fabiolinus** [comment]
Hi and thanks for your help. Really I can't help you. I downloaded this version and the last stable version but it is the same. I clicked on .exe file and I see that screeshot. It sounds really strange. I have no estenstions installed in openrefine and in google chrome. I reported chrome to the original settings too.
    Il sabato 18 giugno 2022, 23:21:38 CEST, Thad Guidry ***@***.***> ha scritto:  
 
 


From the screen shot it appears that the Italian language has already been chosen, but it seems it might be causing a display issue for that particular language?
Puzzling, I cannot find that translated phrase Nessun file selezionato in our Italian translation file https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/langs/translation-it.json

**Comment by fabiolinus** [comment]
I remember that (very) old version of openrefine showed me these buttons.
Fabio
    Il sabato 18 giugno 2022, 23:21:38 CEST, Thad Guidry ***@***.***> ha scritto:  
 
 


From the screen shot it appears that the Italian language has already been chosen, but it seems it might be causing a display issue for that particular language?
Puzzling, I cannot find that translated phrase Nessun file selezionato in our Italian translation file https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/langs/translation-it.json

**Comment by fabiolinus** [comment]
Is that a problem with the italian keyboard? 
Fabio
    Il sabato 18 giugno 2022, 23:21:38 CEST, Thad Guidry ***@***.***> ha scritto:  
 
 


From the screen shot it appears that the Italian language has already been chosen, but it seems it might be causing a display issue for that particular language?
Puzzling, I cannot find that translated phrase Nessun file selezionato in our Italian translation file https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/langs/translation-it.json

**Comment by thadguidry** [comment]
@fabiolinus Do the buttons appear if you use Firefox or Edge browser on your Windows 10 ?

**Comment by wetneb** [comment]
From what I can see it is a problem with a corrupted workspace: it looks like your projects have not been correctly saved. I would back up the workspace somewhere safe, delete the workspace and start OpenRefine again.

**Comment by fabiolinus** [comment]
> @fabiolinus can you please attach the `support.log` file found in the OpenRefine folder?

[support.log](https://github.com/OpenRefine/OpenRefine/files/8935141/support.log)

Also did you download and are using our OpenRefine 3.6-beta2-**win-with-java** ? or just the **win** version?

I downloaded 'openrefine-3.6-beta2-win.zip' from GitHub (Java SE Development kit 15.0.1)

Thanks and sorry for delay

**Comment by elebitzero** [comment]
I created a PR(#4976) that will skip null projects so the UI will load.  The null project IDs are printed on the console.

**Comment by wetneb** [comment]
@fabiolinus can you try to download [our snapshot release](https://github.com/OpenRefine/OpenRefine#snapshot-releases) and see if the problem persists on your side? (Please do not download it before 09:00 UTC today as @elebitzero's fix might not have made it there before that)

**Comment by fabiolinus** [comment]
Ys, it works!!!!!!! Thanks a lot, Fabio

**Comment by fabiolinus** [comment]
Thanks a lot and sorry for delay, I was at the hospital for a quick check. Snapshot will be beta version of openrefine? See you soon,
Fabio


    Il mercoledì 22 giugno 2022, 08:34:42 CEST, Antonin Delpeuch ***@***.***> ha scritto:  
 
 


@fabiolinus can you try to download our snapshot release and see if the problem persists on your side? (Please do not download it before 09:00 UTC today as @elebitzero's fix might not have made it there before that)

**Comment by fabiolinus** [comment]
I downloaded exe file without JAVA. Thanks a lot for your effort.

Fabio

**Comment by fabiolinus** [comment]
![Untitled](https://user-images.githubusercontent.com/33990409/175513420-bb6d7cb2-1aac-4b0f-87f1-fee762853097.png)

**Comment by fabiolinus** [comment]
Hi. I'd like to ask to you. Consider to open two text facets in openrefine. Visible rows are the those which satisfied both facets (AND). Second facet depends from the first facet (order is important). For example male and females showed in the second facet are those selected from the first choice (first facet). OK, It is easy to understand. Suppose you choose a text facet, then a numeric facet. Numeric facet doesn't depend from the first facet. I think the numeric facet must change with the first facet. I don't know if I was clear. Thanks a lot for any help,
Fabio  Frascati





Il venerdì 24 giugno 2022, 12:33:29 CEST, Antonin Delpeuch ***@***.***> ha scritto:
 
 
 


Closed #4972 as completed.

**Comment by fabiolinus** [comment]
Hi. I have a simple dataset:
A B1 a2 b3 c
I'd like to obtain a csv file with tow columns: A (numeric) and B (string):
A, "B"1, "a"2, "b"3, "c"
I use Custom Tabular Exporter but it puts quote evertwhere or ad a lot of quotes to the elements of column B:
""a""
or
"""a"""
How can I obtain a simple schema like before? Thanks a lot,
Fabio


    Il mercoledì 22 giugno 2022 01:17:15 CEST, elebitzero ***@***.***> ha scritto:  
 
 


I created a PR(#4976) that will skip null projects so the UI will load. The null project IDs are printed on the console.

**Comment by wetneb** [comment]
Hi! Please ask the question on the mailing list, StackOverflow, or other help forums.

**Comment by fabiolinus** [comment]
Done. Thanks a lot,
Fabio
    Il sabato 16 luglio 2022 18:25:05 CEST, Antonin Delpeuch ***@***.***> ha scritto:  
 
 


Hi! Please ask the question on the mailing list, StackOverflow, or other help forums.

**Comment by fabiolinus** [comment]
Good question......I will try with firefox, then I will disinstall it.
Fabio
    Il domenica 19 giugno 2022, 00:15:41 CEST, Thad Guidry ***@***.***> ha scritto:  
 
 


@fabiolinus Do the buttons appear if you use Firefox or Edge browser on your Windows 10 ?
