### ISSUE TITLE
Wikimedia Commons: make Wikitext editable/overwritable

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#4989]
Relevant for OpenRefine 3.6+ in which Wikimedia Commons editing is possible.

In a previous meeting for the [Wikimedia Commons integration project](https://github.com/orgs/OpenRefine/projects/2/views/1), we discussed that it would be possible to make Wikitext of a file editable / overwritable. I then recommended to not enable this, mainly with the argument that I find it a bit scary (Wikitext is fiddly and it would not be good if users would, for instance, massively replace, remove or create faulty Wikitext, which could make the Commons community angry).

But based on user interviews / tests organized by @lozanaross (and based on my own experience and needs) I think I've changed my mind: users are actively asking to allow replacing existing Wikitext (to replace complex infobox templates with more simple Wikidata-driven ones), and we think OpenRefine / Wikimedia Commons users should generally be savvy enough to know what they are doing.

### Proposed solution
Let's add an 'override if present' check box for Wikitext in the Wikimedia Commons schema builder, which will trigger overwriting all existing Wikitext upon editing.

### Further considerations
I'm not sure yet if we will indeed want to include a separate field in the schema builder for Wikimedia Commons categories, or if we will skip this and ask the users to include categories in the Wikitext instead. If we add a separate field / functionality to add one or more Commons categories, for consistency an overwrite checkbox there would make sense too.

**Comment by Ambrosiani** [comment]
looking forward to trying this – also want to add +1 for editing categories separately from the other wikitext.

**Comment by lozanaross** [comment]
> For editing categories independently from the wikitext, I would handle that in a separate issue. I think further design for this is needed (what would the UI look like, for instance).

The latest version of the wireframes actually already proposes a UI for that, but indeed best to discuss in a separate issue as that design also needs some more updating.

**Comment by bjhoareAM** [comment]
What is the current situation on this? I find it a little confusing that there is a box to tick indicating you can override wikitext if present, but that it does not actually seem to allow overriding. I am trying to replace the template structures within some categories I have worked on, and it is a little frustrating that I have no way to standardise them thoughtfully with a bulk edit such as this.
