### ISSUE TITLE
Wikidata reconciliation query/scores when multiple variable on same property and date precision

### ISSUE THREAD

**Issue by paulgirard** [OpenRefine/OpenRefine#4993]
I am not sure that is a bug or a question. 
Above all because scores are computed on wikidata side but sill I am sure someone like @wetneb might have insights.

I'd like to understand how to precisely tune a reconciliation against wikidata using a rich data-set.
There are in this example two different reconciliation issue/questions: 
- reconciling against property using multiple values (I am using firstnames in people in this example)
- reconciling against date when there is only years (I am using birthdate)

### To Reproduce
1. Create a project with this sample data with number detection on. This table list variations of possible ways to build the reconcile query.
```
Person	name	Firstname1	firstname2	birthdate
William Albert Ablett	Ablett	William	Albert	1877-07-09 00:00:00
William Albert Ablett	Ablett			1877-07-09 00:00:00
William Albert Ablett	Ablett	William	Albert	1877
William Albert Ablett	Ablett			1877
William Albert Ablett	Ablett	William Albert		1877
William Albert Ablett	Ablett	William Albert		1877-07-09 00:00:00
William Albert Ablett	Ablett	William		1877-07-09 00:00:00
William Albert Ablett	Ablett	William		1877
```
3. start a reconciliation on Person using all the properties like this:
```
[
  {
    "op": "core/recon",
    "engineConfig": {
      "facets": [],
      "mode": "row-based"
    },
    "columnName": "Person",
    "config": {
      "mode": "standard-service",
      "service": "https://wikidata.reconci.link/fr/api",
      "identifierSpace": "http://www.wikidata.org/entity/",
      "schemaSpace": "http://www.wikidata.org/prop/direct/",
      "type": {
        "id": "Q5",
        "name": "être humain"
      },
      "autoMatch": false,
      "columnDetails": [
        {
          "column": "name",
          "propertyName": "nom de famille",
          "propertyID": "P734"
        },
        {
          "column": "Firstname1",
          "propertyName": "prénom",
          "propertyID": "P735"
        },
        {
          "column": "firstname2",
          "propertyName": "prénom",
          "propertyID": "P735"
        },
        {
          "column": "birthdate",
          "propertyName": "date de naissance",
          "propertyID": "P569"
        }
      ],
      "limit": 0
    },
    "description": "Reconcile cells in column Person to type Q5"
  }
]
```
4. The score obtained are somehow mysterious to me
![image](https://user-images.githubusercontent.com/193478/175920765-82dd1aa7-3d22-4d43-adc5-79d76bc419b0.png)

### Current Results
In the current results the best score is obtained when:
- we only use one firstname
- we use the year version of the date

### Expected Behavior

Since the targeted entity https://www.wikidata.org/wiki/Q19832695 is very well described listing both firstnames in P735 and both full date and year only in P569, I would have expected that all variations (but rows 5 and 6) would be scored 100. 
I don't understand why the score are so varied.
Maybe there is a way to reconcile a list of values against on property in a different way to achieve this expected behavior?
And I don't understand neither why the year version of the date yields better score than the entire date?

### Versions
 - Operating System: Linux mint 
 - Browser Version: firefox 101.0
 - JRE or JDK Version: openjdk version "11.0.15" 2022-04-19
 - OpenRefine: 3.5.2

### Additional context

I started a discussion on the mailing list about this but with less precise description: https://groups.google.com/g/openrefine/c/WK6-5kSZLRA

**Comment by wetneb** [comment]
Thanks for your question! Moving it to https://github.com/wetneb/openrefine-wikibase/issues/141.

**Comment by paulgirard** [comment]
Oh yes much better place for this.
Thanks
