### ISSUE TITLE
Extensions defining new importing controllers need to import theme.less from OpenRefine

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4994]
Some extensions define new "importing controllers" (for instance the gdata and database extension). This is the expected extension point when implementing an importing mechanism which loads data from other sources.

As part of this, extensions need to define parsing pages which look like the importer preview we have in OpenRefine.
For the styling of those parsing pages, both the gdata and database extensions rely on OpenRefine-internal `.less` files that they explicitly import on their own side.

This looks like this:

https://github.com/OpenRefine/OpenRefine/blob/5746951ec069549345eb368ea74a77c3fec9a912/extensions/database/module/styles/theme.less#L30

While this technique avoids duplicating files from the core to the extensions, this is far from ideal because this mechanism is not available to extensions developed outside this repository.

Intuitively, it should be possible for any extension to use the standard styling of the parsing page, without having to redefine it itself. Of course, we still want extensions to be able to add some custom CSS to this page, should they need to.

Ideally, it would be great if we could fix this in a backwards-compatible way (meaning that extensions which have been built for the current situation would keep working with the new system), although this is likely to be difficult. And it is probably not so important since we can easily fix the extensions in this repository.

@antoine2711 @WaltonG this is an issue you are likely to run into (or have already run into?) for the SPARQL extension, no?

**Comment by WaltonG** [comment]
@wetneb I copied the theme.less file which contains the below line and it works fine https://github.com/OpenRefine/OpenRefine/blob/5746951ec069549345eb368ea74a77c3fec9a912/extensions/database/module/styles/theme.less#L30

**Comment by wetneb** [comment]
It might work in your development settings but I suspect this is going to break as soon as users install it in their workspace, as documented here: https://docs.openrefine.org/manual/installing#find-the-right-place-to-install

**Comment by WaltonG** [comment]
Will definitely have to try that out
