### ISSUE TITLE
"Discover Wikibase manifests..." button

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#5007]
OpenRefine 3.6 comes with a very handy new `Discover services...` button in the reconciliation dialog that helps people discover reconciliation services (clicking the button will bring folks to https://reconciliation-api.github.io/testbench/#/ which lists many of these services).
![image](https://user-images.githubusercontent.com/9881645/177012120-272ae874-416c-438d-ab2c-a406434477e6.png)

Similarly, it would be great (and a uniform pattern) if we had a similar `Discover Wikibase manifests...` button in the Wikibase extension's 'Select Wikibase instance' dialog window.
![image](https://user-images.githubusercontent.com/9881645/177012156-9c858897-ffc5-47ee-b260-ecf790883184.png)

When clicking on that new button, folks could be led to https://github.com/OpenRefine/wikibase-manifests. This could also be an encouragement for more Wikibase maintainers to publish their manifests there.

**Comment by trnstlntk** [comment]
I actually think this was an idea from @lozanaross - credit where credit is due 😇🥇

**Comment by wetneb** [comment]
Just a note about the text on the button: I would find it more appealing to have something like "Discover Wikibase instances…" or "Discover Wikibases…" because the manifest is just a rather technical thing.

**Comment by lozanaross** [comment]
I vote for "Discover Wikibase instances..." for consistency with the title of the dialog, which is "Select Wikibase instance"

**Comment by elebitzero** [comment]
I can work on this tomorrow.
