### ISSUE TITLE
Add a Confirm dialog for Starred expression Remove links

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#501]
_Original author: thadguidry (December 01, 2011 15:32:49)_

Using Expression Editor and the Starred expression tab.

It would be nice to have an extra &quot;Confirm ?&quot; popup dialog with REMOVE CANCEL buttons when a user clicks Remove link on a Starred expression.

With the slip of a mouse button, I just lost a very long and nice expression that took me 15 mins to pull together with some research, and probably should have just stored that in a Notepad document and uploaded to Google Docs for safekeeping. :)

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=501_

**Comment by MarosKitti** [comment]
Hey, I would like to solve this problem. Can I work on this issue?

**Comment by wetneb** [comment]
You can! Thanks for volunteering :)

**Comment by TejaswiKarasani** [comment]
@wetneb I would like to take up the issue if other is not working on it

**Comment by MarosKitti** [comment]
> @wetneb I would like to take up the issue if other is not working on it

I was working on it.

**Comment by wetneb** [comment]
@kushthedude please do not assign the same issue to multiple people unless they are explicitly collaborating together - the point of assigning people to issues is to avoid duplication of efforts. Thank you!

**Comment by CameronBedard** [comment]
Hello, there doesn't seem to be any submissions on this, can I work on it?

I have a functional change already, here's what it looks like.
![ConfirmDialogSS](https://user-images.githubusercontent.com/25983556/102932148-bd1f4800-446d-11eb-82d7-ee9b3d295a23.jpg)

**Comment by wetneb** [comment]
@CameronBedard sure, thank you!
