### ISSUE TITLE
Switching between Wikidata and Wikimedia Commons does not clear schema from Wikidata

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#5010]
When working with a dataset that combines Wikidata and Wikimedia Commons editing, and when a schema has been created in Wikidata, a switch to Wikimedia Commons will not clear the Wikidata schema, but will keep the 'wrong' schema in place.

I noticed this with the Wikidata-Commons switch but have not tried this with other Wikibases. This issue may also occur there.

Screenshot, showing that there has been a switch to Commons, but we still see the old Wikidata schema:
![image](https://user-images.githubusercontent.com/9881645/177057225-3dbde478-e6bd-446d-a667-fdde7f92ff87.png)

### To Reproduce
1. Work with a dataset in which both Wikidata and Wikimedia Commons must be edited
2. First do edits on Wikidata with a Wikidata schema
3. Switch to Wikimedia Commons
4. Go to the schema tab and notice that the old schema is still in place

### Expected Behavior
Schema should be cleared, OR the last saved schema from Wikimedia Commons would be expected to appear (if one has been saved before in this project)

### Versions
 - Operating System: macOS 10.13.6
 - Browser Version: Chrome 103.0.5060.53
 - JRE or JDK Version: n/a
 - OpenRefine: 3.7 snapshot release of 30 June 2022

### Datasets
[public-art-Stuttgart.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/9035499/public-art-Stuttgart.openrefine.tar.gz)

**Comment by wetneb** [comment]
I can also reproduce this.

**Comment by wetneb** [comment]
This was solved by #5288.
