### ISSUE TITLE
Re-enable Coveralls in the CI

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5013]
Our submission of coverage info to Coveralls is broken, so I have disabled it.
It would be great to fix the underlying issue or migrate to another coverage info submission mechanism.
https://github.com/trautonen/coveralls-maven-plugin/issues/147

**Comment by wetneb** [comment]
Commits which disable coveralls:
* https://github.com/OpenRefine/OpenRefine/commit/bfa8c9af756c5efe570b653067811eadd57bd12d
* https://github.com/OpenRefine/OpenRefine/commit/7ec03039db028d52adeac7e8d6b650a919e26005

**Comment by tfmorris** [comment]
I was able to use the [Universal Coverage Reporter](https://docs.coveralls.io/integrations#universal-coverage-reporter) to upload using the command:

`coveralls --format jacoco -r <repo token>`

and it's supposedly the future for Coveralls, so perhaps just migrate to it now even though it's nominally still under development.
