### ISSUE TITLE
Expose available import formats in the API

### ISSUE THREAD

**Issue by Abbe98** [OpenRefine/OpenRefine#5014]
OpenRefine support for various import formats depends on both the OR version used and the extensions in use. Extensions register the supported formats with the `registerFormat` method, however, there is no way for API clients to retrieve these formats, and clients are left to either hardcode formats or guessing.

### Proposed solution

Expose the available formats through the API.

Possibly `GET /command/core/get-import-formats`

### Alternatives considered

None

### Additional context

 - https://docs.openrefine.org/technical-reference/openrefine-api#create-project
 - https://cs.github.com/OpenRefine/OpenRefine/blob/158586d5c27cd3a14d850d50bb5222495a544e9a/main/src/com/google/refine/importing/ImportingManager.java?q=ImportingManager#L61

**Comment by wetneb** [comment]
Hey @Abbe98, thanks for this request!

So far, our backend API has been built just for the frontend, without any intention that it used by other clients. While we are of course not trying to prevent people from using it in other ways, there are no stability guarantees about this API and it is quite poorly documented. The fact that this API is private is something @tfmorris has been quite adamant about (major contributor to the project, now only sporadically active).

So the change you suggest would go in a new direction, where the backend supports commands which are not used in the frontend. I am personally not categorically opposed to that, but it is something worth discussing more broadly. I guess the main advantage of keeping this API private is to be more free in the changes we introduce.

I would be curious to hear more about your use case: how would you use this feature?

**Comment by Abbe98** [comment]
@wetneb I have a custom OpenRefine frontend (built on top of these APIs) that I want to open source. This is the one thing that is hardcoded for my set of extensions and it would be neat if it could be API-driven.

**Comment by Abbe98** [comment]
Closing as #5025 would make this available with a `GET` request (turns out it was already available but only through `POST` requests).
