### ISSUE TITLE
New interface to display Wikibase editing results

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5032]
We need an additional interface to display the outcome of uploading edits to a Wikibase instance. This is necessary for:
* Displaying a link to the editgroups page (or user contributions): https://github.com/OpenRefine/OpenRefine/issues/4751
* Displaying editing errors which could not be forecast earlier: https://github.com/OpenRefine/OpenRefine/issues/1782. Those errors are currently reported in the server logs but should rather be exposed to the user.
* We could also add some more detailed progress information (number of remaining edits, ETA, current lag…). We could potentially also let the user pause and resume the editing.

This interface should be visible while the edits are being made. Ideally it should also be possible to retrieve it again after the edits have been made, to check the error log after the fact, for instance.

### Proposed solution

Add another tab, alongside the "Schema", "Issues" and "Preview" ones, where we display this information.

### Alternatives considered

* We could use a modal dialog instead. This is not so convenient in my opinion because users might want to look at the grid while edits are being made (for instance to check the contents of a particular row where an editing error happened)
* We could introduce a generic mechanism in OpenRefine to display logs for long-running operations: #4236. I think there is no clear vision for that yet, so I would propose to try out a pattern specifically for the Wikibase extension first, and then see if we can come up with a suitable generalization.
* We could try to store errors in the grid, but that seems not very convenient to me:
    * There is no obvious place where to insert a column with errors (since the schema will generally rely on multiple columns). Running multiple upload operations in the same project (which is very common for me) will create multiple error columns
    * There is often no obvious row to which a given error should be attached (some edits are generated by multiple rows).
    * The EditGroups link or progress information obviously should not be stored in the grid

### Additional context

Especially important for uploads to Wikimedia Commons where the upload process will be very long and error-prone.

**Comment by wetneb** [comment]
@Ebere330 we are actually tempted to go for a different option than the one suggested in this issue, so it is probably not so useful for you to start working on this approach. See the relevant discussion:
https://github.com/OpenRefine/OpenRefine/issues/5348

Let me close this issue as the approach consisting in storing editing logs in the grid is preferred.

**Comment by Ebere330** [comment]
@***@***.*** ***@***.***>  Thank you for your response.
Will view the relevant issue on #5348
