### ISSUE TITLE
Wikibase manifest format does not allow for local reconciliation endpoint

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5035]
For testing purposes I have created a Wikibase manifest for [EDTF Wikibase](https://edtf.wikibase.wiki/wiki/), a test Wikibase instance which demonstrates the EDTF datatype.

As part of this I have written the following Wikibase manifest:
```json
{
    "version": "1.0",
    "mediawiki": {
        "name": "EDTF Wikibase",
        "root": "https://edtf.wikibase.wiki/wiki/",
        "main_page": "https://edtf.wikibase.wiki/wiki/Main_Page",
        "api": "https://edtf.wikibase.wiki/w/api.php"
    },
    "wikibase": {
        "site_iri": "http://edtf.wikibase.wiki/entity/",
        "maxlag": 5,
        "properties": {
            "instance_of": "P3",
            "subclass_of": "P15"
        }
    },
    "oauth": {
        "registration_page": "https://artbase.rhizome.org/wiki/Special:OAuthConsumerRegistration/propose"
    },
    "reconciliation": {
        "endpoint": "http://localhost:8000/${lang}/api"
    }
}
```

### Current Results

This manifest is currently not accepted by the UI, seemingly because the reconciliation endpoint is not recognized as a valid URL.
I suspect this is due to the `localhost` host which might not be accepted by the underlying regex.

### Expected Behavior
According to https://json-schema.org/understanding-json-schema/reference/string.html, the format we are currently using (`url`) is not even supported by the standard. Since we include the `${lang}` variable in it, we should probably use `uri-template` instead, although that would mean conforming to that particular format.

Alternatively we could use our own regex to validate this field, or drop validation for it. After all, the validity of this field is checked immediately after parsing the Wikibase manifest, by trying to add the reconciliation service.

### Environment

OpenRefine 3.7-SNAPSHOT, Linux, Firefox

**Comment by eonm-abes** [comment]
Hi all,

I'm facing the same bug. 

I prefixed localhost with `www` as a workaround : ` "http://www.localhost:8000/${lang}/api"`.  But this workaround doesn't work with URL containing IP addresses like `http://192.168.1.31:8000/${lang}/api`.

__Environment__

OpenRefine 3.5, Linux and Windows, Firefox

**Comment by tarrow** [comment]
I also encountered this; I didn't look inside the code but the workaround for me was to use `http://<some-extra-thing>.localhost:8000/${lang}/api` which (on my ubuntu machine) also resolves to localhost.
