### ISSUE TITLE
Implement expensive Wikibase QA checks only triggered before upload

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5037]
The Wikibase extension comes with some quality assurance checks, which validate the candidate edits against some constraints, to warn the user of potential issues in the edits.

The checks implemented so far are designed to run quickly, so that we can update the issues tab in real time, as the user transforms their dataset and filters it to display a specific subset of rows.

Sometimes it would be useful to implement more expensive checks, which we would not want to run every time a change in project data happens, because it would delay the delivery of issues to the user and waste resources. For instance, I am thinking about the following checks:
* when uploading new items with external unique identifiers, check if there are any existing items with those identifier values. For now we only report an issue if we are creating two different items with the same identifier value
* when uploading new media files, check that their filenames do not exist on the MediaWiki instance yet
* checking for the presence of suitable inverse statements (for now we only check for them within the edits to be made)
* and probably more constraint checks that we cannot implement fully without fetching data from the Wikibase instance

### Proposed solution

Constraint checks could be run into two modes:
* the fast mode (the current one), in which the check must be performed quickly (without fetching external information except for small metadata like constraint definitions)
* the slow mode (the new one), in which the checks are allowed to take longer, for instance by making some network operations

The slow mode would only be triggered when opening the "Upload edits to Wikibase" dialog. This dialog would show those more thoroughly computed checks (currently it already displays the existing fast checks).

### Alternatives considered

One other solution could be to change the architecture used to compute QA issues, so that each scrutinizer could return its issues asynchronously. This would mean that the issues that are the fastest to compute would be displayed first, and then the slower ones would appear. This would be very nice to have, but I think it would not get rid of the need to have two modes (slow / fast), because I would not want to run the expensive checks over and over, every time a change is made (it would generate a lot of requests to the target wikibase, a lot of which would likely be redundant).

**Comment by thadguidry** [comment]
Agree that there are 2 camps of users in the proposal essentially supported...those that can wait or have patience and those that cannot wait much for whatever reason.  We should support both sets of users and your slow/fast constraint checks mode sounds reasonable.  I just don't have strong opinions on what the smart defaults (slow checks/fast checks) need to be where in the tool interfaces, and so leave that to the community to decide.

**Comment by wetneb** [comment]
So far I did not think of actually exposing a control to the user, letting them turn slow checks on or off. My plan so far is that:
* in the `Issues` tab of the main view, the fast mode is used (because this area is refreshed every time the grid, the facets or the schema are changed, so this must only take a few seconds)
* in the `Upload edits to Wikibase` dialog, the slow checks are enabled, because that dialog is typically used when the user is ready to upload (so much less often): at that stage, it is worth checking more thoroughly for problems.

We could also let the user activate slow checks in the `Issues` tab via some control, but I would be slightly worried that this would generate quite big volumes of requests to some web services.
