### ISSUE TITLE
Drop the requirement for reconciliation when uploading new files to Commons

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5038]
@trnstlntk asked if it would possible to drop the requirement to mark a column as reconciled to "new" before uploading new files to Wikimedia Commons.

### Proposed solution

Remove the "subject" field of MediaInfo schema objects, and only use the filename field in place.
That means the user will not check that the filenames they provide do not exist yet on the instance. We need to decide what happens if there are conflicts.
One thing we could potentially do is to lookup the filenames as part of the issues generation, so as to report to the user which filenames exist or not. This could rely on #5037.

### Alternatives considered
Status quo.

### Additional context
This could potentially be useful to other Wikibase instances, removing the need for a Commons-like reconciliation service.

**Comment by lozanaross** [comment]
I am not sure about this - it goes against the logic of how things work in Wikidata schema building. Arguably, Commons users don't care about Wikidata workflows, but if they want to create more sophisticated SDC, then they'll need to inevitable learn about Wikidata schema editing, too. I think solving #4985 should be the priority - after that some simple documentation, some "helptext" and a nice onboarding tour (if we get to that point) will be enough to make users understand the value of creating new items via the reconciliation menu.

**Comment by wetneb** [comment]
Indeed, let's close this in favour of #4985.
