### ISSUE TITLE
Add support for uploading local media files on third-party Wikibases without structured data

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5039]
OpenRefine should be able to upload files to Wikibase instances which are their own media repository. By this, I mean that the media files which can be referenced in Wikibase statements are stored in the same MediaWiki instance as the Wikibase itself.

In such instances, the media files typically do not have structured data associated with them, as that data can already be represented in the item namespace if needed.

### Proposed solution

Repurpose the existing Commons integration, which already includes support for file upload.
* [ ] adapt the Wikibase manifest format to make it possible to keep file upload while disabling support for MediaInfo entities
* [ ] potentially it would be useful to remove the need for a reconciliation service entirely, using #5038. This would make sense because using the reconciliation service to fetch extra data is not super useful if structured data is not enabled on the wiki (although the wikitext could potentially be of interest)
* [ ] make sure the resulting filenames can be used as values in media-valued statements on the Wikibase instance. This requires adapting the edit scheduler to detect the relationship between the upload of the file and its use in a statement.

### Alternatives considered
Not sure!

### Additional context

@lozanaross your input would be very welcome to frame this issue better (I hope I have understood it correctly!)

**Comment by lozanaross** [comment]
This all makes sense to me.

> potentially it would be useful to remove the need for a reconciliation service entirely

Yes, I don't see the need to reconcile these files, since no structured data will be attached to them. We may just have to think about dealing with file names that may be repeating existing file names in the Wiki (i.e. what happens if we attempt to upload a file with a name that already exists in the wiki - an issue notification is generated & upload cannot proceed? files are overridden? file name is appended with a number?).

> make sure the resulting filenames can be used as values in media-valued statements on the Wikibase instance. This requires adapting the edit scheduler to detect the relationship between the upload of the file and its use in a statement.

I think if the files remain a type of "string" they should already technically work (w/o reconciliation). I've been able to successfully create statements linking items to file names that already exist as media inside the target Wikibase.

**Comment by wetneb** [comment]
> Yes, I don't see the need to reconcile these files, since no structured data will be attached to them. We may just have to think about dealing with file names that may be repeating existing file names in the Wiki (i.e. what happens if we attempt to upload a file with a name that already exists in the Wiki - an issue notification is generated & upload cannot proceed? files are overridden? file name is appended with a number?).

Actually this is indeed pretty critical: at the moment, this reconciliation step is the only opportunity the user has to be notified of naming conflicts. So until we have the possibility to report conflicts later on (such as with #5037), I would keep this.

Given that the assumption that entities correspond to reconciled columns is weaved through the tool pretty tightly, it is also tempting from a technical perspective not to violate this assumption. Therefore, so far I have been working on this feature without #5038.

This should not make the third checkbox above any harder, I suspect.
