### ISSUE TITLE
Check for duplicate files on Wikimedia Commons

### ISSUE THREAD

**Issue by Ambrosiani** [OpenRefine/OpenRefine#5041]
It might be interesting to check for duplicate files somewhere in the upload process or at least offering the possibility somewhere in OpenRefine.

Duplicate info for existing Commons files is available through the API: https://www.mediawiki.org/wiki/API:Duplicatefiles.

### Proposed solution

One possibility: check hash for duplicates in the "Issues" tab before uploading.

### Alternatives considered

Another possibility: add duplicates as a possible property to the "Add column from reconciled values" modal. Maybe this is already possible but I don't know the syntax?

### Additional context

![Skärmavbild 2022-07-08 kl  11 06 37](https://user-images.githubusercontent.com/2394405/177959011-5a7c190e-4c3c-4429-a615-72726c253c10.png)

**Comment by trnstlntk** [comment]
Thanks for reporting this; uploading duplicate files indeed needs to be avoided. We already had issue #4472, not sure if they are exactly the same and can be merged?

**Comment by trnstlntk** [comment]
> ### Alternatives considered
> Another possibility: add duplicates as a possible property to the "Add column from reconciled values" modal. Maybe this is already possible but I don't know the syntax?

I'm not sure if I understand this suggestion correctly? Looking for duplicates, to me, seems like a very different action than retrieving statement values via reconciled values, but it's quite possible that I'm just not seeing the light here :D

**Comment by wetneb** [comment]
We indeed already have #4472 for checking for duplicates at upload time.
For fetching the existing duplicates of an already uploaded file we could indeed add a property to the reconciliation service (as suggested by the screenshot). That would be implemented in the Commons reconciliation service, so I opened a ticket about that there: https://phabricator.wikimedia.org/T312703
I suggest we continue the discussion in both of those places.

**Comment by wetneb** [comment]
I met [User:Don-vip](https://commons.wikimedia.org/wiki/User:Don-vip) at Wikimania and he made me aware of a project to offer an API for detecting duplicate images on Commons via perceptual hashes:
https://commons.wikimedia.org/wiki/User_talk:Zache#c-Don-vip-20240808083500-CParle_(WMF)-20240724115200

There is a phabricator ticket here: https://phabricator.wikimedia.org/T362352
