### ISSUE TITLE
Remove the need to click "add item"/"add media" when creating a new Wikibase schema

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5050]
When starting a new Wikibase schema on a project, the user first needs to click on "+ add item" (or "+ add media" for Wikimedia Commons) to model the edits they want to do:

![image](https://user-images.githubusercontent.com/309908/178133934-1c700aaa-2b7a-476f-9ee6-0f5040006698.png)

This is basically an action that is forced on them, so it feels like a useless click we should remove. They should directly land into this state:
![image](https://user-images.githubusercontent.com/309908/178133953-948e6f01-ba95-4b83-b452-393ce931e14f.png)

One exception is when the Wikibase instance supports multiple entity types that OpenRefine can edit. For instance, a Wikibase instance with items and local files would fall into this category. In this case, when opening the schema editor for that instance, we do not know yet if the user wants to edit items or upload media files.

### Proposed solution

If only one of the entity types of the Wikibase instance can be edited by OpenRefine, create an empty schema element for such entity types at schema creation.

If multiple entity types are supported, let the user choose as is currently the case.

### Alternatives considered
Status quo.

### Additional context
Suggested in the context of the Wikimedia Commons integration by @lozanaross.

**Comment by lozanaross** [comment]
Can we put a pause on this until I rework the wireframes? I believe the issue is a bit more complex than what's described above - that is if we want to keep behaviour across all kinds of Wikibases as consistent as possible..

**Comment by lozanaross** [comment]
The reworked wireframes offer a solution that moves the "add item" / "add media" button to the left and makes it more prominent. Then the button(s) appear context-specific to Wikibase chosen. See screenshots below: 

![Screenshot 2022-07-23 at 22 37 41](https://user-images.githubusercontent.com/25489750/180622077-a46f77e1-8584-4f7c-be2b-55591a9a2203.png)

![Screenshot 2022-07-23 at 20 36 44](https://user-images.githubusercontent.com/25489750/180622096-e3c202bc-c2be-4ddf-936d-d53941b26672.png)

![Screenshot 2022-07-23 at 20 36 47](https://user-images.githubusercontent.com/25489750/180622099-0f1b352f-1de2-43de-abff-f79bb6a21946.png)

Complete wireframes (including development parameters are here): https://xd.adobe.com/view/3ae13acb-7afb-4ea5-8252-351a1622abba-6fb2/

**Comment by wetneb** [comment]
I think that is a nice idea, but it feels independent from this issue: does it not make sense to still, by default, add a new entity to the schema if there is a single entity type to chose from?

**Comment by lozanaross** [comment]
> I think that is a nice idea, but it feels independent from this issue: does it not make sense to still, by default, add a new entity to the schema if there is a single entity type to chose from?

Hm, maybe - but then it won't be consistent with current behaviour and with what will be needed for Wikibase. Also while it will save a click, it might then make it less obvious that you can also add more items and bundle a bunch of different changes to different items in one schema - i.e. having to click the button once is a 'learning experience' for users, too. I know it sounds basic, but there are plenty of users (esp GLAM folks) who are new to the concept of how data is modelled in Wikidata, because maybe they only worked with Commons until now. Of course for experienced users it makes no difference. I would suggest we do something like an AB test - e.g. you implement the change as per your suggestion (as long as it's easy enough to implement). We run some tests with a snapshot release in September, and if people like it - we keep it. If people are confused, we roll back to the existing UX (which requires you to click on "+add [item / media]"

**Comment by thadguidry** [comment]
@wetneb you stated in original comment that
> One exception is when the Wikibase instance supports multiple entity types that OpenRefine can edit. For instance, a Wikibase instance with items and local files would fall into this category. In this case, when opening the schema editor for that instance, we do not know yet if the user wants to edit items or upload media files.

You mention we don't know what the user wants to do.  That is often the case in OpenRefine and its general mantra to present to the user what they can do...and then let them make the choices they need.  I think presenting all options based on context would work well; If there is a way to know when a Wikibase instance offers support of multiple types, then we know when to show the buttons or not, correct?  Or am I missing something?

**Comment by wetneb** [comment]
Let's just close this per lack of consensus (one less thing to code, yay!)
