### ISSUE TITLE
UI for schema template selection and saving new templates

### ISSUE THREAD

**Issue by lozanaross** [OpenRefine/OpenRefine#5103]
This is a dedicated issue to discuss development of the UI around schema templates (see also #5043) 

### Proposed solution
The proposed solution is to offer a schema template picker from a dropdown menu directly below a similar dropdown menu for selecting a Wikibase instance (see #4819)

The basic interface can look like this: 
![Screenshot 2022-07-23 at 22 37 41](https://user-images.githubusercontent.com/25489750/180623367-64411fd0-63e5-4af4-acde-c9e399308c68.png)

![Screenshot 2022-07-23 at 20 36 44](https://user-images.githubusercontent.com/25489750/180623368-4bc6512a-78dc-498f-be76-c852a2c194e6.png)

![Screenshot 2022-07-23 at 20 36 44](https://user-images.githubusercontent.com/25489750/180623622-56e2441c-1b09-401a-bb68-0020a14c1a68.png)

Users should be able to save new custom schemas and after saving these will become available in the dropdown menu (NB For Commons we will provide some pre-defined schemas for Artworks, Art Photos and Books). The dialog for saving could look like this: 
![Screenshot 2022-07-23 at 23 28 43](https://user-images.githubusercontent.com/25489750/180623423-765dcdc1-47b5-4c0e-ab09-c3dfd376fa4f.png)

### Alternatives considered
An alternative is to not have schema templates at all, only schemas and allow users to save them locally, but then that won't help with work across teams or when users want an "empty" schema - i.e. a schema with properties pre-filled, but no values.

Other alternatives would be using / integrating Entity Schemas from Wikidata somehow, but that solution also seems unclear how to implement both technically and visually in the UI. (See [discussion here](https://www.wikidata.org/wiki/Wikidata_talk:Schemas?markasread=805886512&markasreadwiki=wikidatawiki#Feedback_from_the_%22Entity_Schema_build-out_and_integration%22_task_of_WMDE's_development_plan,_and_OpenRefine))

### Additional context
The dialog window design for saving schema templates proposed above is just a first draft. The button that says "Open your local schema template library" is just a shortcut to e.g. a folder in the user's local machine where json files of the schemas are saved. That folder should be "pre-loaded" with the schemas that Wikimedia Commons extension will ship with, otherwise for regular Wikidata and Wikibase users the folder will be empty until users create their own schemas. Other ideas / solutions how to make a library of schema templates visible are welcome - I was trying to minimize the UI work of building additional custom dialogs to display the library as that would require more development effort.

**Comment by lozanaross** [comment]
After a schema template is selected, it will populate the schema building interface like so: 
![SDCWireframes_SchemaTab_InfoTemplateSelected](https://user-images.githubusercontent.com/25489750/180623721-ef272907-2344-4a2e-a5e7-ce1280649f03.png)

For complete wireframes (with development specs) check: https://xd.adobe.com/view/bb4e7d0a-39e6-4bcb-aeed-f6215cf509c6-ee1d/

**Comment by lozanaross** [comment]
One other point worth mentioning is the proposal to move the buttons that currently say "Save schema" and "Discard changes" to below the line of column headings, and to update the first button to say "Save schema progress". This proposal aims to make it easier for users to understand the difference between a schema template & the schema they are currently building at the moment, the latter is more of a local / work-in-progress type of entity which they may or may not want to save / export at certain times, or discard entirely.

Mockup of the new button position is below (NB this could be implemented potentially even before the full schema template functionality is implemented, but there is no need):
![Screenshot 2022-07-23 at 23 49 34](https://user-images.githubusercontent.com/25489750/180624081-b946b633-768e-492a-b526-558fcad7083f.png)

**Comment by thadguidry** [comment]
@lozanaross So the term "progress" is also interchangeable with "template"?  I.E. alternatively that button could say "Save schema template"?

We have two entity types if I understand the internal model correctly:
1. A schema (all values populated)
2. A schema template (where there could be no values)

So does "Save schema progress" refer to the entity of 1. or the entity of 2. ?  How would users know?

**Comment by lozanaross** [comment]
@thadguidry - it is tricky indeed:

"Save new..." button that is right next to schema template selector is the one that refers to entity 2. as per your description.

"Save schema progress" is the same button that in the current interface says "save schema" and is above the line of column headers - I am proposing to move that below further below on the page and to add word 'progress' to indicate that button refers to a full schemas (with values) and is something OpenRefine saves in the background anyway (e.g. before Upload).

We may need to do user testing to figure out the best wording, but the two buttons do refer to different things. So I tried to move them as far away as possible.

**Comment by wetneb** [comment]
For me it is counter-intuitive to use "progress" to mean "complete schema", since progress refers more to an intermediate state for me. I would just keep this button as "Save schema".

**Comment by thadguidry** [comment]
Agree with @wetneb , so we would have 2 buttons that describe saving for the 2 entities.  "Save schema" and "Save schema template" somewhere

**Comment by lozanaross** [comment]
OK, thanks for feedback @wetneb and @thadguidry - happy to keep it as it was - I was just trying to suggest somehow a bigger difference between the schema templates and schemas (the latter being also saved in the background as far as I understand whether the user presses the button or not). But agree that 'progress' is not the right word. If we come up with a better solution, we can always change it, but for now I agree we can keep it simple and just use "save schema" (the other button is called "save new" and it's positioned right next to the schema template selector, so not sure if we need to make it more descriptive than that.

**Comment by wetneb** [comment]
> the latter being also saved in the background as far as I understand whether the user presses the button or not

This is probably worth documenting somewhere because I had not realized it was unclear before our discussion. Let me try to clarify this here. Currently, the schema is only saved when:
* the user presses the Save schema button
* the user exports its dataset to QuickStatements
* the user uploads its edits to Wikibase from OpenRefine
* (new in 3.7) the user creates a facet to select rows generating a particular issue, in the Issues tab

If the user makes changes to the schema, and then closes the window without doing any of the actions above, then they are warned that they have unsaved changes by their browser to give them the opportunity to save the schema, whose changes will be lost otherwise.

**Comment by wetneb** [comment]
> there is some kind of autosave going on in the background anyway that users are not explicitly told when it is triggered

Users do get a notification when it is triggered, using the usual yellow pill at the top of the screen. How could we improve that?

> make the text in the default browser message a bit more specific - e.g. "Changes that you made to your schema may not be saved."

As far as I know this is unfortunately something we indeed have no control over. This message is defined by the browser and cannot be customized:
https://stackoverflow.com/a/40570214/985087

**Comment by lozanaross** [comment]
> Users do get a notification when it is triggered, using the usual yellow pill at the top of the screen. How could we improve that?

Ok, but it is very subtle - had to really look for it. For example in these scenarios:

- the user exports the dataset to QuickStatements >> Here at least on my mac chrome browser, I am forwarded to a new empty browser tab that starts the file download, so there is no chance for me to see the yellow notification pill.
- the user uploads edits to Wikibase from OpenRefine >> Here the notification is hidden below the overlay that darkens the screen and opens the new dialog for upload. Unless I'm really looking for it, easy to miss...

I think this my just be my issue though, maybe other users are OK with the subtle clues. I think best to feature a question about this in the next round of user testing + dedicated survey that @trnstlntk and I discussed we want to do in Sept. Depending on the results of the survey, I could design a more obvious overlay for the notification, i imagine it needs to be more central on the user screen, a bit more prominent in size and maybe on top (instead of below) other dialogs / overlays  (or timed to appear for a few seconds before the other dialogs pop up). 

> As far as I know this is unfortunately something we indeed have no control over. This message is defined by the browser and cannot be customized: https://stackoverflow.com/a/40570214/985087

No probs, thought so too.

**Comment by wetneb** [comment]
Since this was implemented in #5191 I would close this, feel free to reopen if you disagree
