### ISSUE TITLE
Add small logo icons next to green reconciliation status bar to indicate data reconciliation source

### ISSUE THREAD

**Issue by lozanaross** [OpenRefine/OpenRefine#5104]
Currently users who work with both Wikidata and another Wikibase instance (e.g. a private Wikibase, or Wikimedia Commons) struggle to remember which columns in their OpenRefine project are reconciled to which service - especially if they work with large datasets. This becomes particularly problematic during schema building.

### Proposed solution
Introduce small logo icons next to the green bar the indicates reconciliation status. The logos will be sourced from the manifests for the WB instances. We can start with just providing logos for Wikidata and Wikimedia Commons, and then build support for custom logos, too. 

Here is a mockup of this proposal in the context of row / record view:
 
![Screenshot 2022-07-15 at 14 32 35](https://user-images.githubusercontent.com/25489750/180624711-06740948-e277-415c-bb89-bbd2fbddbe3a.png)

And a mockup in the context of Schema view:
![Screenshot 2022-07-23 at 23 49 34](https://user-images.githubusercontent.com/25489750/180624720-73847eef-bae7-47cc-bd08-844691744d50.png)

Complete wireframes with more context and development specs are available here: https://xd.adobe.com/view/bb4e7d0a-39e6-4bcb-aeed-f6215cf509c6-ee1d/  

### Alternatives considered
Yes, alternatives were considered that used text (e.g. the name of the Wikibase service) rather than logos, but they were discarded for looking more clunky and for not being workable in the schema building context.

### Additional context
There is another related issue regarding indicating where data is sourced from following data extension operations. If data is pulled from Wikidata via reconciled values - the data can be shown to be reconciled to Wikidata already with the logo, but there is no way to tell users the source was also Wikidata. For that users proposed that prefixes are added to the column headers. This is explained in detail in a separate issue.

**Comment by wetneb** [comment]
Duplicate of #4824, no? If so, let's keep only one of them open (no preference which)

**Comment by lozanaross** [comment]
Oh yes, indeed, forgot that one was already made, let's keep the first one then. I'll close this one.
