### ISSUE TITLE
The login for the Google Data importer seems to be broken

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#5107]
When using the Google Data importer, the login process works, but at the stage of displaying the documents, it keeps stalling.

### To Reproduce
1. Login into Google
2. Then, wait indefinitely.

### Current Results
It stalles.

But I don't believe it's a KEY issue from packaging. I was able to login a first time. I experience the same problem with v3.6rc1 and v3.6.

To make things worst, henceforth v3.6, I think we have this problem on ALL our platforms. I tested Windows 10 and Ubuntu 22.04 and I see the same thing, an infinite spin. :-(

### Expected Behavior
Display the list of files

### Screenshots
![image](https://user-images.githubusercontent.com/12217525/180622346-6350b647-d768-484c-bc3e-58b51a2a1486.png)

### Versions
 - Operating System: Tested on Mac 11.6, Windows 10 and Ubuntu 22.04
 - Browser Version: Chrome v102
 - JRE or JDK Version: Java 11
 - OpenRefine: v3.6rc1 and v3.6
 
 ### Other information
I don't think it's related to https://github.com/OpenRefine/OpenRefine/issues/4414.

**Comment by elebitzero** [comment]
The Google login is fine. The problem is if there is document that has been updated 3-7 days ago or last month, the code in formatRelativeDate throws an error due to the undefined function Date.getDayOfYear.

This does not appear to be a regression since the code was there since 2011.
