### ISSUE TITLE
Japanese Translation File Naming

### ISSUE THREAD

**Issue by AtesComp** [OpenRefine/OpenRefine#5118]
Japanese translation files erroneously use "jp" in the file name.  The "jp" designation is a country code.  They should use "ja" instead as this designation is the language code.

### To Reproduce
1. See the translation files for the main program and extensions.  For Japanese, they are "translation-**jp**.json".
2. Consult the Internet on language versus country code for Japanese.

See: https://www.andiamo.co.uk/resources/iso-language-codes/
See: https://news.ycombinator.com/item?id=5047300

**Comment by wetneb** [comment]
Agreed. This language code was introduced in bedb8c03bf7d1a80a6e978ff8dc10c5ff8a98384, before we used Weblate, and seems to be wrong indeed. We could rename this. Weblate would probably handle this just fine, but on OpenRefine's side I think it would be good to introduce a fallback mechanism to make sure that people using OpenRefine in japanese currently do not get an error when they upgrade. Maybe in the load-language command, for instance?

**Comment by isaomatsunami** [comment]
Wow. The very first translator got off on the wrong foot! (I just wanted to use this phrase. Thanks AtesComp / Antonin!)

**Comment by AtesComp** [comment]
Right! I noticed this when I had a translation submission to the RDF Transform extension using a "-ja.json" file.  I couldn't understand why it wasn't loading until I saw the "jp" files.

Could the load-language code report a warning that the current language wasn't found and show the expected 2 char language code and defaulting? Server side? It's a small corner case but could help in the debug process.

Also, supporting a "debug" preference in OR for log messages could be helpful...maybe for 4.0.

Also, is the browser's navigator.language (and languages array) a default based on the country code given the IP's geolocation?  This would imply the default language code--we would need to translate a country code to a language code.  Also, are there country codes that match other language codes? If so, there is another problem if we don't strongly differentiate country code input from language code.  I'll look at the related code.

**Comment by wetneb** [comment]
> Also, is the browser's navigator.language (and languages array) a default based on the country code given the IP's geolocation? This would imply the default language code--we would need to translate a country code to a language code. Also, are there country codes that match other language codes? If so, there is another problem if we don't strongly differentiate country code input from language code. I'll look at the related code.

I think it is much simpler than that: you do not need any IP geolocation or mapping countries to languages. Most browsers simply expose the locale they prefer using the `Accept-Language` header, such as `Accept-Language: en-GB,en;q=0.5`.
I do not think we currently rely on this header to set the locale, but it would indeed be a sensible thing to do: it would be worth opening an issue for it, if we have not got one for it yet.

**Comment by AtesComp** [comment]
Yes, it is simpler as you say.  I've looked at the code and adjusted as follows:

1. Readded the locale language on the client side via navigator.language || navigator.language[0].
2. Use the locale language on the server side as a "suggested" language that is replaced with the user preference if available.
3. Added a CORRECTOR for user preference "jp" to put a replacement "ja" user preference.
4. Added a CORRECTOR for a ""ja" file exception to look for a "jp" file.  I'd rather force the extension maintainer to rename the file instead.  Otherwise, this could perpetuate for some time.
5.. Renamed all the *-jp.json files to *-ja.json.  External extensions will need to rename any "jp" file.

The CORRECTORS have a TODO noting that the related code should be removed sometime after the 3.7 release.

I'll push the code up as a pull request.

**Comment by elebitzero** [comment]
@AtesComp,  I was looking at this too, and while I'm not making any of the changes you mentioned, I noticed that there are multiple copies of the i18n initialization code in project.js, index.js, and preference.js.  This is because the webapp controller.js has separate templates index.vt, preferences.vt, and project.vt for different pages.

I am issuing a PR to put this common code into a single script.  Please wait for that to be merged, and then make your proposed changes on top of that. That way we don't have to copy it in three places.

The extensions with UIs (e.g. database, Wikidata,etc.) have their own message files, and the ja vs jp problem may be there also.

**Comment by AtesComp** [comment]
Thanks @elebitzero,  I'll wait.  I had just reviewed that common i18n initialization code as well.  Searching on "command/core/load-language" hits 10 files.  I was setting them all to do at least:
```
// Internationalization init
var lang = (navigator.language || navigator.languages[0]).split("-")[0];  <--- HERE
var dictionary = "";
$.ajax({
  url : "command/core/load-language?",
  type : "POST",
  async : false,
  data : {
    module : "database",
    lang : lang  <--- HERE
  },
  success : function(data) {
    dictionary = data['dictionary'];
    lang = data['lang'];
  }
});
$.i18n().load(dictionary, lang);
// End internationalization
```
Sometimes the initial `lang` variable was missing.  I believe @wetneb was suggesting adding it back to all the `data : {`.
