### ISSUE TITLE
[doc] merge "column-groups" right after "rows-vs-records"

### ISSUE THREAD

**Issue by VladimirAlexiev** [OpenRefine/OpenRefine#5122]
1. I didn't know about https://docs.openrefine.org/technical-reference/architecture#column-groups
1. It's an important complement (and actually more powerful than) https://docs.openrefine.org/manual/exploring#rows-vs-records
1. So IMHO "column-groups" should be moved from the "technical-reference" section (which normal users won't read) to the user "manual" section, right after "rows-vs-records"
1. Also, describe the interplay between the two
1. Edit "rows-vs-records".
   a. We can remove "The Wizard of Oz" example because "column-groups" provides a more elaborate example
   b. "if you move a column to the beginning, you may find your data becomes misaligned": true, but not enough: if I move the second column `Actor` to the end, won't this also misalign the data?
  c. So therefore should it not talk of "records and **sub-records** and rows" (eg in this example the subrecord actor=Ray Bolger	has two rows: role="Hunk", role=The Scarecrow)
1. Edit the parent section https://docs.openrefine.org/technical-reference/architecture#column-model 
   a.  Consider whether to move a bit more text to the user "manual". Maybe only "Columns can be removed and re-ordered without changing the raw data--the cells in the rows. This makes column removal and ordering operations really quick"
   b. Add a link in that section to the new location of "column-groups"

Please comment by item, and when agreed I can implement the changes

**Comment by tfmorris** [comment]
Column groups is a partially implemented, buggy, feature, so I'm not sure it makes sense to include in end user documentation.

**Comment by wetneb** [comment]
Thanks for opening this topic Vladimir!
I agree with Tom that this feature is not ready at all for prime time. In fact, in the 4.0 architecture, I have dropped it altogether, after discussion on the mailing list:
https://groups.google.com/g/openrefine/c/A8RhOwlulRs/m/NFR8LDBmBwAJ

That being said, representing hierarchical data is still an important topic, so coming up with a replacement would definitely be welcome I think.

**Comment by VladimirAlexiev** [comment]
* If I shuffle columns, the column groups disappear.
* Discussion for a better hierarchical model: https://groups.google.com/g/openrefine/c/X9O8NBC1UKQ.

@ostephens 
> I don't even know how to use the column grouping except in terms of visualising the data! What can you currently do with the column groupings?

I thought the new OR 3.6 GREL function `parent` to "obtain the parent element of an XML element" may be related to this.
However, it works only for `jsoup`, see #4181.
So if I understand correctly it works on a XML string in a cell, not on the parsed cell structure.

Ok, I'll edit the doc to say that Column Groups are partially implemented and deprecated, and point to these discussions?

**Comment by wetneb** [comment]
Sounds good to me, thanks for your doc edits :)

**Comment by thadguidry** [comment]
> 
> I thought the new OR 3.6 GREL function `parent` to "obtain the parent element of an XML element" may be related to this.
> 
> However, it works only for `jsoup`, see #4181.
> 
> So if I understand correctly it works on a XML string in a cell, not on the parsed cell structure.
>

Correct.  That new function is fir helping parse and filter in cell data, not for project modeling or column modeling.  I really needed it for web scraping data improvements and was the first immediate use case.

**Comment by VladimirAlexiev** [comment]
Closing as obsolete (dead end)
