### ISSUE TITLE
[doc] algolia search doesn't find

### ISSUE THREAD

**Issue by VladimirAlexiev** [OpenRefine/OpenRefine#5127]
Try search (control-K) for "jython" while at https://docs.openrefine.org/manual/jythonclojure#jython:

![image](https://user-images.githubusercontent.com/536250/181468020-23f3b028-870d-4d4f-8df5-ab17ad3128d2.png)

The search config needs to be adjusted somehow, so eg "jython" can be found.

- There's a link "let us know" that goes to https://github.com/algolia/docsearch-configs/issues/new?template=Missing_results.md&title=[openrefine]+Missing+results+for+query+%22jython%22.
- However, https://github.com/algolia/docsearch-configs/issues is archived so one cannot submit issues
- can you copy Missing_results.md here, and change the link to https://github.com/OntoRefine/OntoRefine/issues/new?template=Missing_results.md&title=[doc]+Missing+search+results+for+query+%22jython%22.

**Comment by ostephens** [comment]
I think there is a more general issue with search not working currently - I'm not finding search results at all on https://docs.openrefine.org/ right now

**Comment by wetneb** [comment]
Algolia hahd an outage thish morning, according to https://status.algolia.com/
![image](https://user-images.githubusercontent.com/309908/181557382-f6943628-b3ee-45e7-bc31-ee2e4ea6db62.png)

Perhaps they haven't fully recovered yet?

**Comment by VladimirAlexiev** [comment]
Here's what Algolia returns:
```js
{
  "results": [
    {
      "hits": [],
      "nbHits": 0,
      "page": 0,
      "nbPages": 0,
      "hitsPerPage": 20,
      "exhaustiveNbHits": true,
      "exhaustiveTypo": true,
      "query": "j",
      "params": "query=j&attributesToRetrieve=%5B%22hierarchy.lvl0%22%2C%22hierarchy.lvl1%22%2C%22hierarchy.lvl2%22%2C%22hierarchy.lvl3%22%2C%22hierarchy.lvl4%22%2C%22hierarchy.lvl5%22%2C%22hierarchy.lvl6%22%2C%22content%22%2C%22type%22%2C%22url%22%5D&attributesToSnippet=%5B%22hierarchy.lvl1%3A10%22%2C%22hierarchy.lvl2%3A10%22%2C%22hierarchy.lvl3%3A10%22%2C%22hierarchy.lvl4%3A10%22%2C%22hierarchy.lvl5%3A10%22%2C%22hierarchy.lvl6%3A10%22%2C%22content%3A10%22%5D&snippetEllipsisText=%E2%80%A6&highlightPreTag=%3Cmark%3E&highlightPostTag=%3C%2Fmark%3E&hitsPerPage=20&facetFilters=%5B%22language%3Aen%22%2C%5B%22docusaurus_tag%3Adefault%22%2C%22docusaurus_tag%3Adocs-default-3.6%22%5D%5D",
      "index": "openrefine",
      "processingTimeMS": 1
    }
  ]
}
```

**Comment by ostephens** [comment]
It looks like there were some changes to the Docusaurus/Algolia integration that came in earlier this year. Does anyone know if this migration was done? See https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration

**Comment by wetneb** [comment]
Indeed we seem to have missed this. I have reached out to @allanaaa who signed us up for this as it looks like this is still under her account. I have also applied for another account using the advisory committee's email address to avoid this issue in the future.

**Comment by wetneb** [comment]
Looks like [bd2a819](https://github.com/OpenRefine/OpenRefine/commit/bd2a819606e36fe951960c2f5488e88dd11c8600) fixed it, but I will try to also gain access to the account.
