### ISSUE TITLE
Java setup unclear in user docs for Windows

### ISSUE THREAD

**Issue by seb-29** [OpenRefine/OpenRefine#5137]
Hi everyone!

I downloaded the newest version of OpenRefine (3.6) and tried opening the application. However, instead of the platform, I got redirected to the manual section on Java requirements. As the program requires Java 11-17, I uninstalled my version (8) and installed the latest one (17). **In spite of this, when trying to open OpenRefine, I still get redirected to the manual section on Java requirements! Could anyone please help me with this?**

P.S. I've checked for "java -version" in Prompt Commands: Java 17 is installed. However, searching for "Java" in Windows Start Menu yields no results.

**Comment by thadguidry** [comment]
Take a look at our http://docs.openrefine.org for the Windows installation which explains how to ensure that not only Java is available on the PATH but also your JAVA_HOME is set properly.

**Comment by thadguidry** [comment]
@wetneb What is up with our docs?  I don't see the section for JAVA_HOME any longer?

This is showing when I look at the versioned docs https://github.com/OpenRefine/OpenRefine/blob/608e2f8fccb161ca03ab224e5c57a6c594cfd46a/docs/versioned_docs/version-3.6/manual/running.md

----

:::caution Did you get a JAVA_HOME error? “Error: Could not find the ‘java’ executable at ‘’, are you sure your JAVA_HOME environment variable is pointing to a proper java installation?”

If you see this error, you need to [install and configure a JDK package](https://github.com/OpenRefine/OpenRefine/blob/608e2f8fccb161ca03ab224e5c57a6c594cfd46a/docs/versioned_docs/version-3.6/manual/installing#linux), including setting up JAVA_HOME. :::

----

But when I look at https://docs.openrefine.org/manual/running  I just don't see it any longer?

**Comment by seb-29** [comment]
Thank you @thadguidry! No, I did not get a JAVA_HOME error. I think my OpenRefine has not realized I have Java installed :-/ When I try to access your link "install and configure a JDK package" I get a 404 error (Didn't find anything here!).

**Comment by thadguidry** [comment]
@seb-29 Sorry, but that message reply was to our maintainer Antonin @wetneb and he or someone else needs to figure out what is happening with our docs not showing the same content as in our GitHub /docs/version_docs folder when I browse to the doc page:  
![image](https://user-images.githubusercontent.com/986438/182419253-f0af07b6-129e-4a79-b5a4-d26fbf517f19.png)

**Comment by wetneb** [comment]
@thadguidry this fragment of the docs is rendered correctly, as far as I can tell:
![image](https://user-images.githubusercontent.com/309908/182538216-3b6e8d8a-8c23-4f5e-b2f9-6ec143507f59.png)

**Comment by seb-29** [comment]
Hi @thadguidry & @wetneb,

I´ve checked how to configure Java SDK 17 - below my update!

After installation, the following system environment variable was automatically created under "Path":
_C:\Program Files\Common Files\Oracle\Java\javapath_

I deleted it and created a new separate (i.e. not under "Path") system environment variable "JAVA_HOME":
_C:\Program Files\java\jdk-17.0.4_

Then, I added a new system environment variable under "Path":
_%JAVA_HOME%\bin

Open Refine is now working! I hope this approach is correct - to me, it seems to make sense.

In any case, *thanks a lot* for your quick reactions :-)

**Comment by thadguidry** [comment]
@seb-29 yes, that is correct.

@wetneb I think it makes sense to have the same caution we have under the Linux tab, to also be under the Windows tab, since this is often the first common error that folks have, as evidenced by @seb-29 .  Could we do that small edit to the docs for the Windows tab as done for Linux tab?

**Comment by wetneb** [comment]
I think so, we just need a PR for that :)
