### ISSUE TITLE
"exclude" check box option on cluster member lists

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#514]
_Original author: kyawnain...@gmail.com (December 28, 2011 18:52:34)_

Due to undesired value(s) in the clustered result, I could not merge the rest desired values. Pls see Example below

 mirpurkhas 1 
 mirpurkhas-1
 mirpurkhas-2
 mirpurkhas I
 mir purkas 1

If there is option (check) to exclude line 3 from merge, then it will be great.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=514_

**Comment by thadguidry** [comment]
Found duplicate.  So closing this issue since #1009 captures this feature request well.
