### ISSUE TITLE
OpenRefine 3.6 will not launch on Mac when installed for all the users of the machine (root:wheel)

### ISSUE THREAD

**Issue by stevemaser** [OpenRefine/OpenRefine#5160]
In chatting with the devs on Gitter, it seems like this needs to be baked into the build process:

sudo chmod +r /Applications/OpenRefine.app/Contents/Resources/webapp/WEB-INF/*

otherwise, if the application is owned by "root:wheel" -- which is how Munki would deploy it for those orgs that use that -- the application will not launch.

**Comment by antoine2711** [comment]
More specifically, these 2 files must have o+r permissions: 
- Contents/Resources/webapp/WEB-INF/butterfly.properties
- Contents/Resources/webapp/WEB-INF/web.xml

**Comment by thadguidry** [comment]
But shouldn't it be up to a user to config under what privileges an app has at runtime? Rather than us baking assumed privileges for a particular deployment method on iOS?  It seems like just documentation guidance would be a better choice for users and admins of users in a controlled setting?

**Comment by stevemaser** [comment]
> But shouldn't it be up to a user to config under what privileges an app has at runtime? Rather than us baking assumed privileges for a particular deployment method on iOS? It seems like just documentation guidance would be a better choice for users and admins of users in a controlled setting?

This is on MacOS -- not iOS.    The application on the Mac will not launch if the application has "root:wheel" permissions without making this change to those two files (this is a regression from 3.5)
