### ISSUE TITLE
Is the 5000ms default delay for the fetch URL operation too high?

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5173]
I had feedback from a user who initially did not notice the <s>1000 ms</s> 5000 ms delay in the "Add column by fetching URLs" operation, and had to wait a long time for the operation to complete.

### Proposed solution

There is a case for saying that <s>1000 ms</s>5000 ms is perhaps a bit too high for a default value. It makes sense to have a relatively generous wait by default, so that users who are not aware of the problems caused by sending too many requests at a time do not accidentally hammer services.

### Alternatives considered

Add some contextual help to highlight this field (which is perhaps not so visible). This could be an occasion to educate users about responsible crawling, perhaps?

### Additional context

Perhaps this is less of an issue when we are able to show partial resrults for long-running operations (so that users do not have to wait for the completion of the operation to keep working on the project).

**Comment by elebitzero** [comment]
@wetneb, the default in the UI is actually 5000ms.

In the backend in HttpClient.java, the minimum delay is enforced to be 200ms.  

If the URLs each point to a different domain, I can see requests could be made as fast the websites are responding. Ideally, the backend should manage the requests by domain;   Requests only need to be spaced out to the same domain.

If the URLs all point to the same domain, what is the reasonable number of requests to make per second?  I believe that if less than 10 requests/second are being made, it should be OK.  So, the UI default could probably be changed to 200ms, which is the current backend minimum delay.

**Comment by wetneb** [comment]
Ah thanks for the correction! Then 5000ms is definitely too high indeed.

I think the most common case is when URLs all point to the same domain.

Although I do think 200ms should be fine in a lot of cases, I would perhaps suggest to be a bit more generous for the default value OpenRefine proposes, just to be on the more generous side, so perhaps 500ms?

Also I was not aware we had a minimum wait in the backend. That should probably also be made clear by the frontend (for instance by refusing lower values).

**Comment by tfmorris** [comment]
> In the backend in HttpClient.java, the minimum delay is enforced to be 200ms.

This would be a great place to include a link to make it easy for folks to check the code in question:
https://github.com/OpenRefine/OpenRefine/blob/cb55cdfdf6f9ca916839778dc847cce803688998/main/src/com/google/refine/util/HttpClient.java#L92-L96


My interpretation is that 200ms is the minimum *retry interval* (ie on failed requests), but there is no minimum on the inter-request delay. This restriction was [implemented](https://github.com/OpenRefine/OpenRefine/blame/cb55cdfdf6f9ca916839778dc847cce803688998/main/src/com/google/refine/util/HttpClient.java#L93) at the same time as the binary exponential backoff retries.

**Comment by elebitzero** [comment]
@tfmorris, thanks for pointing that out. I misread the code.

I'll relax the UI check so that the throttle delay just needs to be >= 0ms.

I think it makes sense to have some kind of minimum delay, because otherwise someone could bombard a website with requests. One possibility is to have a UI preference minThrottleDelay which defaults to 200ms, and someone would have to change it if they wanted to use a delay lower than 200ms.
