### ISSUE TITLE
Add RECOVER option to Home Page

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#518]
_Original author: thadguidry (January 16, 2012 06:28:47)_

It would be great to have a RECOVER option after HELP, ABOUT that pops up a help dialog saying &quot;Hover over the project that you wish to undo the last operation and recover&quot;.

Then the hover with mouse over each project instead of showing &quot;X Rename&quot; it instead shows &quot;UNDO LAST OP&quot;.

When the user clicks &quot;UNDO LAST OP&quot;, a script runs to undo using the 2nd to last ID in history, effectively restoring the project hopefully from an errant operation, such as a Key Columnize on a unique list of 1000 rows that ends up creating 1000 columns ! (this happened to me - Thad)

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=518_

**Comment by wetneb** [comment]
Similarly we could provide the option to un-delete projects which were erroneously deleted.

**Comment by wetneb** [comment]
This particular feature seems too specific to be run from the project list UI. The reason why it is currently needed is that it is massively inefficient to view a project with many columns. We should instead improve the project view with a proper JS grid which only fetches rows and columns that are visible on the screen, and fetch more as the user scrolls.
