### ISSUE TITLE
Migrate documentation to the repository for the website

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5187]
We should migrate the documentation to the repository of the website (currently https://github.com/OpenRefine/openrefine.github.com).

### Why I originally pushed for having the docs in this repository

* The ability to add a feature and its documentation in the same pull request was interesting to me
* The ability to use the same versioning mechanism for the code and docs felt like a good idea

### Why it's not that great

* Few PRs update simultaneously the code and the docs. It turns out a lot of code changes do not need documentation changes (because they fix a bug, optimize something…). When they do, we often forget to do it in the same PR and have to do a follow-up PR afterwards
* Because Netlify comes with a lot of PR checks, that makes the list of PR checks very long. We are generally only interested in the checks for the code or the checks for the docs, rarely both.
* This repository already has enough of a PR backlog with code changes alone, we do not really need more volume from the docs
* Having versioning in the same repository is not that great, because due to the publishing mechanism we need to have the docs for all supported versions on the master branch. We cannot simply edit the docs in the git branch of 3.5: those changes also need to be ported to the master branch, in the appropriate directory. This is a bit messy.

### Related

The versioning mechanism is confusing for contributors: #4409

**Comment by wetneb** [comment]
I intend to work on this with the aim to also rewrite our website with Docusaurus in the same process.

**Comment by thadguidry** [comment]
Don't forget to add /docs to the .gitignore

Also, after the migration, I wonder if it makes sense to carefully remove the doc files from the git history (there are automation tools that make this labor easier, or just script it.)

**Comment by wetneb** [comment]
Removing things from the git history is very disruptive because it implies changing the identity of all commits after the introduction of the docs, it would not play well with the open pull requests. We do not have so many images in the docs so I think it should be fine to leave the history as it is.

**Comment by thadguidry** [comment]
Agree, and I thought about that also.

**Comment by wetneb** [comment]
> I like the original reasoning behind encouraging doc & code updates at the same time (and it's something that's often part of code review checklists, along with unit tests, etc). It sounds like the proposed change will make this even worse rather than better.

I feel like when reviewing PRs, it is equally easy to ask the PR author to open another PR on the repository where the docs are stored, and only merge the code PR if there is an accompanying docs PR.

**Comment by thadguidry** [comment]
@wetneb What's the timeline on this?  by end of Oct/Nov?

**Comment by wetneb** [comment]
I have not set myself a deadline for this. I have started playing around with Docusaurus to see what it would take to integrate the current pages in the website, but it's going to take more effort to get something polished.
If someone else wants to have a go, the floor is yours!
