### ISSUE TITLE
Suggestion of properties and items in the Wikibase schema builder sometimes totally refuses to load any suggestions (or only wrong ones)

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#5190]
Sometimes, item and property suggestion in the Wikibase extension's schema builder simply refuses to work (refusing to provide any suggestions at all, or only wrong suggestions), making schema building quite painful.

This issue is difficult to reproduce - I have seen the behavior quite often but haven't discovered a pattern in it. I was recently creating a screen recording while it happened badly and [you can see it happening in this video](https://drive.google.com/file/d/1g0g2SsbVKAMJk70vawf-swkkBtFLiz2N/view?usp=sharing). 

Reproducing my process (but I have the idea it doesn't only happen under these circumstances):
* I added what I thought was a wrong statement in the schema builder, deleted the statement, and then tried to recreate it. I wanted the same property but another value. Property (Source of file) simply refuses to load.
* Then you see me fiddling a bit, working on other statements, trying if moving out of the schema builder and back fixes it (it does not)
* Finally I decide to exit my project and go back to OpenRefine's start screen and re-open the project. Then I can add the statement just fine and the suggester does its job.

Unfortunately I didn't have the Terminal running, so I don't have a log of what happened.

This issue has been reported on Wikimedia's OpenRefine Telegram group as well.

### Expected Behavior
Properties and items display correctly and promptly.

### Versions
 - Operating System: MacOS 12.5
 - Browser Version: Something probably right before Chrome 104.0.5112.79 (Official Build) (x86_64)
 - JRE or JDK Version: n/a?
 - OpenRefine: 3.7 snapshot release of 13 August 2022

**Comment by wetneb** [comment]
I have also experienced this and it seems related to caching. Refreshing the page flushes that cache and then the auto-completion should work again after that.
I would like to understand the problem fully but disabling this caching should be a workaround.

**Comment by j-sal** [comment]
I have also experienced this in the Commons Extension category suggestion service.

After typing the first few letters of a category, i.e "dog", and selecting a category from the suggestions, i.e "dog breeds"
![image](https://user-images.githubusercontent.com/26920450/194849594-397b5932-8ffb-42e3-aaf2-685ff1c28f64.png)

If that category is removed, and then the same initial letters are re-typed, the suggestions no longer load any options
![image](https://user-images.githubusercontent.com/26920450/194849987-cb45bdb5-bfa6-4b08-94a5-e548860dcb22.png)
