### ISSUE TITLE
Commons reconciliation: Guess Types query failed error : java.io.IOException: HTTP error 400 : BAD REQUEST for URL /en/api

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#5193]
**Context:** This error message appears in [one specific project](https://drive.google.com/file/d/177HfAeQjxOSz8AiANeSqE7IJtarZ8RPU/view) provided to me by a user who tried uploading files to Commons [using the Google doc instructions](https://docs.google.com/document/d/19eiMeq3XssiPrT9b04E-8XyE-desBEzYNgygLDYKP4o/edit) I wrote; I have tried to reproduce it in another project of my own and the error does not occur there (Commons reconciliation works fine). Maybe this needs to be reported on Phabricator and not here - it's unclear to me on which side the error is produced.

### To Reproduce
1. Import the OpenRefine project linked above
2. Reconcile Name column against Commons reconciliation service

### Current Results
Reconciliation fails, and there is an error message saying `Guess Types query failed error : java.io.IOException: HTTP error 400 : BAD REQUEST for URL /en/api`

I get the following in my Terminal logs:
```
14:41:33.400 [                   refine] GET /command/core/get-preference (17ms)
14:41:33.428 [                   refine] GET /command/core/get-csrf-token (28ms)
14:41:33.450 [                   refine] POST /command/wikidata/preview-wikibase-schema (22ms)
14:41:39.850 [                   refine] GET /command/core/get-csrf-token (6400ms)
14:41:39.875 [                   refine] POST /command/core/guess-types-of-column (25ms)
14:41:40.639 [                  command] Failed to guess cell types for load
{"q1":{"query":"Grapes_testing batch.jpg","limit":3},"q2":{"query":"Grapes_testing batch 02.jpg","limit":3},"q3":{"query":"Unidentified Mentha‎_testing batch.jpg","limit":3},"q4":{"query":"Gazania rigens_testing batch.jpg","limit":3},"q0":{"query":"Red Hibiscus flowers‎_testing batch.jpg","limit":3}} (764ms)
14:41:40.639 [                  command] Exception caught (0ms)
```

### Expected Behavior
Reconciliation works correctly

### Versions
 - OpenRefine: Version 3.7-SNAPSHOT [009eba8]
 - Browser: Chrome 104.0.5112.101 (Official Build) (x86_64)

**Comment by wetneb** [comment]
That should ideally be a Phabricator ticket filed against the commons-recon-service project.

**Comment by trnstlntk** [comment]
> That should ideally be a Phabricator ticket filed against the commons-recon-service project.

Moved it there now, so closing the issue here. 👉 https://phabricator.wikimedia.org/T315569
