### ISSUE TITLE
Ability to extract 'Name-like' strings from a comparatively larger string

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#52]
_Original author: AndrewOf...@gmail.com (May 20, 2010 15:17:40)_

I'm not sure the extent to which this is possible, I've only looked into this kind of thing very briefly, 
but here goes.

Sometimes you'll have a blob of text with a few names in it, it'd be useful to be able to automatically 
extract these names using some kind of fancy natural language processing.

I don't anticipate this being a perfect system, but I imagine that once you've got a list of potential 
names from all your rows you could use the clustering tools to confirm/reject individual names.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=52_
##

**Comment by ultrageek** [comment]
There is a Natural Language Processing package for Java, OpenNLP, similar to the NLTK (Natural Language Tool Kit) in Python. I'm not sure if it has noun extraction, but here is the link: https://opennlp.apache.org/. The description used to have the word "Java" in it, so I presume it still is. Here's another link for some example Java code to use OpenNLP: http://stackoverflow.com/questions/5836148/how-to-use-opennlp-with-java

**Comment by ultrageek** [comment]
In addition to what I mentioned in my other comment, here's a list of NLP packages (many in Java) than might come in handy: http://www.quora.com/What-are-good-alternatives-to-NLTK

**Comment by tfmorris** [comment]
So, this discussion started back in 2010 and the state of the art has obviously moved on since then, but I believe it's something that's still of interest to the users of OpenRefine.

As @dfhuynh  mentioned in his May, 2010 comment, the "best" algorithms depend on the length of the target text, the domain, and a number of other factors.  OpenNLP, as well as more recent projects like cTAKES, might provide useful starting point.

At this point, this isn't something the core team has the bandwidth to be able to advance effectively, but if someone were to define a use case, research the best alternatives, implement one of them, and submit a pull request, we'd receive it very favorably.

**Comment by ettorerizza** [comment]
I'm just working on extracting "name like" from very short texts (eg "Thad Guidry New York 2016") and I can say that it is very difficult... I would be delighted that Open Refine has a function to extract names, but I also know that it will work very badly depending on the length of the text or the language. Adding such a function that would work once in five, I think, would frustrate many users.

**Comment by thadguidry** [comment]
This is solved already quite easily now in 2017+.  Here's how...

@ettorerizza Most folks just use a Apache Stanbol - Docker image and send a Fetch URLs command to the Stanbol Socket URL endpoint.  https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=stanbol&starCount=0

Here's one that works for your use case I would think quite well. Even though its Drupal mention, its the same use case...provide a string of tags or entities extracted from some larger text string.
https://www.drupal.org/project/auto_recommended_tags

Here's some docs to get started once you have your instance running from Docker... https://stanbol.apache.org/docs/trunk/enhancementusage.html

If someone really wants tighter integration with OpenRefine, then an Apache Stanbol extension could be made (running in same Jetty instance on different port than OpenRefine)  They could also provide a Wikidata enhancement chaining as a default package.  Actually, I think someone has already wrote that enhancement somewhere if I recall, perhaps a Wikidata dev already or some Github project.

**Comment by ettorerizza** [comment]
>  I think someone has already wrote that enhancement somewhere if I recall

The Deri's RDF extension, but never tried.

![sans titre 1](https://user-images.githubusercontent.com/6286410/28998399-7043497a-7a2a-11e7-85bb-fb59be3f23a9.jpg)

**Comment by thadguidry** [comment]
@ettorerizza Ah yeah, that's the one :)

**Comment by ostephens** [comment]
See also the 'Named Entity Recognition' extension from 'Free Your Metadata' https://github.com/RubenVerborgh/Refine-NER-Extension

**Comment by thadguidry** [comment]
@ostephens Yes there are extensions to OpenRefine that handle this.  Closing this issue.
