### ISSUE TITLE
Embed donation box (or prompt) in new release pages

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#5204]
I'd like to embed donation forms in various places in OpenRefine's web presence - mainly near the places where our users usually download the software.
Donations will always be optional - but the project can really use them to pay for day-to-day maintenance work (e.g. packaging) which is not easily funded through grants. Quite a lot of open source projects show donation boxes / forms right next to, or right after, downloading the software, and I'd like to give that a try here too.

I was looking whether it'd be possible to embed such a donation box into our releases pages, like [this one](https://github.com/OpenRefine/OpenRefine/releases/tag/3.6.0), but I couldn't really figure out how to do it. I forked the OpenRefine repo but then could not find where to edit/update this page. Could someone look into this?

Ideally, for maximum visibility, the donation box would be under the Download header, right below the four download links for the different OSes.

I have an embed code for the donation box. It's an iframe html code, provided through Donorbox. Our fiscal sponsor, Code for Science & Society, also [embedded it here](https://codeforscience.org/donate/openrefine/) - but that page is not very visible. I'm not sure if it's safe to post the embed code publicly here, but please ping me and I can give it to anyone who feels like tackling this.

### Alternatives considered
I think it would be great if we actually dedicate a bit more attention and planning, and perhaps even some A/B testing, to arrive at a donation 'path' online which is nice to our users and also encourages people to actually donate. I saw that some open source projects send the downloader to a new page with dedicated donation options right after they clicked a download link. I think that's even more effective: in that case, the user first downloads, and then (while the software is downloading) can use the waiting time to donate. If we just show a donation box below the download links, it may be missed, and/or the user may forget about the possibility because they immediately jump to the downloaded software.

**Comment by trnstlntk** [comment]
The page you get right after downloading LibreOffice - I think it's nice, friendly, not too obtrusive, but still encouraging.
![image](https://user-images.githubusercontent.com/9881645/185951979-a3398776-d0d8-464f-93a2-0bd2ea02d5c3.png)

**Comment by thadguidry** [comment]
👍 agree on donation page shown when users have clicked on one of the 3 links (Win, Mac, Linux) to download OpenRefine.  Mimicking something like LibreOffice has would be great.  Ideally that donation page should be very simple and clear and not messy with lots of text; make it simple for the user to click and send a donation.  I think the prototype donorbox page that Jess showed one time was that kind of simple and I really liked it and felt comfortable interacting with it...so simple!

**Comment by trnstlntk** [comment]
That nice page may have been this one: https://codeforscience.org/donate/openrefine/

Agree on simple and clear.

**Comment by thadguidry** [comment]
@trnstlntk Can you grab the text and ideas out of this issue and open an new issue in our Github pages website repo instead?  or maybe add it as part of the Download experience in https://github.com/OpenRefine/openrefine.github.com/issues/55

I'll close out this issue as we don't think the releases page (or our CI) needs to change for this kind of support.
