### ISSUE TITLE
Cluster and edit display issues

### ISSUE THREAD

**Issue by elebitzero** [OpenRefine/OpenRefine#5210]
When performing cluster and edit on a big enough dataset, some items are pushed out of the dialog and squished.

### Current Results
![image](https://user-images.githubusercontent.com/42903164/186571435-be1adf0e-b734-416f-9149-58791c5d9db7.png)

### Expected Behavior
The contents should fit in the dialog and be laid out properly.

**Comment by thadguidry** [comment]
There's a lot of options here.
1. do we make the right hand side with sliders larger to allow more slider room by default?
2. Thereby moving the right hand side of table with scrollbars to be a smaller table and let users with long string use the scrollbars more?
3. A little of both?

**Comment by wetneb** [comment]
This is a long term and very annoying issue, thanks for tackling it @elebitzero, I am sure you will come up with something great :)
