### ISSUE TITLE
Memory usage display issues when creating project

### ISSUE THREAD

**Issue by elebitzero** [OpenRefine/OpenRefine#5218]
I was creating a project from a 35MB CSV file and I noticed that the progress bar showing the memory usage had some issues:

- The max memory showed as 4294MB but my max memory was set to 4096MB in refine.ini

- The used memory stayed constant at 1728MB which seemed off. I checked ImportingJob.java and found that the used memory was being set as the total JVM memory when it should be total - free memory.

![java-memory-before](https://user-images.githubusercontent.com/42903164/187200498-ee38b01d-3a9f-445d-a384-d4609856e3c0.gif)

**Comment by tfmorris** [comment]
> * The max memory showed as 4294MB but my max memory was set to 4096MB in refine.ini

Likely a 10^6 vs 2^20 issue.

> * The used memory stayed constant at 1728MB which seemed off. I checked ImportingJob.java and found that the used memory was being set as the total JVM memory when it should be total - free memory.

I guess that depends on what you're trying to measure. The JVM has "total memory" allocated which means it is unavailable for any other process (e.g. the browser) to allocate. The fact that it isn't actively using the allocated memory doesn't make it any more available to anyone else.

**Comment by elebitzero** [comment]
The text says 'Memory usage', so my interpretation is the user would expect to see the memory in use, so we shouldn't include the portion of the total memory that is not in use. If total-free is close to max memory, that is a sufficient indicator of OOM.

The refine.ini file has the default min and max set to 1400M. As a result of this, the memory usage appears to be at 100% immediately which in a way is correct as in the JVM has reserved that memory as you mentioned. On the other hand, it is deceiving because a lot of that reserved memory may be free:

![java-memory-1400M](https://user-images.githubusercontent.com/42903164/187372458-f116c13b-ede2-4296-9fc2-4ed4e0067fda.gif)
