### ISSUE TITLE
Ship Commons manifest with OpenRefine by default

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#5220]
I notice that it takes quite a bit of explanation/documentation to help people install the [Wikimedia Commons manifest](https://github.com/OpenRefine/wikibase-manifests/blob/master/wikimedia-commons-manifest.json) in OpenRefine if they want to get started editing or uploading there. Could we perhaps have this manifest pre-installed for every OpenRefine user, just like Wikidata's? Seeing that Wikimedia Commons is a Wikimedia wiki, i.e. a public one that anyone can edit (and re-use files from). 

### Alternatives considered
Also totally OK to not do this. Or, alternatively, have the Wikimedia Commons manifest shipped in the Wikimedia Commons extension (but not in OpenRefine itself).

**Comment by Abbe98** [comment]
Could the Wikibase extension fetch manifests from the manifest repository and allow you to search for the one you need?

Wikidata could be there by default but other ones behind a search box, lowering the barrier for all who's target instance is registered in the repository.

**Comment by wetneb** [comment]
I would say why not! But I think this opens up quite a few design issues that I would not rush.

Mostly, do we want to directly query GitHub to get the contents of the manifest repository? Perhaps there are other hosting solutions we could consider? As soon as we start baking it into the tool, it is a pretty strong commitment (we cannot update the URL of the repository without releasing a new version).

The same question can be asked for
* a catalogue of reconciliation services
* a catalogue of OpenRefine extensions

**Comment by trnstlntk** [comment]
The above two comments broaden the discussion quite a bit, while my ask in this issue is just focused on the Commons manifest. I suggest to create separate issues for figuring out solutions re public "catalogs" of manifests, recon services, extensions... and would appreciate input here re: the specific Commons manifest inclusion request.
