### ISSUE TITLE
"Error: We need either 'curl' or 'wget' present" error is misleading

### ISSUE THREAD

**Issue by frafra** [OpenRefine/OpenRefine#5240]
refine checks for `curl` or `wget` using `which`. Such test fails if `which` is not installed.

https://github.com/OpenRefine/OpenRefine/blob/abab670399924daf2222b366e078b758f6192d80/refine#L121-L122

**Comment by PhilipVigus** [comment]
I'm happy to take a look at this one

**Comment by PhilipVigus** [comment]
So, some thoughts on this. I have a number of approaches...
1. Just update the error message to make it clear that `which` might be one of the commands that's missing
2. Do an individual check against the `which` command with its own error message before the command is used. This would probably make use of something like `command -v`
3. Rework it to not use `which` at all. There seems to be quite a strong sentiment that it's not ideal to use, eg https://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then. Not sure how much to take notice of arguments like this. As with the previous point, I'd probably replace it with `command -v`. However, I'm not familiar enough with bash scripting to know whether `command` is generally more available so would reduce the occasions that the script would fail, or whether it would introduce other issues.
4. Do something that tries to use `which`, and if that fails then tries `command`. If both fail then it errors

Also, looking through the script, it looks like which is used in quite a few other places, so I think it makes sense to change those instances as well as the one highlighted specifically in this PR. The fact that this significantly increases the places that code needs to change is also a factor in choosing an approach above.

Any thoughts?

**Comment by PhilipVigus** [comment]
Yep, I agree with all your comments. I'll implement number 3
