### ISSUE TITLE
Don't require modify access to OpenRefine directory

### ISSUE THREAD

**Issue by teknowledgist** [OpenRefine/OpenRefine#5247]
I would like to be able to "install" OpenRefine to a machine such that all users can run it without affecting other users.  Think:  classroom.

Currently, when OpenRefine is unpacked into a directory to which users have read/execute rights, it will not open.  Thus, either OpenRefine has to be placed in a directory where all users have modify rights (which is a security problem) or each and every user has to download and unpack their own copy each of which takes almost 300MB of space.  

The confusing piece of this is that the software is already user-profile-aware in that the workspace is created in the user profile.  Why then would it also want modify rights to the program directory?

### Proposed solution
Make OpenRefine treat it's directory location as read-only and never try to write to it (or even test for modify rights).  If there are changes to be made to files within that directory, they must be altered through other means outside of OpenRefine.  All settings and default data locations should be within the user profile.

### Alternatives considered
There are no alternatives.  This is just proper, well-behaved application design.

**Comment by wetneb** [comment]
I am surprised that the write privilege is required and agree with your assessment that it should not be necessary. Which operating system did you encounter this issue on?

**Comment by teknowledgist** [comment]
Windows 10.  I am maintaining a [Chocolatey package for OpenRefine](https://community.chocolatey.org/packages/openrefine) (that clearly isn't used much), and deploying it to some managed systems.  Somehow I missed that attempting to start the openrefine.exe fires up a UAC prompt because the location is not writable by unprivileged users, which means they can't run it as "installed".

**Comment by thadguidry** [comment]
You will need to modify the Windows registry first to allow OpenRefine.exe as allowed to bypass UAC upon installing.  There are some MS technet guides to help you administer this across a managed network of Windows PCs. (A custom script in PowerShell can do the Registry modification needed.)

**Comment by teknowledgist** [comment]
@thadguidry That feels rather "hacky" and something necessary for old, outdated software to me.  I'm quite familiar with installing software and centrally managing workstations via GPO and/or SCCM, and I haven't encountered other legitimate software that requires bypasses to UAC to run.  

A couple other points about the workaround you are suggesting:  

1. OpenRefine is just unzipped, not installed, so I'm not sure to what you are referring.
2. MS technet was retired years ago, so can you be more explicit where your information comes from (maybe a URL)?

In the end though, I believe this is still a legitimate feature request.  I'd be happy with either a "proper" installer that puts the binaries within `%programfiles%` and OpenRefine can be run by unprivileged users without further tweaks, or I'd be OK with a zip file that can be unpacked to a read-only location so unprivileged users can OpenRefine.

Thanks.

**Comment by thadguidry** [comment]
But can't your chocolatey script install OpenRefine into Program Files and modify the refine.ini to set the data folder path? (We do intend to make a better installer in the future in issue # )

**Comment by teknowledgist** [comment]
I can do all kinds of things with the install script, but I have to know what needs to be done.  Is the "data folder path" the same thing as the "workspace", because that is already within the user profile by default (regardless of where the binaries sit).  

If modifying the `refine.ini` file is all that needs to be done to stop OpenRefine from wanting elevated credentials, great!  I asked in both the gitter forum and the Google Group for assistance to make a "machine-install" of OpenRefine run for unprivileged users, but I got only crickets.  Is there documentation on what to do?  I asked in both the gitter forum and the Google Group for assistance to make a "machine-install" of OpenRefine run for unprivileged users, but I got only crickets.

**Comment by thadguidry** [comment]
The data folder is the same as workspace path.  Besides setting it via the refine.ini, you can set it via the command option and see all options with 'refine /?'

You can place OpenRefine's folder containing it's files and exe in any location that is readable/writable for a user.  We hope to make a portable version of OpenRefine also and have an issue for that.

**Comment by thadguidry** [comment]
The elevated credentials comes from Windows UAC when an exe is called rhat is located in a permissioned system folder like directly C:/ drive etc.  As long as you move OpenRefine's folder to another location then the UAC warning should go away.

**Comment by elebitzero** [comment]
@teknowledgist

This is working fine for me with local non-admin users sharing an OpenRefine install on the local filesystem C:\software on Windows 10 that was installed by the admin.

Windows 10 Pro
OpenRefine 3.6.1 with embedded java (Ref: https://openrefine.org/download)

Installed in C:\software\openrefine-3.6.1 by admin user.
Other non-admin users see this folder as 'read-only', but they can cd into that directory and run 'refine.bat run' and it works!

Please share more info on your setup. Are you on Windows? How are you sharing the OpenRefine installation? Is it using a network share?

**Comment by teknowledgist** [comment]
@elebitzero I'm using the Chocolatey package which does download the embedded Java flavor.  

As is common practice (and I believe recommended) for zipped distribution application packages, the `chocolateyInstall.ps1` script unzips the download into the Chocolatey package folder.  Usually, that within the Chocolatey package library, so for the "openrefine" package, that is, `C:\ProgramData\Chocolatey\Lib\openrefine`.  Hundreds of other similar packages work without issue when expanded to their package folder, and while that doesn't make it correct, it does mean that it is possible for unprivileged users to run binaries from that location.  To compare with another java-based example, the [jmol](https://community.chocolatey.org/packages/jmol) package that I also maintain expands to it's library directory.

@thadguidry If the issue is just that OpenRefine is not signed, then that answers my question and becomes the resolution to this request.  I'll just have to wait for that.

Thanks.

**Comment by elebitzero** [comment]
@teknowledgist

I checked your Chocolatey script and I see that you launch the app using openrefine.exe.  On my setup that works just fine for a non-admin user like `refine.bat run`.

One thing I noticed is that you have added `-RunAsAdmin` flag.  That may not be necessary as OpenRefine doesn't need to run as admin. That could be why you get a UAC prompt when starting OpenRefine.

```
$Target = get-childitem $FolderOfPackage -Filter openrefine.exe -recurse
$StartMenu = Join-Path $env:ProgramData '\Microsoft\Windows\Start Menu\Programs'
$shortcut = Join-Path $StartMenu 'OpenRefine.lnk'
Install-ChocolateyShortcut -ShortcutFilePath $shortcut -TargetPath $Target.FullName -RunAsAdmin
```
