### ISSUE TITLE
ToString test fails when run in a French locale

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5277]
Running the server tests (with `mvn test`) with a `fr_FR.UTF-8` locale currently fails with a
```
ToStringTests.testToString:50 expected [100.0] but found [100,0]
```

This test should pass regardless of the system locale.

**Comment by PhilipVigus** [comment]
So I've started looking into how the code around this works. I think I understand how I want to fix this, but it's raised another query. Looking at the behaviour of toString(), shouldn't this test also be failing with a french locale for the function to be consistent?
```
assertEquals(invoke("toString", Double.valueOf(100.0)), "100.0");
```

**Comment by wetneb** [comment]
The line you are quoting looks very similar to the one that is failing, so if that is not the same line I would say yes! If the two lines are part of the same test method then the first one to get executed should fail, and anything that follows it will not be executed, so will not have a chance to generate another failure.

**Comment by PhilipVigus** [comment]
Based on what you've said, I've confirmed that the function is definitely inconsistent, as the assert raised in this issue fails but the one I highlighted above does not. (I changed my machine's locale to confirm).

I'm brand new to the codebase and so not sure what to do here. The 'right' thing to do here would probably be to fix the toString function to make its behaviour consistent, but I'm concerned about changing the behaviour of a function that is being used in places in a codebase I don't understand.

Is it likely that there are parts of the codebase that rely on the inconsistent behaviour I've identified, and that making the function consistent might break other things?

**Comment by wetneb** [comment]
This `ToString` function is a GREL function, that is, a function that users can use inside the GREL expression language. This is the default scripting language of OpenRefine (think of it like Excel formulae).

Therefore, by changing it, you will likely not "break" anything in OpenRefine itself, but people who have been using this function in their workflows might find that it does not behave like it used to (and this can be quite hard to debug).

There are various opinions in the team about how backwards-compatible we should be about GREL. It generally comes down to a case by case judgment. ToString is a widely used function so it is definitely worth having this concern in mind at least.

I would be inclined to say that the current behaviour of ToString is fine: we want to let the user convert things to strings following their locale, and that is what the function does, so it is great.
Therefore, the problem would lie more in the test suite. We could decide to force it to run in a specific locale (likely en_US), by adding the appropriate arguments to the test runner (likely in the root `pom.xml` file). Or we could adapt the test so that it works regardless of the locale.

Surely there are other sensible ways to approach the problem though!

**Comment by PhilipVigus** [comment]
I went with the least invasive approach in the end. Let me know if I've done anything wrong with the PR :)
