### ISSUE TITLE
Cluster and edit dialog should prevent selecting another algorithm while processing a different one

### ISSUE THREAD

**Issue by elebitzero** [OpenRefine/OpenRefine#5283]
In the 'Cluster and edit' dialog, when a user selects another algorithm to run while one is still processing, OpenRefine will run both algorithms at once and the results of the algorithm that finishes last will be displayed over the results of the first as shown in the recording below.

Because it is difficult to tell which results go to each of the selected algorithms this problem leads to confusion and delay. Moreover, OpenRefine is using more memory so the algorithms will take longer to process.

### To Reproduce
1. Go to 'Edit cells' > 'Cluster and edit...'
2. Select a 'Keying function' that has results.
3. Switch to a function that has results that takes enough time.
4. Switch back to the original function while the previous is running.
5. Observe that the results of the function that finished first is replaced by the one that finished last.

### Current Results
![Cluster and edit multiple algorithms switch](https://user-images.githubusercontent.com/42903164/191894042-da88e742-1819-4b64-ab39-5069d997be52.gif)

### Expected Behavior
The dialog should prevent switching to another algorithm while one is running by blocking input with an overlay, or adding a cancel button if the operation is cancelable.

**Comment by wetneb** [comment]
Somewhat related to #289
