### ISSUE TITLE
Add new GREL function capitalLettersExtract()

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#5316]
I often have the same need as Kew Royal Botanical Gardens to extract only capital letters and then optionally trim any remaining whitespace and do it simply.  https://github.com/RBGKew/String-Transformers

```
	@Test
	public void testSimple() {
		assertEquals("K G", transformer.transform("Kew Gardens"));
		assertEquals("TW AE", transformer.transform("TW9 3AE"));
	}
```

### Proposed solution
it would be nice to see this functionality builtin as a new GREL function perhaps called `capitalLettersExtract()` or `extractUppercase()` for simplicity.

GREL:
`"Kew Gardens".extractUppercase().trim()`

OUTPUT:
`KG`

### Alternatives considered
Clojure/Python library with GREL or the existing way with a custom GREL script that uses Regex that I hate typing all the time after the last 13 years.

`"Kew Gardens".replace(/[^A-Z]/,'').trim()`

**Comment by ostephens** [comment]
Another alternative (and simpler from a code perspective) would be to add this to the list of common transformations in the edit cells menu

**Comment by thadguidry** [comment]
Ah, yeah, but need both at times, the GREL function and usability in the commons transformations menu.

**Comment by ostephens** [comment]
My only concern with adding a GREL function for something like this is that it's a very specific function - and adding GREL functions at this level of granularity could lead to GREL being very extensive.

Just trying to understand the requirement more - can you give examples of why you need this? (the Kew example seems to be in the line of creating a key for some expected name/title)

**Comment by thadguidry** [comment]
Many examples come up in real life... abbreviations, persons initials, etc.
"Thad Michael Guidry" = "TMG"
"Museum of Modern Art" = "MMA"  <--fail
"American National Standards Institute" = "ANSI"

I think the function would be better than also placing in the commons menu for now.
It's more widely useful programmatically with other GREL functions.

**Comment by ostephens** [comment]
Sure - but why do you want to convert "Thad Michael Guidry" to "TMG"? What's the purpose of that change

**Comment by thadguidry** [comment]
the use case is more driven in science and math domains.
The generic way of framing it, it's simply extract capital letters (find patterns - which we have regex for - and the common complaint that it's sometimes unwieldy).  
So find() ?
And we make find() more syntax friendly without using regex?  That seems harder a mountain to climb?
The generic problem is simply that, I have common functions that I need stored to be called upon, we call them macros before, but we didn't implement support for that yet, but was always in the plan, along with custom macros functions being added to a custom menu for easy access.  The Starred expressions dialog is abysmally antiquated and was a first pass on quickly doing a customized menu by David and I.

**Comment by thadguidry** [comment]
@ostephens I just had a thought...maybe it's easier to just work MORE on Starred expressions dialog...giving it a facelift where we can tag expressions and have a tag filter?  that might be easier (and in my case more useful) than the custom menu on columns.

**Comment by ostephens** [comment]
Sorry - my intention wasn't to shut down discussion but try to understand the issue.

I completely agree that this seems like an ideal situation where being able to write a macro/shortcut to a more complex GREL
Looking at the Kew Gardens work they seem to have several string transformations they supported in the same class:
* CapitalLettersExtractor
* RemoveBracketedTextTransformer
* FakeHybridSignCleaner
* StripNonNumericCharactersTransformer

I was wondering about something more like a named transformation in this way that could be used with GREL like:
value.transformer("name of transformation")

I could see this working ... but I'm not sure it's a bit improvement on what you are currently having to do, and certainly seems less good than a macro

**Comment by thadguidry** [comment]
the macro idea was something of a new macro call syntax, say `$.mymacro` with prefixing of `$.` but again, we never dived into it fully how it might be implemented and I recall David saying something about parsing issues within eval calls with `$` at the time of Gridworks, but he probably fixed them and we never looked back into macros.

**Comment by thadguidry** [comment]
and this issue is a clear indication of why we needed Discourse setup!  :-)
