### ISSUE TITLE
UI edits to schema selection and edits saving in Wikibase extension

### ISSUE THREAD

**Issue by lozanaross** [OpenRefine/OpenRefine#5346]
This has been mentioned in previous PRs and issues, but starting a new issue to track all the final adjustments needed in more detail. This is a request to improve the following UI features:
<img width="1025" alt="Screenshot 2022-10-16 at 21 45 24" src="https://user-images.githubusercontent.com/25489750/196059745-f935c4d5-a547-4af1-b946-8851c431fa8e.png">

1. I think this text is not needed - it's too clunky in the layout; it's information experienced users know and don't need to see at all times; it's also something new users should learn from tutorials / documentation; new users (as shown during user testing) tend not to read small text anyway, and just click around until they find the solution to go forth, or just go and watch a tutorial;
2. Save schema should be called "Save schema progress".
3. Save schema progress / Discard changes should move below the main schema editing area (see wireframes).
4. This should probably just say "Select..."
5. "Save new" is potentially confusing if users just want to save and override an existing schema. Another idea was to keep the button to say only "Save", but I think this will make it potentially confusing next to the dropdown in case users decide they are just saving their selection choice. I propose we call this button "Save schema edits" and we move it to the right of the screen (see wireframes). 

### Proposed solution
Proposed redesign:
<img width="1064" alt="Screenshot 2022-10-16 at 23 59 48" src="https://user-images.githubusercontent.com/25489750/196060312-3ab0d35c-76dc-44ac-aca2-a05112b969e7.png">

For more context see complete design wireframes accessible via this link: https://docs.google.com/document/d/1uWkrid1UJwM3FCak_fI4VUY2EUabVUUFk9z6OeWtzKs/edit?usp=sharing

### Alternatives considered
Several previous iterations can be seen in the wireframe versions in the link above. The naming of the "Save" button and the schema vs schema template was discussed in more detail in previous PRs, e.g. https://github.com/OpenRefine/OpenRefine/pull/5303

### Additional context
The need to adjust this was discussed during the final round of user testing for the Commons extension project carried out Sept / Oct 2022.

**Comment by wetneb** [comment]
This issue is already a design proposal on its own, so I do not think there is much left to design @OloladeOdus. Perhaps it is worth picking another issue where the desired behaviour and appearance is not clear yet?
