### ISSUE TITLE
Speculative suggestion for new Upload tab in Wikibase extension

### ISSUE THREAD

**Issue by lozanaross** [OpenRefine/OpenRefine#5348]
During user testing and development of the SDC (Structured Data on Commons) extension, the question of how opaque the upload process is came up multiple times both in internal meetings and when discussing with users. Perhaps a solution could be to introduce a final step in the Upload process that includes a tab (next to Issues / Preview) and makes the edits upload log visible to users. Not sure how much the log data can actually be transferred into meaningful instructions for users, but proposing something quite speculative below (with dummy text in the error log), it can hopefully be improved and iterated upon by a community discussion via comments here. 

### Proposed solution
**Step 1:** User selects the option to upload and fills out the existing dialog options:
<img width="797" alt="Screenshot 2022-10-17 at 00 28 36" src="https://user-images.githubusercontent.com/25489750/196061480-35d8b449-3f11-4beb-a343-9a3e255beee3.png">

**Step 2:** After upload starts, the log can be seen in the Upload tab (before Step 1 the log is empty just like Preview is empty before a schema is completed):
<img width="798" alt="Screenshot 2022-10-17 at 00 28 47" src="https://user-images.githubusercontent.com/25489750/196061505-a3709e24-dbce-442e-acce-41c93929b45e.png">
(Options to pause / continue or even cancel the upload would be nice, but not essential if too difficult to implement.)

**Step 3:** Upload is complete and user gets that feedback also via the tab:
<img width="798" alt="Screenshot 2022-10-17 at 00 34 53" src="https://user-images.githubusercontent.com/25489750/196061682-f1f00ade-32c3-4e31-be49-d9e3d91e4c4b.png">

For more context see complete design wireframes accessible via this link: https://docs.google.com/document/d/1uWkrid1UJwM3FCak_fI4VUY2EUabVUUFk9z6OeWtzKs/edit?usp=sharing

### Alternatives considered
Nothing changes, we leave upload process opaque, but major errors are flagged via pop-ups that interrupt the usual upload status yellow bar.

### Additional context
N/A

**Comment by wetneb** [comment]
This was also my preferred approach for some time, but with the experience of some architectural changes in 4.0, I realized that it would actually be not so hard to link each edit to a row which generated it. This means that the successes/errors could be reported in the grid. I have added some more details about this approach in this thread:
https://forum.openrefine.org/t/partial-results-of-long-running-operations/482

The main advantages would be that it would let people filter based on upload status (sucess/failure), see the corresponding error messages in the grid, and retry failed edits more easily.

**Comment by lozanaross** [comment]
Yes, I saw this in the Forum, it does look like a much better approach. Shall I close this issue then and we can open a new issue for a design discussion around the 4.0 architecture.

**Comment by lozanaross** [comment]
@Ebere330 this issue is already closed, there is no work needed here.

**Comment by Ebere330** [comment]
Thank you for your response. I have done the mockup for the github issue
assigned to me earlier on. I tagged you to it. Can you please review and
give feedback?
Thank you very much.
