### ISSUE TITLE
Make multi-line "edit cell dialog" larger if it contains more text and if user's screen resolution can handle it

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#5349]
When editing individual cells with quite a bit of text, I end up dragging the little 'enlargement corner' in the "edit cell" dialog all the time, which is not fun. I think, today, many user's screen resolution can totally deal with a slightly larger dialog window. Perhaps even one that flexibly adapts a bit to the length of text in it.

<img width="539" alt="image" src="https://user-images.githubusercontent.com/9881645/196239811-71405d75-5a03-4bd8-a3e0-3efd60dfd470.png">

versus

<img width="549" alt="image" src="https://user-images.githubusercontent.com/9881645/196239912-33477083-9b98-43a1-94cc-03529a34a126.png">

**Comment by thadguidry** [comment]
@trnstlntk Looks like you made it about 30% larger, are you suggesting to have the edit cell dialog to autosize up to 30% larger when necessary to fit text?  What would be a good maximim autosize for horizontal as well as vertical, in your opinion, considering some use laptops with 14in - 15in (381mm) screens?  Perhaps we can come to some agreement on allowing autosizing % percentage against the screen size available and leave maximally 30% bordering all around the browser screen?  That way it will be somewhat consistent across all screen resolutions?

**Comment by thadguidry** [comment]
After a little research and asking friends, it seems we might best go with a simple tried and true Jquery plugin to quickly accomodate your needs.  Try it out:  http://www.jacklmoore.com/autosize/

**Comment by trnstlntk** [comment]
I use a 15 inch laptop, and my previous one was 14 inch. In both cases the screen would very easily accommodate a (much) larger input box. When the user clicks 'edit' it means they are indeed interested in ... editing, and I think it's OK if a popup then takes up quite a bit of screen real estate; as long as the buttons at the bottom remain accessible.

Re actual sizing, percentages, maximums ... this would typically be an area where I'd appreciate professional input from a trained UX designer, who is aware and experienced in typical user behavior, user needs, and common UX patterns in today's web applications.

**Comment by trnstlntk** [comment]
I added the accessibility label, mainly because I have a hunch this also affects that aspect of our UI.
