### ISSUE TITLE
No issues notification circle for Entity problems such as missing description or subject item id

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#5358]
We don't show a notification circle number next to the issues tab in the Schema view for Entity problems that result in the schema being incomplete.

### To Reproduce
1. Use Clipboard importer in OpenRefine and copy and paste the following simple 2 row example dataset

| A | B | C |
| - | - | - |
| 1 | 2 | 3 |
| 4 | 5 | 6 |

2. Click **Create Project**
3. Click on **Wikidata Extension**  -> **Edit Wikibase Schema**
4. Click **Add item** button
5. On Terms click **add term** link
6. From dropdown change Alias to Description but do not type anything into boxes.
7. On top header, click on **Issues** tab to ensure there are 2 issues reported for the empty entity.

### Current Results

No notification circle is shown on the Issues tab for the count of 2 issues.

### Expected Behavior

The issues tab should show the notification circle with number 2 signifying 2 issues are reported under the tab.

### Screenshots
No number is shown on the issues tab 

![image](https://user-images.githubusercontent.com/986438/196829255-803f79b7-aff7-4fe0-bb60-71dc863b388b.png)

However, when the issues tab is clicked, you can see 2 entity issues do exist

![image](https://user-images.githubusercontent.com/986438/196830116-9c339fe1-2ce0-4684-bd33-9ab1cc109353.png)

I expected to see a number 2 next to the issues tab as in this example:

![image](https://user-images.githubusercontent.com/986438/196829884-781e762c-6b34-4a1c-a40a-51c22d84594c.png)

### Versions
 - Operating System: Windows 11
 - Browser Version: Edge latest
 - JRE or JDK Version: embedded in OpenRefine
 - OpenRefine: Version 3.7-SNAPSHOT [ea70840]

**Comment by Howard0115439** [comment]
I would like to work on this issue, could you assign it to me?

**Comment by SoniaSun810** [comment]
Hey @thadguidry! Before we delve into this issue, could we clarify the following points:
1. When there is no issue, we expect to see the absence of a numerical indicator next to the `issues` tab, or the number `0` next to the `issues` tab. 
2. Could this possibly be another bug? Upon initially opening the project, when there is no issue, it displays a "1" next the tab.
<img width="846" alt="Screenshot 2023-05-18 at 18 18 46" src="https://github.com/OpenRefine/OpenRefine/assets/109137919/a6775a68-b348-422c-8bf6-f996a0093c08">

Thank you!

**Comment by Howard0115439** [comment]
Hello @wetneb! My teammate, @SoniaSun810, and I are working together on this task, and I will let her to submit the pull request. We have a query regarding whether it is necessary to include a test case for the code fixing issue, as we were unable to locate any existing test case for testing the `wikibase-schema.js`.

**Comment by wetneb** [comment]
Yes indeeded we are lacking tests for this, I think it is okay not to add a new one for your change.
