### ISSUE TITLE
Windows refine.bat needs to be updated for new arguments matching Linux refine script

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#5359]
Windows refine script arguments `/d` and `/x` no longer match the Linux refine script and causes confusion for those that maintain across both OS's.

We introduced a few new arguments in the Linux refine script over the last couple of years

- `-d <path> path to the data directory`
- `-x <name=value> additional configuration parameters to pass to OpenRefine`
- `-v <level> verbosity level [from low to high: error,warn,info,debug,trace]`

and replaced two with different arguments (which should no longer are `/d` and `/x` as above but instead mimic the Linux refine script as

- `--debug enable JVM debugging (on port 8000)`
- `--jmx enable JMX monitoring (for jconsole and jvisualvm)`

### To Reproduce
1. Start OpenRefine from Cmd Prompt with `refine /d "D:\myOpenRefineWorkspace\"`
2. Notice that log output does not show the data directory being set but instead JVM debugging is enabled

### Current Results
`refine.bat /?` is not consistent with the output from Linux with `./refine -h`

### Expected Behavior
both startup scripts should provide identical arguments, except for differences in shell syntax.
Additionally, `/debug` and `/jmx` should be the corresponding argument syntax in `refine.bat`.
We should also update our user documentation pages where necessary for Windows to reflect the updated arguments.

### Versions
 - Operating System: Windows 11
 - Browser Version: Edge latest
 - JRE or JDK Version: JDK 11
 - OpenRefine:  Version 3.7-SNAPSHOT [ea70840]

**Comment by bhati00** [comment]
hello Sir,
 i've recently learnt the java and developed some rest-APIs , can you guide me how can i contribute to this project , i'm just at beginner level and i've never worked real world problems but i do know basic things of development.
