### ISSUE TITLE
Rows are counted only after the project is opened

### ISSUE THREAD

**Issue by frafra** [OpenRefine/OpenRefine#5387]
### To Reproduce
1. First, upload a file via API
2. Then, open the projects' list

### Current Results
`Rows` column shows 0 rows.

### Expected Behavior
Rows should be displayed.

### Versions
 - Operating System: Linux
 - Browser Version: Firefox
 - JRE or JDK Version: OpenJDK Runtime Environment 17.0.4+8-nixos
 - OpenRefine: 3.6.2 and 3.6.1

### Additional context
Opening the project link updates the `rows` column.

Workaround: GET request toward `/command/core/get-rows?project=PROJECT&start=0&limit=0`.

**Comment by tfmorris** [comment]
The API is for internal use only, so you're going to find all kinds of rough edges like this. The web UI does exactly what your workaround suggests - open the project and show it to the user.

Having said that, the project should have an accurate row count after its imported, which could be used to update whatever separate field is storing this particular row count.
