### ISSUE TITLE
SQL export does not put quote around column names

### ISSUE THREAD

**Issue by frafra** [OpenRefine/OpenRefine#5388]
### To Reproduce
1. Export project as SQL

### Current Results
Column names are not quoted. If a column is named `Plot`, `Plot VARCHAR(255) NULL,` will be printed. Creating such table in Postgres would result in a lowercase `plot` column, if the column name is not quoted.

### Expected Behavior
Column names should be quoted always or when needed.

### Versions
 - Operating System: Linux
 - Browser Version: Firefox
 - JRE or JDK Version: OpenJDK Runtime Environment 17.0.4+8-nixos
 - OpenRefine: 3.6.2

**Comment by wetneb** [comment]
Looks like this is a follow up on #1940 where we did not quite get the fix right!

**Comment by davidcardd1** [comment]
I'd like to work on this issue, as I'm starting to contribute to Open Source projects. Could I get this issue assigned to me?

**Comment by wetneb** [comment]
Thanks for volunteering, the floor is yours!

**Comment by wetneb** [comment]
Sadly PR #5674 had test failures so I had to revert it. This issue can still be tackled.

**Comment by mahika2** [comment]
I'd like to work on this issue, as I'm starting to contribute to Open Source projects. Could I get this issue assigned to me?
