### ISSUE TITLE
Help for select() has parameter order backwards

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#5394]
The help text for the GREL `select()` function has the parameter order backwards. I haven't checked, but I wouldn't be surprised if the error propagated to the user manual.

### Current Results

> select | (string s, element e)

### Expected Behavior

select | (element e, string s)

### Versions

 - OpenRefine: 3.6.2

**Comment by haseeb-xd** [comment]
I wanna work on this. I just have to set the order of parameters right?

**Comment by thadguidry** [comment]
@tfmorris The return snippet also needs a tweak, no?  It returns either Jsoup Elements or String depending on 2nd argument?

https://github.com/OpenRefine/OpenRefine/blob/3d8de572f7e6bbc3e8f4bceed634d6f091dc8ed8/main/src/com/google/refine/expr/functions/xml/SelectXml.java#L53-L56

https://github.com/OpenRefine/OpenRefine/blob/3d8de572f7e6bbc3e8f4bceed634d6f091dc8ed8/main/src/com/google/refine/expr/functions/xml/SelectXml.java#L77-L79

**Comment by thadguidry** [comment]
@haseeb-xd https://github.com/OpenRefine/OpenRefine/blob/3d8de572f7e6bbc3e8f4bceed634d6f091dc8ed8/main/src/com/google/refine/expr/functions/xml/SelectXml.java#L49-L56
