### ISSUE TITLE
Error uploading data no protocol: when there's an empty URL field

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#540]
_Original author: tfmorris (March 01, 2012 21:32:03)_

If you accidently click &quot;Add another URL&quot; during project creation and leave the field empty, you'll get the above error during the upload.  Refine should either allow you to delete the extra field added or ignore empty fields (or both).

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=540_

**Comment by jackyq2015** [comment]
Claimed it! 

Will ignore the empty fields.
