### ISSUE TITLE
Jython site-packages path

### ISSUE THREAD

**Issue by arky** [OpenRefine/OpenRefine#5417]
Every time you use python/jython you'll have to declare the site-packages with following lines. It would be good if this could be stored in preferences or picked up automatically. 

```
import sys
sys.path.append('/home/user/jython2.7.3/Lib/site-packages')
from address import AddressParser, Address
```
https://github.com/OpenRefine/OpenRefine/wiki/Extending-Jython-with-pypi-modules

### Proposed solution

Store in configuration or read from Python/ JYTHON environment variable 

https://github.com/OpenRefine/OpenRefine/wiki/Extending-Jython-with-pypi-modules

**Comment by thadguidry** [comment]
@arky Does setting the Java -D option for `python.home`  in refine.ini and starting OpenRefine from the refine.sh script work for you?
https://wiki.python.org/jython/JythonFaq/InstallingJython

`JAVA_OPTIONS=-Drefine.data_dir=/home/user/workspaceTestA -Dpython.home=/home/user/jython2.7.3/Lib/site-packages`

**Comment by arky** [comment]
> @arky Does setting the Java -D option for `python.home` in refine.ini and starting OpenRefine from the refine.sh script work for you? https://wiki.python.org/jython/JythonFaq/InstallingJython
> 
> `JAVA_OPTIONS=-Drefine.data_dir=/home/user/workspaceTestA -Dpython.home=/home/user/jython2.7.3/Lib/site-packages`
> 

@thadguidry what is the purpose of reassigning refine.data_dir here?

**Comment by thadguidry** [comment]
Oh that's just an example you can ignore that part.  We have it documented in the .ini and our docs website if you want to know more how to point to a custom directory for your OpenRefine workspace.

**Comment by arky** [comment]
Thanks @thadguidry
 
Setting the following option seems to work. This will correctly set the path of the site packages. 
`JAVA_OPTIONS=-Dpython.home=/home/user/jython2.7.3` 

I have used the following snippet to learn that the system automatically appends the '/Lib/site-packages'.
`import site
return(site.getsitepackages())`

However importing of the 'address' package tends to fail mysteriously.

import pycountry # works 
import address_formatter  # works 
import address # fails 
from address import AddressParser, Address # fails

**Comment by thadguidry** [comment]
Great! Hmm not sure about address.  Perhaps check with someone on stackoverflow?
