### ISSUE TITLE
[OR 3.7 Snapshot 20221108] Upload URLs of media files not accepted (as they used to be)

### ISSUE THREAD

**Issue by ookgezellig** [OpenRefine/OpenRefine#5418]
I'm using the latest (20221108) snapshot version of OR. I want to upload images from the KB (national library of the Netherlands) to Wikimedia Commons. 

The URLs to the full images are typically formated as follows: http://resolver.kb.nl/resolve?urn=urn:gvn:KONB16:533939704&role=page&count=1&size=large. When I open this URL in a browser, it displays the image to be uploaded to Commons. 

I've made an OR project where I try to make a new Commons file to be called "	
File:De Nieuwe Haven van Texel met het dorp 't Schilt in 't verschiet - Nederlandsche havengezichten enz. - KONB16-533939704 - Prent 1 van 18.jpg", with the source the mentioned URL

![afbeelding](https://user-images.githubusercontent.com/6546244/200810233-fa5ff2c0-33af-412d-b770-1d4d3684a75e.png)

(See the attached Excel "Dataset_WorkshopOpenRefine_WikiconNL19112022.xlsx" for the exact data I want to upload - 
[Dataset_WorkshopOpenRefine_WikiconNL19112022.xlsx](https://github.com/OpenRefine/OpenRefine/files/9970167/Dataset_WorkshopOpenRefine_WikiconNL19112022.xlsx))

When I try to upload to Commons, OR gives an error, that the URL-format is invalid and can't be accepted. 

![afbeelding](https://user-images.githubusercontent.com/6546244/200810854-32751e96-fe9e-4da8-b9ef-30b7da76888c.png)

I would expect such URLs to be accepted (again), because with an earlier version of OR snapshot 3.7 , I uploaded all files in https://commons.wikimedia.org/wiki/Category:400_years_The_Netherlands_%E2%80%93_Japan_(Memory_of_The_Netherlands), using the same URL-syntax, see column H in the Excel "Nederland-Japan.xlsx". So in the past these URLs were accepted by OR.

[Nederland-Japan.xlsx](https://github.com/OpenRefine/OpenRefine/files/9970154/Nederland-Japan.xlsx)

### Versions
 - Operating System: Window 10 Pro
 - Browser Version: Firefox 106.0.4 (32-bits)
 - JRE or JDK Version: 
 - OpenRefine: 3.7 Snapshot  (20221108)

**Comment by wetneb** [comment]
Sorry about that! I'll work on a fix asap.

**Comment by ookgezellig** [comment]
Thanks for the quick response, much appreciated!

**Comment by ookgezellig** [comment]
I just downloaded & installed the new snapshot release (dd 20221110) and this bug seems indeed to have been be solved, the "Invalid file paths" error message is not showing anymore. Many thanks!
