### ISSUE TITLE
[OR 3.7 Snapshot 20221108] Upload local media files to WM Commonms not working/stalls 

### ISSUE THREAD

**Issue by ookgezellig** [OpenRefine/OpenRefine#5420]
Continuing from https://github.com/OpenRefine/OpenRefine/issues/5418, I've adapted my OR 3.7 snapshot project to include uploads from local files (instead of URLs): 

![afbeelding](https://user-images.githubusercontent.com/6546244/200832380-f670e7ac-4d96-4851-83a7-4f6b0ca130c3.png)

I build my OR schema

![afbeelding](https://user-images.githubusercontent.com/6546244/200832596-5a16f9a1-5b9f-4845-8713-3d0d3ab2acde.png)

, and when I try to upload to Commons, all seems OK, without error messages

![afbeelding](https://user-images.githubusercontent.com/6546244/200832867-53b09515-e120-414e-a85b-e5d8c5edf109.png)

So I press the "Upload edits" button, and the upload to Commons seems to begin...

![afbeelding](https://user-images.githubusercontent.com/6546244/200833181-a73c1b30-2b70-4867-93bf-b6ca21f18fb4.png)

but nothing happens, no files actually uploaded... seems to stall for ever...

I check the console: error messages

![afbeelding](https://user-images.githubusercontent.com/6546244/200833360-11440302-b6ee-446a-a0b8-1c84c85768d3.png)

================================
13:42:01.709 [..mWikibaseEditsOperation] Performing edits (31ms)
13:42:01.709 [..ting.EditBatchProcessor] Requesting documents (0ms)
Exception in thread "Thread-3" java.lang.NullPointerException
        at org.wikidata.wdtk.wikibaseapi.MediaInfoIdQueryAction.getMediaInfoIds(MediaInfoIdQueryAction.java:68)
        at org.wikidata.wdtk.wikibaseapi.WikibaseDataFetcher.getMediaInfoIdsByFileName(WikibaseDataFetcher.java:377)
        at org.wikidata.wdtk.wikibaseapi.WikibaseDataFetcher.getMediaInfoIdsByFileName(WikibaseDataFetcher.java:337)
        at org.wikidata.wdtk.wikibaseapi.WikibaseDataFetcher.getMediaInfoIdByFileName(WikibaseDataFetcher.java:309)
        at org.openrefine.wikibase.editing.MediaFileUtils$MediaUploadResponse.getMid(MediaFileUtils.java:283)
        at org.openrefine.wikibase.updates.MediaInfoEdit.uploadNewFile(MediaInfoEdit.java:251)
        at org.openrefine.wikibase.editing.EditBatchProcessor.performEdit(EditBatchProcessor.java:167)
        at org.openrefine.wikibase.operations.PerformWikibaseEditsOperation$PerformEditsProcess.run(PerformWikibaseEditsOperation.java:262)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by wetneb** [comment]
Interesting, this seems to indicate that no filename was returned by the MediaWiki API after file upload, but without marking the upload as failed. I am not sure in which circumstances this can happen, but at least we could anticipate this case and log the JSON response in those cases.

**Comment by ookgezellig** [comment]
I just downloaded & installed the new snapshot release (dd 20221110) and this bug seems to have (partially) disappeared:

** When uploadig media from an URL (such as http://resolver.kb.nl/resolve?urn=urn:gvn:KONB16:533939704&role=page&count=3&size=large), 

![afbeelding](https://user-images.githubusercontent.com/6546244/201087908-004d09de-f8d1-45c5-92ee-ebc9b04249e7.png)
 
the file is correctly uploaded to Commons, see the result at https://commons.wikimedia.org/wiki/File:De_Haven_van_Amsterdam_-_Nederlandsche_havengezichten_enz._-_KONB16-533939704_-_Prent_3_van_18.jpg 

** When uploading a file from local media, the upload still seems to stall
![afbeelding](https://user-images.githubusercontent.com/6546244/201088939-fcec3ef6-6764-4fa3-9f7b-dc4b81916df7.png)

with the same error message as yesterday
![afbeelding](https://user-images.githubusercontent.com/6546244/201089063-fb14a4f5-2a33-42cd-ba91-d03d49ac3abd.png)

**Comment by ookgezellig** [comment]
I might have cheered too early: I just tried uploading another file from URL (http://resolver.kb.nl/resolve?urn=urn:gvn:KONB16:533939704&role=page&count=4&size=large), but now I get the same stalling and error console messages as when uploading from local media files

**Comment by wetneb** [comment]
My proposed fix will not let them be uploaded but at least the console will display a more helpful error message and the upload will not be stalled by these failures.
