### ISSUE TITLE
Import project archive from URL

### ISSUE THREAD

**Issue by ookgezellig** [OpenRefine/OpenRefine#5431]
From the OR start screen you choose "Import project", which enables the user to select a local project tar.gz file for upload into OR

It would be handy to also have the possiblilty the import a project archive directly from URL, such as (for instance) https://github.com/KBNLwikimedia/OpenRefine-WikimediaCommons-Workshop/blob/main/Dataset-WorkshopOpenRefine-WikiconNL19112022-xlsx.openrefine.tar.gz?raw=true

**Comment by tfmorris** [comment]
Sounds like a reasonable request and we have all the pieces, so it's just a matter of wiring them up. I wouldn't be surprised if writing the tests was harder than the implementation itself.

**Comment by AbrahamRH** [comment]
Hi, I'm interested in contributing to this issue. Can I work on it?

**Comment by SoniaSun810** [comment]
Hey, dear @wetneb ! Can you assign this issue to my group? We've been actively working on it and have developed a promising solution.
