### ISSUE TITLE
Idea: Reconcile -> Facet -> Number of Results

### ISSUE THREAD

**Issue by mshd** [OpenRefine/OpenRefine#5448]
Sometimes I want to match those items with only one possible result. Is there a way to sort the suggested matched by their quantity. 
Disabling blank on "best candidate's score" already filters out those with no results. But I would like to filter out those with only 1 result.

### Proposed solution
Add a numeric facet of the result count.

**Comment by wetneb** [comment]
I have used that in the past! I think you can create a custom numeric facet with an expression such as `cell.recon.candidates.length()`.
No strong feeling about whether this should be included in the UI though.
