### ISSUE TITLE
UI fix: improve position of add media / add item button in Schema tab

### ISSUE THREAD

**Issue by lozanaross** [OpenRefine/OpenRefine#5449]
This issue is transferred from a comment in #5050, so it's easier to track separately.

The UI fix in question is to move the "add item" / "add media" button to the left of the schema building window and thus make it more prominent. See screenshots below (context-specific to Wikibase chosen): 

![Screenshot 2022-07-23 at 22 37 41](https://user-images.githubusercontent.com/25489750/180622077-a46f77e1-8584-4f7c-be2b-55591a9a2203.png)

![Screenshot 2022-07-23 at 20 36 44](https://user-images.githubusercontent.com/25489750/180622096-e3c202bc-c2be-4ddf-936d-d53941b26672.png)

![Screenshot 2022-07-23 at 20 36 47](https://user-images.githubusercontent.com/25489750/180622099-0f1b352f-1de2-43de-abff-f79bb6a21946.png)

Complete wireframes (including development parameters are here): https://xd.adobe.com/view/3ae13acb-7afb-4ea5-8252-351a1622abba-6fb2/

_Originally posted by @lozanaross in https://github.com/OpenRefine/OpenRefine/issues/5050#issuecomment-1193187217_

**Comment by maaannsiP** [comment]
Hi @lozanaross @wetneb, as per the new guidelines https://forum.openrefine.org/t/welcome-and-guidelines-to-the-outreachy-ux-design-internship-applicants/567 in OpenRefine Discourse Forum. I would like to be assigned this.

**Comment by wetneb** [comment]
I am not sure there is much design work to do here - are you looking into implementing it instead? The forum post you linked is about design tasks.

**Comment by maaannsiP** [comment]
I am looking to work on the design. But, if you think there is not much work to do on this issue. Then, I would be happy if you can assign me some issues for design.

**Comment by wetneb** [comment]
I cannot assign you to issues on my own - I do not know what areas of the tool you already master, what your interests and skills are, and so on. See Lozana's post:
https://forum.openrefine.org/t/welcome-and-guidelines-to-the-outreachy-ux-design-internship-applicants/567

**Comment by maaannsiP** [comment]
Okay, Thank you.

**Comment by prashasti-7** [comment]
I have made a few changes to the UI. The buttons have been moved according to the XD image. Please confirm if it looks okay.

![image](https://user-images.githubusercontent.com/108210025/224074450-875594d8-c18c-431d-a55d-5d6147ab374f.png)

I am facing slight alignment issues with the remove button. I could use some suggestions on how to improve it.
![image](https://user-images.githubusercontent.com/108210025/224075053-27fc5a9c-589d-4ef1-8b62-8a4a44370f73.png)

**Comment by prashasti-7** [comment]
Could you guide me on how to recreate the website to add both media and items buttons?
Also, I was having issues while aligning the remove button. I could use some help to figure that out.

### UI Changes Implemented
- Left-aligned 'Add Item' button
- Right-aligned 'Saved Schema' and 'Delete Changes' buttons
- Added side border to the 'type file name or drag reconciled column' [Let me know if that needs to be reversed]
- Increased the width of the div box to cover the whole width (as in the screenshots)
- Remove, add term and other buttons aligned
- Added border above the Add item button

Please let me know if the current changes look okay. I have attached the link for the UI changes.
https://imgur.com/a/444Cu5f

**Comment by wetneb** [comment]
For me it's easier to review your work if you can open a pull request (even in a draft state if you do not feel confident).

> Could you guide me on how to recreate the website to add both media and items buttons as in the XD image?

That would require configuring a wikibase with both mediainfo and item support. You could take an existing Wikibase manifest and tweak it to pretend it has both. I am not aware of a public Wikibase instance which currently uses both those entity types (at least we haven't got any in https://github.com/OpenRefine/wikibase-manifests).
