### ISSUE TITLE
replaceEach function not working and mis-documented

### ISSUE THREAD

**Issue by jquartel** [OpenRefine/OpenRefine#5463]
At https://docs.openrefine.org/manual/grelfunctions#replaceeach-s-a-find-a-replace in the GREL manual, the documentation describes a function replaceEach with syntax

replaceEach(s, a find, a replace)

But the example in the subsequent description uses a function called replaceEachFromArrays, and if you try this example you do indeed get an Unknown function error. However, using replaceEach with the syntax described also always produces an error

_Error: replaceEach expects 3 arguments: string, array of strings to replace, array of replacement strings_

even when using the correct argument types. Try, for instance,

`"The cow jumps over the moon and moos".replaceEach(["th", "moo"], ["ex", "mee"])`

I am using OpenRefine Version 3.6.2 [579a6f7] in Safari Version 16.1 on MacOS 12.6.1 .

**Comment by thadguidry** [comment]
@jquartel you are right!  it's not documented properly.
The function is just called `replaceEach`
But it also doesn't seem to work as internally documented:
https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/expr/functions/strings/ReplaceEach.java#L37-L53

and with the test cases @elroykanye designed:
https://github.com/OpenRefine/OpenRefine/blob/master/main/tests/server/src/com/google/refine/expr/functions/strings/ReplaceEachTest.java#L15-L22 

I get this:
`"abcdefghijklmnopqrstuvwxyz".replaceEach(["a","e","i","o","u"], "A")`
--> _Error: replaceEach: the number of replacements must be equal to or less than the number of search strings._
