### ISSUE TITLE
refine script fails with weird message if maven download fails

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#5484]
Apparently the current Maven version is 3.8.6 and when it fails to download 3.8.5 it gives the error:

```
tar: Error opening archive: Unrecognized archive format
Error: Error while expanding apache-maven-3.8.5-bin.tar.gz
```
when it feeds the 404 HTML page to `tar`

### To Reproduce
1. Uninstall `mvn`
2. Run `refine` script

### Current Results
```
$ ./refine test
Using refine.ini for configuration
-------------------------------------------------------------------------------------------------
You have 1352M of free memory.
Your current configuration is set to use 1024M of memory.
OpenRefine can run better when given more memory. Read our FAQ on how to allocate more memory here:
https://docs.openrefine.org/manual/installing#increasing-memory-allocation
-------------------------------------------------------------------------------------------------
tar: Error opening archive: Unrecognized archive format
Error: Error while expanding apache-maven-3.8.5-bin.tar.gz
```

### Expected Behavior

Ideally, it figures out the current version. At a minimum, say that Maven is a requirement and tell the user to install it.

### Versions
 - Operating System: Mac OS
 - OpenRefine: HEAD

**Comment by tfmorris** [comment]
I only ran into this because I accidentally deleted my system install of Maven. I'm happy to just have it declared as a dependency.

**Comment by wetneb** [comment]
Sounds good to me! So then this issue is about cleaning up the `refine` / `refine.bat` scripts by removing support for this, and a separate PR should be opened to update the docs.

**Comment by wetneb** [comment]
See another error report here: https://github.com/OpenRefine/OpenRefine/issues/4865
