### ISSUE TITLE
Feature: Batch deletion

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#549]
_Original author: chen...@gmail.com (March 13, 2012 06:34:30)_

Since we programmatically uploads data to refine, the project list becomes loaded quickly.

So far I have to write a program to delete them in a batch.  Not sure if that's something that you can consider to built-in?

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=549_

**Comment by wetneb** [comment]
Closing per @tfmorris 's comment above.
