### ISSUE TITLE
XLSX test failure

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5497]
A test instability seems to have been uncovered by the CI: https://github.com/OpenRefine/OpenRefine/actions/runs/3627223760/jobs/6116914771
```
Error:  Tests run: 704, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 38.319 s <<< FAILURE! - in TestSuite
Error:  readXlsxAsText(com.google.refine.importers.ExcelImporterTests)  Time elapsed: 0.04 s  <<< FAILURE!
java.lang.AssertionError: expected [2022-12-06 06:55] but found [2022-12-06 06:56]
	at com.google.refine.importers.ExcelImporterTests.readXlsxAsText(ExcelImporterTests.java:274)
```

The same problem appears in a different job of the same run:
https://github.com/OpenRefine/OpenRefine/actions/runs/3627223760/jobs/6116914844

**Comment by tfmorris** [comment]
There's a race window in the date test. I have a fix, but if you resubmit the job it will likely succeed.
