### ISSUE TITLE
Provide options for Wikimedia sitelinks

### ISSUE THREAD

**Issue by bodhisattwawiki** [OpenRefine/OpenRefine#5512]
OpenRefine does not allow to link Wikimedia pages (be it from Wikipedia, Wikisource etc.) which do not have Wikidata items to the new Wikidata items which are created.

### Proposed solution

I am being bold here to request to provide options to add Wikimedia sitelinks while working on the schema on OpenRefine. This would help create Wikidata items of already existing Wikimedia pages (like Wikipedia articles, Wikisource NS:0 etc.).

**Comment by wetneb** [comment]
Thanks! Yes that is a valid request, but we already have another issue for it:  #1788
