### ISSUE TITLE
Fit height of text facet to its contents when few options are present

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5513]
When creating a text facet in a column where few different values are present, I get a facet with a lot of whitespace:

![image](https://user-images.githubusercontent.com/309908/206866000-d99b51c6-a8df-4ede-a5d0-fbc6683077d8.png)

### Proposed solution
When few options are present, the facet should shrink to a smaller size, without introducing a scroll bar:
![image](https://user-images.githubusercontent.com/309908/206866106-8789f5e4-6130-4c8f-810e-fd34fd0fb82c.png)

When more options are available, it could potentially expand more than its default size, but that should not happen indefinitely: we should introduce a scroll bar past a certain length.

The facets should remain resizable by the user in any case.

### Alternatives considered

None.

### Additional context

Prompted by @ostephens's video on [doing the Advent of Code 2022 with OpenRefine](http://www.meanboyfriend.com/overdue_ideas/2022/12/advent-of-code-with-openrefine/)

**Comment by thadguidry** [comment]
I work with longer strings oftentimes, and so this is also highly dependent on the length of values (or the expression that created them to be longer).
I feel that a box size height of 1/3 the height of the `left-panel` could work as a sensible default? or should it be 1/2?  In other words, allow the height to grow up until either 1/3 or 1/2 the height of the `left-panel` ?

**Comment by wetneb** [comment]
I would not try to change the default size of the facet or making it a proportion of the left panel. With the right CSS it should be possible to just fit to the content (which takes into account longer values which need wrapping on multiple lines).

**Comment by thadguidry** [comment]
OK, but at what height do we say a facet can grow to before we start showing a scrollbar?
