### ISSUE TITLE
cross function produces null when there is no match

### ISSUE THREAD

**Issue by jquartel** [OpenRefine/OpenRefine#5531]
I notice that the result of the `cross()` function is not an array when there is no match found - instead, the result is `null`. This seems to contradict the reference documentation which states "Returns an array of **zero** or more rows..." (that is, we should expect an an empty array, `[]`, when there are no matching rows). So if, for instance, you are wanting a count of the number of matches using `cross(...).length()` (which is something I do) then you currently get "Error: length expects an array or a string" where you expect to get 0.

Incidentally, if the function gets fixed to produce an empty array, as per the documentation, then the result of a common operation where you just want to retrieve the first matching row (i.e. `cross(...)[0]`) will, when there is no match, change to "Error: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0" - currently the result is just null (since `null[0]` is also null). So I'm wondering if the null return was implemented as a specific exception to avoid this ungainly instance. Should we consider making the result of indexing an empty array (e.g. `[][0]`) null instead of producing the error?

I'm looking at OpenRefine 3.6.2 [579a6f7].

**Comment by jenny-Musah** [comment]
Hi @jquartel, I am new to open source contribution and would like to attempt solving this issue if I could just get a clearer explanation,  do we intend to make the function return an empty array, I am very sure there would be a good way to handle any error that comes as a result

**Comment by jquartel** [comment]
Hi @jenny-Musah, assuming we want the function to behave as per the documentation (which I think it should) then yes, cross() should return an empty array (instead of null) when there are no matching rows. I imagine this should be an easy fix.

But this would raise the problem of getting the ugly java error when indexing an empty array (since it is common to use cross(..)[0] to grab the first match, and sometimes there is no match). I'm just not sure if we would want to change the behaviour of array indexing to have a special exception when  indexing an empty array (e.g. by returning null rather than raising the out-of-bounds error).

**Comment by wetneb** [comment]
The default behaviour for "add column based on this column" is (I think) to generate a blank (null) cell when evaluating an expression raises an error, so I suspect it would not actually disturb too many people to change the behaviour of the cross function without any further adaptation.

**Comment by jquartel** [comment]
Ah yes, good point @wetneb . Although I do think there are some inconsistencies in array indexing errors in general. For instance, ["a"][1] generates the out-of-bounds error but ["a"][-2] does not (see also #5361 ).

**Comment by jquartel** [comment]
As @wetneb points out, I think the existing out-of-bounds error is fine. 
So all we need is for `cross(...)[0]` to return `[]` instead of `null` when there are no matching rows. That way, `cross(...).length()` will nicely give 0 when there are no matches instead of "Error: length expects an array or a string".

**Comment by ostephens** [comment]
>Should we consider making the result of indexing an empty array (e.g. [][0]) null instead of producing the error?

I'm against this. If you try to access a non-existent value of an array I think it should generate an error

It would be valid for the array to have `null` as the nth value as well as for the nth value to not exist. Retrieving the nth value of an array should differentiate between these two scenarios

**Comment by wetneb** [comment]
> So all we need is for `cross(...)[0]` to return `[]` instead of null when there are no matching rows. 

@jquartel I think you mean that `cross(...)` would return `[]` when there are no matching rows, right (no `[0]` involved)? Just to make sure we are on the same page. @ostephens would that work for you?

**Comment by ostephens** [comment]
Yes - getting `cross` to return an empty array when there are no matching rows makes sense to me and I'm happy with that

**Comment by antoine2711** [comment]
When `cross()` got reworked in 2019, returning `null` instead of an empty array was not the intention. Clearly an oversight that got missed.

I'm totally for fixing that and returning an empty array if `cross()` finds nothing.

**Comment by jenny-Musah** [comment]
let me try doing this @wetneb  and @jquartel , never made a contribution before

**Comment by jenny-Musah** [comment]
Can I be assigned to this issue, I have never contributed

**Comment by jenny-Musah** [comment]
@jquartel, pls can I get a platform to send a direct message to you, email address, anything, please.

**Comment by jquartel** [comment]
Yes, apologies. `cross()` should return `[]` if there are no matching rows.

**Comment by jenny-Musah** [comment]
@jquartel  can I get the file path to were this issue is?

**Comment by jquartel** [comment]
Unfortunately I'm only a user and (sadly) I've never had time to dive into the source code, so I can't advise on where to look. But I really, really appreciate what you are all doing to improve this already wonderful tool, and I can't thank you enough for taking notice of my bug reports.

**Comment by jenny-Musah** [comment]
I have change the return type from null to return the row, This is the method that does the return for the cross function so i just change the return from 
<
 public HasFieldsListImpl getRows(Object value) {
            if (!ExpressionUtils.isNonBlankData(value)) return null;
            String valueStr = value.toString();
            if (valueToRowIndices.containsKey(valueStr)) {
                Project targetProject = ProjectManager.singleton.getProject(targetProjectID);
                if (targetProject != null) {
                    HasFieldsListImpl rows = new HasFieldsListImpl();
                    for (Integer r : valueToRowIndices.get(valueStr)) {
                        Row row = targetProject.rows.get(r);
                        rows.add(new WrappedRow(targetProject, r, row));
                    }

                    return rows;
                }
            }
            return null;
        }
>
To this 
< 
 public HasFieldsListImpl getRows(Object value) {
            HasFieldsListImpl rows = new HasFieldsListImpl();
            if (!ExpressionUtils.isNonBlankData(value)) return rows;
            String valueStr = value.toString();
            if (valueToRowIndices.containsKey(valueStr)) {
                Project targetProject = ProjectManager.singleton.getProject(targetProjectID);
                if (targetProject != null) {
                    for (Integer r : valueToRowIndices.get(valueStr)) {
                        Row row = targetProject.rows.get(r);
                        rows.add(new WrappedRow(targetProject, r, row));
                    }

                    return rows;
                }
            }
            return rows ;
        }
>


And change the cross function test from this 
<
 @Test
    public void crossFunctionMatchNotFoundTest() throws Exception {
        Assert.assertNull(invoke("cross", "NON-EXIST", "My Address Book", "friend"));
    }>
To this cause the test was failing
<
 @Test
    public void crossFunctionMatchNotFoundTest() throws Exception {
        Assert.assertEquals(invoke("cross", "NON-EXIST", "My Address Book", "friend"), rows);
    }
>

But i'm still worried for the class or whatever would be using this cross function, i don't  know if i still  need to handle the exceptions for any class making use of this cross function.

**Comment by wetneb** [comment]
Hi @jenny-Musah, as you can see your message above is pretty hard to read. To review your code changes it would be much easier if you opened a pull request for them.

**Comment by jenny-Musah** [comment]
Hi @wetneb, Thank you I would make a pull request but I was going to ask what version should I make the changes, this issue says 3.6, should I clone that version and make changes then push it, or I can make the change on any version?

**Comment by jquartel** [comment]
Looks like you could also remove that second-to-last `return rows ;` statement since the flow falls out to that last one anyway.

**Comment by jenny-Musah** [comment]
@wetneb I made a pull request already

**Comment by jenny-Musah** [comment]
![e](https://user-images.githubusercontent.com/102564292/226116965-af61e2d3-1f2f-45e5-b0a2-d5f058cb59f1.PNG)

This check didn't pass i don't know why

**Comment by jenny-Musah** [comment]
@wetneb  
Finally the  "mvn formatter:format" command ran today i pushed again.

**Comment by jenny-Musah** [comment]
Thank you so much @wetneb  for the help, I wouldn't have done this without your help, Finally, I made a contribution to an open-source project I am so excited, Thanks...

**Comment by antoine2711** [comment]
> Thank you so much @wetneb for the help, I wouldn't have done this without your help, Finally, I made a contribution to an open-source project I am so excited, Thanks...

@jenny-Musah : Good work and thank you very much for your contribution to OpenRefine!

Best Regards,
   Antoine
