### ISSUE TITLE
Remove backend commands exposed for each operation

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5539]
So far, each operation that the user can run on a project comes with the following Java classes in the backend:
* an Operation class, which holds the metadata for the operation and is responsible for its JSON serialization (which is exposed in the history tab, among others)
* a Change class (often reused by different operations), which is responsible for actually applying the operation to the project (carrying out the corresponding transformation)
* a Command class, which exposes an HTTP API to initiate the operation on a project.

Therefore, each operation comes with its own HTTP endpoint to apply it, and the frontend can call that endpoint when the user clicks on some menu item or validates some dialog, for instance.

At the same time, we have a generic endpoint to apply a series of operations, represented by their JSON serialization, on a given project. This is used in the history tab, to let the user apply a workflow exported in JSON.

This endpoint (called `apply-operations`) makes all the other operation-specific commands redundant: we should be able to use it to apply any single operation, hence removing the need for a fairly large number of other commands.

This would have the following benefits:
* remove a lot of Java classes
* refactor the frontend so that making any change to the project goes through the same code, making it easier to implement logic that should apply to all those changes (such as warning the user that they are discarding a part of the history if there are "future" history entries: #3184)
* make it easier to implement new operations, by removing the need to implement a corresponding command (but the move can be done without any breaking change with respect to the extension interface - extensions are still free to define their own commands for each operation they define).

This will likely require improving the error handling in the `apply-operations` endpoint, since it is likely that operation-specific endpoints currently offer a better handling. When an operation's JSON representation is incomplete or invalid, we want to be able to return an appropriate response which should be replicated in the frontend accordingly. This will benefit the "Apply operations" UX as well.

**Comment by tfmorris** [comment]
Having recently taken a crack at an OpenAPI (ie Swagger) definition of the internal API has made me continue to doubt whether this is a good idea from an API point of view. I'm definitely all for simplification and reducing duplication, but if we got rid of the individual endpoints, we'd probably have to come up with some kind of "build operation JSON" helpers for the client. This isn't a pattern I've seen (which doesn't mean it doesn't exist) or one which I know how to describe in OpenAPI (if it's possible).

Something to think about and figure out if we go down this path...
