### ISSUE TITLE
Link to reconciliation service's documentation

### ISSUE THREAD

**Issue by Abbe98** [OpenRefine/OpenRefine#5558]
Some reconciliation services has a link to documentation specified in their service manifest. Currently an OpenRefine user would need to do the following to go to the documentation from OpenRefine:

1. click the "Access service API" link in the main reconciliation dialog
2. browse the JSON manifest to see if there is a documentation link
3. click it

It should be easier.

### Proposed solution
The main reconciliation dialog should have a "Documentation" link next to the "Access service API" link.

**Comment by wetneb** [comment]
Yes, the `documentation` field of the manifest was introduced relatively recently and is already available in the 0.2 version of the specs:
https://reconciliation-api.github.io/specs/0.2/#service-manifest
I agree it would be worth displaying.

**Comment by wetneb** [comment]
It would also be worth displaying this in the data extension dialog. For instance, users often struggle to discover some custom properties in the Wikidata reconciliation service: https://forum.openrefine.org/t/wikidata-description-and-sitelink/334/7

**Comment by ayushi-8102** [comment]
Hi! I want to work on this issue. Please assign it to me!

**Comment by Abbe98** [comment]
Here is an example of a service whose manifest contains a documentation link: https://fornpunkt.se/apis/reconciliation/geonames

**Comment by ayushrai206** [comment]
hey, @ayushi-8102 are you still working on this?if not,i would like to take this.

**Comment by ayushrai206** [comment]
@Abbe98 may i be assigned to this?

**Comment by ayushi-8102** [comment]
@ayushrai206 Yeah you can work on it!

**Comment by wetneb** [comment]
@Abbe98 do you think the "Access service API" link is still useful if there is a documentation link available? I have proposed to @ayushrai206 that we just replace that link by the documentation one for now.

If you'd rather have both, would you put them on top of each other (stacked vertically) or one after the other?

Maybe other people have ideas about what this should look like? @OpenRefine/designers

**Comment by Abbe98** [comment]
@wetneb great question, I think it's still useful as it makes it easy to share the endpoint with others, however, if #5878 is implemented I think it's redundant.

> If you'd rather have both, would you put them on top of each other (stacked vertically) or one after the other?

I was thinking one after the other but I do not have much of an opinion.

**Comment by Lydiaofficial** [comment]
The placement whether vertically or side by side, depends on how much horizontal or vertical space  available in the current UI.
Vertical placement, will allow for a clear visual separation between the "Access service API" link and the "Documentation" link, making it easier for users to identify and interact with each link individually.

However, side by side placement can be beneficial if users frequently reference both links or need quick access to them.
