### ISSUE TITLE
Word facet should split on all whitespace

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#557]
_Original author: tfmorris (April 07, 2012 15:42:20)_

In particular, it should consider a no-break space (' ',NBSP) a word delimiter, but probably should use all whitespace characters.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=557_

**Comment by wetneb** [comment]
It's not clear to me what a word facet is? Do we still have that? @thadguidry any idea?

**Comment by thadguidry** [comment]
@wetneb Yes...

![Annotation 2019-12-20 113802](https://user-images.githubusercontent.com/986438/71278506-6abcc000-231d-11ea-9a60-1c9c2ceecf50.png)

**Comment by tfmorris** [comment]
All whitespace was a good idea in 2012, but in 2022 it would be insufficient. Closing this in favor of #2813.

**Comment by tfmorris** [comment]
I changed my mind. This provides 90% of the value and is much simpler to implement than #2813, so reopening.

**Comment by thadguidry** [comment]
Weee!  Pretty words now in the word facet!
