### ISSUE TITLE
Cluster and edit changes space character in values to nbsp

### ISSUE THREAD

**Issue by fitnycdigitalinitiatives** [OpenRefine/OpenRefine#5581]
When using cluster and edit, when you select an existing value by clicking on the hyperlinked option, it replaces any spaces in the original values with non-breaking spaces. See [here](https://forum.openrefine.org/t/odd-space-issue-causing-blank-down-issues/330).

### To Reproduce
1. Use cluster and edit on a column of data
2. In the interface, select one of the clustering option by clicking on the hyperlinked options. Select merge selected and close.
3. New values will all have replaced standard spaces with non-breaking spaces

### Current Results
Space replaced with non-breaking space which can cause inconsistencies with rest of data

### Expected Behavior
Should not alter original data in this way

### Versions
 - Operating System: Mac 
 - Browser Version: Chrome 
 - JRE or JDK Version: 
 - OpenRefine:  3.6.2

**Comment by thadguidry** [comment]
In 3.7 version, cannot reproduce using key collision - Daitch-Mokotoff or nearest neighbor - Levenshtein.
![image](https://user-images.githubusercontent.com/986438/214487430-4a44bd87-f9ee-4d42-affc-c4a270108de5.png)

**Comment by wetneb** [comment]
Argh, I should have thought about this! I indeed introduced those non-breaking spaces in the UI to make sure that options which differed in spaces were rendered differently in the dialog, but I did not think the values were read from the DOM when merging a cluster. Sorry about this! I'll work on a fix asap.

**Comment by fitnycdigitalinitiatives** [comment]
Thanks @wetneb 

And @thadguidry, I'm sorry I wasn't clear in my op, but it occurs when values already have spaces in them, so I think if you check 'small size' you'll see what I'm talking about.

**Comment by wetneb** [comment]
Note that I could only reproduce this bug with Chromium, not with Firefox. I think it is known that they do not handle non-breaking spaces in the same way (or at least, until recently).

**Comment by robroc** [comment]
If I may add to this issue... this non-breaking space added during clustering appears as `\xa0` when the data is exported as CSV and loaded into pandas. 

It also prevents text filtering in OpenRefine when using a normal space. For example, after clustering, the string `DEW TECHNOLOGIES` doesn't return when you search for `DEW ` (with a regular space after the word). The only fix is to copy the whitespace character from the string (in a facet, for example), and do a search-replace with a regular space.

I'm using version 3.6.2 on Windows, Firefox.

**Comment by wetneb** [comment]
This issue should be fixed in 3.7-beta5.
