### ISSUE TITLE
OpenRefine 3.7 beta 2 for Windows not executing

### ISSUE THREAD

**Issue by ann-james** [OpenRefine/OpenRefine#5583]
OpenRefine 3.7 beta 2 for Windows OS is not installing when attempting to download and install from the .exe file with latest version of java already installed using latest version of Chrome

### To Reproduce
1. Download zip file for Windows OS, OpenRefine 3.7 beta 2 with java
2. Unzip file
3. Update and install latest version of java on local machine and latest version of Chrome
4. Open openrefine.exe (application file)

### Current Results
Command line loaded as expected, but application file didn't execute to open the actual application, with latest Chrome browser installed execution of the file opens a new tab which displays the OpenRefine website in the Java section of the page (https://openrefine.org/docs/manual/installing#java)

### Expected Behavior
Expecting to open the application and execute the file

### Screenshots
NA

### Versions
 - Operating System: Windows 10 Enterprise
 - Browser Version: Chrome Version 109.0.5414.120 (Official build)
 - JRE or JDK Version: Version 8, update 361 (build 1.8.0_361-b09)
 - OpenRefine: OpenRefine 3.7 beta 2 with java

### Datasets
NA

### Additional context
NA

**Comment by wetneb** [comment]
Thanks for reporting! We are aware of this and hope to release 3.7-beta3 soon, fixing this issue.

**Comment by wetneb** [comment]
@ann-james could you try 3.7-beta5 and tell us if it works properly this time?

**Comment by tdombos** [comment]
Still not working with the released 3.7 either.

**Comment by wetneb** [comment]
Thanks for reporting @tdombos.
@thadguidry any chance you could double-check if 3.7.0 with Java works on a Windows without Java?
I am not sure if @tdombos' report is a sign that there is still something wrong in the release pipeline or if it is an independent bug related to launch4j.

**Comment by thadguidry** [comment]
@wetneb Yes it's working (launched with .exe), had tested after you released.  Also to absolutely prove, I just now removed again my `JAVA_HOME` and launched it and also used jconsole to verify/inspect the running OpenRefine pid and its VM summary details.  Notice at the bottom the VM arguments, library path, Class path are using the `\server\target\lib\native\Windows` which has the JRE we shipped with 3.7.
![image](https://user-images.githubusercontent.com/986438/221703749-a3be1321-83cb-4d32-b479-11b2b0c74b43.png)

**Comment by wetneb** [comment]
Thanks Thad!

@tdombos does any other version of OpenRefine work on your system? Can you share the version of your operating system, the path to your OpenRefine install and whether your Windows username contains any non-ASCII characters?

**Comment by tdombos** [comment]
Yes, I have v3.6.2 running without a problem. 

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041

No, my username has no non-ASCII characters.

**Comment by thadguidry** [comment]
@tdombos can you do the following:
1. Open a `cmd` prompt and start `refine.bat` rather than using the .exe
2. reply and attach the `support.log` file that is created in the OpenRefine 3.7 folder, if it is not created then a copy/paste of any output from the `cmd` prompt when you tried to start `refine.bat`

**Comment by tdombos** [comment]
No support.log was created, this is the message sent: 
```
You must set JAVA_HOME to point at your Java Development Kit installation
If you don't know how to do this, follow the instructions at
  http://bit.ly/1c2gkR
Type 'refine /h' for usage.
```

Btw running the refine.bat for 3.6.2. on the same computer gives the same error message, but clicking on the 3.6.2 exe works.

**Comment by thadguidry** [comment]
@tdombos And if you start the release version of OpenRefine 3.7  (make sure you downloaded the latest final 3.7 release)... what happens on Windows 10 for you when clicking on `openrefine.exe` inside the extracted folder for `/openrefine-win-with-java-3.7.0/openrefine-3.7.0` ?
![image](https://user-images.githubusercontent.com/986438/222126835-7949677d-e594-4f33-82bb-f6432bff9e45.png)

Does a black cmd prompt begin to quickly open and then close?  Some error notice?  Can you be more specific about what you see after clicking on the `openrefine.exe` in that extracted folder?

**Comment by k9gardner** [comment]
To jump into the thread as well, I'm experiencing the same thing with the release version of 3.7.0. Version 3.6.0 works fine, and when it launches it gives a notice at the top of the browser window, "New Version [Download OpenRefine v3.7.0 now.](https://github.com/OpenRefine/OpenRefine/releases/tag/3.7.0)". I followed that link to the Windows installer. Upon installation, I am experiencing exactly what you describe here. The cmd window opens and closes so quickly I can't see the command there (but there is one there), and then it goes to the "Installing OpenRefine" website.

**Comment by wetneb** [comment]
@ann-james @tdombos @k9gardner could you try the following snapshot release and tell us if OpenRefine opens properly with it?
https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.openrefine&a=openrefine&v=3.8-SNAPSHOT&c=win-with-java&p=zip

Thanks a lot for your patience on this!

**Comment by tdombos** [comment]
It works!

**Comment by wetneb** [comment]
Amazing, thanks a lot! I will then release a 3.7.1 with the fix.

**Comment by tdombos** [comment]
I checked in the 3.7.1 released last week, but it still does not work. Was the fix included?

**Comment by wetneb** [comment]
The change made above was indeed included, but it is still possible that the problem you are facing is due to some other difference between the 3.8-SNAPSHOTs and 3.7. I am not sure what those could be! I would recommend you keep using 3.8-SNAPSHOT in the meantime.

**Comment by ostephens** [comment]
@wetneb what's the status of this? A similar (the same?) issue has been reported on the Forum https://forum.openrefine.org/t/3-7-2-exe-requires-update-bat-doesnt/812 when using the 3.7.2 Windows without Java distribution, when starting using OpenRefine.exe (but works fine with openrefine.bat)

**Comment by wetneb** [comment]
So, thanks to the debugging information provided on the forum, it seems that this is a case of Launch4j refusing to use the locally installed version of Java because it matches our upper bound on supported versions (we support Java up to 17, Launch4j understands this as a strict bound and refuses to use Java 17).

The upper bound on Java compatibility is only based on what we test for. Given that Java runtime environments are generally very backwards compatible, it feels wrong to me to refuse launching if Java is more recent than the versions of Java we test OpenRefine with. So I would just propose to drop this maximum version altogether.

**Comment by thadguidry** [comment]
Hmm, it's probably an OK thing to do for now, after Java 9 released? To drop the maximum version altogether.

Is Maven doing the `-release` option towards the compiler?  Have you checked?  or is it performing a `-Xbootclasspath` or needed any more? https://www.baeldung.com/java-source-target-options

@tfmorris don't you have experience with our previous bytecode compatibility issues when we flipped from Java 7 to 8?

**Comment by wetneb** [comment]
That's a good point. The compiler is set up to target Java 11:
https://github.com/OpenRefine/OpenRefine/blob/51bb001c035791ab8d71f4e0ed94ed9f2cef6be8/pom.xml#L139-L149

But we could replace our `<source>` and `<target>` settings by just `<release>` which is designed for that.
