### ISSUE TITLE
Clean up the refine script

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5586]
The `refine` script has plenty of broken/dead code that we should clean up. Here is a probably non-exhaustive list:

* A lot of the packaging logic (`./refine dist`) is now handled directly in Maven so that command should basically just call `mvn package -DskipTests=true`
* A lot of the linters/checkers are broken or not used
* The `./refine ui_tests` needlessly downloads reconcile-csv, which is no longer used for Cypress tests. Also, it seems to fail to run the Cypress tests on my end
* The `./refine test` and `./refine server_tests` do the same thing because `ui_tests` are not included there.
* The automatic download of Maven is broken (#5484)

**Comment by elebitzero** [comment]
> A lot of the packaging logic (./refine dist) is now handled directly in Maven so that command should basically just call mvn package -DskipTests=true

@wetneb This looks correct in refine. Can you be more specific? 'dist' does call 'mvn package', after ensuring mvn is installed.
```
dist() {
    get_version $1
    build_prepare
    mvn_prepare
    "$MVN" versions:set -DnewVersion="$VERSION"
    "$MVN" package
}
```

**Comment by elebitzero** [comment]
> The ./refine test and ./refine server_tests do the same thing because ui_tests are not included there.

`refine test` does `mvn test` and `refine server_test` does `mvn test -f main` so they are slightly different.  I would leave these alone.

**Comment by elebitzero** [comment]
For #5484, that will be handled in a separate PR so that should just be a part of that issue.
