### ISSUE TITLE
Support Wikipedia HTML tables

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#56]
_Original author: tfmorris (May 21, 2010 17:25:24)_

Feature request

Supporting HTML tables which contain Wikipedia links would be very valuable 
for loading Wikipedia data because the links represent pre-reconciled 
entities (except for red links).

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=56_
##

**Comment by wetneb** [comment]
@tfmorris: Given the issues mentioned above, I went for a different route: parsing directly the source wikicode. It has pros and cons: parsing is easier, but template expansion is not supported so some reconciliation links will be lost
