### ISSUE TITLE
Respect "Batch size" if specified by reconciliation manifest

### ISSUE THREAD

**Issue by Abbe98** [OpenRefine/OpenRefine#5603]
Reconciliation manifests can sometimes have a [ `batchSize` property set in their manifest](https://reconciliation-api.github.io/specs/0.2/#service-manifest) indicating the maximum number of reconciliation queries in a reconciliation query batch.

OpenRefine currently sends 10 reconciliation queries per batch rather than the value specified by the `batchSize` property. By respecting the `batchSize` property many users would likely see less HTTP-requests and faster reconciliation.

Subset of #2549

**Comment by tfmorris** [comment]
It seems backwards for a service to be specifying the behavior of a client. A service might dictate a *maximum* batch size, but clients should be free to use any value below that maximum. A batch size of 10 is on the small side, but with some services there's a reliability tradeoff when increasing it.

**Comment by tfmorris** [comment]
p.s. if the concerning is performance, pipelining multiple requests is another option for improving things.

**Comment by Abbe98** [comment]
Assuming that reconciliation services can actually handle their stated maximums I can only see benefits as it would reduce work for both the service and OpenRefine.

**Comment by Abbe98** [comment]
I'm convinced! 

I wonder, however, if we still couldn't use the parameter to send a better default to reconciliation services by taking the number of rows and maximum batch size into account? Dividing the number of rows with the maximum batch size and if it's above some threshold we could bump the batch size from today's 10?

**Comment by ayushrai206** [comment]
> I'm convinced!
> 
> I wonder, however, if we still couldn't use the parameter to send a better default to reconciliation services by taking the number of rows and maximum batch size into account? Dividing the number of rows with the maximum batch size and if it's above some threshold we could bump the batch size from today's 10?

Hello everyone, So are we finally going with this approach?

**Comment by wetneb** [comment]
Yes, let's try that, we can adjust if needed after testing.

**Comment by ayushrai206** [comment]
> I'm convinced!
> 
> I wonder, however, if we still couldn't use the parameter to send a better default to reconciliation services by taking the number of rows and maximum batch size into account? Dividing the number of rows with the maximum batch size and if it's above some threshold we could bump the batch size from today's 10?

Hey everyone,
Given that (no. of rows)/batch size tells us no. of times http request is sent, can someone please suggest me the threshold(by threshold i mean least no. of times we want http request for a particular dataset with n rows) for this ,considering the time needed per request should be optimal and the keeping in mind the error handling capacity of OpenRefine?Let's say the threshold is x, so i would need to bump up the batch size if - '(no. of rows)/batch size' is greater or equal to x.

**Comment by Abbe98** [comment]
**(suggestion)** I think that if a request would return the results for less than 1% of the dataset then we can bump the number, if batch_size allows for it, probably it can be be bumped until it's 1% again?  So that the user is communicated the progress 1% at the time.

**Comment by wetneb** [comment]
Let's go for that heuristic initially. Again, we can tweak as needed afterwards.

**Comment by wetneb** [comment]
@Abbe98 the heuristic you suggest is implemented by @ayushrai206 in #5992 as `Math.min(Math.max(rowCount / 100, 10), batchSize)`.

One of the test cases is for a service supporting batch sizes of up to 50, reconciling 1200 rows: that gives a batch size of 12. It feels a bit low to me.

I think it's not so crucial that the progress report is granular down to 1%. Personally I am okay to accept progress jumps of up to 10% if it helps speed up the entire process. I'll ask on the issue if people would agree with using  `/ 10` instead of `/ 100`. In that test case, that would mean we use the maximum batch size of 50, and progress would raise by increments of about 4%.

What do you (and others) think about that?

**Comment by Abbe98** [comment]
I'm just as happy with that!
