### ISSUE TITLE
Facets do not keep their size positions any longer in 3.8 snapshot

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#5606]
REGRESSION:  Text Facet (and maybe others?) is not keeping it's dimensions after I click to include a selection from the list.
See Video below (soon).

### To Reproduce
1. Create Text Facet
2. Then, click on include links for a few selections

### Current Results
Notice that upon every click on a *include* link, the facet window shrinks back to default size!

### Expected Behavior
Facet should remain with the size the user has changed it to (especially for long lists for easier browsing/analysis)

### Screenshots

https://user-images.githubusercontent.com/986438/216807735-ce179a85-b5d6-4f27-ae40-e1e36fa92ea5.mp4

### Versions
 - Operating System: Windows 11
 - Browser Version: Edge latest
 - JRE or JDK Version: JDK 17
 - OpenRefine: Version 3.8-SNAPSHOT [4d7571d]

**Comment by wetneb** [comment]
Thanks a lot for discovering this! We should have thought about it. This is probably the sort of bug we would not have if we were using a reactive framework because the DOM elements would get reused. We should look into whether we can fix that cleanly with the current framework.

**Comment by thadguidry** [comment]
and th;e cypress tests could be more robust about visaibility of elements in all dialogs that can reposition.

**Comment by elebitzero** [comment]
This regression is from the PR: https://github.com/OpenRefine/OpenRefine/pull/5514
