### ISSUE TITLE
On project creation memory usage reported incorrectly

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#5665]
### To Reproduce
1. Find a large data file that will take some time to create a project
2. Then, create a project from the data file
3. While the project creation is happening observe the memory usage reporting

### Current Results
Memory usage  is shown as consuming millions of percent of the available memory

### Expected Behavior
A relative accurate (or at least possible!) indication of memory usage is expected

### Screenshots
Screenshot from a recent forum posting
![6cc9cd3f9749bfbffe890b3289f990e650c8dfc6](https://user-images.githubusercontent.com/576174/222741448-b99fc032-be54-4338-b260-278f106d2442.png)

Source: https://forum.openrefine.org/t/large-csv-loading/478

### Additional context
I think this commit is the problem https://github.com/OpenRefine/OpenRefine/commit/6a7046323181dd0094058cc64d1171c166488cf4 

I suspect the order of calculation for the memory means that only the Runtime.getRuntime().freeMemory() is divided by 1048576 to get the value in MB, leaving the Runtime.getRuntime().totalMemory() in bytes - which then leaves the percentage calculation as wildly inaccurate

**Comment by wetneb** [comment]
Definitely worth fixing, and we can release 3.7.1 with that.
