### ISSUE TITLE
Star/Flag by Page

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#568]
_Original author: ericjarv...@gmail.com (May 05, 2012 16:29:52)_

This is a feature request;

-Ability to Star or Flag records/rows by page. 

Thanks,

Eric Jarvies

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=568_

**Comment by wetneb** [comment]
The use case for this is not clear to me, and we might get rid of pages altogether by moving to a scrollable grid, so closing.
