### ISSUE TITLE
The "Something is already running on <URL>.." error is incorrect

### ISSUE THREAD

**Issue by Abbe98** [OpenRefine/OpenRefine#5680]
### To Reproduce
1. First, try running OpenRefine on an invalid interface: `./refine -i gjksjd -p 333sd4`

### Current Results
The "Something is already running on <URL>..." will be displayed even although noting is running there

### Expected Behavior
The check running script is only checking if OpenRefine is running on the given interface, not if "something" is running, the error message should therefore, not say that something is already running there but rather give a more generic error. "OpenRefine isn't running on $URL."?

https://github.com/OpenRefine/OpenRefine/blob/ea017a7ff614aea7d0220e6230c6db18b6322622/refine#L143

**Comment by SaumyaBhushan** [comment]
Can I work on this issue ?

**Comment by SaumyaBhushan** [comment]
Hi, @wetneb created a PR. Please have a look.
