### ISSUE TITLE
Change the name of the NL localisation to "Nederlands"

### ISSUE THREAD

**Issue by verwinv** [OpenRefine/OpenRefine#5693]
### To Reproduce

The Dutch localisation / translation file [translation-nl.json](https://github.com/OpenRefine/OpenRefine/blob/cd7ca684328b6dc885642ae463f01b0e1744f45b/main/webapp/modules/core/langs/translation-nl.json) literally translates the `name` field to "Engels" due to which Dutch users get a confusing _preferred language_ dropdown option.

### Current Results

The _language settings_ > _Select preferred language_ dropdown now shows 'Engels' instead of 'Nederlands'.

### Expected Behavior

The _language settings_ > _Select preferred language_ dropdown would show 'Nederlands' instead of 'Engels'.

### Screenshots

<img width="576" alt="Screenshot 2023-03-15 at 21 04 00" src="https://user-images.githubusercontent.com/6201005/225429459-b97d14ed-7ef1-42db-8d0e-16f8e73ce44e.png">

### Versions
 - Operating System: macOS 13.2.1
 - Browser Version: Chrome version 111
 - OpenRefine: Version 3.7.1 [ecf4ff8]

**Comment by tfmorris** [comment]
Thanks for the report. Sorry about that! It looks like it got broken by e3585b758e3ce0eab898fa542f7a8de25f9eb4ff 7 months ago.

If you'd like to fix it yourself, you can do so using [Weblate](https://hosted.weblate.org/engage/openrefine/) and then change will propagate to the next release.

**Comment by verwinv** [comment]
Changed it in Weblate, cheers!
