### ISSUE TITLE
Locale-dependent tests failing with a French locale

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5696]
We have certain tests which fail when run on a machine with a French locale set:
```
[ERROR] Failures: 
[ERROR]   ForRangeTests.testForRangeWithFloatingPointValues:82->RefineTest.parseEval:352 Wrong result for expression: forRange(0,0.6,0.1,v,v.toString('%.3f')).join(',') expected [0.000,0.100,0.200,0.300,0.400,0.500] but found [0,000,0,100,0,200,0,300,0,400,0,500]
[ERROR]   ExcelImporterTests.readXlsxAsText:284 expected [100.00%] but found [100,00%]
```

This should not be the case.

**Comment by IjayAbby** [comment]
Hello, can this be treated as good first issue?

**Comment by IjayAbby** [comment]
Please point me to a good first issue that is focusing on JQuery

**Comment by wetneb** [comment]
You could pick one of [the ones which are tagged both as "good first issue" and "UI"](https://github.com/OpenRefine/OpenRefine/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+label%3AUI)
