### ISSUE TITLE
Improve look and feel of the issues tab of the Wikibase extension

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5702]
In the Wikibase extension, we offer a tab which displays various issues detected in the edits generated by the current Wikibase schema.

![image](https://user-images.githubusercontent.com/309908/177998450-a1a4e9f8-8031-48ec-8d46-6f39610104d1.png)

I made this UI but I find it pretty ugly:
* the icons for the warnings are too big, sort of pixelated (I think) and their style is inconsistent with OpenRefine's look and feel (we do not have anything similar anywhere else)
* it feels quite tight overall, and not very readable.

How could this be improved? Perhaps there are other changes we could think of to make this part of the UI more inviting?

**Comment by wetneb** [comment]
That looks much nicer, thank you! I still think we could find a better icon set for the warnings but that's likely a matter of taste.

**Comment by prashasti-7** [comment]
If unable to find consistent icons, we could try color-coding the issues. Red-Critical, Orange-Important, Yellow-Warning(as is used in many places), Blue-Information.

I was looking around for a suitable icon set; maybe we can try using WikiMedia's icon for [warning](https://github.com/wikimedia/mediawiki/blob/034e1849d36386463139c1d999044336d2b2094f/resources/lib/ooui/themes/wikimediaui/images/icons/alert-warning.svg), [information](https://github.com/wikimedia/mediawiki/blob/034e1849d36386463139c1d999044336d2b2094f/resources/lib/ooui/themes/wikimediaui/images/icons/info-progressive.svg), [critical](https://github.com/wikimedia/mediawiki/blob/034e1849d36386463139c1d999044336d2b2094f/resources/lib/ooui/themes/wikimediaui/images/icons/error-error.svg). They may seem plain as compared to our current icons. Still, they go well with our current design style(IMO).

**Comment by prashasti-7** [comment]
Yes actually, I was looking for 'Important' but there doesn't seem to be any in their library. 
According to this study, Red-Yellow-Blue is a safe option, but they do suggest that using icons is better. So maybe our best bet is using icons.

**Comment by prashasti-7** [comment]
**Update**

UI with the suggested MediaWiki icons and an additional yellow icon for 'Important':
![image](https://user-images.githubusercontent.com/108210025/226094596-aed008a1-e6b2-4aa8-9905-3a88760033fe.png)

**Comment by wetneb** [comment]
I think this looks really a lot cleaner, but I am curious to hear what others think.

**Comment by thadguidry** [comment]
yeap! cleaner, clear.  I would slightly increase the size if we could on the yellow icons and blue icon.  They appear slightly smaller in scale to the red icon.  Let's try to even out the size of them if we could.  Other than that I'd stretch the lowercase i vertically just a bit, to make sure it shows more readily as an i

**Comment by prashasti-7** [comment]
Sure!
I have made the changes as suggested by @thadguidry. Do you think this looks better?

![Frame 15](https://user-images.githubusercontent.com/108210025/226116576-da78fec1-ea5e-4db5-b4cb-668d8e946b4e.png)

**Comment by prashasti-7** [comment]
An addition could be to add a sidebar to each error
Something like this:
![Frame 16](https://user-images.githubusercontent.com/108210025/226170195-8e222442-2761-4d9a-bee4-86fc26b9b062.png)

**Comment by thadguidry** [comment]
@prashasti-7 I don't have strong feelings about the left border on each element div, but looks OK.  Hmm, the longer yellow border in your screenshot just gave me some questions for @wetneb ...

@wetneb  I don't know if we wanted to sort things better here also?
How are issues sorted in this dialog by default or always? To improve the UX, does the default sorting need to change?  Are all the issue categories actually entirely optional and just fail when uploaded if some issue categories are not resolved? Would those categories truly be considered as ERRORS that are not optional to fix but must be fixed prior to a user uploading?  If so, should we differentiate between OPTIONALS and REQUIRED somehow?

**Comment by wetneb** [comment]
I think this new design is great and could already be implemented relatively easily, hence the "Good first issue" label.

**Comment by t8210103** [comment]
Hello, i would like to be assigned this issue. Also, should I consider implementing a sidebar for each error as suggested, or would it be better to not include it?

**Comment by wetneb** [comment]
Fantastic! Personally I find the side color bars pretty nice, but of course it would already be a great improvement without them.
