### ISSUE TITLE
Add 'Jump to Page #' and itemized page numbers to the page.

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#571]
_Original author: ericjarv...@gmail.com (May 05, 2012 18:17:04)_
1. Add page number links to the 'previous/next' section so the user can jump forward/backward to a specific page, e.g.-
   &lt;&lt; first &lt; previous    1|2|3|4|5|6|7|8|9|10   next &gt; last &gt;&gt; 
   or
   &lt;&lt; first &lt; previous    10|20|40|80|160|320|640|1280   next &gt; last &gt;&gt; 
2. Add a search field to enter a page number so user can jump to a specific page, e.g.-
   Enter page number: [       ]  [Go]

Thanks,

Eric Jarvies

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=571_

**Comment by Rots** [comment]
As a workaround, is there a way to filter by row/record number?
E.g. setting the filter to `num>5100` would suffice in my use case to look at specific section of the input data.

**Comment by Rots** [comment]
Answering my own question, workaround is:
1. add a new column using rowIndex as value
2. add a numeric facet
3. filter on the facet

**Comment by tobinski** [comment]
@Rots I use your workaround and it saves me allot of clicking

**Comment by kushthedude** [comment]
@wetneb Is the page jumping needed? If yes, I would love to take this forward!

**Comment by wetneb** [comment]
I do not know, would that still be useful with an infinite scrolling in place? The notion of page would not be very useful anymore, would it?

**Comment by thadguidry** [comment]
Closing as this has been available since OpenRefine 3.5
In the input box for page number, you can also use up/down arrow keys to advance/reverse the page numbers in addition to using mouse clicks on next/previous etc.
Need to document that so... new issue #4452
