### ISSUE TITLE
Dialog mover

### ISSUE THREAD

**Issue by wumionwheels** [OpenRefine/OpenRefine#5714]
I don't know if this problem is only on the 3.7.1 version or on other versions too but on opening the reconciliation dialogue and moving it up to view the list down below, I couldn't move it back down (mover doesn't display on the footer section) which means I can't  move it back down as screen scroller is also not showing anymore since it is a dialogue

![FireShot Capture 023 - Portal rodents 19772002 scinameUUIDs csv - OpenRefine - 127 0 0 1](https://user-images.githubusercontent.com/23156958/226677429-94afeff4-bc10-4b17-8512-daf507141067.png)

**Proposal**
Add mover when hovering on footers section in a dialogue and probably to other similar dialogue that maybe affected by this

**Comment by elebitzero** [comment]
I don't think it is standard UX to allow someone to drag the footer of a dialog. The only potential change I would make would be to prevent the user from the dragging the dialog offscreen.

For example, Windows prevents dragging a dialog or window above the top of the screen.

**Comment by wumionwheels** [comment]
Oh that will be fine too
