### ISSUE TITLE
Localization of auto-complete fields in Wikibase schema broken since API update

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5716]
The behaviour of the Wikibase API's endpoint for auto-completion of entities (`wbsearchentities`) has changed and since that, the drop-down menu suggesting entities in the Wikibase schema editor displays entities in English regardless of the user's language.

### To Reproduce
1. First, set OpenRefine's language to something else than English, for instance French
2. Then, open a project or create a new one
3. In the Wikibase extension menu, make sure Wikidata is selected as the target Wikibase instance
4. Create a Wikibase schema and type a few letters (such as "mac") in the entity subject field (the only text field present in the schema editor by default)

### Current Results

Auto-completion results are shown in English.

### Expected Behavior
The results should be shown in the language selected by the user.

### Screenshots
![image](https://user-images.githubusercontent.com/309908/226701339-b9cf2e87-e452-49f0-9fa4-fef8771450d3.png)

### Versions
 - Operating System: irrelevant
 - Browser Version: Firefox
 - JRE or JDK Version: 17
 - OpenRefine: 3.7.1

### Additional context

Our code makes requests of the form:

https://www.wikidata.org/w/api.php?action=wbsearchentities&language=fr&search=mac&type=item&format=json

Those are missing the `uselang=fr` parameter, for them to return the expected results:

https://www.wikidata.org/w/api.php?action=wbsearchentities&language=fr&uselang=fr&search=mac&type=item&format=json

It should just be a matter of adding this extra parameter.

**Comment by mitrofmep** [comment]
Hello! I'd like to deal with this issue

**Comment by alemendoza-v** [comment]
@mitrofmep are you still working on this issue? If not I would love to try and tackle it :)

**Comment by wetneb** [comment]
Since it's been a month already I think you can go ahead :)
