### ISSUE TITLE
implementation of Live graphical representation of edited data to see how data is affected on editing

### ISSUE THREAD

**Issue by parmishh** [OpenRefine/OpenRefine#5731]
implementation of Live graphical representation of edited data to see how data is affected on editing
Currently it looks like:
<img width="960" alt="1234" src="https://user-images.githubusercontent.com/91942072/227757624-dbe9c5e3-4f31-41c4-8c46-6107c9fba1f8.PNG">

### Proposed solution
@wetneb I would like to work on it if this feature is relevant you can assign to me😊
after Live graphical representation of edited data
it will look something like:

![AddText_03-26-11 16 51](https://user-images.githubusercontent.com/91942072/227757782-c0799f31-419a-4c78-924c-f3d628774810.png)

**Comment by wetneb** [comment]
Thanks for the proposal @parmishh!
Adding some data visualization capabilities to OpenRefine could definitely be interesting and it would be useful in a lot of use cases. Perhaps it is worth refining your proposal a bit before jumping in an implementation though. Looking at your proposal above, your plots seem to float freely in the grid view, so it's not clear to me how they integrate in the UI. How would the user go about creating those plots and configuring them? Those are just random questions that come to mind looking at your proposal.
If you want to start contributing code to OpenRefine it might be easier to start with a [good first issue](https://github.com/OpenRefine/OpenRefine/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).

**Comment by parmishh** [comment]
@wetneb Got it, Here is a detail approach answering the questions.
Keeping the aspect ratios same we can create a new section just like on the left to the right which would be used to display the graph while making changes this section will be collapsible so that user can close it if not needed.

 There will be three options to choose  one will be to choose the type of graph user want the other two will be for choosing the X-axis and Y-axis as there can be multiple attributes present in our data So the user will have to choose between which two attributes the graph is to be plotted this can be done via these two options.

I have done similar implementation for a website but was in different language but I would be able to implement it here as well as I can have a feel by having a look to the code. You can assign this to me So that I can start Experimenting on this.
However any suggestions regarding this solution is highly welcomed, That will help me improve it.
.
The solution summing up will look something like this:

![AddText_03-26-04 44 00](https://user-images.githubusercontent.com/91942072/227772645-2b22c1be-0635-4f34-8eeb-542d34082bec.png)

**Comment by wetneb** [comment]
I think there are still a lot of open questions on the design (perhaps you could look into improving the existing scatterplot facet instead, for instance?) but feel free to have a go at this for sure.

**Comment by parmishh** [comment]
@wetneb Thanks for valuable suggestions, will keep them in mind while working on it.

**Comment by wetneb** [comment]
Hi @parmishh, are you still working on this?

**Comment by parmishh** [comment]
Yeah, will give final update next week.

**Comment by tfmorris** [comment]
I agree that finding space in the left hand panel, either in the Facets tab or a separate tab, might fit better. If an entirely new piece of screen real estate is going to be carved out, it'd make sense to think through what else, if anything, it can be used for, and how it's managed.

**Comment by thadguidry** [comment]
I do not want to see charting, plotting, bargraphs, list goes on, being put into the core of OpenRefine.
(if this is an extension, great! and let's make that apparent, and label this issue appropriately)

With that being said:
Visualization libraries are plentiful, and visualization platforms are plentiful.  OpenRefine can be part of a roundtripping workflow if the visualization platforms out there could integrate or simply talk to the OpenRefine public API (if we had a public one).

I have been vocal before about my concerns with reinventing the wheels of others (and other programs) that do data visualization so well and continue to evolve rapidly.  We could never keep up and should not even try.  However, as an extension, a light statistics facet #2001 or data profiling extension #5315 is still on my dream list for folks to build.  And recall someone has yet to build the Renjin / OpenRefine extension #1226 which would allow seamless zero-overhead data sharing between R lang and OpenRefine and provide OpenRefine users with thousands of CRAN packages, like http://packages.renjin.org/package/org.renjin.cran/xray and others.

I continue to encourage communities that have data cleaning AND data visualization needs to reach out to the visualization software communities to see what THEY could do with OpenRefine and what WE could do to open up our communication pathways and API's for zero-overhead data sharing between them and help them integrate better for the benefit of both our shared user communities.  That was always our dream towards extensibility of OpenRefine during its early life.

**Comment by wetneb** [comment]
I think this issue is too broad to be actionable for developers or designers, so it is unlikely to get worked on in this form. Closing, feel free to reopen if you disagree.
