### ISSUE TITLE
(Un)star/flag action reverts unrelated cell reconciliation judgments

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5738]
Starring or flagging an individual row reverts any manual reconciliation action on a cell in that row.

### To Reproduce
1. First, reconcile a column
2. Then, make a reconciliation judgment in one of the cells of that column. The action should only impact that single cell (not similar cells).
3. Finally, change the star or flag status of the same row

### Current Results

The reconciliation action of step 2 is visibly reverted (but only client-side, not server side: if the grid is refreshed, we see that it was not actually reverted).

### Expected Behavior

The action in step 2 should not be visibly reverted.

### Screenshots
![Peek 27-03-2023 21-32](https://user-images.githubusercontent.com/309908/228047366-60e94113-16c1-443f-9a13-41b4f0a3a8d5.gif)

### Versions
 - Operating System: Linux
 - Browser Version: Firefox
 - JRE or JDK Version: 17
 - OpenRefine: 3.8-SNAPSHOT

### Additional context

Reported on the forum: https://forum.openrefine.org/t/unstarring-reverts-un-reconciliation/672

**Comment by SoniaSun810** [comment]
> Starring or flagging an individual row reverts any manual reconciliation action on a cell in that row.
> 
> ### To Reproduce
> Steps to reproduce the behavior:
> 
> 1. First, reconcile a column
> 2. Then, make a reconciliation judgment in one of the cells of that column. The action should only impact that single cell (not similar cells).
> 3. Finally, change the star or flag status of the same row
> 
> ### Current Results
> The reconciliation action of step 2 is visibly reverted (but only client-side, not server side: if the grid is refreshed, we see that it was not actually reverted).
> 
> ### Expected Behavior
> The action in step 2 should not be visibly reverted.
> 
> ### Screenshots
> ![Peek 27-03-2023 21-32](https://user-images.githubusercontent.com/309908/228047366-60e94113-16c1-443f-9a13-41b4f0a3a8d5.gif) [ ![Peek 27-03-2023 21-32](https://user-images.githubusercontent.com/309908/228047366-60e94113-16c1-443f-9a13-41b4f0a3a8d5.gif) ](https://user-images.githubusercontent.com/309908/228047366-60e94113-16c1-443f-9a13-41b4f0a3a8d5.gif) [ ](https://user-images.githubusercontent.com/309908/228047366-60e94113-16c1-443f-9a13-41b4f0a3a8d5.gif)
> 
> ### Versions
> * Operating System: Linux
> * Browser Version: Firefox
> * JRE or JDK Version: 17
> * OpenRefine: 3.8-SNAPSHOT
> 
> ### Additional context
> Reported on the forum: https://forum.openrefine.org/t/unstarring-reverts-un-reconciliation/672
