### ISSUE TITLE
Choose File Button - MAC

### ISSUE THREAD

**Issue by wumionwheels** [OpenRefine/OpenRefine#5743]
Today, I downloaded OpenRefine on my Mac, having previously used Windows. When attempting to upload a file, I received an error message stating, "You must specify a data file to import." I was confused and unsure of what I had done wrong. After reviewing the page again, I realized that I had clicked on the wrong button - the "Next" button caught my eye instead of the "Choose File" button. The problem was that the "Choose File" button was not as noticeable, as it was a white button with regular text and only a small shadow around it, which is different from what is used on Windows. 

### Proposed solution
A possible solution would be to either implement the same design as on Windows or to make the "Choose File" button a blue text icon that is consistent with the OpenRefine design.

### Additional context
shot on mac
<img width="1300" alt="Screenshot 2023-03-28 at 06 06 36" src="https://user-images.githubusercontent.com/23156958/228260389-fbcbf837-96f4-485f-972c-a7c174283276.png">

shot on windows
![FireShot Capture 001 - OpenRefine - 127 0 0 1](https://user-images.githubusercontent.com/23156958/228261526-590fc553-cda4-4934-afb7-82c9ebd5c52b.png)

**Comment by wetneb** [comment]
I think it used to be the case that such a button could not be styled - it had to be defined by the operating system. But it might well be that with the newer Javascript APIs it is possible to style this button. If such APIs are widely supported enough I think it could be worth it.

**Comment by ostephens** [comment]
This SO post suggests Javascript isn't needed to do styling https://stackoverflow.com/questions/572768/styling-an-input-type-file-button/25825731#25825731

**Comment by wumionwheels** [comment]
Oh yeah, that's true @ostephens, just checked it on chrome and it works fine. That means the problem is with Safari browser
