### ISSUE TITLE
Refine script support for the Google extension

### ISSUE THREAD

**Issue by elebitzero** [OpenRefine/OpenRefine#5778]
The refine.ini declares three variables for the Google extension: GDATA_CLIENT_ID, GDATA_CLIENT_SECRET, and GDATA_API_KEY
https://github.com/OpenRefine/OpenRefine/blob/53466223ef11aad83422d5989db995cda8ff69ec/refine.ini#L29

refine checks for these, and if all three are set it passes corresponding definitions to the OpenRefine Java process
```
-Dext.gdata.clientid=%GDATA_CLIENT_ID% -Dext.gdata.clientsecret=%GDATA_CLIENT_SECRET% -Dext.gdata.apikey=%GDATA_API_KEY%
```

The Linux refine script parses for `-k <google_api_key>`, but it doesn't do anything. This option is mentioned in the docs, but not in the `refine /h` usage statement.

The scripts should be made consistent.

Options (One of the following):
* Remove the -k option from the Linux refine script.
* Remove all references to google extension from the refine scripts. The user would have to add variables to the JAVA_OPTIONS in refine.ini to enable the google extension.
```
JAVA_OPTION= -Dext.gdata.clientid=%GDATA_CLIENT_ID% -Dext.gdata.clientsecret=%GDATA_CLIENT_SECRET% -Dext.gdata.apikey=%GDATA_API_KEY%
```

**Comment by thadguidry** [comment]
@elebitzero @wetneb This needs an update to our technical docs somewhere as well, correct?  I don't see `gdata` variables mentioned other than an extension reference first paragraph here: https://openrefine.org/docs/technical-reference/migrating-older-extensions#how-to-migrate-an-extension

Or is the mention of the `gdata` variables in our `refine.ini` enough documentation?
