### ISSUE TITLE
CI test failure

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5793]
The CI currently fails with:
```
Error:  Tests run: 720, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 57.881 s <<< FAILURE! - in TestSuite
Error:  com.google.refine.operations.recon.ReconOperationTests.serializeReconProcess  Time elapsed: 0.013 s  <<< FAILURE!
```

This is since a localization update which is obviously unrelated.

Example run: https://github.com/OpenRefine/OpenRefine/actions/runs/4730695127/jobs/8394730586

**Comment by tfmorris** [comment]
> This is since a localization update which is obviously unrelated.

The serialization of operations includes their natural language description, so it seems like it could easily be related to a localization change if the locale isn't pinned or if the localization change inadvertently changed the description in English.

**Comment by wetneb** [comment]
That's an excellent point, I forgot we had backend localization now.
