### ISSUE TITLE
The free memory info is inconsistent between refine and refine.bat

### ISSUE THREAD

**Issue by elebitzero** [OpenRefine/OpenRefine#5795]
I noticed that refine.bat prints out the Java version and "Getting Free Ram...", and then it outputs info in a support.log.

The Linux refine script outputs a banner "You Have xxx M of free memory" but does not write a support.log.

I think it is simpler to just output everything on the command-line rather than output extra info to a support.log.
I would modify refine.bat to output the same banner message that refine script has for the free memory.

Windows refine.bat
```
>refine.bat run
Java 17 (17.0.2)
Getting Free Ram...
21:23:11.511 [            refine_server] Starting Server bound to '[127.0.0.1:3333](http://127.0.0.1:3333/)' (0ms)
21:23:11.517 [            refine_server] refine.memory size: 16384M JVM Max heap: 17179869184 bytes (6ms)
```

Windows support.log
```
-----------------------
PROCESSOR_ARCHITECTURE = AMD64
JAVA_HOME = C:\Program Files\Java\jdk-17.0.2
java release = 17
java -version = 17.0.2
freeRam = 31875 MB
REFINE_MEMORY = 16384M
-----------------------
```

Linux refine run
```
$ ./refine run

Using refine.ini for configuration
-------------------------------------------------------------------------------------------------
You have 7948M of free memory.
Your current configuration is set to use 1400M of memory.
OpenRefine can run better when given more memory. Read our FAQ on how to allocate more memory here:
https://openrefine.org/docs/manual/installing#increasing-memory-allocation
-------------------------------------------------------------------------------------------------

21:36:21.505 [            refine_server] Starting Server bound to '[127.0.0.1:3333](http://127.0.0.1:3333/)' (0ms)

21:36:21.510 [            refine_server] refine.memory size: 1400M JVM Max heap: 1468006400 bytes (5ms)

21:36:21.534 [            refine_server] Initializing context: '/' from '/home/github/OpenRefine/main/webapp' (24ms)
```

**Comment by thadguidry** [comment]
### History
The support.log has been useful in the past, when we had users with locating their default JAVA_HOME path.  And when we had the Java 8/11 issues prior to the fixes @wetneb did, we could see which Java version that OpenRefine would be using.  We could use the support.log to see how their system was setup and any system path issues in locating the JRE/JDK.

### Now
So we made things a bit better when we supported Java 17+ and then introduced a Windows-with-Java release.
The support.log is still a bit useful for those that are not using that with-Java release, but when the Java issues come up on the non-Java release, we typically just point them to downloading and using that... rather then even looking at support.log and trying to help them with their JRE/JDK system issues.

### Future
I would say it is fine to remove the support.log handling for the future.  Installation, starting/stopping, and JRE/JDK issues are all minor now, if not getting more robust in the near-term future.
Using the free ram calculation in the Windows script currently, it should indeed be changed to output the same banner style in command stdout as we had before, like it is now in the Linux script.
