### ISSUE TITLE
Duplicates facet computing incorrectly after undoing row removal

### ISSUE THREAD

**Issue by jquartel** [OpenRefine/OpenRefine#5799]
I often use the 'duplicates' built-in facet and recently I noticed that it was reporting incorrectly after I had undone a row removal operation. I find this is reproducible - see the attached images and the dataset I used for this demo:

1. Load a file with a column that has duplicates
2. Apply the **Facet > Customized facets > Duplicates facet** to that column and note that it shows the duplicates as a 'true' set
3. Remove rows (whichever way you like) so that there are no longer duplicates and note that the facet is now showing only 'false'. (In my example here I starred the second line, faceted by star, and removed matching, but I could have done this a little easier by faceting on Col1, selecting "B", and then removing)
4. Undo the row removal and observe that the facet is still showing only 'false' even though all the duplicates are back. You can even add a new duplicates facet on the column and it will only show 'false'
<img width="499" alt="Original load" src="https://user-images.githubusercontent.com/36742596/233584964-994b9fc8-3c4f-470a-afc1-ad7c09b9487b.png">
<img width="496" alt="Undo row removal" src="https://user-images.githubusercontent.com/36742596/233584973-1cc44900-d50d-4eeb-b971-08cb149bcd16.png">
<img width="495" alt="Facet not returning to original state" src="https://user-images.githubusercontent.com/36742596/233584968-d6130e53-8afa-47eb-aedf-5635ae5434ce.png">

Note that in my use case I often modify the facet to show the duplication count (i.e. `facetCount(value, 'value', 'Col2')`) but the problem is the same.

### Versions
 - Operating System: MacOS 12.6.5
 - Browser Version: Safari 16.4.1
 - OpenRefine: 3.7.2 [f7ad526]

[Simple.txt](https://github.com/OpenRefine/OpenRefine/files/11293737/Simple.txt)

**Comment by tfmorris** [comment]
Good catch! This is basically the other half of #567. I fixed the first half 11 years ago, but this has been lurking for more than a dozen years.
