### ISSUE TITLE
Test coverage dropped to 45.9% from 47.5% in last 7 months

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#5805]
Because incremental coverage results haven't been posted during this period, it'll take some investigation to figure out what caused the decrease.

### Current Results
https://coveralls.io/builds/59203556

### Expected Behavior
Coverage increases continuously rather than decreasing

**Comment by wetneb** [comment]
Interesting! I also would not expect such a sharp drop. My bet is that it is down to a difference in how coverage was computed with the previous pipeline and your new one (not claiming the previous one was the "right" one though). The way coverage reports are aggregated can make a difference, or other fiddly details.

**Comment by tfmorris** [comment]
Actually it looks like the sets of tests aren't comparable (e.g. no extensions in the new results), so this needs a closer look.

**Comment by tfmorris** [comment]
The new Coveralls coverage reporter doesn't seems capable of doing the source directory mapping that the Maven plugin does. A one-time change isn't the end of the world, but it does make things harder to compare.

Re-uploading the results using the Maven plugin shows that coverage on the Refine core **increased** from 47.5% to 48.4%, as expected/desired. Overall coverage decreased from 54% to 52.8%, but that was pretty much entirely apparently due to the database extension tests only running minimally, perhaps due to local environment setup. Although this doesn't seem like super desirable behavior, I'm guessing that the databases would be setup correctly in the CI environment, so I'm going to close this.
