### ISSUE TITLE
Improve/Shorten pull_request.yml e2e test names

### ISSUE THREAD

**Issue by elebitzero** [OpenRefine/OpenRefine#5808]
The PR ui_tests names are cut off in the 'Checks' section. Because of this, the runtime is not visible:

![image](https://user-images.githubusercontent.com/42903164/233754808-3f359018-9311-499e-9c46-b6b7f25dcff9.png)

Also, ui_test is actually an e2e test and not just a UI test.  So, it should be changed to e2e_test to be more accurate.

Proposed Changes:

* Update the scripts so that the e2e tests look something like this:

  CI / e2e_test Project
  CI / e2e_test Column
  CI / e2e_test Facet
  CI / e2e_test Reconcile
  CI / e2e_test Misc
  CI / e2e_test Undo

* Change "refine ui_tests" to "refine e2e_tests"

**Comment by wetneb** [comment]
Makes sense to me!
