### ISSUE TITLE
New column from Freebase values freezes Google Refine

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#582]
_Original author: EricHF...@gmail.com (June 01, 2012 22:52:29)_

<b>What steps will reproduce the problem?</b>
1. Import data set of more than 1 million rows
2. Reconcile column to Freebase City/Village
3. Attempt to add column based on Freebase values &quot;Contained by&quot;

<b>What is the expected output? What do you see instead?</b>
Expected to see new column with &quot;Contained by&quot; values. 

Instead, it fetches and hangs at &quot;100&#37;&quot;, leaving CPU usage extremely and does not &quot;finish&quot; adding the new column, no matter how long I wait (waited at least 30 min). Tried over and over again, even with smaller numbers of rows (less than 10 rows)

<b>What version of Google Refine are you using?</b>
2. 5
<b>What operating system and browser are you using?</b>
Mac OS X, used Safari and Chrome

<b>Is this problem specific to the type of browser you're using or it happens</b>
<b>in all the browsers you tried?</b>
All browsers

<b>Please provide any additional information below.</b>
In the end, I simply exported the rows I wanted to match into CSV and started a new project. The new project had &lt;5000 rows and worked seamlessly.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=582_
##

**Comment by wetneb** [comment]
This seems to be a generic issue of dealing with large projects. Just get more memory and increase heap space.
