### ISSUE TITLE
invert text facet

### ISSUE THREAD

**Issue by fabiolinus** [OpenRefine/OpenRefine#5827]
Hi. Text Facet is a common and useful feature in OpenRefine. I usually choose several values as a multiple OR. If you switch to inverse mode, then the filter is correctly updated. The point is that counts are visualized with a minus sign before (see image). I don't understand why. Is this a bug or not?

![Untitled](https://user-images.githubusercontent.com/33990409/236697054-bebe1785-94a5-4aaf-8c3e-767c4661e63e.png)

**Comment by antoine2711** [comment]
No, it's not a bug. It shows who much rows with that string are hidden.

You might consider first asking thoses questions in the forum:
https://forum.openrefine.org/

Regards,
   Antoine

**Comment by fabiolinus** [comment]
Hi Antoine. I see a minus sign in each item of the text facet. In my example rows with bbb are visible but the show a minus sign too. Why?

**Comment by wetneb** [comment]
I think the idea behind showing a minus sign is to signify that by including this option in the facet, you will be *removing* that many rows/records from the view given that the facet is inverted.

**Comment by fabiolinus** [comment]
Thanks to all
