### ISSUE TITLE
Remove the distinction between change and operation

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5856]
Historically, OpenRefine has relied on two sorts of classes to represent transformations on the project grid:
* Changes, which stored the concrete "diff" between before and after the transformation. Those objects were often heavy, as they store all the values that differ between the two grids
* Operations, which are the higher-level description of the transformation, in a way which can be reapplied on other projects later.

Not every change corresponds to an operation: for instance, when editing a single cell, this applies a Change to the grid without a corresponding operation. In the undo/redo panel, this manifests itself by the fact that the corresponding history entry cannot be selected to be exported to JSON. See more details about the architecture:
https://openrefine.org/docs/technical-reference/architecture-before-4

[In 4.0](https://openrefine.org/docs/technical-reference/architecture-4), I have so far kept this distinction. However, I think it is not so helpful anymore, for the following reasons:
* Change objects are now very lightweight, because they apply to the grid lazily. If any values must be computed eagerly and cached, this is done in a ChangeData object, which is separate from the Change object. In fact, when loading a project, all changes which make up the history are now loaded at all times.
* The distinction between changes which are generalizable to other grids and those which are not is now more of a sort of "editorial choice" rather than a technical constraint. As such it does not justify a duplication of both layers: it could as well be a boolean flag on the single class that represents the transformation.
* Change and Operation objects essentially share the same attributes, because the Change objects need to be able to execute the transformation on demand, so creates a lot of bureaucratic duplication that should not be needed.
* Changes which do not correspond to operations cannot be applied via the `apply-operations` command so I had to keep dedicated Command classes for those. Merging the classes would also let us get rid of those commands.

### Proposed solution

Merge both classes into one and introduce a boolean flag indicating whether an operation is meant to be generalizable.
We could make the decision to still let users decide to include non-generalizable operations in their workflows if they want (perhaps the datasets they work on consistently have the same sort of problem in a row at a fixed location?), or keep the current UX.

### Alternatives considered

Status quo.

### Additional context

This feels like a sensible preparation for the work on column dependencies, because it will simplify the architecture before we introduce more complexity.

**Comment by wetneb** [comment]
@thadguidry naming things is hard indeed!

> Does "ChangeData" only deal with datagrid transformations, never Fetch or Facets, or Clustering, etc., so maybe it's better to just say "ModifyGrid" or "ModifyGridState" as it's new name?

`ChangeData` is meant to be understood as "data of a change", not "to change data". A `ChangeData` object stores the eagerly computed data that is associated with an operation. So `ModifyGrid` would not work. Does any better name come to mind with this description?

**Comment by thadguidry** [comment]
`Transform`
`TransformContext`
`TransformId`
`TransformSerializer`
`TransformStore`

`RecordTransformProducer` seems much more readable, sensible compared to `RecordChangeDataProducer`

I just think the model naming is slightly askew of what many other ETL, workflow, dataflow projects like Apache NiFi and [Apache Hop](https://hop.apache.org/manual/latest/getting-started/hop-concepts.html), [Apache Camel](https://camel.apache.org/manual/transformer.html) and many others adhere to [eip - Enterprise Integration Patterns](http://www.enterpriseintegrationpatterns.com/)

An example of name clashing against semantics.  "DataStore", "Store - what kind? a ChangeData store", "what specific kind? a File ChangeData store"
> FileChangeDataStore
A {@link ChangeDataStore} which stores change data on disk. This is the default one used in OpenRefine. <br>
> * It makes use of two directories:

A much better name would be `TransformFileStore` to conincide with `TransformStore` (ChangeDataStore).

Our current model naming reminds me of CDC - Change Data Capture which is a SQL logging and playback system.  Our History is a kind of log and playback system, but towards storing transforms or sets of transforms.

I can see the connected lines between a Process (ProcessManager.java for example) with it's `getProcess` method and a ChangeData (ChangeDataId) which begs for a better naming strategy, I think.

Process,
HistoryEntry
  Transform (Change),
  Transform (Change),
  Transform (Change),
  Operation ?,
  Transform (Change),

I think "Change" is the wrong model name to evoke.
> A ChangeData object stores the eagerly computed data that is associated with an operation.

**Then why not call it `OperationData` ?  Why introduce a tangential term?  See the confusion this causes?**

> The interface between runners and the application logic principally consists of the following interfaces:
> * `DatamodelRunner`, which is the main entry point of the implementation and lets instantiate other classes;
> * `Grid`, which represents the state of the project at some point in a workflow;
> * `ChangeData`, which represents some data fetched or generated during an operation, which is serialized separately. It can be joined with a `Grid` to generate a new state incorporating this change data.

> Both `Grid` and `ChangeData` are immutable: the grid or change data they represent cannot be modified through
these interfaces. Instead, to transform them, one derives new instances of those interfaces.

Maybe `GridChange` is the ideal name. Dunno.

Maybe @tfmorris or @ostephens could step in and help a bit with this part.

**Comment by tfmorris** [comment]
> I wonder if this is not a good opportunity to just come up with a new word (like Wikibase uses "snak" to refer to a part of its data model),

Using nonsense words to name key data structures is a terrible idea. The Wikibase designers' laziness should not be emulated.

The problem with "Change" (and "Transform") is that it's both a noun and a verb, making the meaning of `ChangeData` ambiguous. `OperationData` or `TransformationData` (not TransformData) would be improvements, in my opinion, but I just [read](https://forum.openrefine.org/t/reproducibility-project-may-progress-report/786/1) that it's unknown if this model works with columnar storage (or perhaps that it's known that it doesn't), so it may not be worth investing a lot of effort in finding the perfect name until that issue is worked out.

**Comment by wetneb** [comment]
@tfmorris it's probably a discussion we should rather continue on the forum (or at least elsewhere) but I would be interested to discuss columnar storage more: you seem to think it's a must? At the moment I have the impression that this will likely not have a noticeable impact for users but requires a big amount of work. But it's just a very preliminary opinion.

**Comment by tsukipedia** [comment]
Is this issue up to date?

**Comment by wetneb** [comment]
It's implemented in the 4.0 branch, but I had kept this issue open in the hope that we'd find a consensus about what to rename "ChangeData" into. Let's just keep it like that and close this issue.
