### ISSUE TITLE
Add a visual indicator/button for expanding collapsed columns

### ISSUE THREAD

**Issue by Abbe98** [OpenRefine/OpenRefine#5879]
### Proposed solution

@wetneb [pointed out](https://github.com/OpenRefine/OpenRefine/pull/5869#issuecomment-1567269708) that there is no longer an indicator that one can click the header of a collapsed column to expand it. We should bring this back but rather than just have the mouse cursor change lets add a proper button(semantically not necessarily visually) so it works from the keyboard this time around.

### Alternatives considered

The cheap solution of making sure the cursor changes one again on hover when a column is collapsed.

### Additional context

I removed the cursor effect in #5869 and I think that's still a good change given the odd behavior of changing the cursor on non-clickable expanded columns as well.

**Comment by VhugoJc** [comment]
@Abbe98 Can I get assigned this Issue?
