### ISSUE TITLE
Running into dependency issue on Linux 

### ISSUE THREAD

**Issue by 5tigerjelly** [OpenRefine/OpenRefine#5880]
### To Reproduce
I started a linux instance and installed all dependencies. I am able to run `./refine` after cleaning and building. However I am running into some issues where it cannot locate the `select2`, `jQuery` when running the server on the browser. It looks like some dependency installation issue, but not sure how to fix 

### Current Results
```
GET http://127.0.0.1:3333/3rdparty/select2/select2.css net::ERR_ABORTED 404 (Not Found)
:3333/:44 

 GET http://127.0.0.1:3333/3rdparty/tablesorter/theme.blue.css net::ERR_ABORTED 404 (Not Found)

index-bundle.js:18 Uncaught ReferenceError: jQuery is not defined
    at index-bundle.js:18:12
    at index-bundle.js:20:4

VM12:1 Uncaught TypeError: Cannot set properties of undefined (setting 'encodings')
    at VM12:1:18
```

### Expected Behavior
Fully running open refine

### Screenshots
<img width="646" alt="image" src="https://github.com/OpenRefine/OpenRefine/assets/15973528/58f814d4-030d-4a4f-9939-f08331ea9cb8">

### Versions
 - Operating System: Linux 
 - Browser Version:Chrome
 - 
 - JRE or JDK Version: openjdk 11.0.19 2023-04-18
 - OpenRefine: 4.0 branch

**Comment by Abbe98** [comment]
Do you have the same issue on the `master` branch?

**Comment by wetneb** [comment]
It could be worth seeing your entire build logs (output of `./refine clean` and `./refine build`).

**Comment by 5tigerjelly** [comment]
This was the output using 4.0 branch : https://gist.github.com/5tigerjelly/6a631bc192b99ce5d5312c3d6e43de31

This was the output using master branch : https://gist.github.com/5tigerjelly/d8217e24e9d8c432becc6bed2b781185

**Comment by 5tigerjelly** [comment]
I think this might be the issue 
```
Using refine.ini for configuration
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> open-refine-webapp@ postinstall /home/tigerjelly/Documents/OpenRefine/main/webapp
> node copy-dependencies.js

/home/tigerjelly/Documents/OpenRefine/main/webapp/copy-dependencies.js:1
import fs from 'fs';
       ^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! open-refine-webapp@ postinstall: `node copy-dependencies.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the open-refine-webapp@ postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tigerjelly/.npm/_logs/2023-05-30T12_32_28_435Z-debug.log
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```

**Comment by wetneb** [comment]
We really should document the minimum Nodejs version in https://openrefine.org/docs/technical-reference/contributing.

Here are my versions (for which building OpenRefine works):
```
$ npm --version
8.19.3
$yarn --version
1.22.19
$ node --version
v16.19.1
```

**Comment by 5tigerjelly** [comment]
I am still confused by the two responses. Is `const fs = require('fs');` the desired update or no?

**Comment by wetneb** [comment]
If that makes it possible to lower the minimum Nodejs version I think it's worth it! It would be useful to know which version you are running.

**Comment by 5tigerjelly** [comment]
Here are the versions

npm --version
6.14.4
$yarn --version
not installed
$ node --version
v10.19.0

I will make the PR

**Comment by wetneb** [comment]
@5tigerjelly do you still plan on making a PR for this?

**Comment by 5tigerjelly** [comment]
created [pull/5916](https://github.com/OpenRefine/OpenRefine/pull/5916)

**Comment by elebitzero** [comment]
Node 14 and below are end-of-life, and Node 16 reaches end-of-life October 2023.
(Ref: https://nodejs.dev/en/about/releases/)

So, we should no longer support Node 10, 12, and 14 for development of OpenRefine.
