### ISSUE TITLE
Manage Wikibase schemas should use a list (auto numbered) to improve display

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#5893]
Currently, the Manage Wikibase schemas dialog shows slight grey rows for each schema to be managed.
If one row only appears, then this looks awkward because the grey row with a schema name looks like some kind of header for the dialog, instead of a row element.  It would be better to tweak the display so that rows get numbered automatically.

### Current Results
![image](https://github.com/OpenRefine/OpenRefine/assets/986438/f30f624d-64d9-4a2e-ab62-4b341beb0759)

### Expected Behavior
Rows are numbered as in this example (number just before the schema row for `test`).
If a 2nd schema was defined then I would expect numbered rows 1. and 2.

![image](https://github.com/OpenRefine/OpenRefine/assets/986438/517d5d0f-2749-44dc-8ad0-d8d135229f88)

### Versions
 - Operating System: 
 - Browser Version: 
 - JRE or JDK Version: 
 - OpenRefine: 

### Additional context
From Forum support topic https://forum.openrefine.org/t/where-is-export-import-schema-option-in-or-wikidata-extension-now/784

**Comment by Hisiste** [comment]
Hi! I'm quite new to Open Source. Can I take this issue? :)

**Comment by wetneb** [comment]
@Hisiste please go ahead! Our guide for first code pull requests is here: https://openrefine.org/docs/technical-reference/contributing#your-first-code-pull-request

**Comment by Hisiste** [comment]
Great! Thank you very much. If I get stuck with this issue, can I ask you @wetneb for hints?
