### ISSUE TITLE
Improve reliability of Coveralls integration

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5909]
The Coveralls integration could be improved:
* [x] the submission of coverage (and even running Java tests?) could be skipped for PRs which do not make any changes to Java files, resources, and pom.xml files (complete list to be checked!)
* [x] the test coverage of generated Java files (for localization) should be ignored
* [x] any tests showing non-deterministic coverage results should likely be cleaned up to avoid spurious coverage variations (see #5898 for instance)

**Comment by elebitzero** [comment]
@wetneb, tomorrow I can work on splitting the pull_request.yml to only build the Linux and Windows servers based on the path, unless you already doing it. Let me know. Thanks.

**Comment by wetneb** [comment]
That would be amazing, but I would also be happy to do it if you prefer. As you wish!

**Comment by wetneb** [comment]
I looks like one remaining source of coverage statistics going up and down is in the coverage of `CalendarParser.java` which goes up and down depending on the build time (likely because the current time is being parsed somewhere and that triggers different code paths in the parser).

See for instance https://coveralls.io/builds/66381077

If we want more stable coverage statistics we could make sure those code paths are covered by independent tests.

**Comment by tfmorris** [comment]
That particular example looks like a JVM finally enforcing a long standing deprecation of the use of internal class             `sun.util.calendar.ZoneInfo`. Does it correlate with JVM version?

https://coveralls.io/builds/66381077/source?filename=main%2Fsrc%2Fcom%2Fgoogle%2Frefine%2Fexpr%2Futil%2FCalendarParser.java#L764

I have a simple fix buried on a branch somewhere that I could probably dig out.

**Comment by wetneb** [comment]
I can't figure out from the Coveralls report which lines are the 26 lines for which coverage differs from build to build. @pkumar2001 has kindly volunteered to improve the test coverage of this class, perhaps that will surface unreachable paths, but if you have fixes available it's of course great to have them too!

**Comment by tfmorris** [comment]
> I can't figure out from the Coveralls report which lines are the 26 lines for which coverage differs from build to build. 

If you click on the link I posted, they are the lines 785-825 which are highlighted in red (offset by a couple of lines of green in the IllegalAccessException handler).

**Comment by wetneb** [comment]
Closed by #6409 and #6476

**Comment by tfmorris** [comment]
> That particular example looks like a JVM finally enforcing a long standing deprecation of the use of internal class sun.util.calendar.ZoneInfo. Does it correlate with JVM version?

I confirmed that the reduced coverage correlates with Java 21, which apparently has disabled reflective access to this class/method, so the Java 11 & Java 21 test coverages are self-consistently deterministic, but coverage varies (varied) with Java version.
