### ISSUE TITLE
Reconciliation services can be added multiple times

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5926]
When adding a new reconciliation service in the reconciliation dialog, we do not check if the service being added is already in the list.

### To Reproduce
1. First, add a reconciliation service
2. Then, add it again

### Current Results

The service is added twice.

### Expected Behavior

The service list should not have any duplicates.

### Additional context

Reported by @fsteeg. Maybe an interesting issue for @ayushrai206?

**Comment by tsukipedia** [comment]
Hello @wetneb, I'm working on this issue, can you assign it to me? I still need to finish testing my changes but this is the PR https://github.com/OpenRefine/OpenRefine/pull/5964

**Comment by tsukipedia** [comment]
I just fixed the cypress issues I was having and ran the tests successfully
