### ISSUE TITLE
Support uploading new version of media files

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5959]
In the Wikibase  extension, the media file upload feature does not make it possible to upload new versions of files.

### Proposed solution

If the user generates edits on matched cells where a file path is also provided, treat those edits as an upload of a new version of the file.
It is likely useful to generate a QA warning about this to make sure this is not done unintentionally.

### Alternatives considered

Decide to forbid this and make it clearer from the UI (via a QA warning for instance) that this cannot be done.

### Additional context

Reported on the forum: https://forum.openrefine.org/t/upload-new-image-version-to-existing-file-on-wikimedia-commons/852

**Comment by trnstlntk** [comment]
Thank you for creating this issue :-)

Here's [a short thread on the Wikimedia Commons Help desk on the topic](https://commons.wikimedia.org/wiki/Commons:Help_desk#Batch_overwriting_a_recent_batch_upload).

* General Wikimedia Commons guidelines about overwriting existing files: [Commons:Overwriting existing files - Wikimedia Commons](https://commons.wikimedia.org/wiki/Commons:Overwriting_existing_files)
* There are unfortunately no user-friendly tools with which you can do this in a more or less 'point and click' way, but it can be done via script or bot.

OpenRefine would certainly fill a certain gap/need when offering this functionality. On the other hand, I have the impression that overwriting files is a rare-ish use case. I'm curious how often folks would want to do this, and whether it is also relevant for Wikibases in general. Comments welcome :-)

**Comment by sebastian-berlin-wmse** [comment]
This is easy enough to do with `ignorewarnings=1` in the request (and changing the issues level).

However, this means that _all_ warnings are ignored. A list of "[s]ome notable warnings" is found on [mw:API:Upload#Upload warnings](https://www.mediawiki.org/wiki/API:Upload#Upload_warnings). `badfilename` should be caught by `FileNameScrutinizer`. I don't know how bad ignoring `was-deleted`/`duplicate`/`duplicate-archive` could be. Is it worth it to allow uploading new file versions?

**Comment by sebastian-berlin-wmse** [comment]
We can get more granularity in what warnings we want to allow by checking which ones we get. If they only are the ones we allow, which I think would be `exists`, `no-change` and `duplicateversions` in this case, we can then resend the request with `ignorewarnings=1`.

**Comment by sebastian-berlin-wmse** [comment]
Uploading new versions works fine locally. It still gives errors, which is odd e.g: 
![image](https://github.com/user-attachments/assets/7ec0791e-f975-44d1-94b0-9e3b10c1a1eb)

This may be due to something strange with my local MW instance. I'm trying to test on Commons, but having some (unrelated) trouble with that at the moment.

**Comment by sebastian-berlin-wmse** [comment]
> I'm trying to test on Commons, but having some (unrelated) trouble with that at the moment.

(Looks like this was #3231)

**Comment by sebastian-berlin-wmse** [comment]
Uploaded a new file version to Commons (see [edit group](https://editgroups-commons.toolforge.org/b/OR/5fe6c009626/)) and got the same result: 
![image](https://github.com/user-attachments/assets/80776a16-8d01-4178-a18e-500e1d1ab617)

**Comment by wetneb** [comment]
I am surprised that "PNG_Test.png" is marked as a new entity and not an existing one in your test. Intuitively, it should already be marked as being matched to an existing entity before you upload the new version. That should be the case if you reconcile the column to Commons normally.

I would even argue that OpenRefine should only accept to upload a new version if the cell is reconciled to a matched item. Otherwise, it could be that the user believes they will upload a brand new file, and they end up overwriting an existing one.

**Comment by sebastian-berlin-wmse** [comment]
> I am surprised that "PNG_Test.png" is marked as a new entity and not an existing one in your test. Intuitively, it should already be marked as being matched to an existing entity before you upload the new version. That should be the case if you reconcile the column to Commons normally.

That's because marked it as new. I do that when testing locally and did it by muscle memory here too🙂

**Comment by sebastian-berlin-wmse** [comment]
> I would even argue that OpenRefine should only accept to upload a new version if the cell is reconciled to a matched item. Otherwise, it could be that the user believes they will upload a brand new file, and they end up overwriting an existing one.

I'm trying to work out how to do this. I figure that you can add uploading to the [existing entity branch in EditBatchProcessor.performEdit()](https://github.com/OpenRefine/OpenRefine/blob/46c29dc5456b35c6ffac556cdc6c8f9d97d62fb3/extensions/wikibase/src/org/openrefine/wikibase/editing/EditBatchProcessor.java#L195), similar to the new entity branch. Is this a reasonable way to do it?

**Comment by wetneb** [comment]
Yes, I would also do that, more specifically in the sub-block that's about MediaInfo updates:
https://github.com/OpenRefine/OpenRefine/blob/46c29dc5456b35c6ffac556cdc6c8f9d97d62fb3/extensions/wikibase/src/org/openrefine/wikibase/editing/EditBatchProcessor.java#L218-L229

I have to say it's not very nice how this method is gathering more and more special cases. It would be nicer to have something a bit more generic which would delegate all the things that are specific to a particular entity type. Maybe it would be worth refactoring it. But unless an approach for that comes to mind, I think it's appropriate to add this special case there indeed.

**Comment by lokal-profil** [comment]
> I am surprised that "PNG_Test.png" is marked as a new entity and not an existing one in your test. Intuitively, it should already be marked as being matched to an existing entity before you upload the new version. That should be the case if you reconcile the column to Commons normally.
> 
> I would even argue that OpenRefine should only accept to upload a new version if the cell is reconciled to a matched item. Otherwise, it could be that the user believes they will upload a brand new file, and they end up overwriting an existing one.

I agree in general but I posted a question on the forum around if having reconciled a row against a matched item should always be interpreted as also agreeing to overwrite it.

On the "issues" side of things that might could also mean that either no warning is raised in this case (where the row is reconciled against an existing file), or that the severity is reduced.

**Comment by magdmartin** [comment]
@tfmorris will it be part of 3.9?
