### ISSUE TITLE
Contains() not working

### ISSUE THREAD

**Issue by VojtechDostal** [OpenRefine/OpenRefine#5965]
This example GREL code: 
"food".contains("oo")

produces the following error for me:
_Error: java.lang.ClassCastException: class java.lang.String cannot be cast to class com.vividsolutions.jts.geom.Geometry (java.lang.String is in module java.base of loader 'bootstrap'; com.vividsolutions.jts.geom.Geometry is in unnamed module of loader edu.mit.simile.butterfly.ButterflyClassLoader @47d277bf)_

Is it just me? Seems like a weird error but I can't get a grip of it. I remember that contains() used to work well before.

I am using openrefine-3.7-beta5 for windows. Thanks.

**Comment by VojtechDostal** [comment]
And I thought I was using almost the latest version! 

Reinstalling helped solve the issue.

I had GeoRefine installed on the previous openrefine, so it might have been due to this as well.

**Comment by tfmorris** [comment]
The extension framework probably shouldn't allow extensions to overload core functions -- at least without a very loud warning.
