### ISSUE TITLE
OpenRefine opens the "Open project" tab by default

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5980]
Until recently, when starting OpenRefine, one would be presented with the first panel ("Create project").
In the current development version (master branch), the "Open project" tab opens instead.

### To Reproduce
1. First, do `./refine`
2. Then, observe the panel that appears in the browser.

### Current Results
The "Open project" panel is shown.

### Expected Behavior
The "Create project" panel is shown.

### Versions
 - Operating System: Debian
 - Browser Version: both firefox and chromium
 - OpenRefine:  3.8-SNAPSHOT [9042ff7]

**Comment by Abbe98** [comment]
Looks like something I caused.
