### ISSUE TITLE
UI improvements for the "Add entity identifiers column" action

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5998]
When using the "Add entity identifiers column action", the UI currently looks like this:
![image](https://github.com/OpenRefine/OpenRefine/assets/309908/a2c6aa9f-2bfa-4342-a30c-e26939fe1283)

### Proposed improvements

* the input field for the column name should be focused when the dialog opens
* the input field could be pre-filled with an automatically generated column name which does not conflict with any existing column name (for instance, if the base column is called "Name", the default column name could be "matched id for Name", perhaps?)
* the "Submit Query" label for the validation button does not make sense, as we are not submitting a query. It should be "OK" or "Create column", I would say. It should be marked as primary (default) button, which generally appears in bold I think
* the title of the dialog does not clearly separate the user-provided data (column name) from the rest. Instead of being `Add column containing entity identifiers on Name`, it could be `Add column of entity identifiers from column "Name"` (note the double quotes)

### Additional context

Discovered while reviewing #5960.
Maybe @OpenRefine/designers have more thoughts about this?

**Comment by wetneb** [comment]
Overall it's worth asking why we are using our own dialog system instead of the built-in `prompt()` javascript function - which would solve a lot of those problems.

If the intention is that it looks cleaner to have prompt with our own UI components rather than the browser's defaults, then we could consider creating our own version of `prompt()` that uses our own dialog system, in a way which would be reusable across the application (so that we don't have to re-implement this logic all the time).

**Comment by Abbe98** [comment]
> the input field for the column name should be focused when the dialog opens

I would prefer if it wouldn't as one can just press tab, I have proposed that such behavior in other places is removed (#5889), this particular modal does not have the same issues as more complex ones but I think the behavior should be consistent.

 > the input field could be pre-filled with an automatically generated column name which does not conflict with any existing column name (for instance, if the base column is called "Name", the default column name could be "matched id for Name", perhaps?)

I imagine most would change this and therefore most would need an extra step to remove the default, assuming everyone is not against my wish to avoid auto-focus.

 > the "Submit Query" label for the validation button does not make sense, as we are not submitting a query. It should be "OK" or "Create column", I would say. It should be marked as primary (default) button, which generally appears in bold I think

Yes this is indeed confusing.

> the title of the dialog does not clearly separate the user-provided data (column name) from the rest. Instead of being Add column containing entity identifiers on Name, it could be Add column of entity identifiers from column "Name" (note the double quotes)

I agree fully.

> Overall it's worth asking why we are using our own dialog system instead of the built-in prompt() javascript function - which would solve a lot of those problems.

We should never use these functions(as in `alert`, `prompt`, `confirm`)  and remove all current usage. They block the main thread and are commonly suppressed by browsers. There is currently a proposal that they should be deprecated from the HTML specification given their problems.

> If the intention is that it looks cleaner to have a prompt with our own UI components rather than the browser's defaults, then we could consider creating our own version of prompt() that uses our own dialog system, in a way which would be reusable across the application (so that we don't have to re-implement this logic all the time).

Yeah, I like this idea. It would be nice to achieve this by turning the current dialog into a class and extend it, although we would need to keep the old JS interface for extensions.

**Comment by thadguidry** [comment]
I think auto-focus is encouraged (a good thing) when further sub-interaction is necessary from a user who initiated a parent action.  I personally like that the flow is maintained for me, instead of me figuring out  where the next flow context is on a page especially when the page might be larger.

Doesn't WCAG agree with that here ? https://www.w3.org/WAI/WCAG21/Understanding/focus-order.html

**Comment by Abbe98** [comment]
> I think auto-focus is encouraged (a good thing) when further sub-interaction is necessary from a user who initiated a parent action. I personally like that the flow is maintained for me, instead of me figuring out where the next flow context is on a page especially when the page might be larger.

The next flow context is the dialog itself and it receives focus by default when opening a dialog, press tab to progress through the flow.

> Doesn't WCAG agree with that here ?

No it's the opposite, if the input is given focus the meaning isn't preserved.

**Comment by tfmorris** [comment]
> > the input field for the column name should be focused when the dialog opens
> 
> I would prefer if it wouldn't as one can just press tab, 

How does the user know that they have to press tab rather than just start typing to fill the only input field in the dialog? I get super annoyed when I have to remove my hands from the keyboard and reach for my mouse just to click on an input field that should have input focus already.

> The next flow context is the dialog itself and it receives focus by default when opening a dialog, press tab to progress through the flow.

I'm not sure users understand what a "flow context" is. If the dialog has focus, where do my characters go when I start typing?

I don't think using `prompt()` is a good idea, but it would be helpful if statements like:

> There is currently a proposal that they should be deprecated from the HTML specification given their problems.

were supported with a reference link.

**Comment by wetneb** [comment]
It's a side comment, but if we are talking about communication norms already, I would find it nice if we could avoid this sort of formulation @tfmorris:

> it would be helpful if statements like:
> 
> > There is currently a proposal that they should be deprecated from the HTML specification given their problems.
> 
> were supported with a reference link.

You could instead write something like "@Abbe98, I didn't know about this deprecation of `prompt()`, do you have a link to share about that?"

The reason why I would prefer that is that the first formulation feels like a reproach, which also introduces a distance with the intended recipient by not mentioning them. It feels needlessly cold and formal to me and could be understood by recipients as a signal that they do not fit in here.

To me it's clear that we don't generally expect people to systematically back up every claim they make with citations - people have limited time and often comment while on the move. It's easy enough to ask for more details when needed.

Happy to discuss this more elsewhere if needed.

**Comment by tfmorris** [comment]
@Abbe98 Please provide a link or other reference to the deprecation proposal for `prompt`, etc, if you have one available.

@wetneb If you already found the link, please provide it. I searched and didn't find anything that looked relevant.

The reason that I would prefer to have this information provided is that it saves multiple people wasting time searching for it.

**Comment by elebitzero** [comment]
Proposed changes:

1. Add quotes (") around column name in title
2. Focus on text input when dialog opens.
3. Change "Submit Query" to "OK"
