### ISSUE TITLE
Change notification to download latest version to official download page

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#6017]
When a user runs a version of OpenRefine that is not the current version, they are notified in the UI that there is a more up to date version an encouraged to download it via a link.

The code that displays this information to the user is at
https://github.com/OpenRefine/OpenRefine/blob/3dabe5130b43d6590faaaf37fae541b655f4e713/main/webapp/modules/core/scripts/index.js#L85

The code retrieves information on the latest version from https://api.github.com/repos/openrefine/openrefine/releases/latest and extracts the `data.html_url` property from the response to get a link to the download. However, this contains the URL of the latest tagged release on Github (e.g. https://github.com/OpenRefine/OpenRefine/releases/tag/3.7.4) rather than linking to the official download page. From the Github tagged release page it isn't immediately obvious how to download the latest version, and those users not familiar with Github are presented with an unfamiliar interface.

Suggest that instead the user notification should provide a link to the official download page https://openrefine.org/download so that the user is directed to the official download page with more obvious options and a more user-friendly interface

**Comment by elebitzero** [comment]
This sounds good, but my only concern is there could be a period where it is out of sync.

Currently, the UI checks https://api.github.com/repos/openrefine/openrefine/releases/latest for a new release, and if there is, the data.html_url e.g.  https://github.com/OpenRefine/OpenRefine/releases/tag/3.7.4 that is shown is guaranteed to be in sync.

However, I believe https://openrefine.org/download is manually updated?  If we direct users to that and the source file releases.js has not been updated, then they may see out-of-sync information (The UI may tell you there is a 3.7.4 but on the download page it still shows 3.7.3).

For example, for this last release 3.7.4, it was released on Jul 16, 2023,  but @wetneb updated the releases.js file on Jul 17, 2023. This means it would have been out-of-sync for some time.  

If someone ran their local OpenRefine 3.7.3 at that moment, it would tell them there is a 3.7.4 version available but the https://openrefine.org/download page might not be updated yet. Is that acceptable ?

**Comment by wetneb** [comment]
That's a great point and I think that could be an opportunity to check how we retrieve the latest release from OpenRefine.
Currently, we call the GitHub API directly, but I think we should rather query `openrefine.org` instead. Relying on GitHub for this causes a couple of issues, such as https://github.com/OpenRefine/OpenRefine/issues/4463, and exposing the IP addresses of all our users to GitHub is not great. Also, if we were to migrate to another forge, the mechanism to check for updates would break.

Instead, we could have a JSON file hosted on our official website, which would contain the necessary information. It could be statically generated just like the rest of the website, directly from the information we have in `releases.js`.
That would have the benefit of also solving this sync problem.

**Comment by wetneb** [comment]
I have made [a PR on the website repo](https://github.com/OpenRefine/openrefine.org/pull/242) to expose version information in `https://openrefine.org/versions.json`, so we could migrate to use that in the same go:

**Comment by tfmorris** [comment]
Another option would be to link directly to the file to be downloaded. I think that's what it used to do and it saves the user an extra page load and click.

Also, as @wetneb points out above, pinging remote sites (whether it be openrefine.org or Github) is a privacy leak, so should be something that we get users opt-in permission for.
