### ISSUE TITLE
Property selection in reconciliation dialog is unreliable

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6031]
In the reconciliation dialog, there is a panel on the right-hand side to configure which columns should be matched with which properties offered by the service:

![image](https://github.com/OpenRefine/OpenRefine/assets/309908/9d3d7521-8e0f-4bdf-9b01-e5211859e2f0)

There are a couple of problems with this UI.

### Redundant checkbox
The checkbox before each column name is redundant with the property field. It only makes sense to check this box if the associated property field is filled, and if the property field is filled then the box should be checked.

In other words, none of the following states are useful to the user:
* ![image](https://github.com/OpenRefine/OpenRefine/assets/309908/93571869-e739-4177-9bd6-1f66440ca36a)
* ![image](https://github.com/OpenRefine/OpenRefine/assets/309908/3dcf03c1-ccb7-4eba-b383-b61b18941b7c)

Therefore, the value of the checkbox could be inferred directly from the state of the associated input field.

### Unclear auto-completion status in property field
The property field does not indicate clearly if the property name typed by the user has been correctly matched to a property offered by the reconciliation service.

When typing a property name in that field, the user is presented with a few options in a drop-down menu (if the service supports it):
![image](https://github.com/OpenRefine/OpenRefine/assets/309908/dbe34e05-5c8d-49de-9d57-bb9c3927d8a3)

If the user picks an option in the list, the property will be correctly used for reconciliation. The state of the input field after doing so looks like this:
![image](https://github.com/OpenRefine/OpenRefine/assets/309908/d89bfce0-5c90-438e-8390-2a04c8138e1b)

If instead the user ignores the suggestions and clicks anywhere else, without picking an option, then the input field will look exactly the same, but the property will not be used for reconciliation because it is not associated with any valid property id:
![image](https://github.com/OpenRefine/OpenRefine/assets/309908/d89bfce0-5c90-438e-8390-2a04c8138e1b)

This can be quite frustrating because once reconciliation has run, it is not necessarily easy to determine if a property was indeed used for reconciliation or not (depending on how the service uses additional properties for scoring). Moreover, one has to wait for the entire reconciliation process to finish before being able to spot this problem (in 3.x).

### Proposed solution

* Remove the checkbox
* Mark the property fields as having an error (similarly to what we do in the Wikibase schema) if they are non-empty but have not been validated with auto-completion. Refuse to start reconciliation as long as any property field is an error state.

### Alternatives considered

Find a new design for this UI, which could potentially also solve #2075 in the same go.

### Additional context

To be considered for NFDI-funded improvements to reconciliation. Cc @lozanaross @ayushrai206 and @OpenRefine/designers

**Comment by elebitzero** [comment]
@wetneb, your proposed solution seems good for incrementally improving the current design. That can be done independently of a complete redesign so  I can work on those changes.  

The auto-completion status is also unclear about the type field if the user doesn't complete the selection. The same fix could be used for both places. 

![image](https://github.com/OpenRefine/OpenRefine/assets/42903164/72bae2e3-c30f-47e9-84c5-332c2ae02094)

**Comment by wetneb** [comment]
I think that makes sense: I am supportive of a redesign but it's true that the work on showing the input field's status better will benefit other places too.

**Comment by wetneb** [comment]
I also proposed a redesign here: #6044 (to solve other problems). Because it's going to take a while to refine the design and agree on it I think it's still meaningful to do some small fixes in the current layout.

**Comment by tfmorris** [comment]
I think just changing the rendering of the labels for selected items would be a significant improvement. I'm not 100% sure, but I think it used to like **director (P57)**, but using the same rendering as reconciled grid cells might be better.
