### ISSUE TITLE
case-sensitive sort does not produce expected result

### ISSUE THREAD

**Issue by HassanRehan** [OpenRefine/OpenRefine#6047]
### To Reproduce

1. Create a project with the supplied "temp.csv"
![image](https://github.com/OpenRefine/OpenRefine/assets/42559726/119803ef-f1a1-4554-b72a-2717e26d84d3)

2. Configure a sort on the single column as follows
![image](https://github.com/OpenRefine/OpenRefine/assets/42559726/9f56aff4-45fa-4af0-a54b-e8178c424c01)

3. Apply the sort by "Reorder rows permanently"
![image](https://github.com/OpenRefine/OpenRefine/assets/42559726/8cee7a26-63e9-4630-aafc-c9cb7f02e4c6)

### Current Results

Sort only moves the character "c"

### Expected Behavior

Here an example within Excel on what the sort should be showing
![image](https://github.com/OpenRefine/OpenRefine/assets/42559726/1182ec7c-0a00-435f-af72-26a0e61032dd)

### Versions
 - Operating System: Windows 10
 - Browser Version:  Chromium 116.0.5845.180
 - JRE or JDK Version: using the "openrefine-win-with-java-3.7.4.zip" release
 - OpenRefine: openrefine-win-with-java-3.7.4

### Datasets
[temp.csv](https://github.com/OpenRefine/OpenRefine/files/12572271/temp.csv)

### Additional context

Looking at the oldest version of JDK that OpenRefine supports: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/text/Collator.html#TERTIARY

https://github.com/OpenRefine/OpenRefine/blob/2b07cfa5ced9bcfdc6d485fe1849af1c79ac320a/main/src/com/google/refine/sorting/StringCriterion.java#L57C50-L57C50

Shouldn't the Collator over here be set to "TERTIARY" or even "IDENTICAL"?
Checking the blame history shows the Collator initially set to the "IDENTICAL" strength.

**Comment by tfmorris** [comment]
Thanks for the bug report. It looks like the case sensitive config handling might have gotten broken when we changed JSON libraries and we didn't have unit test coverage for this particular case.
