### ISSUE TITLE
Inadequate rate-limiting when editing Wikimedia Commons

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6055]
When editing files on Wikimedia Commons, it is possible to encounter rate-limits which imply that edits are not made on the wiki.

### To Reproduce
Steps to reproduce the behavior: see the [forum post](https://forum.openrefine.org/t/openrefine-pause-edit-for-wikidata-edits-but-not-for-wikimedia-edits/972).

### Current Results
Edits are skipped.

### Expected Behavior
The process waits before attempting edits, meaning that edits are successful.

### Versions
 - OpenRefine: 3.8-SNAPSHOT

### Additional context

Edits to Wikimedia Commons involve a bit more operations than on Wikidata, since separate API actions are required to upload the file (if any), edit the structured data and edit or update the wikitext. So it's not so surprising that we are running into a stricter rate-limiting than on Wikidata. The thresholds in use on both wikis might be different too. We need to investigate what those thresholds are and enforce them properly. Also, we should make sure that failed edits are detected properly and re-attempted.

**Comment by sebastian-berlin-wmse** [comment]
@wetneb, do you think this is something that could reasonably be done in OR or would you need to change things in [Wikidata-Toolkit](https://github.com/Wikidata/Wikidata-Toolkit)?

**Comment by wetneb** [comment]
Wikidata-Toolkit already exposes methods to define a particular rate-limiting (in the WikibaseDataEditor class, such as [setAverageTimePerEdit](http://wikidata.github.io/Wikidata-Toolkit/org/wikidata/wdtk/wikibaseapi/WikibaseDataEditor.html#setAverageTimePerEdit(int))). OpenRefine should be able to use those methods to set those parameters to something appropriate for the API actions / Wikibase instance it does.

If that's not sufficient, there could be either
* additional waiting done on the OpenRefine side, without changing Wikidata-Toolkit
* improvements to Wikidata-Toolkit to fit our use cases

**Comment by sunilnatraj** [comment]
@wetneb My finding is by setting the retry limit and exponential backoff settings, it will address this issue. I was able to verify this working. Let me know if this makes sense.

**Comment by wetneb** [comment]
Oh great, if you have some changes which address the issue, that's totally worth submitting!
I had a look at the forum post again, and what I would prioritize doing is making sure the "purge" action and wikitext editing action correctly detect that they are throttled and wait the appropriate amount of time before retrying. I believe this detection is working for Wikibase editing but likely not for the new API actions we have introduced for Commons support.

**Comment by sunilnatraj** [comment]
@wetneb Added support in add / update and purge flows. PR raised.
