### ISSUE TITLE
XML import preview should report errors to the user

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#6058]
When attempting to import the Getty AAT vocabulary [XML file](https://web.archive.org/web/20220418022604/http://aatdownloads.getty.edu/VocabData/aat_xml_1121.zip) the XML parser throws an error about the `xsi` namespace prefix being undefined, but this error is swallowed and never shown to the user (or even logged on the console)

### To Reproduce
1. Create a project using the URL above

### Current Results

Create Project preview page shows an empty display with the message "Click on the first XML element corresponding to the first record to load." (even though there are no XML elements displayed) and the console logs
```
13:49:52.532 [..e.importers.XmlImporter] Error generating parser UI initialization data for XML file (474ms)
```

### Expected Behavior

Console displays the exception which is currently being swallowed
```
ParseError at [row,col]:[1,205]
Message: http://www.w3.org/TR/1999/REC-xml-names-19990114#AttributePrefixUnbound?Vocabulary&xsi:noNamespaceSchemaLocation&xsi
```

User is shown an interpretable (hopefully) error message, along with the line and column where the error occurred, and, ideally, the text of the offending line.

### Versions
 - OpenRefine: 3.7.5

### Datasets
https://web.archive.org/web/20220418022604/http://aatdownloads.getty.edu/VocabData/aat_xml_1121.zip

**Comment by thadguidry** [comment]
Similar? #3638

**Comment by tfmorris** [comment]
It looks like this missed 3.8, so will appear in the next (non-patch) release of OpenRefine.
