### ISSUE TITLE
Missing space when using facets

### ISSUE THREAD

**Issue by frafra** [OpenRefine/OpenRefine#6071]
Missing space between "name" and "count" when using facets:

![image](https://github.com/OpenRefine/OpenRefine/assets/4068/e7b6bbef-60fc-4d59-84de-563c03e4087e)

https://github.com/OpenRefine/OpenRefine/blob/adb0e5f1d2a615e6cb310fc9a84a3c36ce1d03cc/main/webapp/modules/core/scripts/facets/list-facet.js#L181-L182

**Comment by Evangelos-Dimos** [comment]
Can I help with this?

**Comment by wetneb** [comment]
Thanks for the interest! As you can see above, there is already a pull request tackling this issue (#6072), so I would recommend to pick another issue instead :)
