### ISSUE TITLE
Upgrade to Jetty 10 / 11

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#6075]
Community support for Jetty 9 [ended](https://www.eclipse.org/lists/jetty-announce/msg00168.html) June 1, 2022.  I t will continue to receive security updates, but it makes sense to move forward to at least Jetty 10. Jetty 11 has an incompatible API due to package name changes, so it requires a Butterfly update so is blocked by https://github.com/OpenRefine/simile-butterfly/issues/105

I had assumed that we'd eventually have to go to Jetty 11 and did the work to update, but Jetty 12 was just recently released and it provides support for Servlet 4, 5, and 6 in same implementation, potentially minimizing upgrade work, but it is a) brand new and b) requires Java 17 which is much more aggressive than OpenRefine has traditionally been with Java upgrades.

### Proposed solution

Update to Jetty 10 and defer updating to Jetty 11 until other breaking changes are needed in Butterfly.

### Alternatives considered

We could potentially just live with Jetty 9.4 as long as security updates keep coming, hoping to hang on long enough make the transition to Jetty 12 in one jump, but it seems like we could get the rug pulled out on short notice.

**Comment by tfmorris** [comment]
@Abbe98 @wetneb flagging this for a little extra scrutiny in the context of compatibility of 3.8 with earlier releases. It is a major Jetty version update, so it could potentially cause issues.

**Comment by Abbe98** [comment]
@tfmorris I haven't had any issues at all on my end(we are based off master). 

I would actually be in favor of merging your work on bumping Jakarta Servlet and Velocity over at butterfly, from my perspective the benefits would be great and outweigh the potential costs of possibly breaking changes.
