### ISSUE TITLE
NullPointerException in DeleteProject

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#6095]
This NPE was thrown while running Cypress tests. Requires more investigation.

```
java.lang.NullPointerException: Cannot invoke "com.google.refine.ProjectMetadata.getTags()" because "metadata" is null
	at com.google.refine.commands.project.DeleteProjectCommand.doPost(DeleteProjectCommand.java:64)
	at com.google.refine.RefineServlet.service(RefineServlet.java:189)
```

### To Reproduce
1. First, do ...
2. Then, ...
3. Finally, ...

### Versions
 - Operating System: 
 - Browser Version: 
 - JRE or JDK Version: 
 - OpenRefine:

**Comment by elebitzero** [comment]
This looks like a duplicate of https://github.com/OpenRefine/OpenRefine/issues/3479.

**Comment by tfmorris** [comment]
That looks likely. 

(I wonder why it didn't get any template tags assigned when I created it.)
