### ISSUE TITLE
Mangled Unicode characters in reconciliation choices due to OS default character encoding

### ISSUE THREAD

**Issue by elebitzero** [OpenRefine/OpenRefine#6107]
While investigating https://github.com/OpenRefine/OpenRefine/issues/6063, I found a problem more basic than that one.

To reproduce:
 
OS: Windows10
OpenRefine version: development(master)

 1. Create a new project with following CSV:
a,Māori
b,Omaha–Ponca
c,Võro
    (Make sure Character encoding is UTF-8)
![image](https://github.com/OpenRefine/OpenRefine/assets/42903164/5fc8fbee-b10f-421c-95d8-4c6db72ffefb)

2. Select "Start reconciling" from the menu for "Column 1".
3. Select the Wikidata reconciliation service.
4. Unselect "Auto-match candidates with high confidence".
5. Click "Start reconciling".

![image](https://github.com/OpenRefine/OpenRefine/assets/42903164/9e81434a-f82a-41a6-a184-79f215c52e14)

Notice that some of the reconciliation candidates are mangled. For example, Māori shows up as  M?ori and Omaha–Ponca shows up as Omahaâ€“Ponca/

After some investigation, it appears the reconciliation is affected by the default character encoding of the OS.
On Windows10,
```
>chcp
Active code page: 437
```
This is OEM-US. I killed refine.bat, changed the character encoding to UTF-8 (65001) with `chcp 65001`, and re-ran refine.bat and the above tests. After that the text is preserved correctly after the reconciliation.

![image](https://github.com/OpenRefine/OpenRefine/assets/42903164/0e627e23-6756-4a8e-9d5f-a16c79e91360)

Observed Behavior:
OpenRefine behaved differently depending on the the OS/terminal character encoding where 'refine.bat' is run.

Expected Behavior:
OpenRefine should have maintained the UTF-8 character encoding of the project, regardless of what the OS default character encoding is set to.

**Comment by jnross1621** [comment]
Hi there!

I also had a problem--maybe the same problem?-- with mangled characters. I was teaching a tutorial on OpenRefine and one of my students from China brought their laptop up to ask why accents weren't showing up properly, even though she has selected UTF-8

![thumbnail_image](https://github.com/OpenRefine/OpenRefine/assets/118288652/9ca0ffc4-6eb4-4094-b863-08a89372af7a)

This mangling occurs right after the Parse Data fields are selected and before anything else is done. I'm guess this is because her OS is in Chinese by default, but has anyone encountered this before when teaching international students?

**Comment by tfmorris** [comment]
@jnross1621 when you say "right after Parse Data" are you talking about at the time of creating a new project? If so, that sounds like a different problem than this reconciliation issue.

**Comment by tfmorris** [comment]
@elebitzero What browser were you using? I wasn't able to reproduce this using ISO-8859-1 encoding for the server, but apparently Chrome has introduced encoding guessing for content and removed the browser encoding setting, so it could be masking the problem.

**Comment by elebitzero** [comment]
I was using Brave. I cannot reproduce it anymore either so I will close this issue for now. If I see it happen again I can reopen.
