### ISSUE TITLE
Improve error messages in reconciliation operation

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6111]
The errors that are shown to the user when reconciliation fail are wordy and not very helpful to understand the source of the error.
Currently, the error message contains the JSON serialization of the entire batch. This was perhaps helpful when those error messages were written to the server logs, as they were necessary to figure out which part of the dataset was responsible for the error, but now that those errors are displayed in the grid, the context is already clear from the location of the error.

### Proposed solution

Review all the places where `recon.error` is set and make sure a helpful error message is set.

For instance:
* if we cannot connect to the reconciliation service, I would expect a message such as `Connecting to my-recon-service.com failed`
* if the reconciliation service returned an HTTP error, I would expect a messages such as `The reconciliation service returned HTTP error 403`
* if the reconciliation service returns an invalid JSON response, we could have something like `The reconciliation service returned an invalid response: expected ':' after field "queries"`

### Alternatives considered

When it is worth adding more information to the error, but that information can potentially take up a lot of space, then perhaps we could still use the server logs for that.

### Additional context
Follow up to #6006.

**Comment by ayushrai206** [comment]
What do you think should be an apt message to replace the message  "no. of recon objects was less than no. of jobs"?
