### ISSUE TITLE
Make need for Chrome Frame more explicit to user to encourage them to install it

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#614]
_Original author: runuppat...@gmail.com (September 19, 2012 19:09:18)_

<b>What steps will reproduce the problem?</b>
1.Create Project
2.This Computer
3.Browse (chosen a valid xls file)
4.Next

What is the expected output?
Import of chosen file.

What do you see instead?
Nothing happens.

<b>What version of Google Refine are you using?</b>
2.5

<b>What operating system and browser are you using?</b>
W7/64 (VirtualBoxed)
IE 9

---

I tried the same operation on the same VM instance using Firefox and everything went fine.
Then I retried with IE 9 and opened console to see if anything useful would show there.
This is the localized error message:

SCRIPT5007: Impossibile ottenere il valore della proprietà 'length': oggetto nullo o non definito 
index-bundle.js, Riga 57 Carattere 295

translation: can't get value of property 'length', object is null or undefined.
index-bundle.js, Line 57 Character 295

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=615_

**Comment by wetneb** [comment]
Inded.
