### ISSUE TITLE
Option Code in Custom Tabular Exporter misses unchecked columns

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#616]
_Original author: thadguidry (September 20, 2012 23:01:27)_

If you uncheck a column you do not want to export, and then save the Option Code for later applying, that previously unchecked column is rechecked when you later paste and apply the Option Code back in.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=617_

**Comment by jackyq2015** [comment]
in current master code base, it works fine. Should we close it? @thadguidry

**Comment by thadguidry** [comment]
@jackyq2015 In that case, yes, we can close.
