### ISSUE TITLE
Wikibase: Broken styles on 3.7.6

### ISSUE THREAD

**Issue by Abbe98** [OpenRefine/OpenRefine#6163]
Looks like #5953 was backported to 3.7 although it depends on changes made on master. Given it needed to be backported I assume there is another bad backport in there somewhere.

**Comment by wetneb** [comment]
Oops, that's unfortunate! It's definitely worth fixing.
> Given it needed to be backported I assume there is another bad backport in there somewhere.

I don't understand, what do you mean?

**Comment by Abbe98** [comment]
Given that SchemaAlignment.resize() was missing there must be another broken backport as it was only removed recently?

**Comment by wetneb** [comment]
My understanding of the situation is that https://github.com/OpenRefine/OpenRefine/pull/5334 was attempting to fix a bug with resizing the Wikibase schema, and introduced a new one by making reference to the schema alignment UI when it might not be available. The `if (SchemaAlignment) ` block still throws an error if the `SchemaAlignment` global has not been declared yet.

This did not need backporting in 3.7, as this change was already in the `master` branch before we branched off for the 3.7 release series.
Therefore I don't see another bad backport here. But it was worth checking indeed.

**Comment by wetneb** [comment]
Closed by 7abe391
