### ISSUE TITLE
Make reconciliation errors selectable by facets

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6232]
Consider a reconciliation process where some cells could not reconcile properly, resulting in errors stored in cells.
As a user, I want to:
* be notified that those errors happened, without manually scrolling through the dataset to find red text
* be able to easily select all the rows where errors happened, to either fix them manually or re-run reconciliation on this subset only

### Proposed solution

Adapt the reconciliation judgment facet to have a new category, "error", corresponding to the cells with a non-null reconciliation error.

This could be done either by changing the expression that defines the facet (such as `if(isNonBlank(cell.recon.error), "error", forNonBlank(cell.recon.judgment, v, v, if(isNonBlank(value), "(unreconciled)", "(blank)")))`),
or by introducing a new judgment value in the backend. I think the latter would be cleaner.

### Alternatives considered

Introduce another facet for that? It seems a bit overkill to me, and would take up more screen space.

### Current screenshot

Currently, cells with reconciliation errors have status "none":
![image](https://github.com/OpenRefine/OpenRefine/assets/309908/6601f4a7-02f2-4b58-a299-141ea0824fa4)

After this change, it would look like this instead:
![image](https://github.com/OpenRefine/OpenRefine/assets/309908/41e98b1a-d774-4a67-aaf9-b5f778bf4af1)

**Comment by thadguidry** [comment]
@wetneb when you say
> or by introducing a new judgment value in the backend. I think the latter would be cleaner.

do you mean a judgment value of "error" ?  Can you clarify by adding a bit more detail to that part of the proposal comment?

**Comment by wetneb** [comment]
We need to add a new Judgment value here ("error") and update the code so that this state is properly set when creating reconciliation with errors:
https://github.com/OpenRefine/OpenRefine/blob/ec9c7a4fe82aed40841f925f4543cfb1ef6ee108/main/src/com/google/refine/model/Recon.java#L68-L73

**Comment by thadguidry** [comment]
So, we'll be able to facet them directly.  And since we'll have cell.recon.error object, then we can also use that to parse out the error details if we want to?

Also, just wondering if it MIGHT happen that the error object could ever be "empty" and what we will do about that on the backend to avoid giving users on the frontend cluelessness.  Because I don't see that avoidance of "empty" only "null" checking happening here:  https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/model/Cell.java
