### ISSUE TITLE
Unspecified error when trying to add OpenCorporates Reconciliation API as standard service

### ISSUE THREAD

**Issue by KensingtonOscupant** [OpenRefine/OpenRefine#6243]
If I try to add the OpenCorporates Reconciliation API as a standard service via clicking on a column -> Start Reconciling -> Add Standard Service, I get a popup with an error that says "Error contacting recon service: error : error - https://opencorporates.com/reconcile". I am on Ubuntu 22.04.3 LTS. I have tried this with

v3.7.7: "Error contacting recon service: error : error - https://opencorporates.com/reconcile"
v3.6.2: "Error contacting recon service: error : error - https://opencorporates.com/reconcile"
v3.5.2: "Error contacting recon service: timeout : timeout - https://opencorporates.com/reconcile"
v3.4: "Error contacting recon service: timeout : timeout - https://opencorporates.com/reconcile".

OpenCorporates have introduced a whitelist for their reconciliation API this year, but my server is whitelisted with them and accordingly `curl -o /dev/null -s -w "%{http_code}\n" https://opencorporates.com/reconcile` gives `200`. I believe that the same error occurs if you try from non-whitelisted servers.

I used their Reconciliation API with OpenRefine in early March this year and it worked without any problems. Why is this? I have tried tracking down the error in the codebase, but it seems like "error" is not expected behaviour for the error message, so I had a bit of trouble. A starting point could be [here](https://github.com/OpenRefine/OpenRefine/blob/fa8829bdc10e034dcc119d337b573103ee10fd96/main/webapp/modules/core/scripts/reconciliation/recon-manager.js#L65).

### To Reproduce
1. Install OpenRefine as shown [here](https://gist.github.com/felixlohmeier/0ec8b2e8241356ed52af072d9102b391)
2. Try to add OpenCorporates Reconciliation API as standard service

### Current Results
"Error contacting recon service: error : error - https://opencorporates.com/reconcile"

### Expected Behavior
Standard Service gets added

### Versions
 - Operating System: Ubuntu 22.04.3 LTS
 - Browser Version: Don't think it matters but I tried with
        Brave: 1.61.101 Chromium: 120.0.6099.71 (Official Build) (x86_64)
        Safari: Version 15.4 (17613.1.17.1.13)
 - JRE or JDK Version: 
        openjdk version "11.0.21" 2023-10-17
        OpenJDK Runtime Environment (build 11.0.21+9-post-Ubuntu-0ubuntu122.04)
        OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
 - OpenRefine: 3.7.7, 3.6.2 (and timeout for 3.5.2 and 3.4)

**Comment by tfmorris** [comment]
Sorry for the delay in triaging this. As those installation instructions describe, a split client/server installation is an unsupported configuration, but if you want to attempt to pursue this anyway, make sure that both your client machine and server machine (as viewed from OpenCorporates) are whitelisted.

Adding a new reconciliation service is done client side, so the client machine needs to be whitelisted in addition to the server (which will be used for the actual reconciliation operations).

If you confirm that both machines are whitelisted, the next step would be to collect any error messages from a) your browser's developer console and b) the OpenRefine server log.

**Comment by tfmorris** [comment]
@KensingtonOscupant did the suggestion of whitelisting both client & server resolve the problem that you were having?

I'm going to close this as stale, but feel free to reopen it if you are still having issues.

**Comment by thadguidry** [comment]
The endpoint has changed.  And OpenCorporates now requires registering an account to get an API token (key), and using that for requests.  I think it would need to be added with something like this `https://api.opencorporates.com/reconcile?api_token=abc123cd45`

See Comment in our Forums: https://forum.openrefine.org/t/finding-addresses-from-business-names/1546/6?u=thadguidry
