### ISSUE TITLE
Registration to the BarCamp is open

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6245]
**2024-04-18 update:** The BarCamp is taking place on 17-19th June in Berlin and online: https://barcamps.eu/openrefine-2024-barcamp/
Do register and propose sessions! We have funding to support travel costs of multiple attendees.

---

For some time, a few team members have been considering organizing a small in-person meeting around OpenRefine.
The goal of such a meeting would be to have contributors get to know each other better, share their views and coordinate
together on a diverse range of topics, such as roadmap, governance, design, documentation and likely many others.

[Those planning discussions have been held on the forum](https://forum.openrefine.org/t/organizing-an-openrefine-barcamp/179/23), which we acknowledge is only actively visited by parts of the broad OpenRefine community we want to reach out to with such a meeting.

If you are interested in shaping the future of OpenRefine and meet like-minded people, you are invited! Whether you are a translator, a trainer, a developer, a designer, an advocate or if you feel involved in the project in any other capacity, we want to see you at this event.

We are currently evaluating different dates and venue options. We aim to make remote participation possible and anticipate that
we should be able to offer travel support for multiple attendees. Please [select the dates that would work best for you in this poll](https://framadate.org/iHVSSxY9VhtxUhrV) and [let us know on the forum](https://forum.openrefine.org/t/organizing-an-openrefine-barcamp/179/23) (or here) if none of the options work for you.

**Comment by wetneb** [comment]
Unpinning since we are about to make a final decision on the date.

**Comment by tfmorris** [comment]
This is done
