### ISSUE TITLE
Add ANDed behaviour to intra-facet operations

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#625]
_Original author: mihi...@gmail.com (October 03, 2012 13:37:23)_

Note: I was instructed by Tom Morris to create this enhancement request.

When selecting (including) more than one choice inside a facet, the results are filtered using an OR operation. There are cases when an AND operation is needed.

I managed to patch the code so that the behavior is ANDed, please see the attachment for the changes I made (around 20 lines of code). Not sure what the standard procedure is, I just wanted to share the findings with you...

Obviously, they way this enhancement should be implemented, is to have another link, besides change/ invert/ reset, that will allow to switch between OR and AND.

Thank you,
Mihai

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=626_

**Comment by wetneb** [comment]
I would say this should be handled individually by each facet, for those where supporting conjunction and disjunction makes sense.
