### ISSUE TITLE
Import of a non-zip file with a .zip extension fails silently

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#6253]
While working on #6058, I discovered that using the archive.org [URL](https://web.archive.org/web/20220418022604/http://aatdownloads.getty.edu/VocabData/aat_xml_1121.zip) for the XML file results in a blank screen with no error messages. Investigation revealed that the download actually was HTML, but it was being saved with the `.zip` extension. Attempts to load an invalid or corrupted Zip archive should be reported to the user.

### To Reproduce
1. Create Project
2. Get data from URL
3. Use URL https://web.archive.org/web/20220418022604/http://aatdownloads.getty.edu/VocabData/aat_xml_1121.zip
4. Click next to get to preview screen with parsing options

### Current Results
Blank import screen with no error messages

### Expected Behavior
Attempts to load an invalid or corrupted Zip archive should be reported to the user.

### Versions
 - OpenRefine: 3.8-SNAPSHOT

**Comment by thadguidry** [comment]
@tfmorris Could the TextFormatGuesser.isCompressed() be used to catch the magic bytes and thus determine if any `.zip` extension is indeed a valid ZIP file download?
I see your old commit https://github.com/OpenRefine/OpenRefine/commit/a3fab26cca508ea92f013cfba327d82b95de2c5c

**Comment by surajbora59** [comment]
@tfmorris , It appears that there isn't support for importing zip files, even those containing XML, as the imported content shows up as blank. Perhaps we should inform users that importing files from URLs in zip format isn't permitted.
