### ISSUE TITLE
Maven Linux build: please provide jar files instead of single class files

### ISSUE THREAD

**Issue by apoleon** [OpenRefine/OpenRefine#6257]
The Linux binary distribution of OpenRefine distributes hundreds of single class files instead of merging them into a few jar files. This can be observed by downloading the latest tar.gz distribution of OpenRefine from Github. This is only a minor issue but would possibly help to improve some reproducible build problems in Debian. 

### Proposed solution

Modify the maven build to install jar files instead of single class files.

**Comment by wetneb** [comment]
That makes sense: it does make the distribution smaller too (I have noticed that as a side-effect of the more granular Maven modules in the 4.0 branch).
