### ISSUE TITLE
Setting the log level from the command line does not work

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6286]
Setting the log level with the `-v` option in `./refine` and `/v` in `refine.bat` has no effect.

### To Reproduce
1. Run `./refine -v warn`

### Current Results

Observe that info-level logging statements are shown:
```
09:41:22.621 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
09:41:22.624 [            refine_server] refine.memory size: 1400M JVM Max heap: 1468006400 bytes (3ms)
09:41:22.650 [            refine_server] Initializing context: '/' from '/home/user/Programmation/ORmaster/main/webapp' (26ms)
09:41:22.686 [            refine_server] Starting autoreloading scanner...  (36ms)
09:41:23.483 [                   refine] Starting OpenRefine 3.8-SNAPSHOT [94d063c]... (797ms)
```

### Expected Behavior

Only logging statements with logging level `warn` or above should be shown. And similarly for other desired logging levels.

### Versions
 - Operating System: Debian
 - JRE or JDK Version: 17
 - OpenRefine: master branch

### Additional context

This seems to be a problem left over from my migration to Log4j2. In `Refine.java`, we use the Log4j API to set the level, but that has no effect as we are using Log4j2.

**Comment by amparab** [comment]
Hello, I am willing to work on this issue. Can you please assign this to me.

**Comment by amparab** [comment]
Hello @wetneb 
I have created a PR to resolve this issue.
I am new to opensource contribution, hence please let me know if you have any suggestions/feedback. 
Happy to learn!
