### ISSUE TITLE
Support showing in-tool notifications about user surveys or other noteworthy things

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6290]
We currently show a notification on the main page of the tool if a new version is available. It would be useful if we could use a similar mechanism to advertise other things as well, such as when we run a user survey or when we organize an event of some sort.

### Proposed solution

In the JSON file that is queried by OpenRefine to retrieve the latest version, also add another field for an arbitrary notification, like this:
```
{
     "versions": …
     "notification": {
         "text": "Take part in our user survey",
         "link": "https://limesurvey.org…"
     }
}
```
The notification would be displayed in priority over new versions (so that we also reach people who haven't upgraded for a while):

![image](https://github.com/OpenRefine/OpenRefine/assets/309908/1b8222a4-82d4-450d-8a31-85ea0779f3c1)

### Alternatives considered

The notification could also be displayed elsewhere. Maybe @OpenRefine/designers have suggestions?

### Additional context

I would first migrate to stop querying the GitHub API and use a JSON file hosted on openrefine.org, as suggested by https://github.com/OpenRefine/OpenRefine/issues/6017 and #4463.

**Comment by thadguidry** [comment]
I generally agree.  However, push notifications (actually not a push, but a query out, but users will kinda feel its a push), might be frowned upon beyond basic tool updates.

1. Any way to have a checkbox on the notifications that says "never notify in the future about these" and a close X with hovertext labeled as "dismiss for now"?
2. Also, on the home screen of OpenRefine where these notifications would display... I imagine there is no timeout for them to hide, correct?  I think not having a timeout, and just having the checkbox for the user to opt-out of future notifications in that category would take care of any timeout concerns (show the notification until the user opts-out)?
3. What will it look like if there are 3 notifications?  Survey, New Version, Event Soon?  Just stacked up vertically, I assume? Crowded, but that's maybe why the X close on them would be useful, I think.

**Comment by magdmartin** [comment]
We can consider adding a `news` tab on our homepage that will display the RSS feed from our blog. This will provide a non-intrusive way for our users to stay informed about important project updates. However, it may be easier to miss updates with this approach since they won't be accompanied by a yellow notification.
