### ISSUE TITLE
Wiki Commons reconciliation service failing with 400 bad request

### ISSUE THREAD

**Issue by lucyschrader** [OpenRefine/OpenRefine#6298]
When attempting to reconcile filenames of new uploads with Wikimedia Commons, the application returns a 400 error.

The error dialogue reads:
Guess Types query failed error: java.io.IOException: HTTP error 400: BAD REQUEST for URL /en/api

Filename reconciliation was working a few days ago in 3.7.0, then this error started. Upgraded to 3.7.7 but still getting the error. Have tried exporting the project data as csv and using it to start a fresh project but no change.

Sandra F. has mentioned seeing this error before but it appears to have resolved itself in time.

### To Reproduce
1. Create a project with a "filename" column, with values such as "OR030061_Ninox_albifacies_Te_Papa_1509640_375582.jpg"
2. Then, from the Reconcile column menu, click Start reconciling...
3. In the Reconcile column "filename" modal, click Wikimedia Commons (en). The 'Working' modal will show up, and then the browser's error dialogue

### Versions
 - Operating System: Windows 10
 - Browser Version: Chrome 120.0.6099.217 (Official Build) (64-bit)
 - JRE or JDK Version: 1.8.0_391-b13
 - OpenRefine: OpenRefine 3.7.7 [7b36017]

### Datasets

[Laughing-owl-image-upload.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/13908115/Laughing-owl-image-upload.openrefine.tar.gz)

**Comment by wetneb** [comment]
That's a bug from the recon service itself.

**Comment by bjhoareAM** [comment]
As a note, I have experienced issues with this today - so it does not seem to have been resolved
