### ISSUE TITLE
Constraints on nested properties (ie CVTs) don't work when adding from Freebase

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#631]
Attempting to use the constraint from #92 with Population -> Number (ie the number property of the Population CVT) doesn't work.  The problem is that the front end is setting the constraints property on the nested property, but the backend is looking only at the top level.

We need to not only make them agree, but also make the user aware of which context (ie top level or nested), they are writing the constraint for.

This was initially reported on the mailing  list and here: http://stackoverflow.com/questions/12956498/google-refine-add-column-from-freebase-constraint-does-not-seem-to-work
##

**Comment by wetneb** [comment]
This was specific to Freebase's interface. The new data extension dialog for standard services does not support nested properties and does not handle constraints in the same way.
