### ISSUE TITLE
Use SVG logo and icons instead of png

### ISSUE THREAD

**Issue by simonaubertbd** [OpenRefine/OpenRefine#6316]
Hello,
I was very surprised to see OpenRefine still use a png image for its logos displayed in the application
![image](https://github.com/OpenRefine/OpenRefine/assets/46959192/99eb0b0d-0498-4a59-9982-94e38f85d5e2)

![image](https://github.com/OpenRefine/OpenRefine/assets/46959192/45dac724-8323-4c4e-baeb-80097aebf1f3)

SVG (vector image format) are great : fast, light, can resize easily, etc.. and work perfectly in a web browser. Moreover, it's not a lot of work since the logo is already available in svg
https://fr.wikipedia.org/wiki/OpenRefine#/media/Fichier:OpenRefine_favicon_(2018-present).svg

### Proposed solution
To use svg version of these pictures

### Alternatives considered
N/A
### Additional context
N/A

**Comment by wetneb** [comment]
If you check the version from the master branch, I think we have at least changed the top logo to not include the text (@Abbe98 did this, I don't have the PR number at hand).

If the logo is still in PNG and not SVG there, then I'd say it's totally worth migrating indeed. Would you be interested in working on that?

**Comment by simonaubertbd** [comment]
Hello @wetneb  Stupid question but what do you mean by working on that ? I thought the svg logo already exists ?
![OpenRefine logo (2018)](https://github.com/OpenRefine/OpenRefine/assets/46959192/538d7be9-6f75-4c1f-8ae8-19e0a5036380)

Best regards,

Simon

**Comment by simonaubertbd** [comment]
By the way, I had a look at the main branch https://github.com/OpenRefine/OpenRefine/tree/master/main/webapp/modules/core/images

All png. I'm not even sure they're all used

**Comment by simonaubertbd** [comment]
I also found that article about animated svg to replace gig
https://arsiriy.com/2021/02/21/animated-svg-vs-gif/

**Comment by wetneb** [comment]
@simonaubertbd by "working on that", I mean doing the necessary changes in OpenRefine's source code so that the SVG image is used instead of the PNG one. You would then open a pull request for us to review your changes, and after merging the pull request, the next OpenRefine release would not have the problem that you describe: it would use the SVG logos.

Here is an overview of the contribution process (with a lot of steps not being necessary in such a simple case):
https://openrefine.org/docs/technical-reference/code-contributions

**Comment by wetneb** [comment]
I marked this as a good first issue, to replace the OpenRefine logo from a PNG to SVG. There are many other raster images in the UI, which would totally deserve being migrated to SVGs as well, but let's keep this issue focused on the OpenRefine logos mentioned above.

**Comment by vr-varad** [comment]
@wetneb I would like to work on it. Can I?

**Comment by abhishekkujur1307** [comment]
@vr-varad Are you still working on this issue? If not, can I get this assigned ?

**Comment by wetneb** [comment]
I think two weeks is more than enough time to tackle something like this, so go ahead @abhishekkujur1307!

**Comment by abhishekkujur1307** [comment]
@wetneb I am not able to find svg logo for this image.
![image](https://github.com/OpenRefine/OpenRefine/assets/59303347/7d8d0aaf-cd9d-4e0c-bf15-7e137f893856)

If there is, please send me the svg link.

**Comment by wetneb** [comment]
If you try OpenRefine from the master branch (not the latest stable release), you'll see that the image only covers the logo now, as @Abbe98 has already taken care of converting the "OpenRefine" text part to an actual text.
So you should only need to replace the logo itself by the SVG linked above.

**Comment by JasonZelmanovich** [comment]
@abhishekkujur1307 are you still working on this issue? if not I'm looking for a good first issue to tackle and I'd like to give it a try

**Comment by abhishekkujur1307** [comment]
@wetneb Please de-assign me. I am sick and will not be able to contribute.

**Comment by simonaubertbd** [comment]
@wetneb Thanks to the team for that !
