### ISSUE TITLE
Swapped button labels in Wikibase schema editor

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6329]
The labels of the "Save schema changes" and "Save schema" buttons do not correspond to what the buttons actually do.

### Current Results

Clicking on the "Save schema changes…" button brings up a dialog to save the schema in the library (to be used in other projects).
The "Save schema" button at the bottom just saves the changes made to the schema into the project.

### Expected Behavior

The labels of the buttons should be swapped to match their actual behavior.
The button at the bottom saves changes in the project, and is logically located next to the button that discards those changes.

The button at the top is not meant to be used for saving incremental changes but rather saving a schema to be able to reuse it later: as such, it does not make sense to me to have the "changes" word in its label.

### Screenshots

![image](https://github.com/OpenRefine/OpenRefine/assets/309908/fd4f58c7-a567-4a14-9f95-2111dc7733e2)

### Versions
 - master branch

### Additional context
Introduced by #5935.

cc @Abbe98 @lozanaross

**Comment by Redeem-Grimm-Satoshi** [comment]
@wetneb, Swapping the button labels makes sense. Can I hop on this issue?

**Comment by wetneb** [comment]
if you are already assigned to another issue, maybe finish that one first?

**Comment by Redeem-Grimm-Satoshi** [comment]
@wetneb Sure, I thought I could juggle on both

**Comment by Redeem-Grimm-Satoshi** [comment]
@wetneb is still issue still available? can I go ahead with it?
