### ISSUE TITLE
Creating a project from a URL with a trailing space fails

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6330]
### To Reproduce
1. First, launch OpenRefine and go to "Create Project" -> "Web Adresses (URL)"
2. Then, type in a URL with a trailing space at the end, such as "https://datasets.imdbws.com/name.basics.tsv.gz "
3. Finally, press "Next »"

### Current Results

Error: 
```
Error uploading data
Illegal character in path at index 46: https://datasets.imdbws.com/name.basics.tsv.gz "
```

### Expected Behavior

The whitespace is trimmed and the project is successfully created.

### Versions
 - OpenRefine: master branch

**Comment by MHRSRoni** [comment]
can i take this issue ?

**Comment by thalesreisbr** [comment]
Hey @MHRSRoni  did you have any progress on it? Could I take this issue?

**Comment by surajbora59** [comment]
@wetneb , I have opened the PR with the fix for this issue. Please take look #6360 .
