### ISSUE TITLE
Reconciliation against unique identifiers does not work

### ISSUE THREAD

**Issue by matssk** [OpenRefine/OpenRefine#6331]
### To Reproduce
1. First, identify a column in your dataset that contains an identifier.
2. Then, verify that this identifier exists in the same format listed under Identifiers in wikidata
3. Finally, click the column, click start reconciling

### Current Results

It does not correctly match any entities

### Expected Behavior

Match entities, that has the same id, with each other

### Versions
 - OpenRefine:  3.7

### Datasets
As a concrete example I have a column labeled "Steam application ID". In this column you can find the value "https://store.steampowered.com/app/220/", that corresponds to Half-Life 2. On the wikidata page https://www.wikidata.org/wiki/Q193581 under identifiers, you can also find "Steam application ID" with the value "https://store.steampowered.com/app/220/"

**Comment by matssk** [comment]
It wasn't clear from the docs, but I've found a video describing the process and it seems I didn't do it correctly. After correcting the process it works.

**Comment by wetneb** [comment]
Thanks for reporting it regardless! We are aware that this process is far from intuitive and we have plans to improve it.
