### ISSUE TITLE
Use description embeddings for disambiguation

### ISSUE THREAD

**Issue by matssk** [OpenRefine/OpenRefine#6332]
If you reconcile a dataset against Wikidata and have a name column in your dataset with a name like "Michael Jackson" and match this again type human (Q5), there will be many matches. Since there are a number of notable people named Michael Jackson, you may need to go through them manually, typically disambiguating using the Description field from Wikidata. 

### Proposed solution

Creating an embedding vector of the Description from Wikidata is a useful way to automate disambiguation of similarly named entities using the Description field. 

If your dataset has a "Description" or "about" field, that can then be embedded with the same embedding model and they can be compared using cosine similarity or similar.

I have tried this in a custom reconciliation service (not using OpenRefine at all) that I made and found it to work quite well. For the dataset it was tried on it automatically disambiguated correctly in most cases, saving lots of manual work.

I'm not sure if this is the correct place to propose this? It would require Wikidata to implement an LLM model to create embeddings of the Description field too.

**Comment by wetneb** [comment]
That sounds interesting! But as you guessed, this would probably be outside OpenRefine's scope. Any chances your custom reconciliation service could expose the [web API](https://www.w3.org/community/reports/reconciliation/CG-FINAL-specs-0.2-20230410/) that OpenRefine uses to query reconciliation services? This way, one could use your approach via OpenRefine.

**Comment by matssk** [comment]
So it is actually just an alternative way of comparing string properties. Instead of doing Levenshtein distance, compare an embedding for each string and then the cosine distance. The embeddings can be computed on the fly and cached if needed. I might try adding it to the wikibase reconciliation service next time I need it. I'm not entirely sure yet to what extent property comparisons are/should be done in just the reconciliation service, OpenRefine or both.

**Comment by wetneb** [comment]
Closing as it's something that could rather be implemented in reconciliation services.
By the way feel free to join the W3C group, for instance to suggest changes to the protocol that would make your use case easier: https://www.w3.org/community/reconciliation/

**Comment by matssk** [comment]
Where a similar feature could be useful in OpenRefine itself is for clustering. There's now token-based clustering and character-based clustering, so that would add semantic clustering. The actual feature in that case would be clustering of vectors, also useful for finding geographical clusters such as duplicate entities for locations, that have had their entities added by multiple people adding coordinates that are almost, but not entirely identical.

For embedding vectors I think in this case one would either just have them in the dataset already or add by "Add Column By Fetching URLs"

There is already support for k-nearest neighbor clustering, but as I understand it this is only for strings, no vector support at the moment? What would be needed for geo and semantic clustering is just support for vectors in addition to strings. Or is it already somehow possible using arrays?

**Comment by wetneb** [comment]
Sure, those sorts of techniques could also be used for clustering. One would need to figure out a way to make the underlying model configurable: obviously we can't just bundle a big trained model inside OpenRefine directly.

So far our clustering aren't very easy to extend / improve. I have proposed https://github.com/OpenRefine/OpenRefine/issues/4301 which could perhaps help.

**Comment by matssk** [comment]
Yeah, I think having #4301 implemented would be a good start.
