### ISSUE TITLE
CI: application packaged twice in snapshot release pipeline

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6349]
I realized that the CI runs the MacOS packaging twice for each commit! That's a bit much, given that it also involves notarizing the created DMG file, which is therefore also done twice.

This can be seen in the following logs, by looking for the string "Apple notary service" which can be found twice, on `2024-02-05T20:09:06.2471130Z` and `2024-02-05T19:56:54.3974820Z`.

[logs.txt](https://github.com/OpenRefine/OpenRefine/files/14183741/logs.txt)

The antrun plugin seems to be executed twice somehow, when running the following command:
```
mvn package -DskipTests=true -DrepositoryId=ossrh -Dapple.notarization.username=$APPLE_USERNAME -Dapple.notarization.password=$APPLE_PASSWORD -Dapple.notarization.team.id=$APPLE_TEAM_ID
```

This is probably a bug due to the way Maven plugin executions are bound to specific phases/goals.

**Comment by tfmorris** [comment]
Not only is the notarization done twice, but it looks like it fails both times, timing out at 600 seconds. The whole build takes over 45 minutes, which seems pretty heavyweight (although perhaps it's really only half that without the duplication).

**Comment by tfmorris** [comment]
Confirmed that notarization is only happening once and this time it didn't time out, but it just squeaked under the 10 minute timeout at 9m49s, so that timeout might be a candidate to increase (although 10 minutes seems like a *really* long time). Total CI time was 25 min vs 38-40min before the fix.
```
18:23:30 start
18:33:19 end
```

**Comment by thadguidry** [comment]
Just an aside here, but... did we confirm if Maven cache is effectively being reused properly?  Or is it having to download some dependencies all the time again?  That used to be our "original original long build time" problem.

**Comment by wetneb** [comment]
I think it makes sense to bump the timeout indeed.

Maven dependency caching is an independent problem, there is no reason for it to influence notarization time I would say.

I don't think we have much control over notarization time, except perhaps by making our DMG bundle smaller, which is always good to do of course! For instance by cleaning up our dependencies (#6315), but that's of course a big task.
