### ISSUE TITLE
replace menu option with double quote (") doesn't work

### ISSUE THREAD

**Issue by LNBelo** [OpenRefine/OpenRefine#6367]
I have several lines that use “”, but I should replace it with "".
When going to "Edit cells --> Replace" and replacing “ with " the following message appears:
Text transform on 0 cells in column name: value.replace("?",""") Undo

In "Transform", when I use GREL value.replace('“', '"') works normally.

Estação “Tatuca”, Centro de Memória - Unicamp (APS 1.2.046).jpg
Praça “Voluntários de 32”, Centro de Memória - Unicamp (APS 1.1.0297).jpg
Fabrica de Chapéos “Cury”, Centro de Memória - Unicamp (APS 1.1.0364).jpg

### Versions
 - Operating System: Windows 11
 - Browser Version: Chrome 121.0.6167.184
 - JRE or JDK Version: java version "18.0.2"
 - OpenRefine: OpenRefine 3.7.9

**Comment by wetneb** [comment]
That's likely due to a missing escaping in the generation of the GREL expression.

**Comment by ostephens** [comment]
@LNBelo this bug obviously needs fixing, but just to say that there is a special function to replace "smart quotes" with their ascii equivalent - it's under `Edit cells -> Common Transforms -> Replace smart quotes with ascii`

**Comment by tfmorris** [comment]
The message below looks suspicious:
> Text transform on 0 cells in column name: value.replace("?",""") Undo

if the ? represents the encoding error replacement character, there may be two bugs here:
1. missing escape for double quotes when constructing the GREL expression
2. wrong character encoding for feedback message
