### ISSUE TITLE
Incorrect export of escaped quotation marks

### ISSUE THREAD

**Issue by larisa1995** [OpenRefine/OpenRefine#6420]
When changing contents of a cell by "Edit cell" --> "Transform" with a string including quotation mark it needs to be escaped, i.e. "\"". This looks ok inside OpenRefine. But when exporting TSV all the \" are replaced not by " but by "". Expected behavior is \" to be replaced by ".

Operating system is Windows. OpenRefine Version 3.7.4 [05e9de9]

**Comment by wetneb** [comment]
Thanks for reporting! This seems to be a duplicate of https://github.com/OpenRefine/OpenRefine/issues/2071. Have you tried 3.8-beta1? This issue should be fixed in that version.

**Comment by wetneb** [comment]
Closing as duplicate of #2071 per the above, let me know if it actually isn't.
