### ISSUE TITLE
Require Developer Certificate of Origin (DCO) signoff on all commits?

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#6425]
Somewhat related to https://github.com/OpenRefine/OpenRefine/issues/6422#issuecomment-1984389601, I'd like to suggest that we require DCO sign-off on all commits and document what we mean by it in the context of the OpenRefine project.

https://wiki.linuxfoundation.org/dco
https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for

### Proposed solution
- Add DCO info to our developer docs explaining what sign-off implies for us
- Socialize info with developer community
- Enable DCO checking in Github

**Comment by thadguidry** [comment]
I've never liked this extra effort and didn't think in OpenRefine (without any commercial bent connected to it, unlike Linux Foundation or Oracle projects, etc.) that a DCO would even be needed for us?  Maybe I'm not the right one to comment on this.

@wetneb I'd be curious what or how CS&S (essentially, our legal team) thinks about this, if we should have DCO signoffs or not?  Can you email them?

**Comment by tfmorris** [comment]
We require developers to respect licenses and intellectual property rights and only submit code that they own or have the rights to. The DCO is a lightweight mechanism for them to positively affirm that. We've had cases in the past where people have submitted things without sources available or with incompatible licenses. The DCO would prompt them to think first.

I'm a little disappointed that this didn't at least spark a discussion, but I don't feel strongly about it.
