### ISSUE TITLE
Inconsistent location of Extract / Apply button 

### ISSUE THREAD

**Issue by magdmartin** [OpenRefine/OpenRefine#6432]
The button Extract / Apply are not consistently positioned between the project creation and after doing some operations.

After the project creation, the buttons are located under the information module 
![image](https://github.com/OpenRefine/OpenRefine/assets/2589584/562f018c-9ee4-4d2c-98e9-04d0d7f873a7)

After the user performs at least one operation, the button moves up. 

![image](https://github.com/OpenRefine/OpenRefine/assets/2589584/4979a85a-231b-41a3-826f-d2a0f5d13458)

I would expect the button to always be at the top.

**Comment by Redeem-Grimm-Satoshi** [comment]
@magdmartin The button staying at the top is the best solution. It's probably going to avoid future interminglings

Can I work on this?

**Comment by wetneb** [comment]
It also sounds like a sensible solution to me! The floor is yours @Redeem-Grimm-Satoshi
