### ISSUE TITLE
Improve test coverage of our CalendarParser Java class

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6469]
Our [`CalendarParser`](https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/expr/util/CalendarParser.java) class is used as the backbone of [the GREL `toDate()` function](https://openrefine.org/docs/manual/grelfunctions#todateo-b-monthfirst-s-format1-s-format2-) (converting a string to a date object).

This class was imported a decade ago and could perhaps be replaced by an actively maintained library. But doing this would likely change the set of supported formats, which would likely be a disruptive move for many people relying on its current behavior.

This class has [poor coverage statistics](https://coveralls.io/builds/66381548/source?filename=main%2Fsrc%2Fcom%2Fgoogle%2Frefine%2Fexpr%2Futil%2FCalendarParser.java) (only 37.93% of lines covered as of today).

It could be interesting to add more tests to cover many different usage scenarios, reaching a higher test coverage. Writing such tests would likely be helpful to evaluate the potential impact of switching to another library.

Increasing the test coverage of this class would also the overall coverage statistics of our code base to remain more deterministic: see https://github.com/OpenRefine/OpenRefine/issues/5909#issuecomment-2007051238.

**Comment by pkumar2001** [comment]
Can I work on this?

**Comment by pkumar2001** [comment]
what is the target test coverage?

**Comment by wetneb** [comment]
I think going above 80% would be pretty nice already, but I have no idea how much work that involves.
Of course the goal would be to make actual assertions about the parsed values and not just trigger code paths for the sake of coverage. Let us know how it goes :)

**Comment by shivam999876** [comment]
@wetneb Will the code work?
//Code to fix the issue.
import static org.junit.Assert.*;
import org.junit.Test;
import java.util.Calendar;

public class CalendarParserTest {

    @Test
    public void testParseValidDate() {
        CalendarParser parser = new CalendarParser();
        Calendar result = parser.parse("2024-03-20");
        assertNotNull(result);
        assertEquals(2024, result.get(Calendar.YEAR));
        assertEquals(Calendar.MARCH, result.get(Calendar.MONTH));
        assertEquals(20, result.get(Calendar.DAY_OF_MONTH));
    }

    @Test
    public void testParseInvalidDate() {
        CalendarParser parser = new CalendarParser();
        Calendar result = parser.parse("invalid-date");
        assertNull(result);
    }

    @Test
    public void testParseNullInput() {
        CalendarParser parser = new CalendarParser();
        Calendar result = parser.parse(null);
        assertNull(result);
    }
}

**Comment by shivam999876** [comment]
@wetneb Thanks for your response.
