### ISSUE TITLE
Support multiple matches in Match() function

### ISSUE THREAD

**Issue by leonardoparis** [OpenRefine/OpenRefine#647]
Hello everyone,

I´m new to google refine and regex, but I´ve tried them a couple of times and I introduced a question to the open refine group yesterday that seems to have no solution. So, Tom Morris suggested that I could open a new issue here and here we go.

The problem was (as always lol ) simple: I developed a regex to mach proper names in brasil. In a regex tester, it matches almost everything. So, I thought, is just a matter of putting the regex inside a value.match and put it all inside a forEach statement. As the value.match is already a function that generates an array, the forEach is unnecessary (thanks again Tom Morris). So, I ended with this:

value.match(/._(([A-Z][a-z]_\s[A-Z][a-z]_[áãâéêíóôõú][a-z]_)+).*/).join("|")

So, in the phrase: "The ex-president Luiz Inácio is not Marcos Valério friend, senator."

It was expected as a result: Luiz Inácio|Marcos Valério

But it just gives me: Marcos Valério|Marcos Valério

So, I think we have a big issue here.

I don´t know if I can give suggestions here, but here they go (humble):

A button "Extract the matches" inside the Edit Column > Split into several columns... dialog would do the entire magic. Instead of creating columns with the content on left and right my matches, refine would create the columns with the matches. For example:

"The ex-president  Luiz Inácio is not Marcos Valério friend, senator."
Using Split into, with regex ._(([A-Z][a-z]_\s[A-Z][a-z]_[áãâéêíóôõú][a-z]_)+).*
It returns three columns:
1) The ex-president 
2) is not 
3) , senator

With a possible new feature in the future:

1) Luiz Inácio
2) Marcos Valério

I would consider myself as a truly Gandalf with this...lol

So, this is it. Next I explain the motivation for this regex, but maybe not everyone will be interested so, if this is the case, I appreciate your time and willingness to help and improve this wonderful software.

MOTIVATION:

Since I started in a new project to scrape political news from some sites for text analysis purposes, I realized that if I simply split the text on periods (to form phrases) and then split again using the blanks to take only the words and perform a basic count (faceted text), I would end with many words representing first and last names that were supposed to be together.
So, I thought that identifying proper names with a regex would allow me to identify most names automatically. 

With the names of each news in a new column separate by a pipe, it would be possible to split into several columns with the pipe separator. After that, I would transpose from columns to rows and then and then create a text facet to obtain a list of names. Associating a single word code to each name is easy  (Luiz Inácio --> LI0001; Marcos Valério --> MV0001, and so on), and with all names coded, I would mass edit the original column transforming all names into single word codes, split into several columns by the period (".") character, transpose and than split it all again with the "space/blanks". Transpose again and voilá! Text faceting would reveal the most common words in the news and open the way for a more complex text analysis.

Thank you very much for reading the motivation, I think it can be the issue of many people. The link for the original Open Refine list is this:
https://groups.google.com/forum/?fromgroups=&hl=pt-BR#!topic/openrefine/JemOUierAPs

Leonardo Paris.

**Comment by ostephens** [comment]
I think the new `find` function solves this problem. E.g. you can extract the two names using:
```value.find(/[A-Z][a-z]+\s[A-Z][a-z]+[áãâéêíóôõú][a-z]+/)```

@thadguidry @ettorerizza do you agree?

**Comment by thadguidry** [comment]
@ostephens Yeap !  That use case is one of the reasons for us adding the new find() !

I'll add this example to our Recipes.

To find Proper Names using the full Latin Character set would be:

`value.find(/([A-Z]([a-z]|[\u00C0-\u00FF])+)\s([A-Z]([a-z]|[\u00C0-\u00FF])+)/).join(" | ")`

![capture](https://user-images.githubusercontent.com/986438/42653199-5d439e12-85da-11e8-9f37-e17c2217653f.PNG)

**Comment by thadguidry** [comment]
Recipe added:  https://github.com/OpenRefine/OpenRefine/wiki/Recipes#finding-proper-names-or-people-names-in-a-string
