### ISSUE TITLE
Move the "phonetic" extension to a separate repository or merge it with the "main" module

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6488]
I introduced the phonetic extension [in 2018](https://github.com/OpenRefine/OpenRefine/commit/1c9012982929dafe4df072f3d76c89d759913a6f) as a means to:
* add support for clustering methods which had been requested (#926, #927)
* demonstrate how extensions are able to register new clustering methods

I think its value as a sample extension isn't super high, first because it's kept in our repository (so it does not reflect the development practices that third-party extension developers need to adopt), and also because the dependency it uses to implement the clusterers is actually a dependency of the `main` module itself.

I'd be in favor of either:
* migrating it to its own repository (which would mean users would need to install the extension manually if they want to keep using those clusterers)
* merging it with the `main` module, meaning that we'd pull in the two keyers it "implements" in the core tool (which wouldn't make any difference to users as the extension is currently bundled in the official release)

**Comment by thadguidry** [comment]
I'd prefer this move into our core. Thanks!

**Comment by tfmorris** [comment]
I agree with bundling these two keyers with core and removing the extra module.
