### ISSUE TITLE
loosing rows in a project

### ISSUE THREAD

**Issue by mabecabrera** [OpenRefine/OpenRefine#6495]
I have a proyect of 24078 rows i am working with. 
<img width="1676" alt="image" src="https://github.com/OpenRefine/OpenRefine/assets/63611746/d8bd27bb-a380-4d71-98d7-33e3b056dcdf">

But somehow, after moving backwards unintentionally with the touch pad of my mac, I went back to the OpenRefine hub and when I enter again into the project it has less rows. 
<img width="1007" alt="image" src="https://github.com/OpenRefine/OpenRefine/assets/63611746/ff0fa669-dd39-4de8-8193-58dd0345a027">

And it continues to be like that. There is no sing in the history of such a delete of rows...
<img width="313" alt="image" src="https://github.com/OpenRefine/OpenRefine/assets/63611746/8209aaf5-8ea4-4d36-8ba8-9f44066bed9b">

Do not undestand what happened. I am loosing hours of work here.

**Comment by mabecabrera** [comment]
It is also messing up with the facets...
<img width="972" alt="image" src="https://github.com/OpenRefine/OpenRefine/assets/63611746/ddcb1cc3-e22a-4cbe-9980-85b642075a64">

I select on evalue for this column and the results are many columns that do not have that value.

**Comment by tfmorris** [comment]
I'm guessing that "filas" means rows, in which case, it looks like you are
in "record mode" where multiple rows are combined into a record. One clue
is that the second row has no number next to it. It is, instead, part of
record 1. If you click on "filas" to go into "row mode", it should display
things as you wish.

Best,
Tom

**Comment by wetneb** [comment]
This was closed by mistake because I made a typo in the issue number in 83ee35c

**Comment by mabecabrera** [comment]
Ohhhh thank you so much! I had never seen that "Show as" thing! That is what i may have been clicking on wothout noticing and confusing me a lot.
THANK YOU!!!

**Comment by tfmorris** [comment]
Glad we were able to help! I'm going to close this as resolved, but feel free to create a new issue if you run into any other problems.
