### ISSUE TITLE
Heatmaps - Determining correlations between values (aka pivot, aka scatterfacet for non-numeric values)

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#65]
_Original author: iainsproat (May 28, 2010 11:46:43)_

I'd like to be able to get a x&#37; of records which contain valueA in columnX 
also contain valueB in columnY.
This would then allow me to spot high correlations between non-numeric 
data, and narrow down on outliers for any necessary data cleaning.

This can be done manually be faceting on columnX and making a note of the 
count of valueA.
Then filter by valueA and add an additional facet on columnY, making a note 
of the count of valueB.  Unfortunately, this only allows me to look at one 
value combination at a time.

I'd like a representation, similar to the scatterfacet, to display this for 
all combinations of values in columnX and columnY (plus 'empty').  Along 
the x-axis are the values of columnX and along the y-axis the values of 
columnY.  As the data is non-numeric, the graph is split into cells.  The 
value of the cell is the percentage of records with count(recordA + 
recordB)/ count(recordA).  This could be done as a heatmap varying the cell 
brightness between 0 and 255 in scale with the percentage value.  Clicking 
a cell would get me the corresponding rows.  (bonus points for also being 
able to click through to get the inverse - records of valueA which don't 
contain valueB)

An overview of all possible heatmaps could also be generated, similar to 
the overview of all possible scatterfacets.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=65_

**Comment by thadguidry** [comment]
This should be handled by an extension.

**Comment by wetneb** [comment]
I sympathize with the need but it does feel like a fairly advanced faceting need. Given that facets are extensible I'd be tempted to close this per Thad's comment above. Feel free to reopen if you disagree!

**Comment by wetneb** [comment]
Ah thanks @tfmorris, I still haven't got used to this distinction.

**Comment by tfmorris** [comment]
Not a big deal, but will allow one to find declined enhancement requests using a filter like:
[is:issue is:closed  reason:"not planned" label:enhancement ](https://github.com/OpenRefine/OpenRefine/issues?q=is%3Aissue+is%3Aclosed++reason%3A%22not+planned%22+label%3Aenhancement)
