### ISSUE TITLE
Using Cell Edit button to change String to Date data type gives Uncaught RangeError

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#6534]
Console error when changing a cells data type from Text to Date via Cell Edit button.

### To Reproduce
1. First, click Edit Cell and type in a String such "2023-12-01" and click Apply button
2. Then, .click on Edit Cell and choose from it's dropdown to change to `Data type: date`
3. Finally, click Apply button

### Current Results

1. The console immediately shows the following error (No Java stacktrace shows in Terminal log however):

```
project-bundle.js:46913  Uncaught RangeError: toString() radix argument must be between 2 and 36
    at Number.toString (<anonymous>)
    at HTMLButtonElement.commit (project-bundle.js:46913:21)
    at HTMLButtonElement.dispatch (project-bundle.js:5147:27)
    at elemData.handle (project-bundle.js:4951:28)
```
as shown:
![image](https://github.com/OpenRefine/OpenRefine/assets/986438/bed9632e-4626-49a1-94fc-f3e20b06450b)    

2. If I try to use a partial format in the cell value, then I get a popup alert for "not a valid date." as shown:

![image](https://github.com/OpenRefine/OpenRefine/assets/986438/871c9c26-c3a4-4745-96e7-2bf8b7ded6d6)

3. If I try to use the full format as is recommended above the Cell Edit dialog, then I get the previous Console error as shown:

![image](https://github.com/OpenRefine/OpenRefine/assets/986438/0c5d8a81-022e-445d-9124-e47c3a96036d)

### Expected Behavior
The cells' String value is converted to Date data type when the correct format is used.
I assume that when following the Steps to Reproduce, that a cell text value of "2023-12-01" would be good enough to convert to the Date data type?
But no format seems to be working.

If I use Edit Cell -> Common Transform -> to Date , then that method does seem to be working however.
So the issue is just likely somewhere in the Edit button on a Cell and perhaps the Javascript function or callbacks? 

### Versions
 - Operating System: Windows 11
 - Browser Version: Edge Latest
 - JRE or JDK Version: JDK 21
 - OpenRefine: 4.0 Snapshot

**Comment by tfmorris** [comment]
This occurs on the master branch too, so removing the 4.0 label. I suspect that perhaps the Javascript Date.toString() method has changed over time since I can't imagine this not working originally when David coded it, but who knows...
