### ISSUE TITLE
Tag management of the Wikibase editing operation

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6551]
The Wikibase editing operation currently adds a tag `openrefine-3.9` (in the master branch) to the edits it makes on Wikidata.
Because this tag does not exist on Wikidata yet, editing fails.

In the past, I have taken care of requesting the creation of the tag from Wikidata administrators every time we published a new minor release and I could do it again this time. But it does not feel great, because:
* it's one more manual step that needs to be done after releases, so I'd be keen to eliminate it to keep the release process as simple as possible
* this tag creation is one of the hurdles people encounter when setting up a Wikibase instance to work with OpenRefine, or when we publish a new release and the users of this Wikibase instance upgrade to it.
* The versioning of the Wikibase tags was originally introduced to make it easier to spot problematic edits which would have been introduced by a faulty OpenRefine version, so that they could be fixed. I am not aware of any such instance happening for the past few years, so I don't think this is worth the overhead.

So I would be keen to remove this versioning. One problem is that the tag that is applied on edits is stored in the Wikibase manifests that users have stored in their workspace preferences, in the form of `openrefine-${version}` by default for Wikidata. So it's difficult to change those. I can think of the following approaches:
* Drop support for tagging our edits completely. Editing just works out of the box on any Wikibase instance. Arguably the "(details)" link with the EditGroups batch id is more useful and already identifies the edit as being made via OpenRefine. But if people rely on those tags, they will be annoyed (I remember @lydiapintscher saying that it was important on Wikidata)
* Go for a slightly more careful approach: try adding the tag, but if the tag isn't present on the Wikibase instance, edit without adding the tag. This would make Wikibase upload work out of the box, but will silently create untagged batches, which could be annoying if people do rely on OpenRefine edits being tagged. When they discover that, it's very hard or impossible to add back the tags to the edits.
* Or a slightly more elaborate version: if the tag template contains a version number, try using the version-specific tag. If that fails, try using a version agnostic tag (such as `openrefine`). If that fails, edit without tag. If we request the creation of the `openrefine` tag on Wikidata it would ensure edits remain tagged while still providing out-of-the-box editing support for other Wikibase instances (who might or might not care about tags)

Maybe the last version is good enough?

**Comment by lydiapintscher** [comment]
Thanks for thinking about this!
I think keeping a tag for Wikidata is useful as it helps add more context for the people doing patrolling and other edit reviews. I think it is however not necessary to have the version number in the tag. Just `openrefine` is probably enough. So maybe this is a viable approach: add the `openrefine` tag if it is available on the Wikibase installation, otherwise leave the edit untagged.
