### ISSUE TITLE
Reusable java test utilities for extensions

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6556]
As an extension developer, I want to be able to easily write unit tests for the java classes I write.
The `RefineTest` and `TestUtils` classes that we use in the `main` module are test classes that are not designed for public consumption.

We could have a separate Maven module which would offer basic utilities (covering things such as workspace initialization, teardown and project creation) so that extensions can easily depend on such utilities for their tests.

We could also investigate how to do the same for Cypress tests, but I would keep that for a separate issue.

I intend to tackle this as part of the Maven modularization effort.

**Comment by steve-kasica** [comment]
Such a module would be really useful for extension developer. About a month ago I was actually looking around MVN Repository for such a module.

**Comment by wetneb** [comment]
We actually publish our tests on Maven Central, so it's currently possible to add this to an extension's `pom.xml` file:
```
    <dependency>
      <groupId>org.openrefine</groupId>
      <artifactId>main</artifactId>
      <version>${openrefine.version}</version>
      <type>test-jar</type>
      <scope>test</scope>
    </dependency>
```

And then one can use `RefineTest` and `TestUtils` directly.

It's not ideal because the artifact actually contains all of our tests as well, so it's rather big and stability is even less guaranteed than code in the main code base. So I'm hopeful that the Maven modularization will help trim that down to only contain stuff that we can reasonably keep quite stable.
