### ISSUE TITLE
Uncaught TypeError causing dozens of e2e test failures

### ISSUE THREAD

**Issue by steve-kasica** [OpenRefine/OpenRefine#6568]
When I open OpenRefine in the browser, there's an uncaught TypeError getting logged to the console. While it may seem innocuous, it's causing lots of e2e test to fail. 

### To Reproduce
1. Open OpenRefine, navigate to http://127.0.0.1:3333
2. Open Console in Developer Tools

or run `refine e2e_tests` in the terminal

### Current Results
<img width="1427" alt="image" src="https://github.com/OpenRefine/OpenRefine/assets/2933702/d77a33c4-3b51-4407-852f-c8b5fa66ccf6">

I just finished running the suite of e2e tests and found this issue causing more than 40 tests to fail. Some are triggered by `cy.VisitOpenRefine()`. 

<img width="1375" alt="image" src="https://github.com/OpenRefine/OpenRefine/assets/2933702/7010fe1e-d940-4292-a545-e3e63c48ed21">

### Expected Behavior
I'd expect these tests to pass and for this error not to be logged to the concole.

### Versions
 - Operating System: macOS 114.2.1 (23C71)
 - Browser Version: Chrome Version 124.0.6367.62 (Official Build) (arm64)
 - JRE or JDK Version: OpenJDK 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
 - OpenRefine: Version 3.9-SNAPSHOT [a6eef0c]

### Additional context

Seems like this issue stems from `OpenRefineVersion.module_names` being undefined at this line:

https://github.com/OpenRefine/OpenRefine/blob/c6f1b07b8bd7cbfbe923acfc962ae34196c2ade9/main/webapp/modules/core/scripts/index.js#L93

**Comment by wetneb** [comment]
This is likely caused by switching between different branches which did or did not include the change to package classes as `.jar` files instead of bare `.class` files. Sadly running `./refine clean` does not clean up any `.class` files left over (because the new configuration does not produce them there, so mvn doesn't see it as needing cleaning up).
Assuming you don't have any important untracked files in your clone, you could run `git clean -fdx` to remove them all, and run OpenRefine again, which should hopefully solve the problem.

**Comment by tfmorris** [comment]
You also may just need to refresh your server build. The errors are coming from something added relatively recently which requires support on the backend.

The end to end tests are run on every PR, so they are unlikely to be broken without anyone noticing.

**Comment by steve-kasica** [comment]
Thanks @wetneb and @tfmorris. Running `git clean -fdx` fixed it. I thought I was going crazy. I kept pulling from the upstream master branch and running `./refine clean`.

**Comment by thadguidry** [comment]
Another neat git command that I particularly use and can help (depending on if you are OK to delete untracked files) is `git reset @{u} --hard` which helps HEAD get back to a previous state quickly.  Besides `--hard` there's other modes, like default `--mixed`, depending on what you need.  But if you want to blow away changes and reset the branch to match upstream `@{u}` then it's a great way.
> --hard
> Resets the index and working tree. Any changes to tracked files in the working tree since <commit> are discarded. Any untracked files or directories in the way of writing any tracked files are simply deleted.
https://git-scm.com/docs/git-reset#Documentation/git-reset.txt---hard
