### ISSUE TITLE
Enhancement request: 'Open Project' list

### ISSUE THREAD

**Issue by hvmarck** [OpenRefine/OpenRefine#657]
The 'Open Project' list could do with more metadata (e.g. 'Date Created', number of lines/records, number of columns, ...), and if possible sortable.

As a workaround I created a 'Google Refine Projects' that pieces this together from /command/core/get-all-project-metadata, /command/core/get-models and /command/core/get-columns-info.
##

**Comment by tfmorris** [comment]
This should potentially include any additional metadata from #1045 as well, especially *description*

**Comment by wetneb** [comment]
Closing as a duplicate of #1221.

**Comment by tfmorris** [comment]
Usually we try to keep the oldest of a pair of duplicates, so we probably should have closed #1221 instead of this, but for the record, this was included with OpenRefine 2.8 in November 2017.
