### ISSUE TITLE
Complete list of Major Past Event

### ISSUE THREAD

**Issue by magdmartin** [OpenRefine/OpenRefine#661]
Add video presentation and main resources to the [Event wiki page](https://github.com/OpenRefine/OpenRefine/wiki/Events).

Most the resources are listed on the [External Resources page](https://github.com/OpenRefine/OpenRefine/wiki/External-Resources)

**Comment by tfmorris** [comment]
I'm closing this as stale. It hasn't been worked on in over 7 years.
