### ISSUE TITLE
Improve hover submenu navigation/selection

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6672]
Citing Hao Ye from the carpentries:

> 2. Navigating the submenus can require moving horizontally to the submenu, and then vertically to the option (blue path). Instinctively, I might want to move from where my cursor is to the selection directly (pink path), but this exits out of the selection for the submenu and doesn't work. Not sure of an obvious fix, but this is an area of improvement for the UX.
> ![image](https://github.com/OpenRefine/OpenRefine/assets/309908/e8859881-310e-4635-a1f3-b9c8c48c62e2)

### Proposed solution

* I checked what other tools do (for instance Google Docs, LibreOffice Calc…) and they all seem to have a little delay between hovering a menu entry and opening the corresponding submenu (maybe 0.5 s?). This is sufficient to ensure that when moving the mouse diagonally, any submenus met in passing are not opened.
* Alternatively we could require users to click on menu entries to open the corresponding submenus (that's what my Firefox does, for instance)

### Alternatives considered

We are aware that those submenus are cluttered and inconvenient and there is interest in moving to something else. But that is a more involved change and I think it shouldn't block a small tweak like this one.

### Additional context

Forwarded via Jennifer Stubbs of the Carpentries.

**Comment by tfmorris** [comment]
The current implementation is definitely waayy too twitchy. There are a number of alternative implementation techniques discussed here: https://css-tricks.com/dropdown-menus-with-more-forgiving-mouse-movement-paths/

**Comment by adisin17** [comment]
Hi, I would like to contribute. Where do I begin?

**Comment by wetneb** [comment]
You can begin here: https://openrefine.org/docs/technical-reference/contributing

**Comment by adisin17** [comment]
Thanks, will check this out.

**Comment by HrithikPadavala** [comment]
Hi @adisin17 , are you still working otherwise I want to grab this issue

**Comment by HrithikPadavala** [comment]
![image](https://github.com/user-attachments/assets/8d4dcaa6-85ca-41a3-9cdb-75cd8d6b19f6)

Am I missing something? I am running the project for the first time, I can only see an empty screen with logo. Please let me know if I am missing anything

**Comment by magdmartin** [comment]
@HrithikPadavala Welcome and thank you for your interest. For support questions regarding how to run OpenRefine, it is best to reach out on our [support forum](https://forum.openrefine.org/c/support/12). You can familiarize yourself with the OpenRefine [contribution process in our documentation.](https://openrefine.org/docs/technical-reference/code-contributions)

**Comment by XiaohanMu** [comment]
I am really interested in solving the issue using the method of adding pseudo-elements as hover buffers. I located relative code in path OpenRefine\extensions\database\module\styles\jquery.contextMenu.css. I am not sure whether it is the right place to do the change, and if there is any other file I should focus on to solve this issue.

**Comment by wetneb** [comment]
I would rather expect changes to files in the `main/webapp` folder, since `extensions/database` is about the database extension. If styles of the main app are actually controlled by files in this extension, that's something we should fix (independently of this issue).

**Comment by Shubham-M-Rathod** [comment]
Hey I am new to Open Source and would like to contribute to this repo. I think that I might be able to take on this issue and can improve ux by making changes in main/webapp/modules/core/scripts/util/menu.js.
