### ISSUE TITLE
Introduce new top level GREL variable `record`

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#6681]
From https://github.com/OpenRefine/OpenRefine/issues/3577#issuecomment-785094102

There's really no reason that you should have to qualify `record` as `row.record`. `record` should be a top level variable.

### Proposed solution

Introduce `record` as a top level variable in the global context.

### Alternatives considered
Status quo

**Comment by antoine2711** [comment]
@tfmorris : is this issue the same as #2523? I think this is what I asked for…
If so, than we should close my early request.

Regards, Antoine

**Comment by tfmorris** [comment]
Oops! Yes, this is a duplicate.
