### ISSUE TITLE
Fix OSSRH upload in release pipeline

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6682]
Maven Central has introduced some changes in the authentication required to upload artifacts, which causes a failing build for snapshot releases. We should update our workflow to adapt to the new authentication method (which uses a token instead of username/password if I understood correctly).

**Comment by wetneb** [comment]
No code changes are required, just swapping the username/password for tokens:
https://central.sonatype.org/publish/generate-token/

**Comment by thadguidry** [comment]
Is gpg still needed?

**Comment by wetneb** [comment]
yes

**Comment by thadguidry** [comment]
why?  because of Apple signing or something?

**Comment by thadguidry** [comment]
maybe we could add a comment into the workflow yaml file so I don't have to ask these questions. :-)

**Comment by wetneb** [comment]
gpg is used for jar files.
Apple notarization is used for DMG files.
Why did you ask?
