### ISSUE TITLE
Filter() control returns text string not error object when first argument is not an array

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#6694]
Compare the code for Filter
https://github.com/OpenRefine/OpenRefine/blob/05978a07fa8cdca0dc356233b178ef85d76c1676/main/src/com/google/refine/grel/controls/Filter.java#L70

to equivalent code in ForEach
https://github.com/OpenRefine/OpenRefine/blob/05978a07fa8cdca0dc356233b178ef85d76c1676/main/src/com/google/refine/grel/controls/ForEach.java#L74

Filter should return an eval error not a string at this point so it can be caught appropriately in GREL / UI

**Comment by P-yiush07** [comment]
` return new ControlEvalError(ControlEvalError.ERROR, "First argument must be an array or collection");`

instead of  `return ControlEvalError.filter();`

**Comment by P-yiush07** [comment]
`return new EvalError(ControlEvalError.filter());`

try this also

**Comment by wetneb** [comment]
@P-yiush07 would you like to submit this as a pull request?

**Comment by P-yiush07** [comment]
@wetneb I am cloning the repo currently, till then if you can tell me exactly how can i produce this error then it would be really helpful for me. Otherwise I'll debug it anyhow

**Comment by sunil-atheer** [comment]
@wetneb I raised a PR for this issue - https://github.com/OpenRefine/OpenRefine/pull/6701

**Comment by ostephens** [comment]
@P-yiush07 @sunil-atheer generally it's good if only one person works on an issue at a time. I think if you ask, issues can be assigned to you so people know you are actively working on them (@wetneb may have more guidance on this)
