### ISSUE TITLE
Regression: matching a single cell to a reconciliation candidate resets the grid to the first page

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6695]
In 3.8.1 (and the current master branch), matching a single cell to a reconciliation candidate resets the grid to the first page.
Before, matching a single cell to a candidate (with the button with a single check-mark) did not do that - only matching a cell to multiple candidates (with the double check-mark) did.

### To Reproduce
1. First, reconcile a column
2. Then, move to a different page in the grid
3. Finally, match a single cell to a reconciliation candidate

### Current Results

The cell is matched and the grid view is reset to the first page.

### Expected Behavior

The position in the grid should be preserved.

### Versions
 - OpenRefine: 3.8.1, master

### Additional context

Reported by @arthurpsmith on Mastodon: https://fediscience.org/@apsmith/112672042744786060.

This will be fixed by #6546, but because this is a pretty bad bug, it might be worth investigating if we can include a smaller fix to restore the 3.7 behaviour in 3.8. Given the scale of the changes in #6546 I'd be reluctant to port it as such to 3.8.

**Comment by arthurpsmith** [comment]
Thanks for reporting this!

**Comment by wetneb** [comment]
This seems to be caused by https://github.com/OpenRefine/OpenRefine/pull/6239, which was introduced to fix https://github.com/OpenRefine/OpenRefine/issues/6236. Adding the `cellsChanged` flag to the update options forces re-fetching the grid with a reset to the first page, hence the problem.

I think the spirit behind the previous system was to avoid that by re-rendering only the affected cell. It's a subtle thing to get right of course, but it's probably worth it. There would be value in having that even with #6546 merged, because it avoids re-rendering cells which have not changed (which is good for performance) and preserves the exact scrolling position (not just the pagination settings).
