### ISSUE TITLE
batchReconTestConnectionError stalls tests for 60 seconds

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#6733]
This recently added test: https://github.com/OpenRefine/OpenRefine/blob/d29a6e125d4b938766f2de9e1ca83d0e66fcc888/main/tests/server/src/com/google/refine/model/recon/StandardReconConfigTests.java#L393
adds 60 seconds of dead time to the unit tests.

### To Reproduce
1. Run the unit tests

### Current Results
That one test takes 60 of the 85 seconds for the main unit tests, dwarfing the time used by the other 936 tests.

### Expected Behavior
The test should complete within a few seconds, at the very most, ideally less than a second or two.

**Comment by wetneb** [comment]
I suspect this could depend on the specifics of how domain names are resolved on the system, so likely platform-dependent.

**Comment by tfmorris** [comment]
It's hanging on a socket read for the response to a POST, so not anything obviously related to domain name resolution. It's certainly possible that either the timeout or the POST implementation itself is platform dependent.

**Comment by tfmorris** [comment]
I've confirmed that patching the socket timeout to 5 seconds (from 60 seconds) knocks 55 seconds off the test execution time. I would be surprised if this is platform dependent. The test probably needs to stub the reconciliation and/or http client and use a reduced timeout for tests.
