### ISSUE TITLE
Incorrect placement of drag-and-drop placeholder on start screen

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6735]
The placeholder of the drag-and-drop area ("Drag files here") in the start screen is incorrectly placed outside of the area that accepts drops:

### To Reproduce
Steps to reproduce the behavior: just start OpenRefine

### Current Results

![image](https://github.com/user-attachments/assets/9f1a37ac-6616-4bbd-a217-d3aefec931a4)

### Expected Behavior

The text should be centered in the area that accepts drops.

### Versions
 - Operating System: Debian
 - Browser Version:  Firefox 115.12.0esr
 - OpenRefine: master branch

**Comment by Shrishail19** [comment]
Can I do it!?

**Comment by mtafadar** [comment]
I notice this as well

**Comment by shubham-bhk** [comment]
Can I try to solve this ?

**Comment by tfmorris** [comment]
Recent versions of Chrome, Safari, and Firefox (128.0.3) all render correctly on macOS, so I suspect this is a platform specific problem (or perhaps a Firefox bug which was fixed recently).

**Comment by wetneb** [comment]
I can observe this with Chromium 125.0.6422.60 as well
