### ISSUE TITLE
Transformations are silently ignored if Undo is pending

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#6746]
### To Reproduce
1. Open a project with an operation history
2. Undo the last operation by clicking on the 2nd to last operation in the history
3. Use the Edit Cells -> Transform operation to make any change to the grid

### Current Results
Nothing happens.

### Expected Behavior
Confirmation dialog asking if you really want to discard the undone operation

### Versions
 - Operating System: macOS Sonoma 14.5 (23F79)
 - Browser Version: Chrome  Version 126.0.6478.127 (Official Build) (arm64)
 - OpenRefine: 3.9 SNAPSHOT

**Comment by tfmorris** [comment]
@wetneb Do you have a handle on why this is happening? Do you think we can get it fixed for 3.9?

**Comment by wetneb** [comment]
Thanks for the reminder, happy to tackle this for 3.9
