### ISSUE TITLE
ui-tabs-active appears as a text input area rather than a pointer or default

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#6764]
There are places throughout the UI where the ui-tabs apply `cursor: text` rather than `cursor: default` or `cursor: pointer`.  The `cursor: text` allows highlighting the ui-tab text (not beneficial I think) and confusingly changes the cursor shape when hovered over ui-tabs to that of a text input bar making the `ui-tab-active` look like input text areas rather than clickable elements like buttons and tabs typically are.

### To Reproduce
1. First, click on Undo/Redo to make it an active tab, then move mouse over Facet/Filter and Undo/Redo.
2. Notice that the cursor shape changes to a text input bar over Undo/Redo.

### Current Results
ui-tabs in many places of OpenRefine such as Undo/Redo tab and some of the Export dialogs are confusingly showing the `cursor: text` and producing a text input bar upon hovering over any tabs that are in the state of `ui-tabs-active` it seems.

### Expected Behavior
We have various dialogs throughout OpenRefine that use Jquery-ui and it's handling of `ui-tabs` and it's other subclasses such as `ui-tabs-anchor` and `ui-tabs-nav`.  It would be optimal that users see the same cursor shape for ui-tabs since throughout they are indeed clickable elements and not for text input or even beneficial to users to capture the ui-tab text phrase for copy/paste operations.  So I would expect the ui-tabs throughout OpenRefine to show with `cursor: pointer` to bring a consistent UI Tab experience and make it more clear that they are clickable elements.  For `ui-tabs-active` which are not considered clickable since the user is on that active tab, then I would expect we just make those `cursor: default` for the regular arrow cursor rather than `cursor: pointer` for the hand pointer?  Whichever one feels right I think.

### Screenshots

![UndoRedoInput](https://github.com/user-attachments/assets/6a47958e-8c1e-42ec-87a7-b6ebdd62801a)

### Versions
 - Operating System: Windows 11 Pro
 - Browser Version: Edge latest
 - JRE or JDK Version: embedded
 - OpenRefine: 3.8.2

### Additional context
The current default jquery-ui rule seems to be:
```
.ui-tabs .ui-tabs-nav li.ui-tabs-active .ui-tabs-anchor, .ui-tabs .ui-tabs-nav li.ui-state-disabled .ui-tabs-anchor, .ui-tabs .ui-tabs-nav li.ui-tabs-loading .ui-tabs-anchor {
    cursor: text;
}
```
which we probably just need to override the CSS for `.ui-tabs` or maybe specifically just `.ui-tabs-active` , I haven't investigated all the `ui-tabs` areas of OpenRefine but only Undo/Redo and a few Export dialogs.

**Comment by thadguidry** [comment]
@HrithikPadavala Absolutely!  Please read through our Contributing guide.  Looking forward to your PR.

**Comment by GittyHarsha** [comment]
@thadguidry can you review my PR #6811.
I did a simple fix.

**Comment by tfmorris** [comment]
Since this was apparently a conscious design choice by the jQuery UI Tabs designer
https://github.com/jquery/jquery-ui/blob/54f96eea31b21d9ecb00912261df3e5aaebf8cce/themes/base/tabs.css#L38-L42
probably to indicate that the active tab isn't clickable, do we feel we have sufficient weight of evidence to override their design choice?

**Comment by thadguidry** [comment]
Yes.  And another contributor @wetneb gave thumbs up also.  If you look at other apps, they never show text input cursor on their tabs, it's not logical I think.
