### ISSUE TITLE
wikibase: Render property names in issue reports

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6768]
Sometimes OpenRefine generates Wikibase issues of this form:

> **[male population (P1540)](http://www.wikidata.org/entity/P1540) is missing a [P585](http://www.wikidata.org/entity/P585) qualifier.**
> Statements using [male population (P1540)](http://www.wikidata.org/entity/P1540) such as the one on [Katowice (Q588)](http://www.wikidata.org/entity/Q588) are missing a mandatory [P585](http://www.wikidata.org/entity/P585) qualifier.

Note the fact that "P585" is written without the corresponding name ("point in time" as of today, in English).
This happens for properties which are mentioned in constraints but are not present in the candidate edits or project data.
For instance, the "male population (P1540)" property was input in the schema, so OpenRefine knows its label without having to fetch it from Wikidata, which is why it is already included in the generated issue.

### Proposed solution

It would be much more user-friendly if those properties could also be rendered with the label.
This could be done either in the backend (by fetching the names for the missing properties when generating the issues) or on the frontend-side (by making an API call to the Wikibase instance to fetch them when rendering). In both cases, it would be good to cache this information for the duration of the work session (such as, the lifetime of the OpenRefine web interface) to avoid re-fetching those too often from the Wikibase instance.

### Alternatives considered

Status quo

### Additional context

Follow-up from [the OpenRefine-Wikidata training at Wikimania](https://wikimania.eventyay.com/2024/talk/PBMMEJ/)

**Comment by wetneb** [comment]
@sunilnatraj this looks great!

**Comment by sunilnatraj** [comment]
Thanks @wetneb Can you assign this to me.
