### ISSUE TITLE
File type detection fails when multiple files are imported at once

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6772]
The heuristic to detect file types seems to have a weird behavior when working on multiple files, even though those files have a consistent file type which OpenRefine is able to detect correctly when they are imported individually

### To Reproduce

Create two text files `test.md` and `test2.md`, both containing the following content:
```
## Markdown test

This is a [test](https://gnu.org) test
```

2. Import both of those files at the same time (by selecting them both in the same folder)

### Current Results

The files are incorrectly detected as Excel files, which obviously fails.

### Expected Behavior

They should be detected as text files (which indeed happens when selecting only one file)

### Screenshots

![image](https://github.com/user-attachments/assets/7b44966a-355e-48bc-abe7-008a24380ac0)

### Versions
 - Operating System: Debian testing
 - JRE or JDK Version: 19
 - OpenRefine: 3.9-SNAPSHOT
 
### Additional context
Observed at Wikimania 2024

**Comment by sunilnatraj** [comment]
@wetneb I checked out this issue, my observation is that format field is set as null when uploading multiple files; this causes the rankedFormat list generation to set "text/line-based/*sv" as the best format. this results in the error. 

Setting the format value addresses this issue.  Can you assign this to me.

**Comment by tfmorris** [comment]
I think this is only a problem for files which don't have a known MIME type or a file extension which can be used to guess the format. If you upload multiple CSVs, TSVs, JSON files, etc, the problem doesn't occur. Markdown (.md) files are guessed as "unknown" format.

> this causes the rankedFormat list generation to set "text/line-based/*sv" as the best format

Based on the error, I think it's probably using the format "binary/excel"

**Comment by sunilnatraj** [comment]
@tfmorris The mime type is correctly set "text/markdown", format is set as null; this results in the flow attempting to read it as excel.

**Comment by tfmorris** [comment]
> The mime type is correctly set "text/markdown", format is set as null; this results in the flow attempting to read it as excel.

I think that may be system specific. On my Mac, the MIME type is set to `application/octet-stream`. 
![Screenshot 2024-10-11 at 22 53 56](https://github.com/user-attachments/assets/29f5c221-624b-4c25-9627-3d7c80a52bfe)

The root problem here may have been that the Markdown type is unknown, not that there were multiple files, but I may be missing something.
