### ISSUE TITLE
wikibase: check media captions for maximum length before upload

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6777]
On Wikimedia Commons, captions are limited to [maximum 250 characters and cannot contain HTML markup or Wikitext links](https://commons.wikimedia.org/wiki/Commons:File_captions#What_makes_a_good_caption?). When uploading files with longer captions, the structured data is omitted:
https://forum.openrefine.org/t/sometimes-openrefine-forgets-to-add-structured-data-to-wikimedia-commons-and-i-do-not-know-why/1702

### Proposed solution

It would be good to make sure we emit a warning in the Issues tab, warning the user ahead of time that those captions should be made shorter. The warning could have maximal severity so that upload is blocked if the threshold is exceeded.

### Alternatives considered

Cropping the captions so that they fit doesn't seem like a good option as it will likely not cut the caption at a meaningful location.

### Additional context

Reported on the forum (see above)

**Comment by lokal-profil** [comment]
Ping @sebastian-berlin-wmse

I think a sanity check on label and description lengths could be useful (also applies to Wikidata), and for the Commons-extension a warning should prevent that row from being uploaded.

There will however be other similar things that can pop up though (e.g. length limits on monolingual fields). I'm not sure it is reasonable to check all of those before attempting an upload. The question here is if the errors returned today are informative enough that
a) you spot that SDC wasn't uploaded
b) what you need to adjust to be able to re-upload it.

**Comment by sebastian-berlin-wmse** [comment]
"Caption" and "label" seems to be used interchangeably, e.g [in FullMediaInfoUpdate](https://github.com/OpenRefine/OpenRefine/blob/4d08a07f2e9680a95085145feb25dd37463566de/extensions/wikibase/src/org/openrefine/wikibase/updates/FullMediaInfoUpdate.java#L33):
```
     * @param labels
     *            the edits on captions
```

Which is better to use? From what I've seen "label" is primarily used in code, but "caption" in interface.

**Comment by wetneb** [comment]
Yes, caption is the user-facing name and label is the internal one indeed. That makes it possible to treat both items and mediainfo entities as "things with labels" internally. It's inherited from Wikibase itself.
