### ISSUE TITLE
Don't populate create tab at startup

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#678]
If the user is logged in to Google Docs, the list of spreadsheets and Fusion tables is loaded at startup time.  This is needless work which should be deferred.

**Comment by wetneb** [comment]
Not sure if this is still current with the new gdata extension.

**Comment by antoine2711** [comment]
Considering that the list of document appears JUST after you logged in, I wouldn't say it's possible that it's being loaded too soon as it cannot be loaded before being logged, and it can't be loaded after the list is displayed. I'd say this part of OR-WD is fine. I used it a lot in 3.1 to 3.3.
Regards, Antoine

**Comment by wetneb** [comment]
Thanks, let's close this then!
