### ISSUE TITLE
Wikidata date upload adds calendar qualifier as URL string instead of entity link

### ISSUE THREAD

**Issue by VojtechDostal** [OpenRefine/OpenRefine#6798]
See eg. this edit:
https://www.wikidata.org/w/index.php?title=Q327064&diff=2230484245&oldid=2155645303

### To Reproduce
1. Format value in a given cell as recommended in the manual: "1539-10-01_Q11184"  
2. Upload to Wikidata 

### Current Results
A weird format of a http URL is added to the date.

### Expected Behavior
Julian calendar should instead be set.

### Screenshots
<img width="483" alt="Bez názvu" src="https://github.com/user-attachments/assets/02a43f90-092a-41a5-b3a4-bc835c849cad">

### Versions
 - Operating System:  Win 11
 - Browser Version: Chrome 127.0.6533.119 
 - OpenRefine: 3.7.3

**Comment by VojtechDostal** [comment]
Ah, I did not know that only these two were allowed. That explains it,then.

I was following the Schema alignment help page which you just updated. Formerly it just specified the format and gave the proleptic Julian calendar as an example ("such as..."). Now it will be clearer, thanks.

**Comment by tfmorris** [comment]
It seems to me that Wikidata should reject invalid values with an appropriate error message, but we'll update the OpenRefine docs to be clearer (thanks @thadguidry !)+
