### ISSUE TITLE
Add UI to handle EDIT / JOIN Columns to perform basics of concatenation.

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#68]
_Original author: thadguidry (May 29, 2010 20:34:08)_

The proposed UI, &quot;Edit Column / Join Several Columns&quot; would allow simple 
column name input with separators to perform the concatenation function:

cells[&quot;col1&quot;].value + &quot;, &quot; + cells[&quot;col2&quot;].value

UI would expose the following input or clickable Add columns in an ordered 
concatenation such as:

New column name, col1, col4, col2

which would perform a merge across col1, col4, col2 in that order and add 
results into &quot;New column name&quot;

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=68_

**Comment by wetneb** [comment]
Closed by #2110.
