### ISSUE TITLE
Github snapshot build action failing on Javadoc generation

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#6874]
I don't understand what changed, but it looks like what used to be Javadoc warnings are now being treated as errors, failing the build. The Maven javadoc plugin version is unchanged, so it must be a config setting (perhaps a Github default?) which has changed.

Last successful build (2 days ago): https://github.com/OpenRefine/OpenRefine/actions/runs/10983260272/job/30492432424
Recent failing build: https://github.com/OpenRefine/OpenRefine/actions/runs/11006936008/job/30562016644

@wetneb Any idea what might have changed?

**Comment by tfmorris** [comment]
@wetneb any idea what specifically might have changed with the snapshot build? It worked two days ago, but doesn't work now. I haven't changed anything that I'm aware of.

**Comment by wetneb** [comment]
What has changed is commit https://github.com/OpenRefine/OpenRefine/commit/0998923c818f5480acf0dcee57d1828aa70cf789, which introduced a Javadoc comment which fails to compile. So I have opened #6875 to fix the build.

**Comment by tfmorris** [comment]
Thanks! An extra pair of eyes definitely helps. I missed that the build for this merge was the first one that was failing and was looking at the dependency updates.

**Comment by wetneb** [comment]
Fixed by #6875. To make it easier to debug those sorts of cases, I have opened #7018.
