### ISSUE TITLE
ODS file incorrectly recognized as XLS

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6877]
When I upload an ODS file to OpenRefine, it tries to parse it as an Excel file first.

### To Reproduce
1. First, upload an ODS file (with a filename such as `test.ods`)

### Current Results

The importer selected automatically is "Excel files" and I get the error:
```
Error during initialization - org.apache.poi.openxml4j.exceptions.ODFNotOfficeXmlFileException: The supplied data appears to be in ODF (Open Document) Format. Formats like these (eg ODS, ODP) are not supported, try Apache ODFToolkit
```
I need to manually select "Open Document Format spreadsheets (.ods)" for it to be parsed correctly

### Expected Behavior

The file is automatically detected as an ODS file and parsed correctly.

### Screenshots

![image](https://github.com/user-attachments/assets/c4d310f8-9fd9-46fb-9206-109830d4ee97)

### Versions
 - Operating System: Debian
 - Browser Version: Firefox
 - JRE or JDK Version: 21
 - OpenRefine: 3.9-SNAPSHOT (master branch)

### Datasets
[test.ods](https://github.com/user-attachments/files/17142008/test.ods)

**Comment by tfmorris** [comment]
This was likely broken by the attempt to fix #6772

**Comment by sunilnatraj** [comment]
@wetneb Can you assign this to me

**Comment by sunilnatraj** [comment]
@tfmorris @wetneb TextGuesser identifies the ODS file as binary, this is because the file signature of zip and ODS is same.
