### ISSUE TITLE
wikibase: Test failure when run on non-English locales

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6911]
When running the test suite with a French locale, I get:

```
[ERROR] Failures: 
[ERROR]   PreviewWikibaseSchemaCommandTest.testWarningData:147 expected [country] but found [pays]
```

This is a symptom of the fact that https://github.com/OpenRefine/OpenRefine/pull/6895 (cc @sunilnatraj) picks the language in which to fetch the labels based on the system locale.

Instead, we should change the command to take this language from the HTTP request so that it can match the language used in the UI (which is often not the same thing as the system locale).

As a temporary workaround, one can [change the locale used by Maven](https://stackoverflow.com/questions/8901880/set-surefire-plugin-locale-in-maven-pom-file) to get the test suite to pass.

**Comment by sunilnatraj** [comment]
@wetneb As the unit test is checking the value of the label, this test case is tied to the en language. My proposal is to update the test to validate the label if the language is "en" and for other languages we validate the label is not empty.  
`                if (Locale.getDefault().getLanguage().equals("en")) {
                    assertEquals(addedPropertyLabel.asText(), "country");
                    assertEquals(itemEntityLabel.asText(), "Canada");
                } else {
                    assertTrue(addedPropertyLabel.asText().length() > 0);
                    assertTrue(itemEntityLabel.asText().length() > 0);
                }`

**Comment by wetneb** [comment]
That's a quick workaround, but I would prefer to fix the underlying issue. The command should not rely on the JVM's default locale in the first place, because this locale will often be different from the language used in OpenRefine's web UI.

As a result, this risks that the labels added in the backend are fetched in a language that's inconsistent with the rest of the interface, which will be odd for users.

That's why I would rather change the command so that it takes the language as a parameter. This would also ease testing.

**Comment by sunilnatraj** [comment]
@wetneb  I did check the language preference setting flow from the UI, it is updating the JVM locale.  Did i miss something here?

`        if (prefName.equals("userLang")) {
            LocaleUtils.setLocale(valueString);
        }`

**Comment by wetneb** [comment]
Ah, I forgot about that… well then we're even less ready for multi-user support than I thought!
Well then, perhaps just set the locale to English before the test (in a `@BeforeMethod`) and restore it afterwards (in an `@AfterMethod`)? Along the lines of [this](https://stackoverflow.com/a/76430798/985087), but for TestNG

**Comment by sunilnatraj** [comment]
@wetneb Thank you; raised PR
