### ISSUE TITLE
Wikidata login failed

### ISSUE THREAD

**Issue by strainu** [OpenRefine/OpenRefine#6941]
We were unable to login to production wikidata from the latest version of OoenRefine. 

### To Reproduce
1. Download OpenRefine 3.8.4, prepackaged exe for Windows and install on Windows 10
2. Prepare a Wikidata change and try to apply it
3. When asked for login, use the normal wikidata login (reproduced for both new and old accounts, 5 in total, using different internet connections) 

### Current Results

Login fails with a message indicating wrong credentials were introduced 

### Expected Behavior

Login should be OK

### Versions
 - Operating System: Windows 10
 - Browser Version: Edge, Chrome and Firefox latest versions
 - JRE or JDK Version: 
 - OpenRefine: 3.8.4 prepackaged installer. 

### Datasets
Probably not relevant, but can be provides on request

### Additional context
Found during a training session and reproduced reliably by both participants and trainers.

Not sure if relevant, but we had reconciled the data using the Romanian endpoint, not English

**Comment by tfmorris** [comment]
Sorry to hear about the problem! Can you try (re)installing 3.8.2 to see if it works with the same credentials? That would help isolate the problem to the latest release.

**Comment by strainu** [comment]
I will. So far I can confirm it worked in 3.7.9

**Comment by wetneb** [comment]
It seems to be linked to the CSRF-related changes I did to fix one vulnerability, I'll work on a fix.

**Comment by tfmorris** [comment]
This should be fixed in the 3.8.5 release available now.

**Comment by wetneb** [comment]
Well done! It could be worth updating https://github.com/OpenRefine/openrefine.org/blob/master/releases.json so that it's offered for download on the website ([6th step of the release process](https://openrefine.org/docs/technical-reference/version-release-process))

**Comment by tfmorris** [comment]
Oh, **that's** where the release process is documented! I wonder why it didn't show up in any of my searches of openrefine.org. :( It's pretty close to what I guessed at.

I've created a PR for releases.json and to update the release instructions based on my last run
