### ISSUE TITLE
Poor VM performance during JSON import

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#699]
Split from #698 

Importing a 123 MB, 330K object JSON file into a Refine server with 1 GB of VM allocated takes an extraordinarily long time.

Jconsole shows heap usage oscillating quickly between 500MB and 700MB with over 13 CPU minutes having been spent on 32K+ PS Scavenge GC operations, so something is continually creating and destroying large objects (or large numbers of objects).

**Comment by magdmartin** [comment]
Moving to 2.7 milestone to reduce the scope of 2.6 to speed up the release.

**Comment by tfmorris** [comment]
All tests are currently passing on Mac OS X.
