### ISSUE TITLE
Quickstatements export not working

### ISSUE THREAD

**Issue by mbch331** [OpenRefine/OpenRefine#7015]
### To Reproduce
1. Click on Wikidata
2. Select QuickStatements from the export options

### Current Results
A new tab opens with a json which contains an error message
{"code":"error","message":"Missing or invalid csrf_token parameter"}

### Expected Behavior
CSV to download

### Versions
 - Operating System:  Ubuntu 24.04.1 LTS
 - Browser Version:  Firefox 133.0 (64-bits)
 - JRE or JDK Version: 
 - openjdk 21.0.5 2024-10-15
OpenJDK Runtime Environment (build 21.0.5+11-Ubuntu-1ubuntu124.04)
OpenJDK 64-Bit Server VM (build 21.0.5+11-Ubuntu-1ubuntu124.04, mixed mode, sharing)

 - OpenRefine:  3.8.7

### Additional context

URL in the address bar http://127.0.0.1:3333/command/core/export-rows/statements.txt?undefined

Related messages in openrefine console:
11:49:30.778 [                   refine] GET /command/core/get-csrf-token (244986ms)
11:49:31.267 [                   refine] POST /command/core/export-rows/statements.txt (488ms)
11:49:31.437 [                butterfly] GET /favicon.ico [main] (170ms)

A CSRF token is requested.

**Comment by wetneb** [comment]
That's really embarrassing… It's due to me using `$.attr` instead of `$.param`, which is a mistake I did catch earlier, but I have no idea why it didn't make it into my commit.
