### ISSUE TITLE
XML/HTML import - empty cells, auto-type guessing, headers

### ISSUE THREAD

**Issue by ivankovalenko** [OpenRefine/OpenRefine#702]
When importing tables in html format some problems occur (Version 2.5 [r2407])
- cant parse headers from th or any other first row
- cant parse empty cells like <td></td> - the cell is empty and ruines the row/column
- when importing autoguesses cell type - and no way to switch off so phone numbers become corrupted
- when importing html table - the table is parsed into one-column table

Example file

``` html
<table>
<tr>
    <th>name</th>
    <th>phone</th>
</tr>
<tr>
<td>a</td>
<td>+7(000) 21323</td>
</tr>
<tr>
<td>b</td>
<td>444 4444</td>
</tr>
<tr>
    <td>c</td>
    <td></td>
</tr>
</table>
```

![Screen Shot 2013-04-09 at 15 05 41](https://f.cloud.github.com/assets/1657082/356393/7785abe0-a105-11e2-8289-0ca4f99f1deb.png)
##

**Comment by wetneb** [comment]
It looks solved, so closing.
