### ISSUE TITLE
Support Needleman Wunsch distance for clustering

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#703]
Details here:

http://en.wikipedia.org/wiki/Needleman%E2%80%93Wunsch_algorithm

**Comment by wetneb** [comment]
I'd argue this is too specific, it could be implemented in an extension perhaps. Otherwise it's not clear to me how this would be integrated in Refine. Closing this now, feel free to reopen if you have a concrete plan to integrate this.

**Comment by thadguidry** [comment]
@wetneb Let's not be too hasty here and throw this out just yet...(reopening)

NeedlemanWunsch is just a different string distance algorithm, and it's already available in our existing [secondstring.jar](https://github.com/OpenRefine/OpenRefine/blob/master/main/lib-local/secondstring-20100303.jar) ... we don't expose it however...https://github.com/TeamCohen/secondstring/tree/master/src/com/wcohen/ss

@wetneb I think probably the hardest part would be getting a custom Facet(s) for display that is useful for Bioinformatics folks (like we did with Scatterplot) ... but the display(s) needed differ on context and needs... Matrix, Matrix Heat, Dendrogram's, etc.
1. https://www.mathworks.com/help/bioinfo/ref/nwalign.html
2. https://gist.github.com/slowkow/508393
3. https://medium.com/@bostjan_cigan/using-the-needleman-wunsch-algorithm-to-draw-evolutionary-trees-90d9db149413

When you attend the CZI conference later on, I think it would be good to ask folks there to look at this issue and my comments and get some needed feedback from them.... we can always put the work TODO into 2021 and other grants :-)

**Comment by wetneb** [comment]
Ok, so let's say this issue is about adding support for Needleman Wunsch distance in clustering then?

**Comment by thadguidry** [comment]
@wetneb It's Scoring, rather than clustering.... Scoring clusters....but displaying the scores in various ways as I linked to above.  I'd suggest talking to CZI folks later when you get there...would be very interesting to hear their opinions and then write down the summary needs into this issue.

**Comment by wetneb** [comment]
I can't go talk to biologists and ask them to give meaning to this issue :) If a biologist comes to me and asks for Needleman-Wunsch support, then I can ask them how they expect it would work.

An issue must come with a clear ask: how would you want this thing to be integrated in OpenRefine?

It's not enough to say "this is an algorithm that biologists seem to use, we should have it", do you see what I mean?

**Comment by wetneb** [comment]
> Additional context: It was brought up at an OpenRefine user group meeting in Dallas where a few Bioinformatics scientists asked about this support directly...but it's been ages ago and I forgot a lot of their challenges, but I think that Medium article I linked to jogs my memory of their research work.

Great! If you can find that biologist and ask them what they were concretely thinking of, it would be great! Otherwise this issue is not likely to get much love - the risk is that we implement something and it does not actually meet the user's needs at all.

**Comment by thadguidry** [comment]
@wetneb I sense a bit of hostility.  Let's be a bit less rigid and just spend 5 mins with someone at CZI regarding this, since we do know that many of our OpenRefine users are in fact in the Bioinformatics space....and you will be meeting many of them at CZI conference.  This issue will become more clear after you talk just 5 mins with someone there ... just breathe.

**Comment by wetneb** [comment]
There is no hostility at all! Just imagine the situation: I meet a biologist. I can ask them "hey, do you use the Needleman-Wunsch algorithm? How do you think we should integrate it in OpenRefine?"

The chances that this biologist uses this algorithm AND has any experience with OpenRefine AND can figure out a way in which integrating the two would be useful are extremely small.

When someone asks us for such a feature, then we need to understand as soon as possible (i.e. before the end of the workshop if that's an IRL thing) what this user means and how it could potentially work in OpenRefine. Otherwise, it's a lost battle.

**Comment by tfmorris** [comment]
So, this was open for 6 1/2 years with nary a nibble of a "I need this too." I think I'm also on the side of "close this until someone who comes along who needs it." 

And that's speaking as someone who's worked in bioinformatics for the past few years and has burned many core-years aligning nucleotides.

**Comment by thadguidry** [comment]
@tfmorris Correct, because we don't have good tooling in OpenRefine for bioinformatics.  The current Clustering UI we have wouldn't be ideal for Needleman Wunsch and bioinformatics needs anyways.  We could improve that, but we should focus on what we do better.

So closing.
