### ISSUE TITLE
Replace Ant with Maven for dependency management

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#71]
_Original author: dasjogibtsnet@gmail.com (June 10, 2010 10:02:17)_

in order to not having all the libraries in version control, i would suggest using maven in order to declare dependency libs.
http://maven.apache.org/

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=71_

**Comment by junwei-wang** [comment]
why not build openrefine with `maven` package bundled instead of other library????
It's really a bad idea to use ant.

**Comment by magdmartin** [comment]
For reference here is the most recent discussion on that topic and why we are staying with ant: https://groups.google.com/d/msg/openrefine-dev/NT4tNgSzYZw/Amq1_jZ_aqIJ

**Comment by junwei-wang** [comment]
Covention is usually better than congfiguratuion. Hence, maven is better
than ant. I couldn't edit ant configuration any more. I would create a
branch which is built with mvn.
2015年8月5日 23:43于 "magdmartin" <notifications@github.com>写道：

**Comment by fpompermaier** [comment]
+1 for using maven..definitely

**Comment by jackyq2015** [comment]
+1 for the maven. Also I noticed that there's some issue with the automation test. Not sure it can be fixed in a decent way after migrating to maven.

**Comment by junwei-wang** [comment]
@jackyq2015 @fpompermaier 
[OpenRefine with Maven](https://github.com/junwei-wang/OpenRefine)

For now, you can build OpenRefine by type
```sh
mvn clean package
```
and start refine by
```sh
java -jar server/target/openrefine-server-2.7.0-SNAPSHOT.jar
```

**Comment by jackyq2015** [comment]
That's great! Thanks for your effort.

Few comments:
1. Your PR failed to build: 
https://github.com/OpenRefine/OpenRefine/pull/1054

2. I think you can still use the "refine" script under root to start the openrefine. It provided more options.

**Comment by junwei-wang** [comment]
@jackyq2015 I see the CI error. Do not worry. I will update the code relating with your two issues in the near future.

**Comment by magdmartin** [comment]
See PR  #1493

**Comment by thadguidry** [comment]
I've started on this and will fully convert the Ant build scripts to Gradle.  Those with Eclipse IDE can install the newest Buildship plugin as a precursor to my PR coming in the next few weeks.

**Comment by thadguidry** [comment]
@wetneb halfway done

**Comment by thadguidry** [comment]
@wetneb Actually, I'd rather baby step this... Can we move to Maven first ?  Don't we already have a PR past where someone did most of that work already and we could just tweak to get the Maven build working properly ?

**Comment by fpompermaier** [comment]
We have a mavenized version of OpenRefine it this could help

**Comment by ostephens** [comment]
Just moved this into the 3.1 milestone - @thadguidry @wetneb is this correct? (i.e. is this where we are targetting this change?)

**Comment by wetneb** [comment]
@ostephens yes, thanks! I am also closing this to reflect the fact that the migration was done.
