### ISSUE TITLE
Import of spreadsheet with mutliple worksheets hangs

### ISSUE THREAD

**Issue by biofool** [OpenRefine/OpenRefine#713]
I have a spreadsheet that has a couple thousadn rows spread out over maybe 20 worksheets.  If I just try to import one or two it works fine but if I try to import all of them the import always hangs (twice I let it run for over an hour).

I can provide the spreadsheet.  Also I used some simple perl code (yeah I'm that old :^) to convert the mutli worksheet thing into a single worksheet and that imports into refine just fine.
##

**Comment by wetneb** [comment]
@tfmorris could you share the dataset so that any contributor could tackle this bug?

**Comment by biofool** [comment]
I can no longer reproduce the problem.  I would close it I think.

Don't get Mad
Don't get Even
Get the Electors the truth! NOW!
<https://secure.avaaz.org/campaign/en/stolenelection21/?cqOrokb>

Create a Beautiful World <http://createabeautifulworld.com/>

**Comment by wetneb** [comment]
@biofool thanks! closing then.
