### ISSUE TITLE
ngram Fingerprint

### ISSUE THREAD

**Issue by stucki1984** [OpenRefine/OpenRefine#723]
Hello,

I´ve problem with the ngram Fingerprint method. When I start it the custom setting is 2. After changing it to 1, refine crashes....Why? How and where can I manually type in the posted code? How and where do I set the specific column I want to apply the ngram Fingerprint on?

Thanks.

Regards,

JS
##

**Comment by wetneb** [comment]
@stucki1984 I'm closing this as non-reproducible as you have not provided any example data - feel free to reopen if you can find that.
