### ISSUE TITLE
Implement front end browser-based UI tests

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#733]
The testing tool that we use for our (relatively limited) front end tests is basically abandoned, so we should switch to something better supported such as Selenium 2.  One possibility would seem to be to use a free open source plan from Sauce Labs in conjunction with our Travis CI build/test setup.

http://sauceio.com/index.php/2013/03/run-your-selenium-tests-completely-in-the-cloud-using-travis-ci-and-sauce-labs/

**Comment by tfmorris** [comment]
So it looks like Windmill got disabled in 2017 https://github.com/OpenRefine/OpenRefine/commit/9bc2c3078544b0898649bfb3fd3ab81d8d438616 and hasn't been replaced with anything.

Going from minimal UI tests to no UI tests is probably not the direction that we want to be trending...

**Comment by wetneb** [comment]
(Just to make it clear: the tests that were disabled by this commit were not running at the time - Windmill was already broken and unmaintained)

**Comment by wetneb** [comment]
I think we can close this, based on the awesome work of @fgiroud and @kushthedude!
