### ISSUE TITLE
Remove cases where UI blocks access to Exporting the undo/redo data

### ISSUE THREAD

**Issue by Downchuck** [OpenRefine/OpenRefine#736]
Some projects for whatever reason may go wrong; this is likely to happen with a large data set (see issue #720). When a project does become inaccessible, it can be difficult to access the undo/redo history in order to revive the project from scratch. The UI blocks access to this data with the "Working..." animation. If the Undo history list were accessible, the work on the project could still be salvaged regardless of what broken state it is in.

**Comment by thadguidry** [comment]
A refresh of the browser page might make things useable again, but if a background operation is still pending then the state might not be valid anymore. 

**Improvement Idea:** Long-running operations are distinctly defined by OpenRefine and we don't currently have a default timeout (I think) for Long-running operations or a way to quickly let users know..."Hey, this might take a while...ok?  If this takes too long, click CANCEL on the Spinner dialog that comes up to force cancel the operation".

**Comment by wetneb** [comment]
This issue is not really about the undo/redo data, but rather the way some operation creates the "Working…" dialog with no cancel option for too long. Unfortunately it is hard to tell from this issue which operation caused this dialog to appear, so there is not much we can do here.
