### ISSUE TITLE
RecordCells is unreasonably slow for getField on large result sets

### ISSUE THREAD

**Issue by Downchuck** [OpenRefine/OpenRefine#740]
Some large result sets may have thousands of rows contained within a single record. It appears that the implementation of RecordCells.getField in WrappedRow.java is very inefficient. At present, it's much quicker to fill down than to use row.record.

**Comment by thadguidry** [comment]
getField() is not intended to be used that way.

It is faster and easier if you instead select ONLY the row or rows you need from the Record array.

This gets only the 2nd row of the Record array
`row.record.cells["Column 1"].value[1]`

![howtofillcellsupwards](https://user-images.githubusercontent.com/986438/43036011-86980efc-8cbe-11e8-8493-e8a1fd934e8f.PNG)

If you want to get multiple rows then just use Array slicing

This gets the 1st through 4th row of the Record array
`row.record.cells["Column 1"].value[0,3]`

This gets the 2nd through 4th row of the Record array
`row.record.cells["Column 1"].value[1,3]`

![howtogetselectedrowsfromrecords](https://user-images.githubusercontent.com/986438/43036041-4c394b76-8cbf-11e8-9c81-39607714d64e.PNG)
