### ISSUE TITLE
Fill down and blank down per record

### ISSUE THREAD

**Issue by Downchuck** [OpenRefine/OpenRefine#742]
As mentioned in the article "[Fill down the right and secure way](http://googlerefine.blogspot.com/2012/03/fill-down-right-and-secure-way.html)" it would be helpful to have a blank down and fill down with record awareness. Currently, a blank down would cross record boundaries. In some cases, this isn't the desired behavior and a various temporary transforms may need to be applied to get the desired behavior (of just running blank down on a per record basis).

**Comment by ettorerizza** [comment]
Issue still relevant for many users : https://groups.google.com/forum/#!topic/openrefine/TjxiExVpJ6w

**Comment by ettorerizza** [comment]
There should be a way to create a _safe_ "Fill/Blank Down", since we know the number of records and the length of each in the previous column (I do not know if I'm clear?) 

Another important improvement would be a "Fill/Blank" ALL, which would allow to get in a click a clean denormalized dataset.

**Comment by wetneb** [comment]
I think we should make sure Fill down works as expected in Records mode. I would be in favor of fixing that before 2.9.

**Comment by ettorerizza** [comment]
Just a little visual reminder of the problem, for the sake of documentation. In this case, the 1 in the first record spreads to the second record.

![screencast](https://user-images.githubusercontent.com/6286410/37525061-ff926664-292b-11e8-8599-0230e84b07e9.gif)

**Comment by thadguidry** [comment]
@wetneb Can you work on a fix for this over the next 2 weeks ? (invoice-able work)

**Comment by tfmorris** [comment]
There is extensive discussion of what actually got implemented in #1573 and #1803, although I was unable to find a concise description.
