### ISSUE TITLE
Unable to Open Projects in Windows 7 64bit Error:Cannot run program "open" CreateProcess error=2

### ISSUE THREAD

**Issue by shawnholt** [OpenRefine/OpenRefine#749]
Spent a long time on this.  Tried several versions.  installl / uninstall Java Runtime (and JDK) moved to location w/out spaces.  Unable to browse directory and apply extensions. full error:
/command/core/open-workspace-dir: java.io.IOException: Cannot run program "open" (in directory "K:\Users\Shawn\AppData\Roaming\Google\Refine"): CreateProcess error=2, The system cannot find the file specified

Also, does not open browser on startup.
During startup here are messages on console:
17:59:14.356 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
17:59:14.358 [            refine_server] refine.memory size: 1024M JVM Max heap: 1037959168 (2ms)
17:59:14.396 [            refine_server] Initializing context: '/' from 'K:\lodrefine\webapp' (38ms)
17:59:16.525 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (2129ms)
17:59:16.532 [            refine_server] Creating new workspace directory K:\Users\Shawn\AppData\Roaming\Google\Refine (7ms)
17:59:16.533 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (1ms)
17:59:16.557 [                   refine] Starting LODRefine 1.0.7 []... (24ms)
17:59:16.604 [       FileProjectManager] Failed to load workspace from any attempted alternatives. (47ms)
17:59:21.031 [..on.DefaultConfiguration]
##

**Comment by wetneb** [comment]
This issue is about LODrefine, a fork of this project. Please reopen if you can reproduce this with OpenRefine 2.7.
