### ISSUE TITLE
Support reconciliation for non-English names

### ISSUE THREAD

**Issue by ganqqwerty** [OpenRefine/OpenRefine#750]
I try to reconcile the data and I have column containing Russian names of universities. You can see those names in Freebase after this query: 

``` javascript
[{
  "type": "/education/university",
  "name": {
    "lang": "/lang/ru",
    "value": null
  },
  "/location/location/containedby": [{
    "name": {
      "lang": "/lang/ru",
      "value": null
    }
  }]
}]
```

However when I try to reconcile the names for the type /education/university I have 0% of reconciled data.
##

**Comment by wetneb** [comment]
This is fully supported by the Wikidata reconciliation service \o/
