### ISSUE TITLE
Merge ColumnGroup model and Protograph

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#76]
_Original author: iainsproat (June 17, 2010 11:08:53)_

The ColumnGroup model and the Schema alignment protograph are both tree structures describing the relationship between columns.  These models could be merged.

Benefit:
When importing data with a tree structure, such as an Xml file or Json, the columngroup model is automatically created.  When opening the schema alignment dialog, the column relationship is shown as flat - all the tree data is lost and has to be recreated by the user.  If merged the tree would be retained.

Problems:
If the combined protograph is altered in the schema alignment dialog, then the exported data would not match the structure of the original as the columngroup is also changed.  This may not be intended.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=76_
##

**Comment by wetneb** [comment]
I think it is pretty clear now why this should not be done. The ColumnGroup model is a notion that is independent from any knowledge base, while the protograph is specific (Freebase-specific, RDF-specific, or hopefully soon Wikidata-specific).

Potentially, OverlayModels can be very different from trees of columns (and they will not always have the same metadata). So I propose to close this issue.
