### ISSUE TITLE
TRUNK being displayed for revision of released kit

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#768]
The 2.6-alpha1 kit reports it's version as 2.6-alpha1 [TRUNK].

**Comment by tfmorris** [comment]
Despite the referenced fix, the revision still isn't getting set, at least on Mac with the 2.6-rc1 kit.  This will need more investigation.

**Comment by magdmartin** [comment]
it also show on the linux 2.6-rc1 version

**Comment by jackyq2015** [comment]
Are we talking about the revision number at the right bottom on the start page?

I think something like 2.6.123456 is expected. In that way, we can exactly identify which revision we are using from the repository.

**Comment by jackyq2015** [comment]
Need some configuration file hosted as well as code change. Move to 2.7 milestone

**Comment by tfmorris** [comment]
This needs at least a minimal fix before the 2.6 release.  One possibility would be to remove the "TRUNK" nomenclature and depend on developer discipline to always create useful version numbers.

**Comment by thadguidry** [comment]
@jackyq2015 is this fairly well RESOLVED now, in our present ways of releasing ?  Can this be closed now ? or still an issue for Mac Kits in particular ?

**Comment by wetneb** [comment]
Fixed by #1856.
