### ISSUE TITLE
Multiple protographs

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#77]
_Original author: iainsproat (June 17, 2010 11:35:16)_

Gridworks should support multiple protographs.  This would allow flexibility in reconciliation (e.g. protographs for external reconciliation services in addition to Freebase). If issue #75 is implemented it would also allow flexibility in uploading and exporting (e.g. ability to export to different XML or json schemas).

It would also assist in the problem identified in issue #76. (changes to a combined protograph/columngroup model required for reconciliation purposes would affect exporting and vice versa).

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=77_
##

**Comment by wetneb** [comment]
This was solved by f5fc44e24e8e5398b1de3cac4f41f2feb70b7924:
https://github.com/OpenRefine/OpenRefine/commit/f5fc44e24e8e5398b1de3cac4f41f2feb70b7924#diff-a6c9ecf8444bfcf85e906bbe5961faeaR48
