### ISSUE TITLE
Switch from JSONRPC to HTTP BATCH for Google APIs

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#770]
The JSONRPC API has been deprecated https://developers.google.com/api-client-library/javascript/features/rpcbatch
and replaced with HTTP Batch https://developers.google.com/api-client-library/javascript/features/httpbatch

We need to switch the reconciliation service (and anything else that uses it) over to the new API

**Comment by thadguidry** [comment]
@jackyq2015 Can we close this ?

**Comment by jackyq2015** [comment]
Yes. In place since version 3.0 beta
