### ISSUE TITLE
Support Faceting in Export API

### ISSUE THREAD

**Issue by iloveitaly** [OpenRefine/OpenRefine#772]
Right now it doesn't seem possible to facet an export through the API.

Looking at the best API docs I could find (the wiki page on an python client repo) it references a `facets` parameter, but [looking at the source](https://github.com/OpenRefine/OpenRefine/blob/f1387bdb24070b847f9a80be2b68b4c134efefa9/main/src/com/google/refine/commands/project/ExportRowsCommand.java) it doesn't seem like that parameter is supported.
##

**Comment by wetneb** [comment]
So, facets are already taken into account for export, closing.
