### ISSUE TITLE
Rename data directory from Google/Refine to OpenRefine

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#777]
One last bit of branding cleanup.  It's not strictly necessary, but it'll cause less confusion in the future.

**Comment by Aubreymcfato** [comment]
Hi all. 
I use Google Refine 2.5, and I downloaded yesterday OpenRefine 2.6.
Unfortunately, OpenRefine doesn't work for me (it doesn't show some buttons and texts): I switched back to GR, but I lost all my projects. 

I saw [here](https://github.com/OpenRefine/OpenRefine/releases/tag/2.6-beta.1) that I have to change the URL for the data, but it's not working. 
I tried:

* `JAVA_OPTIONS=-Drefine.data_dir=/aubrey/home/.local/share/openrefine/`
* `JAVA_OPTIONS=-Drefine.data_dir=C:\Users\user\AppData\Roaming\OpenRefine` (copying the URL from a friend)

I actually see the projects browsing in my local directory, I even tried to copy them in the right directory, but still not working...
