### ISSUE TITLE
Number to String (NO scientific notation)

### ISSUE THREAD

**Issue by dantexier** [OpenRefine/OpenRefine#782]
Hi *,

I have an column of type integer and I want to transform a string, but the value 21358081 transform it in scientific notation, ie what makes 2.1358081E7.

Obviously I want to get the string: 21358081

The changes I did in two ways and the result is the same (scientific notation):
1. Edit Cells --> Common Transforms --> To text
2. Edit Columns --> Add column based  on this column, and, my expression (GREL) is value.toString()

Can you help me?

Thanks

**Comment by ovillemain** [comment]
Another solution: use language "Python / Jython" rather than "GREL" with the expression "return str(value)"
