### ISSUE TITLE
Freebase extension I18N strings missing from "default" language

### ISSUE THREAD

**Issue by lmsanch** [OpenRefine/OpenRefine#797]
After reconciling some data with Freebase, using Open Refine 2.6,  I am trying to "Add column from Freebase", and that option is not present.
I have tried both the OSX and Linux installs, and they both have the same problem. Thanks

![nmi7j](https://f.cloud.github.com/assets/3156487/1063524/3f3a6860-12c6-11e3-8635-00e7b3405db9.png)

**Comment by kabhinav** [comment]
I am running refine from master branch and I have updated the language settings on Windows but I still have the same problem: undefined is displayed in extensions?

**Comment by Narendrao9** [comment]
Hi tfmorris,

I am facing the same issue (add columns from free base is not present in the dropdown).

The workaround which you have provided doesn't solve the problem.

Could you help me in this ?
