### ISSUE TITLE
Implement Wikidata reconciliation (was Freebase) [$265]

### ISSUE THREAD

**Issue by ghirardinicola** [OpenRefine/OpenRefine#805]
tfmorris suggest it could be an upgrade issue and this service should not be used.
The reconciliation services I see are:
- Sindice (dbpedia.org)
- Sindice
- Freebase Reconciliation Service (the one tested here)
- Freebase Query-based Reconciliation (is this the only one supported right now?)

ERROR REPORTED 
11:36:13.186 [ refine] POST /command/core/guess-types-of-column (9400ms)
11:36:16.806 [ command] Failed to guess cell types for load
##

**Comment by thadguidry** [comment]
I have updated the bounty / issue to reflect the new needs for Wikidata Reconciliation.  (Given that Freebase is going away and will be absorbed into Wikidata this spring)

The starting point for those interested looks like this:

https://www.wikidata.org/w/api.php?action=wbsearchentities&search=Valve&language=en&type=item

Help for the Wikidata API is here: https://www.wikidata.org/w/api.php

**Comment by magnusmanske** [comment]
I did implement one a while ago, partially. Will that do?
https://tools.wmflabs.org/wikidata-reconcile/

**Comment by magnusmanske** [comment]
Plus, git:
https://bitbucket.org/magnusmanske/reconcile

**Comment by thadguidry** [comment]
@magnusmanske 
Its a bit more than just your server side on Wikidata :) changes also need to be done on our client side in OpenRefine as well.  Essentially, the Freebase Standard Reconcile as a default needs to be replaced.  This requires working through and cleaning up most of the Java, JS, HTML, and JSON files here: https://github.com/OpenRefine/OpenRefine/search?utf8=%E2%9C%93&q=reconciliation+OR+reconcile+OR+recon&type=Code

The bounty gets awarded when both parts are done.  The bounty can be split between developers if they wish, for instance, if you want to have someone do the client side improvements in our code, while you take credit and a partial bounty for the server side.  Up to those involved, we don't care as long as it gets done properly and tests complete.  Good luck, get others involved, or finish it all yourself :)

**Comment by wetneb** [comment]
I'm starting to work on this. I am building a more complete server here: https://github.com/wetneb/openrefine-wikidata

**Comment by wetneb** [comment]
@thadguidry Can we close this issue?

**Comment by thadguidry** [comment]
@wetneb Yes, and you can request the bounty on BountySource.com

**Comment by wetneb** [comment]
Thanks a lot!!
