### ISSUE TITLE
Extend toString(value,format) to work with numbers

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#816]
Currently the format string is only used when formatting dates, but it would be desirable to have it work with numbers as well.  This would allow for things like radix conversion, integer formatting of large numbers, etc.  Dates would continue to get formatted using SimpleDateFormat, but numbers would get passed to java.util.Formatter.

**Comment by tfmorris** [comment]
This snippet will work, but after playing with it, I think it's too confusing for the user to deal with our multiple internal number representations, especially since we transparently coerce them as necessary everywhere else.  We'll need a better solution.

            if (args.length == 2 && args[1] instanceof String) {
                Object o2 = args[1];
                if (o1 instanceof Calendar || o1 instanceof Date) {
                    DateFormat formatter = new SimpleDateFormat((String) o2);
                    return formatter.format(o1 instanceof Date ? ((Date) o1) : ((Calendar) o1).getTime());
                } else if (o1 instanceof Number) {
                    return String.format((String) o2, (Number) o1);
                }

**Comment by thadguidry** [comment]
The best code I have seen for dealing with number formatting is in Pentaho and its usage of [java.text.NumberFormat](https://docs.oracle.com/javase/9/docs/api/java/text/NumberFormat.html) to handle this with Format Masking and NumberFormat can uses different Locale's

`NumberFormat nf = NumberFormat.getInstance(Locale.FRENCH);`

https://github.com/pentaho/pentaho-kettle/blob/master/core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java#L81

https://github.com/pentaho/pentaho-kettle/blob/master/core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java#L957

https://github.com/pentaho/pentaho-kettle/blob/master/core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java#L1339

https://github.com/pentaho/pentaho-kettle/blob/master/core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java#L3815

**Comment by thadguidry** [comment]
Yet another possible way would be to use [java.text.MessageFormat](https://docs.oracle.com/javase/9/docs/api/java/text/MessageFormat.html) ?

**Comment by wetneb** [comment]
This is a legitimate enhancement request so removing the "to be reviewed" tag.

**Comment by tfmorris** [comment]
So, it looks like perhaps this didn't get documented because it wasn't a great solution. I guess the question now is whether we need to maintain backward compatibility for the (undocumented) format strings. We should also think about how we extend this to non-default locales.

The one-parameter version uses `Double.toString()`/`Long.toString()` while the two parameter version uses `String.format(pattern string, number)`.

Perhaps we should switch to a different function (`format()`) for compatibility and use `Number.getInstance().format()` for the single argument version and `DecimalFormat(pattern)` for the two argument form (and specify how non-default locales work).

**Comment by Binita-tech** [comment]
I would like to work on this issue, kindly assign it to me.

**Comment by elroykanye** [comment]
Hey @Binita-tech , thanks for offering to help. Let me know if you face any issues.

**Comment by thadguidry** [comment]
@Binita-tech This issue deals with allowing the user to have explicit **manual** control of number formatting, regardless of Locale specified on their system or through a Java environment setting or property.  In that above comment I was just showcasing how Locale can have an impact depending on how an implementation is done for this issue.

Babel (Python) has the ability to force custom number patterns, regardless of locale, for instance: https://babel.pocoo.org/en/latest/numbers.html
and that's basically what this issue's implementation should do...allow the user to force their custom number format pattern they want.

I would say that:  Locale **should not** have any impact on a user's ability to format numbers however they wish at GREL expression time.  We should give users the final choice, above and beyond their system's current OS Locale setting, or the Java system property.  For example, they might be a Canadian professor working with a Ukrainian dataset with currencies and needing to format numbers for peers that are doing machine learning processing with the cleaned data... in German.

So, for this issue, let's focus only on the enforced number format supplied by a user, and skip any implementation of the autoformatting by Locale with a 3rd parameter for now.  That can come as a future enhancement addressing #1894 which likely would just extend number format support to take into account that Locale parameter similar to how Babel and .

**Comment by elroykanye** [comment]
> So, for this issue, let's focus only on the enforced number format supplied by a user,

@thadguidry , so this means that the we just have to adjust toString to taking 2 parameters - the number, the user locale. The locale could be something like `en`, which will then map this short ISO639-2 code to the actual locale before formatting.
Is this in that light?

**Comment by thadguidry** [comment]
@elroykanye No, not Locale (we deal with that later in #1894).  The 2nd argument would be a format pattern.  See @tfmorris comments.  We basically have a 1 arg and 2 arg version of the `toString()` function.  But I am not sure the current state of things in our main branch.  And so you might check with @wetneb to have his thoughts here before anyone begins work on this.

**Comment by elroykanye** [comment]
Alright then, I would suggest then that @Binita-tech waits for that to come up before continuing on with this.

**Comment by antoine2711** [comment]
> And so you might check with @wetneb to have his thoughts here before anyone begins work on this. But if @wetneb thinks that both issues can be addressed at the same time, (…)

I think @thadguidry it is very safe here to assume that both problems are different enough, and with little overlay, that 2 issues are better. You intuition seams good in my mind. Let's focus on the format in @tfmorris comment and leave LOCALE for another issue.

Regards, Antoine

**Comment by ostephens** [comment]
I can see that @elroykanye has done a PR for this, but I have to admit that I'm completely confused as to what we are trying to achieve here at this point.

The `toString()` GREL function already works with numbers (see https://docs.openrefine.org/manual/grelfunctions#tostringo-string-format-optional) using formatting syntax as per https://docs.oracle.com/javase/8/docs/api/java/util/Formatter.html 

I don't love the formatter syntax as it does not seem very user friendly to me, and I always have to Google solutions when I'm trying to use it to achieve a specific format ... but it does work and it is already available in OpenRefine.

What improvements are we now trying to make here?
