### ISSUE TITLE
Profile and improve performance of slow JQuery actions (or use AngularJS)

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#823]
MontageJS www.montagejs.org has many features such as declarative data binding and a managed draw cycle that are useful, concise, performant, and easier than JQuery.  I have talked to the developers and they have looked at OpenRefine and agree that from a design perspective, our 2 projects are very compatible.  I will begin to try to replace simple gui dialogs, then moving on to facets, and the data grid.

This is a 3.0+ milestone.
##

**Comment by thadguidry** [comment]
A good place to start looking for performance problems I think is that we try to do the following with jQuery in a few places.
Common Pitfalls found under AngluarJS's FAQ's:

>ng-repeat

>ng-repeat gets this a lot. People try to use jQuery (see above) to add more elements to some container as they're fetched from the server. No, bad dog. This is what ng-repeat is for, and it does its job very well. Store the data from the server in an array on your $scope, and bind it to the DOM with ng-repeat.

**Comment by tfmorris** [comment]
Yes, doing large numbers of live incremental updates is bad because of continuous relayouts and a whole host of other issues.

**Comment by thadguidry** [comment]
There is still a small issue with the dual licensing ExtJS has.
I think AngularJS architecture overall is more comfortable for developers
and that is the most important for the architecture porting work to be
done..

Thad
+ThadGuidry <https://www.google.com/+ThadGuidry>

**Comment by baditaflorin** [comment]
not sure if this can help, for tables https://github.com/mleibman/SlickGrid/

**Comment by thadguidry** [comment]
Closing this issue as no longer needed.  We are going to plan for separating the frontend / backend and leverage a modern frontend framework that the community is comfortable in.
