### ISSUE TITLE
Error: Could not find or load main class com.google.refine.Refine

### ISSUE THREAD

**Issue by rahji** [OpenRefine/OpenRefine#824]
I'm running Ubuntu 13.04 Raring Ringtail and OpenRefine will not start. I have tried the version that's on the website and I have cloned the github repository. Both have the same error: Error: Could not find or load main class com.google.refine.Refine

The documentation says that this is because JAVA_HOME is probably not set. It is set. JDK_HOME points to the same place. I was using openjdk and I just installed Oracle java 7 jdk to see if that made a difference, but the problem is the same. Everything appears to be set up fine and all other java applications work (processing, arduino, javac, etc). 

RUN_CMD looks like this:

/usr/lib/jvm/jdk1.7.0_40/bin/java -cp server/classes:server/lib/\*   -Xms256M -Xmx1400M -Drefine.memory=1400M -Drefine.verbosity=info -Dpython.path=main/webapp/WEB-INF/lib/jython -Dpython.cachedir=/home/rduarte/.local/share/google/refine/cachedir -Drefine.autoreload=true -Dbutterfly.autoreload=true -Drefine.webapp=main/webapp -Drefine.port=3333 -Drefine.host=127.0.0.1 com.google.refine.Refine

and echoing JAVA_HOME from the refine script shows that it is being seen just fine.

Thanks for any info

**Comment by rachitmanas** [comment]
I am getting the same issue while running on windows10. 

![image](https://user-images.githubusercontent.com/70743234/93026345-f8b2a680-f622-11ea-92d6-e8495a9616f8.png)
How can I proceed to solve it for windows? 

I found a solution [here](https://groups.google.com/g/openrefine/c/StB__ItlIVk/m/ezP9zrYcAKkJ) but in my case its already on the hard drive.

Thanks for any help.

**Comment by tfmorris** [comment]
@rachitmanas please create a new issue which describes the problem that you are having rather than using an unrelated, closed issue.
