### ISSUE TITLE
Consider grok and/or morphlines module for processing source files

### ISSUE THREAD

**Issue by Downchuck** [OpenRefine/OpenRefine#826]
Handy for (reasonably) arbitrary streams of text input, typically used for server log data.  Available in the Cloudera Dev Kit, Apache 2.0 licensed.

Morphlines is an ETL library; in this case, it's mostly the extraction we'd be looking at.
http://cloudera.github.io/cdk/docs/current/cdk-morphlines/index.html
http://cloudera.github.io/cdk/docs/current/cdk-morphlines/morphlinesReferenceGuide.html

There's some cruft that's not as desirable, as the lib was designed for the full ETL, whereas we're mostly looking at extraction and basic transformation.

**Comment by wetneb** [comment]
I also fail to understand the suggestion. Given that this issue is already quite old, let's close it.
