### ISSUE TITLE
.json import is not working properly

### ISSUE THREAD

**Issue by Lyubanya** [OpenRefine/OpenRefine#833]
while trying to import .json doc getting a message "Click on the first JSON { } node corresponding to the first record to load." Data is not displayed. Configure Parsing Options is not available.

Please advise. thanks a bunch.

**Comment by tfmorris** [comment]
There hasn't been any activity on this in a long time and we never got a file to reproduce it with.  If you can reproduce it and provide us with a file, please reopen the issue.
