### ISSUE TITLE
Numeric Facets not working on 2.6

### ISSUE THREAD

**Issue by ultraklon** [OpenRefine/OpenRefine#841]
Choose a numeric column, select numeric facets, the automatic facet draw should be shown, instead the message "No numeric value present." is shown there.
In 2.5 this is working ok
##

**Comment by tfmorris** [comment]
@ultraklon Did you ever get any more information on this?

All - I haven't seen this, but we should explicitly test it for the 2.6 release.

**Comment by magdmartin** [comment]
tested again in OpenRefine 2.6 RC1 on a linux machine. The numeric facet works fine.

**Comment by jackyq2015** [comment]
I believe that you missed the step "Edit the Cell"-->"Common Transform"-->"To Number". The idea that the engine dose not aware of the numeric type unless you tell it so. Suggest to close if there is no further information to indicate otherwise.

**Comment by JosefAssad** [comment]
Ah, it might be something local, and it might also be me doing something obviously wrong, but I can reproduce this. Openrefine 2.7 on Debian stable, reproducing my dataset at the bottom of this comment.

Steps to reproduce:

1. Import the dataset
2. Transform the "rooms" column to number
3. Add numeric facet on Rooms column
4. Observe how histogram looks correct
5. Click "change" on the facet
6. Enter `value>2` as GREL
7. Observe that the preview assigns the right booleans
8. Click ok on the facet expression modal box
9. Observe: dataset has not been filtered, the facet box says "No numeric value present"

Dataset:

```
Description,Rooms,Price
Hello world,1,1000000
Foo,2,2000000
Bar,2,500000
Baz,3,3400000
Qux,2,2100000
Walter,5,760000
Rhonda,1,23000
Mickey Mouse,4,450000
```

**Comment by ostephens** [comment]
I think this is the expected behaviour. A 'Numeric Facet' can only represent numeric outcomes - but by changing the facet expression to `value>2` you have a boolean outcome. For this to work, you need to use the 'Custom Text Facet' (or do a text facet and click 'change' and enter the expression)
