### ISSUE TITLE
OpenRefine triggers use of "High Performance GPU" on OS X

### ISSUE THREAD

**Issue by easp** [OpenRefine/OpenRefine#861]
Conditions:
OS X Mavericks (10.9.2), 2012 Retina MacBook Pro
OpenRefine 2.6-beta1
Java 7

Expectation:
OpenRefine, being an app that the user interacts with through a web browser, and doesn't seem to use OpenCL, will not require a high-performance GPU.

Observation:
When OpenRefine is launched, the system switches from the Integrated Intel HD Graphics 4000 to the discrete NVIDIA GForce GT 650M.  The "Energy" tab of the Activity Monitor also shows that "Requires High Performance GPU" is "Yes" for OpenRefine.

Battery life suffers as a result.

With a little research, I learned it might be sufficient to add:
    <key>NSSupportsAutomaticGraphicsSwitching</key>
    <true/>
to Info.plist in the app bundle, but with that setting, the system still switches to the discrete GPU when OpenRefine is launched.  
##

**Comment by wetneb** [comment]
No answer from the initiator after three years, closing. That's a bug of OS X, not OpenRefine.
