### ISSUE TITLE
Close button not displayed properly when selecting Facet Choices as Tab Separated Values

### ISSUE THREAD

**Issue by magdmartin** [OpenRefine/OpenRefine#871]
Using OpenRefine 2.6 beta (with chrome on ubunut machine) the close button in the window Facet Choices as Tab Separated Values is not displayed properly.

![screenshot from 2014-05-05 11 12 00](https://cloud.githubusercontent.com/assets/2589584/2879265/c82b4d02-d467-11e3-97c1-932f124a5a0a.png)

**Comment by tfmorris** [comment]
Fixed in 2.6-rc1
