### ISSUE TITLE
2.6-beta1 does not open browser tab on start on a Mac

### ISSUE THREAD

**Issue by felixrabe** [OpenRefine/OpenRefine#873]
This is on OS X 10.9.2.

Also, the application does not offer a file menu anymore that offers to open a new browser tab.

Workaround: Manually opening 127.0.0.1:3333 works.

**Comment by tfmorris** [comment]
Fixed by c7aa25ccd3f2685bfe655ee3b689c3c47b5ae5cc from PR #1074
