### ISSUE TITLE
Problem running OpenRefine on a VM

### ISSUE THREAD

**Issue by psychemedia** [OpenRefine/OpenRefine#877]
Trying to run OpenRefine on a VM inside Virtualbox using a vagrant/puppet provisioning script cribbed from https://github.com/DataMinerUK/infinite-interns/ I'm getting an error reported as an issue on some old Google Refine forums:

`Something is already running on http://127.0.0.1:3333/ but doesn't seem to be OpenRefine. Maybe a proxy issue?`

This seems to have been an issue previously (eg https://code.google.com/p/google-refine/issues/detail?id=262 and https://code.google.com/p/google-refine/issues/detail?id=436) but the suggested fix (eg setting no_proxy) doesn't seem to work for me?

Also filed as an issue here: https://github.com/DataMinerUK/infinite-interns/issues/44

**Comment by rfc791** [comment]
For me the ```./refine -p 3334``` did not fix it but doing ```./refine -i 127.0.0.1``` did.
