### ISSUE TITLE
TextSearchFacet refreshes unnecessarily

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#896]
When you ctrl/PageUp or ctrl/PageDn into a page, the TextSearchFacet's event handler fires when e.g. the PageUp key is released, causing a complete facet refresh even though the value in the input field hasn't changed.  This is annoying in trivial cases, but can be a real pain if the current facet setup is expensive to compute.

The event handler is set up in TextSearchFacet._initializeUI()

**Comment by gideonthomas** [comment]
Hi @tfmorris,
I recently started experimenting with Open Refine and found that it is a pretty neat tool.
I decided that maybe I should begin contributing code as well and thought that it might be a good idea to start with smaller issues like this one.
May I work on this issue and submit a pr?

**Comment by magdmartin** [comment]
@gideonthomas thank you for proposing your help. We will be more than happy to review your contribution. 

If you have any questions you can post on the [developer mailing list] (https://groups.google.com/forum/?fromgroups#!forum/openrefine-dev)
