### ISSUE TITLE
Handle long column names better in Key/Value Columns dialog

### ISSUE THREAD

**Issue by baditaflorin** [OpenRefine/OpenRefine#898]
![resize posibility](https://cloud.githubusercontent.com/assets/2330999/4147754/d5234208-341b-11e4-8c2c-2bdff2dab527.png)

**Comment by obarabanov** [comment]
@thadguidry is this ticket going to be in review status for some more time, or it can be set as done ?

**Comment by wetneb** [comment]
@obarabanov issues are closed when the corresponding PR is merged (automatically if they have been properly linked, by writing "closes #898" or "fixes #898" in the pull request or commit message).

**Comment by obarabanov** [comment]
ah ok it's like in other collaboration platfrorms. But I haven't linked it properly, anyway.
My idea was just to give idea / to indicate this ticket is taken / being worked on.
Not sure who's going to merge the PR ?

**Comment by wetneb** [comment]
Sure, we can assign you for that.

**Comment by wetneb** [comment]
Closed by #2352.
