### ISSUE TITLE
unable to open "Browse workspace directory"

### ISSUE THREAD

**Issue by ghost** [OpenRefine/OpenRefine#899]
Hi,
i need to install some extensions ( like this https://github.com/giTorto/geoXtension)
i put the unzip directory to the webapp/extensions folder, i reboot refine but nothing happens.
I try to set extensions directory trought "Browse workspace directory" link, but when i clic there no window opens.

**Comment by wetneb** [comment]
This is likely related to a compatibility issue with an extension and not the "browse workspace directory" command itself. If it is, then it is likely to be OS-specific (it works on linux) and we don't know the OS.
