### ISSUE TITLE
Error: Form too large9759838>1048576

### ISSUE THREAD

**Issue by baditaflorin** [OpenRefine/OpenRefine#902]
I have a document with 870000 records, i try to cluster them

i select all, and hit merge selected and close. 

I get this error

Error: Form too large9759838>1048576

**Comment by wetneb** [comment]
I propose to increase the default maximum form size (still letting users define their own in `refine.ini`) and close this.

**Comment by baditaflorin** [comment]
@tfmorris thanks for the enhancement :) Open Refine is the best thing that i found online for Data Cleaning, thanks for making this happen :)

@wetneb at least from my side, that could be useful, so that less persons end up with this message.

**Comment by wetneb** [comment]
Potentially related to #2235.
