### ISSUE TITLE
OSX 10.10 - Refine cannot get to create a project

### ISSUE THREAD

**Issue by JobsiteSean** [OpenRefine/OpenRefine#907]
I am using refine on 10.10 and it is not working I am getting stuck on the create project.  It basically fails to create a project and then hangs.
##

**Comment by Krienas** [comment]
Yesterday I had tried 2.6 beta 1 version on OSX 10.10.2. Had loaded XLS file as data and had created project without problems. Stable 2.5 version was not working, my guess was that too old java version was expected. But that was a guess - didn't try to solve that.

**Comment by thadguidry** [comment]
@JobsiteSean Were you able to resolve this yourself ?  What does the "hang" actually look like , spinner forever, something else ?

**Comment by wetneb** [comment]
No answer for two years, I think it is reasonable to close that.

**Comment by JobsiteSean** [comment]
Yes, it is reasonable.  I have moved jobs since.
