### ISSUE TITLE
Filter Freebase Suggest to Freebase commons types

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#91]
_Original author: iainsproat (June 23, 2010 16:20:09)_

An option or preference could be provided which restricted Freebase suggest to only show Freebase commons types and properties.  This would assist in funnelling reconciled data from users to the Freebase commons, and may help in avoiding confusion with users unfamiliar with Freebase.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=91_
##

**Comment by wetneb** [comment]
This notion of common types and properties seems specific to Freebase, closing.
