### ISSUE TITLE
add javascript support as a language for expressions

### ISSUE THREAD

**Issue by opensas** [OpenRefine/OpenRefine#911]
Besides grel, python and clojure it would be wise to add javascript support.

Sometimes grel is just not enough, and in those cases I turn to python, but there are lots of developers pretty familiar with javascript.

The jvm has a pretty good support for js as a scripting language.

**Comment by thadguidry** [comment]
I guess that would be OK for now.  Although wonder about Java 16 and later https://github.com/mozilla/rhino#java-16-and-later

**Comment by thadguidry** [comment]
Also, Apache Hop uses `org.mozilla.javascript` it seems.
https://hop.apache.org/manual/latest/pipeline/transforms/javascript.html
https://github.com/apache/hop/blob/master/plugins/transforms/javascript/src/main/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesDialog.java#L63

**Comment by wetneb** [comment]
`org.mozilla.javascript` and Rhino are the same thing, I think (or I would be really surprised if Mozilla maintained two different Javascript interpreters in Java)

**Comment by thadguidry** [comment]
Now I am scratching my head...
https://mvnrepository.com/search?q=org.mozilla.javascript
https://mvnrepository.com/artifact/org.mozilla/rhino

**Comment by wetneb** [comment]
I have created an extension which adds support for Javascript as expression language:
https://github.com/wetneb/refine-js
So I am tentatively closing this.
