### ISSUE TITLE
add the ability to create and share functions

### ISSUE THREAD

**Issue by opensas** [OpenRefine/OpenRefine#912]
New feature: let the user define new functinos (using grel, python, clojure), save and load them for reuse in different projects.

Also, adding some way to publish them (perhaps linking to a gist or git repo) so that they can be shared.

**Comment by Ravenwater** [comment]
We (the Data Lake) would be interested in a collaboration mechanism. The use case we are currently working through is working with the Maine CDC on vector-borne disease data and predictive models. We, as a private company, constantly need to issue these FOIA requests, which the folks at the CDC than need to interpret, solve, check for PII leakage, redact, check, double check, export, and email to us. We than need to go through the reverse engineering of what it is that they sent us, check, double check, refine, apply data dictionary, possibly transform, and than use. It would be much more productive if we could collaborate on the data refinement and use the refinement process as a knowledge transfer process, hopefully repeatable and meta-data generating.

**Comment by baditaflorin** [comment]
at least for code, i am now using and saving my code in a google spreadsheet.
If something like this would get implemented, i would use it and share my "code"

denumire	ce face	cod
Count	Numara cate instante ale literei/cuvantului exista	 value.split("#").length()-1 
Sterge ultimul # de la capatul celulei		value.replace(/\#$/, "")

**Comment by Opennat** [comment]
Saved expressions in transform window should have option (or may be separate tab) to use them across all projects, not only in current one.

**Comment by thadguidry** [comment]
This is duplicated in #1232

**Comment by wetneb** [comment]
Let's only keep #1232 as we have more discussion there.
