### ISSUE TITLE
Firefox hanged after clicking on text facet position

### ISSUE THREAD

**Issue by jgrzebyta** [OpenRefine/OpenRefine#919]
Hi,

My dataset is no so large (less 200 rows) but has around 20 collumns. When I wanted to filter some data I selected Text Faced and clicked on wanted item. After few seconds I had an error message about busy script: "Script: http://127.0.0.1:9292/project-bundle.js:xxx". The value of xxx was different number. Also I cannot go to further fages to see the date I have the some error message.
CPU and memory consumption is normal (cpu ~3%; I started wih option -m 3g but in totoal it takes only 1.2G mem). No error messages in a console.

Cheers,
Jacek

**Comment by wetneb** [comment]
Closing this issue as stale, feel free to reopen if it can be reproduced with a recent verison of OpenRefine.
