### ISSUE TITLE
Update Apache POI to 3.10.1

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#925]
We are currently using 3.8 and there have been three releases since then, but 3.11 was just released today, so a safer strategy is probably to update to 3.10.1.

**Comment by jackyq2015** [comment]
The latest version is 3.12
https://poi.apache.org/download.html#POI-3.12

Should we update to this version?

**Comment by jackyq2015** [comment]
done. PR #1029 created for this.
