### ISSUE TITLE
open refine can not detect duplicate entries based on multiple columns.

### ISSUE THREAD

**Issue by daviddou82** [OpenRefine/OpenRefine#930]
I have been doing some web scraping and there were duplicate rows.   Open refine can only detect duplicate entries based on one column at a time.  I followed all the instructions but the results were incorrect compared to when I do it in pandas dataframe.

**Comment by tfmorris** [comment]
What functions and/or menu selections were you using?  What Pandas functions were you using?  Where did you find documentation that the two were expected to perform equivalently?

**Comment by daviddou82** [comment]
the pandas function is: df.drop_duplicates(['col1','col2','col3'])

This function correctly drops rows based on multiple columns.  

I followed the open refine tutorial on this page:
http://programminghistorian.org/lessons/cleaning-data-with-openrefine.html

with no success after tinkers with all the settings.

**Comment by tfmorris** [comment]
I'm pretty sure there's nothing that says OpenRefine is intended to work the same as pandas, so your use of "correctly" and "incorrectly" isn't correct.  OpenRefine works as it is documented to work.

The tutorial you reference says:

> In the above mentioned step, we assume the dataset has a field with unique values, 
> indicating that the entire row represents a duplicate. This is not necessarily the case, 
> and great caution should be taken to manually verify wether the entire row represents 
> a duplicate or not.

That sounds pretty clear in saying that they only expect it to work on a single column (ie the unique ID column).

If you'd like to facet things by the values in multiple columns, one way to do it would be to create a key that is the concatenation of the values in those columns.  You could either create a new column with this key or you could just use a custom facet that creates the key on the fly.

If you think a feature similar to what pandas has is important, you could add your support to the enhancement request #592 that is open for it.

**Comment by ettorerizza** [comment]
Related to #1302
