### ISSUE TITLE
Unable to start OpenRefine

### ISSUE THREAD

**Issue by aprameyarao** [OpenRefine/OpenRefine#931]
Whenever I open the google-refine.exe or the refine.bat files, the command prompt window opens, stays on for a couple of seconds, and then closes.

When I try to use command prompt to open google-refine.exe, I get the following error: Could not find or load main class com.google.refine.refine

When I do the same to open refine.bat, I get: The system cannot find the file refine.ini. Error: Could not find or load main class com.google.refine.refine

refine.ini is in the same directory as the rest of the extracted files. I'm using Windows 8 64-bit.

Please let me know if there is a way to fix this. Thanks!

**Comment by tfmorris** [comment]
Please use the mailing list for help requests and installation issues:
https://groups.google.com/forum/#!forum/openrefine

One likely cause of this is not preserving the directory structure when unzipping the files.
