### ISSUE TITLE
OpenRefine omits <div class="itemfooter"> when fetching URLs

### ISSUE THREAD

**Issue by iblind** [OpenRefine/OpenRefine#932]
Fetching the contents of a URL (http://stripsjournal.canalblog.com/tag/Les%20Unes%20de%20Charlie%20Hebdo), for some strange reason, includes most tags but omits \<div class="itemfooter"\>. I wouldn't have noticed, but this is the one that contains all the requisite information. Am I totally confused (a likely possibility), or is something off here?

i.e.,

instead of 

\<h3\>foo\</h3\>
\<div class="itemfooter"\>bar\</div\>
\<p\>\</p\>

the output is 

\<h3\>foo\</h3\>
\<p\>\</p\>

**Comment by tfmorris** [comment]
Please use the mailing list/group to discuss questions that you need help with or problems that you aren't sure are bugs.  https://groups.google.com/forum/?hl=en#!forum/openrefine

(but first see my StackOverflow answer http://stackoverflow.com/a/27892017/167425)
