### ISSUE TITLE
Large amounts of text content in clustering-dialog-table-container overflows dialog

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#938]
There is limited support for text overflow and styling with tables.
We should switch out the table class to more controllable `<div>'s` so that we can take advantage of `overflow`, `white-space`, and `text-overflow: ellipsis` for the use cases when there is an extremely long text value (such as analyzing Java stack traces with Clustering) in the "Values in Cluster" column.

Example:

```
<div style="position: absolute; left: 20px; top: 50px; 
  width: 120px; height: 50px; border: thin solid black;
  overflow: hidden; text-overflow: ellipsis">
  <nobr>This is the text content of a cluster value - cluster-dialog-entry (title="Use")</nobr>
</div>
```

To hack on this, the Clustering html code and javascript source is here: https://github.com/OpenRefine/OpenRefine/tree/master/main/webapp/modules/core/scripts/dialogs

**Comment by Ravenwater** [comment]
Wouldn't mind jumping in, as I want to learn the ins and out of OpenRefine as I want to use it for the Data Lake, a public data hub for public service analytics.
