### ISSUE TITLE
createColumnsFromImportTest UT failed under JDK8

### ISSUE THREAD

**Issue by jackyq2015** [OpenRefine/OpenRefine#939]
I tried to replace the openjdk6 to oraclejdk8 on my branch. Some UT failed:
https://travis-ci.org/jackyq2015/OpenRefine/jobs/48385702

It's related to the HashMap value iteration order in JDK8 is not historical. In JDK7, the values will be retrieved in the the same order that were inserted. But JDK8 doesn't guarantee this. 
I think if we want to make sure of the order, we should use LinkedHashMap instead of HashMap even for JDK7:
http://docs.oracle.com/javase/7/docs/api/java/util/LinkedHashMap.html

**Comment by jackyq2015** [comment]
I fixed this one my fork, this is is the PR:
https://github.com/OpenRefine/OpenRefine/pull/937

Can someone review it and merge into trunk?

**Comment by tfmorris** [comment]
Hi Qi Cui.  I'm not ignoring you.  I just haven't had a chance to review your PR between snowstorms, the Superbowl (winning!) and real work.  I'll get to it tomorrow.

**Comment by tfmorris** [comment]
Fixed by PR #937
