### ISSUE TITLE
Creating Extensions - API Wrapper

### ISSUE THREAD

**Issue by psychemedia** [OpenRefine/OpenRefine#942]
I'm trying to reverse engineer some [VIB Bits extensions](https://www.bits.vib.be/index.php/software-overview/openrefine) to generate a minimal plugin that will:
- work on a selected column; eg of company codes;
- implement an "Add column by fetching URLs" operation, (eg applying equivalent of `grel:"https://api.opencorporates.com/companies/nl/"+value+"?sparse=true"` to generate the URL)
- parse the resulting JSON [[example](https://api.opencorporates.com/v0.3/companies/gb/00102498?sparse=true)] into several new columns corresponding to elements in the returned JSON feed (for example, the company or registered address)

One of the VIB Bits extensions uses an explicit Jython script to perform an http POST, but all I need is a GET. Is there a way of using an OpenRefine core function as the expression?

```
var HGNC="HGNC";
  while (names[HGNC]!=null)
  {
HGNC+="_";
  }
  ops.push(
{
  "op": "core/column-addition",
  "engineConfig": {
    "facets": [],
    "mode": "record-based"
  },
  "newColumnName": HGNC,
  "columnInsertIndex": columnIndex+2,
  "baseColumnName": column.name,
  /*"expression": "jython:import urllib\nimport urllib2\n\nif value:\n url='http://www.genenames.org/cgi-bin/hgnc_bulkcheck.pl'\n user_agent='Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.56 Safari/537.17'\n headers={'User-Agent':user_agent,'method':'POST','enctype':'multipart/form-data'}\n data=urllib.urlencode({'data':value})+'&format=table&table_case=insensitive&list_format=text&onfail=retain&mode=list&submit=submit'\n req = urllib2.Request(url, data, headers)\n response = urllib2.urlopen(req)\n \n return response.read()\nelse:\n return",*/
  "expression":""
  "onError": "set-to-blank"
}
  );
```

It would be really useful to have a couple of minimal working extensions to crib from in developing new plugins, I think. The VIB Bits d3.js plugin could be a good start for a minimal GUI demonstrating plugin?

More generally, looking at the Javascript code used to implement extensions, it's not a million miles away from the export code. I wonder if it would be in any way possible to export selected operations and automatically compile them into a simple plugin, or at least generate a chunk of code that could be used within a plugin?

**Comment by tfmorris** [comment]
This seems to straddle the line between a feature request and a question.  Questions of this ilk are best suited for the developer's mailing list (where they'll be seen by more people and probably answered quicker).

Some off-the-cuff thoughts:
- the VIBS plugins are all non-obfuscated Javascript, so not much reverse engineering is required (although they're GPL licensed, so no derivatives can be contributed to OpenRefine or anything else where GPL is an incompatible license)
- although the Add column by fetching URL operation is a long running background operation, you should be able to queue the following operations (a series of Add column based on this column operations?) and have them wait until it's done
- you can generate the necessary URL in a new column, use it for your fetch, then delete it afterwards if you want things tidy.

Unless you want to turn this into a feature request for something that's generic enough to be generally useful, why don't we move this discussion to the mailing list to clarify the best approach.

**Comment by wetneb** [comment]
@psychemedia the functionality you were trying to implement should be much easier to set up now that we have a data extension API. The issue for that is #1179 and the protocol draft is here:
https://github.com/OpenRefine/OpenRefine/wiki/Data-Extension-API

**Comment by wetneb** [comment]
Closing this now that the data extension API is around.
