### ISSUE TITLE
Possibility to extend fetching data from URL functionality

### ISSUE THREAD

**Issue by ambodi** [OpenRefine/OpenRefine#944]
We need a service that can fetch data like OpenRefine from a URL but the ability to fetch ```CSV``` and even extracting ```ZIP``` files such as [World Bank's WDI data](http://data.worldbank.org/data-catalog/world-development-indicators).

Can someone provide a bit of code-point on whether this functionality exist or this could be wrapped better as a OpenRefine extension or extending core of OpenRefine? In case you think this is out of the scope of OpenRefine, you could also argue for that. 

Thanks.

**Comment by magdmartin** [comment]
From Refine's home page under create a project you can download a ZIP file with multiple CSV and then select which you want to load in Refine. I've just done the test with the  WDI (CSV)-ZIP (39 MB) file  from the World Bank's WDI data. 

Does this answer what you are looking for?

**Comment by tfmorris** [comment]
As Martin mentions, this functionality is already available in OpenRefine.  You can specify a URL as the input on the Create Project screen and if the URL specifies a zip file (or tar file) it will explode it and let you choose one of the contained files as your data source.

I'm going to close this, but feel free to reopen it with additional details if we've misunderstood your requirements.

**Comment by ambodi** [comment]
Great, guys! 

Can you return the result in  a query too? Sorry if it is too basic, I am a newbie with refine.

**Comment by tfmorris** [comment]
I'm not sure I understand your question, but if the query is URL is an API that returns JSON or CSV (or HTML) and takes query parameters as parameters with the URL, then, sure, OpenRefine can do that too.

These type of questions are really better suited for the group/mailing list (presuming they aren't already covered in the FAQ).
