### ISSUE TITLE
"Select Files To Import" button missing text

### ISSUE THREAD

**Issue by martingraham** [OpenRefine/OpenRefine#947]
![openrefinebug](https://cloud.githubusercontent.com/assets/3490823/6213560/d2dcabde-b5e8-11e4-848d-8de89f6a97ad.png)

After selecting *multiple* files and moving to the Configure Parsing Options page/dialog, there's a small text-less button to the right of the "Start Over" button (circled in red in image). Clicking it reveals it should have the text "Select Files To Import" label.

**Comment by tfmorris** [comment]
This appears to be fixed in the current development version.
