### ISSUE TITLE
Resizable widget does not resize

### ISSUE THREAD

**Issue by simon1tan** [OpenRefine/OpenRefine#950]
When I create a text facet, the widget that is created is not resizable. There are no errors in the console when I attempt to resize. It shows the double arrows but when I pull down, it does not resize. Running in Chrome 40 and IE 11. Element is class="ui-resizable-handle ui-resizable-s" unselectable="on". _UPDATE_ I think this happens when I have lots of data. When I text filter the data, I can resize. I'm not sure why this is, there is no data to refresh. May have more to do with jQuery than anything else.

**Comment by thadguidry** [comment]
@simon1tan if your still having some issue around the Text Facet resizing, please open a new issue.  This one is a bit dated now.  Thanks !
