### ISSUE TITLE
Feature request: text filter exclude

### ISSUE THREAD

**Issue by simon1tan** [OpenRefine/OpenRefine#952]
Provide a text box to for the text filter widget to exclude data instead of include data. I know the facet has an inverse but a little different.

**Comment by ettorerizza** [comment]
It would be a very simple yet usefull enhancement.

**Comment by thadguidry** [comment]
@ettorerizza Something like this would work that says "exclude" where the "undefined" is ?

![screenshot-2017-10-31 clipboard - openrefine](https://user-images.githubusercontent.com/986438/32225316-b95156e4-be12-11e7-8a69-42b0807d094a.png)

For whomever wants to hack and learn... @ostephens !!! :) the code is here:
https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/browsing/facets/TextSearchFacet.java
https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/scripts/facets/text-search-facet.js

```
  elmts.caseSensitiveCheckbox.bind("change", function() {
    self._config.caseSensitive = this.checked;
    if (self._query !== null && self._query.length > 0) {
      self._scheduleUpdate();
    }
  });
  elmts.regexCheckbox.bind("change", function() {
    self._config.mode = this.checked ? "regex" : "text";
    if (self._query !== null && self._query.length > 0) {
      self._scheduleUpdate();
    }
  });
```
Just extend with something like this...and also wire it up properly in other places, just use the regexCheckbox as an example of what to add in other areas.

```
 elmts.excludeCheckbox.bind("change", function() {
    self._config.mode = this.checked ? "exclude" : "text";
    if (self._query !== null && self._query.length > 0) {
      self._scheduleUpdate();
    }
  });
```

**Comment by wetneb** [comment]
@thadguidry you seem to be pretty close to a working prototype of that feature, why don't you propose a PR yourself? I'm sure you can do it!

**Comment by ostephens** [comment]
I'm happy to have a look, but probably not this week now :)

I see this working the same as 'invert' on the facets - you retrieve the inverse set of rows/records to those that would be retrieved usually - i.e. all those that don't match the text in the filter.

What about implementing as an 'Invert' link to keep consistency with the Facet panel UI and terminology?

**Comment by jackyq2015** [comment]
MR merged
