### ISSUE TITLE
Data set joins

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#96]
_Original author: iainsproat (June 23, 2010 17:20:02)_

Feature suggestion: Data across multiple Gridworks projects could be reconciled to each other.  This would allow the data set joins, and augmentation of data (i.e. similar to 'add data from Freebase') across projects.

This requires some more thinking on how Gridworks can accomodate this internally.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=96_

**Comment by antoine2711** [comment]
@thadguidry, @wetneb & @tfmorris: I think we can now close this issue, as the enhancement to the cross() function also fixed the bug. What do you think?

Regards, Antoine
