### ISSUE TITLE
Import JSON Streaming

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#963]
There are two versions of this:
1. Line delimited JSON
2. Concatenated JSON

See http://en.wikipedia.org/wiki/JSON_Streaming

If our underlying parsers don't handle this directly, we could probably transform the sequence of JSON objects into an array.  ie

[{a},{b}] instead of {a}{b} or 
{a}
{b}

**Comment by wetneb** [comment]
Closing as a duplicate of #1135.
