### ISSUE TITLE
Update download page with Java version restrictions for Refine 2.5

### ISSUE THREAD

**Issue by marcobra** [OpenRefine/OpenRefine#964]
Google Refine 2.5 - Stable version

istributor ID:	Ubuntu
Description:	Ubuntu Vivid Vervet (development branch)
Release:	15.04
Codename:	vivid

At startup despite the defined env var:

export JAVA_HOME=/usr/lib/jvm/java-8-oracle

or 

export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

cannot start i get this error:

./refine: 98: [: /tmp/refine.IDTABLX: unexpected operator
Google Refine requires Java version 6 or later. If you have multiple versions of Java installed, please set the environment variable JAVA_HOME to the correct version.

All works fine with git  OpenRefine 2.6 [TRUNK]

**Comment by jackyq2015** [comment]
Yes. that's an known problem and already addressed in trunk. refine script need to support JDK 8. Why don't you just use 2.6 instead of 2.5?

**Comment by marcobra** [comment]
Obviously i use 2.6 now, but please put some note on the download page, people can't guess this issue, i spent 3 hours on 2.5 a various trying to get openrefine working...

So the main problem here is the lack of info on the main page... the instructions are:

http://openrefine.org/download.html

Linux kit, Download, extract, then type ./refine to start.

Thanks

**Comment by tfmorris** [comment]
Thanks for clarifying what you are actually requesting.  I've updated the title of the issue to reflect that.

**Comment by magdmartin** [comment]
I just update the download page.
