### ISSUE TITLE
RDF properties rendered in Protege

### ISSUE THREAD

**Issue by ssridhar21** [OpenRefine/OpenRefine#965]
I am creating rdf data in .ttl format using OpenRefine. When I open the exported .ttl in Protege, object properties are being rendered as annotation properties. Is this due to something OpenRefine is doing, or is this a Protege issue? Any insight would be greatly appreciated.

Here is sample RDF:
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix religions: <http://example.org/religions#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix comp: <http://comp.org/myExample#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<http://comp.org/myExample#0> a comp:Person ;
	rdfs:label "Person 1" ;
	comp:numberOfWives "1"^^xsd:int ;
	comp:profession "Clerk" ;
	a comp:Man .

religions:Roman_Catholicism a religions:Religion .

<http://comp.org/myExample#0> comp:hasReligion religions:Roman_Catholicism .

comp:Corfu a comp:Place .

<http://comp.org/myExample#0> comp:hasPlaceOfBirth comp:Corfu .

<http://comp.org/myExample#1> a comp:Person ;
	rdfs:label "Person 2" ;
	comp:numberOfWives "1"^^xsd:int ;
	comp:profession "Carpenter" ;
	a comp:Man ;
	comp:hasReligion religions:Roman_Catholicism .

comp:Alexandria a comp:Place .

<http://comp.org/myExample#1> comp:hasPlaceOfBirth comp:Alexandria .

<http://comp.org/myExample#2> a comp:Person ;
	rdfs:label "Person 3" ;
	comp:numberOfWives "1"^^xsd:int ;
	comp:profession "Clerk" ;
	a comp:Man ;
	comp:hasReligion religions:Roman_Catholicism .

comp:Malta a comp:Place .

**Comment by tfmorris** [comment]
This sounds like a (potential) issue with the Refine RDF extension.  Could you please report it to them? https://github.com/fadmaa/grefine-rdf-extension/issues
