### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by jansalm** [OpenRefine/OpenRefine#966]
I have clustered some of my columns but it now Just reporting 'no clusters' yet I can see a lot of adjacent entries which look similar.  What am I doing wrong?
Regards
Jan

**Comment by tfmorris** [comment]
Hi Jan.  The email list / Google Group is the best place for questions which aren't actual bug reports.

The readers will probably want to see examples of the entries that you thought should have been clustered, but which weren't, along with the parameters that you used for the clustering.

**Comment by jansalm** [comment]
Sorry Tom
I am very new to this.
Jan

**Comment by tfmorris** [comment]
On Tue, Apr 7, 2015 at 8:35 PM, jansalm <notifications@github.com> wrote:

> Sorry Tom
> I am very new to this.


No problem!  We're just trying to direct you to where you'll get the best
help.

Tom
