### ISSUE TITLE
Release 2.6?

### ISSUE THREAD

**Issue by techtonik** [OpenRefine/OpenRefine#969]
The https://github.com/OpenRefine/OpenRefine/milestones page says 2.6 is 2 years past due. Is there anything possible to bring the release/

**Comment by akuckartz** [comment]
:+1:

**Comment by tfmorris** [comment]
Please use the mailing list / Google group to ask questions.  The issue tracker is for bugs and enhancement requests.

There is a 2.6 beta available on the downloads page and the development team just had a discussion regarding what it would take to wrap up the final 2.6 kit.  Expect to see it soon.

**Comment by techtonik** [comment]
Done. https://groups.google.com/forum/?fromgroups#!topic/openrefine/UnPRxgk84G4

**Comment by shawnholt** [comment]
fyi: https://groups.google.com/d/msg/openrefine/NR4g3hwh1Rs/1m5lQv0LmrgJ
