### ISSUE TITLE
Master Build not taking all setting from refine.ini

### ISSUE THREAD

**Issue by baditaflorin** [OpenRefine/OpenRefine#970]
The error is that even if i put REFINE_MAX_FORM_CONTENT_SIZE=104844576 in refine.ini, in the master build, this setting does not get process-ed 

Step 1 : Get and build the latest Release 

F:\github\OpenRefine>refine build
Buildfile: F:\github\OpenRefine\build.xml
    [mkdir] Created dir: F:\github\OpenRefine\build\server_tests
build_server:
    [mkdir] Created dir: F:\github\OpenRefine\server\classes
    [javac] Compiling 4 source files to F:\github\OpenRefine\server\classes
    [javac] warning: [options] bootstrap class path not set in conjunction with
-source 1.6
    [javac] 1 warning
     [copy] Copying 1 file to F:\github\OpenRefine\server\classes

build_webapp:
    [mkdir] Created dir: F:\github\OpenRefine\main\webapp\WEB-INF\classes
    [javac] Compiling 427 source files to F:\github\OpenRefine\main\webapp\WEB-I
NF\classes
    [javac] warning: [options] bootstrap class path not set in conjunction with
-source 1.6
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 1 warning
     [copy] Copying 1 file to F:\github\OpenRefine\main\webapp\WEB-INF\classes

build_extensions:

build:
     [echo] Building extensions
build_java:
    [mkdir] Created dir: F:\github\OpenRefine\extensions\sample\module\MOD-INF\c
lasses
    [javac] Compiling 1 source file to F:\github\OpenRefine\extensions\sample\mo
dule\MOD-INF\classes
    [javac] warning: [options] bootstrap class path not set in conjunction with
-source 1.6
    [javac] 1 warning

build:

build_java:
    [mkdir] Created dir: F:\github\OpenRefine\extensions\jython\module\MOD-INF\c
lasses
    [javac] Compiling 3 source files to F:\github\OpenRefine\extensions\jython\m
odule\MOD-INF\classes
    [javac] warning: [options] bootstrap class path not set in conjunction with
-source 1.6
    [javac] 1 warning
build:
build_java:
    [mkdir] Created dir: F:\github\OpenRefine\extensions\freebase\module\MOD-INF
\classes
    [javac] Compiling 48 source files to F:\github\OpenRefine\extensions\freebas
e\module\MOD-INF\classes
    [javac] warning: [options] bootstrap class path not set in conjunction with
-source 1.6
    [javac] 1 warning

build:

build_java:
    [mkdir] Created dir: F:\github\OpenRefine\extensions\gdata\module\MOD-INF\cl
asses
    [javac] Compiling 9 source files to F:\github\OpenRefine\extensions\gdata\mo
dule\MOD-INF\classes
    [javac] warning: [options] bootstrap class path not set in conjunction with
-source 1.6
    [javac] 1 warning
build:
build_java:
    [mkdir] Created dir: F:\github\OpenRefine\extensions\pc-axis\module\MOD-INF\
classes
    [javac] Compiling 2 source files to F:\github\OpenRefine\extensions\pc-axis\
module\MOD-INF\classes
    [javac] warning: [options] bootstrap class path not set in conjunction with
-source 1.6
    [javac] 1 warning
build:
build:
BUILD SUCCESSFUL
Total time: 9 seconds

Step 2 : Modify refine.ini and un-comment REFINE_MAX_FORM_CONTENT_SIZE and put value to 100M  

# NOTE: This file is not read if you run the Refine executable directly
# It is only read of you use the refine shell script or refine.bat

no_proxy="localhost,127.0.0.1"
#REFINE_PORT=3334
#REFINE_HOST=127.0.0.1
REFINE_WEBAPP=main\webapp

# Memory and max form size allocations
REFINE_MAX_FORM_CONTENT_SIZE=104844576
REFINE_MEMORY=1400M

# Some sample configurations. These have no defaults.
#ANT_HOME=C:\grefine\tools\apache-ant-1.8.1
#JAVA_HOME=C:\Program Files\Java\jdk1.6.0_25
#JAVA_OPTIONS=-XX:+UseParallelGC -verbose:gc -Drefine.headless=true
#JAVA_OPTIONS=-Drefine.data_dir=C:\Users\user\AppData\Roaming\OpenRefine

Step 3 > Run OpenRefine

F:\github\OpenRefine>refine.bat
16:28:15.993 [            refine_server] Starting Server bound to '127.0.0.1:33
3' (0ms)
16:28:15.994 [            refine_server] refine.memory size: 1400M JVM Max heap
 1304952832 (1ms)
16:28:16.042 [            refine_server] Initializing context: '/' from 'F:\git
ub\OpenRefine\main\webapp' (48ms)
16:28:16.924 [            refine_server] Failed to use jdatapath to detect user
data path: resorting to environment variables (882ms)
16:28:16.927 [            refine_server] Failed to use jdatapath to detect user
data path: resorting to environment variables (3ms)
16:28:16.955 [                   refine] Starting OpenRefine 2.6 [TRUNK]... (28
s)
16:28:23.685 [                   refine] POST /command/core/load-language (6730
s)
16:28:23.710 [                   refine] POST /command/core/load-language (25ms

16:28:23.843 [                   refine] POST /command/core/get-importing-confi
uration (133ms)
16:28:24.007 [                   refine] GET /command/core/get-all-project-meta
ata (164ms)
16:28:24.075 [                   refine] GET /command/core/get-languages (68ms)
16:28:24.258 [                   refine] GET /command/core/get-version (183ms)
16:29:47.191 [                   refine] POST /command/core/load-language (8293
ms)
16:29:47.204 [                   refine] GET /command/core/get-preference (13ms

Step 4 > Cluster and Edit still gets error > 

16:35:57.359 [                   refine] POST /command/core/mass-edit (153537ms)

16:35:57.360 [                  command] Exception caught (1ms)
java.lang.IllegalStateException: Form too large5049917>1048576
        at org.mortbay.jetty.Request.extractParameters(Request.java:1560)
        at org.mortbay.jetty.Request.getParameter(Request.java:858)
        at com.google.refine.commands.Command.getProject(Command.java:171)
        at com.google.refine.commands.EngineDependentCommand.doPost(EngineDepend
entCommand.java:76)
        at com.google.refine.RefineServlet.service(RefineServlet.java:177)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511
)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)

        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:3
88)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.jav
a:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:1
82)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:7
65)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)

        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:1
52)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:54
2)
        at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnectio
n.java:938)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.
java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by baditaflorin** [comment]
Even if i clean and rebuild, with refine file modified i still get the same error 

if [ -z "$REFINE_MAX_FORM_CONTENT_SIZE" ] ; then
    REFINE_MAX_FORM_CONTENT_SIZE="99048576"
fi
add_option "-Drefine.max_form_content_size=$REFINE_MAX_FORM_CONTENT_SIZE"

**Comment by baditaflorin** [comment]
I manage to change only by modify-ing the refine.java file from server/src/com/google/refine/

 final int maxFormContentSize = Configurations.getInteger("refine.max_form_content_size", 99999999);

https://github.com/OpenRefine/OpenRefine/blob/9b2a506caada4ea6d580d2140184fef8caa7566c/server/src/com/google/refine/Refine.java

**Comment by amsardesai** [comment]
Hi, it seems the option is not getting set properly on Windows. #971 may fix the problem, it enables the max form size option on Windows.
