### ISSUE TITLE
Alternative way to extract JSON History

### ISSUE THREAD

**Issue by baditaflorin** [OpenRefine/OpenRefine#973]
![image](https://cloud.githubusercontent.com/assets/2330999/7229195/81e3773c-e769-11e4-899e-db8b0ac7b6da.png)

The classical approach fails to work in this particular case, maybe because i have altered over 6 millions rows.
I am able to get the 28.5 MB file that is generated by get-operations, but rendering the transformed file in the browser does not seem to work. 

After 5 minutes i am able to see the results in the browser, but to copy and paste the result i was not able to do this. 

I have looked at the source code, but i was not able to make a modified version that will process and save directly the get-operations file, converting it from the raw file 

""entries":[{"description":"Mass edit 4964684 cells in column obiect","operation":{"op":"core/mass-edit","description":"Mass edit cells in column obiect","engineConfig":{"mode":"row-based","facets":[]},"columnName":"obiect","expression":"value","edits":[{"fromBlank":false,"fromError":false,"from":["reziliere contract evacuare, pretenţii","pretenţii reziliere contract, evacuare","pretenţii reziliere contract; evacuare","reziliere contract pretenţii, evacuare","reziliere contract evacuare + pretenţii","reziliere contract EVACUARE, PRETENŢII","reziliere contract EVACUARE + PRETENŢII","reziliere contract PRETENTII, EVACUARE","reziliere contract + evacuare + pretenţii","reziliere contract evacuare + pretentii","reziliere contract EVACUARE, PRETEN"

To pretty JSON that i can copy and paste in other projects.

**Comment by baditaflorin** [comment]
I was able to extract the file, to select and paste in notepad ++ the JSON in firefox. 

Google Chrome seems to handle the conversion in different way, and fails to load. 
I will close this issue

**Comment by baditaflorin** [comment]
what is the process that handles the data conversion ? Can it be linked diretly, to create a save as archive of the final JSON file ?

**Comment by tfmorris** [comment]
Please ask questions on the appropriate mailing list.
