### ISSUE TITLE
Defined a guideline for translation

### ISSUE THREAD

**Issue by magdmartin** [OpenRefine/OpenRefine#974]
Drop down menu and the interface in general have been defined to accommodate English content. With more translation of OpenRefine, some of the string overflow the menu size. 

For example: 
![screenshot from 2015-04-20 08 51 35](https://cloud.githubusercontent.com/assets/2589584/7230391/53853c78-e73b-11e4-86ff-612f938211d3.png)

I haven't been able to find the same issue with the Italian translation, and I personally can't tell if this is happening with the Chinese one. 

Can we make the drop down menu responsive to its content? Should we defined some type of guideline if the content is too long?

**Comment by magdmartin** [comment]
Do we want to fix that for the next release? 
If so is it better to update the French translation to fit in the menu or fix the UI to accommodate the translation length?

**Comment by tfmorris** [comment]
I'm happy to accept low risk fixes for this for 2.6.  Not sure whether 2.6 or 2.7 is "next" in this context.

A combination of making the menus size to their contents and keeping the translated text as short as possible is probably the correct solution for this, but without looking at it I have no idea how hard it would be to fix the flyout sizing.

**Comment by magdmartin** [comment]
I understand by minor fix changes in the actual translation to make it fit the actual menu size. 

Bumping it to 2.7 to change the menu size.

**Comment by magdmartin** [comment]
I just test with master today (b51dbdcbf223)  and this is still an issue. It also impacts the Portuguese (Brasil) translation.

**Comment by thadguidry** [comment]
The best way to handle this is with Tooltips as other applications do.  Mozilla provides a guide and good practice about Tooltips in trees, such as what we have here in our menu tree. https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/PopupGuide/Tooltips
We'll just need to improve our interface with Tooltip option and this issue goes away.  We can even have a user preference for Tooltips On/Off for folks that don't want any annoyance.

**Comment by wetneb** [comment]
Now that #2455 changed the word wrapping, can we close this @magdmartin? Or do you think we should also/instead let menus expand horizontally?

**Comment by magdmartin** [comment]
I think the word wrapping is a nice fix.
