### ISSUE TITLE
Ability to set clustering to none as first option

### ISSUE THREAD

**Issue by baditaflorin** [OpenRefine/OpenRefine#975]
I am working now with a 16 Million Rows database, and i lose 50 seconds each time i load the clustering dialog because is trying to compute the binning,fingerpring for 800.000 different objects that my database have. , even if i already did this, and now i want to do binning,n-gram-fingerprint or another method. 

17:48:43.159 [ compute-clusters_command] computed clusters [binning,fingerprint] in 47728ms (45453ms)
17:49:33.383 [ compute-clusters_command] computed clusters [binning,ngram-fingerprint] in 95677ms (50224ms)

After the first time, when i do the binning fingerprint, and i want to do another clustering, let`s say metaphone3, it`s a period of around 130 seconds, the different from when is computing the binning,fingerprint (50 seconds ) and metaphone3 ( 180 seconds ) when it`s says :

No clusters were found with the selected method
Try selecting another method above or changing its parameters

Because it had computed for the first option, and the second option is still waiting, and, if the user is not aware, he may think that even the second or third option does not compute any clusters

**Comment by tfmorris** [comment]
The misleading message sounds like a bug to me, so I've created a separate issue for it. #976

**Comment by thadguidry** [comment]
Closing since issue resolved in #976
