### ISSUE TITLE
Clear misleading "no clusters" message while algorithm is running

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#976]
Per #975 the clustering dialog shows a misleading stale "No clusters found" message while it is calculating clusters using a new algorithm.  The message should be cleared/changed while the operation is pending.

**Comment by magdmartin** [comment]
Tested on OpenRefine2.6 RC1 and looks closed to me.
When changing clustering method the "No clusters found" is replaced by a "clustering" message with a spinning icon.
