### ISSUE TITLE
RDF extension 

### ISSUE THREAD

**Issue by simpleperson200** [OpenRefine/OpenRefine#986]
Hi,
I'm using RDF extension but when I add prefix I can't press advanced...  option it's lock 
![screen shot 2015-04-24 at 16 25 35]
(https://cloud.githubusercontent.com/assets/11664585/7322228/a18157ac-ea9e-11e4-8c19-5d7d49ef2c9f.png)

**Comment by tfmorris** [comment]
The issue tracker for the RDF Extension is here: https://github.com/fadmaa/grefine-rdf-extension/issues
