### ISSUE TITLE
Clustering doesn't honor facet (text filter) configuration

### ISSUE THREAD

**Issue by baditaflorin** [OpenRefine/OpenRefine#987]
I have a 6M rows file, and i do a text filter, and end up with only 8000 rows. 

If i try to cluster them, i still have to wait around 10-15 seconds, because it`s loading or processing the whole database.

I tried to export and load only the 8000 rows, and then, it only takes 500ms to compute the clusters.

**Comment by tfmorris** [comment]
Does this only happen with the text filter or all types of facets?

**Comment by wetneb** [comment]
Sounds like a pretty important bug!

**Comment by thadguidry** [comment]
Tested again just now with 3.3-beta and works fine...

![Annotation 2019-12-20 131344](https://user-images.githubusercontent.com/986438/71285827-bfffce00-232b-11ea-859b-a5c959ec733e.png)
