### ISSUE TITLE
Changes to the 'AuthSub' authorization method for web applications

### ISSUE THREAD

**Issue by jandiolola** [OpenRefine/OpenRefine#988]
Hello,

I'm fairly new to integrating the Refine tool for work, and I recently received an error message while trying to sign in and authorize my account to access documents. I was re-directed to a page stating the change from AuthSub to OAuth 2.0. Are there updates for this issue?

**Comment by tfmorris** [comment]
Access what documents where?

**Comment by jandiolola** [comment]
My spreadsheets on my Google Drive account

**Comment by tfmorris** [comment]
I'm guessing that you are using Google Refine 2.5.  This was fixed by bf2f775c0bf0e12595ad20637bc0ddfc8eefca04 over a year ago and is available in the OpenRefine v2.6 beta 1 kit.  It will be in the v2.6 kit out shortly.

If you are using a more recent version of Refine, please re-open this.
