### ISSUE TITLE
Freebase reconciliation service doesn't work

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#989]
[This was #805, but that got hijacked for a new feature request.]

The Freebase reconciliation service was proxied through the freebaseapps.com domain (ie Acre) which has been shut down.  Freebase itself will be shutdown shortly, so all the machinery associated with it should be removed.

I think most of this has been done, but we need to double check that there are no remaining loose ends.

**Comment by jackyq2015** [comment]
PR created. 

The code was deployed under:
http://208.75.74.214:3333/

Please help to verify if it works properly and also check the reconsideration part. If need to install some extension, let me know.
